---
title: 警惕 Misinformation
author: Guanghua Mao
date: '2021-03-16'
slug: '153'
categories:
  - Original Articles
tags:
  - Conservative
  - Culture
  - Evolution
  - Propaganda
  - Psychology
---

> 人类在恐惧与兴奋之间摇摆的天性让我们陷于经济困境，没有任何经济模式能够抑制这种情况的出现却不带来严重的后果。监管是人们所谓能有效解决当前危机的方案，但它在历史上从未能够消除过危机。-- 格林斯潘

最近小镇上又在流行骗老人的理财活动，大概意思是投资800元去购买非洲公司的股票，半年之后可以分得20万。毫无疑问，这是一个骗局，但是在我和我的家人的对话中，发现他们或多或少都在受虚假消息的影响---研究生毕业年薪50万，考了注册会计师证年薪百万，投资虚拟货币可以财富自由，电动车比汽油车好，谁谁谁给领导敬酒马上就升职加薪，谁谁谁做外贸一年挣一个亿。经历过这一切的人当然能一眼看出这些说法的荒谬。只需要稍稍做一点研究就能够识破其中的猫腻。尽管我能够从中看出许多说法的荒谬，但毫无疑问，我肯定持有许多荒谬的观点，也被各种虚假的文字、音频和视频欺骗过，比如我就买过 iPad，买回来之后发现毫无用处，基本在吃灰。对于各种各样的信息如何误导人们作出决策，我目前还没有一个清晰的看法，人的行为决策不可能仅仅基于过去发生的事，而必须同时基于对未来的预期，也必须考虑他人的想法和可能的行动，过去、未来和他人构成了影响人们决策的外在因素，而人类的三层大脑---爬行脑、情绪脑和理性脑是塑造人们行动的内在因素。

各种各样的信息通过塑造过去、未来和他人的叙事来影响我们的爬行脑和情绪脑，从而误导我们作出决策。对于购买决策，我有一个简单的建议---不看商品宣传片，也不要管商品利益相关方的言论诱导，只选择在自由竞争的市场制度下经受考验且符合自己需求的商品。但是对于更加广泛的话题，比如历史、经济、政治、投资、社会和技术等话题，这一建议就显得不够用了，对于远超在远离日常尺度因而难以建立直觉的系统级问题上，不仅仅是普通大众，即便是一些专家或者极其聪明的人也可能犯傻。对于这些话题，我有另外一套建议：从演化、到系统、再到统计、最后到复杂思维的一整套逻辑链条来避免自己被戏耍，对于任何故事都完全不要相信。

最后提一个问题：周总理真的说过“为中华之崛起而读书”这句话吗？