---
title: 乌克兰大饥荒85年 苏联一直掩盖真相
author: 白桦
date: '2022-01-16'
slug: '370'
categories:
  - Translation Articles
tags:
  - History
---

[Source](https://www.voachinese.com/a/soviet-Ukrainian-famine-20181124/4672229.html)

在纪念乌克兰大饥荒85周年之际，一批刚公布的解密档案显示，苏联共产党政权曾极力掩盖大饥荒真相，但西方仍然通过各种渠道获得了有关大饥荒的消息。一直到苏联解体前夕，大饥荒议题长期作为禁区被禁止提起和讨论。

解密档案 精心安排不让访问者看到饥荒

乌克兰在星期六纪念大饥荒85周年。乌克兰国家安全局档案部门为此公布了一批解密档案，这些资料讲述了当时在乌克兰的外国人所了解的大饥荒的景象，以及苏共政权如何通过各种手段掩盖大饥荒真相。

30年代的大饥荒爆发期间，法国前总理和激进社会党领袖赫里欧曾访问乌克兰。苏共当局谨慎认真安排了赫里欧的旅行路线，不让他看见那些饥荒遍野的乌克兰农村，而是让这位法国著名政治家参观一些样板式的集体农庄。

策略奏效 法国政治家为苏联辩护

苏共当局还下令严禁衣衫褴褛，外表难看的那些挨饿中的农民接近赫里欧，同时也不让在乌克兰定居的法国侨民接触赫里欧。

苏共当局的努力获得了效果。赫里欧返回法国后，针对当时西方世界流传的苏联爆发大饥荒的消息，赫里欧为苏联辩护说，他没有看到苏联爆发大饥荒的任何证据。

日本公使感受反差 工厂高楼和瘦弱农民

一份告密报告讲述了日本公使在乌克兰旅行的印象。这名日本外交官说，与其他地区的苏联农民相比，乌克兰农民更显得衣着破烂和瘦弱疲惫不堪，与乌克兰工业区顿巴斯正在兴建中的大型工厂和高楼大厦，以及住宅宿舍相比，这两种景象形成了很大的反差。

德国公使 饥荒发生在产粮区 多数村民饿死

德国在乌克兰的总领事馆和外交官是苏共秘密警察的重点监视目标。但德国对乌克兰大饥荒所掌握和了解的情况也最详细。秘密警察的报告谈到了当时德国公使与波兰和日本在乌克兰外交官有关大饥荒的讨论。

在所截获的德国公使1933年发回柏林外交部的报告中提到，大饥荒灾难已经席卷整个乌克兰，最主要的特点是，所有的饥荒都发生在那些被称为黑土地的产粮区。乌克兰农村中80%的村民都已饿死。

当局极力掩盖 饥荒消息仍能穿透铁幕

乌克兰国家安全局档案机构负责人科古特说，公布的这些档案许多都来自秘密警察在外国总领事馆和其他外国驻乌克兰机构中卧底线民撰写的报告，还有其他告密材料，以及秘密警察在大饥荒期间对在乌克兰活动的西方外交官和其他外国人的监视和分析资料。

科古特说，公开的这些解密档案显示，虽然苏共当局极力掩盖大饥荒真相，但有关大饥荒的消息仍然能穿过铁幕让国际社会知道。

苏共称饥荒报道是谎言 梵蒂冈知道真相

苏共当局当时曾把西方对大饥荒的一些报道称作外国代理人凭空捏造的谎言。十月革命后，苏联国门被逐渐关死。到上个世纪30年代时，就如同今天世界很难了解朝鲜内部所发生的事情一样，外部世界当时都无法弄清苏联国内发生的事件。

但西方世界还是能通过许多渠道了解真相。除了外交官的报告外，梵蒂冈也通过在乌克兰境内的天主教徒知道了大饥荒。

奥地利主教募捐 工程师拍下第一手资料

乌克兰通讯社说，当时的奥地利维也纳红衣主教因尼查可能是世界上第一个公开呼吁帮助大饥荒中乌克兰农民的知名人士。因尼查呼吁国际社会为乌克兰提供援助，并组织了募捐活动，他还特别在维也纳召集了有关的国际讨论会。

因尼查的活动得到了奥地利化学工程师维尼伯格的支持。维尼伯格当时在莫斯科郊外的一家工厂中任职，因为工作关系，他曾多次前往乌克兰东部工业重镇哈尔科夫地区出差。维尼伯格当时拍下了大饥荒的许多第一手照片，这些照片被奥地利外交官带出苏联，作为大饥荒的证据为因尼查主教的募捐活动提供了支持。

苏联禁止讨论大饥荒

乌克兰媒体说，苏联时代，在乌克兰，大饥荒作为禁区，当局禁止人们提起和讨论这个话题。直到80年代末时，苏联国内才有人开始研究大饥荒，一些相关资料开始陆续公开发表。但最近几年来，国际上一些有关乌克兰大饥荒研究的重要书籍再次被俄罗斯当局列入到了所谓的极端主义刊物名单中。

时事评论人士伊赫洛夫说，在他的印象中，苏共当局一直试图让人们忘记大饥荒。

伊赫洛夫：“大饥荒议题虽然不像涉及国家机密那样有遭到严厉处罚的风险，但围绕这个议题在前苏联是一片寂静。我的记忆中，可能只有一部变相提到大饥荒的文学作品，作者是一位农民作家。还有一部作品，讲的是二战结束后两年爆发的饥荒。可能这两位作者都不是知名作家，影响力不大，当局才允许他们的作品出版。”

让世界知道真相 多国谴责共产主义罪行

乌克兰目前正在推动让世界更多的国家承认大饥荒是对乌克兰人的民族灭绝行动。波兰参议院在乌克兰大饥荒85周年之际特别通过决议谴责共产党政权，同时缅怀饥荒受难者。波兰参议员们说，应该让世界上更多的人知道大饥荒悲剧和共产主义本质。

刚刚访问乌克兰的斯洛伐克总统基斯卡星期五在基辅表示，乌克兰大饥荒是一场严重的犯罪行为，大饥荒中饿死的人数甚至超过了今天斯洛伐克人口数量。