---
title: 褚老师另类职场课（7）
author: Guanghua Mao
date: '2021-10-06'
slug: '319'
categories:
  - Original Articles
tags:
  - Job
  - Business
  - Politics
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---



# 提升影响力，管理权力关系

影响他人是一门很重要的技术


影响力悖论：想改变别人，必须先改变自己

如果想要提升影响力，将自己的影响力最大化，首先要学会自我管理。

自我管理：

1. 自我观察：换成第三方的视角来看待自己，演讲想要自然，引入一个第三方，让他来评论自己的表现和情绪，把自己的整个心路历程描述出来。从第三方来看自己的行为和表现

2. 自我控制：不要随时随地表达自己的真实情感

3. 行为选择：有意识的选择该做什么，不该做什么。


影响力过程：（你，影响策略，影响对象，期望行为，你的目标）

1. 无脑行为是会伤害所有人。

影响不等于控制，影响是为了实现自己的目标，注意和控制类游戏的区别。控制类游戏常常会适得其反。



# quote


绅士就是从来不无意伤害到别人感情的人。

事实会出错，而观点只是不同。

如果被逼入了一个小角落，就要占领这个小角落，此时进入大众市场已经太迟了。




换位思考（再多强调也不过分）：

站在他人的角度来看待食物。

说明共同目标，预见可能问题，计算杠杆等式，征求对方意见（带来三个解决方案，让领导挑）。

专注于你的目的，不要较劲，不要要面子，也不要当烈士。




常用影响力工具

1. 直接影响力

2. 间接影响力

四个工具：

1. 观察等待，仔细听取他人的发言，找到时机表达自己的观点，如何插话：如果我能补充的话，……。找准时机是非常重要的能力。
不能一直观察等待，仍然要吃手
职场小白常犯的错误，就是当点头侠，从来没有发言过。

2. 提问聆听，很多人犯的错误就是太想表达自己的观点，没有仔细听对方在说什么，尤其是很多人在面对一个大领导，或者自己没自信的时候，脑子里面都在想自己想要说什么，而没有注意到他人。聆听很重要。提问分两种，一般疑问句和特殊疑问句，要尽量问特殊疑问句，层层递进，一定要问到细节。你能不能给我讲懂一个我不太理解的事情。

2.1  探索型问题

2.2 包容型问题，为了把在场的人引入讨论之中所设计的问题

2.3 软化型问题，用提问的方式把自己的问题进行软化

3. 说服教育，小技巧---

3.1 做好“家庭作业”

3.2 说话

3.3 展示自信

3.4 别不懂装懂

3.5 相信你的“产品”

3.6 了解你的听众

3.7 找共鸣

3.8 制造惊喜

3.9 引入听众参与

3.10 别忘了间接技巧



4. 明令执行（中高层）





# 管理权力关系

1. 向上影响，管理老板：

1.1 接受你的老板有权指挥你这一事实

1.2 不要期望老板是完美的

1.3 研究老板的管理风格和喜好

1.4 试图让你的老板加分

1.5 永远不要和别人抱怨你的老板

1.6 时不时地真心表扬一下他

1.7 别忘了老板的老板，真正决定你前途的人

如何管理高管：

1.1 永远别说你不能

1.2 别啰嗦

1.3 别指望具体指示

1.4 他提到的一个很虚的事情，要能落实，成事，不要以为他没有强调就忽略，不要错过机会

1.5 被骂了别往心里去

1.6 别自大

1.7 自信，充分准备

1.8 保持幽默感




2. 横向影响，管理同事：

2.1 留意帮助同事的机会

2.2 回电话，回邮件，按时完成任务和承诺

2.3 别拿同事当心理医生

2.4 别当众自吹，这会招人反感

2.5 友好礼貌，就算是对傻逼

2.6 直接说明疑虑，不要背后说，不要兜圈子

2.7 用成年人的态度对待处理困难和矛盾

3. 向下影响，高效领导：

3.1 记住：你是经理，不是皇帝

3.2 被敬佩很重要，被喜欢不重要

3.3 管理是一门需要学习的手艺

3.4 重视包容性杠杆的力量

3.5 成就你的部下




# quote：

我一直觉得，勤奋只不过是无所事事之人的避难所



















