---
title: 我们到底可以向其他人学习什么？
author: Guanghua Mao
date: '2021-03-17'
slug: '156'
categories:
  - Original Articles
tags:
  - Psychology
  - Prediction
  - Personal
  - Investment
  - Insights
  - Evolution
---

在日常的聊天和各种新闻中，我们经常会被引导去学习一些成功的榜样。相信不少人都深受其害，明明按照别人的的做了，可为什么结果这么差？孔老夫子也曾经说过：“三人行，必有我师焉。”向他人学习看来是古已有之的传统。但乔布斯也曾经说过：“能工模型，巧匠窃意。”同样是向他人学习，其效果也有高下之分。但是我很想提出一个问题：“我们到底可以向他人学习什么？”


如果从经济学的视角来看，只是粗糙地模仿他人的产品或者服务，其实是一个馊主意，因为模仿他人的产品无非两种结果，一个是他人的产品或服务很好学，你学成功了，比如开个餐馆、开个宾馆，可一个产品或服务很好模仿，那么一定会有大量的人模仿成功，结果竞争一定会很激烈；另一个是他人的产品或服务很难学，怎么都学不成功，比如微软的操作系统，我们国家都花了无数的钱去研发国产的替代操作系统，但没有成功，还有微信、茅台、劳斯莱斯、LV，微信自从诞生开始就有着无数的竞争对手，只可惜由于网络效应，所有的竞争对手都失败了；而像茅台等产品由于有着特定的文化和口味偏好，至今也没有成功的挑战者；作为炫耀式消费符号的劳斯莱斯、LV的地位更是难以撼动。当然在某一个产品的市场在快速增长的时候，是可以考虑作为极早期进入者进入市场，但最终还是要面临一片红海的厮杀。

从复杂系统的角度看，很多人物的成功是源于各种力量交相汇聚的结果，并非单一因素可以解释，比如王宝强、英美宪制，如果只是简单的模仿其中几个因素，完全达不到效果。

从概率和统计的角度看，很多人物的成功只不过就是运气，比如拆迁户、中彩票的、蒙对了一只牛股的股民，这完全没法复制。

从生物多样性的角度看，很多人成功很多源自先天，比如乔丹、爱因斯坦和患有阿兹海默症的犹太人，我不太清楚学习这些人什么？

源于人类的认知局限和认知偏差，人们总是愿意简单地模仿和听信于成功人士。但我认为，除了那些在演化-系统-统计-复杂科学上有坚定的理论作为支撑的观点，其他的来自成功人士的成功经验，我们恐怕没法模仿，甚至坚决不要模仿，以免被误导和操纵。更重要的是，由于统计学的内在局限性---无法根据底层条件的改变和临界值的出现而预测未来的情况。很多只是简单基于统计学的看法也不见得靠谱。

---

# 为什么资本家会反对资本主义？

[Source](http://headsalon.org/archives/3371.html)

关于市场制度的种种争议中，一个有趣的场景是，许多坐在书斋里的经济学家都在不遗余力的为市场制度辩护，反倒是不少在市场中如鱼得水、依靠市场取得了巨大个人成就的资本家，却常常从整体和根本上（而不只是某些细节上）指责和攻击市场制度。

比如最近，杰里米·格兰瑟姆（Jeremy Grantham）这位管理着全球最大基金之一GMO的大资本家，在其致投资者的信中，指出资本主义制度有着内在的自我毁灭倾向，因而必须由政府干预来预防和矫正，否则危机和崩溃难以避免；这种说法并不新鲜，不过是马克思观点的凯恩斯版本，多年来，末日博士鲁比尼（Nouriel Roubini）、投机大鳄索罗斯（George Soros），都在不断宣扬这些观点。

对于反对市场制度，尤其是反对现有货币、资本和金融制度的人来说，大资本家们的言论是个有力的佐证：连市场制度的顶级参与者都说它不好，还能有假？难道书斋里的经济学家比他们更了解真相？确实，这种说法看上去很诱人，但假如我们仔细推敲一下便会发现，这种说服力只是直觉上的，而直觉并不总是靠得住的。

特别是在社会和市场这样的复杂系统上，特别是在制度这样的复杂问题上，个体经验和直觉多半靠不住，即便是参与范围最广泛、经验最丰富的参与者；在类似的复杂系统中，个体的成功经历充其量只能证明，他在如何取得个人成功上可能拥有一些正确的知识，而丝毫不能证明他对整个系统的运行原理拥有任何可靠的知识。

这一点即便在不那么复杂的系统中同样成立，比如一个顶级球员未必是个好教练，更未必是个合格的足联规则委员会主席，这三者所需要的恰当知识，不在同一层次上；然而在公众的讨论和评价氛围中，却总是有一种以个人成就为取信标准的倾向，该倾向不仅存在于公共话题中，在关于职业、经营、投资、修养、乃至价值观的种种话题中，都可见到它的影子，其最集中表现，便是近年来日益兴旺的成功学。

成功学的基本假定是：每项成功经历背后，都隐藏着一些有价值的东西，值得探索和学习；如果“有价值的东西”仅仅是指有助于获得成功的经验或启示，那自然没问题，可实际上，许多人将之等同于“关于世界的正确知识”，那就错了；首先，成功不必以拥有正确知识为前提，其次也更重要的是：许多成功的必要前提恰恰是拥有错误的知识！

最简单的例子是彩票，许多热衷于买彩票的人，其热情都来自对中奖概率的错误知识，错误的认为按某种方法选择号码会提高自己的中奖率，进而认为自己的预期收益率高于零，而拥有正确知识的人，预期收益率总是负的，因为总奖额总是小于销售额，所以对于后者，仅当其风险偏好很高时，才会买彩票，这样，在全部中奖者中，拥有错误知识者的比例，必定高于普遍水平。

彩票只是个极端案例，但其所揭示的原理适用于许多高风险行业，在这些行业中，脱颖而出的成功者，更可能是那些对许多风险十分无知的人，越是辉煌而不可思议的成功，所对应的风险无知者比例越高，英特尔前总裁格鲁夫（Andrew Grove）的名言很好的抓住了这一点：只有偏执狂才能生存。

当然，风险无知在成就极少数成功者的同时，也让大批人获得了负收益，所以尽管前者在传播学上具有压倒性的影响，但至少对于客观的探究者，用统计手段还是可以识别出错误知识的负面价值的，这没错，然而，还有另一类错误知识，它对成功的正面影响甚至在整体上都不会消除，因而其正确性完全不能用成功来衡量。

比如，我错误的认为，我的一举一动都会被全知的上帝看到，而他会因我的恶行而惩罚我的子孙，于是我小心谨守道德规范，善待邻居，从不欺诈客户，并因此而成为一名信誉卓著的成功商人；显然，上述错误知识在我的成功中起了关键作用，但它仍是错误的，并且这一错误不可能从对成败的观察与统计中被识别出来。

实际上，从成功这样的功利性目标出发，人们有充分的理由保留某些错误知识，这是因为人类认知能力的局限性；在许多情况下，从正确知识得出有利行动的逻辑链无法在此认知局限之内建立，因为该逻辑链所涉及的知识极度庞大，个人难以获得，或其中逻辑结构高度复杂，人脑难以处理，此时，假如一个简单却错误的知识能以简洁的多的逻辑链导出同样的有利行动，它就是“值得”被保留的。

当然，这个“值得”是基于个体功利性，而当我们以求真的姿态来考察社会这个复杂系统的运行机制，试图回答市场制度是否具有内在自我毁灭倾向之类的问题时，这些对个体成功有利的知识，假如已被更广泛而深入的研究证明是错误的，自然要加以摈弃，不能仅仅因为它出自成功人士之口便甘之如饴。











