---
title: Income Inequality Isn’t The Problem
author: David R. Henderson
date: '2020-10-17'
categories:
  - Translation Articles
tags:
  - Economics
  - English
  - Politics
  - Sociology
slug: '64'
---

[Source](https://www.hoover.org/research/income-inequality-isnt-problem)

[Video](https://www.youtube.com/watch?v=1e35Vf-9n8E&list=WL&index=6)


If you’ve been paying attention to economic controversies in the last decade, you may have noticed many discussions about economic inequality. It’s a hot topic and several people believe that the alleviation of poverty requires a substantial reduction in inequality. For example, Thomas Piketty, the French economist whose book Capital in the Twenty-First Century became a bestseller, understands the distinction between income inequality and poverty but sometimes uses the terms interchangeably, as if one necessarily begets the other. But inequality of income and wealth can remain high or even increase while poverty is decreasing.

In order to understand economic inequality, we need to ask a few questions. First, are there good kinds of economic inequality and bad kinds? Second, is it a good idea, as many policymakers and even some economists insist, to reduce inequality by taxing those at the top end more heavily? Third, has poverty been increasing? Fourth has economic inequality been increasing?

To answer the first question, let us consider two historical figures of twentieth-century American history. The first came to prominence in the late 1940s, when he invented a light one-man chainsaw, and sold more than 100,000 of them at a price that made him quite rich. That added slightly to wealth inequality. But although the wealth gap between this man, inventor Robert McCulloch, and his customers was higher than it was before, the customers got a product they valued that made their lives easier. In economists’ terms, the wealth of these customers increased slightly. Is that increase in wealth inequality a problem? When I’ve asked college students this question, the vast majority says no—and I agree.

Now let’s consider the second figure. In the early 1940s, as a Congressman from Texas, this man defended the budget of the Federal Communications Commission when a more senior member of the House of Representatives was trying to cut it. So the FCC owed him a favor. One FCC official suggested the politician have his wife apply for a license for a radio station in the underserved Austin market. She did so and within a few weeks, the FCC granted her permission to buy the license from the current owners. She then applied for permission to increase its time of operation from daylight-hours-only to 24 hours a day and at a much better part of the AM spectrum—and the FCC granted her permission within a few weeks. The commission also prevented competitors from entering the Austin market.

These moves made Lyndon Johnson and his wife very rich. When he ran for President in 1964, the radio station accounted for over half of his $14-million net worth. This increase in his wealth added slightly to wealth inequality. But customers in the Austin market were, due to the FCC restrictions on further radio stations, slightly less well off than if more stations had been allowed. When I tell this story to college audiences and ask them if they think there’s an important difference between McCulloch’s and Johnson’s methods of increasing wealth inequality, virtually all of them do, and few will defend the latter way.

How does this relate to wealth inequality? In any given year, there isn’t just one inventor or innovator. There are thousands. So each one’s success increases wealth inequality a little but also improves the well-being of tens of millions of people who are less wealthy. Also, as other competitors enter the market and compete with the innovator, they drive down prices and make consumers even better off. Indeed, Yale University economist William D. Nordhaus has estimated that only 2.2 percent of the gains from innovation are captured by the innovators. Most of the rest goes to consumers.

In short, there is indeed a distinction between good economic inequality and bad. Entrepreneurial innovation that improves the lives of consumers is good; using political pull to transfer wealth is bad.

Consider another example—two of the richest people in the world are Bill Gates and Carlos Slim. Gates got rich by starting and building Microsoft, whose main product, an operating system for personal computers, made life better for the rest of us. Would you have a well-functioning personal computer if Bill Gates hadn’t existed? Yes. But his existence and his clear thinking early on hastened the PC revolution by at least a year. That might not sound like a lot, but each gain we consumers got from each step of the PC revolution occurred a year earlier because of Bill Gates. Over 40 years, that amounts to trillions of dollars in value to consumers. The market value of Microsoft is currently just shy of \$700 billion. Assume that Microsoft was much better than other innovators at capturing consumer value and captured fully 10 percent of the value it created, rather than the usual 2.2 percent. That means it has created almost \$7 trillion of value for consumers over those forty years.

Mexican multi-billionaire Carlos Slim is currently the seventh-richest man in the world. He got rich the way Lyndon Johnson got rich. The Mexican government handed him a monopoly on telecommunications in Mexico and he uses it to charge high prices for phone calls. Slim is clearly exacerbating income inequality in a way that makes other people poorer.

Thomas Piketty concedes that it matters how one gets rich, and that many rich people made their money legitimately. But when it comes to advocating policy, he forgets that important distinction. He advocates an annual “global tax on capital” with rates that would rise with wealth. “One might imagine,” he writes, “a rate of 0 percent for net assets below 1 million euros, 1 percent between 1 million and 5 million, and 2 percent above 5 million.” He adds, “one might prefer” a stiff annual tax of “5 or 10 percent on assets above 1 billion euros.”  

But such a policy doesn’t discriminate between those who accrued their wealth honestly and in ways that ultimately contributed to the social welfare and those who got rich through government power. Here’s Piketty’s response to that point: “In any case, the courts cannot resolve every case of ill-gotten gains or unjustified wealth. A tax on capital would be a less blunt and more systematic instrument for dealing with the question.”

Piketty’s last sentence is the opposite of the truth. A tax on capital, no matter whether that capital was acquired legitimately or illegitimately, is incredibly blunt. It’s systematic only in the sense that it systematically takes wealth from all wealthy people. I agree with Piketty that courts are not usually the ideal way to resolve the issue of ill-gotten gains: much of what government does to produce those gains is legal, however morally questionable. The best way to prevent ill-gotten gains is to take away the government’s power to grant them. If the Mexican government had not had the power to create a telecommunications monopoly, for example, Slim’s wealth would be—much slimmer.

That brings us to the second question: Is it a good idea to reduce inequality by more heavily taxing those at the top end? If there’s anything we know from basic economics, it’s that incentives affect behavior. Tax high incomes or wealth heavily and you will have fewer people trying to make high incomes and get wealthy. Moreover, even if the incentive effect were slight, high taxes on highly productive people take wealth out of their hands, where much of it likely would have been used to finance more pro-consumer innovation and productivity, and put it in the hands of government bureaucracies. That simple transfer of wealth, independent of the effect on incentives, makes a society worse off.

Third, has poverty been increasing? No. In fact, what economists call extreme poverty—living on an income of less than $1.90 a day—has fallen dramatically over the last 3 decades. For the first time in world history, fewer than one billion people live in extreme poverty.

This is all the more striking when you remember that the world population, at 7.6 billion people, is at an all-time high. Why has this happened? Because of increased international trade and economic growth—which have made some people extremely wealthy, while also lifting over one billion others out of crippling destitution. The argument that economic inequality somehow exacerbates poverty is specious.

Finally, has economic inequality been increasing or decreasing? The wrong way to answer that question is by comparing the wealth of billionaires to the wealth of the poorest people on earth. The correct way is to compute something called the Gini coefficient. This coefficient, which can range from 0 to 1, measures income inequality. With total income equality, the Gini would be 0; with total inequality, which would mean one person having all the world’s income, the Gini would be 1. So what has happened to the Gini coefficient over time? Economists Tomas Hellebrandt and Paolo Mauro reported the answer in a 2015 study for the Peterson Institute for International Economics. They found that between 2003 and 2013, the worldwide Gini coefficient fell from 0.69 to 0.65, indicating reduced income inequality. Moreover, the two economists predict that by 2035, income inequality will decline further, with the Gini coefficient falling to 0.61. The reason is not that higher income people will do worse but that lower income people in some of the poorest countries, like India and China, will do much better because of economic growth.

If the problem we care about is poverty, then the calls to tax the rich and reduce income inequality are misguided. Instead, we should be cheering for policies that lead to higher economic growth. One other important measure is increased immigration. Allowing more immigration into the United States would allow people to move from low-productivity jobs in poor countries to higher-productivity jobs in America. That would dramatically improve the plight of the poor while also improving, but by a smaller margin, the well-being of the rich. Piketty, for all his faults, put his finger on how to do so. He wrote: “A seemingly more peaceful form of redistribution and regulation of global wealth inequality is immigration.  Rather than move capital, which poses all sorts of difficulties, it is sometimes simpler to allow labor to move to places where wages are higher.”

Amen, frère.