---
title: 尽人事，听天命
author: Guanghua Mao
date: '2021-11-26'
slug: '333'
categories:
  - Original Articles
tags:
  - Prediction
  - Insights
---

最近经历了不少事情，也回想起了不少事情，那些在求学生涯中所经历的一切都历历在目，其中令我印象最为深刻的依然是初中时期的两位学神。这两位完全依靠自律、勤奋、聪慧、不抱怨等特质，完全改写了自己人生的命运。

从设定的目标上说，这两位一开始就是以第一为追求目标，所谓追求卓越就是这样，反观我，反倒是有一种得过且过的心态---能够考上重点高中就好。在目标设定上的区别使得他们能够拼尽全力去学习，而我则是学个差不多就好。缺乏了一个明确且远大的目标会直接影响我们的时间规划、对细节的重视程度、对机会的把握。

从每天的习惯来说，二位学神没有把目标只是单单停留在口头上，而是老老实实地从每一天做起、每一个小细节做起，在看似平凡的每一天中向自己的目标买进，在这一方面，我又差得很远，很多时候，我因为头脑发热也订过一些目标，但是没有针对目标的实施计划，和每天的实施步骤，更重要的是，我设置目标偏爱短期见效，恨不得一天学习 10 小时，对自己的能力没有了解，对非线性回报缺乏耐心。而两位学神能够不断地从日常的点点滴滴中持续改进，把目标融入到每天的生活中，该玩就玩，该学就学，最后的结果也相较于我好很多。

更重要的是，二位学神从来不抱怨，心态极佳，无论是面对成功还是面对失败，都能正确地应对。在我们当地那么贫瘠、教育资源如此落后的情况下，不抱怨、努力想办法解决问题，反观现在抱怨什么原生家庭、教育资源不平衡的，二位学神胜过他们太多。

而我在求学生涯中，犯过无数的错误，急功近利（过分重视短期回报）、眼高手低（有目标没执行）、鼠目寸光（没有意识竞争的激烈，沉浸于自己的小目标，没有用尽全力）、心态不好（傲慢和自责都出现过）。当然，工作之后，我极大幅度地改善了自己的一些缺陷，工作让我成为了更好的人。正如《篮球让我成为更好的人》一书中所说：教练的功能不是训练出更好的球员而是训练出更好的人，每个人追求的应该是丰盈充实的人生，篮球只是其中一个方式而已；重视细节，甚至是穿袜子这样看似无足轻重的小事；专注基本功的训练，而不是奇巧淫技，并把基本功的训练注入每一天的生活之中；不要抱持希望，那是留给没有准备好的人；言传不如身教；坦然面对结果。

总结起来就是尽人事，听天命。每一天都用尽全力，也许成功就会出其不意地找上门。