---
title: Is Fascism Right Or Left?
author: Dinesh D'Souza
date: '2021-07-20'
slug: '259'
categories:
  - Translation Articles
tags:
  - Propaganda
---

>如此来看，女权主义、伊斯兰极端主义、痛骂资本家的这一批和法西斯也没什么区别。换句话说个人主义右，集体主义左。

[Source](https://www.youtube.com/watch?v=m6bSsaVL6gA&list=WL&index=1)

“He’s a fascist!”

For decades, this has been a favorite smear of the left, aimed at those on the right.

Every Republican president—for that matter, virtually every Republican—since the 1970s has been called a fascist; now, more than ever. This label is based on the idea that fascism is a phenomenon of the political right. The left says it is, and some self-styled white supremacists and neo-Nazis embrace the label. But are they correct? To answer this question, we have to ask what fascism really means:

What is its underlying ideology?

Where does it even come from?

These are not easy questions to answer. We know the name of the philosopher of capitalism: Adam Smith. We know the name of the philosopher of Marxism:
Karl Marx. But who’s the philosopher of fascism? Yes—exactly. You don’t know. Don’t feel bad. Almost no one knows. This is not because he doesn’t exist, but because historians, most of whom are on the political left, had to erase him from history in order to avoid confronting fascism’s actual beliefs.

So, let me introduce him to you.

His name is Giovanni Gentile. Born in 1875, he was one of the world’s
most influential philosophers in the first half of the twentieth century.
Gentile believed that there were two “diametrically opposed” types of democracy. One is liberal democracy, such as that of the United States, which Gentile dismisses as individualistic—too centered on liberty and personal rights—and therefore selfish. The other, the one Gentile recommends, is “true democracy,” in which individuals willingly subordinate themselves to the state.

Like his philosophical mentor, Karl Marx, Gentile wanted to create a community that resembles the family, a community where we are “all in this together.” It’s easy to see the attraction of this idea. Indeed, it remains a common rhetorical theme of the left. For example, at the 1984 convention of the Democratic Party, the governor of New York, Mario Cuomo, likened America to an extended family where, through the government, people all take care of each other.

Nothing’s changed.

Thirty years later, a slogan of the 2012 Democratic Party convention was, “The government is the only thing we all belong to.” They might as well have been quoting Gentile. Now, remember, Gentile was a man of the left. He was a committed socialist. For Gentile, fascism is a form of socialism—indeed, its most workable form. While the socialism of Marx mobilizes people
on the basis of class, fascism mobilizes people by appealing to their national identity as well as their class. Fascists are socialists with a national identity. German Fascists in the 1930s were called Nazis—basically a contraction of the term “national socialist.” For Gentile, all private action should be oriented to serve society; there is no distinction between the private interest and the public interest.

Correctly understood, the two are identical. And who is the administrative arm of the society? It’s none other than the state.

Consequently, to submit to society is to submit to the state—not just in economic matters, but in all matters. Since everything is political, the state gets to tell everyone how to think and what to do.

It was another Italian, Benito Mussolini, the fascist dictator of Italy from 1922 to 1943, who turned Gentile’s words into action. In his Dottrina del Fascismo, one of the doctrinal statements of early fascism, Mussolini wrote,
“All is in the state and nothing human exists or has value outside the state.” He was merely paraphrasing Gentile. The Italian philosopher is now lost in obscurity, but his philosophy could not be more relevant because it closely parallels that of the modern left.

Gentile’s work speaks directly to progressives who champion the centralized state. Here in America, the left has vastly expanded state control over the private sector, from healthcare to banking; from education to energy. This state-directed capitalism is precisely what German and Italian fascists implemented in the 1930s. Leftists can’t acknowledge their man, Gentile,
because that would undermine their attempt to bind conservatism to fascism.

Conservatism wants small government so that individual liberty can flourish.

The left, like Gentile, wants the opposite: to place the resources of the individual and industry in the service of a centralized state. To acknowledge Gentile is to acknowledge that fascism bears a deep kinship to the ideology of today’s left.

So, they will keep Gentile where they’ve got him: dead, buried, and forgotten. But we should remember, or the ghost of fascism will continue to haunt us.

