---
title: 方丈在雪球上关于苏宁的评价
author: 方三文
date: '2022-02-13'
slug: '341'
categories:
  - Translation Articles
tags:
  - Investment
---

>苏宁的失败实在是太精彩了

1. 投资阿里巴巴赚了100多个亿，可是扛不住别的失败的投资。//@陌尚阡:回复@7X24快讯:苏宁当年利用线下挣的钱转型投资线上一篮子电商公司股权，这样线上线下都有了，会不会有不一样的结果 // @仓又加错-刘成岗：典型的，方总说的，企业资源有限论，的反面案例
//聚焦和专注是多么的重要//根本原因是加码线上线下 有点不搞电商等死 搞了找死一般。放手一搏 愿赌服输 电商烧钱无底洞 各路英雄大浪淘沙 归根到底考验运营效率


2. 方丈觉得苏宁失败的核心原因是什么？其实苏宁很早也看到了趋势，要线上线下协同，但无奈张老板野心远大于能力，业务多元化，如果all in一条路，抛弃过去的道路，有没有可能有一线希望 // 我觉得说一千道一万，是张老板太牛逼。//线上线上协同概念提的非常早，但是我在线上下单去线下提货，给我感觉就是利益不一致，相互对立的两个部门。执行层面完败。//觉得自己什么都能做？



3. 我是一个个人能力有限论，企业资源有限论者。张老板不这样认为，他的员工也不敢这样认为。//记得在在11年左右，那时发现移动互联网会爆发，然后在A股找相应的标的，张近东的线上口号震天响，觉得很有机会便单一持股苏宁，后来发现线上线下如同左手打右手，太难了。最后亏损40%退出，这是第一次“价值投资”的失败经验 // 我的一个猜测，公司发展壮大得太顺了，各级领导没有经过市场的历练，靠关系或者资历上了位，面对如今的市场竞争只能靠过往的经验来应对，但过往的经验很可能是非市场竞争下的国企经验，而且这样的人应该相当多，属于尾大不掉了，有抱负的年轻人看到这样的环境，恐怕呆不了多长时间，几年之后更高的管理层想把这些领导换掉也是换不掉了，没有人才来接班了//“看的都对，就是没干成” // 不现实的想法,线上要线下供血的。而且关键在苏宁没有电商创业的基因,这一点至关重要的,也是传统行业转向互联网的最大障碍。降维打击吃的就是低维的肉,而且低维往往体态臃肿被活生生的吞掉了,毫无还手之力。比如：诺基亚，柯达。小而美才是最具生命力的。 // 早些年的时候，电商兴起不久，对于苏宁是否要向线上转型，张老板说过，做是找死，不做是等死。现在看，这认知很正确，相对的，苏宁后来走的路就很谜，论理应该结束生意才对。


4. 苏宁的线下能力远强于京东，但是线上的用户体验以及市场份额还差不少，而且京东已然是综合电商，苏宁还在综合零售的转型路上；布局不比京东差，但是意味着同时要做的事情也更多，能不能都做好，还要再观察


5. 谈点看法，留给我的有缘人：

1）张近东的做法，是以己之短，拼年轻人之长。这样的选择，即使是成功了，也是代价非常大。而通常这种成功的概率并不大。明智的选择，是扬长避短，发挥自己的优势。在自己优势的领域做战。

2）史玉柱的选择是非常明智的。退出一个年利润10亿的具体实体经营，转向一个投资百亿以上的市场。仅从时间和精力产出比，就是个明智的选择。此外，重点集中在现在行情不好，大家都不愿意参与的二级市场，正是田忌赛马，扬长避短。

3）一个人的命运是离不开国家和大势的，顺势而为，扬长避短，才能事半功倍。



6. 楼主你说了我所有的理解，深有同感！！！
我从去年开始关注苏宁，买入，到想明白后退出，后悔没早点来雪球。浪费了时间和资金成本。

amazon的贝索斯说过，他们是靠帮助消费者做选择赚钱，而不是靠卖商品，所以亚马逊不拒绝恶评。从这个角度看，京东苏宁干的都是卖货的事情，是真正的电...商。也许苏宁的股票还能走，因为它的故事很多，线上下整合、物流什么的。但就我能想明白的商业模式而言，阿里系这种从帮助消费者和商家角度出发的战略，更有竞争力。

什么是明天，明天就是信息传递更便捷。厂家出货，通过社会化物流，用户直接获得，中间商很少。小米、苹果这样企业的出现，其实已预示了将来。零售商将来，只能靠服务赚钱，而不能靠信息带来的差价赚钱。



7.  企业在经营上“追高”，就象炒股“追高”一样。//@天地侠影:我个人认为，苏宁的问题，已经不是报表的问题；投资苏宁与否，也不是看报表就能给出答案。从今天苏宁收购乐器行来看，我对$苏宁电器(SZ002024)$是愈发的悲哀。这几年，国人让孩子学习乐器太疯狂了，中国家长自以为孩子都是音乐天才。在最顶峰追逐市场的热点潮流，苏宁已经走火入魔了！


8. “多年积累的线下经验、线下资源”这些玩意都是战术层面的，在战略层面的攻击面前，不堪一击。//@Abstainer:去年年初的时候，曾经花了不少时间评估苏宁是否值得买入，评估的结果是苏宁可能升胜出（概率也不是太高），但至少三年才能见分晓。苏宁优势明显，多年积累的线下经验、线下资源，在传统零售领域的巨头中，苏宁是是转型比较果断的；但是电商的几个巨头已有先发优势，个个手握重金，准备决斗，生死一搏不可避免，SUNING的胜出概率当时看都不超多50%，这样下来最好的策略就是等待，而不是博一个概率不高的东西。IT信息化、物流专业化对传统零售的影响一直被低估，这个过程对苏宁来讲会很痛。



9. 既做渠道又做自有品牌，一是业务上有冲突，二是需要具备的资源的禀赋不一样。//@李成东:增加自有品牌的比例！//B2C不太可能有向消费者提价的能力，你看国美苏宁能靠提价吗？只能靠规模和效率，压厂商的价。只有品牌商才有向消费者提价的能力。//@胡龙飞: “京东的模式被证明了：平台被认可，慢慢提价已经被默许”。是这样吗？请教


10. 老董也上雪球啦
我不同意你的观点
苏宁不是京东的问题
而是行业生态的颠覆性的变化
跟原来的基因是否优质根本关系不大
环境突变，统治一个时代的恐龙物种就灭绝了
当初小小的google一出现，庞大的微软帝国就落幕了，今年更爆出季报亏损
不是基因变了，管理层不优秀了，而是行业生态整体变了
在新的行业生态链之下，PK京东、亚马逊、淘宝天猫……，苏宁易购没啥优势

什么双渠道，线下资源+线上资源
没并有想象中的积极意义
反而成为双手互搏、鱼与熊掌不可兼得之势
要么品类不全，说是互补，实际上两边都吸引不了客户，更建立不起忠诚度
要么互相争夺客户资源，自杀自残，整体效益为负
要知道，苏宁模式的本质，作为家电卖场在线下只是二房东而已
1.苏宁并不真正懂零售，特别是对非家电商品的零售转型，它以前的业务员都是厂家的，而不是自己的队伍
2.苏宁的大家电也不需要多大物流支撑，这也是厂商提供的，苏宁物流高投入低回报，和京东、天猫、亚马逊自建物流相比，甚至和第三方专业物流相比，根本形不成核心竞争力
3.苏宁所谓的采购成本优势，不会成为价格战的致命杀手，也不会形成牢固的护城河，因为随着对手迅速跟进壮大，上游的大型厂商不会只押宝苏宁一家，受制于人，重蹈覆辙，而是会乐于看到甚至促成渠道商的分化和多元化。行业生态变化只能会是渠道商对上下游的整体议价能力削弱，而不是增强，消费者大占便宜就是明显的例证。渠道垄断一旦被打破，甚至可以说苏宁已经没有护城河保护了。
总之，线下苏宁对线上业务帮助不大，拖累不小

苏宁投资者的失败
不是价值投资的失败
而是成长投资的失败
成长股一旦停止成长，或者成长低于预期
就必然遭遇戴维斯双杀
一杀业绩
二杀股价
互相反馈
自我强化
形成循环杀跌之势
而树永远长不到天上
因此双杀就是成长股的最终宿命




