---
title: 潮水退去与进步主义
author: Guanghua Mao
date: '2021-01-02'
slug: '133'
categories:
  - Original Articles
tags:
  - Investment
  - Conservative
  - Business
---

[Source](https://www.thenewslens.com/article/100360)

巴菲特老爷子曾经说过：“只有当潮水退去的时候,才知道是谁在裸泳”。2020年，美联储大印钞票，信贷宽松再加上中国疫情控制良好，对中概股的追捧让不少企业的股价不断攀升，“股神”多了起来，潮水也涨了起来。

但当疫情逐渐受到控制，全球经济恢复，信贷紧缩的时候，这些受到追捧的中概股仍然会维持如此高的股价吗？在上个世纪的互联网泡沫中，无数的盲目乐观投资者赔了个底朝天，当这一次的潮水退去，又会有多少盲目乐观者铩羽而归？

投资者的种种乐观假设和当年美国进步主义的乐观情绪如出一辙。他们完全没意识到企业和国家是复杂系统，其成功不可复制，只能通过开新公司和殖民的方式传播其成功。上个世纪，美国一手铸成大错，遣散了大英帝国，让无数前亚非拉殖民地坠入无底的深渊，在进步主义者看来，我们能建立美国，你们就抄袭一下我们的做法也能建立一个同样的美国，阿拉伯之春已经告诉了我们答案；二战之后，出于冷战考虑，美国在东亚重建了秩序，韩国、台湾两个原本在人类历史上默默无闻的地方，一跃成为世界科技的重要参与者。对于公司而言，其成功的产品也是不可复制的，一般而言，一家公司只有通过在时间、空间上不断的复制其成功的产品才有较高的成功率，一旦一家公司涉足其他业务，或者其他公司想要简单的抄袭和模仿其成功产品，成功率是很低的。但在成功故事的刺激下，不甘平凡的人们在乐观气氛和信贷宽松的浪潮下，开启了一波又一波的创业浪潮，绝大多数的公司毫无疑问会失败。潮水退去，人们那些想当然的乐观情绪遭到无情毒打

在2021的时间点上就让我预测一些公司的未来吧：

1. 3年内，小米股价会跌到10港币左右

2. 3年内，b站的股价会跌至20美元左右

3. 腾讯依然是中国最好的科技公司

4. 阿里股价会跌破5000亿美元

5. 京东股价会腰斩

6. 美团股价也会大跌

7. 网易会微跌，但仍然值得看好

另外，中文互联网上还没有看好乌克兰经济前景的文章出现，我很震惊。坚定看好乌克兰，它就是下一个发达国家。