---
title: 投资怎样的公司能赚钱
author: 方三文
date: '2022-01-16'
slug: '372'
categories:
  - Translation Articles
tags:
  - Investment
---


>商业模式：
1.规模
2.粘性（频度、使用深度（离交易多近？需求匹配度？互动程度？））。能否靠网络效应（越多人越好用）形成一个垄断的市场份额：边际效应递增、边际成本递减。

>网络效应也只是增加了用户的粘性





方三文：这几年，在世界范围内给投资者带来最丰厚回报的是哪些公司？（腾讯、Facebook、谷歌、亚马逊）这是一个给大家带来确定性的，比较高回报的一个品类。很多人投资了股票挣了钱，但是也有另外一些人始终对这个东西抱着一种怀疑的态度。因为大洋彼岸有一个叫做巴菲特的人他应该是过去几十年历，炒股赚最多的人。

巴菲特有一个说法：他是不投资科技股的，科技股很可能是泡沫。巴菲特在2001年没有参与当时的互联网泡沫，所以他避免了非常大的损失，可能很多人都觉得这些股票可能看起来涨得不错，但它应该不是我们所谓的价值投资的对象。不知道大家是不是有同样的看法？

确实，巴菲特说过这样的话。但是我要提醒大家，三年前巴菲特买了一家公司IBM，前两年又买了一家公司叫Apple，去年股东大会的时候，巴菲特说了一句话，他说也许像谷歌、亚马逊这样的公司，我和芒格应该是看得懂的。这是非常重要的一句话。

我怀疑，也许再过两年，巴菲特他会说，也许像Facebook、腾讯这样的公司，我和芒格也应该看得懂的，非常有可能出现这样的情况。

因此，我的看法，是不要教条主义的看巴菲特的话，说科技股就不适合价值投资。

从我的看法来说，某一类的股票，科技公司其实是最好的价值投资的对象。为什么呢？价值投资还有一个非常重要的核心，就是希望我们投的公司，经营的可持续性更强一些，受外部的因素——如市场的波动，经济的周期。受内部的因素，如管理的能力，他的影响尽可能的少一些。这样我们就能够建立一定的确定性，可以获得长期的汇报，有什么可以建立这样的确定性呢？我们可以看巴菲特过去擅长投资的几类公司，很多所谓的“护城河”是什么构成的呢？

一、品牌，一杯糖水，只要打上可口可乐的标签，全世界人民就都去喝，这就是品牌。

二、独有的技术，GE会被认为是有一些独有的技术，在大型工业设备上，它有优势。

三、专营权，某些公司因为各种各样的原因，会我获得专营权。比如说上海早期的时候，只有一座南浦大桥。如果政府说南浦大桥是可以收费的，同时又说不允许再修别的大桥，那么这个桥的经营一定是非常赚钱的。

这些品牌、专利技术、特许经营权是过去巴菲特投资很多公司的“护城河”来源。

那么这些东西是不是一定那么可靠呢？首先我们看品牌，我们知道可口可乐的品牌非常好，但是还有一个可乐叫百事可乐。好像可口可乐品牌再强大也无法影响喝百事可乐的人，最后导致可口可乐的市场份额是有限的，它的利润率也是有限的。

再比如说专利技术，GE很好玩，在2008、2009年时，有很多人买了很多GE的股票，当时的价格是十几美金，现在GE的股价是13美元，GE本身连通胀都没有跑过。

我们说汽车工业是一个被认为有一定技术附加值的行业，但是这么多年过去了，你们说像奔驰和宝马有品牌、有技术，但是他有什么技术是只有他能使用别人不能使用的吗？没有。所以这个东西也导致，只要有一个技术是你能用的，接下来大部分人都能够用。所以导致任何一家公司的市场份额都是有限的，利润率也是有限的。宝马的净利润率是多少，大家知道吗？大概是11%。利润率和市场份额都是有限的。

再比如说特许经营权。比如说政府只允许一个人修一座跨过黄浦江的大桥，同时允许这个人收费，这个人一定可以挣很多钱。但是事实上现在黄浦江上有多少桥？修了无数的桥，又修了无数的隧道，所以这个垄断就搞不成了。

综上所述，巴菲特过去教案当中的品牌、技术、专营权造成的企业垄断局面，其实都不是那么可靠。不是那么可靠就会导致这些企业市场份额永远是有限的，它的利润率也是受限的，以至于它的经营上的可持续性和确定性也不是那么确定。这是对传统的巴菲特喜欢投的行业的商业规律总结。

我们再来看一看另一方面，大家知道腾讯的净利润率是多少？腾讯的净利润率是32%左右。大家知道Facebook的净利润率是多少吗？大概是40%左右。

在坐可能有很多有自己的企业，也自己投过很多公司，如果说有自己的企业，自己的业务净利润率超过10%的人，举一下手行吗？那么你对40%净利润率的生意是不是会非常羡慕。那么这40%的净利润率，一定不是说扎克伯格这个人特别黑，靠坑人获得钱，或者是在Facebook上投广告的人特别傻。那么原因可能是什么呢？其实很简单，Facebook以及它的系列产品在中国以外市场上，很多国家都是占的90%以上。我刚刚说那些靠品牌、技术、特许经营权他们有吗？没有，这是垄断带来的。

我再问一下大家，在中国的即时通讯市场上，腾讯占的比例是多少？90%以上。所以他可以获得30%以上的净利润率。高净利润是高市场份额带来的。那么高市场份额又是怎么带来的呢？是政府只允许他一家做即时通讯，做社交吗？不是。是他有一个独门技术别人无法使用吗？也不是。是基于他的品牌吗？有人认为是。我估计你是微信的用户，那么我把微信改成红色你还会用吗？我把微信的名字改成巨信还会用吗？还是会用的是吗？那么和品牌也没有关系。因此不是品牌，不是技术，不是特许经营权，那是什么造成了垄断的局面呢？

微信最重要的是什么呢？是你的朋友都在上面。首先你这种基于血缘关系的亲朋好友都在上面，基于利益关系的同学、同事都在上面，你的客户也都在上面。这样的话，它变成了什么呢？你的人际关系都在上面。你越多的朋友加入这个网络，就会导致这个网络越强大。大家做很多的生意都会有这么一种感觉。就是企业的规模大到一定程度之后，管理效率是会下降的，只有社交软件是用得人越多越好用，越好用越多人用，最后导致别的产品都没人用，所以最后就形成了一个垄断的格局。

这个是这个时代最有趣的一种社会现象之一，就是这种垄断并不是基于品牌、技术和特许经营权形成的，这个基于规模形成的垄断优势你们觉得是可持续的还是不可持续的？如果我们认同Facebook和腾讯是基于规模形成的优势，那么和它竞争唯一的办法是什么？搞一个规模比它更大的。问题是，他已经把地球上的人“捞”得差不多了，我们绞尽脑汁也搞不清楚，如何搞一个更大的。因此在我们现在目力所及的范围内，我是没有看到什么东西可以撼动它的优势。因此我也倾向于认为，它的利润率还可以维持很久。

如果这样的话，也许过两年巴菲特会说，也许Facebook、腾讯我和芒格是应该能够看明白的。这是我对这种公司思维的框架。那么再倒回来，这个东西对指导我们除了去买Facebook和腾讯之外，买其他公司和产品有没有什么启发呢？有。

我看很多公司，我大概都会从这几个角度去考虑这个公司是不是好的，或者我们可以用一些比较好的办法来确定这个东西是不是好的。

一、我们可以看规模。规模非常重要，如果说在市场规模比较小的领域即便你占了非常大的份额，你的利润也是非常有限的。比如说现在非常多的人喜欢投资电影，觉得投电影这件事情太好了，可以把自己的名字打在电影院的屏幕上——出品人：XXX。那么我问一下大家，全国电影票房一年有多大规模？500亿左右。卖票卖了500亿，电影院还要拿走一半，其他的还有宣发的费用，最后分给这些电影投资方的人能有多少呢？我觉得一年绝对不会超过100亿，但是那么多人都在拍电影，煤老板拍电影、矿老板也拍电影、物料公司老板也拍电影，我不知道怎么能赚到钱，这个市场规模是小的，就非常危险。

再比如说现在市值最大的公司亚马逊，是卖书起家的。在同时期中国也有一家是卖书的网站——当当。现在当当的市值是105亿，而亚马逊已经市值过万亿了。为什么？因为当当现在还在卖书，卖书是一个很小的市场，全中国书的市场一共才多大？也就是六七百亿。

但是亚马逊不一样，他非常早的就意识到书这个市场太小，所以后来他从书开始做其他的电商品类——百货。再接下来，他利用服务于电商的基础设施做起了云服务这个生意，云服务这个生意就要大得多了。所以如果亚马逊还在扎扎实实的卖书的话，估计贝佐斯现在和我们的李国庆先生命运是差不多的，都得把公司卖给别人，不可能成为世界首富的。所以市场规模非常重要。

再比如说互联网公司都讲用户，有一些公司号称自己有很多的用户，但是他挣了很少的钱。但是有一些公司只有很少的用户，但是挣了很多的钱。所以拥护和用户之间是有区别的，首先这个区别是用户使用的频度。在座的人，认为自己喜欢旅游的人请举手，去年出去旅游超过10次的人举一下手，去年出差超过10次的请举手。

这就叫频度，商务旅游是高频度的业务，休闲度假旅游是低频度的业务。靠商务旅游挣到钱的公司是携程，靠休闲度假旅游挣钱的公司是谁？如果说都是做度假旅游的话，携程、去哪儿早倒闭了，其实度假旅游就是一个低频的生意，差旅是高频的生意。高频的用户要比低频的用户好很多。

深度。比如说我是一个电视机厂商，全国最大的电视机厂商是谁？就那么几家，对吧。电视机企业可以做得很大，中国14亿口，4亿家庭，我觉得大的厂商生产几千万台是有的，也就是说他有几千万块屏幕放在客户家里，我们也可以认为他有几千万的用户，这些电视机厂家挣到钱了吗？没有。但是如果说我可以在屏幕上装一个浏览器，我也有几千万用户，我能挣到钱吗？我可以告诉大家，一定挣的比电视机厂商多。如果我再在里面装一个软件，比如说微信聊天，他挣的钱又要多得多，其实这就叫深度。深度是什么？如果是电视机屏幕，用户和你的关系是很弱的，你几乎完全无法影响用户的行为。如果说是浏览器的话，你可以动一点手脚，比如说浏览器，有一部分是自己操作的，有一部分是官方给的，他动一点手脚就可以赚很多钱。如果说是每天更新的产品，它可以赚到更多钱。如果你在那个地方可以发一个帖子，那么你就离不开这个产品了。如果说你那个帖子有人回应的话，你对这个东西简直就会上瘾，这就是使用深度。所以深度越深，它可以发掘的商业价值越大。

离交易到底多近。在20年前，中国最大的广告投放渠道是什么？央视。那个时候央视搞个“标王”。现在中国最赚钱的公司，比如说阿里巴巴，他最主要的收入是什么？广告。世界上最赚钱的公司，比如说谷歌、Facebook，是靠什么赚钱，也是广告。但是他们的营收量是超过央视很多很多倍的。

都是广告，怎么会差那么多呢？把原来我们认为挣很多钱的人都给干掉了。这当中有什么原因？你们认为阿里巴巴的广告和央视的广告有什么区别？看电视人少是一个原因，但是最根本的原因不是看电视的人少，而是此广告跟彼广告看起来都是广告，但是其实天差地别。

比如上我正在看电视，我非常激动，这个时候来了一个奥迪汽车的广告，说乘坐奥迪汽车就是有面子。放奥迪汽车广告的这个人希望是什么呢？他希望电视屏幕另一头的人，他那天想买汽车的时候，会买奥迪汽车。但是这种概率有多高？撞大运。

因为首先他不知道我是不是要买汽车，我只想学习XXX，你这个时候出来做一个奥迪汽车广告，我非常生气。

第二，我看电视，我坐在客厅里，这个时候我并不想买汽车，你告诉我奥迪汽车好有什么用呢？

第三，明年我真的想买汽车，你那个广告我早忘了，所以这个广告是没有什么效果的。

举一个例子，比如说我是住在北京的。我昨天在携程上订了一张机票，从北京飞到上海，然后这个时候携程给我弹出一个东西，说上海金茂凯悦酒店打8折，你晚上是不是要入住？你觉得这个效果怎么样？大家发现这里面的区别了吗？

第一，这个东西正是我想要的，他跟我的需求是匹配的。

第二，我如果说我想要，我立刻就可以购买，我不需要跑到4S店去买。

因此此广告和彼广告完全不一样。最终实现影响用户交易行为的东西才是最有价值的。

归纳起来，我们认为在互联网投资这一块，大体上来说，我们要建一个分析框架的话，首先看它的市场规模，第二看它的用户行为是否高频，第三看它离交易是否近。还有一条最根本的，就是你这家公司的产品能不能靠网络效应（越多人越好用）形成一个垄断的市场份额，这个也非常重要。而能有越多人用越好用的特征和刚刚说到的使用深度是非常有关系的，越有使用深度的产品，越有可能出现越多人用越好用的特征。如果说发现这样的特征，那就可能是很不错的投资标的。


