---
title: 'Doing business in Ukraine: 30 years of independence'
author: Avellum Law Firm
date: '2021-09-01'
slug: '293'
categories:
  - Translation Articles
tags:
  - Ukraine
  - Economics
  - Business
---


Published Aug. 20. Updated Aug. 20 at 4:18 pm

>Let me start with a provocative statement: it is really easy and safe to do business in Ukraine today. As discussed in the article below, this is not a naive view of a Ukrainian lawyer but pure facts and statistics. Moreover, if you compare Ukraine with its neighbors, the contrast is startling: information transparency of companies coupled with super-fast registration procedures and special regime for IT companies are astonishing.

# Soviet past


When Ukraine appeared from the collapse of the Soviet Union, it barely had any commercial businesses and little private property. As a result, Ukraine spent the first decade of its independence privatizing the vast majority of large and small Soviet enterprises, transferring land and apartments into private ownership, and allowing commercial businesses to appear and flourish. By 2000, Ukraine had an established (albeit developing) market economy that suffered from corruption, raiding, and enormous bureaucracy. It had the Soviet legacy mixed with the Wild West style of doing business. To see how things changed, it is better to compare Ukraine in 2000 with its current state in 2021.



# Public registers


In 2000 Ukraine only had 4 publicly accessible registers that focused primarily on company registration. In contrast, in 2021, Ukraine has nearly 70 public registers accessible online that provide helpful information to companies in most business areas. Services such as Opendatabot enable comprehensive searches on any company and instant notification on any changes in the registers to its shareholders and management. You can even see financials that companies regularly submit to the state authorities.


# Starting a business


When I started my career in February 2000, it took me 30-40 days to register a new business in Kyiv and involved 14 different procedures. Today, if you are really in a hurry, you could register a company (usually an LLC) in just 2 hours and complete most procedures (up to 6) online. Numerous notaries around the country will be happy to help you if you want to do it in person.


# Minority shareholder protection


Doing Business Report by World Bank in 2007 ranked Ukraine 142 out of 175 countries in protection of minority shareholders. Today, Ukraine ranks 45, and further improvement is expected soon with the adoption of the new law on joint stock companies. Ukrainian corporate law now provides enormous flexibility for private companies’ corporate governance, shareholders’ agreements are gaining popularity, and court practices have filled in most ambiguous gaps in corporate disputes. At the same time, the latter are significantly less prone to corruption since procedural laws were substantially improved in the last 5 years.


# Licensed activities


As a post-Soviet bureaucratic state, Ukraine required licenses for 65 types of activities in 2000. Many more permits and authorizations were required at that time, too. This number of licenses dropped to 34 today, with many licenses now issued online and searchable. Ukraine abolished numerous redundant permits altogether.


# Work permits


Work permits for foreign nationals used to be notorious, with long waiting lines, review periods of at least 30 days, and the often absurd discretion of state officials. It now takes up to 7 days to get a work permit. In some cases, waiting is not required at all.


# Property registration


Real estate registration was no less notorious, often requiring up to 90 days to register a building or apartment and cost 4,3% of the total value of the property.

Registration with the Bureau of Technical Inventory (BTI) was a top-3 source of corruption in Ukraine for many years. Today it takes one day to register your new apartment in the public register without any need to deal with the BTI, and the cost dropped to 1.7% of the value. In most cases, a private notary will act as a one-stop-shop, with whom you can buy or sell land, buildings, or apartments.

# International treaties


Ukraine nearly doubled the number of international treaties (including bilateral investment treaties) from 2,405 in 2000 to 4,647 in 2021. It gives confidence to investors that in case of a dispute with the government, an investor may seek protection in investment arbitration.



# Diya City


As I prepared this piece, the Law on Stimulation of Data Economy in Ukraine came into force. It created a special regime for qualified IT companies at least for the next 25 years. Among other things, it envisages flexible employment of IT specialists and even more flexibility in contracts and corporate governance. If this regime proves popular in the future, it is likely to be expanded to other industries throughout Ukraine.


This is not to say that Ukraine has nothing to improve. On the contrary, the Ukrainian legal community works hard to implement further improvements in Ukrainian law and fully harmonize it with the EU legislation. However, the progress is remarkable and deserves praise and attention both from foreign and local investors.


