---
title: 永不餍足的需求
author: 方三文
date: '2022-01-15'
slug: '369'
categories:
  - Translation Articles
tags:
  - Investment
  - Business
---

[Source](https://xueqiu.com/1955602780/85728271)

>互联网偏好、精神消费偏好、自由社会偏好、网络效应偏好、越贵越好偏好。要注意：好的行业不代表好的商业模式。

老一辈无产阶级革命家告诉我们，发展经济的目的，是满足人民群众日益增长的物质和文化需要。

为了满足人民群众日益增长的物质需要，中国企业造彩电，造冰箱，造空调；造自行车，造摩托车，造汽车；盖公寓，盖别墅。基本上所有的行业，中国企业都造成了世界第一。

但这时候突然发现问题了。

啥问题？

彩电冰箱空调太不容易坏；汽车已经没地方停了；空着的房子比住人的房子还多。

人再饿，吃三顿也饱了；再伟大的人，躺下来也就占两平方米；喝了茅台，最多也一夜七次，再来一次腰受不了了，@但斌 是吧？原来，不是产能过剩，而是需求有限啊。

人民群众限入了需求满足的空虚之中，企业家限入了增长失速的焦虑之中：下一个增长点在哪里？

其实无产阶级革命家早就给大家指出了方向：文化需要。

文化这词有点虚，我给改个名目吧，叫精神需要，正好跟物质需要对应起来。

精神需要这个东西太有意思，它的运作规律跟物质需要正好是相反的：

人的物质需要是有限的，精神需要却是无限的，所谓马屁再多也不嫌多，就是这个意思。

人的物质支付能力理论上是可以无限扩张的，人的精神支付能力却是无法扩张的。你想想，让巴菲特给你付100万美元，对他实在是太小case；你让他陪你聊24小时天，他顿时崩溃了。现在陪聊两小时收300万美元呢。

人在物质需要方面的支出都是斤斤计较的，精神方面的支出却是根本不计价。给陈圆圆买一栋帝都别墅，吴三桂肯定要讲价的；等到冲冠一怒为红颜的时候，就根本不讲价了，精神需要啊。

所以结论很简单，如果谁能满足人民群众永不满足的精神需要，谁就挣大钱。

其实，过去也有这样的产业，是满足这个需求的，比如电影、电视、书籍、报刊，俗称文化娱乐产业。

这个模式有一个特征：就是在满足精神需求的产品跟用户之间，隔着一个叫做媒体或者机构的东西。

这个机构存在的理由是：它知道把控产品的质量，它知道用户的需求。

它真的知道吗？它真的知道吗？它真的知道吗？

后来出了一个叫互联网的东西，做了一个胆大包天的尝试，就是把中间环节砍掉，直接让生产者面对用户。比如，新闻让当事人发布，不要通过一个叫记者的中介；比如，文章让作者直接发布，不需要媒体做中介；比如，唱歌的姑娘，直接向观众收钱，不要通过一个夜总会老板或者制片人。

这一试不要紧，发现了一个惊人的事实：多少年来中间隔着的那个机构，既把控不了产品的品质，也把握不了用户的需求！

做这个胆大包天的尝试的是什么？

$Facebook(FB)$ $腾讯控股(00700)$ $微博(WB)$ 当然还有推特，陌陌，YY。。。

他们摧毁了一个旧世界，建立了一个新世界。

所以理解为什么它们的股票要涨了吧？

我夜来无事，梳理了一下全世界最有可能市值达到万亿美元的公司，也有一个惊人的发现：一家传统制造业公司都没有！一家都没有！不信您看看：万亿美元(ZH1068865)

将来的王者，一定是满足人民群众永不满足的精神需要的公司，而不是满足很容易满足的物质需要的公司
