---
title: 拒绝的艺术 and 非常成功
author: 王川、冯大辉
date: '2020-12-07'
slug: '103'
categories:
  - Translation Articles
tags:
  - Culture
  - Insights
  - Investment
  - Sociology
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

# 拒绝的艺术

曾经有那么几年，我经常被邀请做某些事情：邀请参会，邀请做分享，邀请写个书评，邀请写个软文，邀请帮转发条微博，约我喝咖啡…

在这个苗头逐渐起来的时候，我不知道如何去拒绝对方。都是一些朋友来找，对方难得开口，你让我怎么拒绝? 于是呢，我只好去参会，有些场合还需要演讲，上去讲十五分钟就下来，连来带去消耗两天时间；我去做分享，去了只是给一个小团队闭门讲座；我写书评，看完书之后绞尽脑汁遣词造句，一篇短文写了好几个小时；我给人写软文，被骂广告狗；我帮转发微博，被粉丝果取关…

朋友们的一些邀请还好，有些朋友给过我无私帮助，能提供帮助自然要去支持。有的时候，还有大量陌生人来的邀请，不答应还会被骂「你以为你是谁? 找你是看得起你，装什么逼? 」 时间久了，把自己搞得苦不堪言，大量的时间被消耗在这些事情上，「增熵」大概是一种自然现象，个人生活和工作都很难摆脱这个魔咒。更可气的是，这些邀请我的朋友还时不时的来问我：你每天都在网络上写东西，你不累吗? 你可真有时间啊…

让我说啥？我当然累，如果我能不去参与一些事情，就可以节省大量的时间，可以把这些时间留给更有意义的事情，留给自己的生活。

直到有一天，我开始直截了当的学会拒绝。

拒绝参加行业会议，无需出于社交的目的去参会。我不想认识任何一个行业大佬，行业大佬会给你带来新用户吗? 你自己什么都不是，大佬搭理你干嘛? 加个微信就代表认识人家了吗?

随着创业进入持久战，也越来越觉得没有什么更多经验分享，做不好的事情太多了。拒绝公开演讲之后，这样我就不用为演讲内容做准备，甚至也无需为演讲效果不好而困扰。对于我这样每次几乎都是即兴演讲的人尤其是一种解脱。

拒绝给人写书评或产品评测，但是顺手的话，在微博或是微信上推荐一下好书或是好玩的产品，效果同样很好。为什么要做你给我的「规定动作」?

拒绝做闭门讲座，或是单独针对提问者回答问题，这样效率太低。如果有必要，可以节省下来时间写一篇有针对性的文章，让更多人有参考。比如，有人找我去给讲讲微信怎么运营? 需要我讲嘛? 把我过去的微信公众号文章看一遍就有所有的内容。

拒绝帮人转发微博，内容好，我自然会转发。内容不好，转发了有什么用？何况一群找我转发微博的人，平时自己根本不花时间做这些事情，甚至在一些场合嘲笑我：那家伙整天玩那些有啥用? 然后他用到你的时候会厚着脸皮来求你。

拒绝任何没有目的的面谈。不少做投资的做媒体的，提前几天来约我聊天喝咖啡吃海底捞，一律拒绝。且不说，定时间地点本身就对自己工作有干扰，见面聊什么呢? 无非是空对空的扯淡罢了。

当拒绝掉大量实际没什么意义的事情后，我真的觉得自己「势利」了很多。不过，我一下子可以有更多的时间去做一点有效的事情，也有机会静下心来尝试帮助更多的人。比如，我会选择推荐更多有趣的帐号，激发这些朋友的创作激情，他们的文章能帮助更多人。

让你做的事情对更多人有价值，就会有更多人帮助你。如果你做的事情只对少数人有价值，你得到的帮助自然不多。有人写篇文章就叫我来转，然后呢? 不断的过度消费我自己，给别人推荐更多的垃圾。

归根结底，这是如何让自己时间更有效的一个选择方式，尝试达到一个「减熵」的状态。也是最近几年来的一个变化。

---

# 聚焦和婉拒的艺术 – 兼谈成功和非常成功的人的区别

今天读到著名公众号"小道消息”的作者冯大辉先生的文章，“拒绝的艺术”，深有同感.

冯先生的抱怨是，他在业界有点影响以后，常常会收到各类邀约，参加活动，发表书评，转发文章，耗时耗精力不说，还吃力不讨好。有时拒绝一些陌生人的要求后，会迅速遭到无情的痛骂.

这一点我自己也常常遇到，在我的公众号 investguru发了将近五十篇原创文章后，常有读者私信，要求见面聊聊.

可是我对他们基本没有了解，无亲无故，他们也不是我的投资俱乐部付费会员, 为什么一定要见面?

实际上，一个人水平高低，基本上从微信上，他发表的对事物问题的见解很快就可以看出。如果微信上交流可以解决，如果没有具体明确的事要做,为什么还要花几个小时约见，浪费汽油，浪费停车位，浪费食物饮料，说一些不痛不痒的寒暄，吃得脑满肠肥后再拍屁股走人?

这是为了给日后的糖尿病，高血压，痛风和脂肪肝打下坚实的基础吗？还是要给制药公司未来增加销售额?

这个现象的潜意识是这样的: 人们希望结交有各类资源的人，帮助自己事业上的进步。但是有些朋友，不注重提高自身的实力，而把希望完全寄托在攀附别人的捷径上，所以花大量时间参与社交活动.

可是所有的资源交换，最终必须要对双方互惠互利，方可长久.

如果一个人没有能力为他人增加实在的价值，没有东西证明其能力和信用, 期待从他人那里获得实在的价值，是不现实也是不合理的.

如果被拒绝后, 给别人随便扣上一顶”功利”的帽子，把自己置于某种虚幻的道德制高点上，那就更加可笑了.

我的朋友戴忠玉（公众号: 锐战略）转告我巴菲特老师的一句话, “成功的人和非常成功的人的区别是，非常成功的人几乎对所有的事情都说不”. 我深表同意.

对低水平事物的无原则接纳，就是对高水平事物的辜负.

在投资的策略上尤其如此。大部分投资工具，绝大多数时候，都不是好的选择. 需要非常挑剔，耐心等待, 有所不为才能有所为. 这是最重要的美德之一。（可以参考我的公众号investguru 里的老文章，“在自己选择的战场战斗”. 公众号内输入 007 即可调出）

在走向非常成功的路上，要对哪些事情说不呢？分享一下我的浅见.


第一，保持充足的睡眠，对损害身体健康的工作狂方式, 坚决说不.


第二，现代企业和教育的文化氛围，有一种鼓励人们无所不学，学得越多就越好，而且不加选择地全面攀比的心态。要对这种盲动心态说不.


在教育上，这种思维被许多家长用到了极端，给中学生巨大精神压力。硅谷腹地的斯坦福大学旁边的一所著名高中，2009年至今，已经超过十名高中生自杀.

第三，说不，绝不是意味着固步自封，不听取不同意见。恰恰相反，正是因为保持开放的心态，愿意学习新鲜事物，所以才有能力和耐心，把自己的选择限制在最好的事物上.

第四，要保持高度的战略独立性。可以看看外面别人在做什么，但绝不丧失主见，影响自己的长期部署.


微信上流传的许多创业成功学的理念，鞭策人们以最快速度把公司做大, 上市，一些成功的个案也给创业者们打了鸡血.


但是这会使有些人，制定不切实际的战术目标，甚至头脑发热去投入陌生的领域，做完全不擅长的事情. 要对这种冲动说不.

三国时期司马懿和诸葛亮在五丈原对峙时，诸葛亮千方百计地诱惑对手出战，甚至送妇女的衣服羞辱司马懿为胆小鬼。司马懿知道蜀汉粮草终会耗尽，巍然不动.

在从对方使者口中得知, 诸葛亮每天要亲自过问打屁股二十大板以上的事后，司马懿知道他活不了多久了。后面的一切就都是历史了.

真正的英雄，在事业的发展途中，他们会不断问，这个东西真的那么重要，必不可少吗？他们不人云亦云，他们谢绝那些不重要的东西，集中自己的精力在重要的，力所能及的事上.


他们可能短期会得罪一些人，但是他们知道，只有依靠聚焦, 把重要的事情做好了，才能真正驾驭自己的生活和事业,赢得长期的尊重.

这就是区别成功的, 和非常成功的人的标志.