---
title: 下一块金砖在哪里？
author: 辉格
date: '2021-07-01'
slug: '232'
categories:
  - Translation Articles
tags:
  - Economics
  - Investment
---


 [Source](http://headsalon.org/archives/2335.html#comments)

>这篇文章作为对[**人类百年投资史：投资，最终还是赌国运**](https://guanghuamao.netlify.app/2021/06/30/dgy/)这篇文章的回应。我认为中国总体而言还有几年的好日子（因为疫情红利），但对于年轻一代来说，那个黄金年代已经过去，绝大多数人不会有任何改变命运的机会，失业率会很高，人们的物质生活水平不会大幅改善了。另外，除开文章提到的看好的国家，我继续坚定看好乌克兰。

最近，新兴市场投资基金研究公司（EPFR）发表的数据显示，国际资本正在大量流出以金砖四国为代表的新兴市场，跟踪这些市场的指数也相应的大幅下跌，高盛的分析师也认为，新兴市场的黄金时代已经结束；这些看法，无疑给那些寄望于新兴市场的繁荣将全球经济拉出萧条的人们泼了一瓢冷水，不过与种种乐观论调相比，它们看来更贴近现实。

过去二十年的新兴市场繁荣，是后冷战时代全球化所导致的资源再配置过程的后果，中国和印度的人力资源、俄罗斯和巴西的自然资源，在此之前被深锁在坚固的要素壁垒之内，一旦壁垒拆除，便造成了一股全球性资源再配置洪流，这些资源在进入全新的配置结构后，其产出能力和资产价值皆成倍增长。

这一过程不仅带来产出增长，更倍增了这些资源拥有者的财富，也为完成再配置过程的企业家、资本市场和金融业带来了大量投资机会和丰厚的资本回报；这是一种特殊事件带来的特殊繁荣，为更好的认识它，最好把它与常规增长区分开来，来自生物进化史的类比或许能帮助我们做这种区分。

地质史上，间或会有一些重大地理事件给生物界带来一个特殊的进化阶段，比如板块移动造就的巴拿马地峡最终在250万年前把南北美洲连成一体，冰川进退曾反复打开和关闭连接亚洲和北美的白令陆桥，气候干湿变化曾反复开闭连接下撒哈拉非洲和欧亚大陆的撒哈拉屏障，海面升降也曾多次开闭直布罗陀海峡。

这些地理事件所导致的物种流动，都会在短期内造就一个进化飞跃期，大批物种兴衰更替和辐射进化的规模、幅度和速度，都远非其他时期所能比肩；试想，假如有若干天使站上帝身边观赏进化史，并热衷于对各物种的命运下注，那么上述地理事件发生之际，大概也是他们押注兴趣最浓厚的时候。

那些观察敏锐、对进化规律有着良好把握的天使，这也是一展身手的最佳时机，假如上帝允许，他们或许还会从天堂跳下来，给那些在新生态形势下有发展前途的种群指路、提供交通工具，甚至贷款，这时候，他们就不只是投机者，也是投资者和企业家了。

战后树立的几道铁幕，如同关闭的直布罗陀海峡，将其身后的地中海变成了几近干涸的盐湖和大片荒漠，而构成过去二十年新兴市场繁荣的主要动力，便是海峡开放后迅猛灌入的海水，而现在，这一过程似乎已经完成，08年危机或许就是这股洪流所遭遇的一次反弹——正如熊彼特所指出，由于后浪看不见海岸在哪里，浪潮常常会扑过头而遭遇反弹；这并不是说进化已经停止，创新和增长仍将持续，但它已进入常规阶段，那种惊心动魄的场面已经过去了。

这样，“下一块金砖在哪里”这个问题就变成了：哪里还有这种级别的壁垒？答案似乎很明显：已经找不出大陆级规模的单一壁垒；阻碍要素流动的障碍当然还有很多，但那些都是零星分散而错综复杂的，不是由单一力量所设置并控制的，因而也是难以指望在短期内突然拆除的；如此看来，未来的增长将以常规方式进行。

在常规阶段，增长潜力将再次回归到制度优势和创新体系，这一点正是过去十多年常常被人们所忽视的，新兴市场令人眩目的表现让他们以为制度基础并非那么重要，这种见解的极端表现是张五常的“五千年最好论”，他们因为看到地中海的鱼类种群增长迅猛，便错误的断言地中海有着鱼类发展的最佳环境条件，其实只不过是因为此前地中海的鱼都死绝了。

投资者和企业家们，需要尽快从开放洪流所带来的喜悦和振奋中清醒过来，重新将目光聚集到制度和创新等传统优势上来，如此才能将自己的策略建立在一个牢固而可持续的基础之上；那些在市场制度建设上取得了长足进步的国家，比如秘鲁和蒙古，那些以危机为契机改善了其市场制度的国家，比如韩国，那些面对危机不乞灵于干预和管制而坚守市场取向的国家，比如新加坡和新西兰，在未来更值得看好。

重要的是，对于这些国家的人民，是不是金砖并不重要，那是给投资者衡量投资机会用的指标，好的制度才是他们生活和事业的坚实保障，许多在过去二十年很少吸引投资者目光的国家，比如斯洛文尼亚，实际上在生活安康和经济繁荣上都取得了极大进步。

