---
title: Evolution arms us with an extra artery
author: Cosmos
date: '2020-12-16'
slug: '116'
categories:
  - Translation Articles
tags:
  - Evolution
---

> 人类仍然在进化

[Source](https://cosmosmagazine.com/uncategorized/evolution-adds-an-arm-artery/)

Anatomical change could become the norm.

The human body continues to evolve in intriguing ways. New research in Australia has confirmed that more and more adults have a median artery in their forearms.

Or, more accurately, they have retained the median artery. It is the main vessel that supplies blood to the forearm and hand in the womb, but usually disappears once the radial and ulnar arteries develop.

Usually, but not always. Since the 18th century, anatomists have been studying its existence in adults, and the new study suggests it could soon become the norm.

“The prevalence was around 10% in people born in the mid-1880s compared to 30% in those born in the late 20th century, so that’s a significant increase in a fairly short period of time, when it comes to evolution,” says Teghan Lucas, from Flinders University.

“This increase could have resulted from mutations of genes involved in median artery development or health problems in mothers during pregnancy, or both actually. If this trend continues, a majority of people will have median artery of the forearm by 2100.”

And when the median artery prevalence reaches 50% or more, the authors write in their paper in the Journal of Anatomy, “it should not be considered as a variant, but as a ‘normal’ human structure”.

Lucas and co-authors Maciej Henneberg and Jaliya Kumaratilake, from the University of Adelaide, made their finding after studying the anatomical literature and dissecting 78 upper arms from cadavers of European descent donated for studies.

And the finding is more than just a curiosity. A third artery causes no problems and offers real benefits, says Henneberg, who is also a member of the Institute of Evolutionary Medicine at the University of Zurich, Switzerland.

It increases overall blood supply and can be used as a replacement in surgical procedures in other parts of the human body.

“This is micro evolution in modern humans and the median artery is a perfect example of how we’re still evolving because people born more recently have a higher prevalence of this artery when compared to humans from previous generations,” Henneberg says. 

The researchers cite other intriguing examples of human anatomy changing over time, including the increasing absence of wisdom teeth, prevalence of the fabella (a small bone in the back of the knee joint) increasing over time, and the thyroidea ima artery (a branch of the aortic arch) decreasing then disappearing completely by the end of the 20th century.