---
title: 學歷無用！劍橋高材生淪打工仔　嘆：這不是我要的生活
author: 综合报道
date: '2021-06-25'
slug: '202'
categories:
  - Translation Articles
tags:
  - Labor
---

 [Source](https://www.ettoday.net/amp/amp_news.php7?news_id=308287&from=google.com)

> 畢業自英國劍橋大學的班恩，求職不順只得到亞馬遜打工，身邊的同事也多是高學歷份子，許多人讀了他的故事後感慨，「學歷真的越來越不值錢。」

－這世界就像死了一般，我獨自在廁所推著口中的牙刷，盡量避免和鏡子中那具行屍走肉眼神接觸……。－

出身自全球頂尖劍橋大學的班恩，畢業後求職屢屢碰壁，最後只得捨棄夢想到網購大廠亞馬遜(Amazon)應徵，與其他數學博士或法學院畢業生在倉庫內，每日一起重複做著一些煩瑣的工作，「這不是我預期中的生活，但我們又有什麼辦法？」班恩將自身故事PO網，引發許多同輩的年輕人迴響，感慨努力換來的學歷越來越不值錢。

根據經濟合作暨發展組織(OECD)統計，自2007年起，全球失業年輕人數量增加了30%，低度就業造成薪資低落、長期失業引發社會動蕩不安和犯罪率高升，儼然成為各國政府頭痛問題。今年6月歐盟盟領袖高峰會，就曾將降低青年失業率列為首要任務。

出身自貧民區牧師家庭的班恩(Ben)，從小一路苦讀好不容易靠獎學金進入了劍橋大學，並以二級甲等榮譽學位成績畢業，原本夢想成為海軍軍官，卻苦尋不著機會，找到的幾份工作又十分不穩定，過著有一餐、沒一餐的日子，最後只好簽字領取失業救濟金，「我從沒想到自己會有這一天……。」

後在就業服務站介紹下，班恩硬著頭皮到亞馬遜應徵倉儲管理員，在面試過程中，班恩發現，面試官對自己的學歷根本沒興趣，只在乎他有沒有吸毒、是不是偷渡客，直到接受培訓時，班恩才知道，原來那名面試官也是高學歷份子，卻因政府縮減預算失業，只能跟他一樣放棄夢想來到亞馬遜工作。

像班恩這樣的「原」精英份子，在亞馬遜的倉庫裡比比皆是，他和同事們每天要上11個半小時的班，平均走上28公里的路，休息時間只夠吃口飯、喘口氣，活得就像一隻螞蟻，過去的驕傲，刷下了門禁卡後就只能拋在腦後，「在這裡眾生平等，我們只是工人、大機器裡的小螺絲，存在意義只有工作，你是誰都不重要。」

我很幸運，還能選擇上早班或晚班。」雖然亞馬遜給的薪水很低，每小時只有7英鎊(英國規定最低時薪為6.19英鎊，約台幣300元)，但班恩說他很感恩，因為他知道還有很多劍橋人，不是還沒找到工作，就是在當所謂的「試用期」免費員工。

就拿他的弟弟亞歷山德(Alexander)來說，儘管擁有劍橋學士和布里斯托爾大學電機碩士學歷，卻在來亞馬遜應徵時被刷下，目前仍只是備取人員。

為何青年失業問題如此嚴重？除了全球化、人類壽命延長等因素外，兩位麻省理工學院經濟學家在《與機械賽跑》一書中指出，現代科技的革新跟當年工業革命不同，電腦、機械人、網際網路不但未帶來龐大就業機會，反而使人力需求越來越少，搜尋引擎巨擘谷歌(Google)一座占地15公頃的資料中心，竟只需要60名全職員工就可運作！求職自然越來越困難。

班恩的故事見報後，許多年輕人都心有戚戚，班恩說，隨著聖誕節的腳步近了，最近他的工作越來越多，很意外的是，班恩已經學會面對、接受現實，「我都跟我10歲最小的妹妹說，我在聖誕老人的石窟工作！」

現在……還有誰要抱怨自己高學歷低成就？