---
title: 何谓良法？
author: 博弈与演化
date: '2021-08-31'
slug: '282'
categories:
  - Translation Articles
tags:
  - Common Law
---

> 中国与美国的差距如同猩猩与人类的差距

法律是现代社会秩序的基础之一，它规制着我们的生活，也正因为如此，它的好坏对我们生活有着巨大影响。本文想简单聊聊对何谓良法的一些看法。

 

道格拉斯.诺斯指出，制度最根本的的作用是：减少人类所面对的不确定性，不管这种不确定性是来自社会还是自然界。这里的“制度”是英文中的“Institution”，它包括成文的法律，以及不成文的社会规范，传统，道德规则等。今天我们重点讲成文的法律。法律主要通过奖惩的方式，来促进人与人之间的合作和协调，不管这种合作是消极的合作还是积极的合作；所谓的消极的合作，即人与人之间不相互伤害；而所谓积极合作，即人们之间相互帮助，贸易等合作行为。任何激励大家不合作，使得大家对未来预期混乱，增加不确定性，从而降低人们的幸福感的法律，都不是好法律。在这个基础上，我们开始阐述何谓良法。

 

1.法律不应强人所难，也即其应有可行性。它不应规定普通人无法做到的事情，也就是说它需要有一个正确的人性基础，同时也要考虑当时环境的限制，否则就会把大部分人和企业置于违法的境地。而一旦大部分人被置于违法的境地，法律执行起来就变得很困难；而当法律被普遍违反而不受惩罚时，整个法律体系就容易丧失它的权威和合法性。更有甚者，这种强人所难的法律，往往成为当权者手中暴虐的工具，通过选择性的执法，来打压异己和寻租，同时也增加对应公民和企业的不确定性。

 

例如，很多部门出台对大部分企业都非常严格的管制标准，使得在目前环境下的企业大部分都无法达到标准。这时候，对应的管制官员就可以通过这种严格的法律来进行寻租：先是在考核中让企业不合格，然后诱导企业对其进行行贿。比如消防。再如，劳动法规定企业每个员工每个月加班时间不得超过36个小时，但对于大部分好企业而言，这都是非常难以做到的，结果只能普遍地进行数据造假。

 

法律也不应该规定人们一定要见义勇为，见义勇为只能通过道德进行激励和约束，而非法律。同样法律可以规定人们只能在18岁之后才能结婚生子，但不应该规定人们只能在35岁之后生孩子，因为这种年纪的女性男性生育能力已经大大下降，生育的风险也大大增加。

 

2. 一个法律规则，应该在时间维度上是相对稳定的。法律最重要的作用，就是给人们以稳定的预期，协调彼此和自己的行为，从而降低不确定性，使得人们可以合理的安排明天的生活。而一旦一个法律朝三暮四的话，那么人们就无法对未来形成稳定的预期，使得法律形成的秩序崩塌，就让人无法安排未来的生活，从而提高了生活的不确定性。大部分人是害怕不确定性的，人类在高度不确定性的环境中，压力会很大，精神会很痛苦。

 

还是举例子，如果今天的交通规则规定大家开车都走右边，而明天就突然规定要改走左边，那大家就会很无所适从，最后人们只能抛弃法律，按照惯例行为。企业家们，也常常不得不面对的各种政策不确定性，包括产业政策，税收政策，以及其他种种管制政策，例子就不举了，最近大家也都看到了。

 

从另一个角度看，良法本身也应经得起时间的考验，所以表现的稳定，历久弥新。美国联邦宪法从制定至今，已经有两百多年历史，整个架构基本上没变，只是多了二十七条修正案而已，堪称稳定法律的典范。

 

而恶法则常常不得不朝令夕改，徒增许多不确定性。2016年出台的股市熔断机制，在刚一出台就造成股市巨大的动荡，从1月4号出台，到1月7号叫停，成为了最短命的股市机制。那么如何避免这种不必要法律造成的动荡和不确定性呢？这是一个很大的话题，其中涉及到人类的有限理性，良好并被严格执行的立法程序，灵活的法律选择淘汰等机制，这里就不再细说。

 

当然社会本身也在不断的变革之中，彻底稳定的法律，也是一种僵化，很可能不再适应当前的社会，特别是在中国目前的大转型时代，如何平衡好保守和变革，一直是改革的核心问题之一。

 

3. 一条法律规则，不应该同其他法律相互矛盾，不能有一条法律要求我们做一件事，而另一条法律则要求我们做相反的事，导致无论我们如何行事，都无法避免的违反法律。其实这一条是隐含在上述第一点中的，自相矛盾的法律，本身就是强人所难的法律，不具有可行性。当然，这一条虽然看上去简单，但其实还是很难完全实现的，因为在一个复杂的管理型国家里，存在数以千计的不同规则和管理计划，在这么多规则中，我们只能尽量减少法律彼此间的冲突，而不太可能完全消除。

 

4. 法律应该是前瞻性的，而非溯及既往的。这个原则表现在国家不能用当前的法律处罚人们过去从事的当时是合法而当前是违法的行为。也就是说，法律不能“秋后算账”。这个原则本身也是对国家权力的一种限制。一旦一个国家有权力通过现在的法律，对过去合法的事情进行惩戒，那么现在任何合法的行为，在未来都可能成为不合法的事情，这就大大增加现在行为的不确定性。

 

对于产权的保护，这点尤为重要。人们在当下合法辛辛苦苦赚来的钱，买的房子和地产，不应该在未来的一直法令面前，突然间灰飞烟灭。如果真存在大概率这种可能，人们可能就不会太努力去创造财富，也不敢做长期的投资，经济的发展必然受到抑制，同时人民也讲长期生活在恐惧之中。

 

5. 法律的目的应该是良善的，但同时法律也需要能达到它自身立法时之目的。法律不会自动完成其立法时的目的。这里重点论证“法律应该是能达到其立法目的”。The road to hell is paved with good intentions，通往地狱之路，由善意铺就。这个世界上有许许多多的政策，其目标是好的，但结果往往灾难性的。

 

大锅饭集体公社，目地是消灭不平等，大家共同富裕；而最后实际导致的结果却是粮食产量下降，严重的饥荒。最低工资法，目标是保护工人弱势群体，让他们拿到更高的工资，而最后实际的结果却常常是，那些最弱势的，最缺乏技能的工人，失业找不到工作。交通法规里，为了照顾“行人”这个弱势群体（不知道为何行人就是弱势群体了，难道是因为没有车？），常常出现即使司机无过错，行人闯红灯，但依然让司机负相当的责任。虽然这样司机有很大的积极性去避免事故，但行人却缺乏对应的激励，认为反正你撞了就要赔钱，反而不那么小心避免事故了。

 

劳动法中，充满了各种对员工的保护，然而越保护，雇工越不自由，老板就越不敢雇工，失业就越多，经济就会收到很大的影响。国内许多经济学家对2008年出台的新《劳动法》都意见很大，特别是张五常教授，他认为中国最近10年的经济增速放缓，劳动法要背主要的锅。

 

另外，还有田园女权们争取的各种对女性的优待，也常常使得企业不敢雇佣女员工。比如，要求产妇要休更长的假，甚至为了平等，要求男性也跟着一起休假。首先，产妇如果休更长的假，由于企业不是慈善机构，就只能尽量避免雇佣生育期的女性，由此也导致女性更难找工作；而一旦女性的经济不够独立，往往就更容易受制于男性，造成女性在家庭地位中的弱势，反而更不利于女性权利的伸张。而有人提出，为了避免这种情况，男人也应该跟着一起休假，这想法虽然听起来很美，但问题是一旦问“谁”负责出钱时，真正的麻烦才出来了。

 

在机制设计理论中，一个政策如果要达到它的目标，要符合参与约束和激励相容约束。一般而言，一个国家的法律，除非你移民，否则你是不得不参与其中的。但当一国内部有很大问题时，该国那些有能力移民的精英常常会选择移民，即”不跟你玩了“，所以一国法律，要想达到它的目的，首先要基本符合参与约束。其次，所谓的激励相容约束，是指在政策框架内，参与人按照自身利益最大化行动时，恰好符合政策所要的结果。

 

上面的那些例子中，大多都不符合激励相容约束，大锅饭集体公社的参与者们，最大化自身受益的行为是”偷懒，吃饭的时候多吃点，不注意节约“，结果导致粮食减产和饥荒；最低工资法之下，当最低工资高于市场出清工资时，企业主们最大化自身受益的行为是”那些无法创造出比最低工资价值更高的员工，我不雇佣“，结果是那些真正的弱势群体，原本虽然只能拿到更低工资，但依然有人雇佣的人，现在没人雇佣了，也无法通过被雇佣而获得更多的实践机会，在未来获得更高的工资。

 

最后，除了以上几点，一个法律的诞生，还需要符合对应的立法程序，以确保其自身的合法性。在生效时，它应该被完整清晰地公布出来，而不是被锁在一个黑暗角落的保险柜中，等着别人违反后拿出来，提着笼子到处抓人。当然，本文算是很粗略的谈关于何谓良法的一些观点，不保证完整，也不保证正确。实际上，这是一个很复杂的问题，值得我们去深入思考。一般而言，聊完何谓良法，很想聊聊何谓良政，不知道会不会太敏感。

 

总结一下：1.不强人所难，考虑当时的环境限制；2.在时间维度上有相对稳定性；3.不与其他法律相互矛盾；4.是前瞻的，不溯及既往；5.目的是良善的，而且要却是能达到其目的；6.符合立法程序，确保其自身合法性；7.被清晰完整的公布出来。

 

以上，谢谢。