---
title: 美国才是抗日的中流砥柱
author: 韩连潮
date: '2021-12-06'
slug: '342'
categories:
  - Translation Articles
tags:
  - History
  - America
  - China
---

[Source](https://www.voachinese.com/a/hanlianchao-us-/2931177.html)

>今天连发的几篇文章都是为了让大家警惕商业宣传、政治宣传、个人宣传，要能够独立的收集数据进行分析，要永远小心谨慎。

1945年9月2日上午9时( 美国时间9月1日)，200多艘盟军军舰停泊在日本东京湾，海湾上空黑云压顶，然而在美军的密苏里号战舰上，参加日本投降仪式的盟军将领和美军官兵的胜利喜悦之情溢于言表。

在盟军最高统帅、美国五星上将麦克阿瑟的主持下，日本外相重光葵代表天皇和日本政府、日军参谋总长梅津美治郎代表日本大本营首先在《降伏文书》签字。9点22分，最后一名盟国代表签署完毕，正式结束了人类历史上最为惨烈的一次杀戮。

瞬时，太阳破云而出，阳光普照海湾，1200余架美国海军、陆军和海军陆战队战机和轰炸机马达轰鸣，以壮观整齐的编队飞越密苏里号战舰，再一次展示盟军的军事实力，庆祝二战胜利。

美国战机和轰炸机编队飞越密苏里号战舰

70年来，人们从二战的悲剧中吸取了许多教训，学习到无数宝贵的经验，建立了新的国际秩序和规则，尽管各国的武装冲突仍时有发生，但这一体系基本有效地维护了世界和平，创造了经济繁荣，提高了各国人民的生活水平。

然而，这些年来，仍然不断有人企图重新改写这段历史，他们有的将侵略者说成受害人，有的将贪天之功据为己有，夸大自已在战争中的作用和贡献。但谎言终究是谎言，事实胜于雄辩：美国才是抗日的中流砥柱。

这一看法是基于一个不可否认的历史事实：既不是中国，也不是苏联或其他任何国家，而是美国战胜了日本。

根椐美国国会研究所资料，在日本偷袭珍珠港之后短短的3年多的时间里，美国动员了1611万人参军参战，同时在欧洲、亚洲两线作战，伤亡67万人，其中死亡人数40余万(战死人数近30万人），在亚太战死人数达10万人之多。

这个数字与苏联和中国军人在二战伤亡人数相比似乎微不足道，但在西方所有盟国中则是最高的。更重要的是，牺牲和贡献并不一定成正比。美国的领导作用，工业能力，科技创新和军事实力奠定了二战胜利的基石。我们可以从以下几个方面来论证美国抗日的中流砥柱作用。

首先，美国是抗击日德法西斯的世界兵工厂。我们知道，美国在极短的时间里进行大规模的战时动员，生产了150艘航母，12万艘其他各类的舰船，30万架飞机，10万辆坦克和装甲车，，240万辆各种车辆，大炮和榴弹炮4万多门，260万挺机关枪，子弹410亿发。到1944年，包括中国在内的同盟国三分之二的军事装备和物质是由美国生产提供的。美国生产制造的飞机比日本和德国生产总合还要多出一倍（美国国家二战博物馆资料）。

其次，美国消灭了日本帝国赖以生存的海军。从中途岛海战开始，美国转向进攻日本海军，日美两国在太平洋进行了史无前例的大海战，其结果是美国大败日本，掌握了制海权。美国陆海军联合评诂委员会资料显示，美国共击沉了611艘日本海军军舰(其中包括日本25艘航母中的21艘，以及仅有的2艘超级战列舰），2117艘商船，总顿位达974万吨，并将40万日本海军官兵葬送入太平洋海底。其他盟军海军共击沉了45艘日本海军舰船，73艘商船，总吨位28万吨。中国海军在二战期间唯一的战绩是击沉了3艘日本商船。

美国对日本海军的致命打击，不仅使日本无法在整个太平洋投射军事力量，而且还切断了日本战略物质运输补给线，大大削弱了日本军工生产能力和前线作战能力，并让日本本土暴露在美军的火力打击之下，确定了日本必败的战略格局。

失去制海权导致日本出现能源危机。石油是保持日本战争机器运转的必需品，美国通过破译日本海军密码，对日本在南太平洋地区的石油生产和运输了如指掌，因而派出潜艇和飞机对油轮和油田实施打击和轰炸，有110艘日本油轮被美国潜艇击沉。1942年夏，美国还击沉了载有去南洋工作的1000名石油专家的＂大洋丸＂邮轮，几乎导致日本石油技术人员全军履没。美国的打击致使日本出现燃油短缺，战争机器运转失灵。据报道，日本投降后，美国士兵奉命前往首相官邸捉拿东条英机，发现他自杀未遂，他们花了两小时居然找不到一辆有油的救护车将其送医院抢救。由于缺乏战略物资，战争结束前期新组建保卫日本本土的众多师团无法获得装备。

出任过日本首相和日本海军大臣的米内光政海军大将曾表示，日本1942年11月在瓜达尔卡纳尔海战中失利败于美国而之后，军中有识之士已经认识到日本此次战争必输无疑，因为日本丧失了制海权，只有坐以待毙。

第三，美军在海战的同时，也给予日本空军以毁灭性地打击。美国用损失14533架战机的代价换来了消灭了2万架日本战机的成果（艾里斯:《二战数据统计》，1993）， 取得了空中优势，使其能够直接轰炸攻击日本本土战略目标、运输补给线和地面部队。

总部设在昆明、前身为飞虎队的美国第14航空队是唯一一支在战区内组建和作战的空军部队。为了援华，他们飞越世界屋脊，空运了65万吨中国急需的军用物资。在执行驼峰航线任务的过程中，美国空军500多架飞机失事坠毁，468个美国机组牺牲。战争结束时，第十四航空队在华有2万美军和1000架飞机。尽管有种种限制，该部队击落和重创了2908架日本飞机，而己方飞机只损失193架。他们还击沉击毁了210万吨位日本商船和99艘军舰，以及18000艘运送军队和补给的小型内河船舶。第十四航空队还炸毁了1225辆火车机车，817座桥梁，4836辆卡车，击毙了近6万日军，完全掌控了中国战区的制空权(历史网资料），有效地阻止了日本的进攻。日本第6方面军曾判定，由于美空军的打击，使其燃料严重匮缺，铁路运输线行将崩溃，他们将不得从中国南部撤退。

第四，美国歼灭了日本陆军生力军。美国歼灭日军的数量大大超过了任何其他国家。据美国陆军参谋长报告，自珍珠港事件到战争结束，东方战线上共歼灭 ( 仅包括战斗中击毙、击伤造成终身残废、俘虏的人数，不包括非战斗死亡和减员）日军150万余人，其中中国战场约占百分之十七，印缅战场占百分之十一，余下百分之七十二均为美国单枪匹马所歼灭。战斗中死亡的日军近百分之八十是由美军击毙， 中国战场击毙的日军只占总数的百分之十；日本皇军在海外最精锐的师团，大部分也为美军所歼灭。

第五，美国还通过科技创新发明了原子弹，从根本上改变了战争格局。不管历史修正主义者和反核人士如何臧否诟病核武器的使用，都无法否定其在促使日本投降中所起的作用。我们知道广岛和长崎是日本军事要地：广岛是前中国派遣军司令畑俊六领导的第二总军司令部所在地，该部队负责日本南部的保卫。此外，广岛还是日本军事通讯中心、战略物资储存点和部队集散地；长崎则是日本最重要的军事工业基地，为日本战争机器生产弹药、军械和军舰以及其他重要军工产品。美军在日本投降前6个月的战斗伤亡是前3年战争的总数，越接近日本本土，日军抵抗越顽强。美国为了减少伤亡，争取日本尽快无条件投降，防止苏联介入，不得已使用原子弹。正是因为美国的原子弹炸毁了广岛和长崎，才使裕仁天皇痛下决心，接受波茨坦公告，结束战争。

综上所述，可见美国无愧于抗日中流砥柱的称号。事实上，无论有无苏联对关东军的牵制，中国对支那派遣军的牵制，美国击败日本只是早晚的问题。

由于中国并不是抗日的主战场，尽管中国军民浴血奋战，尸山血海，但并未改变抗日的战略格局。相反，没有美国的援助，尤其美国跨岛作战的胜利，迫使日本投降，中国很可能已彻底被日本所灭。完全可以说中国抗战胜利仅仅是美国战胜日本的副产品，日本并不是中国而是美国的手下败将。这也是一些日本人始终对中国不买账的原因。

太平洋战争爆发初期，美国对中国寄予了很大的期望，以为中国作为一个大国能对抗战作出重大贡献，美国可以借重中国广阔的地域和丰富的人力，使中国成为进攻日本本土的基地，而严酷的现实使美国人失望，不得不放弃不切实际的浪漫想法。美军军史资料显示，美国认为中国国民政府、地方势力和共产党各怀鬼胎，并不齐心协力抗日; 政府和军队效率低下，腐败无能，无法承担抗日重任，因此，美国调整了战略，将重点放在跨岛作战，同时也降低了对中国的期待值，只求中国不与日本媾和，能够坚持抗战即可。

日本的中国派遣军1941年有60万人，到1945战争结束时发展到105万人，屡战屡胜，占领了大半个中国，造成了320万中国军人丧生的惨状，日本投降时并未显现任何败象。中国派遣军最后一任司令冈村宁次称，日本投降的消息尤如晴天霹雳，因为“中国派遣军与其他方面军不同，前后八年百战百胜，至今（指奉命投降时）尚保持了足以战胜敌人之力量，而今竟以本国业已投降而不得不投降，确实面临异常尴尬的场面。前线部队未能全面收听8月15日天皇广播，据说不少人还以为圣谕广播是让他们更加努力进行奋战！”

冈村的说法不无道理。抗战胜利前夕，日本派遣军为了清除美国在华空军基地，减少美机对日本本土的轰炸，于1944至1945年初实施了一号作战计划，对河南、湖南和广西发动进攻，尽管中国战区的制空权已为美国掌握，国军又在数量上大大超过日军，但在日军凌利的攻势下仍溃不成军，造成大片国土丢失，使美军在华的36个空军基地丧失殆尽。所幸的是，美国在跨岛作战中取胜，将空军基地转移到更近日本的马里亚纳群岛，继续对日实施轰炸。

整个抗战期间，中国军队打得最好的一次战斗是日军在华发动的最后一次战役 －－芷江作战（1945年4月至6月），双方打成平手。不过，这场战斗只是日军第二十军发动的区域性攻势，参战人员为3个师团共6万兵力，旨在占领芷江机场。中方投入兵力60万。战斗中，日军116师团击溃了国军的4个军，美国紧急空运其一手训练和装备起来的新六军和其他“阿尔发”部队，并且派出4000美军顾问直接下到连队参战，加上现代化通讯和后勤补给，尤其是第14航空队的空中强力支援，才终于击退了日军的进攻，迫使日军退回原驻地。日军1,500人被击毙，5,000人受伤。中国军队6,800 人牺牲，11,200 受伤（美国军史资料）。这是抗战以来国军所取得的最佳战绩。

早在1942年，日本的中国派遣军拟实施五号作战计划, 准备从日本本土、满洲和朝鲜派出36万作战部队增援中国派遣军，旨在一举攻陷中国设在重庆的临时首都，彻底击溃国民党的抵抗。但是由于美军与日军在南太平洋瓜岛上的激烈争夺战，牵制了日军，消耗了其资源，致使五号作战计划因得不到所需的兵员和30万吨的军事物资而不得不放弃。

1944年底，冈村宁次担任中国派遣军司令之后，为了减轻日本本土的压力，再次建议展开四川战役，消灭重庆政府，但日军大本营因美军会在日本登陆作战而否定了冈村的四川作战计划。美军又一次保全了重庆政府。

国民党和共产党在谁是抗战的中流砥柱问题上都有不实之词。中国军队当时拥有4、500万的兵力，是世界上最大的军队，然而，在日寇几十万人的进攻之下，溃不成军，八年抗战不能收复一座重要城市，全歼日军一个联队（团）。相反，大量的官兵投敌。据冈村宁次透露，在抗战胜利前夕担任中国派遣军司令末期的短短几个月中，居然有40万国民党军队＂归顺＂。从1942春到1943年秋，整个华北地区的国民党军全部投敌。其他地区也普遍存在大批地方国军投降的情况。

抗战中，中国政府采取的黄河花园口决堤、抓壮丁、焦土抗战等措施，给中国人民带来的灾难可能远甚于日军的杀戳。尽管如此，中国在蒋介石委员长在领导下，虽然在军事上未能战胜日军，却没有向日本屈服媾和。连日军也承认与之对阵的主力是国民党中央军，尤其是黄埔系国军，而不是共军。虽然关东军和中国派遣军都将一些精锐师团调住太平洋战场，但中国的确牵制了中国派遣军的大部分兵力。尽管这对击败日本的战略意义并不重要，但可能相对减少了美军的伤亡。

中共声称自己是抗日胜利的关键更是滑稽可笑。中共按斯大林的指示，利用帝国主义战争，壮大自己力量，夺取政权，取得无产阶级革命胜利，所以在整个抗战期间，中共军队基本上是游而不击，坐收渔翁之利。

中共吹嘘得最历害的平型关大捷，只是偷袭日军一个运输队而已。中共虽然在百团大战中打了一些硬仗，但也只是攻击了一部分小股分散的日军，并未与日军主力交锋，对整个战局没有产生太大影响。

中共敌后游击战的实际情况在其将领吴法宪的回忆录中可见一斑。吴任政委的115师685团是中共的精锐部队，参加过平型关战斗，1938年进入江南敌后区，从3千多人迅速发展到1万2千人，后编入新四军第3师，全师从2万人发展到7万多人。所进行的5000多次战斗，大都是与所谓国民党＂顽军＂以及伪军争夺地盘而发生的。两次较大的所谓反扫荡，共军基本上是化整为零，东躲西藏于数量少于自己数倍的三流治安日军的追击。吴透露从1941年夏天到1942年下半年，其部队整整一年多没有打仗。从1942年下半年到1945年上半年的近三年时间里则是按延安指示开展＂整风＂运动。中共其他敌后游击区的情况大体与之相同。

中共在抗日中最大的功绩莫过于和平解决西安事变，让蒋介石先生安全返回南京领导抗战。但越来越多的证据表明西安兵谏实际上是中共一手策划，周恩来和杨虎城一个唱白脸一个唱红脸，迫使蒋先生承认中共的合法性。它的直接后果之一是让国军过早地在淞沪战役中消耗自己的有生力量，使得日后抗战举步维艰。

还有一个常常为国人忽略的历史事实是，美国是为中国主持公义，坚持要求日本从中国撤军，而受到攻击被迫卷入战争的。

日本1931年发动918事变，占领了中国东北三省之后，美国站在中国一方，谴责日本的侵略行经，拒绝承认满洲国，并对日本实施了有限制裁。由于民意不赞同卷入东亚战争，同时众多官员认为美国在华利益无足轻重，加上错综复杂的中国政治现状，美国没有采取更为强硬的措施。

1937年卢沟桥事变之后，日本全面侵华导致美国民意发生逆转，美国开始挑战日本。罗斯福总统7月7日当天宣布美国的《中立法》不适用中国。美国政府一方面通过信贷和租借法案项目向中国提供战争物质，另一方面逐渐加强对日本贸易制裁。1939年7月美国通知日本终止美日贸易条约，1940年开始实行对日实行部分禁运，包括石油，钢铁等战略物资。1941年7月又实行全面禁运，并进一步冻结了日本资产。但是，由于军事上没有准备，美国政府和军队都不想介入与日本的直接武装冲突和战争，还是希望通过外交谈判解决问题。

由于百分之八十的日本石油依赖美国进口，美国的禁运给日本侵略战争带来巨大困难。为了攫取战略资源，继续发动侵略战争，日本决定南进，占领印度支那和南太平洋产油地区。而日本知道美国太平洋舰队的存在，让其无法保障南方战略资源基地。因此1941年7月的御前会议批准了南进的作战计划，随后又批准和实施了由哈佛毕业生山本五十六海军上将领导制定的偷袭珍珠港计划。

与此同时，美日继续外交谈判。美国坚持解除禁运的的一项主要条件是日本必须从中国和印度支那撤军。但日本根本没有意愿从其占领的中国土地上撤出，导致谈判陷于僵局，日本领导人因而作出美国没有诚意外交解决的判断，决定日军必须迅速行动打击美国海军。而美国领导人则认为谈判尚有可能，日本缺乏军事实力直接攻击美国领土。在日本1941年12月7日成功偷袭珍珠港之后，美国举国上下震惊，决心还击日本。这是太平洋战争爆发的根本原因。

然而，战后相当多的阴谋论人士和历史修正主义学者认为罗斯福总统在美日关系上玩弄阴谋诡计，诱使日本上勾，袭击珍珠港，引发太平洋战争，为美国参加二战找到口实。日本靖国神社中关于二战起因解说词也一直坚持这个说法，2007年才被摘下。这一说法不符合历史事实，本质上是为侵略者开脱罪责。因为从笔者读到的历史资料来看，虽然罗斯福总统收到不同渠道的警告，但是没有一条情报准确地指出日本会在何时何地攻击美国目标。毫无疑问，日本发动侵略战争是其军国主义本性所决定的。

另一说法是，日本的投降是苏联出兵满洲的缘故，并不是美国使用原子武器的结果。这也是无稽之谈，其目的在于谴责美国没有必要使用不人道的大规模毁灭性武器。事实上，8月8日，广岛被炸第三天，外相重光葵进宫觐见天皇，报告了从外台汇集的有关原子弹的信息，天皇当即决断终止战争，而东京8月10日才知道苏联出兵东北的消息。此外，日本当局对苏联参战的震惊，不是因为惧怕和苏联交手，而是因为其要求苏联保持中立，与美国斡旋日本有条件投降的期待破灭所致。

总之，无论中国抗战多么悲壮惨烈，多么可歌可泣，付出的代价多么惨重，中国未能在抗战中取胜是不容置疑的事实。整个一部抗战史是中华民族的耻辱史、血泪史。不直面这一残酷的历史事实，把头埋在地里，屁股翘到天上，妄自尊大，化友为敌，甚至不惜篡改抗战历史，为自己一党执政的合法性背书，向周边国家示威显狠，打着和平的旗号反和平，就不可能真正从二战中吸取教训，反而会重蹈日本军国主义的覆辙。

美国在中华民族存亡之际拯救了我们的国家和人民，没有占领中国的一寸土地，也未从中国获得任何特殊利益，功莫大焉。我们应当感恩戴德，与美国建立长期的同盟关系，认同普世价值和民主宪政，内治修好，外施王道，化干戈为玉帛，共同维护战后的国际关系和世界和平。这才是我们纪念二战胜利，反思历史和缅怀先烈的真谛和应持的态度。