---
title: 'Book Review: Make it Stick'
author: Guanghua Mao
date: '2022-01-18'
slug: '373'
categories:
  - Original Articles
tags:
  - Book Review
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

>原来我的学习方法很低效

Remember that the most successful students are those who
take charge of their own learning and follow a simple but
disciplined strategy. You may not have been taught how to do
this, but you can do it, and you will likely surprise yourself
with the results.

Embrace the fact that signifi cant learning is often, or even
usually, somewhat difficult. You will experience setbacks.These
are signs of effort, not of failure. Setbacks come with striving,
and striving builds expertise. Effortful learning changes your
brain, making new connections, building mental models, increasing your capability. The implication of this is powerful:
Your intellectual abilities lie to a large degree within your
own control. Knowing that this is so makes the difficulties
worth tackling.

Following are three keystone study strategies. Make a habit
of them and structure your time so as to pursue them with
regularity.

# Practice Retrieving New Learning from Memory

What does this mean? “Retrieval practice” means self-quizzing.
Retrieving knowledge and skill from memory should become
your primary study strategy in place of rereading.

How to use retrieval practice as a study strategy: When you
read a text or study lecture notes, pause periodically to ask
yourself questions like these, without looking in the text: What
are the key ideas? What terms or ideas are new to me? How would I defi ne them? How do the ideas relate to what I already know?

Many textbooks have study questions at the ends of the
chapters, and these are good fodder for self- quizzing. Generating questions for yourself and writing down the answers is
also a good way to study.


Set aside a little time every week throughout the semester
to quiz yourself on the material in a course, both the current
week’s work and material covered in prior weeks.


When you quiz yourself, check your answers to make sure
that your judgments of what you know and don’t know are
accurate.

Use quizzing to identify areas of weak mastery, and focus
your studying to make them strong.
The harder it is for you to recall new learning from memory, the greater the benefi t of doing so. Making errors will not
set you back, so long as you check your answers and correct
your mistakes.

What your intuition tells you to do: Most studiers focus on
underlining and highlighting text and lecture notes and slides.
They dedicate their time to rereading these, becoming fluent
in the text and terminology, because this feels like learning.


Why retrieval practice is better: After one or two reviews of
a text, self- quizzing is far more potent for learning than additional rereading. Why might this be so? This is explained
more fully in Chapter 2, but here are some of the high points.


The familiarity with a text that is gained from rereading
creates illusions of knowing, but these are not reliable indicators of mastery of the material. Fluency with a text has two
strikes against it: it is a misleading indicator of what you have
learned, and it creates the false impression that you will remember the material.


By contrast, quizzing yourself on the main ideas and the
meanings behind the terms helps you to focus on the central precepts rather than on peripheral material or on a professor’s turn of phrase. Quizzing provides a reliable mea sure of
what you’ve learned and what you haven’t yet mastered. Moreover, quizzing arrests forgetting. Forgetting is human nature,
but practice at recalling new learning secures it in memory and
helps you recall it in the future.

Periodically practicing new knowledge and skills through
self-quizzing strengthens your learning of it and your ability
to connect it to prior knowledge.


A habit of regular retrieval practice throughout the duration of a course puts an end to cramming and all-nighters.
You will need little studying at exam time. Reviewing the material the night before is much easier than learning it.



How it feels: Compared to rereading, self- quizzing can feel
awkward and frustrating, especially when the new learning is
hard to recall. It does not feel as productive as rereading your
class notes and highlighted passages of text feels. But what
you don’t sense when you’re struggling to retrieve new learning is the fact that every time you work hard to recall a memory, you actually strengthen it. If you restudy something after
failing to recall it, you actually learn it better than if you had
not tried to recall it. The effort of retrieving knowledge or skills
strengthens its staying power and your ability to recall it in
the future

---

# Space Out Your Retrieval Practice

What does this mean? Spaced practice means studying information more than once but leaving considerable time between
practice sessions.

How to use spaced practice as a study strategy: Establish a
schedule of self- quizzing that allows time to elapse between
study sessions. How much time? It depends on the material. If
you are learning a set of names and faces, you will need to review them within a few minutes of your fi rst encounter, because these associations are forgotten quickly. New material
in a text may need to be revisited within a day or so of your
first encounter with it. Then, perhaps not again for several
days or a week. When you are feeling more sure of your mastery of certain material, quiz yourself on it once a month. Over
the course of a semester, as you quiz yourself on new material,
also reach back to retrieve prior material and ask yourself
how that knowledge relates to what you have subsequently
learned.


If you use fl ashcards, don’t stop quizzing yourself on the
cards that you answer correctly a couple of times. Continue
to shuffle them into the deck until they’re well mastered. Only
then set them aside— but in a pile that you revisit periodically,
perhaps monthly. Anything you want to remember must be
periodically recalled from memory.

Another way of spacing retrieval practice is to interleave the
study of two or more topics, so that alternating between them
requires that you continually refresh your mind on each topic
as you return to it.

What your intuition tells you to do: Intuition persuades us
to dedicate stretches of time to single- minded, repetitive practice of something we want to master, the massed “practicepractice-practice” regime we have been led to believe is essential for building mastery of a skill or learning new knowledge.
These intuitions are compelling and hard to distrust for two
reasons. First, as we practice a thing over and over we often
see our performance improving, which serves as a powerful
reinforcement of this strategy. Second, we fail to see that the
gains made during single- minded repetitive practice come from
short-term memory and quickly fade. Our failure to perceive
how quickly the gains fade leaves us with the impression that
massed practice is productive.

Moreover, most students, given their misplaced faith in
massed practice, put off review until exam time nears, and then
they bury themselves in the material, going over and over it,
trying to burn it into memory.

Why spaced practice is better: It’s a common but mistaken
belief that you can burn something into memory through sheer
repetition. Lots of practice works, but only if it’s spaced.


If you use self- quizzing as your primary study strategy and
space out your study sessions so that a little forgetting has
happened since your last practice, you will have to work harder
to reconstruct what you already studied. In effect, you’re “reloading” it from long- term memory. This effort to reconstruct
the learning makes the important ideas more salient and memorable and connects them more securely to other knowledge
and to more recent learning. It’s a powerful learning strategy.


How it feels: Massed practice feels more productive than
spaced practice, but it is not. Spaced practice feels more difficult, because you have gotten a little rusty and the material is
harder to recall. It feels like you’re not really getting on top
of it, whereas in fact, quite the opposite is happening: As you
reconstruct learning from long-term memory, as awkward as
it feels, you are strengthening your mastery as well as the
memory.


---

# Interleave the Study of Different Problem Types

What does this mean? If you’re trying to learn mathematical
formulas, study more than one type at a time, so that you are
alternating between different problems that call for different
solutions. If you are studying biology specimens, Dutch painters, or the principles of macroeconomics, mix up the examples.


How to use interleaved practice as a study strategy: Many
textbooks are structured in study blocks: They present the solution to a partic ular kind of problem, say, computing the volume of a spheroid, and supply many examples to solve before
moving to another kind of problem (computing the volume of
a cone). Blocked practice is not as effective as interleaved practice, so here’s what to do.


When you structure your study regimen, once you reach
the point where you understand a new problem type and its
solution but your grasp of it is still rudimentary, scatter this
problem type throughout your practice sequence so that you
are alternately quizzing yourself on various problem types and
retrieving the appropriate solutions for each.


If you fi nd yourself falling into single- minded, repetitive
practice of a partic ular topic or skill, change it up: mix in the
practice of other subjects, other skills, constantly challenging
your ability to recognize the problem type and select the right
solution.

Harking back to an example from sports (Chapter 4), a
baseball player who practices batting by swinging at fifteen
fastballs, then at fi fteen curveballs, and then at fifteen changeups will perform better in practice than the player who mixes
it up. But the player who asks for random pitches during practice builds his ability to decipher and respond to each pitch as
it comes his way, and he becomes the better hitter.


What your intuition tells you to do: Most learners focus on
many examples of one problem or specimen type at a time,
wanting to master the type and “get it down cold” before moving on to study another type.


Why interleaved practice is better: Mixing up problem types
and specimens improves your ability to discriminate between
types, identify the unifying characteristics within a type, and
improves your success in a later test or in real- world settings where you must discern the kind of problem you’re trying to
solve in order to apply the correct solution.

How it feels: Blocked practice— that is, mastering all of
one type of problem before progressing to practice another
type—feels (and looks) like you’re getting better mastery as
you go, whereas interrupting the study of one type to practice
a different type feels disruptive and counterproductive. Even
when learners achieve superior mastery from interleaved practice, they persist in feeling that blocked practice serves them
better. You may also experience this feeling, but you now have
the advantage of knowing that studies show that this feeling
is illusory.

---

# Other Effective Study Strategies


**ELABORATION** improves your mastery of new material and
multiplies the mental cues available to you for later recall and
application of it.

What is it? Elaboration is the process of finding additional
layers of meaning in new material.

For instance: Examples include relating the material to
what you already know, explaining it to somebody else in your
own words, or explaining how it relates to your life outside of A powerful form of elaboration is to discover a metaphor
or visual image for the new material. For example, to better
grasp the principles of angular momentum in physics, visualize how a fi gure skater’s rotation speeds up as her arms are
drawn into her body. When you study the principles of heat
transfer, you may understand conduction better if you imagine warming your hands around a hot cup of cocoa. For radiation, visualize how the sun pools in the den on a wintry

day. For convection, think of the life- saving blast of A/C as
your uncle squires you slowly through his favorite back-alley
haunts of Atlanta. When you learned about the structure of
an atom, your physics teacher may have used the analogy of
the solar system with the sun as the nucleus and electrons
spinning around like planets. The more that you can elaborate on how new learning relates to what you already know,
the stronger your grasp of the new learning will be, and the
more connections you create to remember it later.

Later in this chapter, we tell how the biology professor
Mary Pat Wenderoth encourages elaboration among her students by assigning them the task of creating large “summary
sheets.” Students are asked to illustrate on a single sheet the
various biological systems studied during the week and to
show graphically and through key words how the systems interrelate with each other. This is a form of elaboration that
adds layers of meaning and promotes the learning of concepts,
structures, and interrelationships. Students who lack the good
fortune to be in Wenderoth’s class could adopt such a strategy
for themselves.








**GENERATION** has the effect of making the mind more receptive to new learning.

What is it? Generation is an attempt to answer a question
or solve a problem before being shown the answer or the
solution.


For instance: On a small level, the act of fi lling in a missing
word in a text (that is, generating the word yourself rather
than having it supplied by the writer) results in better learning
and memory of the text than simply reading a complete text.



Many people perceive their learning is most effective when
it is experiential— that is, learning by doing rather than by
reading a text or hearing a lecture. Experiential learning is a form of generation: you set out to accomplish a task, you encounter a problem, and you consult your creativity and storehouse of knowledge to try to solve it. If necessary you seek
answers from experts, texts, or the Web. By wading into the
unknown first and puzzling through it, you are far more likely
to learn and remember the solution than if somebody first sat
you down to teach it to you. 


You can practice generation when reading new class material by trying to explain beforehand the key ideas you expect to find in the material and how you expect they will
relate to your prior knowledge. Then read the material to
see if you were correct. As a result of having made the initial
effort, you will be more astute at gleaning the substance and
relevance of the reading material, even if it differs from your
expectation.


If you’re in a science or math course learning different types
of solutions for different types of problems, try to solve the
problems before you get to class. The Physics Department at
Washington University in St. Louis now requires students to
work problems before class. Some students take umbrage,
arguing that it’s the professor’s job to teach the solution, but
the professors understand that when students wrestle with content beforehand, classroom learning is stronger.

**REFLECTION** is a combination of retrieval practice and elaboration that adds layers to learning and strengthens skills.

What is it? Refl ection is the act of taking a few minutes to
review what has been learned in a recent class or experience
and asking yourself questions. What went well? What could
have gone better? What other knowledge or experiences does
it remind you of? What might you need to learn for better mastery, or what strategies might you use the next time to get
better results?

For instance: The biology professor Mary Pat Wenderoth
assigns weekly low-stakes “learning paragraphs” in which students are asked to refl ect on what they learned the previous
week and to characterize how their class learning connects to
life outside the class. This is a fi ne model for students to adopt
for themselves and a more fruitful learning strategy than
spending hours transcribing lecture slides or class notes verbatim into a notebook.


**CALIBRATION** is the act of aligning your judgments of what
you know and don’t know with objective feedback so as to
avoid being carried off by the illusions of mastery that catch
many learners by surprise at test time.


What is it? Everyone is subject to a host of cognitive illusions, some of which are described in Chapter 5. Mistaking
fluency with a text for mastery of the underlying content is
just one example. Calibration is simply the act of using an
objective instrument to clear away illusions and adjust your
judgment to better refl ect reality. The aim is to be sure that
your sense of what you know and can do is accurate.


For instance: Airline pilots use fl ight instruments to know
when their perceptual systems are misleading them about critical factors like whether the airplane is flying level. Students use
quizzes and practice tests to see whether they know as much
as they think they do. It’s worth being explicit here about the
importance of answering the questions in the quizzes that you
give yourself. Too often we will look at a question on a practice test and say to ourselves: Yup, I know that, and then move
down the page without making the effort to write in the answer. If you don’t supply the answer, you may be giving in to
the illusion of knowing, when in fact you would have difficulty rendering an accurate or complete response. Treat practice tests as tests, check your answers, and focus your studying
effort on the areas where you are not up to snuff.


**MNEMONIC DEVICES** help you to retrieve what you have
learned and to hold arbitrary information in memory.

What are they? “Mnemonic” is from the Greek word for
memory, and mnemonic devices are like mental file cabinets.
They give you handy ways to store information and find it
again when you need it.

For instance: Here is a very simple mnemonic device that
some schoolchildren are taught for remembering the US Great
Lakes in geographic order, from east to west: Old Elephants
Have Musty Skin. Mark Twain used mnemonics to teach his
children the succession of kings and queens of En gland, staking the sequence and length of their reigns along the winding driveway of his estate, walking it with the children, and
elaborating with images and storytelling. Psychology students at Bellerbys College in Oxford use mnemonic devices
called memory palaces to organize what they have learned and
must be prepared to expound upon in their A-level essay exams. Mnemonics are not tools for learning per se but for creating mental structures that make it easier to retrieve what you
have learned.