---
title: The four categories of decision making
author: ' Philip Rosenzweig'
date: '2021-09-02'
slug: '295'
categories:
  - Translation Articles
tags:
  - Business
  - Decision
---

[Source](https://www.imd.org/research-knowledge/articles/the-four-categories-of-decision-making/)

>Business leaders and the complexity behind strategic decisions. 此文算得上是对 [Left Brain, Right Stuff](https://www.goodreads.com/book/show/19990883-left-brain-right-stuff?ac=1&from_search=true&qid=cn4LEfeFvM&rank=2) 一书的总结。

Decisions are a part of life and while they range in complexity, we face various decisions on a daily basis. But how can we best make decisions that lead to optimal outcomes? With an ever-growing wealth of research on the topic, decision making is being transformed into a science that can aid greatly in guiding decisions. However, undoubtedly useful in certain circumstances, the application of such research highly depends on the kind of decisions being made, especially in the business world.


There are clear limits and, to date, most decision making research applies to one type of decision, and it’s not the type that’s most challenging for managers. Their most important and most difficult decisions are strategic decisions with consequences for the performance of the company. Before managers take any advice on how to make better decisions, they must recognize how decisions differ.


Decisions vary along two dimensions: control and performance. Control considers how much we can influence the terms of the decision and the outcome. And performance addresses the way we measure success. Combining them creates four categories of decisions:



1] **Making routine choices and judgments.** When you go shopping in a supermarket or a department store, you typically pick from the products before you. Those items, perhaps a jug of milk or a jar of jam, are what they are. You have no ability to improve them. Control is low. Moreover, you make the choice that suits you best—it doesn’t matter what anyone else is buying. Performance is absolute. The same goes for most personal investment decisions. You may be able to decide which company’s shares to buy, but you can’t improve their performance after you buy them. You want high returns but aren’t trying to do better than others. The goal is to do well, not to finish first in a competition.


2] **Influencing outcomes**. Many decisions involve more than selecting among options we cannot improve or making judgments about things we cannot influence. In so much of life, we use our energy and talents to make things happen. Imagine that the task at hand is to determine how long we will need to complete a project. That’s a judgment we can control; indeed, it’s up to us to get the project done. Here, positive thinking matters. By believing we can do well, perhaps even holding a level of confidence that is by some definitions a bit excessive, we can often improve performance. Optimism isn’t useful in picking stocks whose performance we cannot change, but in the second field, where we have the ability to influence outcomes, it can be very important.

3] **Placing competitive bets**. The third category introduces a competitive dimension. Success is no longer a matter of absolute performance but depends on how well you do relative to others. The best decisions must anticipate the moves of rivals. That’s the essence of strategic thinking, which Princeton professor Avinash Dixit and Yale professor Barry Nalebuff define as “the art of outdoing an adversary, knowing that the adversary is trying to do the same to you.” Investments in stocks are typically first-field decisions, but if you’re taking part in a contest where the investor with the highest return takes the prize, you’re in the third field. Now you need to make decisions with an eye to what your rivals will do, anticipating their likely moves so that you can have the best chance of winning.

4] **Making strategic decisions**. In this fourth category of decision making, we can actively influence outcomes and success means doing better than rivals. Here we find the essence of strategic management. Business executives aren’t like shoppers picking a product or investors choosing a stock, simply making a choice that leads to one outcome or another. By the way they lead and communicate, and through their ability to inspire and encourage, executives can influence outcomes. That’s the definition of “management.” Moreover, they are in charge of organizations that compete vigorously with others; doing better than rivals is vital. That’s where strategy comes in.


The decisions to enter a new market, release a new product, or acquire another firm are all in the fourth field, but we can find many examples beyond business. In sports, a coach shapes the performance of athletes, melding them into an effective team that can outperform the opponent. Or in politics a winning political campaign depends on a smart assessment of rivals as well as the ability to mobilize supporters, often in the face of long odds.


**The constraint of decision making research**


In the course of their daily responsibilities, executives face a range of decisions, often in each of the four fields outlined here. But decision making research cannot be universally applied. When turning to research to help make better decisions, it’s critical to understand these four fields of decision making.



For first- and second-field decisions, cognitive psychologists have demonstrated that people make decisions in ways that do not conform to the tenets of economic rationality. They exhibit systematic biases, which, if surfaced, managers could use to shape routine decisions. For third-field decisions, guidance comes from the branch of economics that studies competitive dynamics: game theory. Game theory can illuminate areas from price competition to geopolitics, yet it has an important limitation: Players cannot alter the terms of the game.

So while a great deal of attention has focused on teaching executives to excel at game theory and to be aware of common biases in order to avoid their ill effects, if we apply only those lessons to the world of strategic management, we’re missing a trick.


The fourth field of decision making has a layer of complexity that doesn’t lend itself to the careful controls of laboratory experiments, so we know less about how best to make them. What sort of mind-set do they require? When we can influence outcomes, it is useful to summon high levels of self-belief. And when we need to outperform rivals, such elevated levels are not just useful but indeed essential. Only those who are able to muster a degree of commitment and determination that is by some definitions excessive will be in a position to win.




