---
title: 王川的4个投资法则
author: 硅谷王川
date: '2020-12-08'
slug: '105'
categories:
  - Translation Articles
tags:
  - Business
  - Investment
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

# [告别机会主义，去体系化地发掘和创造财富](https://mp.weixin.qq.com/s?__biz=MzA3MzE5MjM2Mw==&mid=2672246929&idx=1&sn=136dd267f6c2e14c1bd4878a7f251e3b&chksm=85a12655b2d6af434215359072edf08512d60019cecc51a52ea62e6f4aa06e584b26ff4393c6&scene=21#wechat_redirect)

（1）

我自己也没想到，回首往事时，2005年对我来说，是魔幻现实主义的元年。

我的记忆定格在六月， 亚利桑那州的凤凰城，大华中国超市的一家川菜馆。那一年我去凤凰城炒期房，有的地方新房子刚交订金，一两个月后价格就涨了十万美元。我还记得川菜馆的小二，和我的经纪人打招呼，得意地说他已经订了四套房子，每幢房都涨了好多。我的直觉有些不安，但是自己在这种炒房中已经获利，所以也想不出该做什么别的。

八月份时百度来美国上市。CNBC 记者电视上采访李彦宏，质疑上市时的高估值。李的回答大意是市场很大，一切都还是开始。此时，硅谷刚刚从2000 - 2003年这三年漫长的高科技熊市中复苏不久，我对这种回答的直觉是：极度怀疑。马东敏是我在科大少年班高两级的师姐，九七年底在硅谷还曾经一起吃过饭。现在差距这么大，如果说没有一点失落感，那是不客观的。

十二月时回国访问亲友，吃饭间大家谈到了上市一年多的谷歌。一位同学不断强调，谷歌本质上是一个媒体公司，不能够以传统科技公司的商业模式理解他的估值。席间所有人包括我，并没有理解他的话的真正含义。我半年前还曾经因为看空谷歌而买了他的 put option,刹羽而归。当然这位同学自己也没有真正重仓谷歌，不过那是另外一个话题了。

在北京和多年未见的表弟重逢，给他的见面礼是一个 iPod， 但遗憾的是，知道它的产品火爆，却一直觉得它太贵是个泡沫，我没有买过一股苹果股票。 

在表弟的住处，发现他用 QQ 和网上的朋友聊天，用各种表情符号打情骂俏,不亦乐乎。我只是把这个东西当成小孩子的玩具，却没有意识到腾讯已经在香港上市一年多，这是一个公开的唾手可得的机会，这将是未来十年回报最好的投资之一。

这时中国各大城市的房产已经连续涨了好几年，在奥运村附近看见各种场馆如火如荼的施工。要不要在北京买幢房子？这个念头，和脑海中日本房产九十年代泡沫破灭的镜头不断打架。

我在纽约的同学朋友那边，不断传来各种对冲基金经理挣几千万，几亿美元的消息，让我怀疑九十年代的互联网高科技浪潮，是否要彻底被纽约的“金融创新”所替代。三年后全球金融危机爆发，我才终于顿悟，这本质上是一堆狗屎 （以亚利桑那房地产为代表的次级贷款）包装后被金融杠杆推波助澜的结果。

（2）

如果说时光可以让我重回到 2005年，让我可以获得上帝视角，我多么希望：

1/ 有人会苦口婆心地劝说我，当时美国二三线城市的投资房的炒作，就是一个击鼓传花的游戏。不能因为绝对价格看起来比一线城市便宜很多，就以为它是一个好的投资。一线中心城市的各种资源集聚效应，是二三线城市永远无法比拟的。

2/ 有人来告诉我，互联网任何领域的龙头老大，因为极强的扩展性，一旦形成正反馈循环和复杂的生态系统，是后进者不可能在现有游戏规则下追赶的。


3/ 有人来告诉我，中国的人口红利刚刚开始爆发，中国和发达国家的差距正在缩小，以过去的经济数据，过去的 PE 来估值，是可笑的。

4/ 有人来告诉我， 增量永远比存量更重要。最大最快的增量，是最值得关注的地方。

5/ 有人来告诉我，如果一个产业的增长速度远远超过整体宏观经济的增速，要么就是别的传统产业萎缩受损，要么就存在庞式骗局。不劳而获地永动机不存在，something has to give.


（3）

我慢慢意识到，如果缺乏一个更全面，更多元化，更高，更远的感知视角，个体人在商业社会中的盲动和瞎子没什么差别。这里的几个痛点在于：

1/ 各类信息渠道噪音太多，需要有办法能够节省时间，去粗取精，较快地抓住主要矛盾。

2/ 线上和线下认识交往的人，大多认知肤浅，能力平庸，要一个个去甄别其信用和能力的成本非常高。


3/ 需要一个高效的渠道，可以和世界上各地各行各业的聪明人频繁沟通，获得不同的视角和洞见。

最终需要这个渠道，把不同行业不同地区不同视角的真实信息高效综合起来，更准确地认识客观世界，提前发现和把握世界经济科技的大趋势，抓住最大最好的机会，而规避庞式骗局的陷阱。

不解决这些痛点，后果就是人长期处于一种机会主义盲动的泥潭无法自拔，不能系统化地提升自己。

（4）

即使是曾因机会主义侥幸致富的人，如果缺乏这样的渠道和一套全面的体系，也同样会因为机会主义而散尽千金。

而拥有这个渠道后，当这个渠道的人数量越多，背景和地区越多元化，对客观世界的认知就越接近真相。

有了这个渠道，也许我会十几年前就开始摆脱偏见，重仓布局苹果，谷歌，腾讯或者百度，而且基于对底层商业逻辑的深刻理解，就渐渐对各种无聊的短期波动和媒体肤浅的负面消息无动于衷。

也许我会十几年前就抽身离开二线城市房产的投机，不再浪费时间和次贷危机重灾区的经济困难的租客纠缠各种鸡毛蒜皮的小事。

也许我就更早地规避各类机会主义的盲动，获得更多的时间去休息和安静地思考，把时间和资源聚焦在发掘世界上最好的事物上，并更早进入良性循环。

---

# [简单为王](https://mp.weixin.qq.com/s?__biz=MzA3MzE5MjM2Mw==&mid=213347311&idx=1&sn=da543c0deaffa19b6e60e2addfe26c4a&scene=21#wechat_redirect)

1977年一月，巴菲特出资三千两百万美元收购水牛城晚报。水牛城 (Buffalo)是著名的尼亚加拉大瀑布所在地，夏天风景宜人，冬天大雪纷飞。我九十年代初曾在其邻近的罗切斯特大学留学。

晚报在水牛城是第一大报，发行量是其竞争者 courier express的两倍。但晚报不发行周末版，周末的市场属于courier express。

老巴的收购动机之一在于介入周末版的竞争市场，扩大报纸盈利. 巴菲特当时个人净资产只有七千万美元左右，这笔交易是一个相当大的投资。而且不同于个人先前三十年主要在股票市场的经验，这次他是要全资收购运营一个大生意了。他信心满满，摩拳擦掌。

收购当年巴菲特立刻开始印刷周末版。面对晚报直接对其生命线的攻击，Courier express 迅速展开了对晚报的旷日持久的反垄断诉讼。期间老巴被迫多次从老家飞到水牛城出庭作证。法官的判决是迅速的，晚报可以发行周末版，但是发行营销要受到政府各种管制监控，以防止其垄断.

这个判决一年半以后才被高等法院推翻。但晚报的生意每年持续亏损，1978年亏近三百万美元，1979年亏四百六十万美元。 Courier express 日子也不好过，年均亏损近三百万美元，双方陷入惨烈的阵地战.

帮水牛城晚报运送报纸的卡车司机工会，闻到了血腥的味道，酝酿着要火中取栗。 1980年12月的一个周一，工会头子突然提出新的加薪要求，于次日清晨开始罢工，并暴力阻挠晚报雇佣其他非工会的司机送报。工会的如意算盘是，巴菲特不敢此时对工会强硬。

从巴菲特的角度来看，如果此刻退让，那报社还有雇佣关系的十二个工会势必得寸进尺，公司财政状况将恶化；但如果到周末仍无法送报，订户可能会大规模退订而使运营更加艰难。

据在场者描述，淡定儒雅如老巴者，当时也紧张得流汗。也许他那时心中无数草泥马凶猛地奔腾，这是考验一个智者，一个男人的真实品格的时刻了，老巴权衡很久，拍案而起，怒喝一声， "老子拼了! ”。

第二天老巴对工会反将了一军：如果工会周日不回来送报，水牛城晚报将彻底关门。所有人包括卡车司机都会被解雇。巴菲特将会蒙受巨大的损失，但对于卡车司机而言，则是彻底砸了饭碗, 没得吃了。

最终工会在巨大压力下放弃了无理要求。晚报的运营继续亏损，在衰退的经济中和对手又死磕了将近两年。突然，1982年九月，courier express 宣布由于无法继续承受亏损，将永久关门。形势急转直上，晚报一家独大的第一年，净赚一千九百万美元。到八十年代末晚报一年利润四千万美元，远超过老巴最初的三千两百万美元的买价。

三十多年后的2013年，巴菲特参股投资3G Capital 收购 Heinz, 用可转股债券方式，拿9%利息，但是运营工作和主要风险是老巴的一个合作伙伴，巴西大亨雷曼承担。 交易公布时老巴淡淡地感叹一句， "Any partnership that does not require me to do any work is my kind of partnership". "任何不需要我做任何工作的合作方式就是我最钟情的合作方式". 

我想，他说这句话时，一定又忆起那个大 雪纷飞的十二月，那个威胁要停止送报的工会头头，那个有可能要把接近自己百分之五十身家的资产清零的夜晚，那个区别男人和男孩的瞬间。他接受了考验，但那 刻骨铭心的经历使他重新审视自己投资布局的方式。

尽管后来水牛城晚报的投资回报很好，但是值得他耗神和无下限的对手撕咬吗？值得他冒着公司破产的风险，亲自和工会缠斗吗？值得他的家庭生活被严重干扰，一次又一次的飞到水牛城调解各方面矛盾，出庭作证吗？

回到本文的主题：

王川投资第一法则是： 如果你可以用简单直接的方式投资获利，就不要用复杂费力的方式去投资。

仔细把这句话重复一下，想想有没有说你自己。看看周围，有多少人挖空心思较尽脑汁为去寻找更高的回报，去从事耗时费神自己不胜任的活动而伤痕累累。

可以一剑封喉，就不要多余的花拳绣腿 ；

可以用简单算术获利，就不要去搞复杂数学模型，在 N 阶导数的计算中去捡钢镚.

可以用国债获利，就不要浪费时间分析公司报表技术曲线炒股票.

可以用股票获利，就不要去当天天修马桶刷油漆买材料，“房客虐我千百遍，我爱房客如初恋“的苦命房东。

可以长期持有获利，就不要猜测市场短期走动，频繁交易忙得不亦乐乎，最后获利微薄，还要每年交30%以上的税给政府。

可以交给可靠的团队管理公司，分担风险，就不要亲自赤膊上阵参与公司运营。

---

# [趋势为王](https://mp.weixin.qq.com/s?__biz=MzA3MzE5MjM2Mw==&mid=213071891&idx=1&sn=991f2df8494538a1006783081278e089&scene=21#wechat_redirect)

你有没有过一个经历，多年以前你会纠结某一个小事，比如某一个客户没有搞定，一笔交易少赚了钱，一次考试没有考好。你会纠结自己没有考上中科大，北大，清华, 而上的只是杭州师范学院，深圳大学或者1914年的湖南第一师范学校.

但回头看这些事完全无足挂齿。如果你做的事大方向是对的，尽管小处有失误有曲折，完全没关系。但如果你在一个夕阳产业或者增长缓慢的行业，大方向不利于你，不管你如何勤奋，都是在白费力.

王川投资第二法则就是： “如果三十年后的趋势很明显，就不要纠结短期的变化逆势而动”.

凡是违反这个法则的操作者，最后都亏得很惨。过去二十年比较有代表性的例子是传统纸质媒体被互联网媒体的颠覆，传统胶卷照相行业被数字相机的颠覆。顺应这个法则进行前瞻性的投资，则会顺风顺水，赚得盆满钵满.

今天王川投资第二法则的一个最重要的现实的例子是，能源价格未来三十年会不断下降，甚至接近免费。你的所有和能源有关的投资很可能血本无归。凡是以能源为主要成本的产业，价格将会大大下降，世界上大部分物质资源将会更加丰富而贬值.

这个结论的主要依据是，光伏太阳能将作为一个主要能量来源，随着技术进步，价格将不断下降，把其他能源产业的价格一起拉下马.

1979年适逢美国如火如荼的能源危机，卡特为了表示政府对清洁能源产业支持的决心，下令在白宫房顶上安装了32块太阳能板。那时候太阳能板平均一瓦特能量成本七十多美元，极昂贵不经济。两年后里根上台第一件事就是下令把这些太阳能板拆了。

今天太阳能板价格已经降到了一瓦特36美分。其价格的下降曲线，非常类似芯片业的摩尔法则，业界有一个总结，叫做swanson's law (斯万森法则), 大意是随着太阳能铺设容量的增加，太阳能板的价格平均 3-4年会下降一半.

太阳能还有一个好处，边际成本为零。安装设备和太阳能板的费用是固定的一次性的，但太阳能板的寿命一般至少十年以上，维护费用几乎为零，安装好以后，能量取之不竭。不像石油和天然气，还要考虑传输的费用和原材料价格的波动.

今天太阳能板在有些地区的住宅安装发电成本已经低于当地市电价格，达到了所谓“市电平价”的水平，这个趋势将会愈演愈烈，把其他能源产业包括天然气，核电，风电，水电慢慢吞噬.

在电池存储技术方面，技术进步也有类似的规律，大约每十年电池存储能量密度会翻一番。这一切，都在为电车彻底超越汽油车奠定了基础.

想象一下，在2020 - 2030年间的某一天，突然彻底变天了。电车变得比汽油车更便宜，充电也一样方便快捷，充满电续航能力可以远超五百公里，传统汽油车销量开始崩溃，汽油价格跌到三十年前的水平.

大量二手汽油车白送也没人要，许多汽油车的维修店不得不关门。传统石油业产业链严重萎缩，德州和美国西部一些依赖石油产业的地区房地产价格大幅跳水。中东，加拿大和俄国和其他产油国经济也势必严重衰退.

你觉得你现在在能源方面的投资会有好的回报吗?

有的读者可能还会说，即使你说的长期趋势是对的，因为这样那样的原因,我还是要投资某一个能源公司，别急，下次关注我的文章，关于王川投资第三法则的，看了后你也许会改变想法.

---

# [增速为王](https://mp.weixin.qq.com/s?__biz=MzA3MzE5MjM2Mw==&mid=422319796&idx=1&sn=865a668ee5e7b9fc4377f89fb35cbc4a&scene=21#wechat_redirect)

当同一个问题,有不同角度的解决方案时,产品性能的增长速度最快的解决方案,最终会胜出.

这个法则的一个推论是: 增速慢的解决方案, 一旦过了临界点被替代方案超越, 其背后的公司或者个体, 将会出现断崖式的崩溃.

关于王川投资的第一和第二法则, 可直接点击下面的连接.


(2)

这个法则的第一个经典例子,是数字照相机淘汰传统胶卷照相机.

你也许还记得 1975年第一台数码照相机,是柯达公司发明的. 数字照相机照片的像素数目,每年平均20%以上的增长,而胶卷冲洗的照片,则进步缓慢.

普通消费者使用的传统35毫米胶卷, 冲洗照片的像素大约在 4-18 兆之间.

但到本世纪初,数字照相机的像素超过两兆 后,如果打印到一张五英寸 x 七英寸的照片上,其精度和胶卷冲洗的照片,肉眼已很难区分.

数字照相无需胶卷, 拍摄成本为零, 再加上家用电脑和智能手机的迅速普及, 传统胶卷照相机在大众市场被彻底取代,也就毫无悬念了.

而照相业的鼻祖, 柯达公司, 股价从1997年开始就不断下滑, 从2006年到2008年更是下跌了90%,直到最终 2012年宣布破产.

(3)

第二个例子,是正在发生的,电车淘汰汽车的事件.

汽油车的效率,实际上过去一百年内,没有多少进步.1913年福特生产的 Model T, 一加仑汽油可以跑 25 英里,这实际上和2016年美国销售的新车的平均汽油里程数 24.8, 相差无几.

里面提到锂离子电池的成本,大约以每年16%的速度不断下降.

特斯拉的 Model S, 2012年出厂时,60kwh 的版本底价七万美元, 续航里程 208 英里. 2015 年, 七万美元可以买到 70 kwh 的版本, 续航里程 230 英里.

实际上, Model S 在2015年美国七万美元以上的豪华车中,市场份额已经达到26%,远超同一价位的奔驰 S-class 和宝马七系列.

再过几天, 三月三十一号, 新出来的 Model 3, 底价三万五千美元, 预计续航里程两百英里以上,2017年底开始交货. 这将开始直接冲击宝马三系列,和高端的丰田佳美/普锐斯占据的市场.

(4)

第三个例子, 来自九十年代末的电信行业.

美国的电信行业一直到九十年代中期,日子都非常好过.主要原因是缺乏技术上的竞争.通讯业的收费模式一直是: 价格与通话时间,通话距离成正比,多年没有变化,没有商量,爱用不用.

一直到 1997 年, 从美国打国际长途电话到中国,价格都在一分钟两到三美元. 电信公司在国际长途业务上的利润率据说远超拦路抢劫.

传统电信器材公司, 在这种商业模式的指引下, 推广的是所谓 ATM（Asyncrhonous Transfer Mode） 的通讯协议,意在建设一个统一的网络协议,可以同时处理语音,数据和录像.

ATM 通讯协议的思路,还是基于传统电信公司,语音信号传输的线路交换 (circuit switch) 的思维模式.

与之相竞争的技术标准,是以思科为代表的数据网络公司的 IP（Internet Protocol) 网络架构. 从工程实现角度看, ATM 比 IP 效率更低下,系统更复杂,价格更昂贵.

与此同时,普通消费者接入互联网的数据带宽,按照每年50%的增长速度,不断发展.到九十年代末,有线电视公司提供的宽带服务传输速率可以超过 1 Mbit 每秒.

1 Mbit 是个什么概念? 打电话的语音信号,转变成数据传输,大约一秒钟消耗 50 Kbit, 相当于 0.05 个 Mbit.

(4)

第三个例子, 来自九十年代末的电信行业.

美国的电信行业一直到九十年代中期,日子都非常好过.主要原因是缺乏技术上的竞争.通讯业的收费模式一直是: 价格与通话时间,通话距离成正比,多年没有变化,没有商量,爱用不用.

一直到 1997 年, 从美国打国际长途电话到中国,价格都在一分钟两到三美元. 电信公司在国际长途业务上的利润率据说远超拦路抢劫.

传统电信器材公司, 在这种商业模式的指引下, 推广的是所谓 ATM（Asyncrhonous Transfer Mode） 的通讯协议,意在建设一个统一的网络协议,可以同时处理语音,数据和录像.

ATM 通讯协议的思路,还是基于传统电信公司,语音信号传输的线路交换 (circuit switch) 的思维模式.

与之相竞争的技术标准,是以思科为代表的数据网络公司的 IP（Internet Protocol) 网络架构. 从工程实现角度看, ATM 比 IP 效率更低下,系统更复杂,价格更昂贵.

与此同时,普通消费者接入互联网的数据带宽,按照每年50%的增长速度,不断发展.到九十年代末,有线电视公司提供的宽带服务传输速率可以超过 1 Mbit 每秒.

1 Mbit 是个什么概念? 打电话的语音信号,转变成数据传输,大约一秒钟消耗 50 Kbit, 相当于 0.05 个 Mbit.

第四个例子,是九十年代中期开始关于家庭娱乐发展方向的讨论.

当时的主流观点是,家庭娱乐的未来方向,在于所谓的"互动电视" (Interactive Television). 有线电视公司,可以提供成百上千个电视频道,供消费者选择付费.消费者需要购买一个机顶盒,和内容服务商互动.

但是谷歌的youtube 的出现,和网络带宽的持续增加,改变了这个格局.

今天美国普通消费者的网络带宽, 可以达到每秒 50 Mbit 以上, 而一个高精度的录像,每秒钟需要传输的数据也只有不到 5 Mb.

但最核心的要素,在于 youtube 上的视频内容, 在指数倍的不断增加.

根据网站 reelseo.com 的 Mark Robertson 的数据, 2015年11月,每分钟大约有五百小时的视频内容被用户上传到了 youtube. 而在 2007年10月, 每分钟上传的视频内容只有 8 分钟. 八年来的年均增长速度为 170%. 

虽然未来增速会放缓,但是预计到2016年底,每分钟长传到 youtube 的视频内容会超过 700 个小时.

youtube 的海量视频内容,超过十亿以上的全球观众, 和仍然高速的增长, 是只有几百个频道,几千万个订户, 线性增长的有线电视公司,完全无力竞争的.

家庭娱乐方向的辩论可以休矣,互联网赢了.

---

# [波爱为王](https://mp.weixin.qq.com/s?__biz=MzA3MzE5MjM2Mw==&mid=2672246661&idx=1&sn=7a9a9093f3bb90bbb02fbab80d363195&chksm=85a15941b2d6d057e41258a5625a1423172528dfa58150e585685a8a43fa43e3b1c9f47b0449&scene=21)

(1)

1879 年十一月十日，是美国电话业历史上一个里程碑的日子。美国电报电话公司 (AT&T) 的前身， National Bell, 和西联公司 (Western Union) 就电话专利的官司终于达成庭外和解。西联放弃了对专利的所有诉求，把自己和电话相关的资产，换取了 National Bell 在专利有效期内的百分之二十的收入.

National Bell 的投资者早就预测它最终会在官司中生出，其股价在 1879年三月时还只有五十美元，到九月份时突破三百. 庭外和解达成后的次日，股价突破了一千美元。八个月涨了二十倍，这种疯狂的速度，在AT&T的一百多年历史中，是空前绝后的.

有资料显示，从1878年到1928年的五十年间，AT&T 股东包含股价升值，分红，和所谓配股发行 (rights offering) 收益在内的累计回报，达到 259 倍，折合年化收益率 11.7%.

AT&T 的成长并非一帆风顺。1894年其电话专利到期后，竞争者如雨后春笋般涌现。到1907年，高达 49%的本地电话业务被各个独立电话公司占有。AT&T对市场的垄断一度遭到看似严竣的挑战.

当新任总裁 Theodore Vail 1907年上台后，采取一系列措施收复失地。其基本策略是：坚决拒绝和别的独立电话系统提供连接服务，尤其是在 AT&T 对长途电话业务近乎垄断的情况下，独立电话公司的用户打长途电话几乎不可能.

独立电话公司一般钱少，器材更落后，客户服务也更差，财务数据大多惨不忍睹。美国金融界巨头 J.P. Morgan 当时是 AT&T 最重要的财务支持者，他实际上控制了美国的商业信贷。如果有独立电话公司快撑不住了，他就会断贷，然后 AT&T 跳出来开价收购. 最终的结果是皆大欢喜，小电话公司的股东拿回一些钱, J.P. Morgan 赚了钱， AT&T 少了一个竞争者， 电话用户获得更好的服务和长途电话的连接.

(2)

联邦政府对AT&T 的垄断开始进行干预，在1913年达成所谓 "Kingsbury 承诺", 其核心条款是强迫 AT&T 必须给独立电话公司提供长途电话接入服务。但在这个让步之外， AT&T 并不承诺把自己的本地电话系统和其它电话公司互联，同时  AT&T 继续拒绝和其它长途电话竞争者连接.

政府的管制干预，跟不上市场的变化，进入三十年代 AT&T在电信行业的多个细分领域市场份额超过 80%甚至 90%，奠定了绝对垄断地位. 以1939年的数据为例，AT&T 控制了美国 83%的电话市场，90%的电话机和交换机设备市场， 98%的长途业务市场，100%的跨洋无线电话市场，它也占有了行业 90%的收入.

这，就是横跨三个世纪，美国商界, 规模最大时间跨度最长的波色*爱因斯坦凝聚态.

即使你错过了前五十年的发展，对于达到波爱态的 AT&T，后面半个多世纪的巨大增长，在诸多投资选择中，仍然是鹤立鸡群.

从 1929年到1984年 AT&T 最终被政府拆分的 55 年内， AT&T 的股价从 195 美元涨到 390美元，年均涨幅 1.3%。 同期股东每年还有现金分红，从 1929年的每股 9美元涨到 1983年的每股 32.4美元，年均现金分红大约 5.5%- 6% 之间。另外股东每隔两三年通过打折配股发行的方式获得收益，估计折合每年约 2-3%的额外回报.

这些收益叠加起来，意味着 AT&T 这五十五年间年均回报在 8.8% - 10.3%之间，而同期道琼斯工业指数包含分红的年均回报只有 7.5%. 即使按照 8.8%的年化回报率计算，55年下来就是 103倍 !

这个故事还没完，即使是在 1984年 AT&T 被分拆之后，它的子公司之一的 SBC, 也就是现在的AT&T, 股价从 1984年的 五美元涨到了2017年的四十美元，这期间还保持每年约 4-5%的现金分红，三十三年下来实际年化回报率11%左右. 这是在二十一世纪数据网络通信大行其道， AT&T 通信业务垄断地位已经弱化的情况下取得的业绩.

波爱，波爱，你在波动中顽强生长，让投资者深爱.

(3)

在其它条件相近的情况下，只投资市场垄断地位即将达到，或者已经达到波色*爱因斯坦凝聚态的公司.

如何判断一个公司即将或者已经达到波爱凝聚态?

第一个要求是，这个公司的商业模式可以同时服务大量客户, 新客户的边际成本极低。这基本上排除了大多数类似咨询业的商业模式，一次只能接一个客的公司.

微软多卖一份软件的边际成本几乎为零。 AT&T 多增加一个新用户的成本也很低，关键是用户多打电话多交费时，它的边际成本也几乎为零.

第二个要求是，公司在核心市场有较大概率达到，或者已经达到甚至超过 80%以上的市场份额.

80%不是一个固定的铁律，当然是多多益善。但超过 80%以后，其它竞争者想在现有商业模式下翻盘，基本没有可能.

第三个要求是，公司继续保持较强的商业竞争力，利用在核心市场的垄断，不断开拓新的相关市场的垄断性，再反哺其核心市场的垄断地位.

在桌面操作系统市场上，我们看到的是微软，不断通过增加捆绑第三方应用软件，比如 WORD, Powerpoint, Excel, Internet Explorer 等等，在这些应用软件上达到垄断性后，反过来强化其在操作系统上的垄断.

AT&T, 利用其在长途电话业务, 电话设备业务和跨洋业务上的垄断，强化其本地电话业务的垄断.

波爱凝聚态，这是一个神奇的世界.

在这个世界里，客户对于产品的选择是不假思索的，对于竞争者的考虑是不可想象的.

在这个世界里，竞争者幻想通过简单降价，或者增加几个小小的功能，就想抢占市场份额，就是痴人说梦。对于用户而言，更换平台和使用习惯的代价太大，不是降点价多点功能就可以做到的.

达到波爱态的公司，收入和利润率固若金汤。即使遇到大的经济萧条，其余竞争者往往率先被淘汰破产出局，而市场份额自然被它笑纳.

上世纪三十年代的经济大萧条，道琼斯工业指数到最低点时下跌90%左右，很多公司破产。而 AT&T 股价回撤只有76%（从最高 300美元一股跌倒最低 70美元），即便如此，它还是保持了给股东每年一股九美元的现金分红不变。经济复苏之后，它的垄断地位更强了.

(4)

如果你还记得 2015年初我的关于腾讯的老文章
王川：四千亿个理由告诉你，视野比勤奋更重要，长期持有才是王道

两年后的今天，腾讯的股价又上涨了 70%。而过去五年股价它的升值将近六倍。这个数字，是绝大多数风险基金对冲基金，无法望其项背的.

如果说1999年刚开始创业的腾讯，还面临各种巨大的风险和不确定性；那么今天的腾讯，坐拥将近九亿活跃微信和 QQ 用户，六亿活跃移动支付用户，已经达到了事实上的波爱凝聚态.

腾讯正用自己在社交领域的绝对垄断地位，推动其在移动支付的市场份额. 2017年初其活跃支付用户数已经超过支付宝，而平均支付频次已经达到支付宝的三倍.

支付和社交的海量数据的积累，又帮助腾讯在精准广告投放市场上的扩张。腾讯在广告业务 2016年的收入已经接近百度的40%，但其2016年的广告增长速度高达54%，而后者基本停滞不前.

而这一切，都会进一步反哺腾讯在社交领域内的垄断地位.

2013 年微信已经确定在中国的移动社交应用上的垄断地位时，许多分析师还在纠结腾讯下一季度的游戏收入是否理想. 他们有预见到微信红包和支付在2014年的诞生和强势崛起吗？同理，动辄要颠覆微信的创业者，十几年来一直顽固地纠结下季度腾讯游戏收入而睡不好觉的分析师们，难道腾讯会坐等别人超越，不会积极开拓新的应用场景和市场，进一步加强其各方面的领先地位吗？

笔者无意在此预测腾讯的短期股价走势，但根据 "波爱为王" 的投资法则，腾讯未来十年的股价升值，超过 A 股或者港股指数，超过移动互联网领域 95%以上的风险基金的回报，将是一个大概率事件.

(5)

人们常犯的错误是，发现了一个达到波爱态的强势垄断型公司后，看到其过去的股价增长，懊悔当年钱多人傻时没有参与，感叹现在股价太贵而迟迟不敢入手。而事实上, 在 AT&T 跨越三个世纪的成长历史中，绝大部分时间作为长期投资都是不错的入场时机. 波爱凝聚态的公司, 在竞争者咬牙切齿的痛骂中，垂而不死，腐而不朽，其顽强生命力被大多数投资者低估.

与之形成强烈反差的是，初期的创业公司做大的几率非常渺茫，但人们却拿一些不到万分之一概率的事件给自己打鸡血. 看看当下各种轰轰烈烈的创业投资评选大赛活动就知道，大家集体为小概率事件支付真正高昂的溢价. 创业公司整体长期回报不佳，就是数学上的必然了。美国95%以上的风险资本基金的十年的长期记录是亏损掉一半的钱.

为什么人们要舍近求远，为一个没有全面严格论证的初创企业的高估值买单？为什么一个达到波爱凝聚态的好的投资机会就在面前唾手可得，大多数人却无法抓住和坚守？这个现象背后的各种复杂原因，不是几句话可以讲得清楚.

而真的猛士，敢于放弃对小概率事件的意淫，敢于重仓大概率低风险高回报的投资. 他们阅读无数案例而无比挑剔，他们看似无所事事却满载而归, 因为他们知道，波爱为王.

---

点评：写得很好，可以总结一下：对于现存市场，形成规模效应、网络效应、自我强化倾向和有极高迁移成本的公司（波爱凝聚态），是最好的投资标的。但是，新公司抓住另一波趋势，在一个高速增长的蓝海市场成为造就新的波爱凝聚态公司。
