---
title: 疑人不用
author: valueman
date: '2020-12-21'
slug: '122'
categories:
  - Translation Articles
tags:
  - Investment
---

[Source](https://xueqiu.com/1376479032/126876442?page=1)

[Source](https://xw.qq.com/cmsid/20200907A0EKAN00)

> 正如《合作的进化》所说，要一报还一报，不和有污点的人合作。非常挑剔，才能非常省心，非常成功。

# 疑人不用

几十年来积累的朋友圈，只要其中某个人曾经有过恶性的行为（比如说伤害过别人，弄虚作假，不守信用。），那么这个人不可能继续存在于我的朋友圈中。道理是显而易见的：如果和这种人交往，下一个受到伤害的对象极有可能就是我。

疑人不用，应该是每个人的处事原则。

证券市场投资的思路和现实之中处理事情的思路在很多方面是相通的，对于有重大疑点的上市公司，回避是最好的选择。

请重温巴老这句话：“在撞了很多次南墙之后，我学会了只与那些我喜欢、信任和赞赏的人共事。在拥有良好经济特性的公司中，如果公司所有者或者投资者能成功与理想的管理者协同合作，便可以创造奇迹。相反地，无论一家公司的前景看起来多么光明，我们也不愿与缺乏令人欣赏的特质的管理者合作。与坏人做生意，我们从未成功过。”

近来市场爆雷不断，乐视，康得新，康美，这三家公司市值都曾经达到过千亿以上，现在却均面临退市，投资者损失惨重。

以康美为例，前段时间有位V在长达数月时间内，发贴数十篇质疑康美做假，而该V从事的行业和康美是同行，按说有极高的可信度。我不知道他拯救了多少原康美药业的股东出苦海，只要有一个，也是功德一件。只有你认识到别人的善良并被触动后，善良才有意义。“我们奋力拼搏，忍辱负重，不就是为了能够认识到那些对我们善良的人吗？”

如果你是一个对市场一无所知的新手，踩这些雷虽情有可原（不知者无过），但罪不可赦（冒然出手，造成严重亏损，只能自认倒霉承担亏损）。

如果这些信息你都知道，还要踩这些雷，那么和自残有什么区别？

某在进入市场之前就是一个小白，后来读过几本书，书中人们在市场中赔的极其惨烈的案例特别能吸引我，因为踩雷这种事情，如果仓位集中，遇上一个就会亏的底掉，会终结投资之路，会把自己生存的经济基础给摧毁。这里我要顶着压力再贴一句芒格老的话：“如果我知道我会死在哪里，那我就永远不会去那个地方。”

到现在我依然认为自己是一个小白，只是读过几本书，能够辨别明显的矛盾和道理，而深层次的矛盾和道理，还需要继续思考、学习和实践。

---

# 切糕“后遗症”有多严重？如今明码标价，5元一两没人买，游客：真不敢了

提起和外出旅游有关的一些话题，相信很多人应该都是有关注过不少的吧，毕竟在网上关于这个方面会让人热议的点也很多，尤其是近些年随着旅游业的蓬勃发展，越来越多的普通人也都喜欢上了外出游玩散心。不过，提到和外出旅游有关的问题时，其实除了一些旅游地的特色景点之外，其实很多人也是会有其他的关注点，比如某些地方的特色美食，很多时候也会格外吸引人。

但在这个方面，也有让人觉得不安的点，那就是一些坑游客的地方除了景区的“天价门票”外，可能会出现“天价美食”，比如当初新疆的“天价切糕”，就一直让不少游客念念不忘。也因为这个原因，所以很多人去到新疆旅游看到切糕，可能都要有很严重的“切糕后遗症”了，因为即便是当地街头上的切糕明码标价，也依然有很多游客不敢买。甚至还有一些游客，面对5元一两的切糕标价，即便心里十分想要去试试，行动上还是“真不敢了”的状态，毕竟那个一刀切多少就得买多少的情况，真是让人挺害怕的。

不得不说，即便近些年很多地方的切糕市场比较平和，商业也都足够正规，也很少再有宰客的情况出现，但非常多游客外出游玩看到的时候，其实内心多少还是会有点“慌”，因为有些人真的是被坑怕了
