---
title: 大而不倒------市值重要吗？
author: 方三文
date: '2022-02-04'
slug: '397'
categories:
  - Translation Articles
tags:
  - Investment
---

$苹果(AAPL)$  市值会超过10000亿美元吗？

市值已经3000亿了，它还会涨吗？5000亿了，它还会涨吗？好象我们从来没有见过市值这么高的公司耶。

这真是个感性的想法。实际股价涨不涨，最后应该只取决于公司的盈利能力能否持续增长，而盈利能否持续增长又取决于苹果的产品销量能否持续增长。

而销量能否持续增长，一方面取决于市场的规模，还有多少潜在的用户；另一方面取决于产品的市场占有率能否上升。

目前苹果产品的市场占有率有多高呢？以手机为例，在美国市场上，iPhone 并不是老大，落后于三星、LG、MOTO；在中国，手机用户有10亿，而 iPhone 现在的数量大约是2000多万只，也就是市占率还是个位数。

当然，把智能机跟非智能机放在一起比可能很二啊，但智能手机在手机市场的份额还可以提升，iPhone 在智能手机市场的份额还可以提升，理论上讲是这样。

那么这些剩下的人会买iPhone吗？也许会，也许不会，但非常确定的一点是，他们不会因为苹果市值是否超过5000亿美元购买或者不购买 iPhone。

这其实是普遍存在的一种思维。对于已经规模很大的公司，投资者可能感性地质疑其增长前景；那么他的兴趣就会希望去从小公司里找能成长为大公司的“黑马”。

实际的情况是，小公司成长为大公司的概率，远远小于大公司继续增长的概率。小公司之所以是小公司，往往是它的行业处境、商业模式、管理能力决定的。而大公司之所以能成长为大公司，就因为它们在这方面是有优势的。这就叫，大而不倒。

所以真正有意义的问题是：企业所处的行业规模有多大？企业在行业的竞争力如何？把市值忘掉吧。

当然了，公司规模大了会面临管理上的问题，但管理问题和规模问题并不是直接相关，企业人员规模与市值规模也并不是直接相关（我看苹果人员规模并不是与市值同步膨胀的，富士康可能存在这样的情况），所以可以说，市值和管理问题的关系，很弱。我们可以去具体地了解企业管理上有没有问题，但不能推论出，市值大了一定有管理问题。


当然，苹果真正的问题是，乔布斯去世了。这个问题对公司的影响，不在本文的分析之列。这里只是要说，公司市值大小，和股价涨不涨，关系可能不是那么大。