---
title: 乌克兰发掘历来最大万人冢 疑史达林迫害牺牲者
author: swissinfo
date: '2021-09-01'
slug: '290'
categories:
  - Translation Articles
tags:
  - Propaganda
  - Politics
  - Ukraine
---

[Source](https://www.swissinfo.ch/chi/%E4%B9%8C%E5%85%8B%E5%85%B0%E5%8F%91%E6%8E%98%E5%8E%86%E6%9D%A5%E6%9C%80%E5%A4%A7%E4%B8%87%E4%BA%BA%E5%86%A2-%E7%96%91%E5%8F%B2%E8%BE%BE%E6%9E%97%E8%BF%AB%E5%AE%B3%E7%89%BA%E7%89%B2%E8%80%85/46897908)

>预测阿富汗局势的时候忘记说了，阿富汗也会有政治迫害和大屠杀，就算发生了这些惨案，也最多就是谴责一下，屠夫们仍然会安然在位。


（法新社基辅25日电） 乌克兰南部敖德萨市（Odessa）当局今天表示，当地挖掘出5000至8000人的遗骸，据信是前苏联领导人史达林「大整肃」迫害时期的受害者，这是乌克兰至今发现最大规模乱葬岗之一。

乌克兰国家记忆局（National Memory Institute）地方分部主任古查留柯（Sergiy Gutsalyuk）告诉法新社，这些骨骸是在敖德萨机场附近进行机场拓建探勘工作时，从超过24处埋葬地发掘出。他说当地前几年已挖掘出一些乱葬岗。

古查留柯表示，这些死者是在1937至1939年间遭到杀害的囚犯，执行死刑的是前苏联领导人史达林（Joseph Stalin）恶名昭彰的秘密警察单位「内务人民委员部」（NKVD），这个单位也是前苏联国家安全委员会（KGB）的前身。


1930年代正是史达林进行外界所称的「大整肃」（Great Purge，又称「大恐怖」Great Terror）时期。古查留柯指出，这些囚犯的国籍和判处死刑罪名尚待厘清，但要确认他们的身分恐怕办不到，因为当时文件仍未解密且都保留在莫斯科。

古查留柯表示：「在目前的俄罗斯政府执政下，这些文件永远不会交给我们。」他还说，随着挖掘行动持续，发现的被害人数可能还会增加。

自从俄罗斯2014年并吞原属乌克兰的克里米亚（Crimea），并扶植乌克兰东部的武装分离运动人士后，这两个前苏联国家的关系已大幅恶化。

乌克兰历史学家估计，1930年代史达林整肃异己期间，有数十万乌克兰人被囚禁在劳改营或在营中被处死。

其中一个最知名处决地点是在乌克兰首都基辅（Kiev）郊区村庄拜基夫尼亚（Bykivnia）附近的森林，1937至1941年间有数十万人被埋在这里。

除此之外，乌克兰视发生在1932至1933年间造成数百万人死亡的乌克兰大饥荒（Great Famine），为史达林主导的种族灭绝行动。