---
title: 褚老师另类职场课（2）
author: Guanghua Mao
date: '2021-10-06'
slug: '314'
categories:
  - Original Articles
tags:
  - Job
  - Business
  - Politics
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---



# 职场制胜方法

忘记公平，找到杠杆。错误计算杠杆是十分致命的。

杠杆往往不是单一的杠杆 ，杠杆一般与交易有关。

正确，迅速地计算杠杆等式。

错误计算杠杆等式的例子：IT老员工不愿意给新经理写周报；不要说任何人的坏话（副总裁当着秘书说他老板的坏话）
组织算错杠杆等式：飞行员罢工成功，空姐见状却罢工失败（易取代）。选择权要牢牢掌握在自己手中。

杠杆：职位高，职业地位（飞行员，空乘），有没有对方需要的东西，有么有独享资源（红色背景），对高层有没有影响力，技能是不是难以替代，是否有替代途径，组织内名声好不好，感情依赖强不强，更对方关系好不好，是不是符合白左的利益，是否在道德上站得住脚。

留神杠杆移位：小孩逐渐长大的时候，杠杆也越来越多，但父母没有意识到这一点，会犯下很多错误。在职场中：提职、降职和重组。
提职：空降经理可以重新证明自己，如果是同事那很难重新证明自己。

# quote

永远不要有意的得罪任何同事，他有可能成为将来的老板。做一个好人而不是老实人。用专业和职业的方式对待不喜欢的人和事。（阿里）

杠杠 VS 公平
不断积累和增加自己的杠杆。不要纠结于公平。筹码越多越不在意公平。

七大增加杠杆的办法：

结果，results；其实就是业绩，有上升可能性，也是一种保护。


知识，knowledge，专业技术水平，技能。

态度，不是是不是喜欢，是不是愉快，要专业地处理人与人之间的关系。诚实，耿直是职场自杀最好的办法。

同理心，人们愿不愿意和你交心。

关系网，跟不同组织之间的关系，上下级，同事，等等。


包容，做一个项目和决策的时候，让尽可能多的人参与进来。做 ppt 让领导参与。

超脱，工作认真负责，千万不要太动感情，锤科员工是范例。不要对工作太在意，太依赖。（增加自己的选择权）



# 作业

## 你有多大杠杆：

我的工作结果给公司带来明确价值

我备有对公司非常有用的知识

我几乎被所有同事认为好合作，爱助人

同事经常会找我诉苦，寻求帮助

公司上下我认识的人很多

我在工作项目、决策中经常会引入他人

我会客观看待局势，对待工作

## 你有哪些杠杆故障

自我诊断：想一个你自己错误计算杠杆等式的案例；想一个你遇到过的杠杆移位的案例
从诊断到行动：现在你会怎么做。


# 员工不应该知道的公司秘密

和HR聊会导致你失业。HR不是帮助雇员而是帮着公司防着雇员。

小心HR：

永远不要找HR申诉性骚扰

永远不要找HR解决纠纷（自己解决矛盾，化解矛盾的能力是十分重要的）

永远不要找HR申诉有关钱的问题（出差出车祸，小钱不要找公司报销，大钱肯定要找）

永远不要找HR抱怨（HR一定会把你的抱怨告诉领导）

暴露自己的真实想法是最快的职场自杀方法。就是要鸡贼，利用软肋，增加自己的筹码。所有的挑战都是机会。
