---
title: 政府和市场都是泡沫制造机
author: Guanghua Mao
date: '2021-06-29'
slug: '225'
categories:
  - Original Articles
tags:
  - Economics
  - Investment
---

>这篇文章涉及的知识太复杂，自己水平不够。

过去三四十年，在中国，我们能够很明显的看到政府鼓吹起来的泡沫：学历、基建、光伏等等你，中国政府拥有大量的媒体资源和财政资源，而且能够压低反对者的声音，因此凡事中国政府决心要做的事情，无论对错都会被社会人口执行，结果自然是大量的泡沫。为什么人们会自然而然的相信自己不熟知的事物，这涉及到心理学，在此不做详细介绍。对于学生来说，最出名的莫过于那一句--“21世纪是生物学的世纪”。无数学子报考生物学，学习成绩优异者则奔赴美利坚耗费了无数青春攻读博士甚至读了一个又一个博士后，结果找不到工作，只能改行计算机。从这个意义上讲，政府、社会权威、富豪，这个有着极高话语权的社会力量，而且源于[人类认知的局限性](https://guanghuamao.netlify.app/2020/12/09/1-99/)，他们所传达的信息很容易引发人们的过度乐观和过度悲观。想要不受这些噪声影响就必须坚持独立思考，并对这些现象引起警觉。

同理，市场中极度成功的故事也会极大刺激人们的投资欲望，智能手机制造泡沫、智能眼镜泡沫、百团大战等一系列市场泡沫故事都是我们亲身经历的。附上一篇张化桥先生写过的[文章](https://guanghuamao.netlify.app/2021/03/31/ge-16/)。

附马云在人生定位一书中的感言。

>“对于特劳特先生的定位观点我早有耳闻，这让我想起阿里巴巴的战略定位。有很长一段时间，阿里巴巴的模式都不被人看好。这是又惊又喜的一件事，有时候，不被人看好是一种福气。正是因为没有看好，大家没有全部杀进来，否则的话机会肯定不属于我马云。如果看过特劳特《商战》一书，大家就会知道，侧翼战就是要在无争地带进行。一杯咖啡可以卖二三百年，星巴克在全世界有上万家店，关键要有独特的定位。”

> 贝索斯说：我相信，如果你要创新，你必须愿意长时间被误解。你必须采取一个非共识但正确的观点，才能打败竞争对手。



 [Source](http://headsalon.org/archives/4071.html)

@茶博未：请教@whigzhou 读了《向女王道歉背后隐藏的自大》末2段让我联想到印度政府对IT教育强力注资扶持，培养出过剩的IT专才，让全球尤其美国获得很多便宜好用的程序员。再考虑从军方apanet进化来的internet。政府比企业家更擅长大手笔制造泡沫。政府因此也是创新的一个重要发生器？

@whigzhou: 政府行为导致了很多创新，这一点是明白无误也无须否认的，它的战争机器曾经是推动创新的最大单一力量，问题是，离开了市场的激励约束机制，你无从知晓为这些创新所支付的代价是否值得？也不知道社会是否恰好需要这么多创新。

@whigzhou: 也无从知道它对资源的挤占压制了多少创新

@whigzhou: 况且，创新只是生活的一个方面，企业家个人节衣缩食、担惊受怕、冒巨大风险下注豪赌，这是他自己的事情，凭什么让纳税人负担这些？世界进步跟他们有啥关系？他们为啥要关心？

@tertio: 政府在某些方向上不明智地投巨资的一个结果是，市场上的高级人才都被这个资金黑洞吸引过去了，压制了其他方向。而市场的决策和方向都分散得多，也明智得多，通常整体上只是犯了过于乐观的错误。

@whigzhou: NIH

@茶博未: Bill Gates基金的医疗项目呢？

@whigzhou: 有类似效果，但道德上无可指责，人家吸引资源的能力来自从自己口袋里掏出来的钱，不是从我口袋里硬掏的

@whigzhou: 对于慈善投资的再配置效果，可以说的是：把非直观的挤出效果展示出来，问问慈善家这是不是你想要的结果，如果他说是，那就没话好说了，这是他的权利

@茶博未: 我这样理解你文章的政策含义对不对？由着市场去收拾市场自己造成的泡沫，创新作为非少数人意图的结果

@whigzhou: 嗯，差不多。需要强调一点：A）我从道德上反对政府做这些事，这无须经济学理由，B）我又从经济学上反对那些认为政府做这些事有如此这般好处的观点，A和B是两个独立的主张，之间不必有关系

恐怖分子放毒蜘蛛咬人->被咬的人中有一个因此变成蜘蛛侠->几年后蜘蛛侠拯救世界->全世界人民改变了观点，同意当时恐怖分子放毒蜘蛛咬人物有所值……

楼上有个基本错误：即使没有政府资助，ARPANET不一定不会产生，只是产生的时间和形态可能略有变化。
因此，享受到ARPANET未必导向“同意花自己的钱去资助它”

----

 [Source](http://headsalon.org/archives/7602.html)

@whigzhou: 当前各国（特别是欧日）央行往系统里拼命灌钱、毫无节制抬高杠杆的劲头实在有点疯狂了吧，照这么买下去，流通中的企业债全进央行了，日本央行甚至直接买股票，到明年大企业都变国企了，想想不久前他们还在痛责私人银行家头脑发热，事实证明，论无视风险制造泡沫的胆量，有谁比得过政府呢？ ​​​​

