---
title: 微言（23）
author: Guanghua Mao
date: '2022-02-14'
slug: '342'
categories:
  - Original Articles
tags:
  - Insights
---

1. 前期市场调研太重要了，爷爷，黄总，梁老板的锅具，决策的重要性由此可见一斑。

2. 人们都太渴望一个简单的答案来解决所有问题。

3. 阿里盖坤的东西很不错，和 digital marketing 高度相关。


4. 真知blog 关于窄门思维的一章说得非常好。

>选择比努力更重要，那么要如何做选择呢？彼得蒂尔有一个管理原则：极端聚焦，公司和公司的高管在一段时间之内都必须只能专注于一项任务，年终总结的时候也只能写一项对公司最有价值的事情。彼得蒂尔这样解释：人其实是喜欢逃避挑战和困难的一种动物，假定现在有 2 个任务，一个比较难，要怎么做也没有明确的标准答案，可是一旦完成，工作上就会取得巨大的进展，而另一个比较容易，有固定的工作流程，工作成果对公司也会有帮助，但帮助不是特别大。人们普遍会完成简单的任务，然后再去找另外一个简单的任务去完成，那个困难但是对公司帮助巨大的任务就被搁置了。相反，如果你只有一个困难的任务，那么人们就不得不拼命地想尽一切办法去解决它。如果一家公司、一个人一直在逃避去解决 95 分难度的问题，而总是在试图解决 80 分的问题，那么这家公司也就是一家普通公司。马云曾经说过：我对于十年内能成功的事情都没有兴趣。狂妄吗？当然不是，一个月能做成的事，竞争激烈，3~5 能做成的事情仍然对手众多，只有把眼光放得更长远 10~20 年，才能真正打造自己的竞争优势。选择走更难的路往往是一种更加智慧的选择。所以当有很多选项的时候，不妨就选择那个更加困难的。这往往有一下 7 个好处：1. 最难的事情解决的往往也是最重要、最核心的问题，做成之后产生的回报也是最大的；2. 更难的事情做起来反而会更简单，因为大多数人都喜欢做 50 到 80 分难度的事情，所以你会发现在这个难度等级里面挤满了竞争者，可当你把目标定到 120 分难度，基本上就没有什么竞争对手了。3. 当你目标远大的时候，会吸引最好的帮手和合作者，因为最优秀的人同样也是目标远大，喜欢解决最重要最不可思议问题的人。4. 最难的事情最大的优势是，它的难度可能只是普通事情的 100 倍，但它所产生的价值和影响力却是普通事情的 10000 倍，在性价比上已经赚大了。5. 做最难的事情，就算不成功结局也不会太差。6. 越难的事情经济回报也更大，我们可以将经济回报再投入到更难的事情上面，形成正循环。7. 解决难的问题，能够满足成就感和自信心，还能建立起竞争对手难以跨越的高门槛和护城河。


5. 以上的文字说得很好，不过我还是认为：1. 要聚焦，2. 挑战更难事情不意味着以卵击石，要扬长避短，顺应大势，用不同的方式去做。