---
title: 马化腾给我们上了一堂金融课
author: 方三文
date: '2020-11-04'
categories:
  - Translation Articles
tags:
  - Business
  - China
  - Evolution
slug: '89'
---

[Source](http://tech.163.com/10/0622/09/69P7IETU00094IFL.html)



如果马化腾来给大家上互联网产品运营或者互联网公司管理课，听的人估计要爆棚。不过，这次他给我们上了一堂金融课。

6月11日，腾讯在联交所披露了一份股权变动公告。公告显示，腾讯创始人马化腾于6月7日在场外以每股102.7港元的价格，减持了500万股腾讯股票，涉及金额5.135亿港元。在股价150港元的时候，马化腾以102港元的低价减持500万股，这是怎么回事呢？

原来，马化腾一年前购买了一款金融衍生品，具体而言，他购买的这款产品叫做锁定利润策略期权组合(Collar option strategy)，马化腾在腾讯股价90港元的时候约定了一年后以102港元的价格卖出股份，出售给他这款产品的投行则承担股价下跌的损失和上涨的收益。如果投行又将相反的合约卖给另一个投资者的话，则对方承担股价下跌的损失和上涨的收益，这就是俗称的“对赌”。

以腾讯现在的股价看，马化腾亏大了，这回是不是又要骂万恶的投行给小马哥设了一个套呢？可能不能这样看。我们假设一下，如果腾讯的股价现在是80块钱呢？那么小马哥依然可以以102的价格卖出股份，承担这每股22块钱损失的就是与小马哥对赌的人了。

所以这是一个生动的个案，告诉我们金融衍生品是什么东东：它是实现你投资诉求的工具。如果你对股价运行的方向很有信心，想扩大你的收益，那么衍生工具可以做到；如果你对股价运行的方向没有信心，想锁定你的收益，那么衍生工具也可以做到。金融衍生品就是一个工具而已，它并没有善恶之分，使用它不出乱子的核心是你要明确自己的诉求，同时要承担自己判断的后果。在这一次交易中，马化腾显然是想锁定自己的利润，那么他购买的衍生品就成功地帮他实现了诉求，但他也承担了自己判断的后果。应该说，马化腾在选择产品的时候是比较专业的，不象有些公司，想锁定原油、外汇价格波动的风险，却选择了单边看涨或者看跌产品，诉求和行为分裂，结果价格朝相反方向运行，就酿成了灾难性的后果。

如果一年前马化腾确信腾讯的股价能涨到现在的位置，他打死也不会买这份合约。现在的情况不能证明马化腾的失误，倒是再次证明了一点：即便如公司董事长这样最核心的人，也无法准确地预测自己公司股票的价格走势。长期以来，很多投资者都倾向于认为，市场上的价格是由内幕人士、阴谋家、机构和庄家操纵的，所以也认为获取内幕消息是获利的捷径。与这种自信相比，马化腾面对市场的谦卑，真是值得我们警醒，因为他采取的是双边锁定风险的保守策略。股价真的那么容易被操纵？内幕消息真的那么容易获得？我听说过另外一个很生动的故事，一个上市公司的董事长，信誓旦旦地说服自己的朋友购买自己公司的股票，结果这朋友开了一辆奥迪进去，开了一辆奥托出来。结果这董事长都不好意思再见到自己的朋友。

我们都在费劲地猜测是谁在操纵市场，但结果可能是我们每个投资者的行为，组合起来最后操纵了市场，这也是索罗斯所说的，相信自己的虚妄。