---
title: 现行教育制度无法解决阶级固化
author: 末世前的宁静
date: '2021-06-27'
slug: '210'
categories:
  - Translation Articles
tags:
  - Insights
  - Investment
---

[Source](https://www.zhihu.com/question/55518958/answer/416883241)

> 这位老哥的很多看法都很合我的胃口。除开作者认为高等教育是泡沫这一观点深得我心之外，最后一句话也很值得深思，很多人鼓吹文凭的价值，是因为他们在其它方面一事无成，只有吹一吹文凭。这不禁让人想起了无数体制内人士，一辈子一事无成，收入低、地位低、见识低只好吹自己认识谁谁谁、自己读初中的时候学习成绩多么好。可笑。对于绝大多数小镇做题家来说，大学就是他们一生的顶点。

现行教育制度无法解决阶级固化，反而是中产阶级奴役无产阶级的工具


每当对应试教育进行批判时，总会有许多人像“打了鸡血”一样跳出来反对：“教育公平是社会公平的最后保障。一旦取消了应试教育，寒门就更难出贵子，阶级固化会更严重。假如没有了高考，穷二代怎么可能拼得过富二代？”

为何这种声音如此响亮？真的是穷人的声音吗？新闻传媒是中产阶级控制的，社会舆论是他们操纵的。鄙视和丑化穷人，让无产阶级永远在社会最底层做牛做马才是中产阶级的夙愿。作为社会既得利益者的中产阶级普遍都非常渴望“寒门无法出贵子”，怎么可能放纵媒体形成鼓励穷人跳出寒门的社会舆论？事出反常必有妖，控制舆论的中产阶级反对教育体制改革，甚至鼓吹现行教育制度有利于打破阶级固化，真实目的是为了让无产阶级充当炮灰。

高考似乎成了宗教般的朝圣，每年高考期间全社会都为此让路。交通管制，考生家长在考场外焦急地“陪考”，新闻传媒全方位地跟踪报道。然而可以发现，中产阶级子女考上大学，特别是重点大学的比例远远超过无产阶级子女。哪怕寒门子弟考上了重点大学，在校期间的表现以及毕业后的职业发展都远远不如同类型高校毕业的中产阶级子女。可以明确地说，现行教育制度根本无法让寒门里的人才上升，根本无法打破阶级固化。

高考看上去很公平，然而基础教育资源的分配不公让许多寒门子弟在起跑线上就被甩出一大截。更关键的是，寒门子弟考上重点大学，往往还要付出大量的隐形牺牲。众所周知，北京考生考上清华北大的可能性远远高于那些本省缺乏重点大学、农业人口众多的省份的考生。从平均生源质量上说，高考大省的考生似乎远远优于北京考生。然而在清华北大就读期间，感到压抑的反而是“小县城的学霸”居多，北京生源反而不那么严重。相当多数的“小县城学霸”来自农业省份的工薪家庭或者农民家庭，往往为高考已经全力以赴。当他们努力考上清华北大后，发现那里中产阶级子女居多并且普遍多才多艺，比如外语口语非常流利，课外知识极其丰富等等。由于信息渠道的匮乏，寒门子弟在大学之前往往全力以赴为高考，而中产阶级子女则充分利用“黄金年龄阶段”学习了大量实用知识和技能，将寒门子弟甩得远远的。由于绝大多数学生（包括清华北大中的许多学生）毕业后并不从事基础学术研究，因此在校期间的学习成绩对实际工作并无多大帮助。在中小学阶段就积累了大量实用知识和技能的中产阶级子女可以获得巨大优势，彻底击败寒门子弟。

因此目前的教育制度将无产阶级赶上应试的歧途，而信息渠道宽广的中产阶级则不会为了考试而考试。题主问到“高中生为什么要努力学习”，个人认为不但高中生，甚至整个中小学阶段都不应该过于努力学习，而应该充分利用“黄金学习年龄”扩大知识面，积累各种技能。考上好大学固然有优势，然而如果为此牺牲了太多就得不偿失了。如果一个高中毕业生除了读书其他什么都不会，那么哪怕考上了名牌大学，最终一定会掉队。

绝大多数大学生最终从事的工作跟在校期间从课堂上学习的知识关联很小，甚至没有关联。读大学主要是获取一张文凭，拥有一块“敲门砖”，证明自身曾经参与过一场“军备竞赛”并且取得了一定的成绩。许多高中毕业生在上大学之前普遍对大学充满向往之情，心中满是神圣。然而实际上绝大多数大学都极其官僚化，腐朽不堪。只会念教材的庸碌叫兽并不罕见，学生会则往往是勾心斗角的官场。研究生称呼导师为“老板”，甚至沦为导师的秘书和家仆。

大学早就不是什么“象牙塔”了，大学生也早就不是什么“天之骄子”了。然而尽管社会舆论已经习惯用平常心看待普通大学，却从没停止过吹捧名牌大学。特别是北京大学和清华大学这两所生源最优、资源最丰富的高校，一直是造神的好素材。比如民间一直流传着类似这样的传说：“清华北大的许多学生都异常聪明，许多‘学神’只需稍微翻书看几下，就能轻松学会一门课程。” 实际上北大清华里只是学霸居多，“学神”无论在世界上哪一个地方都是凤毛麟角。假如你曾经在重点高中就读过，那么可能班上就有同学考上了北大清华，他们都像神一样高不可攀吗？显然不是。绝大多数名牌大学里的学生也只是比大多数人聪明一些，加上比较努力学习而已。初次到访北京的国内游客往往都喜欢去北大清华的校园里转转，试图吸收一些“高级知识”的气息。这种“朝圣旅游”早就让北大清华的校园管理方头疼不已，于是对组团参观校园进行阻拦。然而限制越多，就越多人想去“朝圣”。

当然好大学肯定比差大学拥有更多的资源，比如更优秀的教师队伍，更多的论文数据库等等。然而当今是互联网极其发达的时代，哪怕学校提供的信息资源有限，也可以通过互联网来适当弥补。另外好大学比差大学拥有所谓“更优质”的同学圈子，比如清华北大的许多学生可以认识同班的高干子女。然而圈子也只能给自身提供更多的信息渠道，接近权力并不等于拥有权力。不管怎样，在互联网发达的当今时代，信息垄断和信息不对称已经远远不像过去那样严重了。

个人认为当今时代完全可以通过互联网自学所有课程，然而由于“学历鄙视链”的顽固存在，缺乏“全日制”的学历会受到严重歧视。因此如果能考上好的大学当然更好，但是不应该形成强烈的执念。诸如“两耳不闻窗外事，一心只读圣贤书。整个高中阶段全力以赴为高考，考完后整个人都精疲力竭”以及“只考上了 211, 决定复读冲刺 985”等行为就是高考执念在作怪，跟“范进中举”差不多。之所以知乎上总是喜欢鼓吹学历，是因为“学历鄙视链”的受益者控制了话语权。许多人拿到大学通知书的那天是他人生最辉煌的时刻，然后就一直在走下坡路。他们最自豪的就是拥有了一张与众不同的文凭，自然会竭力鼓吹文凭的价值，而无视高等教育的巨大泡沫。