---
title: 从王庆根自杀到欧建新自杀之我见
author: CSDN
date: '2021-03-30'
slug: '194'
categories:
  - Translation Articles
tags:
  - Labor
  - Business
  - Nonlinear system
---

 [Source](https://blog.csdn.net/bbgwlove/article/details/79047090)

> 人因为线性思维和过度乐观犯下了多少错误

王庆根，男，神童级别人物，曾在美国斯坦福大学攻读化学专业。学霸经历可谓星星闪耀，能够亮瞎每个人的24k氪金狗眼。40岁自杀。

欧建新，男，中兴某公司的老员工。42岁自杀。


两者共同点：学霸！真学霸！都是名校毕业。王庆根主修的化学专业，后改行到计算机。在当时的美国一家大型公司上班。欧建新，主修计算机。

两者区别：王庆根主修专业化学，后来在饭局上，一位朋友说计算机赚钱多，改行计算机，虽然心里了仍然放不下化学，但迫于金钱的需要，自己学起了计算机。曾在一家公司担任软件开发工程师，在另一个美国大型公司担任首席软件工程师。

欧建新，毕业于北航，应该是计算机相关专业，具体是否计算机不详。但毕业后从华为就职8年到中兴就职n年，可谓计算机的老前辈。

两者的自杀：

王庆根因不堪软件开发压力，主要是他带领的小团队因无法实现具体的某一个目标，而被领导问责，后来工资减半。由20万美元降为10万美元。导致抑郁症。又因在美按揭购买的房子未能还清房贷，不能回国。其主修的化学专业由于毕业后未能从事，也荒废，导致在他不想搞计算机的时候，去面试化学专业的公司，化学专业的公司对他毫无兴趣。失业=自杀？


欧建新： 看新闻报道是因为公司股权问题。但凭个人直觉，股权卖的再低也是钱，除非钱少的真的不足以弥补当前的财务缺口。

导致两者自杀的原因看似不太一样，实际上一样：工作压力和财务困境。



给从事计算机开发行业人的忠告：

1，消费要有平常心，节约。切不可看到今日工资特别高，就敢买游艇，买三套房子，买n个苹果。因为你的财富都是通过你的工作获取的，而不是通过钱生钱，当你不工作的时候，你的钱不增而减。谁都有年轻的时候，谁都有感觉要膨胀的时候，谁都有好时候，谁都有坏的时候，我们能做的是，当我们处在坏的时候，会做什么选择，一些房产是否有必要购买，不买可以活下去吗？ 问一下自己。

2，计算机行业确实带有青春饭的特征：

从事计算机专业越久，你的工资会越高，但是公司会从节约成本的角度出发，辞退你。尤其是40岁左右。好多单位喜欢招聘应届生，为什么？应届生才是真正的利润源头，刚毕业的小伙，不用给太多工资，跟他聊一聊好好学习，钱会多多，他就热血沸腾，恨不得通宵工作。这些都是上年纪的老员工所不具备的。

另一个古老的行业就是青楼，请自行对比年轻姑娘的市场和老阿姨的价格与前景。

还有一个阴谋论说 你不适合做计算机才会觉得压力大，其实你不然，每个大学毕业的学生的数学都不算差，但只要从事了计算机行业，无论你是计算机专业的还是非计算机专业的，热爱计算机专业还是不热爱计算机专业的，都会觉得压力大。这是由于计算机行业特点所决定的，因为计算机，不是小说，写错别字也无所谓，而是一个标点符号都不得有错。这就要求事必躬亲，你心里想的再快，也要手指头跟上。

---

# 逼死欧建新的不是中兴，而是现实

 [Source](https://blog.csdn.net/weixin_30951231/article/details/95105065?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-2.control&dist_request_id=1328741.50862.16170923298064527&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-2.control)


欧建新是谁？据说是中兴通讯的一位员工，前些天因为裁员问题与公司沟通不顺，于是以极端方式结束了自己的生命。作为同样习惯采用极端方式处置问题的同业人员，我在这里对其表示哀悼。

但是哀悼完，擦干眼泪，我们还得说点正事，就是这件事对于我们这些活着的人、同样面临中年危机的人有哪些意义？

首先，我们要看到中兴裁员的大背景，即经济形势的变化。今年上半年，不是流行过一个华为裁员34岁以上员工的话题吗？可见裁员这个事不独中兴有，华为也有，而且后续一段时间内，采取同样行为的公司只会越来越多，因为经济形势越来越恶劣了。从这点讲，中兴裁员的行为不是个人行为，而是公司行为，是中兴为了自救而采取的行为，这点在文章中也可以得到证实。那么中兴所提供的N+1赔偿方案是否存在问题呢？或许钱是少了点，不太讲求人情，但不得不说，该方案的确是符合法律规定的。所以截止目前，尚未能发现中兴存在什么问题。那么事情是否如文章所言，存在打击报复的情况呢？我不能说没有，但即便有，人家帽子扣得到位，也谈不上什么问题吧？所以到了这个时候，不能再纠结于公理正义而浪费时间了，而是要以此事为警钟，为随时被现实逼到墙角的可能做好准备。

那么欧建新是如何被现实逼到墙角的呢？虽然文章表述不细致，但有提到1977年出生，南开大学研究生毕业，华为8年、中兴6年等信息，并且欧的老婆寒夜来客连续用好员工、好老公、好儿子、好父亲这样的字眼来形容欧，这样看来，欧应该是一个不错的人。但这是事情的全部吗？显然这只是寒夜来客眼里的欧，而不是公司领导眼里的欧，公司领导眼里的欧也许是另外一番景象。尽管文章中有提到欧新建经常加班，甚至把工作带回家，并以此评价欧为好员工，但于领导而言，这样的员工只怕要多少有多少吧？倒是已然年届40的欧，又拖家带口的，干活还能跟活力四射的年轻人相提并论吗？恐怕工资要高上一大块才是真的。而且IT这个行业有个极坑的地方，就是知识更迭迅速，5年前的技术，到今天可能就屁都不是，这也是我越来越讨厌IT的地方。所以别讲什么学历不学历、经验不经验的，没用，企业只看重你带来盈利的能力。所以我看到评论里许多人在讲，欧再找份工作就是了，但这个事情是否容易恐怕只有欧自己最清楚，反正我是没打算再去找一份工作的。

但如果仅仅是失业，欧恐怕也不会被逼到墙角，毕竟一个40岁的中年男人，怎么也该有点积蓄吧？而且中兴在我印象里，素来是以钱多活少著称的。但就现实来看，事情恰好相反，欧对钱的纠结，可以说是如生命一般。怎么会出现这种情况？虽然文章中没有说她们家庭的资产结构，但我猜测，其资产结构是极端不合理的，很可能负债多而存款少，这就可以解释公司明明准备赔偿N+1的工资，还要回购股份，而欧却最终由于股价太低而选择自杀的原因了。也是，一个男人，断了收入，手里又没钱，不对社会做点极端的事情，就只好对自己做点极端的事情了。

但这样就牵扯到另外一个话题，即近年中国流行的几个荒谬言论：

第一个，铁饭碗。尽管现在不大讲了，但为什么还有那么多人要考公务员，要进国企？其实心理、思路可谓一脉相承。但是上个世纪末的下岗潮证明，别说在欧美，就是在中国也不可能有铁饭碗的。虽然近二十年中国经济发展的不错，一个漫长的上升期，新式军舰像下饺子一样，但华为、中兴已经为我们创建了新的榜样。

第二个，中国老太与美国老太买房的故事。这个我是在上世纪末听到的，大意是中国老太攒三十年钱才住上房子，而美国老太在住上房子三十年后还清了贷款。这个故事逻辑很好，但却不符合现实。其实早在2007年次贷危机的时候，我们就应该发现问题了，可惜那个时候的中国还在快速发展期，而我们对美国的关注也仅限于顶层，未如电影《大空头》一样去关注一个一个的点，所以我们没有感受，不知道破产是个什么样子。这次欧新建用自己的生命给我们做了提醒，我们还要继续忽视吗？

第三个，房价一直涨。也不知道哪个驴入的讲的，海南、温州不是例子？甚至当前经济的大背景已经是资金从紧，这批人还要坚定不移的看好未来房价，好吧，我只能说没发生过不代表不会发生，拭目以待。

第四个，高通胀背景下，买房是最好的选择。或许吧，但我想说这话的人一定是做投资的，而不是刚需。刚需会把房子卖掉吗？就算卖掉怕也是换房吧？所以这个钱就如同股票账户一样，纸面富贵罢了。我还是坚持，高通胀背景下，对于钱不多的人，留钱才是最佳的选择。

讲了这么多，真不是为中兴辩驳，而是现实对我有所触动。现在的我还处于准备阶段，可是你有准备了吗？







