---
title: 赚钱容易吗？其实每个人赚钱都不容易
author: 普2019
date: '2021-07-05'
slug: '242'
categories:
  - Translation Articles
tags:
  - Business
---

[Source](http://www.admincun.com/309.html)


大家是不是经常看到朋友圈各种晒美图晒旅游，总感觉为什么人家赚钱这么容易，自己赚钱却需要熬时间熬体力，最后拿着一点微薄的收入不敢乱花，其实每个人赚钱都并不容易，在风光的背后是你看不到的付出。


为什么赚钱不容易

如果有些社会阅历浅，见识并没有那么丰富，一定会觉得这个理由很扯，虽然自己赚钱不容易，但是那么多人生来就很有钱，人家随便弄个公司又能赚钱，其 实这只是我们能够看到的表面，实际上呢没有谁的财富是无缘无故而来的，哪怕是富二代，他们的财富也是基于父辈或祖辈的努力，他们看起来容易，其实只不过是 有人替他们承担了那些不容易。

当然即使有钱人也并不一定就容易，纵然有祖辈的积累，对于他们而言也会有不容易的时候，大家不见有多少富二代最后也会负债累累，债台高筑，有多少创业成功的人士也会经历种种挫折，只是他们风光了，曾经这些的灰暗被掩埋了。

---

下面的案例大家可以体会一下：

任正非：半年时间都是噩梦，常常哭醒

“我无力控制，有半年时间都是噩梦，半夜常常哭醒”、“研发失败我就跳楼”，这是任正非在华为创业维艰期决绝说出的话。

京东曾在2008年倒闭，刘强东为此一夜白头。

马云创业初期，公司入不孵出，为了补贴公司，马云经常去义乌进小商品回来卖。后来在北京创建中国黄页同样失败，团队一群人在离开北京前一天去逛长城，却忍不住在长城上痛哭。

现在的马云一年飞行了800多个小时，平均每天2小时在飞机上度过，走访了33个国家和地区；

李开复罹患淋巴癌前，经常和年轻人比赛熬夜，半夜回邮件；

网上曾流传过王健林的一天作息表，他早上4点起床，健身45分钟，工作量约是16小时；

柳传志讲到他得病时，往往病好了第二天就又立刻工作，后来变成一个常态，经常地半个月左右就要犯一次……

这种作息及高强度的工作在企业家中并不是少数，而如今90岁的李嘉诚、88岁的巴菲特还坚持在企业的一线工作。

搜狐创始人张朝阳，张朝阳用“悲催”来形容他的2012年，他焦虑、抑郁，精神上常常处于一种外人无法理解的恐惧之中。“我什么都有，但我就是很痛苦！”

---

上面是成功的案例，下面是没有挺过来的

2011年，上市仅3天的万昌科技股份有限公司董事长高庆昌坠楼自杀，据了解他生前患有严重抑郁症；

2015年11月，上市公司金莱特董事长田畴因突发心肌梗塞去世，年仅43岁；

2016年3月，苏州金龙总经理吴文文自杀身亡，年仅46岁，长期患有抑郁症；

2016年10月，“春雨医生”的创始人张锐因心梗猝死，年仅44岁；

2017年2月，途牛旅游网预定中心副总经理李波，因心梗猝死，同样44岁；

2018年1月，曾经的天才it少年，创业明星茅侃侃，烧炭自杀，年仅35岁

2018年1月，重庆游戏界元老冒朝华因突发脑溢血去世，年仅38岁；

我们与其羡慕别人的容易，不如努力强壮自己，让自己成为别人羡慕的人，其实你要明白每一个值得羡慕的人，曾经或许都和你一样，无非是他们经历了种种 的不容易，以及经历了种种的痛苦，终于从泥沼中站起来，但人生路还很远，起来并不意味着永恒，所以我们应该时刻保持警醒，不因为一时得失而情绪激动，赚钱 不容易，我们坚持总会有容易的时候，赚钱容易我们不珍惜也总会过去。

