---
title: Is Capitalism Moral?
author: Walter Williams
date: '2020-11-02'
slug: '84'
categories:
  - Translation Articles
tags:
  - Economics
  - Moral
  - Propaganda
---

[Source](https://www.youtube.com/watch?v=fJr2RO7g7jI)

Many people believe that free market capitalism is selfish, even immoral. They say it's about greed, about a hunger for money and power; that it helps the rich and hurts the poor. They're wrong. The free market is not only economically superior, it is morally superior to any other way of organizing economic behavior. Here's why. The free market calls for voluntary actions between individuals. There's no coercion. In a free market, if I want something from you, I have to do something for you.

Let's say I mow your lawn and you pay me twenty dollars. What does that twenty dollars really mean? When I go to the grocer and say, "I would like to have four pounds of steak" He, in effect, says to me, "You want a lot of people to serve you -- ranchers, truckers, butchers, and packagers. All these people have to be paid. What did you do to serve your fellow man?" "Well," I say, "I mowed my fellow man's lawn." And the grocer says, "Prove it." Then I offer him the twenty dollars. Think of the money that you've earned as a certificate of performance. It's proof that you've served your fellow man.

People accuse the free market of not being moral because they say it's a zero-sum game, like poker, where if you win, it means that I have to lose. But the free market is not a zero-sum game. It's a positive sum game. You do something good for me, such as give me that steak and I'll do something good for you -- give you twenty dollars.
I'm better off because I valued the steak more than I valued the $20 and the grocer is better off because he valued the $20 more than he valued the steak. We both win. Ironically, it's the government, not the free market, that creates zero-sum games in our economy. If you use the government to get a food stamp, a farm subsidy or a business
bail out, you will benefit -- but at the expense of your fellow citizens. Isn't it more moral to require that people serve their fellow man in order to have a claim on what he produces rather than not serve others and still have a claim? But, a lot of people ask, what about giant corporations? Don't they have too much power over our lives? Not in a free market. Because in a free market We, the People, decide the fate of companies who want our business.

Free market capitalism will punish a corporation that does not satisfy customers or fails to use resources efficiently. Businesses, big and small, that wish to prosper are held accountable by the people who vote with their dollars. And, again, it's the government that can undo this.

Take the example of the American automobile industry. It was struggling to survive in 2009. Why? Because they were producing cars that did not please a sufficient number of their fellow men. In a free market, they would therefore have gone bankrupt. The market would have said, "Look, you're done. Sell your plant and equipment to somebody who can do a better job." But when Chrysler and General Motors failed, they went to Washington D.C. and got the government to bail them out. The government bailout essentially meant to them: "You don't have to be accountable to customers and stock holders.' No matter how inferior your product is and no matter how inefficient you are, we'll keep you in business by taking your fellow man's money. When government interferes in this way, it takes the power away from the people and rewards companies that couldn't compete successfully in the marketplace. That may work out very well for politicians, big unions and corporate officers, but it seldom does for the tax payer.

That's why a free market system can only work if there is limited government. Limited government means you and I decide which businesses survive. That's the America that our Founding Fathers envisioned -- a limited government that has only a few specifically mentioned -- or enumerated -- powers that are listed in Article I, Section 8 of the United States Constitution. It's this brilliant, limited-government notion that produced the wealthiest nation in history. In a free market, the ambition and the voluntary effort of citizens, not the government, drives the economy. That is: people, to the best of their ability, shaping their own destiny.

Sounds pretty moral to me.