---
title: 张朝阳与马云的颠倒人生
author: 老邱
date: '2020-12-06'
slug: '97'
categories:
  - Translation Articles
tags:
  - History
  - Evolution
  - Conservative
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

> 张朝阳，马云，贝索斯，杨元庆都是同一年出生的。

张朝阳也算得上中国互联网发展史上的“教父级人物”。1998年前后，他是马化腾、丁磊等人的创业偶像，激发了一代人的创业梦想。

然而，互联网大潮一浪盖过一浪，即使是当年的大佬，稍有懈怠也会被拍在沙滩上。如今张朝阳已经逐渐边缘化，而曾经名不见经传的小人物们则个个成为了独霸一方的互联网诸侯。

如果说拿60后的张朝阳与70后的马化腾、丁磊他们相比多少有点拳怕少壮的意思，那与张朝阳同岁的马云与之作对比，则能明显的看出，两位大佬拥有着相互颠倒的人生。

而且2019年对他们俩来说都很重要，因为张朝阳需要奋斗，而马云则要退休了。

# 学霸的病与学渣的命

9月10日出生的马云比10月31日出生的张朝阳大51天，但事实证明，并不是出生早就学习好。

马云在高中时期因为偏科（不喜欢数学）成为了一个学渣，张朝阳则因为在高中偏科（特别喜欢物理）而变成了一个学霸。

两个人的命运在高考的节点上第一次发生了分叉。

1981年，张朝阳从西安顺利考入了清华大学物理系。

一年后，马云才第一次参加高考，却因为数学只考了1分而落榜，第二次高考马云的数学略有长进，考了19分，第三次才有了质的变化考了79分，马云才如愿进入杭州师范大学专科就读，恰逢当年杭州师范大学英语本科录取人数不够，马云才因为英语好而递补成本科学生。

作为学霸，张朝阳在清华过得并不开心，至今清华大学的官网上还挂着张朝阳2000年写的《张朝阳：读清华很苦》这篇文章，篇幅不长，但能从字里行间看出张朝阳的痛苦：

“厌学是肯定的，太苦了，没怎么享受过生活。而且，这么苦，却学不到任何东西。这么多人在一起做同样的事情，一起吃，一起睡，做一样的功课，就像一个小社会，分数就是一个人的身份。其实特没意思，（我的）学习效率极低。”

张朝阳说自己在清华清华最轻松的一年是最后一年，因为拿了奖学金知道自己要去留学了，所以“不需要竞争，也就不想念书了”。

他对自己在清华的求学经历评价并不高，最后在文章中写道：“对我来说，就是人生的一段经历，这是因人而异的”。

当然张朝阳对母校清华的感情还是有的，后来他创业有成，也曾多次向母校捐款，数额也有几千万之巨。

而在1984年第三次高考才考入杭州师范大学的马云，则对自己在杭师大的求学经历十分满意，在这里他并没有从学渣进化成学霸，但他过了一个五彩斑斓的大学生活，据他的大学同学回忆，马云曾在大学里组织过校内十大歌星评选的活动，被同学称为“可能是中国最早的选秀活动”。

他还当选了全校的学生会主席，并在寒暑假为贫困同学联系铁路上勤工俭学的机会。大二大三的时候，马云成功地申请成为了一名党员。

2018年5月13日，在杭州师范大学110周年校庆的时候，马云作为嘉宾在现场演讲，他说在杭师大求学的日子里，其中有两堂课让他印象深刻。

第一堂课是学习面对失败和挫折，“我是失败了两次才考上杭师大的，我一直争取在做一个成功的失败者”；第二堂课，“就是把我培养成了一名老师”。

马云后来也说过：“我没学过怎么当CEO，我是用当老师的方法来当CEO。”而每当有人问起他的母校，他都会说：“在我心里，杭师大是最好的学校，没有之一。”

在校庆的演讲中，他告诉自己的学弟学妹们：“如果你毕业于杭州师范大学，请你用欣赏的眼光看看自己。”

在捐助母校这一点上，马云比张朝阳出手更大一些，2015年他曾给杭师大捐助1亿元，设立“杭州师范大学马云教育基金”，他说“1亿不算多，但希望通过促进母校的发展与师范人才的培养”。

张朝阳在清华当学霸的痛苦，也让他后来得了一种病，叫名校综合征，今年7月初他接受媒体采访时还提到过，说这是一种厌学精神，主要表现就是“不想接受新的东西，这几年我把它克服了”，张朝阳说。

而马云在杭师大一边当着学渣，一边又通过担任学生会主席、组织各类活动充分地锻炼了自己的组织管理能力，为他日后的创业打下了一点点基础。

这是一个学霸的病和一个学渣的命。

---

# 始于1998的创业反差

张朝阳早年创业成功的风光与马云创业的坎坷也形成了鲜明的对比。

1997年，张朝阳的老师尼葛洛庞帝第一次访华，面对媒体的追问说出了那句“我通过投资查尔斯的公司来了解中国的发展”，从此张朝阳一朝成名天下知，他成了互联网创业的启明星般的人物。

而1997年的马云却停止了自己在“中国黄页”的创业，带领6位同事北上，在北京出任中国国际电子商务中心国富通信息技术发展有限公司总经理，他们还开发了外经贸部的官方网站。

但在马云北漂的14个月里，他过得并不开心，事业也并非他想象的那般自如。

后来他回忆这段日子时说：

受过挫折、失落过、迷茫过，忍受过地下室，也挤过早上六点的公交车。

1998年，34岁的马云决定离开北京。临走之前马云还曾去搜狐面试过，接待他的人名叫古永锵，不过马云最终并没有加入搜狐成为张朝阳的手下，而是带着他自己的手下回到了杭州创业。

离开北京的前一天，马云带着团队一起去爬了长城，一起在小酒馆里喝得烂醉，一起唱着《真心英雄》一起流泪，一起约定以后要做一家不让自己后悔的公司。

不过，在功成名就后的2016年，马云说出了一句：“我人生中最大的错误就是创立了阿里巴巴。”

回看中国互联网兴起的1998年，马云的记忆是迷茫和苦涩的；但对张朝阳来说，记忆却是甜蜜与充满激情的。

因为这一年，张朝阳创办的爱特信公司在摸索了2年后推出了搜狐网站，并且公司也更名成了搜狐。

当年2月25日，在中国大饭店的地下室里，搜狐召开了正式成立的发布会。

张朝阳第一个感谢的是北京牛栏山酒厂，它是搜狐网历史上的第一个广告客户，投放额度5万元。

1998年10月，张朝阳作为中国互联网创业精英，被美国《时代周刊》评为“全球50位数字英雄”之一，与他一起入选的还有比尔·盖茨、乔布斯等美国科技圈大佬。

张朝阳的成名，还直接激励了马化腾在1998年11月11日创办了腾讯公司。

有趣的是，就在1998年冬天，马云带团队南归杭州的时候，刚刚创办腾讯的马化腾却从深圳北上跑过石家庄4次，在1999年3月开发出QQ之前，小马哥为了腾讯的生存也去石家庄跑电信的寻呼机项目。

后来，马化腾在2017年11月在石家庄参加中国国际数字经济峰会时说：“石家庄是腾讯的发源地，腾讯的第一单业务、第一笔收入就来自石家庄。”

在这个特别的1998年，互联网大佬们不同的命运轨迹乍看起来似乎有云泥之别，但细看却有人正蓄势待发。

---

# 张朝阳的紧迫感与马云的悠悠然

2019年7月初，搜狐因为做无人机的项目为张朝阳安排了一次专访，当时说好的只聊无人机相关话题，但最后记者们却没有“控几好寄几”，问了张朝阳不少有趣的话题。

其中一个问题是“2019年上半年的工作中给您带来最大成就感的一件事是什么？”，当时听到这个提问后，张朝阳竟沉默思考了长达25秒钟，然后说：“很多事情吧，也不好说（具体是哪一件）。产品的事情就不说了，做了各种产品迭代，然后就是有了一种紧迫感，就是做事情不能拖延。”

被问到未来的目标时，张朝阳说：“把搜狐的故事重新带回来，希望把搜狐重新带向辉煌。”

当时一名美女记者接茬问道：“要是带不到（辉煌）呢？”

张朝阳语气颇为坚定地说：“肯定能带到，因为我时间多啊，我打算活100岁呢，而且我身体很好。比如我80岁的时候还在做搜狐，（别人）能做过我吗？”

听到这话时我就心想，张朝阳80岁时如果还做搜狐的话，那马云届时已经退休25年了，马云2017年前后曾经公开表达过对加勒比海岸的阳光和沙滩的向往，“我不想死在办公室里，而是想在阳光沙滩上”，马云吐露自己的心声。

如今的马云，早已选定了接班人逍遥子张勇，自己从几年前开始就是在全球飞来飞去，与各国政商要员交朋友，推广阿里的全球电子交易平台，还在联合国担任特别顾问做公益，基本上不再管理一线了。

而张朝阳还没有接班人，他2007年就曾对媒体说过要选接班人，当时一口气晋升了王昕、楚媛、龚宇三位C字头高管，分别担任CMO、CFO和COO。

不过，与马云创业有18罗汉且后期总有关键人才加盟相比，张朝阳的创业则更像是孤胆英雄一般，而且有“互联网黄埔军校”之称的搜狐在发展历程中也流失了不少优秀人才。

比如，2004年张朝阳刚晋升了古永锵担任COO，但同年年底古永锵就提出了辞职，第二年年初离开搜狐创办优酷；2007年年初张朝阳晋升了龚宇担任COO，2008年底龚宇又被公司宣布即将离职，2010年初加盟了爱奇艺。

如今优酷和爱奇艺背靠阿里和百度，与腾讯视频组成视频行业的“爱优腾”组合，把张朝阳的搜狐视频落下了不少。

当然，马云在创业过程中也流失了不少人才，但得益于马云的管理才能和勤奋工作，阿里通过严谨的运作机制保证了公司一直是震荡上升状态。而搜狐则因为张朝阳曾经一段时间的疏于管理，困于“好人文化”，一度被圈内当成是互联网养老公司，渐露疲态。

截至今天，搜狐的市值仅有3.24亿美元，阿里的市值则是4966亿美元，两者相差超过1500多倍。

同样的55岁，马云已经放下公司的一切正式退休了，而且有张勇作为阿里巴巴这艘巨舰的掌舵者，马云可以放宽心去颐养天年；而张朝阳却需要为了让公司盈利、重回互联网中心而奋斗终生，在他背后是搜狐有没有接班人、搜狐为什么不私有化、张朝阳做投资是不是更能收益最大化……等等一系列追问。

张朝阳如今也已经猛醒，今年年中他对媒体说：“我曾经很风光，然后现在有点落寞，但是我找到了人生的意义，认真地做好手头的事情。”

然而，互联网行业的突出特点是竞争激烈且时不待我，如今张朝阳幡然醒悟并奋力追赶，不知是否还来得及。但愿，将来在互联网历史的注脚中，不会将之称为“悔之晚矣”。

---

# 张朝阳的泡吧与马云的酒吧

事实上，对于自己曾经疏于管理的那段时期，张朝阳也曾经公开反思过——从1998年到2010年前后，他还是比较飘的：“自己有钱又有名，受好的教育，赚的钱是阳光财富，从事的又是一个新兴产业，把互联网带进了中国。”

当时，搜狐接连做出了搜狗和畅游，2008年还拿下了奥运会的官网，2009年畅游成功上市，这一切的顺境让张朝阳变得虚荣和自我膨胀。

那时的张朝阳还很喜欢泡吧，高晓松曾经在一档视频节目中回忆过和张朝阳一起泡吧“撩妹”的故事：

在一个屋子里，我、张朝阳，还有联想的总裁刘军，我们三个都是清华的。进去玩，然后有人介绍说这个姑娘是中戏的，这个姑娘是北电的，有一个姑娘说“我是清华的”，我们仨就说，哎，这挺有意思啊！我们很客气的没有用“清华切口（江湖黑话）”来拆穿她，就问姑娘：你是哪个系的？姑娘说：算数系的。

高晓松说：“当时我们就心里想这姑娘是不是只上过小学，因为只有小学才有算数这门课”。

张朝阳自己也曾回忆起在北京半夜叫马云陪自己泡吧的经历：

记得有一次晚上我在酒吧唱歌，那时候马云也在北京，于是我就叫他出来玩。结果马云夜里12点才过来，待了半小时就走了，因为他正在拼命干活。

或许张朝阳和马云后来的人生剧本，就在那时走向了不同的发展方向：一个沉迷于娱乐之中，另外一个则在拼命奋斗，谁能获得更大的成就显而易见。

马云在恰当的年纪做了他应该做的事，而张朝阳则在功成名就之后，没有了继续努力的动力。这倒是像极了当年他在清华大学的最后一年，拿到了国外留学的奖学金，知道自己要去留学了，“不需要竞争，也就不想念书了”。

当然，马云那时之所以没跟张朝阳一起泡吧，也可能是因为他曾经当过老师吧？类似的还有罗永浩，老罗说过：从前和朋友去唱卡拉OK，他不会主动叫姑娘，但别人叫也不避场，自从成为老师后，只要别人叫女孩子，我马上退场。

三十年河东，三十年河西。张朝阳如今已经不怎么去泡吧了，但马云却会主动提出去玩一玩。

去年7月3日，张朝阳在北京搜狐媒体大厦接受媒体专访，回应搜狐公司运营的事宜；也是同一天，马云在杭州阿里巴巴总部接待了29位来自澳大利亚的留学生，他提议说晚上要不要一起去唱kTV，但突然发现人太多，唱K不方便，于是他提议说，要不要去我们的酒吧坐坐？

那天晚上，澳大利亚的留学生们一起去了HHB平头哥酒吧，据说唱歌和啤酒的费用都由马云全包了。

在张朝阳忙于收拾自己的团队，试图保住自己的“城池”的时候；马云却刚好相反，他变得十分悠闲，现在想在酒吧待多久就待多久。

---

# 写在最后

古人常道：时也，运也，命也，非吾之所能也。

马云与张朝阳在年少气盛时，应该也无法预料自己此后的人生走向。如今看起来像是“颠倒人生”，实则是个人在时代潮流中所做每一个选择的不断叠加与相互效力，最终成就了如今的光景。

无论是如张朝阳般少年顺遂，青年成名，中年颓靡又大彻大悟，过上了一段“先甜后苦”的人生苦旅；抑或是像马云般少年波折，青年坎坷，中年得志且顺势而上，演绎了一出“先苦后甜”的逆袭大剧，或多或少都对后来者有所警示或启发。

至于各自的成败得失，他们心中自有定数，其余的统统将交给历史去评说。



