---
title: 人生太短，别给自己找不痛快
author: Guanghua Mao
date: '2021-03-15'
slug: '147'
categories:
  - Translation Articles
tags:
  - Insights
---

[Source](http://oppo.yidianzixun.com/article/0OyvPNKC?appid=oppobrowser&share_count=2&impid=-1134756418_1585463783189_0LEtVDKR_n2n&__publisher_id__=TQy_f16IRzmSaKPh4tRCqw)

古人云：燕雀安知鸿鹄之志！不同的人，不同的志向，不同的高度，别想着他一定能懂你！

永远不要和不同层次的人争辩。理解你的人，你略微表达自己，他就明白了；不理解你的人，你磨破了嘴皮，他也不把你当回事。

路不同，不相与谋，道不同，不必同行。

苍鹰眷恋的是高空，麻雀喜欢的是枝头，你和麻雀说天空多么辽远，麻雀和你说枝头多么安逸，鸡同鸭讲，争也白争！

如同坐井观天的青蛙，他不愿意从他的世界出来，你和他说多少外界的美好，他都会当成欺骗。

不同的世界，你和他争什么呢？

即便争过他，反而被人笑话，和“傻瓜”论短长，赢了有什么意义？

层次不同，不用争，不用盲目求谁的赞同。他不懂你，说再多也是白搭，与其和他争长论短，不如转身各自为安。

人与人之间，想要长久相处，想要获得认同，我们能做的不是争，而是让。

让，彰显的是一个人的心胸，体现的是一个人的气度。让一步海阔天空，退一步云淡风轻！

这个世界，谁也不用迎合谁，谁也不用讨好谁。两个人，三观一致才能走得长远，三观不合，争论再多也不会同路。

其实有的时候，你的也不一定是对的，他的也不一定是错的。只是你们的生存环境不一样，你们从小到大走过的路不一样。

何必相争？不一样的人，拥有不一样的心，对一件事的理解和接受程度也不同。不要总是想着争，也无需强求对方的认同。

他怎么想是他的事，做不到理解咱，咱也不去较真。懂你的人，自会把你善待，不懂你的，不必和他多言！

想成为什么样的人，就付出多少的努力！

想拥有什么样的圈子，就先要提升自己！

你的目标就是你的世界，你的世界就是你的人生！

不要总想着争，多多成就你自己，当你充分认识自己，不断成就自己，你定会遇到更多懂得你、理解你的人。

这个世上，不同的人走不同的路，不同的心有不同的天空。不被理解的时候，不要气馁，问心无愧就好，坦坦荡荡就行。

永远不要和层次不同的人争辩！挤不进的圈子也不用强融。他人的话不堪入耳，就不听；他人的事你看不惯，就不看。

人生太短，别给自己找不痛快，人心不同，多些换位和体谅！用包容赢得人心，用快乐装点人生！