---
title: 读书改变命运，是最大的中国式骗局
author: 蔡宁
date: '2021-06-26'
slug: '206'
categories:
  - Translation Articles
tags:
  - Culture
  - Decision
  - Propaganda
---

### [Source](http://blog.sciencenet.cn/blog-1213429-1024743.html)

科学网名博主喻教授近日回母校中学，发表了励志演讲[《努力几年，足以改变你一生的生活》](http://blog.sciencenet.cn/blog-117889-1024421.html)



大意是讲从小吃不饱，穿不暖的乡村苦孩子，通过辛勤努力，终于出人头地的故事。

这篇博文目前已有超过80个推荐人，超过80条评论。可是质疑，我只看到知名学者谢力教授的一个帖子而已。这说明，这篇博文所反映的价值观是社会主流的。

然而事实上，读书改变命运，是最大的中国式骗局，危害甚大。读书本身，其实并不能改变命运。真正决定命运的，是制度。只不过有时读书恰好迎合了制度而已。古人读圣贤书，可以科举做官，改变命运。后来古人所读的圣贤书失去价值了。到某个历史时期，知识分子变成臭老九，读书反而成坏事了。恢复高考，只要考上大学，就成了人人羡慕的国家干部。高考改变命运。再后来有段时期，上新东方，考托考G，出国改变命运。时代变迁，“读书”和“命运”的关系一直在变。如今，又不再是“读书改变命运”的时代了。

功利性的学习，为考试过关而读书，可能是教育界最大的问题。有多少孩子在学习过程中拈轻怕重，生怕在不考的知识上多浪费自己一分宝贵的精力。又有多少孩子上了大学以后发现前途迷茫，从而彻底放弃读书，甚至变得对抗读书的？就是因为曾经被这句话所欺骗，所以再不上当。

从小到大，只要是考试能解决的问题，在下无不一次成功。作为应试教育的真正成功者，我深知其中窍门何在。不在于“智商”，更不在于“用功”，乃在于心法也。其实有意栽花花不发，无心插柳柳成荫。越是计较结果，则越拘执心塞，往往越发挥不好。功利性的学习，本质上属于一种不专心的表现，心思不在知识本身，而在功利，焉能取得好成绩？只有日常的学习、涉猎、思考不局限于考试范围、大纲范围，不单以学生的标准要求自己，方能收放自如。考试，只是游戏耳，挥洒可也。

喻教授博文中透着一股浓郁的唯物质论(唯物主义？)，作为高级知识分子，境界是不甚高的。所谓“改变你一生的生活”者，显然指的是物质生活。无论是针对喻教授自己，还是针对台下听众孩子们。可是为了改变你的物质生活，读书并非必须的途径。

那么问题来了，读书究竟有什么用？我想，这才是身为大学教授，应该解答的。大学教授，光临山村中学，总应该说点跟孩子们的老师家长不一样的，能令他们耳目一新的观点才是。

有个歪果仁教授，是我的好朋友，他总想劝我信教，认为我有慧根...他这么劝我：你何必管它真假呢？不如姑信其有，你非但不会损失什么，反而在世俗人生之外，白白多了一个彼岸人生，这是相当划算的买卖。借用这个故事打比方，读书，可以使我们在世俗的物质生活之外，多了丰富多彩的精神生活，使我们的人生更深刻更有意义。一个人有思想，有情操，有艺术的品味，就可以傲视权贵，睥睨那些貌似依世俗标准强于自己，实则精神空虚的家伙。因为内涵比他们更深，生活比他们更幸福。使人彻底摆脱草根气质，唯有读书和思考，别无他途。

“是真名士自风流”，真正的知识分子，应该是透着一股倾倒众生的名士范儿。曹师则贤是大家都知道的典型人物。再比如科学网上我所认识的谢力教授，马军教授，杨正瓴教授，葛素红教授，王毅翔教授...反之，如果格调不甚高，则不免流于言语无味，面目可憎，算不得真正的知识分子。