---
title: 'Book Review: Guide To Analysing Companies'
author: Guanghua Mao
date: '2021-03-01'
slug: book-review-guide-to-analysing-companies
categories:
  - Original Articles
tags:
  - Accounting
  - Book Review
  - Business
  - Decision
---

# Introduction

The aim of this book is to provide an understanding of how to analyse and assess the performance and financial position of a company from the various sources of information available.

The examples focus on retail, service and manufacturing companies rather than banks and other financial services companies, which are subject to a different set of legal and reporting measurements.

Profit and finance are the two broad strands interwoven in the overall management of successful business organizations today. Profit is not sufficient on its own; a company must have the resources to allow it to continue in business and to flourish. Without profit there can be no dividend or share value improvements, or reinvestment for future growth and development. A substantial part of this book focuses on various ways of identifying and measuring profitability.

An important lesson from the downturn in the 1990s and the 2008 global financial crisis is to invest in a company only when you are absolutely certain you understand the business and sector within which it operates. If you cannot see where the profit are coming from, don't invest. If you cannot understand what the company does, don't invest.

---

# Part 1 Understanding The Basics

## 1. The Annual Report and What Underlies It

An annual report contains two distinct types of information: quantitative - the financial statements; and qualitative - various reports and a management commentary. The annual report tends to be too long and too complex.

Information on a company's financial position is mainly derived from the balance sheet and cash flow statement. An assessment of company performance will focus on the income statement of changes in equity.

It is recognised that if the cost of collecting the information is greater than the benefit of providing it, it is not worth it. The report is expected to be timely

### Double Entry Book-keeping

### Who Publishes Accounts?

### Limited Liability

Most trading companies have limited liability. This was introduced in the 1860s to provide shareholders with some protection against a company's creditors. Shareholders providing a company with capital, through the purchase of stocks and shares, cannot be forced to contribute any further money to the company or its creditors.

### The Corporate Persona

A company is a legal entity separate from its managers and owners and is referred to as an entity in most accounting standards.

After having realised all assets and repaid all loans and creditors, the last act of a company, before it ceases to exist, is to pay what remains to the shareholders - the net worth of the company.

### Private and Public Companies

A quoted or listed company is one whose shares can be bought and sold on a stock exchange. A quoted company must publish more information than a private company. This is to satisfy legislation and the requirements of the listing stock exchange. A private company cannot offer its share for sale to the public, so different safeguards and reporting requirements apply compared with those for public or stock exchange listed companies. Private companies can be large organisations.

### Ownership and Management

Shareholders of a private company are often directly involved in its management, often with members of the family acting as directors. 

### Consolidated Accounts





## 2. The Statement of Financial Position

## 3. The Income Statement

## 4. The Statement of Cash Flows

---

# Part 2 Assessing the Facts

## 5. Guideline for Financial Analysis

## 6. Measuring Profitability

## 7. Measuring Efficiency

## 8. Working Capital and Liquidity

## 9. Capital and Valuation

## 10. Strategy, Success and Failure






















