---
title: 'Book Review: Make it Stick'
author: Guanghua Mao
date: '2022-01-12'
slug: '365'
categories:
  - Original Articles
tags:
  - Book Review
  - Epistemology
  - Learning
---

>在 Youtube 上看过这本书的讲解，同时结合自身的实际经验觉得此书甚好。

A growing science of learning: highly
effective, evidence- based strategies to replace less effective but
widely accepted practices that are rooted in theory, lore, and
intuition. But there’s a catch: the most effective learning strategies are not intuitive.

WE apply two of the primary learning principles in the book: spaced
repetition of key ideas, and the interleaving of different but
related topics.

If learners spread out their study of a topic,
returning to it periodically over time, they remember it better.
Similarly, if they interleave the study of different topics, they
learn each better than if they had studied them one at a time in
sequence. 

While much remains to be known about learning and its
neural underpinnings, a large body of research has yielded
principles and practical strategies that can be put to work immediately, at no cost, and to great effect.


---

# Learning Is Misunderstood

 what we mean in this book when we
talk about learning: we mean acquiring knowledge and skills
and having them readily available from memory so you can
make sense of future problems and opportunities.

There are some immutable aspects of learning that we can
probably all agree on:

First, to be useful, learning requires memory, so what we’ve
learned is still there later when we need it.

Second, we need to keep learning and remembering all our
lives. We can’t advance through middle school without some
mastery of language arts, math, science, and social studies.
Getting ahead at work takes mastery of job skills and difficult
colleagues. In retirement, we pick up new interests. In our
dotage, we move into simpler housing while we’re still able
to adapt. If you’re good at learning, you have an advantage in
life.

Third, learning is an acquired skill, and the most effective
strategies are often counterintuitive.



Learning is deeper and more durable when it’s effortful.
Learning that’s easy is like writing in sand, here today and
gone tomorrow.


When the going is harder and slower and it doesn’t
feel productive, we are drawn to strategies that feel more
fruitful, unaware that the gains from these strategies are often
temporary.

Rereading text and massed practice of a skill or new knowledge are by far the preferred study strategies of learners of all
stripes, but they’re also among the least productive. By massed
practice we mean the single- minded, rapid-fire repetition of
something you’re trying to burn into memory, the “practicepractice-practice” of conventional wisdom. Cramming for exams is an example. Rereading and massed practice give rise to
feelings of fl uency that are taken to be signs of mastery, but for
true mastery or durability these strategies are largely a waste
of time.

Retrieval practice—recalling facts or concepts or events
from memory— is a more effective learning strategy than review by rereading. Flashcards are a simple example. Retrieval
strengthens the memory and interrupts forgetting. A single,
simple quiz after reading a text or hearing a lecture produces
better learning and remembering than rereading the text or
reviewing lecture notes.

When you space out practice at a task and get a little rusty
between sessions, or you interleave the practice of two or
more subjects, retrieval is harder and feels less productive, but
the effort produces longer lasting learning and enables more
versatile application of it in later settings.

Trying to solve a problem before being taught the solution
leads to better learning, even when errors are made in the
attempt.

The popular notion that you learn better when you receive
instruction in a form consistent with your preferred learning
style, for example as an auditory or visual learner, is not supported by the empirical research.

When you’re adept at extracting the underlying principles
or “rules” that differentiate types of problems, you’re more
successful at picking the right solutions in unfamiliar situations.
This skill is better acquired through interleaved and varied
practice than massed practice. 

 In virtually all areas of learning, you build better
mastery when you use testing as a tool to identify and bring
up your areas of weakness.

All new learning requires a foundation of prior knowledge.

 If you’re just engaging in mechanical
repetition, it’s true, you quickly hit the limit of what you can
keep in mind. However, if you practice elaboration, there’s no
known limit to how much you can learn. Elaboration is the
process of giving new material meaning by expressing it in
your own words and connecting it with what you already
know. The more you can explain about the way your new
learning relates to your prior knowledge, the stronger your
grasp of the new learning will be, and the more connections
you create that will help you remember it later. 

Putting new knowledge into a larger context helps learning. 

People who learn to extract the key ideas from new material and organize them into a mental model and connect that
model to prior knowledge show an advantage in learning complex mastery. A mental model is a mental represen tation of
some external reality.

Many people believe that their intellectual ability is hardwired from birth, and that failure to meet a learning challenge
is an indictment of their native ability. But every time you learn
something new, you change the brain—the residue of your
experiences is stored. It’s true that we start life with the gift of
our genes, but it’s also true that we become capable through
the learning and development of mental models that enable
us to reason, solve, and create. In other words, the elements
that shape your intellectual abilities lie to a surprising extent
within your own control. Understanding that this is so enables you to see failure as a badge of effort and a source of
useful information— the need to dig deeper or to try a different strategy. The need to understand that when learning is
hard, you’re doing important work. To understand that striving and setbacks, as in any action video game or new BMX
bike stunt, are essential if you are to surpass your current level
of performance toward true expertise. Making mistakes and
correcting them builds the bridges to advanced learning.

## Empirical Evidence versus Theory, Lore, and Intuition

How is one to know whose advice to take on how best to
go about learning?

It’s wise to be skeptical. Advice is easy to fi nd, only a few
mouse-clicks away. Yet not all advice is grounded in research—
far from it. Nor does all that passes as research meet the standards of science, such as having appropriate control conditions to assure that the results of an investigation are objective and generalizable. The best empirical studies are experimental
in nature: the researcher develops a hypothesis and then tests
it through a set of experiments that must meet rigorous criteria for design and objectivity.


It turns out that much of what we’ve been doing as teachers
and students isn’t serving us well, but some comparatively
simple changes could make a big difference. People commonly
believe that if you expose yourself to something enough times, you can burn it into memory. Not so. Many
teachers believe that if they can make learning easier and faster,
the learning will be better. Much research turns this belief on
its head: when learning is harder, it’s stronger and lasts longer. What’s apparent from the research is that gains achieved during
massed practice are transitory and melt away quickly. Rereading has three strikes
against it. It is time consuming. It doesn’t result in durable
memory. And it often involves a kind of unwitting selfdeception, as growing familiarity with the text comes to feel
like mastery of the content. The hours immersed in rereading
can seem like due diligence, but the amount of study time is
no mea sure of mastery.

Belief in the power of rereading, intentionality, and
repetition is pervasive, but the truth is you usually can’t embed something in memory simply by repeating it over and
over. 

>重复阅读居然无效，看来我的学习方法的确错了。

