---
title: 股民为什么不自信 为什么信仰如此脆弱
author: 张化桥
date: '2021-03-31'
slug: '200'
categories:
  - Translation Articles
tags:
  - Business
  - Economics
  - Investment
  - Psychology
---

[Source](https://finance.sina.cn/sa/2011-05-30/detail-ikftpnnx9327995.d.html?from=wap)

> 张先生是难得一见的直率的人。


在海内外股市，我们可以看到如下三种有趣的现象：

一是绝大多数人都急于聆听别人的意见(不管是专家还是杂家)。而且，大家也都很容易接受别人的意见。看空的人有道理，看多的人也不错。于是，专家们就经常收到演讲的邀请，生意兴旺。股民们见了庙就拜，见了菩萨就烧香。这可不限于普罗大众，也适用于一些养尊处优的投资经理们。

二是绝大多数股民很容易在极短的时间内抛弃上星期刚刚从演讲中听到的专家意见，因为今天的演讲嘉宾好像听起来更有道理。当然，这意味着股票要换，资产配置要调整。

三是绝大多数股评人士和证券分析师对股价的预测都是在目前价格上再加上15%，或者减去15%(小心的人们只是加减10%而已)。你有没有听过如下的专家意见？“这只股票8块钱买入，7元止损，9元卖出！”。对宏观经济指标比如GDP、通胀、汇率等等的预测，也是如此。可是，大家都知道，市场不是这样走的：股票一年内翻几番，或减值大半，都是司空见惯的事情。在预测股票指数的点位方面，可笑的故事就更多了。

为什么股民们包括一些所谓的专业人士如此胆怯？为什么他们的信仰如此脆弱？我和同事们有时笑谈这种现象，但大家都没有答案。我猜想，可能有这样几个原因：

大家没有做足功课，对1000只股票都知道一些大概，而对每一只股票和它们背后的公司的精髓都不太了解。在计算机面前一坐就是一整天，但是并没有花时间弄通一件事。我们听了许多专家的看法，但都是别人用勺子喂给自己吃的。所以，我们所持的股票一旦下跌10%，我们便怀疑别人知道的多过自己，我们也许中了埋伏，于是“斩仓止损”。反过来，如果我们所持的股票突然涨了15%，我们就不知道还是否应该继续持有。电视上和收音机里，专家们对股票的点评也很可笑：他们可以解答任何人关于任何股票的疑惑，其渊博和自信实在让人佩服。

理论上，每个专业的股票分析员都应该对他们自己所负责研究的那十几只股票和它们背后公司的业务相当熟悉，应该敢于拍着桌子作出更大胆的预测，但是，他们很少这样做。

原因有三：一是他们的工作相当艰难，几乎无法去做。你想想，预测短期(几个月或者一年内的股价和汇价)谈何容易。即使你的基本面分析百分之百正确，市场不见得肯配合。分析师们也许都明白这个道理，所以一般都很谨慎，不愿意太大胆，他们的工作不允许他们看得太远。英文里有句话很恰当：“谁也不想把脖子伸出来让别人砍。”二是股票分析师们经常忙于事务性的工作，比如为基金经理们安排访问公司、组织会议、内部管理等等。三是忙于销售自己和销售自己的观点，没有太多时间做研究。这听起来很有讽刺意味：没有时间做研究，但必须花大量的时间销售自己的研究成果。别笑，这是生意经。2002年，本人在跟某基金经理推介一只股票时，没想到他是真正的专家，我被他的几个基本问题问得浑身冒汗，因为我回答不上来。他穷追不舍，直到我差点昏过去为止。从他的办公室出来，我浑身就像散了架一样。从此，我发誓不再做路演，除非万不得已。

股票投资的事儿，只能洁身自爱。那我们究竟如何解决缺乏信仰的问题？我觉得，两个办法可能很有效。

一是逼迫自己只投资完全弄懂了的股票。很多国人近年来开始谈论到海外买股票，我不敢苟同。如果你的资金在一亿元以下，你投资海外股票所遇到的研究成本和交易成本会抵消你可能创造的回报。投资身边最熟悉的资产永远是最好的策略，全球如此。不要害怕跑输了别人。自己过自己的日子，你生怕错过了机会，你就不能坚持长期的态度。

二是逼迫自己看长期(5年以上)。这说到容易做到难。去年底，本人自以为在美国发掘了一个“十倍股”(ten-baggar)，买了很多，但是它连续半年来一直下跌。起初，我记住巴菲特的教导，追加了很多，不亦乐乎。但后来，它的股价继续下跌。我的底气越来越不足了：我是不是看错了？这时，它已经占到我的资产组合的20%了，好在它的董事长最近提出把公司私有化才让我挽回了信心。

