---
title: 褚老师好，你对人生有没有大的规划啊?
author: 褚明宇
date: '2021-12-24'
slug: '358'
categories:
  - Translation Articles
tags:
  - Personal
---

想起一面试题。

不记得是不是讲过这件事儿了。

如果没讲过最好。如果我已经讲过了，只能请你再容忍一回我这个老年痴呆症早期患者，假装这是第一次听吧，要是能一边听一边做出津津有味的神情就更体贴了。

接着说面试题。

我想说的是一个挺常见，说实话有点儿俗的面试题。

这个问题通常会出现在一场面试的最后，有关你技术、能力、经历的问题该问的都问了，有关具体业务的问题该聊了都聊了，这时候面试官忽然做高瞻远瞩状，换了一种感觉很深刻又略带得意的语气问：

如果给你无限的资源，你现在最想做的事是什么？

这是一个所谓的「开放性」性问题。这个问题虽然俗，但是还是能考察到几个挺重要，而前面那些具体的技术讨论又无法直接测量的维度。

首先是看看你这个人的 vision——远见。可以是在你专业领域里的远见，也可以是你在更广阔领域里的远见。

比如，你是一个搞计算机人脸识别算法的工程师，要是你对这个问题的回答是：我最想做的就是人脸识别，我会把人脸识别算法做得更准确！

那你彻底完了——这是最糟糕的答案。

不幸的是，这类答案应该是面试官们听到的最多的一类答案了。这么回答的人也许会辩解说，这说明我热爱本职工作啊，干一行爱一行有什么不好？

问题就是，不管你从事的是哪一行，钻研的是哪一门技术，此时此刻的玩儿法一定都是在一定资源配置下的玩儿法——不管是人力、物力，还是资金规模，都是「有限」的。

你是一个工程师，现在有一百台高性能服务器可以用于计算，如果你现在有一万台呢，如果有十万台呢？你会怎么怎么做呢？如果你说来说去还是你现在的那些算法那些思路，那你估计很难成为一个有远见的技术大拿。

你是一个小领导，现在有一个二十人的团队，如果你现在有两百人呢？有两万人呢？你打算怎么做呢？如果你说来说去还是你现在熟悉的业务，那你也很难让人觉得你会有什么远大的前途。

而且，在绝大多数情况下，这样的答案不仅仅是不好，而是错误的！二十人规模的业务，就算你只是想线性扩张到两百人，你以为人多了十倍收入就能多十倍了？要是给你两千人呢？一个有二十个员工的餐厅跟一个有两千员工的「餐厅」，根本就是不同的生意。

更重要的是，有两千人，你为什么还老想着要做餐饮呢？有十万台机器，你为什么还只盯着人脸识别不放呢？

那这个问题该怎么回答呢？

简单地说，不管你的答案是什么，必须不能是你现在做的东西，至少不能是现在的思路，最好是完全不同的领域。

这可能跟你平时听到的鸡汤正相反，夸张一点说，你几乎应该：干一行、恨一行。

如果你在二〇〇〇年问马斯克这个问题：给你无限的资源，你现在最想做的事是什么？我想他不会说是电子支付，虽然那时候他创办的电子支付平台PayPal正大获成功。

他会说：我要去火星！

事实就是，短短两年后，在他通过PayPal的成功获得了更多的资金之后，马斯克果断地放弃了电子支付这个买卖，创办了航天公司 SpaceX. 

如果你在二〇〇五年问罗永浩这个问题：给你无限的资源，你现在最想做的事是什么？我不知道他当时的答案会是什么，但我想绝不会是：教英语！虽然那时候已经做到了新东方的头牌。我想答案也不会是：当网红！虽然当时他已经是个流量巨大的不折不扣的网络红人。

老罗后来做了什么，大家都有目共睹。

注意，马斯克不是在发财之后才开始思考要发火箭的，老罗也不是在获得了投资之后才开始想要颠覆人机交互的，这是他们一直的「理想」。

理想——正是这个面试题试图测量的另一个维度。

理想是什么不是最重要，关键是看你有没有理想。可能是从小被中小学老师逼着写《我的理想》这类假惺惺的作文写恶心了吧，我一贯不喜欢「理想」这个词。我觉得更好的说法是「呼召」，这个问题想看的是你是不是一个有呼召感的人。

看过一篇论文，研究、分析不同人对工作的满意度。那篇文章说人可以分成三种，第一种是「打工型」，工作就是为了挣钱养家糊口，第二种是「事业型」，工作的目标是事业发展——不断在职场爬梯子升职，第三种是「呼召型」，总觉得自己有一种与生俱来的使命。

跟踪这三种人在职业生涯早期中期后期的满意度，发现：打工型的一开始就不满意，到后来还是不满意。而事业型的一开始很满意踌躇满志，但越到后来就越垂头丧气。最牛逼的是呼召型的，一开始就特满意，到后来不管成功与否，还是对工作充满激情满意得不得了。

呼召型的员工通常是最优秀的员工，就算现在这份工作、这个行业并不是他的最终「理想」，但这类员工的工作效果还是会超过那些一心想往上爬的事业型员工，更别说混日子打工型员工了。

像我上面说的，理想是什么不重要，有理想最重要。

就算马斯克的远大理想不是搞电子支付，他还是能在电子支付领域获得成功，就算罗永浩的远大理想不是教英语，他还是成了比别的一心想在新东方混的老师更杰出的英语老师。

好吧，写着写着我想起来了，我以前应该讲过这个面试题，那次我讲的好像是我自己当年去麦肯锡面试被问到这个问题时给的答案。

哦对了，这个面试题考察的第三个维度是看你这人是不是靠谱，有多强的推销自己的想法，说服别人的能力。比如你说我要是有无限的资源就去把小日本灭了，这倒是挺有理想的，可是听起来有点儿不靠谱，而且再往下讨论起执行层面的技术、可行性什么的很难以一种不笑场的方式聊下去。

我当初的答案今天就不重复了。

公平地自我剖析一下，我那个答案现在想起来还是挺靠谱的，但是，显然我没有说服那个面试我的麦肯锡纽约办公室合伙人，所以还是不够牛逼。

不过这不是我今天不讲这个答案的原因。

我不想重复那个答案的原因是，尽管你这个关于「有趣的愿望」的开放性问题让我想起了这个面试题，尽管我把那个答案粘贴复制过来就可以完美地回答这个问题，但是——

但是我想对你真诚一些。

现在是晚上五点半，我坐在上海的一个咖啡店里给你写这篇回答。对我来说玩儿微博问答就像是在跟朋友聊天，又不是面试又不找工作，我不愿意把一个人在面试官面前做出的那副积极向上、聪明机智、充满热情的嘴脸给你。

天正在慢慢变暗，我决定给你一个真诚的答案。

你问我对自己的「规划」，真实的答案是：我没规划。

我一贯很烦「自我定位」啊「人生规划」这样的词，每次听到只会让我焦虑和抑郁。坦白地说，我是一个没有理想的人，不管我在面试的时候会怎么装，装得怎么像，我不是一个有呼召感的人。哈哈虽然没理想，但干一行恨一行这条我还是做到了。

至于「还没有实现的愿望」，我的愿望好像都是实现不了的。

比如我想有朝一日买下一个有很多所房子的大院，把我从小到大所有的好朋友都请来住，做我的邻居。

最近几个月周围很多熟悉的东西好像在加速地消失，先是常去的寿喜烧店，然后是那个在我上海度过第一个中秋节的小酒吧，再然后是去了六年的东湖路上的大象餐厅。就在这星期，连我平时去买水的便利店也忽然关了。

比如我想让这些熟悉的、我爱的东西永远不会消失。

比如，我想让爸爸妈妈永远健康，永远活着，我可以永远地陪着他们。