---
title: 方丈在雪球关于贪婪的讨论
author: 方三文
date: '2022-03-13'
slug: '416'
categories:
  - Translation Articles
tags:
  - Investment
---


1. 虽然你说自己“不懂”，但你应该是依据常识，买了几个不错的公司。这种常识大概率是对的。这属于“看山是山”的阶段。这种阶段不容易亏钱。
如果你为了自己“懂”，去“研究”了很多公司，比如看看新闻，看看财报什么的，觉得自己“懂”了，却很可能亏钱。那是“看山不是山”的阶段。//@Wangzhe0220:回复@不明真相的群众:所以方丈建议我这种情况可以继续玩着这些资金么？因为之后等到机会自己肯定会把75%都投进去这几只股票，但自己其实根本就不懂，一般来说都赚不到自己认知外的钱，而且这样做感觉有悖于价值投资 为了满足自己的贪婪？感觉长时间来说对自己不好。所以想知道为什么说可以拿着，感谢方丈！


2. 这个棍子不应该打在“女人”头上吧。 人活在世界上，都有可能被人蹂躏，和性别无关。当然，最主要是被自己蹂躏，被自己的愚蠢、贪婪、无能和坏运气蹂躏。



3.  作为一名曾经的“传统媒体”从业人员，我觉得，将“发现准确事实（或者所谓的真相）”“发表公允观点”的特权授予特定的从业人员，虽然事实上曾经长期存在过，但其实效果是很差的，无论是他们（好吧，也许是我们）的能力、道德都不足以支持。
我甚至可以这样说，现在回头看自己写的很多报道，那与事实偏离得不是一点半点，但当时被读者当作“真相”来阅读；现在回头看自己写的很多评论分析，那观点也是偏颇幼稚得一塌糊涂，但当时的读者也认为是震聋发聩、直指人心。
想起这些我就觉得非常羞愧。//@allSBnow:回复@大苹果的飞飞:我同意富贵提出的问题的确存在，但不太同意产生这个问题的原因。
互联网社交媒体和自媒体本身相对于之前官方权威式和资格审查式的“主流”媒体相比，还是有很多优势和进步的，这里不细说，当然我们都希望能看到“专业的”“客观的”报道。
我觉得造成目前这些问题的原因不在于新型媒体，而在于互联网网民本身。
一，以前的媒体从业人员本身有个门槛，文化程度相对比较高，文字的表达，对社会的认知程度，逻辑分析，这些能力都比较强。所以相对而言，平均水准高。在新的环境下，这些人并没有减少，只会增多，只是更多的水平较低的人参与进来，整体水准被拉低很多。
二，也就是说，绝对意义上的优质信息变多了很多，但相对上的优质信息比例下降了很多，这造成一个结果，就是对“优质信息”识别能力变得很重要。对于整个社会来说，信息季度丰富而杂乱，信息交流空前增长。
从某些负面的人性角度来看，比如懒惰，贪婪，放纵，虚荣，恐惧，只会放大这些问题。所以说，如果互联网社交媒体是“恶”的话，那也是人的‘恶“。
三，记得二三十年就有过一种说法，在知识和信息爆炸的年代，文盲不再是不识字的人，而是不知道如何学习，如何分辨信息的人，当时我觉得这话有些做作，现在想想，我觉得我们已经进入这个阶段了。
四，很多媒体平台企业利用所谓的大数据，所谓的人工智能，在利用人性的恶来吸引用户，绑定用户，消费用户，换句话说，我认为这是一种短视。最终在未来获胜的媒体平台应该是这样的：他们教人们如何识别优质的信息，有用的信息，不仅仅让人们娱乐，更会引导人们更有效率地规划自己生活；他们拥有长线投资用户的思维，而不是短线的。


4. 大部分广受关注的事件，调查结论都是可靠的，但不一定符合公众的预期。
我做过一段时间的社会新闻工作，个人也是社会新闻爱好者，接触过不少情节离奇、后果恶劣的事情。
如果要将它们进行归纳总结的话，就是这些情节离奇、后果恶劣的事情，主要都是基于人的无知、贪婪、坏运气酿成的，很少是因为人的“坏”酿成的。
我自己也接触过不少人，其中有些人我很不喜欢，但你要让我指出谁谁谁是“坏人”，我真是一个都指不出来。

5. 学巴菲特有几难： 1，买股票就是买公司，需要对商业有很深刻的认知，非常难。 2，别人贪婪时我恐惧，别人恐惧时我贪婪，需要对市场波动有深刻的理解，非常难。 3，安全边际，需要承认自己SB，非常难。


6. 因为人自私、贪婪、无知、愚蠢，既无法根除动机上的恶，更无法避免结果上的恶。

>还可以加上健忘


7. 可以说，雪球里写满了这样的话，但是呢，没有什么卵用，抵不住大家的贪婪（想割韭菜）和愚蠢（想发横财）。

8. 我从来不关心别人炒什么。所以既不恐惧，也不贪婪。


9. 人类社会是被懒惰、贪婪与恐惧推动的。懒惰推动了技术进步，贪婪创造了商业系疑难，恐惧繁荣了文化宗教。//@打狗三十六式:回复@不明真相的群众:人类就是在不断的浪费中前行的，当年有了马车的时代，造一个速度低，还要加油的汽车的时候，那个时候也觉得浪费

10. 不好说，人性的贪婪与恐惧不会变，黑天鹅事件的概率不会变。


11. 市场总是会跌，就象会涨一样，跌没有什么问题。跌得快，还是跌得慢，很难说哪个好，如果一定要选择的话，我觉得跌得快更好一些。工具是中性的，工具背后是人心的贪婪与恐惧。无论有没有工具，贪婪与恐惧都在那里。所以，没有什么问题。


12. 这个世界上，骗局永不眠，因为它基于人性的贪婪与愚蠢，这永远不会变。


13. 自卑和贪婪嘛，惟恐别人忽略自己，惟恐别人不知道自己能干。//@obese:回复@不明真相的群众:为啥有些人会试图、甚至不自觉地想给建议、影响别人呢？

14. 这个就像去澳门场的人，想每把都押中，我也很想，可是我没有这个本事给你什么建议。//@niliuyuyue:回复@不明真相的群众:方丈，真心想得到一些建议。自我感觉还是太贪婪，太急于求成，又太想控制回撤和亏损。但总是当局者迷，控不住仓位，也就控制不住回撤。

15. 墙倒众人推，破鼓万人锤
自我介绍下，我来自温州，一个经商氛围浓厚、传统民间借贷成风的城市。在10年钱荒的时候，温州的担保公司、地下钱庄如雨后春笋，仿佛所有的温州人都开始做资金生意，逢人见面开口“吃了吗？”紧接着就是“我放了几十，几百万的贷款！”那是候月息2分是很便宜的，高的达到6分。后来的后来大家都知道了，民间借贷危机来了。
我分享的故事发生在昆明，同时期更精彩的故事应该是昆明泛亚有色金属交易所的旁氏骗局。由商会牵头，发起昆明某城中村改造项目，有意向的会员付了购房预付款。恰恰是这笔钱，在当时钱荒的环境下，牵头人没有经住诱惑，做起了担保公司的生意，由于资金链出现问题，放贷人变成了借款人，愈陷愈深，能抵能贷的都上了，包括自己的产业，住宅。借款利息不管几分，统统都要，只为了能喘口气。
故事的最后，牵头人被债权人堵在办公室一个月，不能回家，没有人身自由。恶意谩骂家常便饭，更有甚者，拳脚相加。在闹剧的高潮，债权人在追回投资无望的情况下，要把牵头人从窗户推下去！扬言“大不了一死！你先死！我再死”！
P2P感觉就像互联网版的温州民间借贷，烂在骨子里不是P2P，不是为P2P打广告的大V，而是参与这场贪婪游戏的人。
最后用和尚的警句结尾，世风日上 ，人心很古。

16. 任何市场的风险主要都是自己的愚蠢和贪婪：1、买错了。2、买贵了。


17. 老唐的人生观是积极进取的，认为人可以学习、进步；我的人生观是消极的，认为人的愚蠢、贪婪、冲动很难改变。

18. 管它涨跌，任它多空，我自持股不动，是这意思吧？//@宁静的冬日M:回复@刘姝威:刘老师说得好，令人佩服[很赞]
同时我也在想，也很多朋友是我这样的升斗小民，还达不到刘老师那样的素质，没法具有同样的大局观。
所以也可以狭隘一点，目光短浅一点，道义放两边利字摆中间来考虑问题。我们就纯粹从谋利的角度去想，怎样做才能利益最大化呢？
直观看做空好像是不错的选择。
但是，我提醒大家，有一个简单的常识是：股市长期看永远都是上涨的。任何一种“危机”导致的下跌，最终都会被证明是上涨中的波动，是买入机会。相反，任何一个在危机中做空的，都有可能空到永远不会再出现的历史低点。
如果不信，大家可以看看大萧条时期的道琼斯～不管做空的时机选择有多成功，哪怕选到300多点（或许只有07年上证的6000才有近似的完美）的最高点，而不是选择在多年后为了一些鸡毛蒜皮的小事，比如二战，朝鲜战争，总统被杀，911（没错，你没看错，跟1929年的大萧条比这些都是鸡毛蒜皮的小事，就更不要说什么贸易战，加息之类的事了）。。。去做空，现在也会发现，那是一个永远也不可能回得去的历史点位。
我们真的有必要冒这样的风险吗？我们有什么样的的神通，能预见下一步会是利空引起进一步下跌，而不是利空出尽？
还有一种相反的选择，借钱赌一把，杠杆做多，别人恐惧我贪婪。。。
我提醒大家第二条常识：股市的涨跌都是人的行为决定的。牛顿有句话说得好：“我算得出天体运行的轨迹，却算不出人心的疯狂。”没人能规定一个贸易战只会跌多少，跌多久。杠杆的问题是，一旦使用不当，有可能发现，自己买入的时机最终确实变成了遥不可及的历史低点，但在此之前，自己却已经爆了仓。
如果不脱离以上两条常识，我们小老百姓该做什么，完全可以按自己的性格，财务状况，自由决定。努力工作，快乐生活，幸福投资。多年后蓦然回首，我们自然会发现，股票始终是长期回报最高的大类资产。



19. 拿住，不许动，你就会发财//@dslkhy:回复@不明真相的群众:你好方总，雪球的忠实粉丝，本人投资基金已有几年，就是克服不了自己的贪婪和恐惧，现持有九只基金，算是三个组合。第一个组合互转，易方达沪深300增强30%，易方达安心债券15%，易方达稳健15%，第二不动的，天惠，国泰估值，华泰先行20%，第三灵活组合工银深证红利，工银可转债，工银沪深300 20%，最近大盘跌的有点扛不住，不知我的组合策略有什么缺点请指点迷津，资金是三年或五年不动的钱。


20. 你以为你是在跟“空头”、“喷子”、“股黑”战斗，实际上你在跟自己的愚蠢、贪婪、恐惧战斗


21. 这就是我前几天说的，贪婪时自贪婪，不管他人是否恐惧；恐惧时自恐惧，不管他人是否贪婪。//@非完全进化体:回复@老鱼儿CD:因为股价上涨乐观是错的，因为股价上涨悲观也是错的。

22.  巴菲特的话不能全当真的，我觉得真正牛逼的是：我贪婪时自贪婪，不管别人是否恐惧；我恐惧时自恐惧，不管别人是否贪婪。//@王夕刚:回复@不明真相的群众:可，别人好像在贪婪啊。

23. 投资挑战的根本不是人性好吗，所谓贪婪与恐惧，更多是由于认知不够深，知识不够广博造成的。人们常说巴菲特敢于在别人贪婪时恐惧，别人恐惧时贪婪，但更多的时候，老巴是在敢于在别人贪婪的时候更贪婪，恐惧的时候更恐惧。哈哈。

24. 如果社会财富的生产是基于可继承的资产，比如土地、黄金，那么底层很难有翻身的机会；如果是基于无法继承的智力、精力，则社会阶层流动会更加通畅。//@Mr_Elie:回复@宁静的冬日M:信用本位是个比黄金本位更好的制度安排，不能因为说目前的货币制度有瑕疵就退回到金本位吧，这跟说现在人心浮躁，贫富差距过大一心要回到文革之前的脑残是异曲同工啊[笑]对黄金的痴迷几乎可以说是人性中的懒惰和贪婪，你希望赚到一屋子金砖就能子子孙孙永世吃喝享乐去了，实际上金本位下的社会就是这样，财富的传承无损耗，后代也无动力去创造价值。今天信用本位下的货币逼迫资本时时刻刻都要流动起来创造价值，否则就要被侵蚀。实际上虽然没人挑明，但我认为纸币贬值恰恰是维系社会平衡的需要，但不能贬过头了，需要维系一个微妙的平衡。虽然与直觉矛盾，但其实对大多数人来说，适度通胀是绝对好过通缩的，这也是黄金和比特币之类的臆想创造一个永不贬值的货币永远无法成功的根本原因。


25. 挣小钱靠寻找交易系统的bug，挣大钱靠创造价值

26. 非常同意这个看法。理解生意的人，才能在别人贪婪时恐惧，在别人恐惧时贪婪//@Michael8808001:回复@Michael8808001:嗯，借管兄之帖与各位投资伙伴分享个人的一个肤浅总结:

1.企业成长不易，成长性是个很罕见的东西。我过去十年三四百家客户中，成长为上市公司的是四家，比例为百分之一。我很惊讶的发现，我绝大多数客户企业(98%以上)十年中规模沒有任何变化。原来三百人的厂十年后还是三百人。

2.企业倒闭不易，倒闭也是个很罕见的东西。我过去十年三四百家客户中，真正倒闭的企业比例为百分之一到二，三四家而己。

嗯，以上统计样本为民营制造业，三百人以上企业。

股市的看法却是相反的。在企业成长时，股市总是显得过于乐观，但我也不知为什么，总有些因素会让企业停止成长，成长股说翻脸就翻脸。一定意义上，成长是小概率事件。

另一方面，在企业陷入困境时，股市又往往过于绝望。其实企业破产倒闭是个很小概率的事。作为投资者对反转股投资，只要不孤注一掷式押宝，控制好单一标的与单一行业上限，反转股投资实质上是很安全的。

27. 在别人恐惧的时候贪婪，也是优秀企业的特征


28. 大家感觉跟人性的弱点（贪婪、恐惧）作斗争很难，但背后的答案，是不是并不能完全从人性角度找，而是：对自己的判断不确信（对投资标的研究不够，没有估值能力），没有安全边际。


29. 太阳底下无新事，仍是贪婪与恐惧的一年。


