---
title: 没有门槛的事情，不如不做
author: 李嗲Lydia
date: '2021-03-31'
slug: '195'
categories:
  - Translation Articles
tags:
  - Personal
  - Nonlinear system
  - Insights
---


[Source](https://zhuanlan.zhihu.com/p/22855528)


>我不同意这个标题，因为很难定义什么是有门槛的事情，投资的门槛就很低，直播带货的门槛也很低，但同样有人做得很牛逼。不要跟风、投资有扩展性、自我强化能力和有比较优势事情更重要。

总是有人爱问我人生三大终极问题：我为什么这么穷？他为什么那么有钱/牛逼？我如何像他一样有钱/牛逼？也许是喝了不少鸡汤，能问出这种话的人多半很勤奋：加班，健身，刷公开课，三十好几了准备重拾英语，总之整天也没少努力，却总也不见忙出个什么名堂，望望房价，长吁短叹。

当然，有时间有兴趣的情况下，做一些自己喜欢的事情边充电边消遣是非常值得赞扬的。但是假如你很缺钱，很想尽早摆脱现有的生活状态，早日财务自由，这种伪勤劳多半没用。因为你所做的努力，都没有门槛。别人随时可以超越你，如果他愿意。那么你的价值在哪里呢?

社会财富的积累分为资源型收入和劳动型收入。你的工资，你的兼职（考瑜伽证，健身证，摄影，会计代账），都属于劳动型收入，包括你做点代购或者分销直销，在初期都属于劳动型收入，而这现在看起来还不错，你努力和勤劳一点就能够做到并且过得很富足。但是这离能给人安全感的财务自由还有着相当遥远的距离。一旦你因为健康问题，生活环境变迁，生儿育女等琐事缠身，你就会失去这部分收入来源，一夜回到解放前，赚钱如吃屎，花钱如拉稀，永远跟个耕地的老黄牛一样停不下来。

而当你努力的方向门槛越高，你钻研得越深，你越容易获得长久的竞争力和信息差。在一个平台的红利期钻研游戏规则，积累在特定领域内top 3的影响力是一个；玩游戏打个国际比赛拿个奖回来是一个；积累客户资源左右逢源，拥有圈内的口碑和人脉也是一个；这些当你一旦积累好了之后，那长尾效应带来的丰厚利润足以令你高枕无忧。所以当你在努力之前，你是不是可以想的更清楚些，你努力了之后的成果究竟能给你带来的是短期效益还是长远效益呢？好的起点，会让你不会南辕北辙累死在自己挖的坑里。

你爱考证当然很上进，但是你若是想靠考证获得另一个行业的基础职位来获得财务状况的改善，那就是痴人说梦了。任何行业，任何岗位，拿大头的永远是上游，这是古往今来的游戏规则，你不承认就是不客观。而当你在现有岗位上做到顶尖之后，赢家通吃的模式就会向你开启了。多少跑调的演员，演而优则唱，拿着你辛辛苦苦吊嗓子都争取不来的曲子炒成口水歌，你有什么办法？

你看别的女生晒晒照片整整容就能获得赞美无数，于是你也开始学，可是永远有比你更年轻更漂亮的小妖精干掉你；你看别人已经走了十个国家五十个地区羡慕嫉妒恨，于是也开始规划起gap year准备直接就去北极圈，制霸朋友圈的逼格之王；你看二姨家的闺女微商做的风生水起于是你也跟着尝试，先屯了五万块的货堆满了床底。啊，你到底要吃人家的屁到什么时候，那些真正的有钱人都在忙着钻研下一个红利期在哪里，懒得现身对付你。凡是用钱，用人力就能解决的事业，都是沙滩上的碉堡，一吹就倒。

更不要说随着科技的大幅发展，劳动力的生存空间被进一步压缩，你为什么不努努力，先多花一点心思提高自己的终身战斗力，做别人可能要花大量时间和精力才能做到的事情。而最后多半，只会让他们乖乖花大价钱雇佣了你。

同样的时间，要学就学最难的，要爬就爬最险的峰，要去就去最远的地方，你只有超过别人一大截，别人才会注意到你的存在。你还年轻，脑袋空空，即使表面上也能逛逛卢浮宫，装模作样地听听维也纳的歌剧，可是这和你功成名就后，被当做贵宾接待观赏的体验是绝对不一样的。而这，才是你最初奋斗努力的意义。

战胜他们，并远远甩开，找到你的那条羊肠小路吧。具体是什么，不要问我，问你自己,找属于你个人的“稀缺资源”。在有限的时间精力里，记住判断的准则：没有门槛的事情，坚决不做。