---
title: 中国概念股钱多成灾
author: 方三文
date: '2022-01-30'
slug: '382'
categories:
  - Translation Articles
tags:
  - Investment
---

[Source](https://xueqiu.com/1955602780/20105874?utm_source=pocket_mylist)

买入一只净现金高于市值的公司，捡到了大便宜？很遗憾，你可能只是买到了一个长着现金肿瘤的怪胎。

 

价值投资者特别重视投资的安全边际，对公司负债率有一种本能的厌恶。如果股价能够低于净资产，他会觉得可能捡到了便宜货。如果股价居然能低于每股净现金，会觉得更是碰上了千载难逢的买入机会。

那么，投资是不是就在行情系统里面，把净资产和净现金占比最高的公司找出来呢？



是的，公司有一些现金，有较高的净资产，给了我们一定的安全区间，但我们不要忘了投资的本义。

为什么投资呢？是因为我们自己有点现金不知道怎么让它增值，我们相信有比我们更懂得使用这些现金的人，就是我们投资的公司的管理层和员工。那么，能否把现金用好才是衡量公司能力的标准，而不是现金的多少。

通常，公司有几个办法使用好现金：

投资于核心业务上，改善现有的产品和服务，提升公司的竞争力和市场份额。这应该是公司融资的最主要诉求，也是投资者把钱投给公司的最主要理由。

如果主营业务上用不完，有很多公司将现金用于并购相关业务，以期增强公司的业务竞争力，甚至实现公司的转型。盛大控股减持在盛大游戏的股份，将现金用于拓展文学、影视等业务，应该就是这个诉求（相关文章：资本市场对盛大战略的估值：零）。并购会碰上一个并购质量的问题，买了跟业务不相关或者质量差的资产，有可能钱就打了水漂。并购后还有一个业务整合的问题，并购公司通常都有“整合”梦想，希望并购来的业务能够与现有业务产生协同效应。可是“整合”听起来美妙，结果却往往是灾难的开始。这两方面要学习谷歌（GOOG，603.26，-0.18%），谷歌说得上是互联网公司里的并购大王，其并购有两个特点：一是并购都有专业的团队论证并购的合理性和价值，遵重专业性（相关文章：看谷歌如何利用它的260亿现金）；第二是并购来的公司都不急于做管理上的“整合”，基本还是保持独立公司的管理模式，只是在渠道和文化上有所谓“整合”。这样就能保证被并购的公司依然保持其活力。

如果并购还用不完，现金还能用来干什么呢？通常可以用来分红。分红稳定的公司，也有一群追捧者，比如养老社保基金。

但分红有个问题是需要纳税，另外，投资股票本来就是钱有多，分了红钱用来干什么呢，还不是得用来买更多的股票？所以有一些投资者认为，回购股票是比分红更好的回馈股东的办法。但是回购股票也有一个问题，就是不能象分红一样成为一个持续的策略，没有办法形成投资者稳定的预期。

如果不分红，又不回购，那现金还可以用来干什呢？只好存在银行里或者买美国国债了。但是回到我们说的投资本义上来，如果钱是上市公司的CFO拿去存银行，我为什么不自己去存而要买你的股票让你去存呢？

遗憾的是，现在中国在美上市公互联网公司，普遍都是最后的处理办法：把巨额的现金放在银行里吃利息，或者买一些短期理财产品。同时，每个季度的正向现金流，还在源源不断地增加净现金总额。有好几家公司，如果这个状况持续下去，净现金总额超过市值，都是指年可待的事情。更加荒唐的是，有时候巨额现金不但没有给股东创造价值，反而因为处理不当造成巨额损失，比如购买不靠谱的理财产品。这时候，这巨额的现金，功能就接近于人体上的肿瘤了：消耗养料却不创造价值。

钱多当然是好事，但利用效率如此之低就是个问题。看来这些公司的CEO和CFO们，得想出一个更好的办法来用好这批现金，以回报投资者


