---
title: 优点科技刘江峰：创业公司要能自我造血 打工更舒适
author: 凤凰网科技
date: '2021-03-30'
slug: '190'
categories:
  - Translation Articles
tags:
  - Investment
  - Economics
  - Insights
---

[Source](https://tech.ifeng.com/c/7pBEYt3Vz0q)

2019.08.16

> 我一直很关注这个人，搞得几次创业都很不靠谱，太技术乐观主义，另外一个不看好的对象是舒为的造作，十年以后再来验证我的眼光吧。另外，我在[潮水退去与进步主义](https://guanghuamao.netlify.app/2021/01/02/1/)中提到了过去几个月对中概股的追捧完全符合泡沫产生的条件，那篇文章写于2021年1月9号，而3月份股市的表现印证了我的说法，大热的中概股都在大跌。新技术的出现总是会引发各种泡沫，人们对技术、制度、文化和基因、自然条件这四个因素对人类社会的影响一直欠缺思考。其它三种因素都在不同程度上强化或者弱化技术的影响。这篇文章写完之后再写一个预测帖吧。

科技峰会在北京举行。优点科技刘江峰出席峰会并接受了凤凰网科技的采访，谈到了对目前投资环境的判断，创业投资中的心得，也讲了5G对他所处的安防行业的影响。

作为有多年从业经验的创投人士，刘江峰指出宏观环境的变化，从非理性的“追风口”、“追概念”到回归理性，也让创业公司面临“生死危局”。作为投资人，他表示现在看项目，主要是看它的自我造血能力、现金流和盈利状况。他笑言：“打工比创业要稳妥、舒适很多。”

作为创业者，他主要聚焦于家居安防和社区的工作。他表示对智能家居行业来说，5G带来的机会最主要是低时延。过去一些安防的造价很高，5G带来的低时延可能改善这一状况，提高用户体验。

以下为采访全文：

凤凰网科技：当前宏观形势严峻，很多基金和创业公司都在感叹钱荒，作为经验丰富的企业管理者和创业者，您对当下的环境有什么样的感想？大环境不好的时候，该如何谈机遇？

刘江峰：过去整个创业和投融资环境也好，很多非理性的因素在里面。大家追风口、追概念，我觉得这种情况是正常的状态，可能对很多企业来说，尤其对年轻人来说，相对挑战大一些。

凤凰网科技：您同时具有投资人的身份，在现在环境下投资方面的策略是否发生了调整和改变呢？

刘江峰：个人做投资人的感受，就像天使基本等同于做慈善，当然也和一些投资机构做项目评估，总体上会更谨慎。因为现在经济环境也在变化，包括消费力也在下降，包括我朋友的公司做各种品类，从3C到传统的，都看出压力很大。对品牌、新公司而言更难了，特别是头部的品牌对它来讲是减员增效问题，不牵扯到生死问题。对于创业公司而言，这时候生存压力很大。我们看项目的时候，也是看它的自我造血能力、现金流和盈利状况。现在概念起的作用会下滑很多。

凤凰网科技：分享一下您最看重创业公司哪一个特质或者是哪一个特性？

刘江峰：大部分投资人首先看的是团队，因为事情都是人做的，以及要看团队本身在所做的这块业务上团队的经验，和对创业公司的理解。我个人做创业者也是一样的，但跟大公司和小公司创业的区别蛮大的。像我们打牌一样，大公司里面牌很多，大王、小王都很多。你现在手里都是3、4、5，而且过去的资源肯定也不够用，你在做这些业务的时候跟别人合作关系不一样，在大平台上跟创业公司是不一样的，这里面面临着各种的挑战，我觉得最核心是在小公司，首先要面临生存的问题，公司在生存和发展上怎么样做平衡，很多猛打猛冲最后就失败了，我们自己也有教训，也有一些体验。我们在看别的公司时，也会看Leader的个人风格，很多中国人对创业过于美化，我建议打工比创业要稳妥、舒适很多。

凤凰网科技：今天的话题是5G时代，IoT和5G时代成为热门，大家都在做平台和生态，作为比较独立的厂商，优点科技是如何体现自己的特点？

刘江峰：优点科技本身专注于IoT，我们还有几家兄弟公司，是我们在控股，在做家居的产品，主要聚焦于家居安防和社区的工作。现在对智能家居行业来说，5G带来的机会最主要是低时延。因为过去的很多IoT产品工程造价很高，5G带来的低时延可以很好的把这些问题解决掉，用户体验也会更好。但5G也面临覆盖问题和最终成本问题，现在5G设备还是蛮贵的。我们重点布局在音视频，我们做安防和传感器，水电煤和智能门锁，包括家庭的监控，各种门铃猫眼主要通过声音、视觉，不管是可见光还是热传感技术，这些技术对于5G本身大带宽用途不大，实时性也不像通信那么强。刚才说在低时延上运作，现在我们用音视频技术的时候，这些东西最终靠音频和视频觉察到出现的异常，或者有人摔倒、家里入侵，包括一些异常情况的发生，会及时识别和进行信息的传递。当然会叠加后端的一些服务，跟物业公司的合作，跟公安派出所的合作等。5G在媒体和其他方面应用会更多。我们希望整个5G模块成本尽快普及，想办法把成本做低。我们跟业界很多做5G的厂家合作，从高通开始，听说国内其他的厂商也会开放一些口子，为合作提供了很大机会，我们将更多在软件和服务这块去连接和集成。

凤凰网科技：您刚才也谈了5G方面的产品和服务，您觉得最终的民用商业化和落地有个什么样时间表？

刘江峰：我觉得今年就会。

凤凰网科技：这些产品真正让老百姓用上是什么时候？

刘江峰：它中间有折中的过程，我觉得5G的CPE在明年起来以后，在明年下半年就会开始有产品落地。

凤凰网科技：可以利用5G技术。

刘江峰：对，现在家里装一些智能开关，智能开关要么是布线的，那个工程很大。包括家里装音响，我家里装了800米的布线，工程量很大，还费钱，用起来也不方便。其实5G来了之后，这些完全可以无线布置，家里的智能开关、室内的音箱，走Wifi不靠谱，因为Wifi、蓝牙干扰特别多。像家里的智能开关摁一下时延可能2秒灯不关，再摁一下把它关了，再摁一下又开了，很多人体验不好，搞两下就不愿意用了。这方面好的体验，我觉得明年下半年会出来，不会说每个开关里会装5G模块，那个太贵，而是通过5G的CPE这些来做。我们做了一款3D结构光人脸识别的锁，当你走向门口，我们是打15000-18000个点进行3D活体识别，现在用Wifi去传递。但Wifi的干扰多、稳定性不好，因为家里的路由器不一定一直连着，路由器一两百块钱不靠谱，经常会断掉。如果用5G模块，整个QS会有很大的保障。

我们看智能家居行业，因为各种各样技术的限制，导致体验不好，没有很强烈的购买愿望。现在卖净水器、台灯、锁，但没有形成整体的家居环境的智能服务条件。如果5G到来，这方面肯定有机会，也取决于5G的模组厂商和芯片厂商，对于他们来讲主要设备还是手机、通讯网络，刚才我看爱立信总裁在那儿讲。他们自己在芯片环节投入也很大，但还是取决于将来谁开放的更多、更快，因为人跟人的通信是用不了的，更多是2B的移动医疗，人跟物与服务的结合。

