---
title: 家庭应该常备哪些药物
author: 余向东
date: '2021-08-20'
slug: '266'
categories:
  - Translation Articles
tags:
  - Insights
---

[Source](https://mp.weixin.qq.com/s/WFpf9gnTjeii3RZoW8Eq9Q)

看过很多家庭常备药物清单，中西药，成人儿童用药，慢性病药物，常见病药物，一应俱全，无下数十种，简直可以开一个小药房了。

老实说，这些推荐都是不负责任的。

我们家以前也备用了一些药物，比如抗生素啊，感冒药啊，创可贴啊，止泻药啊等等。但近十年左右，基本不再备用药物。

我家不常备药物，不是因为我可以随时方便得到药物，而确实是因为我对备用药物有了更科学理性的认识。

我的认识之一，是在做JCI的过程中初步了解到，药物储存是一种极其专业的事儿，对环境的洁净度、温湿度、空气、光线等均有非常严格的要求；对高危药品和易混淆药品的标示，以及药品的效期等，也有要求。普通人根本不可能懂这些，你家里备用了一大堆药，让专业人士来检查一下，可能多数已经失效了，甚至污染了，吃了不但不能治病，还很可能危害健康。

认识之二是，一般人不具备正确用药的基本常识，乱用药，无适应症用药，反而不如不用药。

家里备用抗生素，常常用于普通感冒、腹泻、外伤等等情况，但这些其实是不需要用抗生素的，用了反而有害。真正需要在家口服抗生素的疾病，普通人无法判断，比如，儿童轻度肺炎、成人普通尿感等。你判断不了，需要去医院就诊，敢自己在家里用吗？可以说，对绝大多数家庭，完全不需要备用抗生素，就像你家里不需要备用一把枪一样。

很多家庭备用有止咳化痰药，其实也弊大于利。最重要的是学习靠谱的医学科普，真正理解止咳化痰药的证据。对于儿童，国际上基本不建议使用止咳化痰药。对于成年人，如果咳嗽不影响工作生活，也不主张止咳。而更重要的是，对于不明原因的咳嗽，一定要首先把咳嗽的原因搞清楚，而不是稀里糊涂地自己乱吃止咳药。化痰药的效果一直存在争议，缺乏确凿的证据，不吃也罢。

感冒药更是必备。但是，如果你不是医生，我劝你不要备。因为儿童感冒药国际上公认是弊大于利的。成人感冒休息喝水不香吗，你非要吃药？当然，有些情况是可以吃点药的，这需要医生的指导，非专业人士你不懂的，你备药自己吃药除了增加药物不良反应的风险外，获益非常有限。

还有的家庭喜欢备点正气水儿，白药等等神药，我也建议不要备。防中暑靠那水儿不顶用，还是空调电扇冷饮靠得住，道理你自己细想吧。跌打损伤什么的，赶紧去医院，拍片看有没有骨折，皮肉伤清创缝合消毒才是王道，有破口的话，可以根据情况用一两天的抗生素；白药不顶用，信不信由你。

清火的啊、消食儿的啊、解毒儿的啊...别乱用，否则几年后你可能要靠透析过日子，也可能得肝癌。信不信由你。

那么，家里就一点药儿也不用备吗？

还是备点儿吧，毕竟一点儿也不备，你心里一定放不下。

我建议，可以备以下药物：

一、家里有人确诊有某种慢性病，如高血压、糖尿病、血脂异常、痛风、哮喘、帕金森病...相应的药物你得备一点，也不要多，备一最多两瓶（盒）就可以了。就像菜一样，又不是买不到，吃完了买新鲜的不香吗？非要备十几盒？需要说明的是，我建议你备的，是正规的，上了国内外循证指南的药物，而不是什么救心丸儿啊，滴丸儿啊之类，你懂的。

二、家里没有病人，仅仅是备不时之需，可备之药很少：解热镇痛药（布洛芬，或对乙酰氨基酚）一盒足矣、口服补液盐（一般腹泻时可以在家服用，观察一到两天，不行去医院）、消毒剂（酒精、碘伏等）一瓶、绷带两三卷，我觉得就这么多了。如果很长时间没用，记得更换，别当它们是黄金。

药物从来都是双刃剑，只有专业医生才有权衡利弊合理使用的能力；普通人把药物一律看作毒药更好，更能免于受到伤害，免于耽误病情，收获真正的治疗之利。

总之，家里需要备用的药很少，不备也没事儿。脑子里备一点靠谱的医学知识才是王道。