---
title: 学经济家微博言论合集
author: 学经济家
date: '2021-07-16'
slug: '252'
categories:
  - Translation Articles
tags:
  - Common Law
  - Economics
  - Insights
  - Investment
---

1. @学经济家：英国人：炮舰射程以外的只会是野蛮人乃至食人族  vs 美国人：We are all created equal，我是文明人那自然你也是。//@whigzhou:同时，这本书也可帮我们看清英式帝国主义和美式帝国主义的区别，以及这一区别带来的后果。

2. 不用关心啊，普天之下差序格局以吏为师，听话就行了，不听的被弄死也是活该[挖鼻]//@王怜花:“西方人两千多年探讨的两个核心问题，即权力的归属问题和权力的界限问题，亦即由人民来控制权力与为权力划定适当的范围和界限的问题，我们从没关心过。这使我们建设现代政治文明缺少传统的支撑。”

3. 09年时总结过：稀缺时代投产能赚钱；产能充足时会做品牌的赚钱；品牌多了渠道（国美，央视）分肉；都做渠道时地主分肉。在雪球发过，这次捎带着重复并自我吹嘘一下，嘿嘿。 //@卢山林:问题越解释越清晰了。

4. 哈哈哈，每天西方水深火热，这边风景独好；成绩一日千里，处处弯道超车；对外最大克制，反击义正辞严；领导深谋远虑，群众喜迎涨价……挑选+裁剪+重复的套路，从爷爷辈起就耍的纯熟了，闭着眼都能干[笑cry]//@王怜花:转发微博

5. 纽屎。老友段皇爷曰：美帝媒体界整体而言是发达国家里最烂的，也是美帝诸多行业里最烂的，没有之一；偏偏是许多中国媒体人眼里的圣殿，一步不紧跟就惶惶然；[摊手]//@刘海影:扭腰时报真的可以

6. 养那么多官呢，强调那么多年忠孝呢……官场如剧场，个个都是戏精

7. 员工不要以为老板对你有什么感情，老板跟你称兄道弟只是想让你帮他赚钱，并不会给你的父母养老送终。 ​​​

8. 后来阻挡默克的HPV疫苗10年//@雷尼尔雪山2020:有人感恩默克制药了么？只字未提。“最后，时任默克公司总裁的罗伊·瓦杰洛斯，在了解到中国每年有2000多万新生儿迫切需要接种乙肝疫苗的实情后，做出了一个惊人的决定：放弃每年至少20亿的生意，以700万美元的超低价将技术转让给中国。”

9. 即便是成千上万人间接因过度监管而死去，大多数人（尤其是媒体为了填版而快速炮制的内容）仍然会简短来一句：管的不够，管的不够多，管的不够好（让我来啊）。至于背后的，太长不看…

10. “掀桌-坐庄-指定-服从”模式的千年传统，想另学也很难//@王怜花:“中国近两千年来的情况并不是依靠暴力精英之间达成协议，而是个别暴力者摧毁了其他暴力者，建立政府，然后在精英之间乃至社会上扩大分工以提高生产效率。西方的政治是合伙制的，中国则不是，这就导致制度随时可逆。”

11. 所以不要相信公权力嘴里的天花乱坠，自始至终你自己才是自己的上帝。//@游戏和语言://@西峯://@学经济家://@王怜花:“政治“可能”让一个国家成为地狱，但是，它却“不可能”让它变成天堂。换句话说，政治所能抵达的上限不会那么高，但是，它所能抵达的下限却可以非常的低。

12. 《美国独行》的作者其实文笔风趣，经常看着[允悲]，摘几段：

盎格鲁圈两百年来的优势正在走向终结，同样走向终结的还有现代世界，对于现代世界的秩序和繁荣，很多人认为它体现了一种普遍的、广泛的趋势，事实上，它衍生于一种非常独特的文化传统，而且离开这种传统，它很难存续。指明现代世界有多么“英国化”，显然有违英伦风范。真正的英国人不屑于做这种可憎、粗俗之事。所以，你们需要一些殖民地的粗人代劳，比如我。但是，温文尔雅的谦逊和蔑视自己的遗产，毕竟是两码事。

……

正如外国人常做的那样，他援引了温斯顿·丘吉尔的话，天真地以为这会赢得当地人的好感。然而，很显然，对英国几乎所有的统治精英来说，引用丘吉尔的话只能证明你是一个极端的疯子。几年之前，我有幸在白宫拜访过布什总统，并在总统办公室见到了丘吉尔的半身像。奥巴马入主白宫后，下令撤走半身像，并归还给英国。目前它下落不明。不过，考虑到温斯顿爵士论述苏丹运动的书中对伊 教的不恭之辞，半身像很可能在希思罗机场被捕，并被驱逐出境，因为它对公共秩序构成了威胁。

……

更可悲的是，我们还得必须指出这些“反法西斯团体”无数恶行中最愚蠢之所在，他们竟然认为“大英帝国与奴隶制存在密切关联”。实际上，大英帝国与奴隶制的主要联系是，它废除了奴隶制。在威廉·威尔伯福斯、英国议会和英勇的皇家海军讨论这个议题之前，奴隶制被世界各国的文化视为人类生活的一大特征，和天地一样永恒。大不列颠将世界大部分地区的奴隶制铲除殆尽。


13. 民国同期法德意西波等民主也是玩砸的。不分层的一人一票本是怪胎。创始期美国是政府极小不牵扯多少利益，选民又是天然筛选过的--花几年收入或自由换张几分之一死亡率的船票的，都不是寄生者。后来推动普选的法德主要用意是征兵。一战后普选政治正确了，二战后再质疑者才被视为疯子反人类

14. 大企业只敢反GOP（不会挨收拾，就像某国人只敢反美）。钱该跑跑。//@水獭otter:商人无节操。按理说反对川普，川普下台了，应该留下来一起建设社会主义，怎么就跑了。[允悲]//@敬恒1969: 巴菲特反对蠢普，知道其不得人心，早晚下台！//@水獭otter: 民主党要加税，所有的资金都在往外跑，主要是亚洲。

15. 从乌克兰大饥荒起，美国媒体届在某些领域的信誉值就平均为负了。一个经常把社会注义社会症义挂在嘴边的群体，谁信谁去夹边沟。

16. 但却是某国媒体人眼中的山巅（而非粪坑）//@PragerU字幕组:如群友所言：美国媒体的专业水准，职业道德是发达国家最垃圾的，不是现在是这样，过去一百多年都是；却又是发达国家媒体业中最自大最傲慢最装逼最有优越感的，也是意识形态色彩最浓，公知味儿最重的，一代逼王媒体的典型就是扭腰时报了。

17. 东亚老传统了，小黄人不算人，是战争机器or经济机器or官僚机器的燃料…“君上之于民也，有难则用其死，安平则尽其力”…

18. 如图，1960-2014年全球范围内，企业被没收（或锅有化）事件发生的数量。

 该图来自经济史学家Gaillard2020年的新书《Country Risk：The Bane of Foreign Investors》（国家风险：外国投资人的灾祸）

Gaillard指出，“国家风险”（Country Risk）对外国投资人产生影响(或可能影响)的任何宏/微观经济、金融、社会、正治、制度、司法、气候、技术或卫生风险。风险造成的损害包括：财务损失；对投资公司的雇员、客户或消费者的安全构成威胁；声誉受损，或失去市场或供应来源”(Gaillard 2020)。20世纪70年代中期，“国家风险”的概念被逐渐引入到经济文献和媒体中。（关于这个Country的含义，可参考辉总的定义：http://t.cn/A6GatxKR）

该图表明，1980-1990年代外国人投资企业被没收的发生数量发生了显著的下降，如何解释这一现象呢？作者解释认为，1980年代的债务危机迫使大多数发展中国家和新兴国家转而采取了有利于市场经济的政策（比如产权保障、SOE私有化、贸易金融自油化）——这些政策后来被概括为 “华盛顿共识”。

那为啥2005-2014年这种没收行为又有所抬头呢？这是因为超过50%的没收行为集中在三个国家——玻利维亚、厄瓜多尔、委内瑞拉。


19. 太多的部委+公务员（争着对企业家行使爹权），太多的国企特别是银行（争着圈占资源），过苛的劳动法和土地法（放纵对企业家的敲诈），地方债拉基建+房贷拉住宅的管道又不通（有钱无处投转而囤金+缺钱啥都建不了），咋起飞…

20. @久坂萩：经营下的缅甸是东南亚最富裕地方之一，自耕农出口的大笔粮食和工矿初中级产品销往各洲。后来缅甸成为世界最穷国之一。今天大把傻子恶狠狠说“不喜欢社会主义就去缅甸啊”，请问为什么要去这个反资本反到黑、社会主义历史比中国还长的地方？应该说“反资本是吧，反资本滚去缅甸！”

21. 没有两档制+旋转门的话，前任的各种瞎猫乱抓，后任都得奉为铁律，必须吹捧不能批评。你说前任的政策是可议的，那前任的提拔也就是可议的了，那就会动现任官员的根基。而官本位社会里动人官位≈杀人父母+扒人八代冒青烟的祖坟。再打大的道理，比不过组织行为学逻辑。

22. 美国人反帝情结太深了，以反帝立国，以反帝为天命，反英帝反苏帝反美帝都很容易high起来。//@久坂萩:美国绝不是万能的，不可能解决所有的国际问题。但是有很多问题还确实就是孤立，退缩和思想混乱（认定“左”‘第三世界’默认正义，美国不正义）带来的。

23. 恢复乡绅制度就是与党争权。乡绅制度和宗族社会其实是清末中央专制帝国逐渐瓦解，权力由外来流官转到本地精英的产物，有乡绅必然地方自治，地方一旦自治，中央必然衰弱。所以，要多树吴仁宝、王宏斌这种新乡贤典型，防范孙大午这种野心家，宁可遍地张献忠，不能有一个曾国藩。

24. 把美国人骗过去了（更主要是当时美国驻华使馆新闻处、国务院遍布左翼人士比如费正清乃至苏碟…麦卡锡后很多又躲进学术界…帮着涂抹了几十年，直到苏联解体俄文档案放出来…

25. 印象里04年前后，广东省预算公开，有人发现仅一个机关幼儿园每年就拨款2000多万，比当时所有粤北山区失学儿童募到的希望工程捐款多的多、多的多。后来有错就改，预算公布时更多障眼法，也不准媒体“私自解读”了。（大概那时我在论坛里曰：财政史就是政治史，而政治史则是谎言史）

26. 传统社会想转型开放准入社会，很难，死很多人也不行（变换大王旗，新租代旧租）。早年靠大英帝国一枪一炮的打，日本大清或北美土著并没有邀请。威尔逊之后不能打了，靠被打-反击-占领。其余的万古长如夜，这才是正常的。

27. 没错，70多亿人里只有2%是秩序维护者。假如没了，即使德法日等的宪政秩序和公民自由也难撑2代人。没转型的就不用说了，很快让你知道，现代文明只是历史进程中的一次偶然，得之不可思议，维护耗尽血力，终了永不重来。//@张平特拉维夫:转发微博

28. 这个世界只有一小撮人是真正的支持自由和反对干预生活的政府，而且也只有他们有方法和力量在这个世界普及自由。

当这一小撮人也对自由产生怀疑时，现代文明的大厦的根基便开始晃动。

就像，放弃自由贸易的胡佛关税法案，直接引爆了经济危机。日本破产，德国崩溃，最后走上军国主义。

所谓的艺术家，科学家，离开了自由的支持，他们的艺术和科技就像泡沫一样，一吹即散。

美国的自由派知识分子看不起红脖子们，可要不是红脖子们对政府的抵抗，对自由的支持，自由派们早就被自己的同志们送到古拉格了。 

说到底，自由派知识分子们不过是保守派们建立的自由秩序的消费者，是一帮搭别人的便车却又想拆掉这辆车的狂人

29. 建议：先来几本海外商学院的金融市场教材，几本央行主官回忆录、若干篇央行学者论文。撰于日本零利率无效之前的、甚至弗里德曼货币数量论破产之前的著作，9成会把新手带到沟里去。教材永远优先。//@刘夙:转发微博

30. @孤影_JN：组织行为学经典现象，平权组织跟他们声称所要解放的“被压迫”群体的利益会产生根本性冲突，“受压迫”群体消失，平权人士将会集体失业。女权、黑命贵、LGBTQ皆是如此。平权人士打死都不能承认社会平等，反而要极力煽动夸大群体矛盾。

31. 原来诺思早就说过，认为市场经济--宪政秩序可以自动维系乃至拓展，是一厢情愿。

换句话说，烂国是自然的、广泛的、悠久的、乃至终结的。从光荣革命演化到现在，人们所享受的各种权利、自由的增长，以及由此带来的科技进步和财富增长，才是泡沫。想多享受一会儿吗？

原话是：“权利开放社会中的社会学家过多地依赖于一个暗含的、方便的假设，即，他们所生活的这个社会就是历史规范（historical norm）。与此相反，我们认为自然国家，而不是权利开放秩序，才是社会的默认结局。”

32. 《集体行动的逻辑》是公共选择学派的早期经典之一，后来的大拿是诺思。这个学派不把政府视为慈祥的无私的保姆，而是劫匪和镖局等基因的混合体。这么说吧，没受此学派熏陶就讨论公共事务的教授学者乌泱乌泱的，但都不值得理会，即便是诺奖得主也要当民科看。

33. 推荐，不仅仅是这篇文章，而是诺思领头的这个学派，个人还是相当喜欢的。理由有：

1）划分出“自然国家”这个概念，即，经济特权被政治过程所操纵，以创造出用来稳定政治联合体的租金。（对应的，英美及其改造过的西欧、日韩台，我个人看法是“异常国家”，不经ICU级别的器官移植、长期免疫抑制，难以自发实现，一般会停在某个阶段）。

2）学者较多、研究视野更立体。几十个国家的转型经历，多个层级（中央、地方、基层）、多条寻租脉络（央地税收、债务、外汇、国企、贸易合资金融等许可或补贴、土地许可）、多种博弈演化模型（精英之间武斗文斗、精英与民众组织之间、政商联结）。比福山、亨廷顿、阿西莫格鲁等单点牛人、概念网红型，料更多。

3）视国家为博弈场地、博弈后果而非博弈者。这个我置顶的“刷机学2019”里有举例。

购书的话《暴力的阴影》、《暴力与社会秩序》值得作为入手必读。

《亚洲教父》、《独Cai者手册》、《掠夺之手》《经济增长的迷雾》也可以看看。

34. 吃财政饭看政客或官僚脸色的行业，宏观经济，产业政策，城市规划，教育医疗社保福利，绝大多数“专家”都左的没法看//@kingsmill:传染病医生的生计靠政府的程度高得多，从防到控，一系列操作政府都插手而且垄断，有了研究成果也是给cdc。相对来说外科医生的主顾是病人，很多医生自己其实是小企业主

35. “中华人民共和国”从名义法律到名义国体到名义纲领，都是罗马文明的分支，评论里爱国猴子们的智商尚不足以意识到这点……