---
title: '历史上中国人是非常勤劳的，为什么一直都很穷？  '
author: 翻开历史书
date: '2021-08-31'
slug: '274'
categories:
  - Translation Articles
tags:
  - China
  - History
  - Economics
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

[Source](https://kknews.cc/zh-my/history/3ybq9no.html)

估计很多人不知道，我们中国人彻底解决吃饭问题，也才几十年的时间。在封建王朝的漫长岁月里，可以说整个清朝以前中国人其实一直很贫困。书上说古代中国是一个“自给自足”的状态，我认为这种说法是不准确的。

在历史上，中国从来就没有“自给自足”过 ，一旦遇上天灾人祸，就会爆发大规模的饥荒。历朝历代都是如此，就算是号称鼎盛的唐朝，爆发水旱蝗灾，也会饿死整片整片的人。

那么古代中国人为什么穷呢？我们通过常识或者说史实，可以看出来我们中国人是最勤劳的民族。每天日出而作、日落而息，没有休息、没有懈怠，整天除了劳动就是工作。有人会说科技不发达，这个是结果不是原因，为什么会导致科技不发达呢？

我想古代中国人的穷还有更加深刻的原因，今天我带着大家一起去深扒一下：


# 经济发展模式有问题

大家都知道这几十年我们富裕了，为啥富的呢？其实就是因为发展了商品经济或者说是市场经济。古代历朝历代的皇帝们，都实行的是“重农抑商”的经济模式，并在国家政策上限制工商业的发展。古代中国人的生产活动，并不是为了积累财富，而是为了自家的消费，也就是小农经济。只有当自家出现了生活盈余品的时候，才拿到集市上去交换，在这样的经济形态下，商品交换极其有限，人民是不可能富裕起来。

皇帝们为什么实行“重农抑商”的经济政策呢？主要还是从统治的稳定性考虑的，他们认为种地是本业，其他的都是不务正业。皇帝们还认为，把农民固定在一个地方种地，有利于管理、有利于稳定。如果人员流通起来，就会出现思想开明、不利于管理，从而影响皇帝们的统治基础。



> 朱元璋说：“若有不务耕种，专事末作者，是为游民，则逮捕之”。李世民说：“禁绝浮华，劝课耕织，使民还其本，俗反其真，则竞怀仁义之心，永绝贪残之路。此务农之本也。”



几乎历朝历代的皇帝们，都对商品经济嗤之以鼻。大家想想，天天种那一亩三分地，你就是再勤劳也不可能发家致富的。



# 战乱四起、改朝换代过快


我们的历史其实说白了，就是皇帝轮流坐庄的历史，张家换成了李家、王家换成了朱家。 没有一个安定的内部环境人民是不可能富裕的。



每一次的改朝换代几乎都伴随着战乱和兵祸，广大农民的财富都会在这样的环境下消耗殆尽。每一次改朝换代也伴随着财富、阶级的重新划分。在一个不稳定的内部环境中，是不可能产生大量财富聚集和传承的。



# 不光严禁国内贸易，国外贸易也被禁止


大家知道，导致我们近代落后的一个主要原因就是：明、清时期实行的闭关锁国政策。



当我们自己还是老一套经济模式的时候，老外那边发生了工业革命了。其结果就是1840年以后我们被别人揍趴下了，这是我们中华民族心中永远的痛、也是我们贫穷和落后的重要原因。



# 关于官的问题


我们历史上很长一段时间都实行的是科举制度，也就是所有的人才都被这个制度网罗到了体系内，当官去了。在这种制度的指导下，民间就兴起了“当官光荣”、“经商低贱”的观念。古代一般讲“士农工商”，商人是最没有前途的一类人了。科举制度让无数的精英，长年累月的去读那几本书（一般是四书五经），也压制了无所个想创造财富的灵魂。



我们古代也一直没有解决好，官员的廉政问题。老百姓不光要交税、做徭役，还要被各级官员盘剥，这也是导致贫穷的一个重要原因。



最后我想说，什么样的土壤产生什么样的人。在一个崇拜当官的、打压商人的古代社会中，财富是不可能被大量积累的、富裕也就无从谈起了。有人说勤劳可以致富，勤劳虽然是致富的一个重要原因，但绝对不是一个核心原因。当有人千方百计阻止你拥有财富的时候，靠着勤劳想去致富，往往只是一个笑话。





