---
title: 靠运气赚来的钱，怎么就凭实力亏没了？
author: 米筐投资
date: '2021-07-05'
slug: '240'
categories:
  - Translation Articles
tags:
  - Investment
  - Business
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

[Source](http%3A%2F%2Fcj.sina.com.cn%2Farticles%2Fview%2F5996376439%2F16569717700100nyfe)



发家致富靠运气，守财持家靠实力。

# 田强的烦恼

田强（化名）最近很烦恼。成年人的烦恼，大多跟钱有关，田强也不例外……这些年投资、创业，几乎事事不顺，亏了几百万，早些年赚的钱近乎亏完了。

田强的故事带有传奇色彩，若不是这些年流年不利，他应该是屌丝逆袭、农村贫穷少年翻身晋升阶层的楷模榜样。

当然，这样的人和事或许你并不陌生，只要留心观察，总能在身边找到这样的案例，而这样的故事在四十年波澜壮阔的改革红利催生的财富大潮中不胜枚举。

田强毕业于2000年初期，没钱、没权、没势、没关系的他也没有好的去处，不得已就在他上学的这座省会城市漂着。

人生中充满着各种阴差阳错。偶然的机会，田强（那时还是小田）找到了一份售楼员的工作——不是地产商的职员，而是一家地产代理公司的基层员工。

下面的故事就有些俗套，像是写小说，其实就是田强的真实经历。

做了售楼员，大致摸清了地产商房产销售的大致节奏、也懂了些营销策划，之后跳槽去另一家代理公司做策划专员，再之后升任主管……慢慢的有了些人脉，终于独立出来成立了一家小型的代理策划公司——接不了大项目，但一些小盘、小项目还是能接到的。

随着省城市场竞争的日趋激烈，田强也找到了房产代理新的蓝海——广大的地级市、甚至县城，省城的营销方案、活动策划、开盘流程等让小地方的人大开眼界，并纷纷的倾囊购房。

最兴盛的时候，田强的公司有员工近百人，广泛的散播于四五六线城市。也就是那些年，田强积累下了几百万，并在省城买了多套房产。

大概在2012年，也就是2008年四万亿放水刺激、一波地产大牛市后的新一轮楼市调控后，田强决定离开这个行业。

一是代理公司日趋头部化，再小的项目都想找个知名的品牌机构，二是很多地产商都开始组建自己的营销策划销售团队，三是那两年地产行情确实不好。

手拿近几百万的资金怎么办呢？要么投资要么创业啊。田强也确实是这样做的。

先拿100万投资于民间借贷的担保理财、再拿50万投资于私募股权……后来干脆自己在老家低息集资再到省城高息民间理财，结果想必大家都知道——私募股权就是一场骗局，担保理财很大一部分打了水漂。

后来他又创建类似“淘宝”、“阿里巴巴”那样的电商平台；

在2015年“大众创业 万众创新”风潮时，还参与了不少众筹项目；

之后又参与大健康产业，承包了一家体检中心；

2018年数字货币疯狂的尾期，还发行了一只数字货币……

田强做事干脆果断、风风火火，可看了上面的项目，想必大家也都猜到了结果。

早些年的积蓄和房产，这些年硬生生被自己的一腔热忱折腾的近乎殆尽。

# 为什么成功？

有些人为什么会成功？不同的人会有不同的答案，且每一个答案都听起来条理清晰、逻辑严谨、头头是道……可真实的答案可能会超出所有人的预料——运气！很多人的成功仅仅是因为运气。

那后来为什么又会失败呢？因为实力啊——不是实力太强，而是实力原形毕露、是因为自己实力本身就泯然众人，只是再没有之前成功时的那种好运气罢了。

可很多人在成功后，总会有一种能力幻觉，以为自己无所不能、所向披靡……可离开运气，自己真的什么都不是。

田强就是凭借运气赚钱、而靠实力亏钱的典型例子。

2000 年之后的十余年，是中国地产的大牛市行情，这里有经济红利、改革红利、人口红利、城市化红利、人口大城市聚集红利的综合因素叠加，而田强恰好处在这样海量 增量财富的蓝海里，只要脑子稍微活络些、再加上一些敢闯的胆量，不说财务自由，积累百万资产或达到小康水平还是较为容易的。

而他后来失败，则是因为他自满自大、错把之前的运气当作了自己的实力，所以才奋不顾身的四处投资、激情创业，更重要的是他近乎都在存量财富市场里的搏杀——很少、甚至没有增量财富的创造，只是存量财富的争夺，一个人赚的就是另一个人亏的。

这样的故事不仅在新闻和小说里，在我们的身边也时不时的会遇到：某人生意曾经很成功，后来转型不顺逐渐没落了；某人曾经很有钱，后来投资不利挥霍一空；某企业曾经在行业内遥遥领先，后来像流星一样陨落……

成功是得靠运气的：增量财富市场的大环境、迅猛发展的某个行业、某个机缘巧合自己洽在其中、自身又有基本的技能特质、偶然的机遇并刚好被捕捉到……成功是一系列的机缘巧合。

为什么这两年很多人抱怨生意不好做了？因为以前经济增长快，会有大量的机会，相应碰到好运的机会就多，说不定哪个就轮到你了，那是非常态。而今只是常态的回归。

为什么现在会凭实力能把之前赚的钱亏完呢？因为现在的财富其存量争夺的特征较为明显，大方向来看就是GDP增速在下滑——没有那么多新财富创造出来，那就只好对现有财富进行争夺了。



于是，我们大家都看到了：民间借贷的担保理财洗盘一批财富、真的假的股权私募洗盘一批财富、P2P理财洗盘一批财富、数字货币洗盘一批财富、创业折腾洗盘一批财富……

在存量财富争夺的市场里，你越折腾、越努力、越尝试……财富被分配/被转移的机会就越多、可能性也就大啊。

那如何走出“凭运气赚钱 靠实力亏钱”的魔咒呢？

# 如何守财富？

在思想上，我们一定要有个认识——财富具有偶然性和运气性。

比你更优秀、更努力的人多得是，可唯独包括你在内的少数人成功了、而大多数人却没有成功，仅仅是因为你的运气好……在恰好的时间、恰好的地点、恰好是你遇到了。

你的成功不具有普遍性和可复制性，仅仅是一个幸存者偏差的个案。

有了这种心理后，就会对财富多了些敬畏，也会对自己的能力有了更为客观的评价，不会盲目相信自己什么都行、相应的也就少了很多砸钱投资的冲动。

在行动上，我们要坚持一个原则——在可承受范围内多尝试。

有了一定财富后，为了绝对安全就什么都不干、让钱静静的躺在账户里吗？当然不是。且不说这样只会坐吃山空，即使不花销等若干年后其购买力也会贬值，因为通胀也在侵蚀财富啊。

所以也就有了“多尝试”的建议，多尝试、多试错、多样化的投资，投的注足够多、中彩的几率就会变大，东方不亮西方亮，说不定哪个机会就逮住了——这不是也在博一个运气的概率么？！

但“多尝试”的前提是，要在自己的承受范围内，也就是说不要一把梭、满仓上、全杠杆、All in，以避免一旦爆仓全军覆没的悲剧，那可就没有东山再起的机会了——以前赚取财富的好运哪能想来就来呢。

当风险可以承受时，即使血本无归也不影响整体资产安全，反而能学得经验教训，若运气好大赚一笔，则会为整体资产锦上添花，也多了更多的经验和自信。

同 时在资产多时，应更在乎资产的安全性、而非收益性，因为资产多，即使收益率低些，但因为基数大，其绝对收益也相当可观，若贪心不足只想着“本金多就应赚得 更多”，很可能因为追逐收益而损失了本金——大多数的投资骗局都是这样的，以高收益诱惑你，你看中别人的利息，而别人却看中了你的本金。

如果仔细观察，我们或许会发现一些成功人士，在发迹之前敢闯敢干、胆子大有激情有魄力，可在有成之后反而畏首畏尾、瞻前顾后，显得胆小慎微、不敢越雷池一步，前后差别恍若换了一个人。

是他变傻或变蠢了吗？当然不是。

以前什么都没有，当然要甩开膀子大胆尝试去博运气啊，而今运气博到了，当然要变得保守起来把博来的运气给守住哦——运气就是运气，带有不确定性，怎么能保证以后还能像以前那样有好运气呢？别到时运气没博成、反而把之前凭借运气博来的财富弄丢了。

走过来的人，看似失去了创业时的一腔热血冲劲，实则是深思熟虑后的理性抉择。

凭运气赚来到钱，必须得靠实力守住。