---
title: 中共英雄的历史真相，谁说了算？
author: 洪振快
date: '2021-12-12'
slug: '348'
categories:
  - Translation Articles
tags:
  - History
  - Propaganda
---

[Source](https://cn.nytimes.com/opinion/20160225/cc25hong/)

最近十几年，在言论相对自由的互联网上，中国大陆的老百姓对中共历史上塑造的英雄形象，包括黄继光、邱少云、“狼牙山五壮士”等，普遍表示质疑。这种质疑，反映了尊重常识、了解历史真相的愿望，既是老百姓的觉醒，也反映了民心民意——对中共宣传的不信任，乃至对中共的不满。中共对此的应对是，发动官方宣传机器。据一位军方背景的学者的说法，要“捍卫”英雄形象，意图打赢网络“上甘岭战役”。于是，普通网民与中共官方及其支持者（网络水军“五毛”、“自干五”及“毛左”）之间，在网络上你进我退，硝烟弥漫。这是很容易观察到的，也是我的亲身体会。

“狼牙山五壮士”是中共宣示自身抗日功绩的一面旗帜。在去年9月的“世界反法西斯战争胜利”70周年阅兵仪式中，“狼牙山五壮士”部队方队作为10个阅兵方队中的第一个方队出现，足见其地位。这面旗帜的重要性在于，“狼牙山五壮士”是抗日战争中出现的，比起黄继光、邱少云是抗美援朝（即朝鲜战争）中出现更有价值，因为抗日战争是民族大义，又是世界反法西斯战争的重要组成部分，不仅能够获得全民族认同，而且更能获得全世界文明主流的认可。而中共在抗战中的功绩，也需要这一“抗日英雄群体”形象的支撑，因为中共在抗战中没有更有名的英雄事迹可供宣传。

“狼牙山五壮士”的官方版本（以小学语文教科书和新华社、《人民日报》报道为代表），简要归纳如下：1941年秋，日军“扫荡”晋察冀根据地。9月25日，日伪军约3500余人围攻易县狼牙山，晋察冀军区第一军分区一团七连奉命掩护党政机关、部队和群众转移，该连六班马宝玉等五名战士担负掩护主力和老百姓转移的任务，五人分散射击，使日伪军误认咬住了八路军主力，将其引向狼牙山棋盘陀峰顶绝路，五人打退日伪军多次进攻，毙伤90余人，子弹打光后，仍用石块还击，最后宁死不屈，毁掉枪支，喊着“打倒日本帝国主义！”“中国共产党万岁！”的口号，纵身跳下数十丈深的悬崖。马宝玉、胡德林、胡福才壮烈殉国，葛振林、宋学义被山腰树枝挂住，负伤归队。

上述官方版本已经沿用了几十年，但也不断受到质疑。比如，文革中，红卫兵对宋学义跳崖而未遇难表示怀疑。1994年7月，《长江日报》刊登了一篇文章，提出当时六班不是五个人，而是六个人，还有一位副班长，投敌被杀。1995年8月，《羊城晚报》又刊登了一篇文章，称五壮士跳崖是“三跳二溜”，马宝玉等三人跳崖牺牲，葛振林、宋学义是“顺着崖壁溜了下去”。

近年在互联网上，这个故事受到更多的质疑。比如有网帖通过知情者之口，说五人跳崖前“与鬼子拼起了刺刀”、“是拼不过敌人不小心倒退摔下了悬崖而非故意跳下”。其中，最让人感到怀疑的是，跳下悬崖而能被山腰树枝挂住生还。众所周知，文革中的红卫兵都是狂热、不理性的中学生，连他们都对跳崖生还表示疑义，比红卫兵更理性、客观的网民对该故事表示不解和疑惑是很自然的。

2013年8月下旬，国家宣布打击网络谣言，广州越秀警方将一位在新浪微博上“污蔑狼牙山五壮士”的网民张广红抓获，以虚构信息、散布谣言的罪名予以行政拘留七日。该事件被报道后，舆论哗然。出于对警方抓人程序的质疑，本人撰写了两篇文章：9月上旬，本人在财经网上发表评论文章，质疑小学语文课本《狼牙山五壮士》的真实性；同年11月，本人在《炎黄春秋》杂志上发表史实考证文章，质疑新华社、《人民日报》2005年报道的“狼牙山五壮士”的事迹的真实性。两篇文章质疑了“狼牙山五壮士”的官方版本——比如在棋盘坨顶峰跳崖的说法，但都是根据中共官方认可的出版物上的材料，遵循史学研究规范，而且对“狼牙山五壮士”抗日持正面评价。我的文章对他们作为抗日战士一直都表示尊重，只是认为民众有了解历史真相的权利，所以希望澄清历史真相而已。然而，由于事涉中共历史上塑造的英雄形象，还是捅了马蜂窝，引发了连环官司。

先是本人和文章编辑黄钟被两位左派网络活跃人士梅新育、郭松民公开以极具侮辱性的言词辱骂，在律师函无效后，本人和编辑黄钟以侵犯名誉权为由起诉了两位骂人者。案件拖了一年多才开庭审理，又过了七个多月后才于2015年12月宣判，结果是北京海淀、丰台两个法院认为骂人有理，可以不负法律责任，因为本人文章是“试图质疑甚至颠覆‘狼牙山五壮士’的英雄形象”(判决书的说法)。对此判决，我们认为其违背司法职责，背离法治原则和宪法精神，况且，明显受到政治干预——比如，被告郭松民的代理人王立华（网络公开此人身份为解放军总参政治部下属宣传部原副部长，大校军衔）在公开的视频中透露，国防大学原政委赵可铭上将曾给法律部门的最高领导打电话，称：“你们这个案子如果判反了，你们就是反军叛国。”本人已向中纪委、军纪委、最高法、最高检等中央七部门公开实名举报，但将近两个月，没有任何部门给回信。因此，判决不能让人信服，我们已提起上诉，目前二审法院还未做出最终裁决。(春节刚过，北京市第一中级人民法院、第二中级人民法院即召集谈话，法院本周正在开庭进一步审理。）

此外，“狼牙山五壮士”幸存者葛振林、宋学义的儿子葛长生、宋福保还起诉本人，要求本人向五壮士“在天英灵登报谢罪”。经过一次证据交换和两次庭前会议，原定2016年1月27日开庭审理，但因对方涉嫌作伪证被本人的代理律师揭露——对方公民代理人王立华大校所提交给法庭的证明上写的“保定狼牙山红色文化研究会副会长”身份系伪造，本人已向审理该案的北京市西城区人民法院提交此人代理非法、妨害司法的证据，法院需要调查核实，目前还未接到开庭通知。

作为历史研究者，本人一直关心的是“狼牙山五壮士”的历史真相到底如何。关于该事，出版物中多为口述材料，一直缺乏档案等史料证实。严肃的历史研究者大多清楚，口述的“革命回忆录”，可能含有较大水分，不能轻易作为史料。但中共对档案的管理十分严格，除非中共自己愿意公开，否则老百姓无法看到。本人2015年7月到解放军档案馆要求查阅晋察冀军区1941年9月份牺牲人员名单，以便证实“狼牙山五壮士”事迹，但材料提交半年之后仍无答复。不过，“狼牙山五壮士”后人的代理人后来去了解放军档案馆，该馆提供了一份档案（晋察冀军区司令部1942年2月1日做出的《晋察冀军区1941.8.13—10.17反扫荡战役总结》）。根据去年11月底交换证据时对方提交的这份档案（部分内容），以及北京军区公布的相关材料等，“狼牙山五壮士”的历史真相开始显山露水。结果证实本人原来发表中的文章所提出的对中共官方宣传的“狼牙山五壮士”事迹的质疑都是成立的：官方版本与内部档案是两个完全不同的说法，相对真实的内部档案颠覆了官方版本的宣传。

档案关键部分内容为：“二十五日拂晓，管头、龙门庄、界安共出敌三千五百余，并携民夫牲口千余，分经干河、条条岭、东西水、步乐、娄山、沙岭、上下铺，围攻狼牙山，以搜索龙王庙、棋盘坨为主，十二时敌占龙王庙、棋盘坨、老君堂、乌马驿各高地，我（指晋察冀军方）在该地活动之部队于敌开始动作时即向外线转移，仅一团在该地游击之第七连第六班因掩护主力转移，退路被敌截断，该班当即占领有利阵地顽强抵抗，将敌诱至我预设之地雷群，敌触地雷毙伤指挥官以下五十余名，嗣敌四次冲锋均被击退，敌复伤亡四五十我阵亡二，终以弹尽，该班长乃率所余战士四名，先将武器破坏，跳断崖殉国，亡三伤二（敌退后得救归队）。”
上述档案等材料证实了几个关键信息：

第一，官方版本一直宣称阻击日伪军的六班只有五人，档案证明五人跳崖前已“阵亡二”，即当日六班至少有七个人。而葛振林曾表示实际有12人。这说明，官方版本信誓旦旦地说只有五人，实际是不实之词，当天的作战过程、双方伤亡等也非官方版本宣传的那样。
第二，官方版本称“狼牙山五壮士”作战目的是将日伪军引向狼牙山棋盘陀峰顶绝路。而档案明确提到，日伪军当日行动的主要目标就是占领棋盘坨——“以搜索龙王庙、棋盘坨为主”，并且中午12时棋盘坨已被日军占领——“十二时敌占龙王庙、棋盘坨、老君堂、乌马驿各高地”。可见把日军引向棋盘坨明显属于不实之辞。

第三，官方版本称“狼牙山五壮士”跳崖地点是棋盘坨顶峰。但上世纪90年代以来，当地百姓提出是小莲花峰（《百年潮》2003年第6期刊登的叶晖南《狼牙山的真实故事》一文有较详细说明）。之后，狼牙山景区官方确认在小莲花峰，并树立标志。2014年9月1日国务院颁布的文件，确认跳崖地是小莲花峰。档案证实，跳崖地确实不是在棋盘坨顶峰——因为12时棋盘坨已被占领，而后“跳断崖殉国”，这个“断崖”是否就是小莲花峰姑且不论，但显然不是棋盘坨顶峰。跳崖地点乃是新闻报道、历史事件的基本信息。跳崖地点变化，意味着作战经过、作战目的等说法都将随之改变。这说明，长期以来中共官方宣传不实信息，不想将历史真相告知世人。
第四，官方版本称“狼牙山五壮士”的整个作战过程是完全主动的。档案说得很明白，当日“十二时敌占龙王庙、棋盘坨、老君堂、乌马驿各高地”，整个狼牙山已被敌控制，六班战士是“退路被敌截断”，无路可走，换言之，就是被追杀，而按照《人民日报》1951年8月1日刊登的葛振林写给毛主席、朱总司令的信中的说法，当日情况是“（班长）马保林指挥我们撤退到一个从没有人到过的悬崖上”，若其所述属实，则退却是慌不择路，更谈不上主动了。

本人认为，上述档案和北京军区后勤部公布的材料等，证明了所谓“狼牙山五壮士”的英雄事迹，实际是遭遇日军搜山，日军以“多路的轻装部队”快速行动，“迅速的占领该山的最高顶”（北京军区后勤部公布的材料的说法），中午12时已占龙王庙、棋盘坨、老君堂、乌马驿各高地，控制了制高点，在此地游击的六班“退路被敌截断”，在牺牲二人（至少二人）后，五人慌不择路，退到了“一个从没有人到过的悬崖上”。至于五人跳崖，葛振林后来承认跳的地点不完全一样，牺牲的三人或许是跳悬崖，幸存的两人据其自述则是“溜”、“滚”、“窜”，1946年中共文艺机构在延安的出版物也说是“三跌二溜”。

由此可见，该事迹并无特别英勇之处，而中共中央北方局机关报《晋察冀日报》在事件发生后40天（1941年11月5日）刊出《棋盘陀上的五个“神兵”》的报道，进行了拔高、神化（号称“神兵”）。本来，战时夸大宣传可以理解，但时过境迁，应该回归历史真实，而不能不顾政治伦理，把战时夸大宣传当作史实，继续宣传，甚至更进一步造神。但经过1958年拍摄并于随后上映的电影《狼牙山五壮士》，以及进入小学语文课本，与史实不符的“狼牙山五壮士”事迹成为一种观念，被塑造成一个表现中共抗战功绩的典型，而任何试图回归历史真实的努力，就要受到侮辱谩骂、人身攻击，法院还要以司法判决认定是“试图质疑甚至颠覆‘狼牙山五壮士’的英雄形象”，要求对侮辱谩骂、人身攻击尽到“容忍义务”。从这种荒诞现象，可以看到中国的政治现实，中共官方为了维护意识形态，甚至不惜抛弃不得干预司法的“依法治国”宣示。

抗战期间，英勇作战，功绩彪炳，可歌可泣的英雄事迹甚多。仅以中共承认的抗战英雄而论，就不在少数。如中共领袖毛泽东1938年的讲话中就提到不少国民政府领导的正面战场上的抗战英雄，还给在上海闸北英勇抗战的“八百壮士”题词，赞扬其为“民族革命典型”。
根据国民政府公布的材料，抗战期间国民政府军队伤亡约323万人，其中阵亡近133万人。中共方面宣布，抗战期间领导的军队伤亡45万人，其中阵亡16万人。两者比较，中共领导的军队伤亡不到国民政府军队的七分之一，阵亡则不到八分之一。国民政府军队在正面战场上的英勇抗战和英雄事迹，连中共领导人都承认的，现在中国大陆老百姓已很少有人了解；而一个敌后抗战、并无特别英勇之处的“狼牙山五壮士”事迹，却要夸大为神，并且不容丝毫质疑。这是历史的不公正。

历史总归会回归真实。公众希望了解历史真相。掩饰真相，终会成为历史笑柄。以政治干预司法，对探求历史真相的学术研究，进行不公正的司法裁判，剥夺公民言论出版自由、学术自由的宪法权利，最终也会被历史审判。