---
title: 微言（5）
author: Guanghua Mao
date: '2021-07-16'
slug: '250'
categories:
  - Original Articles
tags:
  - Insights
  - Economics
  - History
  - Politics
---

1. 如果中国经济的问题真有目前普遍估计的那么严重的话（多难交集 -- 期货融资、信托、房地产、产能过剩、出口受压），很可能将没有万全之策，只能选相对最不糟糕的路 -- 印钱-贬值同时让一批企业信托违约破产，尽量避免大城市房地产恐慌性崩盘，胡温之祸的恶果，现在才刚开始显现。

2. 天朝就是法国。千年老二的命。因为人口众多而奋起追赶当个老二。因为公有制核心太小，于是无数精英或互砍或浪费而无法合力冒尖。拿破仑有一个机会，却因为独裁而不知足最终亡国。专制国家总是在群体的自傲而又个体的自卑中折腾没完。

3. 职业学校、技校太需要了，中国还想在装逼传统里耽误自己多久？

4. 过去几十年的中国，汹涌澎湃，不仅是不进则退，进慢了也是退。但时代不同了，今后几十年，不退则进，退得慢点也是进。换言之，傻逼发财的日子过去了。一两年之内傻逼混日子的日子也会成为历史，然后还能逆袭的那才叫真神。

5. 上世纪初，钢琴是美国吊丝进入中产、装高富帅的必须。现在老美孩子学钢琴的比例很小了，老中学会了 //@文语堂echo:为什么呢 //@华尔街叛徒:中国妈妈对钢琴的追求是无论如何都不可能改变的
遛了一圈，发现美国媒体对冬奥开幕式总体偏酸，认为不如北京。在我看来，这印证了前面我说的“研究苏俄历史的学者憎恶苏俄，研究中国历史的爱上中国”

6. 只能说没让你死的事情总会让你更强大。俄罗斯生存环境极为艰苦，从自然到地缘政治两方面，菜花都是逼出来的。反观中国，两千年相对而言日子基本能过。生命都是苟且偷生得过且过的，所以一事无成。

7. 春节串门， 我发现，周围很多亲戚朋友有“秘方情节”，“挖宝心态”，遇到困难，只希望快速找到一个秘方绝招，一下就解决。糊涂。很多已婚女人，神经错乱般的崇拜身边的成功者发财户，大事小事，无端指责自己男人，以此泄愤，实在是无语了。实际上，大部分成功，只不过是赶巧了。

8. 据我了解，基本上只有中国妈、中国老婆经常拿别人羞辱自己的孩子男人。不知道日韩是否也是这种贱人文化

9. 靠近沈阳的小地级市，今年新开了第一家麦当劳，环境这些年得到改善，不再暴土扬长。人们的收入却还处在较低的水平，3000-5000算是较高收入了。考上好大学的年轻人基本都不会回来了。逛街都没啥逛的，很多有点钱的人也慢慢移居去沈阳了。总是传言要归沈阳管了。



10. 不会创新、不愿投资创新，那就只能搞价格竞争。不解的是中国企业家，包括港台有几十年基业经验的，为什么几乎全部只能靠价格竞争 

11. 很多中国人似乎不理解，美国入室偷窃的都会精心侦察选没人在家的时候，知道有人的话极少会进入，除了知道你没枪的地方之外比如纽约市。夜不闭户，其实是基于威慑基础上的文明。中国人在自己家里都必须锁好门的那种不安全感实在是根深蒂固

以上言论转载自@华尔街叛徒（已被封）


---

1. 在远超日常经验的科学研究和系统性认知上，人民群众是非常愚蠢的，难怪说人民群众不傻逼谁傻逼。

# 往死里操

【2016-06-21】

1）大众从来不是政治角斗场的主动力量，

2）有时他们确实会扮演重要角色，比如被一部分精英动员起来，用作棍子去打另一部分精英或大众，

3）充当棍子不会给他们带来好处，拿他们当棍子使的人当然也会把他们往死里操：看看烟草税、可乐税、最低工资法、禁毒禁娼、欧洲油价电价、医药管制、土地规划……

4）所以围绕福利制度、累进税、普选权等等的制度之争根本不是什么阶级斗争，那从来都是不同精英团体之间的斗争，各自努力将社会竞争规则朝自己希望的方向改变，

5）在实行自由规则的社会，穷人/弱者/笨蛋往往也会失败，但那是有尊严的失败，而在福利制度下，穷人/弱者/笨蛋还是会失败，但那将是被骗走了尊严的、堕落的、污秽的失败，就像The Wire里那个拖着鼻涕的线人

@振华-Citywanderer:土地规划?何解

@whigzhou: 没有土地规划时，穷人可以住偏一点、差一点、挤一点的房子，甚至拖车，有了土地规划，穷人睡在公园椅子上

@whigzhou: 很多人说有了普选权就不可能收人头税了，蠢，换个名字而已，德国电价中的70%不是人头税是啥？