---
title: WHAT IS MATHEMATICS?
author: Guanghua Mao
date: '2019-12-23'
slug: what-is-mathematic
categories:
  - Tranlation Articles
tags:
  - Math
---

Author: Richard Courant & Herbert Robbins

Translator: Guanghua Mao

Source: *WHAT IS MATHEMATICS* (2nd Edition)

# 什么是数学

Mathematics as an expression of the human mind reflects the active will, the contemplative reason, and the desire for aesthetic perfection. Its basic elements are logic and intuition, analysis and construction,generality and individuality. Though different traditions may emphasize different aspects, it is only the interplay of these antithetic forces and the struggle for their synthesis that constitute the life, usefulness, and supreme value of mathematical science.

Without a doubt, all mathematical development has its psychological roots in more or less practical requirements. But once started under the pressure of necessary applications, it inevitably gains momentum in itself and transcends the confines of immediate utility. This trend from applied to theoretical science appears in ancient history as well as in many contributions to modern mathematics by engineers and physicists.

Recorded mathematics begins in the Orient, where, about 2000 B.C., the Babylonians collected a great wealth of material that we would classify today under elementary algebra. Yet as a science in the modern sense mathematics only emerges later, on Greek soil, in the fifth and fourth centuries B.C. The ever-increasing contact between the Orient and the Greeks, beginning at the time of the Persian empire and reaching a climax in the period following Alexander's expeditions, made the Greeks familiar with the achievements of Babylonian mathematics and astronomy. Mathematics was soon subjected to the philosophical discussion that flourished in the Greek city states. Thus Greek thinkers became conscious of the great difficulties inherent in the mathematical concepts of continuity, motion, and infinity, and in the problem of measuring arbitrary quantities by given units. In an admirable effort the challenge was met, and the result, Eudoxus' theory of the geometrical continuum, is an achievement that was only paralleled more than two thousand years later by the modern theory of irrational numbers. The deductive-postulational trend in mathematics originated at the time of Eudoxus and was crystallized in Euclid's *Elements*.

However, while the theoretical and postulational tendency of Greek mathematics remains one of its important characteristics and has exercised an enormous influence, it cannot be emphasized too strongly that application and connection with physical reality played just as important a part in the mathematics of antiquity, and that a manner of presentation less rigid than Euclid's was very often preferred.

It may be that the early discovery of the difficulties connected with "incommensurable" quantities deterred the Greeks from developing the art of numerical reckoning achieved before in the Orient. Instead, they forced their way through the thicket of pure axiomatic geometry, Thus one of the strange detours of the history of science began, and perhaps a great opportunity was missed. For almost two thousand years the weight of Greek geometrical tradition retarded the inevitable evolution of the number concept and of algebraic manipulation, which later formed the basis of modern science.

After a period of slow preparation, the revolution in mathematics and science began its vigorous phase in the seventeenth century with analytic geometry and the differential and integral calculus. While Greek geometry retained an important place, the Greek ideal of axiomatic crystallization and systematic deduction disappeared in the seventeenth and eighteenth centuries. Logically precise reasoning, starting from clear definitions and noncontradictory, "evident" axioms, seemed immaterial to the new pioneers of mathematical science. In a veritable orgy of intuitive guesswork, of cogent reasoning interwoven with nonsensical mysticism, with blind confidence in the superhuman power of formal procedure, they conquered a mathematical world of immense riches. Gradually the ecstasy of progress gave way to a spirit of critical self- control. In the nineteenth century, the immanent need for consolidation and the desire for more security in the extension of higher learning that was prompted by the French revolution, inevitably led back to a revision of the foundations of the new mathematics, in particular of the differential and integral calculus and the underlying concept of limit. Thus the nineteenth century not only became a period of new advances, but was also characterized by a successful return to the classical ideal of precision and rigorous proof. In this respect, it even surpassed the model of Greek science. Once more the pendulum swung toward the side of logical purity and abstraction. At present we still seem to be in this period, although it is to be hoped that the resulting unfortunate separation between pure mathematics and the vital applications, perhaps inevitable in times of critical revision, will be followed by an era of closer unity. The regained internal strength and, above all, the enormous simplification attained based on clearer comprehension make it possible today to master the mathematical theory without losing sight of applications. To establish once again an organic union between pure and applied science and a sound balance between abstract generality and colorful individuality may well be the paramount task of mathematics in the immediate future.

This is not the place for a detailed philosophical or psychological analysis of mathematics. Only a few points should be stressed. There seems to be a great danger in the prevailing overemphasis on the deductive-postulational character of mathematics. True, the element of the constructive invention, of directing and motivating intuition, is apt to elude a simple philosophical formulation; but it remains the core of any mathematical achievement, even in the most abstract fields. If the crystallized deductive form is the goal, intuition and construction are at least the driving forces. A serious threat to the very life of science is implied in the assertion that mathematics is nothing but a system of conclusions drawn from definitions and postulates that must be consistent but otherwise may be created by the free will of the mathematician. If this description were accurate, mathematics could not attract any intelligent person. It would be a game with definitions, rules, and syllogisms without motive or goal. The notion that the intellect can create meaningful postulational systems at its whim is a deceptive half-truth. Only under the discipline of responsibility to the organic whole, only guided by intrinsic necessity, can the free mind achieve results of scientific value.

While the contemplative trend of logical analysis does not represent all of mathematics, it has led to a more profound understanding of mathematical facts and their interdependence, and a clearer comprehension of the essence of mathematical concepts. From it has evolved a modern point of view in mathematics that is typical of a universal scientific attitude.

Whatever our philosophical standpoint may be, for all purposes of scientific observation an object exhausts itself in the totality of possible relations to the perceiving subject or instrument. Of course, mere perception does not constitute knowledge and insight; it must be coordinated and interpreted by reference to some underlying entity, a"thing in itself, " which is not an object of direct physical observation, but belongs to metaphysics. Yet for the scientific procedure, it is important to discard elements of metaphysical character and to consider observable facts always as the ultimate source of notions and constructions. To renounce the goal of comprehending the"thing in itself, " of knowing the"ultimate truth," of unraveling the innermost essence of the world, may be a psychological hardship for naive enthusiasts, but in fact, it was one of the most fruitful turns in modern thinking.

Some of the greatest achievements in physics have come as a reward for courageous adherence to the principle of eliminating metaphysics. When Einstein tried to reduce the notion of"simultaneous events occurring at different places" to observable phenomena, when he unmasked as a metaphysical prejudice the belief that this concept must have a scientific meaning in itself, he had found the key to his theory of relativity. When Niels Bohr and his pupils analyzed the fact that any physical observation must be accompanied by an effect of the observing instrument on the observed object, it became clear that the sharp simultaneous fixation of position and velocity of a particle is not possible in the sense of physics. The far-reaching consequences of this discovery, embodied in the modem theory of quantum mechanics, are now familiar to every physicist. In the nineteenth century, the idea prevailed that mechanical forces and motions of particles in space are things in themselves, while electricity, light, and magnetism should be reduced to or explained as mechanical phenomena, just as had been done with heat. The"ether" was invented as a hypothetical medium capable of not entirely explained mechanical motions that appear to us as light or electricity. Slowly it was realized that the ether is of necessity unobservable; that it belongs to metaphysics and not to physics. With sorrow in some quarters, with relief in others, the mechanical explanations of light and electricity, and with them the ether, were finally abandoned.

A similar situation, even more accentuated, exists in mathematics. Throughout the ages mathematicians have considered their objects, such as numbers, points, etc., as substantial things in themselves. Since these entities had always defied attempts at an adequate description, it slowly dawned on the mathematicians of the nineteenth century that the question of the meaning of these objects as substantial things does not make sense within mathematics, if at all. The only relevant assertions concerning them do not refer to substantial reality; they state only the interrelations between mathematically"undefined objects" and the rules governing operations with them. What points, lines, numbers" actually" *are* cannot and need not be discussed in mathematical science. What matters and what corresponds to"verifiable" fact is structure and relationship, that two points determine a line, that numbers combine according to certain rules to form other numbers, etc. A clear insight into the necessity of a dissubstantiation of elementary mathematical concepts have been one of the most important and fruitful results of modern postulational development.

Fortunately, creative minds forget dogmatic philosophical beliefs whenever adherence to them would impede constructive achievement. For scholars and layman alike it is not philosophy but active experience in mathematics itself that alone can answer the question: What is mathematics?