---
title: Be the Best Gold Digger You Can Be
author: Guanghua Mao
date: '2020-09-18'
slug: be-the-best-gold-digger-you-can-be
categories:
  - Psychology
  - Translation Articles
tags:
  - Economics
  - Psychology
---


### Author: Jen Kim

### [Source](https://www.psychologytoday.com/us/blog/valley-girl-brain/201107/be-the-best-gold-digger-you-can-be?amp) 


>Does nature’s get-rich-quick scheme really pay?



There was a time when the label of "gold digger" was a stigma or something to be ashamed of. "She/he is a gold digger," you would warn your pal. Nowadays, it seems dating or marrying for money is not only out in the open, but also touted as something to be proud of.

Bravo's Matchmaker Millionaire, (which I confess, I love) is the perfect example. The delightfully obnoxious Patti Stanger plays matchmaker to the affluent, usually setting up wealthy men with young Hollywood model types, who all swear that they're really searching for true love. 

Yeah, okay.

Although, to them, love comes in the form of no-limit credit cards and Infinity pools. The premise of this business makes for great reality television, not a sustainable relationship. Why would anyone, millionaire or not, date someone who is so clearly motivated by a bank account?

Let's start here:


Their brief 13-month union lasted until dead did them part; Marshall died, leaving his buxom bride half of his $1.6 billion fortune.

What did Marshall have to lose in this deal? Well, he wasn't exactly a spring chicken if you know what I mean. Marshall wanted to spend his final months with Playboy's Miss May. At the end of his life, he didn't need to buy a new car or a new house, he just wanted some company. And Smith probably just wanted some major cash for very little time and work. Win-Win for both of them.

Now, fast forward to February this year when London's Daily Mail published a story about a woman named Kim Perez, who reinvented herself to attract and marry a wealthy man, which she did. Her incredibly blatant account (which you can read [here](https://www.dailymail.co.uk/femail/article-1352664/How-marry-millionaire-Shop-girl-Kim-reinvented-land-rich-husband.html)) is both revolting and mesmerizing for a couple different reasons.

First, she is unabashedly frank about her desire for the "finer things in life" and her goal to marry someone with money. Usually, people are reluctant to admit their shallowness and superficiality, but Perez flaunts it like a Louis Vuitton bag.


But now that she's "living the dream," Perez's daily life "consists of shopping, then going to the gym or for lunch." To help pass the time, her husband has also set her up with a fake-tanning business, "because there is only so much shopping you can do!"

After she was married, Perez eventually came clean to her husband about her humble upbringing and all the changes she had undergone to become someone that might be appealing to him. He laughed it off and found it "funny."

Not only didn't he seem to mind that he was being exploited, but he also found her self-loathing humorous. Which suggests that this relationship works perfectly-- she is unabashedly superficial, while he is unforgivingly self-centered. This partnership will continue to work, just as long as the cash is flowing. Perez gets her lunches and shopping sprees, while her husband gets the ficitious dutiful and beautiful trophy wife he fell for.

But what happens if the cash stops flowing? Does anyone think that far ahead when they're in love?

As you can see, gold digging works. So, maybe that's why it's becoming more accepted and... taught.

While I was at grad school pursuing higher education, Chinese girls in my peer group were attending school in pursuit of wealthy husbands. For around $3,000, The Beijing Moral Education Centre for
Women will train young females how to become more attractive to affluent men. Students learn varied skills and techniques, which range from makeup application to tea pouring skills.

In an interview with The Vancouver Sun, the school's founder and instructor, Shao Tong, says that the school improves women by "nurturing internal qualities and developing potential." Potential for
what, exactly? Who knows?

The Centre has become a breeding ground for love connections since it opened last year, boasting more than 30 matches in just the past few months. Affluent men must pay the school around $5,000 for meet-and-greets with eligible bachelorettes.

These men go into these preconceived situations fully knowing that these women are more interested in their pocketbooks than really finding a soulmate.


And what exactly are these women getting themselves into? Mercedes and mansions, that's what. As long as they continue pouring tea the right way and looking the perfect part, they will always be taken care of financially. So what about love and trust? If you are so bold as to go to a school which specializes in exploiting others, then you probably don't care too much about fidelity.

Bottom line: these financially contingent relationships will work -- just as long as both parties don't actually care about being "in love." Love makes things too emotional, too messy, and it can often get in the way of any successful gold digging business transaction.

Other thoughts:

According to Forbes' most recent Rich List, there are 1,011 billionaires. Within this ultra elite group, 89, or roughly 9 percent, are women.

And though the number of female millionaires has increased in the last five years, they still represent the minority of high earners. Daily Finance reports that as of 2010, nearly 27 percent of the millionaires' club is composed of women.

While a few of these ladies have earned their own fortunes (e.g.,Oprah), the majority of these women are wealthy thanks to [hefty divorce settlements and inheritances](https://money.cnn.com/magazines/moneymag/moneymag_archive/2007/07/01/100116670/). Which isn't necessarily a bad thing, but another question is: why are most women still waiting for someone else (usually, a man) to make them rich, instead of doing it themselves?