---
title: The Halo Effect
author: Guanghua Mao
date: '2020-09-17'
slug: the-halo-effect
categories:
  - Business
  - Insights
  - Decision Theory
tags:
  - Book
  - Personal
  - Business
---

# Delusion One: The Halo Effect

>The tendency to look at a company’s overall performance and make attributions about its culture, leadership, values, and more. In fact, many things we commonly claim drive company performance are simply attributions based on prior performance.


---


# Delusion Two: “The Delusion of Correlation and Causality”

>“Two things may be correlated, but we may not know which one causes which. Does employee satisfaction lead to high performance? The evidence suggests it’s mainly the other way around — company success has a stronger impact on employee satisfaction.”


---

# Delusion Three: The Delusion of Single Explanations

>Many studies show that a particular factor — strong company culture or customer focus or great leadership — leads to improved performance. But since many of these factors are highly correlated, the effect of each one is usually less than suggested.


---

# Delusion Four: The Delusion of Connecting the Winning Dots

>If we pick a number of successful companies and search for what they have in common, we’ll never isolate the reasons for their success, because we have no way of comparing them with less successful companies.



---

# Delusion Five: The Delusion of Rigorous Research

>If the data aren’t of good quality, it doesn’t matter how much we have gathered or how sophisticated our research methods appear to be.

---

# Delusion Six: The Delusion of Lasting Success

>Almost all high-performing companies regress over time. The promise of a blueprint for lasting success is attractive but not realistic.

---

# Delusion Seven: The Delusion of Absolute Performance

>Company performance is relative, not absolute. A company can improve and fall further behind its rivals at the same time.

---

# Delusion Eight: The Delusion of the Wrong End of the Stick

>It may be true that successful companies often pursued a highly focused strategy, but that doesn’t mean highly focused strategies often lead to success.

---

# Delusion Nine: The Delusion of Organizational Physics

>Company performance doesn’t obey immutable laws of nature and can’t be predicted with the accuracy of science — despite our desire for certainty and order.


