---
title: 亿万富翁“生死劫”
author: Guanghua Mao
date: '2020-09-17'
slug: ''
categories:
  - Translation Articles
tags:
  - Personal
  - Business
  - Economics
---

>**只有在潮水退去的时候，你才知道谁在裸泳**

# 2008 金融危机

### 1.阿道夫·默克勒： 迟到的贷款协议

　　他是德国的第五大富豪，其名下资产超过90亿美元，他在2008年福布斯富豪榜中排名94位，被称为“德国的巴菲特”，甚至一度被认为是德国工业精神的“象征”。可就是这样的一位传奇人物，竟然在74岁高龄，在全球金融危机的逼迫之下，以卧轨自杀完成了人生的救赎。

　　阿道夫·默克勒(Adolf Merckle)出生于1934年，从祖父手中接过产业后，他依靠自身的踏实与努力，将一个只有80名员工的药厂一步步打拼成为一家拥有10万名员工、年销售额达400亿美元的工业集团。该集团经营内容十分广泛，从制药业到水泥生产均有涉及，而且资产中不乏一些著名企业，如德国最大的水泥制造商海德堡水泥公司、主要生产非专利药的通益药业有限公司、药品批发商菲尼克斯公司和投资公司VEM等。

　　金融危机爆发以来，默克勒旗下的几家公司均出现危机：原本就因为2007年收购行为而资金紧张的海德堡水泥在金融危机下雪上加霜；最引以为傲的通益药业和菲尼克斯公司在申请银行贷款时不得不被抵押；因为没有预料到保时捷收购德国大众，默克勒大举做空德国大众的股票，致使投资公司VEM蒙受巨大损失，据路透社报道，该公司外债高达50亿欧元。

　　一手经营的商业帝国摇摇欲坠，令默克勒心急如焚。然而，作为一个在商界打拼40余载的老将，更让他绝望的却是面对这种情况时的束手无策。2008年11月默克勒向其家乡巴登-符滕堡州政府寻求帮助，遭到拒绝。“默克勒生命的最后几周一直在寻求银行贷款，他辗转于包括AG商业银行、德国AG银行、苏格兰皇家银行和巴登-符滕堡州的兰德公众银行在内的40家银行间，以期取得贷款以避免VEM倒闭。”

　　2009年1月5日，进入新年后的第一个星期一，忙碌了一天的默克勒依然没有为自己经营半生的企业筹到救命钱，孤独无助的他选择了离开。

　　第二天，他的家人发表简短声明，向外界解释道，“由于家族企业集团因金融危机陷入困境，加上最近几周与此相关的不确定性，还有无力回天的无助感，击垮了这位充满激情的家族企业家，因此他结束了自己的生命。”

　　就在声明发表的第二天，一笔数额约为4亿欧元的过桥贷款被获准发放给VEM公司。如果这场“甘霖”早两天到来，是不是就可以避免默克勒悲剧的发生？上穷碧落下黄泉，两处茫茫皆不见。


### 2.斯蒂芬·古德：微笑者的离去

　　就在默克勒自杀的几个小时前，美国芝加哥的一位富豪——美国地产拍卖商斯蒂芬·古德(Steven L. Good)也用一声枪响结束了自己的生命。

　　与默克勒相同的是，斯蒂芬·古德也是子承父业，也同样把一家小企业做成了行业翘楚。古德的父亲1965年创办了谢尔登·古德拍卖公司。自公司创办以来，该公司成功进行了数万起房地产拍卖，收入超过95亿美元，成为美国最大房产拍卖商之一。现年52岁的古德去世前是该公司的董事长兼首席执行官，据公司网站透露，经古德之手的业务额高达40亿美元，遍布商业、工业、租赁等各个领域。

　　不过，与古板低调的德国富豪不同的是，这位美国地产拍卖商不仅是位商人，还是位畅销书的作家。古德曾经出版过一本名为《教堂、监狱、金矿——地产经济界初生牛犊的百万交易》的书，在书中，古德慷慨地向人们介绍了他是如何将一家小的拍卖行做成房地产拍卖界的“索斯比”，此书甚至被美国国家拍卖协会的发言人盛赞为“地产拍卖界的必读之物”。

　　除了是一名成功的地产拍卖商和作家之外，古德慷慨的性格和乐于合作的态度也深得他人喜爱。一位昔日的同事评价古德称，“任何了解他的人都深知他的领导能力、他的慷慨。他总是那么活跃积极，一直微笑着，我怀疑没人能解释为何他会选择这样的方式结束生命。”

　　古德上个月曾在一份有关行业前景的文章中说，市场形势“非常严峻”，“由于商业借贷紧缩以及就业市场萎靡，商业领域的投资停滞不前”，除此之外，外界找不到任何他轻生的理由。可是，这样一位乐观的人也选择了放弃生命。2009年1月5日清晨，在一片森林中自己的红色捷豹座驾上，当古德将枪口对准自己时，他还带着人们熟悉的那份笑容吗？
　　

### 3.蒂里·德拉维莱切特： 倾覆的“诺亚方舟”

　　如果说古德的离去最出人意料的话，法国基金经理蒂里·德拉维莱切特(Thierry de la Villehuchet)则可说是在劫难逃。因为深陷于前纳斯达克主席麦道夫(参见2008年第54期“人物夜话”)的“庞齐骗局”中无法翻身，这位法国基金经理在自己的办公室中用刀片和安眠药结束了自己的生命。

　　据报道，德拉维莱切特掌管的大约20亿欧元中，投向麦道夫所设基金的就高达15亿欧元，投资比例高达75%。而就在去年，该比例也仅有30%。作为一名经验丰富的基金经理，为什么德拉维莱切特会把大部分鸡蛋放在同一个篮子里，又是为什么会在危机来袭时突然把这个比例大幅提高呢？据德拉维莱切特的兄长解释，德拉维莱切特大幅提高投资于麦道夫基金比例，是因为“在其他对冲基金纷纷倒闭的时候，麦道夫管理的基金似乎提供不错的回报”。“麦道夫是他非常信任的基金经理”，德拉维莱切特一名助手也表示了他对麦道夫的信任。如此看来，德拉维莱切特甚至已将麦道夫视作金融危机下的“诺亚方舟”了。

　　因此，可以想象当德拉维莱切特得知他最信任的基金经理竟是个大骗子，自己管理的75%资金将因为麦道夫骗局而灰飞烟灭时，他的心情会如何。德拉维莱切特的一名朋友说，他几乎“崩溃”，担心客户把他告上法庭。法国《论坛报》援引德拉维莱切特一名助手的话报道说，麦道夫丑闻曝光后，德拉维莱切特“无法应对随之而来的压力”。德拉维莱切特自杀后，并没有留下任何有关自杀原因的信件或文字。不过，在他采取行动前，其哥哥收到他的一条短信，德拉维莱切特在短信里表达了自己的压抑及对客户不可推卸的责任。“他觉得他应该为此负责任，他觉得自己有罪”，德拉维莱切特的哥哥在接受《纽约时报》采访时说，“在当今的金融业界，很少人有他这样的责任感，没人愿意承担责任。他是为荣誉而死。”
　　
　　

### 4.特里克·罗卡：身在福中无福享

　　特里克·罗卡(Patrick Rocca)拥有世人羡慕的一切：他年青有为，虽然只有41岁，但2007年统计他的身家即已达到近50亿英磅；他社交广泛，虽然年轻，却是爱尔兰知名的富豪，不仅如此，他还与多位国际知名人士私交甚笃：前美国总统克林顿无论何时来爱尔兰打高尔夫球，坐的都是他的直升机；前英国首相布莱尔曾是他的座上嘉宾；英国版《谁是接班人》影集的大亨Alan Sugar是他的网球球友；他家庭幸福，生活富足，拥有漂亮的太太和3个乖巧的女儿，他的妹妹曾当选“爱尔兰小姐”，并嫁给了爱尔兰著名音乐家Van Morrison。可是，即使这样令人艳羡的生活也没能阻止罗卡扳动手中的扳机，2009年1月19日，趁着妻子送女儿上学的时间，他在家中用一颗子弹结束了自己年轻的生命。

　　事发后，整个爱尔兰为之震惊，“他的突然离去对整个都柏林都是沉重的打击。”《英国每日电讯》如是评论。《泰晤士报》则写道，“罗卡的离去就像一些爱尔兰银行财富的蒸发一样，又迅速又戏剧化，比如盎格鲁-爱尔兰银行。”据爱尔兰多家报纸指出，罗卡选择自杀的主因是由于金融风暴造成包括盎格鲁-爱尔兰银行在内的数家爱尔兰银行获利一夕之间成为幻影，而罗卡在这些银行中砸下了巨额资金。其不愿具名的友人表示，“就我所知，罗卡有逾200万欧元的贷款与盎格鲁-爱尔兰银行密切相关”。

　　在金融危机中，爱尔兰4家上市银行的股价均大幅下跌。其中，盎格鲁-爱尔兰银行股价跌幅最大，相较2007年年中时31.3亿欧元的市值，如今该行的市值已大幅缩水至2.35亿欧元以下。2008年，盎格鲁-爱尔兰的市值累计蒸发98%。银行高层也频频爆出各种丑闻，继该行董事长菲兹帕特里克(Sean Fitz Patrick)隐瞒股东向银行贷款8700万欧元的丑闻曝光后，该行首席执行官和财务总监也宣布辞职。至此，该行在困境中不能自拔，股价创下19欧元新低。很快，这家建于1964年的老牌银行便被爱尔兰政府国有化了。“该银行收归国有的消息对他造成了极大震撼”，上述罗卡友人对爱尔兰媒体称。
　　
---

# 骗局制造者


据媒体报道，如今一些此前全球最知名的亿万富翁已经宣布破产，造成这些巨富一无所有的原因很多，比如经济衰退、糟糕的投资选择，以及让他们陷入困境的大规模欺诈案件。在这些破产的亿万富翁中，有些人已经卷土重来变得和从前一样富有，更多的人则没能重获自己曾经拥有的财富。


### 1.弗吉尼亚女富豪特丽夏·克鲁格（Patricia Kluge）



克鲁格通过同媒业亿万富豪约翰?克鲁格（John Kluge）的离婚而拿到了总计超过10亿美元的分手费，她随后把大笔引人注目资金投资到自己的葡萄庄园里。然而，当房地产市场崩溃时，她失去了一切，甚至不得不在拍卖会上卖掉自己的珠宝和艺术品。

克鲁格曾是一名女继承人和模特，她在纽约旅行时遇到了自己的第二任丈夫、身价50亿美元的约翰?克鲁格，两人在1981年结婚。9年后，这对夫妇离婚了，帕特丽夏?克鲁格（Patricia Kluge）获得了一笔每年高达100万美元的巨额和解金，外加他们在阿尔伯马尔（Albemarle）的庞大房产。阿尔伯马尔位于弗吉尼亚州的乡村，这一房产最终导致了帕特里夏?克鲁格财富的没落。

事实上，在2008年的房地产市场危机前，克鲁格还一直过着上流社会的生活。

但为了把自己的财产变成一项有利可图的生意，克鲁格和她的第三任丈夫在阿尔伯马尔附近960英亩的土地上开办了“克鲁格庄园酿酒厂和葡萄园”。一时间，她曾收获了短暂的成功，克鲁格的葡萄酒甚至出现在切尔西·克林顿（Chelsea Clinton）的婚礼上。

然而就在房地产市场崩盘前，克鲁格进行了一系列糟糕的投资，并将大量资金投入了自己的房产，克鲁格也因此失去了一切。

克鲁格随后拍卖了自己的所有精美珠宝和其他财物，试图免于破产，但这并没有奏效，她本人最终于2011年6月申请破产保护。

### 2.爱尔兰前首富肖恩·奎恩（Sean Quinn）



奎因曾是爱尔兰首富，但由于对爱尔兰一家银行的不良投资，奎因被迫交出了自己大部分资产。2011年11月，奎因在申请破产时声称自己的资产还不足5万英镑。

生涯早期，奎因通过在塑料、玻璃和酒店等行业的投资获得了巨大的成功。2008年爱尔兰债务危机爆发前，《福布斯》杂志估计奎因净资产为60亿美元，列爱尔兰个人财富榜第一名。他还持有盎格鲁-爱尔兰银行25%的股份，该银行在2008年金融危机期间不得不接受纳税人的救助。随后银行被政府接管，奎因家族也因此欠下巨债，并和银行之间开始了一系列的法律纠纷。

英国2011年报道称，奎因声称自己的资产已不足5万英镑，并表示已申请破产。


### 3.前纳斯达克主席伯纳德-麦多夫（Bernard Madoff）



如今的麦道夫坐拥美国史上最大庞氏骗局头目的恶名，导致投资者累计损失约650亿美元，且几十年来一直未被发现。2008年，麦道夫被控11项欺诈、洗钱、作伪证和盗窃罪名，被判最高150年监禁。

麦道夫是金融行业的老手，在丑闻曝光前他一直没有引起人们的注意。案发前，他和妻子的个人净资产在8.23亿美元至8.26亿美元之间。

他在1960年创立了自己的华尔街公司伯纳德-麦道夫投资证券公司（Bernard L. Madoff Investment Securities），并曾担任纳斯达克市场主席。

大约从 1980 年代开始，麦道夫以明星基金管理人的形象，不断伪造回报率以吸收投资，同时以新钱抵旧债，制造投资成功的假象，从而把“生意”越做越大。而且，他从来不说明自己的投资方法，也不解释他是如何利用投资者的资金获得回报。不论市场好坏,他每年都可以支付10%以上的投资回报利润。他曾经有一次说:“这是通过恰当的投资策略产生的，我不能予以详细解释”。

当时，麦道夫的客户包括富豪、对冲基金、大型机构投资者甚至欧洲的一些银行。在很多投资老手们看来，向麦道夫的公司投资，他们担心的不是损失金钱，而是损失赚钱的机会。

这个骗局一直持续到了2008 年，在金融危机之下，大量投资者同时要求赎回资金，直到麦道夫再也拿不出钱，他的巨额庞氏骗局开始解除。经亲口承认，他的两个儿子向当局举报了麦道夫。麦道夫后来以金融诈骗被判处 150 年监禁，两个儿子则先后自杀和病逝。

入狱前，麦道夫与检察官达成协议交出了他的大部分资产。作为交换，他的妻子露丝·马多夫得到了250万美元，她后来搬到了康涅狄格州的老格林威治生活。


### 4.硅谷史上巨骗、“女乔布斯”伊丽莎白·霍尔姆斯（Elizabeth Holmes）



伊丽莎白·霍尔姆斯曾是硅谷一颗冉冉升起的明星，净资产达50亿美元，旗下血液检测公司Theranos估值90亿美元。然而，媒体很快就发现Theranos的血液测试非常不准。霍尔姆斯也于2018年6月被控欺诈，目前净资产为0美元。

2003年，作为一名大二学生的她从美国斯坦福大学肄业，并用大学期间积攒的钱创办了一家名为Theranos的血液测试公司，号称只需要一个针眼和一滴血以及廉价的检查费，就可以做上百种不同的身体化验。

在21世纪初，Theranos作为一个令人兴奋的投资机会获得了广泛关注。到2004年底，该公司已从私人投资者那里筹集了约600万美元，其中一些人与霍尔姆斯有着密切的私人关系。同时，霍尔姆斯在30岁那年首次登上《福布斯》全球400位最年轻女富翁行列。

然而，随着围绕Theranos的传言越来越多，有关该公司做法和监管规定的猜测也越来越多。2012年，霍姆斯试图让中校戴维·舒梅克（David Shoemaker）同意在军队进行一次实验，后者向美国食品和药物管理局提出了自己的担忧。美国医疗保险和医疗补助服务中心（CMS）随后对该公司进行了检查，他们被告知“该设备仍在开发中。”

2016年，CMS得出结论称“Theranos的血液检测可能对患者构成安全风险”。在经历多次诉讼、裁员和联邦政府指控霍姆斯实施了“大规模欺诈”后，Theranos最终于2018年9月关门大吉，勉强避免了破产命运。霍尔姆斯和合作伙伴桑尼·巴尔瓦尼（Sunny Balwani）被美国司法部指控欺诈。根据《福布斯》公布的数据，如今霍尔姆斯的个人净资产为0美元。


### 5.斯坦福金融集团（Stanford Financial Group）前董事长艾伦-斯坦福（R Allen Stanford）



作为美国历史上第二大投资者欺诈案件的主脑，斯坦福金融集团因其不正当的商业交易和骗取1.8万多名客户的钱财而臭名远扬。与麦道夫案的受害者不同，斯坦福金融集团的许多受害者尚未获得赔偿。

斯坦福的罪行始于他拥有一家德州健身俱乐部的破产，大学毕业后的斯坦福开了一家健身会馆，但因生意不好而被迫关闭。随后的他开始转向离岸银行业务，开始实施他的计划。据媒体报道，斯坦福金融集团的许多受害者都是退休人员，他们得到的是斯坦福“安全投资”的承诺，这也使得这起投资者欺诈案件的性质变得更加恶劣。

2009年2月17日，美国证券交易委员会突击搜查斯坦福金融集团休斯顿总部时，以“大规模持续欺诈”的罪名指控这位大亨及其同伙。调查称，斯坦福金融集团一直在欺骗投资者，为斯坦福奢华的生活方式提供资金，最终导致投资者损失了70亿美元。

最终，斯坦福在2012年被判有13项重罪，目前正在佛罗里达州一所戒备森严的监狱服刑110年。然而，斯坦福这一犯罪活动的后果依然严重，因为他的受害者在该计划实施的数年里均遭受了数百万美元的损失。同时，《福布斯》列出斯坦福如今的净资产为0美元，根本无力偿还投资人的损失。


### 6.前巴西首富埃克-巴蒂斯塔（Eike Batista）



巴蒂斯塔曾经梦想成为全球首富，然而他的这一梦想随着曾经繁荣的海上石油公司OGX在2013年的破产也随之破灭了。

这位白手起家的亿万富翁因其奢华的生活方式而广为人知，并成为巴西年轻一代顶礼膜拜的偶像。2012年，巴蒂斯塔身价约300亿美元，成为世界第七大富豪。

但当巴蒂斯塔的石油公司打出的油井一点油都没有采出来，造成了债务和投资者信心危机后，这又波及到了他名下的其他生意，导致他被迫在2013年申请破产。2014年启动的震撼整个巴西石油界的大规模反腐败行动更是让他雪上加霜，巴西当局在2017年1月指控巴蒂斯塔涉嫌洗钱和幕后交易。2018年7月，他因贿赂里约热内卢前州长塞尔吉奥·卡布拉尔（Sergio Cabral）被判30年监禁。