---
title: No Economic Mess in Texas
author: Wall Street Journal
date: '2020-09-28'
categories:
  - Translation Articles
tags:
  - Business
  - Economics
  - Politics
  - America
slug: '46'
---

# 德州经济安然无恙



### [Source](https://www.wsj.com/articles/no-economic-mess-in-texas-1437433836)

## Abstract

Last week's "beige book" release from the Federal Reserve Bank of Dallas shows that despite the struggling oil and gas industry, the Texas economy is still enjoying moderate growth. Since prices in the oil patch began sliding a year ago, pundits on the political left have been waiting for evidence to declare the Texas model a failure.

---

## Full Text

A funny thing has happened to the economic miracle in Texas that liberals predicted would go bust along with oil prices. America's foremost state job creator of the past decade continues to produce opportunity and employment.

Last week's "beige book" release from the Federal Reserve Bank of Dallas shows that despite the struggling oil and gas industry, the Texas economy is still enjoying moderate growth. Since prices in the oil patch began sliding a year ago, pundits on the political left have been waiting for evidence to declare the Texas model a failure. They're still waiting.

Last month the federal Bureau of Economic Analysis reported that in 2014 the Texas economy grew by a sizzling 5.2%, second fastest in the country after North Dakota's 6.3% and more than twice the U.S. average. That followed 5.5% growth in 2013 and 6.2% in 2012. And 2014 was the year oil prices fell to $53 a barrel in December from more than $107 in June. The Texas rig count in May was down 58% from a year ago.

Liberal Governors, tired of looking bad next to Texas, may have hoped to catch a break as the full impact of cheap oil hit the Lone Star State in 2015. And Texas is creating jobs more slowly this year--1.1% growth through May versus 3.6% in the same period last year. Lower-paying positions in hospitality have substituted for higher-paying energy jobs.

But the overall economic resilience is a far cry from the Texas recessions that followed previous oil busts. Unemployment in the state, 4.3% in May, was still well below the national average of 5.5% that month.

Some credit goes to the foresight of energy companies that made themselves less vulnerable with better balance sheets. In a report specifically focused on the energy capital of Houston, the Dallas Fed notes recent improvement in job growth and says that "refining, petrochemicals and service industries are managing to offset oil-producer woes." Statewide, education and health services employment has also been strong.

Meanwhile in Austin, which has little exposure to the energy industry, business other than government is booming. May job growth surged at an annual rate of 6.6%, including "a significant increase in high-paying scientific and technical services jobs." Texas is now America's top technology exporter, surpassing long-time leader California.

Imagine how the economy of Washington, D.C. would suffer and how high the local unemployment rate would soar if government spending fell by half in less than a year. But Texas is mainly in the business of wealth creation, not redistribution.

The Texas strategy of avoiding burdensome taxation and regulation has attracted a variety of businesses across many industries that have diversified the state economy. Texas still has no personal or corporate income tax. New Gov. Greg Abbott has been annoying the left even more by taking a hatchet to business franchise and property levies. He recently signed into law tax cuts amounting to $4 billion over two years despite the reduced flow of revenue due to falling oil production. This is the opposite of the tax-raising strategy pursued by Illinois, Connecticut, Maryland and New York when revenues decline.

The Texas Governor was in New York urging more businesses to consider moving south and west. And while service businesses of many types are currently growing in Texas, don't expect energy and related manufacturing to stay down forever. Mr. Abbott says that "we are on the cusp of once again transforming the energy world" with new Gulf Coast terminals for exporting liquefied natural gas.

Economic dependence on commodity prices can be a boom and bust proposition, as Canada's Alberta province and Australia are experiencing. But the resilience in Texas is proving again that limiting government is an economic growth strategy for all seasons.

