---
title: 乡亲啊，别把你最好的东西给我
author: 南洋首富
date: '2020-09-18'
categories:
  - Translation Articles
tags:
  - Economics
  - Personal
  - Sociology
  - Chinese
slug: '24'
---


### [Source](https://mp.weixin.qq.com/s?__biz=MzU2NTgwOTE0MQ==&mid=2247483743&idx=1&sn=2507a52a37825303f167a6ff337d6f79&chksm=fcb75bc5cbc0d2d3393ab6a6be686b85d79e8477c06941eab40352bf989235f9d2d93c2a03e4&scene=21#wechat_redirect)

有一个人救了一只猫，那只猫为了感谢救命之恩，每天给恩人叼来一只死老鼠，放在恩人的餐桌上。这是一个知恩图报的故事，说的是那只猫已经把他认为的最好的东西给了你。

我举这个故事，不是为了跟故事的原作者一样给你灌输心灵鸡汤，我的意思是说，你用你以为的最宝贵的东西的招待我，也许适得其反。

每次返乡，我都不大愿意见我的中学同学们。那些已经发达的，或者正在发达中的同学，会给你这个久别家乡的老同学一个最美好的款待。在豪华酒楼订一个包厢，请来一大堆昔日同学，点上一些极其昂贵的菜肴，一顿饭花掉五千元甚至八千元，吃饱了还要唱唱歌。然后有钱的同学抢着买单。

这对我来说是一个尴尬的时刻。我吃了你们的，意味着我欠你们的人情，以后你到我的地方来，迟早我也得请你吃一顿盛宴，而不是在振鼎鸡或者东方既白请你吃一顿人均三十元的便餐。但是我真的没那么多钱，我也舍不得花那么多钱。

你们请我吃的美食，我并不觉得比振鼎鸡更好吃，我不是那种需要吃昂贵食品的人。我几乎对任何食品都充满热爱，这意味着我对任何食品都一视同仁，不论是最近卖到三千元一斤的东海野生大黄鱼，还是价格跌到三块八一斤的鮸鱼，我都同等喜欢，而且觉得他们的味道和营养都是完全同等的。

但是，在鮸鱼还卖五十元一斤的时候，你们可能会请我吃鮸鱼，如今鮸鱼跌价到三块八，你们再也不好意思请我吃鮸鱼了。你们必须破费以表示对我的厚道和尊敬。而我，却似乎欠了你们很多债。

我也吃到过天价的东海野生大黄鱼，凭良心说，我相信那绝对是真品，因为跟我小时候吃过的东海野生大黄鱼味道是一模一样的。那时候粮食供应不足，大米一毛四一斤得凭粮票，而东海大黄鱼七分钱一斤随便买。我上小学的时候，曾靠吃东海大黄鱼为主食而度过饥荒的。我攒的大黄鱼的牙齿有满满的一瓶，是那种一升的棕色玻璃瓶。

所以，当你请我吃三千元一斤的东海野生大黄鱼的时候，我的感觉是花三千元钱吃我小时候吃过的七分钱一斤的黄鱼，但是我却欠了你三千元的债，这对我来说比借高利贷还难受。我也没兴趣喝你们带来的法国进口的或者意大利进口的葡萄酒，我习惯喝国产的十元钱一升的葡萄酒。我偶尔也喝白酒，喝的是十元钱一瓶的衡水老白干。我不觉得一千元一瓶的法国葡萄酒比十元钱的葡萄酒好多少，我真心觉得葡萄酒是越便宜的越好喝。

我更不喜欢你们请我到歌厅唱歌。说真的，你们有些人唱的远没原唱好，你们的嘶吼歌声对我是一种折磨。我不喜欢当众唱歌，因为我唱得难听走调。即使你们不勉强我唱歌，你们自己也闭嘴只听原唱，我也并不喜欢，因为你们点的那些歌，十有八九是我不喜欢的。最后你们买单，我欠人情债。我是受尽折磨还浪费时间陪你们受罪还捞到了人情债。

我也不大喜欢别人送我昂贵的礼物。某朋友因为我帮了他的忙，于是买了一件欧洲名牌的衣服送给我。你要想到我从来不穿这么正规高档的衣服，你浪费了几千元给我买衣服，我不会舍得再花几千元买配得上这衣服的裤子皮鞋和皮带，我又不好意思穿着它配上我的劳保鞋和工装裤，免得看着的人都感到不舒服。所以，你送的衣服浪费了一大笔钱，我把衣服扔在柜子里也是浪费空间，要是把衣服卖了或者转送给别人，又恐怕辜负了你的好意。

其实你们这些喜欢花大钱买人情的人，花钱方面未必比我大方，只是你们撕不下脸来省钱。你们买了单，嘴上一个个挺豪爽，心里未必不肉痛，这又逼得你们做伪君子有伤品德。所以，以后聚餐最好还是按照我的规矩来，找个人均不超过三十元的苍蝇馆子，我白吃你的也不觉得欠你，让我付账我也不肉疼，抢着付账也不见得很有面子。大家做一个心安理得的人，一顿吃完，谁也不欠谁的人情，人生可以幸福不少。

我到贵处旅游，我并不喜欢你们大老远的开车接送我，也不喜欢你们给我安排住的市中心的宾馆。我喜欢一个人逛逛街，喜欢住在随便编一个证件号就可以住的几十元的小旅馆，喜欢半夜三更在黑胡同里钻，喜欢一个人跟民工一起躺在火车站广场，这些都让我感到惬意。而你的安排让我不得不装得自己跟你们一样衣冠楚楚，丧失了人生很多乐趣。

有些话当面不好说，写在这里，你要是自认是我的朋友，记在心里，免得将来我无以回报，只好往你的餐桌上扔死耗子。