---
title: 'Economics: Labor Markets'
author: Guanghua Mao
date: '2020-03-14'
categories:
  - Original Articles
tags:
  - Economics
  - Labor
  - English
slug: economics-labor-markets
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

# The Markets for the Factors of Production

The economy’s income is distributed in the markets for the factors of production. The three most important factors of production are labor, land, and capital.

The demand for factors, such as labor, is a derived demand that comes from firms that use the factors to produce goods and services. Competitive, profitmaximizing firms hire each factor up to the point at which the value of the factor’s marginal product equals its price.

The supply of labor arises from individuals’ tradeoff between work and leisure. An upward-sloping labor-supply curve means that people respond to an increase in the wage by working more hours and enjoying less leisure.

The price paid to each factor adjusts to balance the supply and demand for that factor. Because factor demand reflects the value of the marginal product of that factor, in equilibrium each factor is compensated according to its marginal contribution to the production of goods and services.

Because factors of production are used together, the marginal product of any one factor depends on the quantities of all factors that are available. As a result, a change in the supply of one factor alters the equilibrium earnings of all the factors.

This chapter has explained how labor, land, and capital are compensated for the roles they play in the production process. The theory developed here is called the neoclassical theory of distribution. According to the neoclassical theory, the amount paid to each factor of production depends on the supply and demand for that factor. The demand, in turn, depends on that particular factor’s marginal productivity. In equilibrium, each factor of production earns the value of its marginal contribution to the production of goods and services.

The neoclassical theory of distribution is widely accepted. Most economists begin with the neoclassical theory when trying to explain how the U.S. economy’s $16 trillion of income is distributed among the economy’s various members. In the following two chapters, we consider the distribution of income in more detail. As you will see, the neoclassical theory provides the framework for this discussion.

Even at this point, you can use the theory to answer the question that began this chapter: Why are computer programmers paid more than gas station attendants? It is because programmers can produce a good of greater market value than can gas station attendants. People are willing to pay dearly for a good computer game, but they are willing to pay little to have their gas pumped and their windshield washed. The wages of these workers reflect the market prices of the goods they produce. If people suddenly got tired of using computers and decided to spend more time driving, the prices of these goods would change, and so would the equilibrium wages of these two groups of workers.

---

# Earnings and Discrimination

In competitive markets, workers earn a wage equal to the value of their marginal contribution to the production of goods and services. There are, however, many things that affect the value of the marginal product. Firms pay more for workers who are more talented, more diligent, more experienced, and more educated because these workers are more productive. Firms pay less to those workers against whom customers discriminate because these workers contribute less to revenue.

Workers earn different wages for many reasons. One reason is that wage differentials play a role compensating workers for job attributes. Other things being equal, workers in hard, unpleasant jobs are paid more than workers in easy, pleasant jobs.

**所以人们普遍认为地位高，有面子，有保障的那些工作职位反而会因为这些原因而工资低，比如白领，公务员。难怪我一直很讨厌‘体面’这个说法。体面往往意味着收入一般。**

Workers with more human capital are paid more than workers with less human capital. The return to accumulating human capital is high and has increased over the past several decades.

Although years of education, experience, and job characteristics affect earnings as theory predicts, much variation in earnings cannot be explained by things that economists can easily measure. The unexplained variation in earnings is largely attributable to natural ability, effort, and chance.

Some economists have suggested that more educated workers earn higher wages not because education raises productivity but because workers with high natural ability use education as a way to signal their high ability to employers. If this signaling theory is correct, then increasing the educational attainment of all workers would not raise the overall level of wages.

Wages are sometimes pushed above the level that brings supply and demand into balance. Three explanations of above-equilibrium wages are minimum-wage laws, unions, and efficiency wages.

## The Superstar Phenomenon

Superstars arise in markets that have two characteristics:

* Every customer in the market wants to enjoy the good supplied by the best producer.

* The good is produced with a technology that makes it possible for the best producer to supply every customer at low cost.

---

# Income Inequality and Poverty

Data on the distribution of income show a wide disparity in U.S. society. The richest fifth of families earns more than twelve times as much income as the poorest fifth.

Because in-kind transfers, the economic life cycle, transitory income, and economic mobility are so important for understanding variation in income, it is difficult to gauge the degree of inequality in our society using data on the distribution of income in a single year. When these other factors are taken into account, they tend to suggest that economic well-being is more equally distributed than is annual income.

Political philosophers differ in their views about the role of government in altering the distribution of income. Utilitarians (such as John Stuart Mill) would choose the distribution of income that maximizes the sum of utility of everyone in society. Liberals (such as John Rawls) would determine the distribution of income as if we were behind a “veil of ignorance” that prevented us from knowing our stations in life. Libertarians (such as Robert Nozick) would have the government enforce individual rights to ensure a fair process but then would not be concerned about inequality in the resulting distribution of income. 

Various policies aim to help the poor—minimum-wage laws, welfare, negative income taxes, and in-kind transfers. While these policies help alleviate poverty, they also have unintended side effects. Because financial assistance declines as income rises, the poor often face very high effective marginal tax rates, which discourage poor families from escaping poverty on their own.

**I dislike redistribution because their whole concepts and arguments are foolish.**




















































