---
title: 放弃精巧
author: 南洋首富
date: '2020-09-18'
categories:
  - Translation Articles
tags:
  - Economics
  - Personal
  - Sociology
  - Chinese
slug: '3'
---

### [Source](https://mp.weixin.qq.com/s?__biz=MzU2NTgwOTE0MQ==&mid=2247484632&idx=1&sn=aebb7e0307abf23b6c03d44d3459c12b&chksm=fcb75e42cbc0d754be1cc434d2cb6af714e5e715c32de1519e87e90cf57fed8238804494c9a1&scene=21#wechat_redirect)

偶尔读到这样一段文字：

>一个人无法在力量上显示自己时，就要在精巧上做文章。

一个人缺乏敢作敢为的勇气时，就要在合情合理这个道德品质上做文章。
文字也一样，如果你的思想没有力量，文字就没有可以震撼人的东西。

琴棋诗画的精巧，小资品味的精巧，这些都是因为你没有办法展示力量。

如果觉得写文章需要花力气在词藻上，需要推敲，雕琢，那大体上是一篇不值得写的文章。可能除了外壳一无所有。

文玩就是这样的精巧。格律诗词，对联，书法，各种文人精致文化，都是这样的精巧。

南锣鼓巷是精巧的；丽江是精巧的；那些精心布置的咖啡厅是精巧的。餐具精巧、服装精巧、茶道精巧、婚礼精巧。

没有械斗、没有战争、没有动荡、没有荒芜。你日常唯一需要的刀子，或许只是一把指甲剪。

失去力量炫耀的社会，就会越来越精巧。力量在政府手中，政府不断炫耀力量，而民间不断炫耀精巧。

鹿晗和蔡徐坤不需要胡须，不需要孔武有力，只需要不辨雌雄的精巧。

失去力量而走向精巧的一个例子，是八旗子弟。老舍《正红旗下》写道：

>……按照我们的佐领制度，旗人是没有什么自由的，不准随便离开本旗，随便出京；尽管可以去学手艺，可是难免受人家的轻视。他应该去当兵，骑马射箭，保卫大清皇朝。可是旗族人口越来越多，而骑兵的数目是有定额的。于是，老大老二也许补上缺，吃上粮钱，而老三老四就只好赋闲。这样，一家子若有几个白丁，生活就不能不越来越困难。这种制度曾经扫南荡北，打下天下；这种制度可也逐渐使旗人失去自由，失去自信，还有多少人终身失业。……我们创造了一种独具风格的生活方式：有钱的真讲究，没钱的穷讲究。生命就这么浮沉在有讲究的一汪死水里。

这种八旗子弟的“讲究”，就是今天城市小资的讲究。

中产小资是尴尬的。他们受过良好的教育，这种教育让他们做白领、懂外语、会一些酒桌谈资，而真正的思想、科研、学术，他们望尘莫及。

他们有体面工作，但是随时可能失去。他们有不低的收入，但是面对富豪，觉得自己一贫如洗。

小资是骨子里失去力量和自信的人群，他们的才华、创造欲需要泄放和表演，却没有胆气豪气，只能走向精巧。


红酒，咖啡，爵士乐，小众电影。若是旅游，不妨去尼泊尔徒步，去布拉格逛菜场。


瑜伽、茶道、冥想已经有点俗套，潜水、滑雪和跳伞已经不足以展示品味。

他们嘲笑买奢侈品的土豪是土包子。他们蔑视买地摊货的人没有审美品位。他们同情知识分子的生活缺乏精致情调。面对各种群体，他们总要找回一点优越感。

这种优越感的背后，是自信的丧失。他们没有力量感，时刻处于焦虑之中，唯恐自己被时代抛弃。

他们养孩子特别讲究，以至于流行这样一种说法：“这年头只有穷人才养得起孩子”。


第欧根尼是有强大力量的，所以他不需要任何精巧。他住在木桶，有一张毛毯御寒。他当众自慰，做爱，说话不给面子，让精巧的主流社会很尴尬。

苏格拉底和第欧根尼都不是精致的人，他们掀起一件件精巧的外套，指着下面告诉大家：这里面都是狗屎。

人民的力量是巨大的，乌合之众不仅可以处死苏格拉底和耶稣，也可以毁灭整个社会秩序。

只是一旦不能形成组织，人民就被原子化。有些人喜欢用“身后站着人民”给自己壮胆。当他转身，会发现身后只有一个个原子，连散沙都不如。

人民是什么？杨亘说：今天高喊打到xxx的是人民，明天支持为xxx平反的也是这群人。

人民宁可放走强盗，也要处死耶稣。

对他的信徒，耶稣也很清醒：

耶稣临死前说：



耶稣不需要精巧。他站在广场，气场强大，令伪善者惊恐。他一次都没笑过，只有愤怒和忧伤。他对大众说：你们要悔改，跟我来。

给耶稣施洗的人，是约翰。施洗约翰住在荒野，吃蝗虫和野蜜，过精神洁净的简陋生活。后来他的头被砍下，放在盘子里。



