---
title: 克隆，抑或克累得
author: Zhongjing Liu
date: '2020-10-11'
categories:
  - Translation Articles
tags:
  - Evolution
  - History
  - Sociology
  - Chinese
slug: '52'
---

[Source](https://medium.com/@LiuZhongjing/克隆-抑或克累得-clade-83ef226db248)

传承之术，不外二者。以忠于原版计，自当取克隆；为抗乱耐劫计，克累得居优；略外扰而计繁殖能力，二者相去无几。进化，以度劫为胜，不知优劣，是以克隆种群扫地几尽，舍若干昆虫外，仅存人造果类薯蓣之属，其品种天然退化性，育种家亦无如之何。

梵文之衍生、拉丁之破碎，语言之克累得也。华语则克隆之孤臣孽子，虽韩、日、满、蒙旧字亦不就其范围。方言蔓衍，变异无端，一统者易困，继统者多亡，自然之理。《国史大纲》断-岐、续-统别中西，不易之论。衰周齐楚不通译，百家尚在，秦汉文字一而学统定，其间若有契合。此后华以同质胜，欧以异质胜，合者弱而聩，分者强而慧，正应史伯“和实生物，同则不继”。
        
列国自奋，爱其士而强其民，谋于外也；天下一统，愚其士而弱其民，谋于内也。自由不赖多国体系（政治学之克累得？）而能久存者，古今中西未有。虽罗马一统，亦亡其共和而用东方神皇。吉本叹息：“微北蛮，吾子孙其退化为侏儒乎？”麦考莱曰：“微封建黑暗，顺戴克里先专制一统之制，吾欧其将为中国乎？”所忧正与孔子相反。

近乎孔门者，前有拉丁教士，后有拉丁人文学者。想使大格列高利、伊拉斯谟斯诸贤得行其志，必废封建、破等级，有教无类，拔寒门向学者为官僚以代贵族。于是西欧当有罗马后朝之一统，以古典（基督教）经、（哲人）子典籍取士任官，寒人蛮鄙皆以诵拉丁效罗马为荣身耀乡不二法门。政治克隆术得志，近代世界胎死腹中。豆瓣诸公必为艾南英之续。

当代之克隆术，莫大于国族运动、国语运动，皆方言之天敌。然则行于欧洲，以拼音文字本色，反激小民族主义-文化民族主义。国族国语大兴于十九世纪，芬兰、波希米亚、爱沙尼亚诸方言复活而有文艺勃兴，非偶然也。二十世纪，小族复兴、中欧破碎，皆其顺流之势。其风方劲，苏格兰、威尔士、巴斯克、加泰隆、布列塔尼方言再造文化民族主义方兴未艾。

大国语大国族运动，成效最著者反在远东效颦者。中日韩皆以同质性高、文化创造力疲软闻，然内部比较，华之领先日韩，亦无可疑。

以是观之，繁简之别，不在其美感、文野，而在其同质性。旧体有字无音，不能尽去方言也明，为克累得留一线之机，须知历代诗词文极而弊，皆赖返本以求方言民谣活水而复振，其道无异土豆苹果不取野种杂交，不数代则退化为枳。新体之身兼音字，自命普及文化，实则先否认地方文化有文化资格而后灭度之，实秦火灭度十五国风而官书隶字以吏为师之扩大深化版。问题不在字形，而在官书国语一统普及主义有大碍于华文化基因多样性，必增加其退化机会而削弱其抗病幸存能力。

政治大一统之所利，即文化繁衍力之所患。英语布于万邦、法语不出魁北克，即出此道。人工花园扶持，速其亡也。北美独立，英帝国之大患，英语之大幸。华文化之幸，亦在太宗无力亡韩成祖、未能吞越，其大不幸乃在楚齐特色文化终亡于秦汉。闽语变异，大华国族主义之不幸，华夏世界之幸；吴语垂绝，国语国族之成就，华夏文化之自戕。

物无两大，事无两全，众善不并立，唯有勇有识者择之。