---
title: The Fundamentals of Programming
author: Guanghua Mao
date: '2020-01-09'
slug: the-fundamentals-of-programming
categories:
  - Python
tags:
  - Mac
  - Python
  - Programming
---

# Introduction

Now more than ever, you hear about the importance of STEM education and the need for qualified computer programmers. This article is designed for you, someone who's curious to pull back the curtains and explore the world of computer programming. I'll walk you through your first line of code, explain the core concepts needed to write useful programs, and take a peek at several programming languages along the way. 

---

# 1. Programming Basics

## 1.1 What is Programming?

Programming is the process of converting ideas into instructions that a computer can understand and execute. These instructions are specific and sequential. The instructions we provide to computers need to be specific so that we can get our desired result. Computers are very literal. They try to execute our commands exactly. When we give them bad instructions, we might introduce bugs or even make the computer crash. In programming, a bug is when something unexpected happens, whereas a crash is when your program stops early or freezes. The other characteristic of computer instructions is that they're sequential. The order of the steps will impact your final product. It's all about giving computers the right instructions and the correct sequence of steps to produce the desired result. This is important because programming is just as much about finding errors and preventing crashes as it is about writing the instructions or code that the computer understands.


## 1.2 What is Programming Language?

When you want to provide instructions to a computer, you use what's called a programming language. There are hundreds, if not thousands, of programming languages available, each made up of its own syntax, or rules, and semantics, or meaning. Now you may be wondering, what's the point of having so many different languages, especially if they do the same thing? Why not just have one programming language and we all use it? The main reason why we have so many languages is that each comes with its own set of strengths and weaknesses. Regardless of the language you choose, ultimately, that language has to be broken down into the only one that computers understand, machine language. Machine language is extremely complex for us to write directly because it's mostly just a series of numbers. This is why we have these other languages that we call high-level languages. They're closer to human languages, comprised of **keywords, structure, and syntax** that's easier for us to learn and understand.

## 1.3 Writing Source Code

Writing source code is what programmers do all day. It's the instructions we have for the computer, and it's written in plain text. You can use text editor rather than word processing applications. Now that we know how to write our code, we need to learn how to translate it into the language that the computer speaks. Machine language. This is a vital step to get it running on any device.

## 1.4 Running Your Code


There are three main ways to translate source code into machine code: compile it, interpret it, or an combination of both. They perform complex functions that help to optimize the size, speed, and security of your source code, but it helps to convey the general idea of how they differ. Typically, languages like C, C++, and Objective-C are known as compiled languages, whereas PHP and JavaScript are known as interpretive languages. And finally, Java, C# and Python use the combination approach. Nowadays, the line between compiling and interpreting is a bit blurry, as many languages have some variants of both. The key thing to keep in mind, is that you may need to perform additional steps to get your code to run on your, or someone else's machine.

## 1.5 Using IDEs

You can write entire programs in simple text editors, but in practice few programmers do. They use enhanced text editors called integrated development environments, or IDEs. IDEs provide features that speed up code development. Programmers love to argue, I mean talk, about which IDE is their favorite. If you have an hour or two to spare, just ask any programmer what IDE they think is best. Then get ready to pull up a chair. IDEs can ease the burden of software development by providing tools to help you write, debug, and run your source code more easily. Ultimately, it's up to you to find one that meets your needs, and you don't mind using it for hours a day.

---

# 2.Programming Syntax

## 2.1 Why Python?

When choosing the language for this article, I had two main requirements. It needed to be popular and easy to learn. As far as being popular, right now, the top five programming languages are Java, Python, JavaScript, C and Scala. That narrowed down the list considerably. But when it comes to ease of learning, both Python and JavaScript have fewer Syntax requirements than the other languages, so let's look at those two. Both Python and JavaScript tend to be more concise. This means it takes fewer lines of code to get things done. They're also easier to understand, as both languages use structuring and wording that are closer to human language. But which one to choose? Well, JavaScript was designed to work with and manipulate webpages, and it continues to be widely used for that very reason, although, it can also be used for non-web applications. Python, on the other hand, was designed to be a general purpose language. You can use Python to create web apps, internal company tools, perform scientific analysis, as well as create games. The Python language has been around for decades, and it's available on multiple platforms including Mac, Windows, Linux and more. It's a great choice for exploring the various concepts that we're going to cover. So for this article, Python is the winner. 

## 2.2 Basic Statements and Expressions

Statements are the building blocks of any program and are the individual actions that you want your program to take. Without statements, there's no program. Each statement can be made up of **keywords, expressions, and operators**. I'll talk more about keywords later. For now, we'll focus on expressions and operators. Operators are symbols that tell the computer to perform an action with some input. You're already familiar with many of the operators that are used in programming from your primary school education. If you're from the United States, you may have been taught the phrase, please excuse my dear aunt Sally as a way of remembering the order of operations or **PEMDAS**. Computer programs are made up of statements, statements that can perform a mathematical calculation, display something to the screen, or even make a choice between two code paths. As we continue to explore the fundamentals of programming, you'll see just how powerful this concept really is.

## 2.3 Troubleshooting Issues

You're not doomed as a programmer what can you do to figure out why your code is acting up? or error you're dealing with. Errors tend to fall into three categories:

* Syntax - Language rules broken

* Runtime - The computer was unable to execute a portion of your code. 

* Semantic - The output of the program is not what you expected.

It's best to slowly review each line of code to see where you have missed providing a set of quotes, parentheses, or a colon. If you meet these errors, the best thing to do is to look it up. My preferred website for doing so is *stackoverflow.com*. You can copy and paste the error message and then look for similar questions to what you're experiencing. When you click on the question, you'll often find a suitable answer. Semantic errors are the most challenging to troubleshoot. and then run your code. That makes it easier to figure out where you introduced the error. Sometimes, these issues pop up from the smallest of mistakes. Just laugh it off and keep moving forward.

---

# 3. Variables and Data Types

## 3.1 Introduction

Writing code typically involves the handling of information. A variable is simply a container for a value. When we run our programs, the computer gives us space in its memory where we can put data that we want to use as a reference for later. This data is called a variable. We declare variables in Python by giving them a name and then setting their value. This is called assigning the value. And this assignment is done with the assignment operator, which is the equals sign - `=`.


Although we're using an equals sign, try not to think of it the same way you did in high school algebra. In programming, the equals sign means I want to take the value on the right and store it in the variable on the left. It doesn't mean the two sides are equal. That's important to keep in mind.

```{python}
age = 12

print(age)
```


we want the variables to represent different data types. A data type allows us to put our variable in a particular category so that the computer knows how much space to give us in its memory. And it generally knows how we plan to use our variable later on in the program. You can check the type of any value or variable in Python by using the type function.

Like all things in programming, there are a few rules that we have to follow when working with variables in Python. First, variable names should contain only letters, numbers, and underscores. And even though numbers are allowed, the name shouldn't start with a number. Second, spaces are not allowed in the name. Third, it's important to know that names are case sensitive. Finally, variables cannot be keywords. These are reserved words that mean something special to the Python interpreter. In general, you want to use short, descriptive names that make your code easy to understand. Naming things takes practice. In fact, it's often cited as one of the hardest problems in computer science. Keep that in mind and be patient with yourself as you get used to working with variables.

## 3.2 Working with Numbers and Strings

Python treats numbers in a few different ways depending on how they're being used and the difference is largely based on whether it's a whole or fractional one. Let's look a few example.

```{python}
2 + 3

2 * 3

2 ** 3

3 / 2

#Without remainder
5 // 2

#only keep the remainder
5 % 2
```

So far, we've only been using whole numbers or integers to do our calculations but in the real world, fractional numbers are a daily part of our lives. In some programming languages like JavaScript, There's no distinction between numbers with and without decimal places. Whereas in most programming languages, numbers with decimal places are considered special and they're typically called floats. A float is any number with a decimal point. It's short for a floating-point number.

```{python}
0.3 + 0.2
```


Let's talk about strings. In programming, whenever we have to deal with text, be it an email address, someone's name, or even an emoji, we use strings. The name comes from the fact that it's a string of characters one after the other. The characters can be letters, numbers, symbols, and even spaces. They're typically represented by beginning and ending quotes. Strings can be passed directly to functions or they can be stored in variables.

```{python}
print("Life is amazing!")
```



```{python}
#one single quote and one double quote
print('She said to him,"you are so cute"')
```


## 3.3 Properly Using Whitespace

Python doesn't care about extra empty lines in your programs, just like most languages. In fact, it's common for developers to add extra empty lines, also known as white space, You can think of it kind of like paragraphs in a book.

```{python}
#print("Hi!")
#name=input("What's your name? ")
#print("It's nice to meet you,", name)
#answer=input("Are you enjoying the course? ")

#if answer=="Yes":
#    print("That's good to hear!")
#else:
#    print("Oh no! That makes me sad!")
```

In the above code, things are squished together. You might find it especially challenging to figure out what this code is going to do, and that's totally understandable. Let's add a few blank lines so that it can be easier to read.

```{python}
#print("Hi!")
#name = input("What's your name? ")

#print("It's nice to meet you,", name)
#answer = input("Are you enjoying the course? ")

#if answer == "Yes":
#    print("That's good to hear!")
#else:
#    print("Oh no! That makes me sad!")
```

Much easier to read. Although in movies, programmers are often depicted as just endlessly typing on the keyboard, we actually spend much more time reading and understanding code than we do writing it. That's why we add white space. between the different elements of our statements.

Hopefully, you were able to pick up on what the input function does. It takes some input from the user, and then it stores it in a variable.

```{python}
#print("Hi!")
#name = input("What's your name? ")

#print("It's nice to meet you,", name)
#answer = input("Are you enjoying the course? ")

#ifanswer == "Yes":
#    print("That's good to hear!")
#else:
#    print("Oh no! That makes me sad!")
```
If we delete the space between if and the answer variable, we will get a warning: invaild syntax. That's because Python expects us to have a space after the if key word. So let's go back and add a space once again after if. Don't worry if you don't understand all the ins and outs of the current code, just keep in mind that most wherever it helps to improve readability. takes white space very seriously, and your code will fail if you don't respect the rules. The good thing is that the more you practice, the more you follow the rules without even thinking.


## 3.4 Working with Comments

Comments are notes to your future self and others to describe what your code does. Right now, we have small programs. We can keep the flow of it all in our heads, but over time as you continue to grow your programming skills, you'll be writing much longer programs. Some may even be thousands of lines of code spread over dozens of files. It would be impossible to keep all of that in your head. By adding comments to your code, you can document the purpose of the different variables, functions, and classes. You can think of them as virtual sticky notes.

Other than serving as reminders for us, we can also use comments to help temporarily ignore some code. Programmers use this technique all of the time. It's called commenting out code.

```{python}
# Greet the user
#print("Hi!")

#ame = input("What's your name? ") # Ask the user their name
#print("It's nice to meet you,", name)

#answer = input("Are you enjoying the course? ")

#if answer == "Yes":
#     print("That's good to hear!")
#else:
#    print("Oh no! That makes me sad!")
```


Comments are a powerful tool for programmers, and as you've seen, we can use them to serve as reminders, provide explanations for other developers, and even help us with debugging code.

---


# 4. Conditional Code

## 4.1 Making Decisions in Code

Any expression that breaks down to either true or false is called a *Conditional or Boolean expression*. But as we've learned, computers don't speak our language. We can't just ask a questions directly the way we have it here. And that's where *relational operators* come into play. We've already worked with several operators, we've used arithmetic operators, like the plus for addition, or the percent sign for modulo. We've also used the equal sign for assignments. Relational operators work with two operands, and they return a value, true or false, based on their relation to each, thus the name.

```{python}
5 == 4

5 != 4

age = 15

age_to_drive = 15

age == age_to_drive

```

## 4.2 Exploring Conditional Code

In the real world, we make decisions based on current conditions all of the time. The most common way for a computer to make decisions is by means of an if statement. An if statement has this general structure. It starts with the word if, that's where it gets its name from, then it checks some condition, and if that condition is true, then it will do the work that you've placed inside of it. 

```{python}
if 5>4:
  print("Everyone knows that")

print("Thank you!")
```


The indentation in Python is very important because that's how the interpreter knows which statements belong to the if. In fact, we have a name for statements that are grouped together this way in programming. It's called a block. This new print statement isn't indented. It's not part of the previous if statement's block.

So far, we've just gone from top to bottom processing every single line only one path, but that's boring and it doesn't give us much opportunity to interact with the user. Now, we know how to switch things up based on some condition and we can start to write much more interesting programs.

## 4.3 Working with Simple Conditions

With if statements, we've discovered a way to add a bit more flexibility and excitement to our programs, but so far, if the condition is false, then we just don't do anything. But typically, we'll want to take some action in this case as well. This is done with the *if-else* statement. It looks very similar to our normal if statement, except that it has the else keyword along with a colon, followed by a code block. In programming, this is called the *else clause*, because you never find it without an accompanying if statement. 

```{python}
plant = "Cacti"

if plant == "Cacti":
  print(plant, "doesn't need a lot of water")
else:
  print(plant, "loves water")
  
print("Thank you!")
```


With if-else statements, we will always execute one of the code blocks depending on the result of the condition test. This makes it perfect for when we need some action to take place in our programs.


---

# 5. Modular Code

## 5.1 Introduction to Functions

Functions make programs easier to read, write, and debug. A function is a block of code packaged together with a name. They're a core feature of all programming languages, yet depending on the language, they may be called subroutines, methods, or some other name, but it's all referring to the same thing, a way to break up your code. In fact, you've already used a few functions like print to show something on the screen and input to get a response from the user. There are hundreds of other functions in Python that we've yet to explore. One key benefit of functions is that they help us to avoid writing the same lines of code again and again. We teach the computer how to do something one time and from then on out, we just call the function by its name and the work gets done. No need to repeat ourselves. Functions save us from having to do tedious error-prone work as programmers.

```{python}
# creat a function
def beautiful():
  print("You are so beautiful!")
  print("I love you.")
  print("I am kidding.")
  
# Calling the function
beautiful()
beautiful()

```


Pretty cool, right? I'm sure you're eager to learn how to take advantage of functions in your own code. Let's get started.

## 5.2 Setting Parameters and Arguments

In programming, we often want to provide different outputs to our users based on some input. Functions allow us to do this, in fact, let's go over to VS Code to see a function that simulates our carwash experience.

```{python}
#set a parameter
def wash_car(amount_paid):
  if amount_paid == 6:
    print("Basic car washing")
  if amount_paid == 12:
    print("Platinum car washing")

#call a argument 
wash_car(12)
```


One thing to note is that sometimes parameters and arguments are used interchangeably, you'll have to rely but don't despair, the key thing to know is that functions have the ability to change their behavior based on their parameters and arguments.

## 5.3 Returning Values from Functions

In Python, when creating a function using the def statement, you can specify what the return value should be with a return statement. A return statement consists of the return keyword and the value that the function should return. eing able to return values from functions is a cornerstone of programming. I can't wait to see what you're able to build with this new power.

```{python}
#creat a function
def withdraw_money(current_balance,amount):
  if (current_balance >= amount):
    current_balance = current_balance - amount
    return current_balance

balance = withdraw_money(100, 50)

if balance > 50:
  print("Thank you!")
else:
  print("You need to make a deposit")
```

---

# 6. Next Step

We're done, congratulations. You now know the fundamentals of programming. You've learned how programs are created using programming languages. You've been able to write source code and run it from your own computer. And you have a foundational understanding of the Python programming language. I hope you feel inspired to keep learning more. At this point the best thing you can do is start practicing. Don't feel that you have to learn everything there is about a specific language or tool before you can get your hands dirty. You need to practice coding on a consistent basis to get better, and to feel more confident. Here are a few ideas to help you get started. Search online for a local meetup group that caters to new programmers. Participate in an online community focused on your chosen language. Create some programs that use the skills you've learned so far. I really enjoyed putting this article together for you, and I wish you much success on your coding journey.





































