---
title: Accounting Foundations
author: Guanghua Mao
date: '2020-01-19'
slug: accounting-foundations
categories:
  - Accounting
tags:
  - Accounting
  - Foundation
---

# 1. What is Accounting?

What exactly is accounting? First, it is quantitative, it is numbers. Accounting is all about numbers. Second, accounting is financial in nature. Third, accounting is meant to be useful. The fundamental purpose of accounting is to be useful. Accounting is a very practical field of study. Fourth, accounting is useful for making decisions. Accounting helps you use information from the past to make decisions in the present to change the future.

In a nutshell, accounting is quantitative, numbers about money to help people make better decisions.

There are four kinds of accounting. First the most fundamental type of accounting is bookkeeping which is the routine gathering of the information, making sure the everything recorded. So **bookkeeping** is gathering information systematically. The second flavor of accounting is **financial accounting**. This is reporting to people outside your organizaiton who might be thinking loaning you money, or investing your company. Summary reports, not the details. The third flavor of accounting is **managerial accounting**. These are the detailed, secret data that individuals use inside their organizations to make detailed decisions. For example, should I raise the price? Should I stop selling shirts and start selling shoes instead? Where should I locate my new factory? Finally, **income tax accounting** is we use to make sure that we are compliance with the law.


---

# 2. Bookkeeping

At its heart, bookkeeping is about collecting information, getting things recorded. Once events are recorded, then we can start organizing these events and start making better decisions. Without bookkeeping, Walmart and Google could not continue to function. Bookkeeping seems mundane, but that's where it all begins. We can use the past to help us make better decisions for the future, but it all starts with getting things written down. That is bookkeeping.

---

# 3. Financial Accounting

Financial accounting involves reporting the summary results of a business or organization to people outside that organization. Accounting allows people to raise money from strangers so that they can turn their dreams into reality. There are three financial reports: the balance sheet, the income statement and the statement of cash flow.

The key external users of financial accounting data are lenders and investors, the people who provide the capital to a business so that an entrepreneur can turn her or his dreams into reality. However, lenders and investors aren't the only external users of financial data. For example, suppliers use a company's financial statements. If I'm going to sell to you on credit, then I want to know if you're going to be able to pay me or not. So, if you're considering entering in to a long-term significant supplier relationship, where you're selling on credit to another company, first thing you're going to do is to get their financial statements and do a little analysis to see if they're going to be able to pay you back. Also, customers use a company's financial statements. Anybody who enters into a long-term relationship with a business wants to know if that business is going to be around in the future. Employees should also look at a company's financial statements. Employees have long-term relationships with companies. Before leaving one job and taking another job with a different company, employees should look at the financial reports of the new company. Competitors also use a company's financial statements.

## 3.1 Balance Sheet 

The accounting equation. Assets = liabilities + equity. If I borrow the money, then liability is the name I give to the source of financing to buy the asset. If the money was invested by owners, I say equity was the source of the money to buy the asset.

What are assets? A formal definition is that assets are resources owned or controlled by a company that will provide probable future benefit. Cash, accounts receivable, inventory are assets. 

The balance sheet lists the liabilities of a company, obligations that will require probable future sacrifice, either by paying assets or by delivering some service. Accounts payable, wages payable, tax payable, long-term debt and unearned revenue are liabilities. The balance sheet is a report as of a point in time. It's often spoken of as being a snapshot.

If the money is invested by the owners, the source of the financing is called owners' equity. Paid-in capital is the amount that owners take out of their personal savings and invest in their business. This amount is also sometimes called capital stock or capital contributions. Another way that owners invest in a business is through retained profits. The amount of dividends represents the amount of profits that owners have removed from the business. Retained earnings are profits keeping in the business.

The balance sheet is not perfect. There are some limitations. First, when you look at the balance sheet, most of the numbers you see are not market values, they're costs. This often misleads people, because when they look at the balance sheet, they think they're seeing market values. The second limitation is worse. Some very valuable economic assets are not reported at all in the balance sheet, especially intangible assets, such as, logos, relationships and names. The intangible assets that a company grows itself, creates itself, organic homegrown intangibles, they're recorded at zero on a balance sheet, and for many companies, these assets are the most important assets they've got. This exclusion of homegrown intangibles can cause a big discrepancy between a company's recorded accounting value and its actual market value.

## 3.2 Income Statement

The income statement tells you how much you've made and how you made it. The income statement is for a period of time.

The income statement contains two items, revenues and expenses. Revenues - expenses = net income. Rvenue is the amount of assets created from the sale of goods or services. Revenue tells us that the company obtained some of its assets through work, through providing value to its customers. Similarly, expenses are the amount of assets consumed through business operations.

Net income is the net amount of assets generated in doing business. Net income is the overall measure of a company's economic performance during the period in question, the month or the quarter or the year. Net income is the one number that summarizes the results of business operations of a company. For large companies, the most commonly discussed net income number is earnings per share. By the way, earnings means the same thing as net income. So, earnings per share is just the amount of net income, divided by the number of ownership shares in the company. Earnings per share, affectionately known as EPS.

## 3.3 Statement of Cash Flow

The statement of cash flows is the baby of the financial statements. The balance sheet and the income statement, they've been around for over 500 years. In contrast, the statement of cash flows first started appearing in just 1988, so it's brand-new in an accounting sense.

The statement of cash flows is a report of the amount of cash collected and the amount of cash paid by a company during a period, a month, quarter, or year. The structure of the statement of cash flows is to separate the cash flows into three categories. Operating activities, those are the things that I do every single day. I'm in the business to conduct operations, that's what I exist for. Investing activities are expanding the productive capacity of my business. Financing activities are getting the cash to do what I need to do. I'm borrowing money and I'm paying it back. I'm getting cash from shareholders and I'm paying them dividends.


These three financial reports, the balance sheet, the income statement, and the statement of cash flows, summarize everything you need to know about a company's financial performance. That is financial accounting.
 



---

# 4. Managerial Accounting
 
Organizations need to use information to make internal decisions. That internal information is the focus of managerial accounting. Think of managerial accounting data as being the detailed, private information that is used internally to make daily decisions. Product cost, break-even analysis, budgets, performance evaluation measures, long-term capital budgeting, outsourcing decisions, these are the kind of internal decisions that are made using managerial accounting data.

People within the organization consider their information needs, create new measures that summarize important aspects of their operations, and proceed to make better decisions. That is managerial accounting. Information tailored to an organization's specific needs to help that organization better plan, control, and evaluate its operations.

## 4.1 Product Costing

One important function of managerial accounting is computing the internal cost of providing our products or our services. Direct materials are the actual stuff that the item is made out of. The direct materials cost is pretty easy to estimate. Direct labor people are the skilled craftspeople who actually do the work. Overhead costs are a bit difficult to figure out. A traditional way of assigning overhead costs is in proportion to the number of direct labor worker hours spent on a specific product or process.

If we don't understand our costs, we don't know how to intelligently set our prices. And if we don't know how to set our prices intelligently, but our competitor down the street does know how to estimate their costs appropriately, then in the long run, our competitors going to beat us.

## 4.2 Break-Even Analysis

Another illustration of a use of managerial accounting is break-even analysis. Break-even analysis is built on the idea of separating your costs into those that are fixed, the $18,000 for the car in this example, and those that are variable, 

## 4.3 Budgets

Budgeting is another important topic in managerial accounting. Budgeting is making systematic quantitative plans on paper so we can see problems before they arise in the real world.

Companies go through these times of cash shortage, individuals go through these times of cash shortage, but if you plan it out, the cash budget gives you a more realistic, meaningful target than just panicking and saying, hey, our cash went down.

Budgets help you see problems in advance. And perhaps solve them in advance before they ever actually happen.

## 4.4 Performance Evaluation

You get exactly what you measure, so you have to make sure you measure the right things. Because employees respond very strongly to performance evaluation measures, those measures are a powerful tool in motivating desire behavior. 

Mission statements show where the accounting measure should be pointing. Just measuring something and holding somebody responsible for that number changes their behavior.

 

---

# 5. Income Tax Accounting

Any large company in the world keeps three sets of books. Of course, there is one underlying bookkeeping system that captures all that data, but then, those raw data are used in different systems to prepare reports and analysis satisfying the different purposes. So, first, there are financial accounting records. Those are the reports that are provided to outsiders, banks, or potential investors. Next, there are the managerial accounting data that we use inside the company every single day. Those detailed data are used to make internal decisions. Third, we use the same broad bookkeeping data to fill out the tax reports to be in compliance with the law of our local governments. These income tax records can be said to be a third set of books. Now, let me illustrate the difference between taxable income and financial accounting income. The idea of financial accounting income, accrual income, is that you don't follow the cash, the money. Instead, you follow the effort. For your financial accounting records, you would report the income this year when you actually did the work. Taxable income, on the other hand, is closer to cash flow. Typically, taxable income is reported when you collect the cash. Good laws are objective, clear, and easily understood. If we're measuring subjective economic values, it's hard to tell who's right or wrong. In contrast, cash flow is very straightforward, so that people can tell whether they're obeying the law or not.

You may have heard the Ben Franklin saying: In this world, nothing can be said to be certain except death and taxes. Taxes have been with us since civilization began. In order to perform essential services, governments need money. That money has most frequently come in the form of taxes.

There are substantial practical difficulties. First of all, what is income? What expenses are acceptable deductions when computing this income? How will the tax be collected? Will the reported income be verified, and if so, how?

Income tax accounting is its own specialized field. With income tax accounting there's an important element of income tax compliance. You have to make sure that you are obeying the law. There's also the element of income tax planning, meaning that you want to try to structure your affairs so that you don't have to pay any more income tax than you are legally required to pay. And of course for you and me, there's just the routine element of filling out our income tax form each year.

Governments consider which activities they want to encourage, and then decide to grant tax deductions for money spent on those things. And if a government really wants to encourage an activity, then they grant tax credits for money spent on those items.

There's ordinary income and there's capital gains income. Ordinary income is just what it sounds like, ordinary income, such as wages, salary, interest on your bank account. Capital gains income arises when you make an investment and the value of the investment increases.

Worldwide and particularly in the United States, capital gains income is typically taxed at a lower rate than is ordinary income. Now we could get in a long philosophical discussion about whether this is right or wrong. Let me just give you the rationale on both sides of the argument. The reason that capital gains income is typically taxed at a lower rate is that the government wants to encourage people to invest. In addition, people say, listen, if I'm going to invest my money in a stock portfolio I already paid tax on that investment money when I originally made it as income. You're going to tax me again when I invest it? On the other side, a very reasonable view is that income is income. There's no difference between ordinary and capital gains income, it's just a different way to make income. Capital gains income should be taxed the same rate as ordinary income. Now those are the arguments on both sides. The fact is that in most jurisdictions around the world capital gains income is taxed at a lower rate. In fact, in some places capital gains income is not taxed at all. 

Here is where a lot of the complex tax shelter arrangements arise. Tax shelters take on many forms. One form is structuring your affairs so that income can be classified as capital gains income rather than ordinary income. Lots of things, both legitimate and shady, have been done to create tax shelters to change the nature of income from ordinary income to capital gains income. People prefer to have income they make classified as capital gains income, if at all possible, so that the income is taxed at the lower capital gains rate.

There is the notion of the tax bracket. Income is taxed in chunks. The first part of income in almost every tax system around the world is not taxed at all. So this is a 0% tax bracket. Income higher than this initial amount is chopped up into pieces, tax brackets. Income in higher tax brackets is typically taxed at higher rates. Income in the lower tax brackets is never taxed at the higher rates that apply to income in the higher tax brackets. 


# 6. Conclusion

Now you might be saying to yourself, I love this accounting staff. I want to know more about accounting.
 
Fortunately, I am going to write many additional accounting related articles that are available on my personal website. You are now a powerful person. Armed with the knowledge of accounting. Best wishes to you.





















































