---
title: 《清醒思考的艺术》
author: Guanghua Mao
date: '2020-03-14'
categories:
  - Original Articles
tags:
  - Personal
  - Chinese
  - Book Review
  - Decision
slug: '9'
---

从对自己留学这一既成事实后悔以来，我便一直好奇自己和家人为何当初做出了如此不理性的决定，又能够通过何种方式避免重蹈覆辙。后来在[神兽之间](https://mp.weixin.qq.com/s/ATh50jtQ-7SerBc2NC56qg)的推荐下，我开始阅读《清醒思考的艺术》一书。

这篇文章既包含了书中的主要内容，也包含了我对本书中概念的进一步阐释和内容的理解。

首先是对‘理性’一词的理解，作者在书的序言部分写到：思维错误是指系统性地偏离了理性的，合乎逻辑的思考和行为。不过这话说了等于没说，何谓‘理性’？何谓‘合乎逻辑’？作者并未进一步探讨这些概念。但这是不能令读者满足的，所以我打算给‘理性’一个专属于本文的定义：没有从可靠的信息源获得信息或者获得可靠信息后，没有用科学的方法做出推断或者有了可靠信息与科学推断之后，没能做出有效的行动；如果要阐述清楚何谓可靠，科学和有效，这文章可就写不完了，接下来的内容会告诉你那些不算可靠，科学和有效。在此我假定了一个人做出决定的过程为：获得信息，做出判断，采取行动。在每一部分人都有可能会犯错，但某些错误是系统性的，即经常且普遍的。所以作者本人认为值得加以整理并公布，也是我愿意花时间读的原因。

---


# 不可靠的信息

## 1. 幸存偏误

幸存偏误显然是信息被高度扭曲。做决策的人们采信了不可靠的信息源，比如商家的宣传，娱乐媒体的头条和成功人士的演讲。幸存偏误扭曲了真实的成功率，让无数愣头青在偏听偏信之后贸然入场，然后是尸横遍野。

**解决办法：永远要问失败率，而不是成功率。**

## 2. 确认偏误

我们过滤掉与我们的现有观点相矛盾（因此被称作反驳证据，不过它缺少合适的德语表达）的新信息。信息不是被扭曲了而是被无意过滤了。

**解决办法：记录自己的所学所思所想，然后反驳自己**


## 3. 权威偏误

权威的出现使得信息被扭曲，我们会不自觉地认为那些位高权重，腰缠万贯，名满天下的人在各个方面都有着更好的判断。事实并非如此。而在中国，权威偏误还体现在家长权威对信息的扭曲，特别是在未成年人做出重要选择的时候，家长们会把自己几十年前的认知带到现在来，以此指导小孩的人生。结果自然是大家受苦。别听父母亲人的，绝对不是情绪化的宣泄。而是让自己选择更加明智的有效武器。

**解决办法：永远去找另一条相反的看法**


## 4. 现成偏误

又是信息被扭曲的例子，人们对易获取的，现成的，重复出现的信息会高估其真实比例。

**解决办法：看看截然不同的想法**


## 5. 故事偏误

人的大脑喜欢故事，但是故事是对现实的扭曲和简化。

**解决办法：学会科学研究**

## 6. 禀赋效应

我们拥有的东西会被我们不恰当的高估。信息扭曲的案例。比如中文系的人会说中文博大精深，买了房的人会坚信房价会涨。

**解决办法：看相反意见**

## 7. 团体迷思

这难道不是现成偏误的一个例子吗？

## 8. 基本特征谬误

即人总是高估人的作用，而忽视了人所处的情景。有意思。会不会政府的作用也被高估了？

**解决办法：多关注情景，少关注人。**

## 9. 自我选择偏误

放大了自我的存在。

## 10. 新手的运气

一开始的成功会被无限放大。

## 11. 认知失调

禀赋效应的一种。我们会合理化自己做出的错误选择。






---


# 不科学的推断

## 1. 选择标准与结果

即便是有了全面且完善的信息，人们仍然有可能做出错误的判断。把选择标准当作结果便是其中之典型。游泳能让身材变好吗？用了化妆品能变得像模特一样好看？上了哈佛就能如同校友一样功成名就？答案当然是否。只有好看的模特才会拍化妆品广告，不用化妆品也一样好看。不过这一问题的解决倒也简单，通过控制变量就可以知道这一推断的可笑之处。所以你还要上MBA课程吗？

**解决办法：统计推断**

## 2. 过度自信

我们总是系统性地高估我们的学识和预测能力——而且高估得很厉害。

**解决办法：认定自己是中下等人？开玩笑。请对所有预测持怀疑态度，尤其是当这些预测是由所谓的专家们作出的。请你在筹划任何事情时都从悲观的角度出发，作最坏的打算。这样你才会真正有机会，更现实一些地判断形势。**

## 3. 从众心理

只要别人做什么我也跟着做什么，我的行为就是正确的。换言之，越多的人认为一个想法正确，这个想法就更加正确，太荒谬了。跟风随大流在学生生涯表现得更加明显，学生们疯狂追逐所谓的好专业，没想明白就考研。

**但我倒觉得在机会成本很低的情况下从众是也没什么，比如去哪吃个晚饭。但一件事机会成本太高那就别从众了。**

## 4. 纠结于沉没成本

**解决办法：别纠结，唯一重要的是现在的形势及你对未来的评估**

## 5. 互惠偏误

吃人的嘴软，拿人的手软。

**解决办法：别欠人情，花钱办事**

## 6. 对比效应

这一部分没看懂，前面说的是人要从边际上思考。后面又提到什么超级名模让女孩自卑。关键问题是对比一定是错的吗？基于错误信息的对比当然是错的，超级名模毕竟是极少的，但社交媒体的大规模宣传使得人们将其在人群中的占比无意识地提高，从而自卑。但对于前面提到的过度自信的人在面对未经扭曲的完整信息时，通过对比后，自卑一下又有何不可呢？

## 7. 事后诸葛亮

没啥好说的

**解决办法：写下你的预测，然后回顾它**

## 8. 控制偏误

控制错觉是指：相信我们能够控制或影响某种我们客观上无法控制或影响的东西的倾向。比如政府想要影响经济走向，可是或许经济本身就是个无法控制的系统呢？

**解决办法：将注意力集中于你真正能影响的少量东西——坚定不移地只关注其中最重要的那些。其他的，听之任之吧。**

## 9. 回归均值

**解决办法：因果推断**

## 10. 结果偏误

我们倾向于以结果判断决定——而不是当时作决定的过程。

**解决办法：记录自己的预测，无论结果好坏，都要回顾自己做出决策的过程和理由。看来因果推断的确很重要**


## 11. 讨喜偏误

无事献殷勤，非奸即盗。其实和前面的**互惠偏误**有点像。这个人不错和这个人销售的东西不错是两码事。但我感觉也不算是偏误，对于机会成本低的东西可以是无所谓的态度。另外作者也犯了错，他并没有论证受‘讨喜偏误’影响的人做出的选择特别差。

## 12. 零风险偏误

没有百分百的安全，想要完全消除风险反而会导致整个系统崩塌。

**解决办法：怀着“没有什么是安全的”想法生活**

## 13. 归纳法

也就是线性思维。人们总是相信以前的趋势总是会延续下去。

**解决办法：相信一切都是暂时的**

## 14. 错误的因果推断

相关性不等于因果关系。不过很多章节都在谈这个。

## 15. 光环效应

一方面成功了，其他方面也会被认为是优秀的。失败的人，哪儿都是错的。

## 16. 替代途径

替代途径是指，所有同样可能发生但没有发生的事情。

**解决办法：别拿通过冒险的替代途径获得的成功太当真。考虑最坏的结果。**

## 17. 预测的错觉

和前面的诸多内容重复，总之一句话，别迷信权威，自己做预测也要写下来，同时看看相反的预测，然后回顾。

**解决办法：别看人们怎么说，看看他们怎么做。**

## 18. 自利偏误

成功归于自己，失败归于外因。这就是自利偏误。和前面的过度自信偏误有点像。

**解决办法：因果推断？低估自己？**

## 19. 联想偏误

和选择标准有点像。

**解决办法：因果推断**

---

# 无效的行动

## 1. 行动偏误

在不明情形下我们会产生要做点什么的冲动，随便什么——不管它有没有帮助。

**解决办法：如果情况不明，请你不要采取任何行动，直到你能更好地分析形势。你要克制自己**

## 2. 不作为偏误

当形势不明、矛盾、看不透时，行动偏误就会插手了。此时我们倾向于做无用功，哪怕没有这么做的合理理由。而不作为偏误的形势大多是一目了然的：今天的行为可以防止未来的损害，但防止损害对我们的激励并不强。

**对人的要求可真高**

## 3. 双曲贴现

及时行乐的诱惑力极大——尽管如此，双曲贴现也是一种思维错误。我们越能控制我们的冲动，我们就越能成功地规避这一错误。我们对我们的冲动控制越小——比如在酒精的影响下——我们就越容易犯这个错误。及时行乐是个好主意——如果每星期一次的话。但天天享受，好像每天都是末日似的，却是不明智的。

**我倒不觉得及时行乐，或者说高估离得更近的好处有什么不好。对于生活在大洪水地区的人来说做任何长远打算都是没有用的，哪为什么不及时行乐呢？延迟满足只适用于那些法治良好的社会。**




---

# 没看懂

## 1. 激励过敏

*不知道作者想要表达什么，或者这和思维错误有什么关系*

## 2. 公地悲剧

*这和思维错误有什么关系？和不理性有什么关系？作者知道自己在写什么吗？*

## 3. 选择的悖论

*再一次作者偏离了书的主题，另外其结论站不住脚。*

## 4. 奇迹

*论述倒是没什么问题，可是和不理性有什么关系？*

## 5. 忽视概率偏误

*作者后面又提到‘我们很难区分各种风险，……，风险很难估计，但又是躲也躲不过但’，所以你想干什么？*

## 6. 稀少性谬误

*案例没有说服力，更重要的是这本来也不是思维错误。按照边际效用的观点，一样东西刚出现时的确给人带来的效用更高，人们也愿意花更大的代价得到它。比如假期的第一天，第一部手机。但对于司空见惯的东西，即使是稀缺或者假装稀缺，也不会有人多看一样，比如现在的小米手机，和跳楼价的服装。*

## 7. 忽视基本概率

*不认同。作者难道不知道什么是条件概率？所谓基本概率就是先验概率。小样本条件下，先验概率当然不会被推翻。后面的案例倒是很认同。*

## 8. 赌徒谬误

*案例没有说服力。基本理论倒是认同，独立事件的发生概率不受其他事件的影响。*

## 9. 锚定效应

*不认同。*

## 10. 规避损失

*不认同。快乐，幸福感这些东西根本没法横向比较。从边际效用上看也不是如此。*

## 11. 社会性懈怠

*没有对财产权的确认和保护才会如此吧。*

## 12. 指数增长

*和思维错误有什么关系？另外，经过多年的宣传，还有多少人搞不清楚呢？*

## 13. 赢家的诅咒

*供过于求当然就是这样。和思维错误有什么关系？*

## 14. 关联谬误

*不认同。*

## 15. 框架效应

*没看懂。*

## 16. 享乐适应症

*作者当真没有学过边际效用吗？*



---

# 总结

根据我一开始提到的关于‘理性’的定义，以及本书所列出的52个思维错误（尽管有些我不认同）。可以讲如何做一个理性的人总结如下：

1. 从可靠的信息源获得信息。什么样的信息是可靠的？未经扭曲的，完备的信息就是可靠的。但在生活中我们所获得的信息都会经过有意识或者无意识的扭曲。有意识的扭曲来自于利益集团的刻意和部分人士的偏见。无意识的扭曲更多来自于人自身的缺陷，人会高估自己，自己所拥有的或曾做出过的选择，身边熟人的想法，大众媒体的宣传，权威人士的看法，广为流传的故事以及人本身的作用。所以对待信息源和信息，人需要对其真实性和完备性做出质疑。另外，永远找出相反的意见看一看。

2. 做出科学的推断。此处涉及的内容很多。总结起来就是因果推断很重要，相关性不代表因果关系；不要高估单个因素，尤其是人或者人组成的团体，的作用；写下自己对于未来的预测，并回顾这些预测；做最坏的打算；不要线性思维。

3. 开展有效的行动。不要形势不明，没想清楚的时候瞎折腾。也不要高估近在眼前的诱惑和风险过早的享受。更不要低估远在未来的风险与收益而不作为。对于机会成本低，潜在风险小，不过度消耗现金流，但未来前景无限的事物。可以尝试做下去。























































