---
title: Everything has a diminishing marginal utility
author: Guanghua Mao
date: '2020-08-13'
slug: everything-has-a-diminishing-marginal-utility
categories:
  - Insights
tags:
  - Evolution
  - Labor
  - Economics
---

As an popular economic concept, diminishing marginal utility is not new. We all know that utility deriving from a product or commodity reduces as more and more we consume of it.

The utility, here, can be defined as a level of satisfaction that we get from a consumption of a commodity. On the contrary it can be defined as lack of desire to consume more of it.

When I look back to the history of competence, I surprisingly find out that almost everything has a diminishing marginal utility. Here are some examples:

Chinese parents believe that investment in education is the best investment. They want their children can get a bachelor's degree from a good university because in their opinion a bachelor means a stable and rich life. This was true 30 years ago. The problem is the labor market in china doesn't need so many bachelors. A bachelor's degree was sacrifice 30 years ago, but it is everywhere nowadays. As a product, there is no employer will give a new bachelor good salaries. The same phenomenon happens in many education-related topics, such as, choosing which majors and whether to gain a master's or phd degree.

English, the most wildly used language in the world, is an important skill that a lot of people are struggling to learn. They believe that the skill must help them earn more money  or get promotion in their career development. That is not true at least in China now. Maybe it is true 20 to 30 years ago.  Let us assume that every Chinese understand English, as Singaporean do. Will every Chinese will get promoted? The answer is clear. Although Singapore, which has the perfect geological position, dominant western culture and efficient political system, is much more advanced than China, even most countries, adults in Singapore has to work day and night with low salaries. Here is a true story. My senior who got his CS master's degree in the US went back to China after graduation. He was hired by a Chinese companies, whose HR didn't ask my senior how his English was. This is the reality. If you were the first 10000 to 20000 English learners in China, you can get promoted. Currently, there are about multimillion English speakers in China. How can you expect the same results of back days? The phenomenon happened in other fields and countries, such as accounting and CS in China,  engineering in India, law in the US and business administration in the world.

Each and Every profession was made to deal with some problem existing in the society. When the profession was at peak, it was a good career and the good news of gaining the skill was widely spread.  But now we have much better alternates and the professionals out there do not provide any unique value. Such as Accountant was created to handle finances because there were no tools like excel and accounting software. Engineers to create stuff but now we have robots to do the same work more swiftly. But the sad part is we are sending our children to join those professions which have lost their charm and expecting the results (monetary) as were of back days. How can you expect that world won’t change? World will keep finding cost effective solutions to the problems. You can’t complain or expect that labours will be appointed in a world where robots can generate 10x results at half of the cost.

Adapting to the changing environment and knowing the actual demand of the industry. Be aware of the changes that are coming in the Industry. How to face the rapidly changing world and be a winner in the future is a huge topic that I am not going to cover in the article. 


In simple words: don't do the same thing and expect the same results.



