---
title: The Case Against Early Retirement
author: Richard W. Johnson
date: '2020-10-11'
categories:
  - Translation Articles
tags:
  - Labor
  - Psychology
  - Sociology
  - English
slug: '58'
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

[Source](https://www.wsj.com/articles/the-case-against-early-retirement-11555899000)


Most people look forward to retirement, a reward for decades of hard work. But like many other pleasures, it may be bad for your health. It may even kill you.

How can that be? How can working longer be good for your health? After all, many people dream of -- and plan for -- retiring early. Strenuous, stressful work can wear people down and damage their health. On the other hand, retirees can relax and reinvigorate themselves. They have time to follow their passions and pursue activities that enrich their lives.

But in our rush to leave the office, we don't realize that retirement also has a downside, especially over the long term. Many retirees indulge in unhealthy behaviors. They become sedentary and watch too much television. They eat too much. They drink too much. They smoke too much. Without the purpose of fulfilling work, retirees can feel adrift and become depressed. Without the camaraderie of their co-workers, retirees risk becoming socially isolated. Without the intellectual stimulation that work can provide, retirement can accelerate cognitive decline.

The problem for researchers is measuring which is the more powerful force -- the joys of a more leisurely life or the downsides. An experimental study, in which researchers randomly force some workers to retire and others to remain in the labor force, would provide the best evidence, but that kind of experiment is impossible.

Instead, researchers have turned to statistical models that rely on factors that affect work but are unrelated to health -- like Social Security eligibility ages, tax breaks for older workers or mandatory retirement rules. Researchers then can determine how health changes when these milestones are reached.

The result: Many of these studies clearly show that health problems intensify after workers qualify for retirement benefits and abate after policies encouraging work are introduced.

# When you're 62

Consider a 2018 study by Maria Fitzpatrick at Cornell University and Timothy Moore at the University of Melbourne, which used administrative data covering the entire U.S. adult population to examine how mortality rates change at age 62, when people can first begin collecting Social Security retirement benefits. After all, death is the definitive indicator of poor physical health, which itself is difficult to measure.

Dr. Fitzpatrick and Dr. Moore found that men are 2% more likely to die in the month they turn 62 than in the previous month. This mortality surge is driven largely by increases in deaths from lung cancer and chronic obstructive pulmonary disease, and risk factors for these conditions include smoking and lack of physical activity -- both of which become more common when people retire. Mortality rates at age 62 increase less for women than men, and the relationship is not as clear-cut, perhaps because age-62 mortality is much lower for women.

More evidence comes from looking at a Dutch policy change in 2009, which introduced a tax break for older workers. It provided workers a 5% bonus at age 62, a 7% bonus at 63, and a 10% bonus at 64. These incentives, which were eliminated in 2013, spurred work by men ages 62 to 64, and had smaller effects on women. Using this temporary policy innovation as a type of social experiment, Alice Zulkarnain and Matthew Rutledge at the Center for Retirement Research at Boston College concluded that delaying retirement reduced the five-year mortality risk for men in their early 60s by 32%. As in the U.S. study, the impact was smaller for women.

The evidence also suggests that retirement can accelerate cognitive decline. The mental exercise that work provides seems to keep people sharp. Learning new skills seems particularly important. By establishing "cognitive reserves," such activities may help the brain become more adaptable and better compensate for age-related erosion in cognitive ability.

Economists Susann Rohwedder and Robert Willis used data spanning the U.S., England and 11 European countries to show that retirement significantly reduces cognitive function. When people retire, they typically get less mental exercise, because work activities are generally more cognitively stimulating than home activities. Retirees may routinely play bridge or do crossword puzzles, but that isn't as intellectually challenging as many jobs. A 2014 study of half a million retired self-employed workers in France found that dementia was significantly less common among those who retired later than those who retired earlier.

# The social network

Another risk for retirees is that leaving the workforce can cause them to be socially isolated. Most workers interact extensively with their colleagues, providing camaraderie and often social support. Although you would think that retirement provides people with additional time to nurture social ties, Eleonora Patacchini at Cornell University and Gary Engelhardt at Syracuse University found that retirement shrinks social networks and the frequency of social interactions. The impact is especially large for women and college graduates. Smaller social networks and social isolation tend to reduce life satisfaction and impair physical and mental health.

It's important to point out that a paying job isn't always necessary to reap the health benefits of work. About one-third of Americans age 55 and older regularly volunteer for community groups and other organizations. Such unpaid activities can involve levels of physical, cognitive and social engagement similar to those in paid employment. Many studies, including a 2019 evaluation of the Foster Grandparent and Senior Companion programs, find that unpaid work, like paid work, reduces depression and loneliness and improves life satisfaction for older adults.

These studies aren't definitive. More research is needed to establish the pathways through which retirement affects health, and to identify which types of workers are most affected. For example, the health benefits of work aren't generally shared by people with especially stressful, boring or physically demanding jobs. Workers in blue-collar jobs, for instance, accumulate health problems more rapidly as they age than workers in less physical jobs and usually experience health gains when they retire.

# Financial fitness

Retirement, meanwhile, doesn't just threaten the physical and emotional well-being of people. In fact, perhaps the biggest downside of retirement is financial. Social Security replaces only about 40% of a typical paycheck. Employer pensions are much less common today than in the past, and relatively few people have saved enough in 401(k)s or elsewhere to guarantee a financially secure old age.

By staying on the job, workers can redeem their retirement prospects. Workers who extend their careers can save part of their additional earnings for retirement, and they can accumulate more Social Security credits. What's more, retirement savings don't have to last as long when workers delay retirement.

My Urban Institute colleagues Barbara Butrica, Karen Smith and Eugene Steuerle have estimated that an additional year of work raises future annual retirement income by 9%, on average. The financial benefits from continued work are even greater for low-income workers because Social Security's progressive benefit formula replaces a higher share of earnings for low-wage workers than high-wage workers. The bottom fifth of earners gain, on average, 16% by working an additional year.

The good news is that many older Americans are working longer. For much of the second half of the 20th century, the average retirement age for men declined steadily, as expanded employer pensions and the introduction of Medicare and early Social Security benefits made early retirement increasingly affordable. Between 1950 and 1993, the share of 65-year-old men participating in the labor force plunged from 69% to 28%. But the trend then reversed, in response to declines in employer pensions and employer-provided retiree health insurance, increases in older adults' educational attainment and changes in Social Security rules. By last year, the participation rate for 65-year-old men had rebounded to 46%.

The trends differ somewhat for women, reflecting changing norms about women's work. Between 1950 and 1993, the participation rate for 65-year-old women edged up 5 percentage points, to 21%, as women of all ages moved into the labor force. The participation rate then surged to 35% in 2018.

Despite these gains, obstacles to work at older ages remain. One is psychological: Many people feel they should retire by a certain age (or earlier), because that is the way it has always been. We should be encouraging older workers to stay on the job for their own health.

What's more, for many older workers the decision to leave a job is not their own. Instead, too many are pushed out of their jobs before they are ready to retire, and end up struggling to find new work with comparable pay. Employers often seem reluctant to hire older workers, because of fears that they are too expensive, lack up-to-date skills, or will retire before employers can recoup the cost of hiring and training them.

Various policy changes could increase older workers' employment. Federal law prohibiting age discrimination in the workplace could be strengthened after a 2009 Supreme Court decision made discrimination more difficult to prove. We could revamp our approach to education and training to prioritize lifelong learning so older workers can keep their skills up to date. And we could invest more in programs and benefits for older unemployed workers, who generally have trouble finding jobs and often stop looking.

By enabling more older workers to stay on the job, these reforms could benefit companies facing shortages of skilled workers. But it could do more than that. It could also save lives.




