---
title: How one 31-year-old paid off $220,000 in student loans in 3 years
author: Emmie Martin
date: '2020-09-19'
categories:
  - Translation Articles
tags:
  - Economics
  - Linguistics
  - Politics
  - English
slug: how-one-31-year-old-paid-off-220-000-in-student-loans-in-3-years
---


### [Source](https://www.businessinsider.com/how-ebony-horton-paid-off-220000-worth-of-student-loans-in-3-years-2017-3)

>Ebony Horton dedicated herself to paying off her student loans as quickly as possible.

Ebony Horton In 2013, Ebony Horton realized she needed to overhaul her lifestyle.

Working an entry-level job in Washington, DC, Horton earned a mere `$`38,000 a year — barely enough to cover her living expenses, let alone make a dent in the more than `$`100,000 she owed in student loans.

"I was struggling to survive," Horton, now 31, told Business Insider. She said she and her boyfriend "had two cars, but I couldn't even afford to get a parking pass for the second car, so it was constantly getting towed. It was just one thing after another."

Between her undergraduate years and going back to school for her MBA, Horton had racked up `$`132,000 in loans, which ballooned to more than `$`220,000 with interest. She deferred them for two years after earning her MBA, but soon they became impossible to avoid. She began educating herself on personal finance — particularly through the books of Dave Ramsey and Suze Orman — and started devising a plan to pay back her loans as quickly as possible.

To make that happen, Horton knew she would have to make changes to both cut costs and boost her income.

She had toyed with the idea of moving back in with her parents to save on rent, and when her father had a stroke in 2013, she knew it was time to make the transition.

Back home in Joliet, Illinois, Horton took a job as an operations manager at the nonprofit her mother runs. The salary was comparable to what she made in DC, but the cost of living was drastically less. She increased her student-loan payments, setting the lofty goal of paying them off entirely in a year.

Horton and her boyfriend tied the knot soon after the move. Horton's mother gave the couple a condo that she had purchased at an auction for $13,000 as a wedding gift. It became crucial in wiping away the hefty student-loan tab.

Horton and her husband lived in the condo for three months, but then they decided to move in with her grandparents down the street and started renting out the condo to bring in extra income.


The income boost made a huge difference — so they doubled down.

Horton's husband had the idea of buying another rental unit to increase their cash flow even more. Though Horton was reluctant at first, she eventually agreed. They ponied up all the cash they could muster for a $42,000 two-unit condo to rent out, allowing Horton to rake in more money to put toward her loans.

The strategy worked so well that the couple ended up purchasing another `$`55,000 unit shortly thereafter.

When Horton's grandparents moved south, she returned to her parents' house, refusing to live in one of her rental properties because they were bringing in extra income.

"I didn't want another setback," she said. "I wanted to put that money toward my student loans."

All told, Horton said she and her husband were putting 95% of their combined income toward Horton's student loans, making payments of roughly `$`10,000 a month.

Horton committed fully to her goal and was willing to make sacrifices to reach it. When one of the couple's cars stopped working, Horton walked or biked 4 miles to work, rather than diverted cash toward buying another vehicle.

"I left a very little amount of money for me — just enough for us to eat off of," Horton said. "I moved in with my parents or I was living with my grandparents. I kept scaling back so that I could pay it off."

In early 2017, the day came: Horton made her final loan payment. In just over three years, she had put a grand total of `$`220,561.21 toward becoming debt-free. Though it took longer than her original goal of just one year, Horton's dedication to repayment is nothing to scoff at.

"You have to stick with it," she said. "You have to be willing to make some very drastic sacrifices, and you have to be creative in the ways that you produce extra income."

Now that her loans are a thing of the past, Horton wants to continue buying and renting out properties; she has her sights set on finding real estate in downtown Chicago. Horton is also writing a book, and she hopes to one day speak to high school and college students about how to take on loans and responsibly pay them back.

While everyone's situation is different — not everybody can move back home, and not everybody will have a small rental property gifted to them — Horton's willingness to ditch an expensive city like DC to move back to the Midwest, cut down living costs, and increase her earning power by purchasing more real estate helped her pay off a mountain of debt in just three years, when it may otherwise have taken a decade or more

To anyone who feels overwhelmed by the prospect of taking on student loans — or paying back any debt they've incurred — Horton has a simple message: "I just want them to feel empowered that they can pay if off. If I can do it, anybody can."





