---
title: 美国中产阶级活到老劳到老
author: FreeTrader
date: '2020-09-19'
categories:
  - Translation Articles
tags:
  - Economics
  - Sociology
  - Chinese
slug: '34'
---

[Source](https://blog.wenxuecity.com/myblog/47609/201111/16093.html)


"The vast majority of baby boomers want or plan to work in some capacity as long as they can. Eighty-four percent of people between the ages of 51 and 70 expect to work after they formally retire, and nearly two thirds say they can't see themselves ever retiring completely, according to a survey by management consulting firm McKinsey Global Institute. The McKinsey analysis also indicated that 60 percent of boomers will need to work in order to maintain something like their current lifestyle."

根据美国人退休协会(AARP)最近公布的一份研究报告，从1991到2007年的16年里，55岁以上的美国人申请个人财务破产的案例急剧上升，并且呈现出年纪越大，破产比例越高的趋势。

报告显示，1991年，在无力偿还债务而申请破产的美国人当中，只有百分之8点2是55岁以上的中老年人。到了2007年，中老年人申请破产的比例上升到百分之22点3。与此同时，65岁以上的老年人申请破产的比例增长了百分之125，75岁以上更老阶层的破产案例更猛增了百分之433。

报告特别指出，2005年生效的一项新法律提高了申请个人财务破产的条件和难度，使得全美国申请破产的绝对数量显著下降。但是即便如此，2007年老年人申报破产的案例还是比1991年成倍增长。

“婴儿潮一代人是美国历史上最大的一个群体，大约有7千7百万人。很显然，当他们接近退休年龄时，全社会承受了很大的压力。他们出生、成长在繁荣时期，即使在经济萧条时他们也没有承受到很大的压力，因此从来就没有学会存钱和理财。”

里士满联邦储备银行理事会主席托玛斯·迈克尔是《当良好退休金不复存在的时候》一书的作者，他在接受媒体采访时表示，美国退休人员协会公布的报告讲述了一个可怕但真实的故事，并且这个故事很可能会每况愈下。他说：“我们面临婴儿潮时期出生的整个一代老人，他们中有百分之55的人没有在经济上为退休做好准备。”

“平均每个婴儿潮家庭的退休存款，如果不算房屋的价值，还不足5万美元。算上房屋等不动产，也就再增加10万美元多一点的财产。这样算起来就很可怕，他们退休几年之后就会用尽他们的存款，然后就不得不大大降低他们的生活水平，而且生活水平降低的程度恐怕是大萧条以来少见的。”

美国退休福利研究所最近也公布了一份退休信心指数的年度调查报告，从另外的角度证实了美国退休人员协会的悲观论断。根据这项调查，过去一年美国人对退休后保持舒适生活的信心从2007年的百分之27降到2008年的百分之18，下降幅度是这项调查创立18年以来绝无仅有的。

如果不懂股票，即使有大量存款在手，也不保险，且看一个例子：

埃伦•明特尔(Ellen Minter)与丈夫杰夫•巴特曼(Jeff Bartman)在耗神劳心、年收入在50万美元上下的科技行业干了30年，最近的一份工作是在德国软件公司SAP AG。夫妇二人都已五十有余，2007年，他们开始为早日退休作准备。他们从旧金山附近搬到了酒乡希斯伯格。他们读了大量关于退休的书。他们极其精确地计算了未来的用钱需求，连想多久在外面吃一次饭都考虑到了。

他们认为，积蓄了几百万美元在手，他们的资产回报率每年只要达到3%就能轻松地提前几年退休。明特斯太太说：“我算来算去。用所有的理财模式都套算了一遍，最后得出结论：没问题，万事俱备了。”

2007年10月，明特尔太太从SAP退休。她在eBay上卖掉了自己上班时穿的香奈尔(Chanel)套装，将雷克萨斯（Lexus)的敞蓬车换成了灵活的大众甲壳虫(Volkswagen Beetle)汽车，并开始画水彩画。2008年1月1日，57岁的巴特曼也从公司退休。当天晚上，他们开了一瓶多年前在法国买的1996年的Cabernet红酒，为未来干杯。

但当他们的股票开始下滑时，满腔喜悦很快就化为乌有，尤其是巴特曼。明特尔太太说：“每天早上喝咖啡的时候，他都会坐在那儿说：‘你知道股市又跌了多少吗？你知道股市又跌了多少吗？’”

到了2月，她听见他不停地打电话，去人才市场转悠，看看有什么机会。巴特曼说，低迷的经济环境加上大选年的种种不确定因素，让他担心起来。他说：“我觉得，嗯，我还可以继续。我觉得应该安然度过这段不稳定的时期－－我要继续工作。”

巴特曼正在面试一份新的技术方面的全职工作。他妻子还是坚持退休。与此同时，这对夫妇表示，已经将投资组合中的更多资金转投较为安全的货币市场基金了。

即便钱多烫手，也挡不住新时代的通胀！一个振奋华尔街的消息是，2011年11月15日，美国债务总额正式超过`$`15T！(http://www.usdebtclock.org/)小布什以前的42届总统，总共才欠债`$`5T，小布什卸任时，弄到了`$`10.3T，是欧巴马竞选总统时的攻击点之一。但在奥巴马手里，仅两年10个月，就弄到了`$`15T。

Wake up, middle class!

Only safe cash flow guarantees retirement!