---
title: Obama’s shameful Afghanistan retreat
author: Frederick Kagan
date: '2020-10-11'
categories:
  - Translation Articles
tags:
  - Politics
  - Sociology
  - English
  - America
slug: '56'
---

> Obama’s shameful Afghanistan retreat: This will embolden the Taliban, Al Qaeda and ISIS

> 从阿富汗的耻辱撤退


[Source](https://www.nydailynews.com/opinion/frederick-kagan-obama-shameful-afghanistan-retreat-article-1.2400776)

The headlines should read: "Obama to slash U.S. troops in Afghanistan by over 40% weeks before he hands over responsibility to a new President." Instead they say: "Obama extends U.S. military presence in Afghanistan." Talk about controlling the narrative.

We're missing the plot here. The President announced on Thursday the most irresponsible decision he could have made about Afghanistan — second only to the promise he had made earlier to pull almost all U.S. troops. The right decision would have been to keep forces at current levels, or, better, send reinforcements.

For we are losing in Afghanistan, again. Security is deteriorating. The Taliban seized and briefly held the capital of an important province north of Kabul. They are threatening another one a short drive southwest of Kabul. U.S. forces destroyed two Al Qaeda training camps in Kandahar, one very large. The Islamic State controls part of Nangarhar Province, east of Kabul. Afghan security forces cannot hold what they have, let alone regain what they have lost.

The Taliban had been driven out of almost all the important areas in southern Afghanistan and disrupted elsewhere by the additional forces Obama sent in 2010. The premature reduction of American and allied troops and the operational restrictions imposed on the remaining troops have let the Taliban rebuild.

A couple of years ago the Taliban would not have dared mass forces for an offensive against a major city, because American airpower supporting U.S. and Afghan troops would have decimated them. No more. Now the enemy masses and maneuvers as they did from 2006 to 2009, when they nearly toppled the Afghan government.

A limited number of American forces with the right authorities could prevent them from doing that. But Obama has chosen to allow the Taliban the freedom of action to threaten the survival of the Afghan state once again.

American forces with Afghan partners drove Al Qaeda almost entirely out of Afghanistan in 2002. U.S., Afghan and allied troops kept them out for a decade — the one enduring success against Al Qaeda President Obama had maintained.

Now they're back. The President has thus put in danger even the most limited of the goals he had identified in Afghanistan.

The emergence of fighters loyal to the Islamic State in Afghanistan is even more disturbing. The vast majority of them are local insurgents who had been fighting under other banners, so it's not as if new forces have invaded Afghanistan. But the ISIS brand is much more virulent, violent and extreme even than al Qaeda. It makes the Taliban look moderate.

That such a group has drawn Afghans under its banner is proof of the failure of U.S. efforts against ISIS broadly. Success attracts followers. ISIS will likely radicalize those followers even further, while preparing to unleash greater violence against Afghan forces and U.S. troops. That will be further proof to potential recruits of its success and power, encouraging radicals elsewhere to join ISIS. It is a disaster in every respect.

The Afghan security forces, meanwhile, are suffering badly. Losses and desertion rates are too high. They lack the equipment to prosecute a modern war against a serious enemy. We built those forces on the assumption that the U.S. and its allies would continue to provide meaningful and reliable air support, help with logistics, planning and intelligence and more. As we have withdrawn that support, they have faltered.

All this was both predictable and avoidable. The President was warned that he had announced too aggressive a drawdown plan in 2009. He disdained recommendations to keep 20,000 or 30,000 troops in place after the drawdown. He is once again disregarding advice to maintain the current — inadequate — force level in favor of scheduling yet another unjustifiable withdrawal.

All Presidents make mistakes. Most come to recognize and learn from them. Others double down. In this case, doubling down on retreat is doubling down on failure.
