---
title: 死心吧，这辈子你不可能开心
author: 南洋首富
date: '2020-09-18'
categories:
  - Translation Articles
tags:
  - Economics
  - Personal
  - Sociology
  - Chinese
  - Insights
slug: '23'
---


### [Source](https://freewechat.com/a/MzU2NTgwOTE0MQ==/2247484737/1)


高君跟我说：一个同学，住200多平江景房，开保时捷帕梅拉，不上班，在家带小孩，过得不快乐 ，也压抑。


开保时捷的人，通常都不快乐。

保时捷是惹人注目的品牌，开保时捷的人通常在乎别人的看法。

不够富裕的人买保时捷，更希望被人认可。

出门开豪车，通过别人眼中羡慕的眼光，可以获得一丝满足。但是，这种满足距离真正的快乐还很远。

如果这辆车占据你很大一部分收入，你会小心翼翼爱护它，稍微刮擦一下都会很心疼，油漆有几道划痕都会马上去修。


即使车子什么问题都没有，也会三天两头想给车子做点美容。

我在大街上看到最随意的车，就是五菱宏光。中国任何一个城市，到处可见刮擦得一塌糊涂的五菱宏光。

外壳撞个坑的，掉一块漆的，沾满淤泥的五菱宏光的车主，似乎并不在意他的车变丑了。他们很少费心打理他的车。

车子不是他的负担，也不是他的炫耀。

如果你钱真的够多，开保时捷也会像别人的五菱宏光那样随意。比如说，有些人家里有劳斯莱斯，还有好几辆其他豪车。

他并不享受开豪车的感觉。开车的是他的司机。

他对豪车没有激情，豪车只是给别人看的。

当地的电视节目里经常可以看到对他的采访。儒雅，豪气十足，妙语连珠，大家都知道他是一个有涵养有文化的成功商人。

但是他并不快乐。

他在几个城市有别墅。但是他每天睡觉的地方很少在自家床上。

有时候，他在会议室的沙发上，在二个会议间隔睡半小时。

他不开车，都是司机开车，因为坐车的时间就是他睡觉恢复体力的时间。

他经常在候机室和飞机上睡觉。有时候在马德里，有时候在亚特兰大，随时要在几个国家飞来飞去。

跟朋友聊天的时候，聊着聊着，他就会在沙发上打起呼噜。

他一天二十四小时，你永远分不清他哪个时间在工作。

一个长年累月睡不够的人，怎么可能幸福？





一旦有客人到，有领导到，他立即振作精神，面带微笑，展示一副自信刚毅的面容。这种强打精神的生活，进一步伤害他的身体。

他做很多项目，每个项目都需要殚精竭虑。每个项目都有无数的陷阱和风险。任何一个合同，他都不敢轻率。

要和不计其数的部门搞关系。虽然你是富人，但是一个很小的公务员都可以给你带来很大的麻烦。所以任何公务员都不敢怠慢。

父亲住院他没空探望。也没有时间陪孩子。

“如果工作只需要996，那该多轻松”。这是他的肺腑之言。

有一次他跟我说：“虽然累，好歹没有被催债，比那些资金链断裂的朋友幸福多了。”

政策和政局的稍微变动，可以让一个亿万富翁顷刻破产，这是现实。

努力的人并不幸福。人之所以努力，是因为对现状还不满意。
如果一个人不断换恋爱对象，那是因为他还没找到让他满足到不需要再换的爱人。

如果一个人不断变换工作，那是因为他觉得自己的工作不够好。

一个人不断读书、进修，那是因为他对自己的学历、学识还不满意。

努力，是因为对自己的状况不满意。对现状不满意的人，幸福感是缺乏的。

不要相信工作是幸福的。若不是为了金钱地位，全世界99%的人应该都会辞职。

普通人之所以工作，是因为他们要追求的东西只能靠工作换取。

有些很努力的人，有了几个亿还在拼命努力，从某种角度看，也可以说是一种精神病。这种病，不妨称之为“事业强迫症”。



他们不是天生上进，而是天生无法满足。说得好听点，叫“永不满足”，说得难听点，叫“欲壑难填”。

物欲满足后，依然有无数别的欲望。比如成为聚光灯明星的欲望，比如扮演武林高手拍电影过把瘾的欲望，比如请大家来听一次他登台演唱的欲望。

比如当青年导师、写书给大家指点人生的欲望。

这是个神奇的时代，人类有史以来从来没有像今天这样富裕。物质资料多得不可思议，大多数人都很容易生存。

生存有多容易？假如果你是个普通人，月薪一万，一个月工资可以买五千斤粮食，足够你吃十年。你的收入，相当于古代一个有几百亩土地的地主。

你买一张高铁的票，速度是千里马的十倍。

很多人衣服多得柜子放不下，新买的衣服一次都没穿，放几年不时尚了，就扔了。

你我生活的年代，一个普通小市民，生活都比古代的大地主舒适，甚至还可以享受到古代帝王都享受不到的电视机、抽水马桶、地铁、高铁、电冰箱、智能手机、电脑游戏。

但是小市民依然不快乐。

人家的孩子上的是米尔谷紫藤幼儿园，那是幼教大师和谷歌幼儿园办的外教上课的双语幼儿园，咱家孩子上的是方言混杂普通话的“双语幼儿园”。

将来，人家的孩子讲一口地道的英语，从华尔街拉投资，到硅谷创业，咱家孩子到处投简历。人家孩子公司的HR，见到不是211、985的简历直接扔垃圾桶。

面对孩子的未来，你能不焦虑吗？——虽然数据告诉你，即使孩子只有高职学历，也已经超越绝大多数中国人。

你以为人家的孩子比你的孩子快乐吗？

告诉你一个可靠数据：美国常青藤大学的自杀率比中国的二本高职这种烂校高十几倍。有心理问题和精神病的概率，也远高于中国烂校。他们的快乐程度，是很低的。

北大清华的学生的快乐程度，也不比二本烂校高。

他们有很多成为成功人士的机会，但是在获得快乐方面，并不比普通小市民更多。

快乐是有诀窍的，而且很简单，就是人人都知道的二句话：



1、关我屁事；2、关你屁事。

别人的成功关我屁事。别人有钱关我屁事。我会饿肚子吗？不会。这是个饿不死人的时代。

别人开保时捷关我屁事。坐公交很可怜吗？并不，比骑千里马还舒服，还不用自己开车。周润发日常就是坐公交的，他不缺钱，但是他不需要任何炫耀，也不会跟别人攀比。

别人买别墅关我屁事？我的房子虽然不大，只有三十平方，可是想想领导人胡先生，xi先生，李先生，他们读大学时住的宿舍，人均居住面积3平方米，我的住房面积已经是他们当年读北大清华时的十倍。

你要为自己的将来考虑呀！——别人会这么警告你。

我的将来关你屁事？也许我还能过得一帆风顺，你却因为投资失败、房价暴跌破产了。

你要为孩子的未来考虑呀！——他们这么说。



我孩子关你屁事？我孩子快乐着呢，还是关心一下你自己的孩子吧，从小被关着读书做题目，将来怎么可能有健康的心理，怎么可能有快乐。

你或许不知道，海淀区的孩子在拼的时候，硅谷精英孩子正流行去乡村养猪养鸭。

英国夏山学校这种完全自由的放养式学校，更是很多知识精英推崇的教育。

你不觉得自己太不上进了吗？——他们这样说。

关你屁事。我活得好好的，只是活法与你不一样而已。





最后，摧毁你的压力，可能是你的亲人，他们痛心疾首，为你的堕落而伤心痛哭。正如流浪大师沈巍，也一定遇到这问题。

这时候，你若是稍微妥协一下，一辈子的快乐就没了。沈巍老师就做得很好，他离家，流浪。谁说他不上进呢，他每年读书的数量，比中国成年人平均读书多一百倍。

所以，如果你不愿被这集体价值观裹挟，最终可能还得众叛亲离。

维特根斯坦出生于欧洲首富家族，劳斯莱斯就是他家的私产，维特根斯坦青少年时代的业余爱好是做飞机发动机玩。但是后来他放弃家产，放弃大学教授职位，去当一个乡村中学老师。

无论沈巍大师，还是维特根斯坦，他们的快乐并不比那些泡浸在金钱里的成功名流少。

释迦牟尼还是王子的时候，完全感受不到快乐，想来想去就是人生是苦。于是他翻墙逃离，出家，终于悟出了解脱之道。
很多人自称没有快乐，那是因为他们根本不追求快乐，而是追求世俗成功和别人的赞许。

