---
title: SUPPLEMENT TO CHAPTER 1 THE THEORY OF NUMBERS
author: Guanghua Mao
date: '2020-01-07'
slug: supplement-to-chapter-1-the-theory-of-numbers
categories:
  - MATHMATICS
tags:
  - Math
  - NUMBERS
---
 
# INTRODUCTION

The integers have gradually lost their association with superstition and mysticism, but their interest for mathematicians has never waned. Gauss, the foremost mathematician of modern times, who devoted himself to many different branches of mathematics, is said to have expressed his opinion of number theory in the remark, "Mathematics is the queen of the sciences and the theory of numbers is the queen of mathematics."

# 1. THE PRIME NUMBERS

## 1. Fundamental Facts

Most statements in number theory, as in mathematics as a whole, are concerned no with a single object-the number $5$ or the number $32$-but with a whole class of objects that have some common property.

Of fundamental importance is number theory is the class of all $primes$. *A prime is an integer $p$, greater than one, which has no factors other than itselt and one*. The importance of the class of primes is due to the fact that every integer can be expressed as a *product of primes*. An integer (other than $0$ and $1$) which is not prime is said to be *composite*.

There are infinitely many primes. The proof of the infinitude of the class of primes are gived by Euclid remains a model of mathematical reasoning. It proceeds by the "indirect method". We start with the tentative assumption that the theorem is false. This means that there would be only a finite number of primes, perhaps very many- a billion or so-or, expressed in a general and non-committal way, $n$. Using the subscript notation we may denote these primes by $p_1, p_2, p_3, …, p_n$. Any other number will be composite, and must be devisible by at least one of the primes $p_1, p_2, p_3, …, p_n$. We now produce a contradiction by constructing a number $A$ which differs from every one of the primes $p_1, p_2, p_3, …, p_n$ because it is larger than any of them, and which nevertheless in not divisible by any of them. This number is 

$A=p_1p_2…p_n+1$.

Although the proof is indirect, it can easily be modified to give a method for constructing, at least in theory, an infinite sequence of primes.

When a number has been expressed as a product of primes, we may arrange these prime factors in any order. The decomposition of a number $N$ into primes is unique: *Every integer $N$ greater than 1 can be factored into a product primes in only one way*. Here we shall give a proof of recent vintage. It is a typical example of an indirect proof. We shall assume the existence of an integer capable of two essentially different prime decompositions, and from this assumption derive a contradiction. The contradiction will show that the hypothesis that there exists an integer with two essentially different prime decompositions is untenable, and hence that the prime decomposition of every integer is unique.


## 2. The Distribution of the Primes































































































































