---
title: 'Economics: Introduction'
author: Guanghua Mao
date: '2020-03-12'
categories:
  - Original Articles
tags:
  - Book Review
  - Economics
  - English
slug: economics-introduction
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

When I started learning economics, I thought economics can teach me to make more money because the word 'economics' implied money in my first look. Undoubtablely, my thought is wrong. Therefore, when I decide to write the introduction article, I need to illustrate what is economics indeed.

According to *The Principle of Economics* by *Gregory Mankiw*. Economics is the study of how society manages its scarce resources. Economists study how people make decisions. Economists also study how people interact with one another. Finally, economists analyze the forces and trends that affect the economy as a whole, including the growth in average income, the fraction of the population that cannot find work, and the rate at which prices are rising.

# Ten Principle of Economics

There are ten principles of economics which are grouped by three types: How people make decisions, How people interact with each other and How the economy as a whole works.

## How People Make Decisions

The behavior of an economy reflects the behavior of the individuals who make up the economy, so I will begin the study of economics with four principles about individual decision making.

* Principle 1: People Face Trade-offs (Operations Research?)

* Principle 2: The Cost of Something Is What You Give Up to Get It (Opportunity cost)

* Principle 3: Rational People Think at the Margin

Economists normally assume that people are rational. Rational people systematically and purposefully do the best they can to achieve their objectives, given the available opportunities. Economists use the term marginal change to describe a small incremental adjustment to an existing plan of action. Keep in mind that margin means “edge,” so marginal changes are adjustments around the edges of what you are doing. Rational people often make decisions by comparing marginal benefits and marginal costs.

* Principle 4: People Respond to Incentives

An incentive is something (such as the prospect of a punishment or reward) that induces a person to act. When policymakers fail to consider how their policies affect incentives, they often end up facing unintended consequences. When analyzing any policy, we must consider not only the direct effects but also the less obvious indirect effects that work through incentives. If the policy changes incentives, it will cause people to alter their behavior.

The fundamental lessons about individual decision making are that people face trade-offs among alternative goals, that the cost of any action is measured in terms of forgone opportunities, that rational people make decisions by comparing marginal costs and marginal benefits, and that people change their behavior in response to the incentives they face.

## How People Interact

The first four principles discussed how individuals make decisions. As we go about our lives, many of our decisions affect not only ourselves but other people as well.

* Principle 5: Trade Can Make Everyone Better Off

* Principle 6: Markets Are Usually a Good Way to Organize Economic Activity

In a market economy, the decisions of a central planner are replaced by the decisions of millions of firms and households.

At first glance, the success of market economies is puzzling. In a market economy, no one is looking out for the economic well-being of society as a whole. Free markets contain many buyers and sellers of numerous goods and services, and all of them are interested primarily in their own well-being. Yet despite decentralized decision making and self-interested decision makers, market economies have proven remarkably successful in organizing economic activity to promote overall economic well-being.

* Principle 7: Governments Can Sometimes Improve Market Outcomes

One reason we need government is that the invisible hand can work its magic only if the government enforces the rules and maintains the institutions that are key to a market economy. Most important, market economies need institutions to enforce property rights so individuals can own and control scarce resources.

We all rely on government-provided police and courts to enforce our rights over the things we produce—and the invisible hand counts on our ability to enforce those rights.

Economists use the term market failure to refer to a situation in which the market on its own fails to produce an efficient allocation of resources. As we will see, one possible cause of market failure is an externality, which is the impact of one person’s actions on the well-being of a bystander. Another possible cause of market failure is market power, which refers to the ability of a single person or firm (or a small group) to unduly influence market prices.

The fundamental lessons about interactions among people are that trade and interdependence can be mutually beneficial, that markets are usually a good way of coordinating economic activity among people, and that the government can potentially improve market outcomes by remedying a market failure or by promoting greater economic equality.

## How the Economy as a Whole Works

We started by discussing how individuals make decisions and then looked at how people interact with one another. All these decisions and interactions together make up “the economy.”

* Principle 8: A Country’s Standard of Living Depends on Its Ability to Produce Goods and Services

What explains these large differences in living standards among countries and over time? The answer is surprisingly simple. Almost all variation in living standards is attributable to differences in countries’ productivity—that is, the amount of goods and services produced by each unit of labor input.

* Principle 9: Prices Rise When the Government Prints Too Much Money


What causes inflation? In almost all cases of large or persistent inflation, the culprit is growth in the quantity of money. When a government creates large quantities of the nation’s money, the value of the money falls.

* Principle 10: Society Faces a Short-Run Trade-off between Inflation and Unemployment.

The fundamental lessons about the economy as a whole are that productivity is the ultimate source of living standards, that growth in the quantity of money is the ultimate source of inflation, and that society faces a short-run trade-off between inflation and unemployment.

---

# Think Like an Economist

Economists try to address their subject with a scientist’s objectivity. Like all scientists, they make appropriate assumptions and build simplified models to understand the world around them. Two simple economic models are the circular-flow diagram and the production possibilities frontier.

The field of economics is divided into two subfields: microeconomics and macroeconomics. Microeconomists study decision making by households and firms and the interactions among households and firms in the marketplace. Macroeconomists study the forces and trends that affect the economy as a whole.

A positive statement is an assertion about how the world is. A normative statement is an assertion about how the world ought to be. When economists make normative statements, they are acting more as policy advisers than as scientists. I dislike the concept that how the world ought to be because how can you make sure that your thoughts are right and meet all requirement of all individuals in the economy and Do you want to shape the world by the standards of heaven? According to my experience in data science, I think the three stages --- descriptive analysis, predictive analysis and prescriptive analysis --- are much better than normative statements because these stages don't impose any value or requirements on the truth.

Economists who advise policymakers sometimes offer conflicting advice either because of differences in scientific judgments or because of differences in values. At other times, economists are united in the advice they offer, but policymakers may choose to ignore the advice because of the many forces and constraints imposed by the political process.

---

# Interdependence and The Gain from Trade

Each person consumes goods and services produced by many other people both in the United States and around the world. Interdependence and trade are desirable because they allow everyone to enjoy a greater quantity and variety of goods and services.  

There are two ways to compare the ability of two people to produce a good. The person who can produce the good with the smaller quantity of inputs is said to have an absolute advantage in producing the good. The person who has the smaller opportunity cost of

producing the good is said to have a comparative advantage. The gains from trade are based on comparative advantage, not absolute advantage. 

Trade makes everyone better off because it allows people to specialize in those activities in which they have a comparative advantage. 

The principle of comparative advantage applies to countries as well as to people. Economists use the principle of comparative advantage to advocate free trade among countries.

**How can I know what my comparative advantage is? Should I try everything in the world? If I shouldn't, How can I know the thing I am doing reflect my comparative advantage?**

---



































































