---
title: 日本政府口出狂言：“50年要拿30个诺贝尔奖”
author: 林小春
date: '2021-08-31'
slug: '278'
categories:
  - Translation Articles
tags:
  - China
  - Insights
---

[Source](http://japan.people.com.cn/2002/01/07/riben20020107_15480.html)

> 剩下的都是历史。弱者无能，强者无敌。

日本在２００１年３月出台的第二个科学技术基本计划中提出，要在５０年内拿３０个诺贝尔奖。在不久前结束的百年诺贝尔庆典后，日本政府重申了这一目标，并在瑞典卡罗林斯卡医学院内设立了“研究联络中心”。这一举动在全世界引起很大反响，毁誉参半，褒贬不一。

获得２００１年诺贝尔化学奖的日本科学家野依良治评论说，日本政府“没有头脑”，纯属“狂妄之言”。不过，也有专家认为如此评论有点失之偏颇。如果与英国对比，诺贝尔奖问世百年中，英国已有８９人获奖，５０年中也远多于３０人。今天，日本的经济和科研实力已居世界前列，５０年拿３０个诺贝尔奖似乎不是大话。



从资金投入上看，尽管日本经济近年来处于低迷状态，但依然是公认的经济大国，因而能够大量投入科研资金。日本２００２年度财政预算总额减少，但科技等领域预算不降反升，近几年的科研经费更达到国内生产总值的３％以上，居发达国家首位。在基础研究上，日本也取得了引人注目的成就。１９９８年，日本科学家发现中微子有静止质量；２００１年，日本科学家找到了宇宙中存在“宇称不守恒”现象的有力证据；日本克隆牛技术也基本达到实用化水平；日本还在研制世界最快的超级计算机“宇宙模拟器”。此外，日本在纳米和新材料等领域位于世界前列，并参与了国际空间站和人类基因组等重大国际合作科研计划。日本正积极在生物技术、生命科学、信息通信、航空航天、机械、环境、材料和能源技术等各个领域扩张。

资金投入和技术基础并不一定导致得诺贝尔奖。诺贝尔奖问世百年中，日本仅有９位得主，其中科学奖７名。因此，对日本这一目标的怀疑不无道理。但值得注意的是，日本对培养具有创造性的人才高度重视。早在１９９４年，它就提出“确保科技人才的基本方针”；野依良治获奖后，日本宣布，拨专款７０００万美元为他建立研究中心；日本还利用自身优势，吸引外国科学家到日本工作或合作研究。诺贝尔奖的颁发有“滞后性”，日本近十年来大量的科研投入将逐渐取得成效，２０００年和２００１年日本科学家连续得诺贝尔奖，在一定程度上说明了这一点。



日本为什么提出这一目标？有专家认为这是表明一种姿态。日本不仅是技术大国，而且还要成为科学大国，并提出“科技立国”；同时，这一口号也很具号召力和感染力。无论最终得到３０个诺贝尔奖与否，从积极的方面看，它可鼓励更多的人才重视科学、投身科研；其目的正如２００１年６月２８日的《日刊工业新闻》文章所说，日本要成为“受世界各国尊敬的国家”。


其他发达国家没有提出类似的口号，但也各有措施。美国的科研基础雄厚，每年都有科学家获奖，不需要制定目标；德国近年来在本土作研究的科学家获诺贝尔奖者日渐减少，德国已表示将大力改善科学家的工作环境；英国和法国等虽然没有提出相应的目标，但它们也制定了重点科研发展战略。在这些国家的财政预算中，资金投入都呈上升趋势。

为了实现这一目标，日本近几年采取了很多措施：加强科研投入；积极改革僵化、分割的旧科研体制，如把文部省和科技厅合并；重点发展生命科学、信息技术、环境和纳米技术等；支持企业科研，为了促进成果产业化，还设立专门的技术转让机构；以可持续发展为目标，立法确定科研方向；在自己创造有世界水平的成果同时，开展国际合作。


不过，很多专家表示，日本的这一目标或许适得其反。在这一目标下，科研体制可能失衡，更多人力、物力、财力可能会投向易被诺贝尔奖评委会认可的、容易出成果、快出成果的领域，忽略其他领域的基础研究，并误导部分科学家把得奖当成科研的目的，最终反而阻碍科学的发展。


