---
title: 微言（22）
author: Guanghua Mao
date: '2022-02-06'
slug: '400'
categories:
  - Original Articles
tags:
  - Insights
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

> 2020 的中概股飙升，3D 打印，智能眼镜，比特币，区块链，人工智能，元宇宙，智能音响，电动汽车，官店旅游产业大爆发，VR/AR，社区团购，微商，房地产投资。没想到我已经经历了如此的炒作和泡沫

1. 最近看到了许多讲述要专注、专心的话：博二兔，不得一兔；少则得，多则惑；贪多嚼不烂

2. 工作与打王者荣耀有很多相似之处：你没法挑选你的同事；要通过正确的方法影响同事；影响不了就做好自己的事情，扮演好自己的角色；自己能力的提升最重要。

3. 自我反思在第一份工作中做得最不好的一点：抱怨。

4. 技术是流动的，技术是共享的。了解了这一点就能够明白为什么靠技术吃一辈子饭是不可能的，为什么组织人、管理人、影响人的能力是最珍贵的。到目前为止，对我影响最深的一本书仍然是 left brain, right stuff。一开始的战略制定就要想好，要考虑到行业的天花板和规模，要想想自己能不能成为第一。很多人为什么参加培训，努力学习最终的结果并不好，其实看完这本书就能够全明白。


5. 桑德拉销售体系，谈判，决策，合作，沟通都是很重要的能力，远比技术能力重要。

6. 电子商务与数字营销

7. 唱衰自己，发现自己的愚蠢很反人性，但是很有价值，人们都想证明自己牛逼

8. 看了零售大师的视频，服务和商品的供给和需求都在本地化的实体店很难被取代，即时性和便利性要求极高的也很难被取代，线上可以引流

9. 一个人成功之后的表现才是他的真实水平，很多人都是成功之后膨胀而走上丢人现眼的道路的，比如 五五开，小沈阳

10. 投资者可能需要面临三个问题：
1，对商业的认知。在这方面，肯定有无数人靠着智商、勤奋，无限接近巴菲特，甚至超过巴菲特。
2，对市场的看法。大部分人跟巴菲特是反的，一天到晚都跟市场摔跤，摔多了难免自己摔倒。
3，对自身的认知。大部分人跟巴菲特也是反的，一天到晚都想证明自己NB，而不是认知到自己是SB。


11. 其实，这并不是人不“客观”，而是大部分人只看到现象，看不到规律；只看到结果，看不到过程。


12. 世界的客观规律是干的多收获多的可能性越大，绝大部分人拼的不是天赋而是投入。但每个人对生活的态度不同，他可以选择多大程度的努力同时也要做好得到相应回报的预期。

13. :如果仅仅是为了追求“激励有持久性、品牌的美誉度和员工的认同感”，不仍然是为实现预期利润作铺垫么？

2001年，一个日本记者采访乔布斯向他请教企业创新和管理之道，她的原话是：“现在很多日本公司试图年轻化，想给他们的文化注入冒险精神。”这和你所说的，其实就是一回事，最终追求的仍然是公司可持续性，进而成为一家顶级企业或者长寿企业。

乔布斯并没有回答她的问题，或许这些并不是他感兴趣的。他在采访中说到苹果生产了最好的产品，影响了数千万用户和整个行业。谈到互联网时他说了一句让我非常震惊的话，他说：“现在的互联网是没有感情的，现在的带宽不足以传递感情，要传递感情你需要更多的带宽。”这句话准确地切中了当时的互联网的弱点：只有展示，没有互动，纷繁但不生动。这句话如果细思，它其实就是一个方向性的预言：如果带宽持续增加，则人类的感情就可以通过互联网传递。没过几年，SNS崛起，而后视频火爆，再到现在各种网络应用爆发式增长，其实都在这个预言的范围之内。要知道，乔布斯说这番话的时候还是拨号时代的2001年。

从这个采访视频中可以看出，作为一个顶级企业家，乔布斯所关注的其实并非$苹果(AAPL)$ 本身，而是产品和它对人类社会所起到的作用，他更关心的是技术对人的影响。换言之，作为一个顶级企业家，他所追求的不应该是企业是否顶级或长寿，而是应该将其视为自身愿望实现的工具和平台，如果人的目标不能实现，那么这个企业就只能是一个圈养人的牢笼。一家顶级企业更应该是一个对人类社会作出重大贡献的组织。

人类社会之前并没有公司、股市，这些东西只不过是为了更高效的实现合作而出现的新的组织形式罢了。

回到那个日本记者和你的问题，其实有一个相同的答案：企业被经营它的人赋予了愿景，那它就成为实现这些愿景的工具和平台，它自然就会越来越年轻，自然就会越来越具有冒险精神，也自然而然地有了利润之上的追求。而从更长远更宽广的尺度上看，能够称为顶级的，只能是那些对历史进程有着重要影响力的企业。



14. 18日听了普林斯顿大学李凯教授题为Research vs. Innovation的报告，很有收获。他认为研究是将钱变成公开(public domain)的知识库（后张晓东教授补充为知识库和人才库），而创新则是将少部分知识根据市场的需要变成钱。他认为成功公司如苹果谷歌直接创新生成专利，而不从事研究。美国就是这样运作的。

15. Windows 8最近开始热起来，有人认为它有可能秒杀Android甚至iOS。看了些演示，印象是它并没有汲取十年来Tablet PC没有能够大幅成功推广的教训：用户交互过程中，最重要的不是漂亮，而是发疯的近乎直觉的简单。而掀开Windows 8 Metro的盖头，还是以前的基于键盘的应用，想既用在平板又用在笔记本上。

16. You think that focusing is to say "yes."  No, focusing is about saying "no." And you gotta say "no, no, no," and when you say "no" you piss off people.  … The result of that focus is gonna be some really great products, where the total is much greater than the sum of parts. S.J.

17. What's the meaning of life?  Siri's answer on the iPhone 4S: Try and be nice to people, avoid eating fat, read a good book every now and then, get some walking in, and try to live together in peace and harmony with people of all creeds and nations.

18. “Most people make the mistake of thinking design is what it looks like. People think it’s this veneer — that the designers are told, ‘Make it look good!’ That’s not what we think design is. It’s not just what it looks like and feels like. Design is how it works.” S. Jobs

19. 读一篇谈美国高等教育的文章，说有三项能力在美国高等教育界被认为是大学生应学到最重要能力：分别是理性思维critical thinking，综合推理complex reasoning，以及书面表达writen expression能力。哈佛耶鲁所有学生都必修写作课，可见其重要。仅从最直观写作能力而言，中国大学显然不如此重视。


20. 非常认同。对于绝大多数学生来说，交流沟通的能力，书面表达的能力，独立思考的精神，对音乐和艺术的基本知识和眼光，都比艰深的数学或信息学奥校题重要得多。

21. 赞同。越是什么清华斯坦福所谓牛校出来的，越该低调行事，尊重他人，虚怀若谷。 //@henryhxu:开会碰到一群清华学生，无论男女，都非常二，谈话只知清华，科研，三言两语就鄙视天下所有学校和老师，不顾及来自不同学校背景其他人的感受，简单来说就是老子天下第一，有一种ridiculously stupid的优越感。

22. 赞同。不懈的长期的努力是最稀缺的优秀品质，因为这非常辛苦，违背人之常情，极难做到。有志者事竟成六个字或是老生常谈，但极富感染力，我经常想起。乔布斯凌晨回复用户的邮件，马化腾两分钟回复陌生人的私信；而很多人却只看到他们的成功和财富，没有看到其背后不惜一切代价的努力和激流勇进的精神。


23. 回国访问了一个实验室，据导师介绍其学生在实验室工作每周至少五六十个小时，多者多达九十个多小时，统计数据是根据指纹考勤机，外出午餐都要打指纹，故十分精准。赞许其研究组发奋图强之余，我私下实在觉得这考勤机弊大于利，做研究不象编程序容易量化工作成果，谁能知道学生在实验室里的研究效率呢？ 

> 想起了管理出烂股一文

24. 原文说乔布斯四点起床没有任何依据；恰恰相反，乔布斯最反感循规蹈矩，年轻时生活毫无规律。其次，如果平庸意味着幸福，我愿意付出不幸福的代价，不去选择平庸，而选择大起大落，把自己的所有都放在赌桌上，输赢都玩儿个痛快。//@_Otacon_:平庸未尝不是一种幸福 //@_小团月:然后就病倒在了工作岗位上。

25. 乔布斯说过：您要是觉得一样儿东西不怎么的，别成天抱怨，自己做个新的。INFOCOM开幕式里十五分钟的幻灯片，延续了我钟爱的风格，全面采用手绘插图，以简洁的设计为基调，以星巴克咖啡为比喻，辅以实时动画截图，希望营造一种行云流水、举重若轻的现场效果。害怕现场紧张，关键的措辞还简单打了草稿。

26. 一个当了教授的朋友说起他的导师临别时送给他一条「锦囊妙计」。我想，我送给自己学生的锦囊里会有三个字：「稳、准、狠」。「稳」扎稳打，周密计划，好好学习，天天向上；「准」确判断大局，抓准稍纵即逝的时机；行事风格超乎常人，有一种「狠」劲儿，敢于甘冒奇险，目标单一而明确，不达目的不罢休。 

---

以下文章皆来自于李葆春的微博

# 买房还是租房

分答上回答了一个问题，关于年轻人是否应该买房。可是回答时间限制太严格，有点儿意犹未尽，想写一篇关于是否买房的说明文。中学时学说明文时，强调的是只陈述客观事实，而不发表主观论述和观点。说明文的影响力在于，「摆事实」以正视听之后，每个读者自然会形成自己的观点。

是买房还是租房住，自然和有多少钱直接相关。如果没有足够的资金，当然应该租房住。可是钱有两种：一种是一笔能拿得出来的存款，一种是每月的收入。举个常见的例子，如果我能一笔拿得出一百万，每月收入一万五，是否应该买房？

这个问题关系到买房有什么好处和坏处。房子对人有两种价值：一是提升生活品质，包括让心情更愉快。二是作为一种投资产品，将来可能会升值。

只考虑生活价值的话，理论上说房子越大、地段越好，生活品质越高，心情越愉快。按国内一二线城市当前的租售比分析，每月同样的开销，很明显租房可以租到更大更好的房子。另外，租房的灵活性很好，随时可以把家搬到更好的地段，更大的房子，生活品质相应提升。可是心情是个难以捉摸的东西，很多人没买房之前心情很差，买了房心情非常愉快，感觉生活一下子好起来了。虽然没什么根据，但是对这些人来说，显然买一个小房比租一个大房生活品质更高，心情更好。

但如果只考虑投资价值的话，租房虽然没有任何投资价值，但是因为租同样的房子的每月开销比买房更低，省下来的钱可以投资股票等其他投资产品。而跟其他投资产品相比，房地产属于不动产 (illiquid assets)，买卖成本偏高，而且不是想卖就能立即出手。从投资成本来说，不适合短期投资，也不适合“集腋成裘”式的投资。另外，因为买房一般都需要贷款，相当于借钱投资，有杠杆效应，投资风险更高。比如如果首付一百万，贷款四百万，那么房价要是下跌百分之十，就相当于投资损失百分之五十。因为风险更高，房地产投资只适于三四十年的长期。这样长的时间里，大多数的房产可以至少做到保值，也就是说抵消了货币贬值的损失。五年甚至十年都属于短期投资，因为杠杆效应的存在，风险很高。相比而言，长期投资股票等产品是可以升值的，因为企业可以把资金用来提高生产力。

但是不买房转而把资金投资其他产品也有一个很重要的坏处：这样的投资方式需要很强的自制力，每月主动把剩余的资金用于投资，以保证将来退休以后的生活品质。可惜这很不符合有钱就想花的人之常情，属于逆水行舟。买房相当于强制性的储蓄，对自制力稍差的人来说是一件好事。可即使强制储蓄，也要有个上限，大致应该是每月收入的三分之一。也就是说，如果每月收入一万五，应该最多拿出五千去还供房贷款。否则不仅降低了平时的生活品质，还因为杠杆效应，增加了风险。

有人说，想这么多干什么，别人买我就买。这样的人适合买房，因为他们认为和别人不一样 (contrarian) 风险很高；有人认为不买房就找不到他心目中的女神或者男神，那么他应该买房，因为找到终生伴侣很重要；有人认为不买房就结不了婚，那么他该买房，因为婚不能不结。但是无论如何，至少应该明白买房带来的风险和相应失去的其他机会，明白历史不一定等同于未来，这样才能知己知彼，立于不败之地。

---

# 应不应该看微信公众号

每天花了大量的时间在阅读公众号上的文章，值不值？读多了觉得浪费时间，没读又怕错过了什么。（问题来自「向上移动」）

英文有一个缩略语叫「TL;DR」，代表「too long; didn't read」，中文大概可以译成「中心思想」或者「长话短说」。

TL;DR: 别看微信公众号上的文章。

微信公众号文章的最大优点是免费阅读。英文里爱说「没有免费的午餐」，意思是说如果一个产品对用户免费，一定需要用其他方式来收费，对用户来说往往比收费的产品代价更高。

微信公众号主要有两类：市场营销和文艺青年随笔。

市场营销的目标是靠吸引人的文章、照片和视频来吸引读者的注意力和时间（attention span）。因为任何人的时间都是非常有限的，所以这一类公众号的目的就是抢占「时间」这种稀缺资源。因为写这类公共号的作者往往是专业从事这项工作的，他们可以穷尽一切可能的方式和一切当下最吸引人的话题去吸引你阅读转发，进而「引爆朋友圈」，抢占更多人的注意力和时间。

文艺青年随笔的写作目标则不一样。它属于自娱自乐型，如果正好有爱好相仿的人来点个赞留个言，锦上添花，心情更加愉快。文艺青年随笔从来不对当前热门话题发表意见，阅读量一般很小，挺容易辨别的。可惜的是，文艺青年一般很难有大量的空闲时间从事长期的无偿创作，所以这类公众号就像当年的博客一样，容易开始却很难坚持，早晚要销声匿迹。

不可否认，微信公众号里确实有少量质量很高的文章，一般都出自文艺青年的随笔。可惜的是，因为高质量的文章比例太低，需要「沙里淘金」的时间太多，从时间成本来看，往往得不偿失。

那平时等地铁这种碎片时间里，不看公众号文章看什么呢？人的记忆往往偏爱长篇情节、故事有张力有跌宕起伏的文字。这么说吧，去年你在微信公众号看过的故事，现在还记得哪篇？跟朋友聊天时，与其靠「哎你看过咪蒙老师的那篇公众号文章吗」开场，不如用「莎士比亚老师写的Macbeth里讲了一个故事」、「乔治奥威尔老师在1984里说过」，或者至少「钱钟书先生在围城里有一句名言」来得引人入胜。

当然了，如果你这篇微信公众号文章是别人在朋友圈里转发的，是「金」而不是「沙」的概率几乎为零。

同样道理，我这篇回答也完全没必要看到结尾。因为不看没有错过任何值得记住的东西，而看这篇文字所花的时间，过去了就再也回不来了。

---

# 厌倦了自己的职业怎么办

作为一个情感专家，如果有一天厌倦了这个人设怎么办？（问题来自「向上移动」）

首先，你能提出这个问题，说明你在随时审视自己（be reflective），这种自省能力，需要极高的才华和修养，一般人不容易做到，值得「手动点赞」。

「人设」这个词儿用在名人身上，我认为可以理解为一种「品牌」。比如褚明宇常常提到「人分上等人和下等人」的理论，就具备一种品牌效应，其相应的产品力有助于他在市场竞争中异军突起。和普通品牌不一样的是，你作为「情感专家」，品牌价值中的一大部分直接和你的名字联系在一起，就像Coco Chanel的Chanel或者乔布斯的苹果，很难剥离开来。

但是如果哪一天自己都不喜欢自己的品牌了，怎么办？我认为无非「渐变」和「跳变」两种策略。

选择「渐变」，就是选择有意地将产品逐步转型，或者慢慢淡出大众的视野。李安导演的电影，从《饮食男女》到《色 · 戒》到《Life of Pi》，是成功的转型；而张扬导演的电影，则从当年《爱情麻辣烫》、《洗澡》的成功，到不为路人所知，是低调淡出了大家的视野。

我开始在UIUC读书那年进来一个名叫Vaduvur Bharghavan的教授。他在UIUC任教期间培养出来的学生成绩斐然，后来都去美国名校当了教授，他也毫无悬念地评上了终身教授。传说他升职后突然悄悄地离开了学校去了加州，没有临别赠言，甚至没跟任何人打招呼。这就是我说的「跳变」。

「求变」就像很多人的「中年危机」，无论是买辆跑车还是积极创业还是热衷组织校友会，其实本质原因不外乎是觉得同一件事儿做的时间长了，想重整旗鼓，卷土重来，实现少年时代的梦想，活出别样的精彩。可是，为什么一定要「变」呢？说不定一辈子当一名小有名气的情感专家，一位不知名的教授，一个「有趣的人」，甚至一名空乘或者油漆工，也自有一种稳操胜券的幸福。

以不变而应万变，以无招而胜有招。粗茶淡饭，说不定强于山珍海味。品牌也好，事业也罢，「maintaining the status quo」也许是最聪明的选择。

---

# 如何看待学习英语

大家怎样看待学习英语的事情？（问题来自「向上移动」）

我在美国上学时有个好朋友。当年他有一个愿望：十年之内英语说得和美国人完全一样。其实他说这句话时，英语已经非常出色了。出国前他为了准备GRE，当时没有新东方可上，于是自己一个一个词儿把《新英汉词典》背了下来。

他为了练习英语口语，刚到美国就倾其所有买了一台崭新的彩色电视机，每天看电视里的广告。我开始没太明白，为什么看电视专门去看广告。后来才知道，广告的好处在于它天天重复。他每天跟着广告练习，直到发音和语调都和广告一模一样。二十多年后，我还记得一则卖钻戒的广告词儿：「How could three months of salary last forever?」还有他现场认真跟读的神情。

他用英文写作的时候，喜欢一边想一边嚼口香糖揪头发，常常陷入冥思苦想。他逐字地衡量着每一句话的句式和用法，一遍遍地修改同一个自然段，往往一晚上也写不了几段儿。他写得虽然慢，可一旦定稿就不再修改，所以跟我写得飞快但是经常大改的风格相比，颇有「龟兔赛跑」之妙。

几年以后我们都当了教授，我去美国找他叙旧。走进他家的客厅，发现四壁皆空，只是正中间放着一个纸箱子，上面放了一台电视，正是他当年刚到美国时买的彩色电视机。纸箱子旁边放着一大摞录像带，是他一集一集亲自录下来的「Seinfeld」全集。他每天吃晚饭时，正好重温几集。每一个笑话，每一个包袱，都到了倒背如流的境界。

学习英语没有捷径。无论听、说、读、写，你的付出远远超出常人，早晚可以「和美国人完全一样」。

---

# 在学术界还是工业界

在学术界还是在工业界搞研究？（问题来自「向上移动」）

众所周知，投资有两种主要方式：投资股票（stocks）和投资债券或定期存款（fixed income）。

投资股票的风险相对比较高，但是长期来看回报也高，「在大风大浪中成长」，适合承受风险能力比较强的人。而投资债券则正相反，风险很低，但是相应的回报也低，适合喜欢风平浪静的人。当然通常更好的策略，是年轻的时候尽量多投资股票，进而逐渐加入债券投资，到退休前把风险降到最低。

工业界有点儿像投资股票，而去学术界则更像投资债券。

同样的人才去工业界，收入一般比去学术界高很多，有时候甚至是两倍以上。那为什么每一个学术界的空缺，都通常会有大量具有博士学位的申请者呢？

学术界大多有终身教授制（tenure）。一位教授晋升以后，大学就放弃了解雇他的权利，相当于以前国营企业的「铁饭碗」。去工业界则因为各种原因被解雇的风险较高，尤其是随着年龄增长，竞争力逐年衰退，有可能失业时正是孩子上大学最需要收入的时候。

很多人会说，那些失业的朋友，很快都会找到新的工作，说不定工资比以前还高，没有任何损失啊。这是因为在经济发展快的社会或时代，工业界工作的失业风险自然低一些。但是我们无法准确预测未来，也许到我们自己最需要工作收入来源的时候，经济发展减缓，甚至出现经济危机，这也是风险的一种表现形式。

所以，工业界回报高就必须承担一定的风险；而学术界「铁饭碗」的工资必然会低不少。去工业界还是学术界，要考虑的一个重要因素就是更偏爱「大风大浪」，还是更钟情「风平浪静」。

其实，有关收入的横向比较还没有这么简单。我们不但要考虑退休之前的工资，还要考虑退休后的退休金收入。假如30岁开始工作，65岁退休，活到100岁，那么退休以后的时间和退休前大致相当，退休金收入对于保证退休后的生活水平至关重要。

一些大学和很多政府部门相似，实施一种叫「defined benefit」的退休计划，退休以后每月提供一笔数额丰厚的退休金，一直发到去世；此后再继续给配偶发退休金，直至去世。如果工业界没有类似的计划，保守起见，则需要将退休前收入中的至少一半存起来留给退休后来花。大多数人无法做到这一点，也许只能降低退休后的生活水平。

当然，大学教授如果教学科研之外还有余力，可以同时去公司咨询或创业，享受「大风大浪里成长」的高回报，又没有相应的高风险。就像一个「portfolio」里既投资股票又投资债券，有点儿「两全其美」（have your cake and eat it）的感觉。很多人还提及诸如「我就喜欢教书育人」或「我就热爱那种没人管我的自由」等「情怀」方面的因素。可惜这些因素使我们本来就不简单的「优化模型」更加复杂，就不在这篇短文里展开论述了。

---

# 如何减肥

如何不那么痛苦的减肥？（问题来自「向上移动」）

我所了解的有关健康和运动的常识，基本上都是从书里看来的。

——

十年前我在一次多伦多至北京的航班上，一口气读完了一本书，可以说改变了我后来的运动习惯。书名很长，叫做「The Fitness Factor: Every Woman's Key to a Lifetime of Health and Well-Being」，作者Lisa Callahan是一位医生，专业是运动受伤恢复。其实这个书名起得有点儿误导，书里介绍的常识不仅适用于女性。

书里介绍了大量有关减肥、饮食、健康和运动的常识，但是其中最重要的一条，其实可以用一句话概括：无论男女，无论在什么年龄段，保持健康的最有效的手段是力量训练（weight training）。作为一种无氧运动，力量训练不仅可以增加肌肉力量和比例，肌肉恢复的过程还可以提高新陈代谢的速度，也就是常说的「睡觉时都在减肥」。另外，它可以增强骨骼的密度，大大延缓中老年人骨质疏松的过程。

正是因为这些显而易见的好处，我和国内的朋友聊天时，经常推荐他们开始力量训练。可惜的是，无论是年轻学生还是中年领导，大多数人都不以为然，认为女生没必要练力量，或者认为力量训练只是为了肌肉好看，所谓「六块腹肌」（six-pack）。但其实绝大多数人力量训练的频率和重量极其有限，很难练到「好看」的水平。力量训练其实是减肥和保持健康最有效的捷径，是运动必不可少的一部分，男女老少皆宜，甚至只需要家里有哑铃就行。

就像那本书里说的：力量训练就像一种万灵药，可以延缓衰老，预防重大疾病，提高身体的综合素质，而且任何年龄都可以开始。关键是你想不想得到这些好处。

——

四年前一个偶然的机会，我在美国一个机场的书店里买了另外一本书，书名叫「The 8 Hour Diet」，作者是Men's Health的主编。美国的Men's Health和国内的不同，以健康和运动为主题，极少提及时尚，是一本相当专业的杂志。

这本书的中心思想叫「Intermittent fasting」。每天无论吃多少都可以，但是要保证所有的进食都在8小时内完成，比如十点到六点之间，其他时间只喝茶或水。另外重视保证8种健康食品的摄入，同时坚持每天至少8分钟的有氧和力量训练。这和很多人所说的「少吃多餐」「一定要吃早餐」等常识是截然相反的。

「8-Hour Diet」的好处很容易理解。让身体每天都有一段时间不能得到满足，这样可以「居安思危」，激励细胞更加活跃。书里提到，「8-Hour Diet」若能与健康食品和运动结合起来，不但对减肥很有好处，还可以有效地预防癌症、心血管疾病和糖尿病这三大杀手级疾病。

遗憾的是，我把这本书的理论给很多朋友介绍过，但极少有人认同这些想法。有时候不禁会感慨，一个人的想法即使是误区，一旦形成，确实很难改变。

·  ·  ·

希望这篇短文，可以像十年前那本书改变我一样，改变微博里几位朋友的想法。

---

# 码农这个职业

想听褚老师和李老师谈谈「码农」这个职业。（问题来自「向上移动」）

我很少的几个偶像之一，Chris Lattner，就是一个标准的「码农」。

Chris Lattner是我和褚老师在UIUC的校友。他在读硕士学位期间就设计和实现了一种叫「LLVM」的系统，将传统编译器 (compiler) 模块化，大大提高各个模块的可重用性 (reusability), 开源以来彻底颠覆了几十年来的编译系统设计。他博士毕业后加盟苹果，将一种叫「Automatic Reference Counting」的内存管理机制引入了Objective C和iOS平台，替代了当年最流行的「Garbage Collection」机制，大大提高了内存管理的效率，保证了iOS apps在内存有限的情况下一样可以流畅运行。

2010年以来，他独自一人开始设计一种名为「Swift」的全新编程语言，汲取了二十多年来现代程序设计语言几乎所有的宝贵经验，真正实现了既能快速开发、又能高速运行的「Holy Grail」，现在已经成为iOS平台上的主流程序设计语言。2013年他获得了UIUC的特别校友成就奖（Distinguished Alumni Achievement Award），可以说他的工作改变了整个软件产业。

如果说Chris Lattner是一个标准的「码农」，那么如果能再年轻一回，我的理想就是当一个像他一样的「码农」。

可惜的是，这几年「码农」这个词儿无论是用来叙事还是用来自嘲，都带有一种天生的贬义。这种贬义甚至影响了大量学生，觉得再怎么好好学习计算机，将来不也就是当一个「码农」或「程序猿」而已。

但是实际上「码农」这个职业虽然显得像个「农民工」，却先天具备两个极为有利的优势。第一，不仅仅是计算机行业，很多其他行业也需要开发和维护越来越复杂的软件系统。第二，一个水平高的「码农」就像一个天生丽质的模特，相当罕见。乔布斯曾经说过：「The difference between the average software developer and the best is 50:1. Maybe even 100:1.」

这是因为当一个好的「码农」，不仅需要从离散数学开始，掌握一种叫做「计算思维」的能力；还需要从计算机体系结构、操作系统、算法分析入手，掌握几十年来计算机工程的无数成功和失败的设计。就好像学一门乐器，需要多年静下心来苦心孤诣地积累，才能成为一代名家，才能自然而然地具备一种「一夫当关，万夫莫开」的气场。

当然至为登峰造极的功夫，是将程序设计从工程提升到艺术的层面，发现其中的魅力所在。这一点，和当年梁思成研究建筑、杨振宁研究物理相比，颇有异曲同工之妙。Chris Lattner主导的Swift语言中每一个版本的演进，都是在以一种近乎工匠般严格的精神，仔细地衡量每一行代码的语言风格如何更加「漂亮」。比如程序界面里需要定义一个表示蓝色的变量，早先写成：

let blue = UIColor.blueColor()

后来演进为：

let blue = UIColor.blue

如果一个所谓的「码农」能够返朴归真，达到如此「以无招而胜有招」的境界，我会像刚刚看完伍迪艾伦的电影一样，产生一种久久挥之不去的感动。

---

# 工程师

如何成为一个合格的工程师？（问题来自微博私信）

有一位工程师、一位牧师和一位医生在高尔夫球场打球。他们发现前方有几个人占着场地，打得又慢又不专业，就问球场的服务员。服务员说：这几个人是消防员，曾经在球场的一次火灾中，因为帮忙救火而失明了。

牧师动容地说：“我今晚一定会替他们祷告，祈祷他们重见光明。”

医生惋惜地说：“我联系一下眼科的同事，看看能不能为他们做点儿什么。”

工程师不解地说：“那他们为什么不能晚上打球啊？”

——

工程师的世界和科学家艺术家不同，不但不是非黑即白，而且没有完美可言。一个工程师的工作，是如何在一些约束条件下完成一个系统的设计和实现。这样的系统和真实的世界一样，永远是不完美的。就像需要在一年内设计一辆造价不超过十万元的汽车，一位合格的工程师，需要在各种取舍之间权衡利弊得失（tradeoffs and compromises），最终得到一种最好的解决方案。

在我们这个高尔夫球场的故事里，牧师和医生都在表示同情，只有工程师在想如何解决这个问题。

而约束条件中最常见的，往往是资金和时间成本。一家航空公司的电话订票系统，如果只有一个电话服务中心，很有可能在最繁忙时无法应付需求。但是如果在全国建立多个服务中心，虽然可以提高系统的可扩展性（scalability），但由于各个中心之间的数据需要实时同步，提高了系统设计的复杂度，增加了系统实现的资金和时间成本。我们常说的「KISS (Keep It Simple Stupid)」，就是希望通过简化设计而减少资金和时间的投入。

其实，日常生活和工作里的很多事情，与其一味追求尽善尽美的「工匠」精神，不如提倡一点儿工程师式的「实用主义」，在有限的时间里做完。做饭与其追求做得多好吃，不如做得快；写论文与其追求「沉鱼落雁之容」，不如「在规定时间里」把问题和解法写清楚。一个合格的工程师需要大量工程实践和训练，而这种「多快好省」地生活和工作，同样需要一种「工程师」式的理念和智慧。

一个玻璃杯里有半杯水。悲观主义者想：「玻璃杯已经空了一半。」乐观主义者想：「玻璃杯还有一半水。」

而工程师会想：「玻璃杯的设计有失误，容积可以减半。」

我喜欢这种「工程师」式的哲学。



---

# 区块链与比特币

李老师，前两天您在社区回答了关于比特币的看法，认为它是完全的投机不建议参与。想问下您怎么看待区块链技术和基于区块链技术开发的应用而产生的代币，如以太坊，eos和一些山寨币，您觉得他们都没有实际的价值么？（问题来自「向上移动」）

显然，无论是比特币还是以太坊（Ethereum），都是有实际价值的。如果你有数量足够的比特币或其他数字货币，理论上来说你可以用它去买法拉利的跑车。

但我想你更关心的问题其实是，比特币和以太坊等其他数字货币，到底是否有投资价值，也就是说它们长期来看（五至十年）是否会升值。

我在前一篇回答里盖棺定论，把买比特币定性为「投机」（speculation），你也许认为过于武断。

2009年，比特币最初的设计目标是作为一种数字货币用于电子支付，也就是说当钱花用来买东西。它的创始人Satoshi Nakamoto设计的区块链技术从学术角度看是一种优美而杰出的设计，重点是完全不需要信任任何监管体系，而是依赖公开记录并验证所有交易。

但是比特币最初实现区块链技术用到的算法中出现了一个问题。它处理交易的吞吐量（transaction processing capacity）不高，形成了性能上的瓶颈。因为大量拥堵，造成了交易费用居高不下。从这一点来看，比特币作为货币用于支付的目标基本已经失败，很难进一步推广。

这也是包括以太坊在内的其他数字货币如雨后春笋般地不断涌现的原因。这些新型的数字货币的交易处理吞吐量都比比特币高得多，那是否可以将来取代比特币作为主流数字货币实现电子支付呢？

我认为希望十分渺茫。

首先，如果其他数字货币开始流行，对持有比特币的人不利，这些人一定会反对推广其他货币。他们持有比特币的目的早就不是为了要拿来买东西，而是用来保值（store of value），甚至升值。其实，这个目的和最开始设计比特币的初衷是背道而驰的：如果作为货币用来交易，需要的是流通甚至通过增发略微贬值，而不是升值。黄金可以用来保值，但却很难用来作为货币买东西。

其次，传统货币用于电子支付或转账，现在早已司空见惯。别说改用比特币或以太坊，就算是让您从微信支付宝改成其他支付平台，多半儿您都不乐意。

好吧，用来电子支付买东西是没希望了。那是否可以跟买股票一样用来长期投资期望它升值呢？

这相当于期望越来越多的人会买入比特币或其他数字货币。而买入的原因不是为了电子支付买东西，而是因为大家都期望它长期可以升值，是一种优秀的投资方式。

您多半儿听说了，比特币历史上曾经创造过一年上涨50倍的辉煌，也曾经一年跌过60%。就像货币历史专家、加州大学伯克利分校的经济学教授Barry Eichengreen说的：「Expectations can change.」

而「区块链」并不能增加比特币长期升值的概率，因为绝大多数人不明白它是怎么回事儿。

如果您听说的都是「投资」比特币成功的故事，那是因为这是一种「有偏采样」：投资失败了人家不会告诉你。

不过投机是一种娱乐，只要您充分意识到了其风险，是非常刺激好玩儿的。

祝您过山车玩儿得开心。

---

# 香港保险

最近听朋友聊到买香港保险的事，重疾和理财保险产品，想问问社区里有没有懂这行的，香港保险靠不靠谱？（问题来自「向上移动」）

前一阵子去香港开会，一个大学的教授请我去一个挺高档的馆子吃饭。他妻子也参加了，她正好在一家保险公司供职，大概是推销保险产品的吧，简称「理财顾问」。据说她收入颇丰，远远超过大学里的教职。

三句话不离本行，我们就聊了一会儿保险产品。她给我介绍说，她们公司的保险产品，可以保证每年百分之六的回报率。

「那要是出现像零八年那会儿的经济危机呢？」

「那也能保证百分之六的回报。」

我礼节性地笑着，没有再继续聊这个话题。据说她的客户大多是国内来的。

任何投资产品，但凡提到「保证」什么超过定期存款的回报率，都会十分可疑。这是因为市场是无法保证短期投资收益的，潜在的回报越高风险越大。既然是投资，就要清晰地认识并接受其风险。这就是所谓的「风险和机遇并存」。

香港的保险业，往往是用这种「保证回报」的金字招牌作为其最大的亮点来推销其产品。而买这类保险产品的客户，则常常正是被如此「物美价廉」的「投资」产品所吸引，竟然忘记了购买一份保险产品的初衷。

保险最基本的职能，其实是在投保人出现意外死亡（或者重大疾病）时，保险公司给家属可以赔付一笔免税的赔偿金。

而实现这个职能最简单的险种叫定期人寿保险（term life insurance）。举个例子，如果一个定期保险一年交一千美元，在六十岁过期。投保人六十岁前去世赔付五十万美元，但是如果六十岁前没有去世，则所有的保费就白交给保险公司了。这种保险产品因为比较简单易懂，在当今十分成熟的保险业，保费会相对低廉，甚至会包括头十年或终身保费不会上涨的条款。相对而言，保险公司的利润空间也不会太大。

而往往需要「理财顾问」推销的保险产品，基本上都属于「终身保险」（universal life insurance）。表面上看，这种保险产品兼具定期保险和投资两种职能：如果意外去世可以赔付一定金额，但没有去世则可以拿回大部分「投资」的本金及其分红 ——「best of both worlds」。

但是不要忘了，但凡什么东西听起来非常诱人，往往一定暗藏玄机，英文叫「too good to be true」。那具体来说这「玄机」在哪里呢？对不起，这可是「可口可乐秘方」，保险公司是不会明确告诉你的。比如如果你提前终止保险合同，有可能大部分的「投资」无法收回，损失惨重。而这种「只能买入不能变现」直接影响到投资的「流动性」（liquidity），是投资的大忌。

我个人认为，要是想买保险就买简单明了的定期保险，要是想投资就专门去投资，两者最好不要混为一谈。实在要买，也建议花几天时间仔细研读合同里的条款（fine print），尽量找到其「玄机」所在。而无论保险还是投资，一个好的产品往往即使「待字闺中」依然炙手可热，不需要推销，更不需要给推销员分红。

一个最好的例子是美国著名的基金产品之一，西蒙斯创立的Renaissance Technologies旗下的Medallion Fund。该基金自从1993年以来只对本公司员工开放，二十多年来每年平均回报70%以上。

这不仅仅是「待字闺中」，简直就是「闭门谢客」了吧


---

# 找工作

李老师好！您曾经说过，找工作就跟找对象一样：「没有的时候有无穷多种选择，非常灵活机动；有了就成了唯一选择，不满意的话就只能听之任之，或者付出昂贵的「跳槽」成本。」 

我本科快毕业了，想请教您一下，您是怎么看待人生第一份工作的选择的呢？（问题来自微博私信）

你听说过一个叫「gambit」的英文词儿吗？

这个词儿最初是从一种叫「the Queen’s Gambit」的国际象棋开局来的。这种开局有点儿匪夷所思：第二步棋就放弃一个卒，从而让皇后有充分发挥其优势的机会。这种古老的开局是典型的以退为进，韬光养晦，采取的是「先天下大乱而后天下大治」的方针。然而它却极其有效，曾经在国际象棋大师赛中风行一时。

找第一个工作就像下国际象棋。有时候吃一点儿亏、冒一点儿风险，往往如同「the Queen’s Gambit」一样，是一种行之有效的开局。

我有一个舅舅叫王缉思，是我从小到大的偶像。他在国际关系尤其是中美关系领域是世界知名的学者，现任北京大学国际战略研究院院长，曾被美《外交政策》杂志评为世界风云人物一百人之一。

去年我回北大时他曾给了我一张名片，地址是「北京大学北阁」。我从小在北大长大，这个地址在我印象里可以和「宾夕法尼亚大道1600号」媲美。不过我最佩服的还是他一口流利的英文，略带伦敦音，以至于我长大以后每次听到伦敦音就会想到他。

而他的第一个工作，是在内蒙古放羊。而且一去就住了十年。据说，他那会儿为了学习英文，只能用短波收音机收听美国之音。

也许，如今第一个工作再不尽如意，也不会比他的经历更糟糕了吧。但是我想，也许他后来所有的成就，都离不开那个时代给他带来的阅历；也许他一口标准而流利的英文，也离不开那个短波收音机。

所以，如同那句「天将降大任于斯人也」的老话里说的，第一个工作不一定非要踌躇满志，锋芒毕露。放弃一些优越的条件，冒一点儿有意义的风险，静下心来，从长计议，踏踏实实地一点一滴提高自己真实的水平，提高自己在市场里的价值，说不定将来可以充分发挥「皇后」的优势所在，迅速崭露头角。

最近有一个新闻：谷歌的AlphaZero同时开动了五千多个TPU，不但靠「左右互搏」的战法四小时学会国际象棋，而且棋风有人的「灵性」，已臻「独孤求败」的境界。

而AlphaZero最喜欢的两种开局之一，就是古老而凌厉的「the Queen’s Gambit」。


---

# 勤俭节约

从小到大受到的教育里，「勤俭节约」一向是一种美德。

比如《小学生守则》里就有一条叫「生活俭朴，爱惜粮食，不挑吃穿，不乱花钱」。它虽然排在「热爱祖国，热爱人民，热爱中国共产党」之后，但是那种「一分钱掰成两半花」和「新三年旧三年缝缝补补又三年」的哲学，却自始自终刻骨铭心。

现在一想，怎么就没有人举手提问：「为什么要存钱呢？」

老师一定会回答：「存钱是为了以后买房、投资、买比特币啊。」

按理说，这个理儿讲到这儿就差不多了。大多数人也是这么身体力行的：省吃俭用，买车买房，如果还有闲钱去「理财」，投资点儿黄金美股比特币什么的。

但关键的问题在于，拿省下来的钱去「理财」干嘛？

老师一定会说：「理财是为了将来花啊。」

这个回答里暗含了一个假设：钱将来花比现在花要强。

可惜这个假设是错误的，反过来倒是多半成立。首先，钱是会贬值的，现在一百块可以买三杯咖啡，三十年以后也许只能买一杯了。其次，人是会逐渐衰老的，年轻时花钱玩儿过山车是享受，年纪大了说不定就是折磨。年轻时一定要喝上好的葡萄酒，年纪大了喝什么酒已经没什么区别了。

而且无论贫富，永远有这样一种可能：快要离开这个世界的时候，发现钱还远远没有花完。

所以正确的做法是，每年的收入全部花掉，还完房贷之后，银行的存款永远是负数，就像很多外国人。到了退休的时候要是缺钱花，再把已经基本付清的房产用「反向房贷」（reverse mortgage）抵押给银行提现。

这种「做一天和尚撞一天钟」的哲学有诸多好处。没有机会积累大量的积蓄，就没有那种跟中了彩票似的挥霍无度的风险；钱花掉了，自然不用担心它将来贬值，也不用担心比特币大跌是否需要「清仓」；孩子没有继承财产的可能，更容易形成独立自主、自力更生的性格；在年轻时充分享受生活，爱过恨过，吃香的喝辣的，走遍大江南北。

我有一个理想：将来有一天回首浮生往事，如果能再重来一次，该怎么玩儿怎么折腾，一切的选择，一如当年。


---

# 迷茫与焦虑

李老师好，我很喜欢您的文字，也喜欢您的生活方式，每次看您的微博都觉得您的生活就是我一直追求的生活。但是我目前还在迷茫的阶段，在复旦读大二，对于自己的未来，对于以后的生活伴侣都有诸多焦虑，害怕自己做出错误的选择。请问老师年轻的时候遇到这样的焦虑吗？请问老师该如何调整心态呢？（问题来自微博私信）

无论什么时候、什么事儿，我都经常会焦虑啊。比如刚刚收到你这个问题那会儿，我就想，完了，命题作文来了，写不出来怎么办？你的问题就差「字数不少于八百字，文体不限，诗歌除外」了。

一个人的焦虑，是因为未来的阴错阳差，完全无法预料。我们都希望一个好的结局，越是重要的事儿，越害怕事与愿违。在焦虑这件事儿上，我对你最多只是「五十步笑百步」而已。

王朔是北京一比较贫嘴的作家，多年前写过一部小说，名字叫《顽主》。里面给「五十步笑百步」造句：「新娘上轿，前五十步笑，百步以后哭。」

你瞧，同样六个字，换个方式来看，结果完全不同。

有些事儿吧，我们还真得想个办法，换个角度来看。

比如寻找「生活伴侣」这事儿吧，什么才叫「错误」的选择？为什么一个「错误」的选择就满盘皆输？

一个滴酒不沾的数学家，天天不是在餐馆打工，就是在公园演算数学证明；另一个酷爱喝酒、撸串，天天不求上进，小富即安，哪个选择是「错误」的？

如果运气不好正好碰到了一个「错误」的选择，为什么不能立马离开这个选择，一切重新开始？

我们系里有一个葡萄牙裔的秘书，经历过四任丈夫，一共抚养了四个儿子。她自豪地将他们的照片摆在办公室的书架上，我看着这些照片，个个光彩照人。有一瞬间，我觉得他们的妈妈才是真正的「人生赢家」。

如果一个选择虽然非常重要，但是没有对错之分，甚至选与不选都无所谓对错，是不是心情就一下子轻松好多？如果新娘上了轿，前五十步笑，百步以后可以换一个轿子坐，是不是上哪个轿子都差不多？

刚才给你写这篇作文的时候，我一旦明白了写得怎么样其实无关紧要，一下子就豁然开朗，如释重负。于是草草成文，一气呵成。

写完一看，好像也没差到哪儿去啊。

---

# 工作的回报

李老师您好，经常默默地看您的微博，包括对于青年人问题的解答，觉得您的文风特别的实在和中肯。所以我也想请教您一个问题，不知道能不能有幸得到解答。

我是学内燃机的工科生得到了一个车企台架工程师和一个知名运营商企业客户经理的offer。我倾向于前者因为我觉得在车企好歹是一门技术，不管将来怎么样都能找到工作，尤其是年纪大了之后有技术更稳。但是就职于该公司的一个表哥又强烈建议我去这家公司，说待遇好也锻炼人。但是我想做这种销售类的工作谁都可以干，尤其是年龄大了以后出来能好找工作吗？

我想这也是一个中国相当部分工科学生面临的问题，当毕业季找到的工作在性质上具有巨大差别时，到底是坚持一技在身，还是转去做一些销服类或者其他的跨行业的工作？（问题来自微博私信）

如果你去问李开复或者去看TED的演讲，他们会告诉你两个字：「激情」（passion）。这种「follow your heart」听起来不错，可是它的假设里有一个致命的缺陷：很多人对什么工作都没有什么热情。

这就好像你去相亲，有两个对象。一个长得好看但有可能跟别人跑了，另一个有学识有文化什么都好就是相貌一般。可哪一个你都不是「一日不见如隔三秋」，就想赶紧把这婚结了。你该选哪一个？

工作和谈恋爱一样，不是每个人的运气都好到曾经爱一个人爱到茶不思饭不想，可以写进电影剧本。

那如果对什么都没什么热情，工作这么重要一件事儿，应该如何选择？

首先，千万别全盘接受别人的建议。表哥也好，李老师也好，往往给出的建议都是基于他自己的工作背景和偏爱，往往不一定中肯。你可以仔细研究他这篇「议论文」的论据和论证方法，但不要直接接受他的论点。

其次，对工作没什么热情，正好可以理性地把它们放在一个多维度的空间里，分析一下它们的特性。跟投资差不多，一个工作可以简单地用三维空间表述：风险（risk)，流动性（liquidity），还有回报（return）。风险是指这个工作是否很容易失去（投资产品是否会大跌）；流动性是指你是否可以随时换个工作（投资产品是否可以随时卖出变现）；而回报呢，则代表这个工作的总收入。

和投资一样，风险高的工作潜在的未来回报自然也高一些；而你很容易换其他工作，多半儿公司把你换成别人也不难。

如何选择一个最好的工作？一个最简单的办法，你可以把一个工作在这三个维度各转化为一个 [0, 1] 区间里的量，零代表最差，一代表最好，再计算一下这个工作在三维空间里的位置到零点的距离。距离最长者为胜。

比如「创业」这个选择，回报比普通工作高百分之五十，风险则可能高百分之一百，在三维空间里，也许是一个很糟糕的选择。

当然，如果你有一个女朋友或男朋友，最好的方式是进行「优化投资组合」：一个人的工作风险较小，流动性和长期回报较低；另一个人去选择风险高、潜在回报高、流动性较强的工作。这样可以保证一定回报，又尽量降低风险。

而这个理论的前提是两个人需要相互信任。翟欣欣之所以找苏享茂，苏享茂之所以找翟欣欣，大概都是「优化投资组合」的结果。


---

# 当教授

前几天我跟一个申请读硕士研究生的学生聊天，问他将来毕了业有什么打算。他不假思索：「读博士，读完了争取当个教授。」就好像当个教授是一切优化问题的最优解。

我倒是觉得，当个大学教授和当个小学老师差不多，只是一个普通的工作，并没有那么令人悠然神往。力荐教授这个职业的，大多数自己都是教授。借用电影《肖申克的救赎》里的一个词儿，这叫「institutionalized」。

当个教授确实有机会到处开会，可惜去开会其实行色匆匆，疲惫不已，大多数时间是在工作，而不是在旅游。

当个教授确实有一笔稳定的收入，可惜工作压力太大，时间太长，基本没有周末，平均每小时税后的时薪，大概跟在星巴克卖咖啡差不了太多。

当个教授确实有做学术研究的自由，可惜研究的成果和水平都是别人说了才算。和其他工作差不多，少数人在金字塔尖儿，占有大多数的「声望」和资源。

当个教授相当于开了一家皮包公司：品牌推广、市场营销、产品创收、人力资源，都是一个人管。从经费申请到学生推荐信，从立项到结题，从本科课程到组织会议，没有一件事儿是省油的灯。

我做这个工作，或许是因为我有自知之明：没有足够的胆量去「海归」创业，没有足够的能力去谷歌编程，也没有足够的人气去当「大V」网红。

或许只是为了将来女儿可以跟朋友介绍：「我父亲当年是个大学教授。」


---

# 个人隐私

Cambridge Analytica和Facebook的新闻告诉我们一个显而易见的常识：个人的隐私只有在失去以后才会觉得珍贵，而使用免费的产品往往需要付出高昂的代价。很可惜，在这个「算法」至上的时代，很多人并没有意识到这一点。

我很庆幸，多年前我永久删除了自己的Facebook帐号，同时坚决不玩儿各种「朋友圈」。


---

# 微信公众号的名字

李老师，冒昧打扰下。我最近想开个微信公众号，想尝试写类似「大象公会」这个号上形式的文章，和读者一起做认知上的升级，并借此了解和熟悉公众号管理之类的事。

但是在公众号起名上我遇到了阻碍，我原本是想起「因果警察」，我想的是不判断是非，只追溯因果，这点但是跟我打算写的东西契合，但是由于名号词汇过不了审核，我就很困惑，一时不知道起个什么名字，所以就很唐突地来问老师，老师有没有什么起名字的建议？（问题来自微博私信）

先给你泼一盆冷水啊。微信公众号和微博差不多，阅读量多半儿表现为Zipf分布。它是一种幂律分布，极少数公众号阅读量极高，而大多数没什么人读。而读者寥寥，对写作热情没有什么激励，文字的质量就很难提高，也很难长期坚持下去。这些都和公众号的名字无关。

新号开张儿，无论谁都想起一个好听点儿的名字。我认为，与其试图去体现公众号的主题，不如反其道而行之，起一个让潜在的读者莫名其妙的名字，去挑战他们的好奇心。

就拿「大象公会」来说，我乍一看就完全不知道这是什么主题。而这种潜在的好奇反而可能让一位读者点开其中一篇文章，然后或开怀大笑，或感触良多，继而爱不释手。

当然这种「莫名其妙」也还是要有个限度。要「莫名其妙」得似曾相识，而非「莫名其妙」得冷若冰霜。你可以先想想你的读者群大致年龄段，然后找一个这个年龄段的人十几二十岁时耳熟能详的名字。因为每一代人都有他们最钟爱的电影、电视剧、歌星和时尚，这些是藏在他们记忆深处挥之不去的。

比如七十年代早期出生的读者，可以叫「铁臂阿童木」，叫「血疑」，叫「阳光灿烂的日子」，叫「花房姑娘」，叫「过把瘾就死」，叫「北京人在纽约」，叫「恋曲一九九零」，叫「新华文摘」，叫「芙蓉镇」，叫「排球女将」，甚至可以叫「小鹿纯子」。

当然，如果你的读者群是四五十年代出生的，那你得考虑「红灯记」、「白毛女」、「喀秋莎」，或者「莫斯科郊外的晚上」。

褚明宇曾经提到，他多年前在纽约曾经建议给一个乐队起名叫「新华书店」。他的套路就是试图去唤醒潜意识里对「新华书店」的一种热爱，因为那不仅代表着一家书店，更代表着一个年代。

而管乐队叫书店的那种「驴唇不对马嘴」，那种刘瑜笔下的「突兀之美」，有点儿像咬了一口的苹果商标，正是起名字这门学问的最高境界。


---

# 读博士很痛苦

李老师您好，通过褚老师认识了李老师，经常默默地看您在分答，微博的回答，包括对于青年人问题的解答，特别喜欢您流畅，质朴的文风。所以我也想请教您一个问题，不知道能否有幸得到您的回答。

我大学毕业于一所内地排名前十的985院校，翻译专业，毕业后在一家英语教育机构（不是新东方）任职，今年是第三年。其实当年毕业也考到了研究生，但是觉得国内研究生太水，没去读。国外文科类研究生学费略贵，虽然家境小康，但是父母赚钱不易，不想给父母增加负担。我是真的很享受当老师的过程，在工作中我发现我很适合做教研，也就是大量阅读原版读物，然后开发出适合不同年龄孩子阅读的材料。

虽然工作上发展尚可，但是随着年限增长，愈发感受到办公室政治的残酷和累心，并不想参与其中。于是，萌生了去美国读教育类PhD的想法。我知道一纸文凭对赚钱并无卵用，只是想找到一个可以让自己沉浸其中的事情去做，如果还能学有所成就更是不负此生。李老师您本身带博士生，您觉得我这样的想法和背景（我觉得自己研究背景还是浅了些）适不适合直接申请读博士呢？申请博士在您看来有哪些需要注意的事项？（问题来自微博私信）

——

你知道有一种叫「波特」（Port）的酒吗？

波特酒是一种极甜的加强葡萄酒（fortified wine），适合饭后甜点时喝。它的主要产地是葡萄牙海边的一个叫Porto的城市，酒名也是因之而来。为了有足够的时间发酵，波特酒一般至少需要两年时间才能装瓶，装瓶后还需要至少十几年时间才能喝。它的酒精浓度比一般葡萄酒高，口感纯正、甜美，有一种「余音绕梁」的感觉。

如果说上中学是开胃的鸡尾酒或者香槟酒，上大学本科是与主菜相配的红葡萄酒，那么读博士学位就是餐后的波特酒。

读博士和波特酒一样，有其好处和坏处。如果你明白了这些好处和坏处，还愿意去读的话，我认为值得一试。如果能申请出国读自然最好，就好像要喝就应该喝葡萄牙出产的波特酒一样。

按照西方人的偏爱，咱先从坏消息说起吧。和餐后的波特酒差不多，博士学位可有可无，读不读博士没有什么明显的区别。它无法帮你逃离办公室政治，无法帮你提高工资收入，也多半儿无法帮你结交「谈笑有鸿儒，往来无白丁」的朋友。

更有甚者，读博士的过程其实相当痛苦。想写论文但是写不出来，想做实验但是结果不对，好不容易结果出来了投稿，又被审稿人拒绝，那是常有的事儿。

读博士是一件只有「有志青年」才做的事儿。他们有点儿像数学家或者哲学家，不在乎收入，也不在乎朋友，也不在乎「苦其心志」，就是喜欢研究一些普通人懒得去研究的问题。这大概是为什么「博士」英文里其实叫做「哲学博士」(Doctor of Philosophy) 的原因。

博士学位可有可无，又含辛茹苦，那它到底有什么好处呢？它最重要的好处，是它虽然苦，但是苦尽甘来时，有一种极为独特、浓郁的甜味儿。没喝过波特酒，你无法想象世上竟然还有这种和香槟或葡萄酒相比迥然不同的甜法儿，甜得发腻，甜得厚积薄发，甜得「一览众山小」，甜得「轻解罗裳，独上兰舟」。

当然还有一个好处：一切尘埃落定之后，你还会得到一份可以挂在墙上的证书，上面写着你的名字，还有「Doctor of Philosophy」。


---

# 下等人朋友

李老师，我是一名大三的学生，经常觉得身边的人很「下等」，是我自己的问题还是环境的原因呢？以及怎样才能交到真心的朋友？（问题来自分答「在行一点」）

正好今天收到一条微博私信。发信人不同意褚明宇最近的一篇微博，于是来问我：「关注您很久了，气质和褚明宇很不一样。不知道怎么和这个上等人成朋友了？」

两个问题出发点颇为不同，但是言外之意大致都是：如何尽量「向上移动」，别跟「下等人」成为朋友？

其实我们来想一想，我们知道的人里，哪些人是「上等人」呢？巴菲特算吗？马斯克算吗？布隆伯格算吗？斯皮尔伯格算吗？如果限于国内，那马云算吗？马化腾算吗？陈晓卿算吗？刘瑜算吗？

想好以后我们再来假想一下，如果给你一个和他一起吃午饭的机会，你作何感想 — 欣喜若狂？还是激动万分？

要是我有这样一个机会，只会觉得紧张。就跟要去谷歌面试一样。

比如有一次和一位教授吃饭，他一语双关，提到数学里著名的「李群」(Lie group)，我一时半会儿没反应过来。从那儿以后每次见到这个教授，我就有点儿紧张。

而真正的朋友，至少你和他吃饭不会觉得紧张。

我有一个朋友是大学同学，因为他们家住得挺近的，有时会带孩子串个门儿。孩子一起玩儿的时候，我们也能一人一瓶啤酒，聊一会儿天。这位同学有两大爱好：分析台湾形势和研究中国军事问题。很可惜由于平时时间有限，我对台湾和军事无知得很，超级不熟，聊不起来。而我喜欢的主题，比如汽车，比如电影，他同样无话可说。

不过后来我们发现一个知识交集：安卓操作系统。他的工作和安卓相关，恰好我也懂一点儿。从那儿以后我们每次见面，聊几句就聊到了安卓，竟然也言之有物，侃侃而谈。

所以我觉得，无论是二十多的小姑娘还是六十多的老爷子，每个人其实都有一些自己喜欢的人和东西，就像一个「频谱」。而两个人之间，只需要各自的频谱有一处很窄很窄的频段相同，就能产生共鸣。而我们像在用一个老式的收音机收听遥远的电台，只需要不停地扭动大大的旋钮，找到那个频段，就找到了「真正的朋友」。

毕竟盖棺定论之时，无论你是「上等人」还是「下等人」，总会希望世界上还有人能够时时想起你，觉得你是他的一个真正的朋友。

---


# 雷克萨斯的车

李老师，您好。刚看到您的最新微博，说喜欢汽车。可以说说雷克萨斯吗？褚老师曾经说过，所谓「高端」汽车品牌里他最没兴趣买的是雷克萨斯。（问题来自微博私信）

挑选汽车就像挑选葡萄酒一样，理论上说不能以品牌一概而论，而需要考虑具体的型号和出产年份；但实际上大多数人买车主要看的是品牌，所以品牌价值是汽车厂商的兵家必争之地。

丰田公司八九年创立雷克萨斯这个品牌，是为了推销LS400。当年的LS400可不是一般的豪华轿车：它是专门为美国市场设计的，采用4.0升8缸发动机，豪华车标准的纵置后驱结构，无论是做工的精益求精还是驾驶舱的安静程度，都可以「秒杀」当年的奔驰和宝马。当年连比尔·盖茨都买了一辆LS400，并且连续开了五年。

丰田也是很早进入中国市场的品牌之一，而且在当年中国市场对品牌价值的树立非常重视。它八十年代初「车到山前必有路，有路必有丰田车」的广告词，可以说和九十年代初「摩托罗拉寻呼机，随时随地传信息」一样，几乎代表了一个时代。国内汽车广告里，大概只有《蜗居》里宋思明的那句「开车的男人，有血性的，都希望拥有一辆路虎」可以和它媲美，不过那已经是零九年左右的事儿了。

可惜的是，丰田对雷克萨斯这个品牌的核心价值一直举棋不定，让人无可适从。最大的错误，就是当年把好好的「凌志」改成了「雷克萨斯」这个名字。「凌志」这个名字好就好在它就像「奔驰」、「宝马」这些名字一样，有一种灵动的感觉（soul），让人浮想联翩，令人心旷神怡，耳目一新。而「雷克萨斯」这个名字则普通、平庸，没有令人悠然神往的那种风骨。

雷克萨斯的轿车虽然还和当年一样，纵置后驱、做工精良、质量稳定、行驶安静，但这些和它的品牌形象一样，过于朴实无华，没有任何让人拍案叫绝之处。

但是雷克萨斯最大的败笔，还是它的纺锤形格栅。这个设计的初衷是希望一改以前老气横秋的气质，能够用一种激进的设计，让年轻人喜欢。可惜这就像一个平时生活朴素的女生，忽然开始浓妆艳抹，像换了一个人，只能让人觉得莫名其妙，避而远之。更何况汽车的设计最重要的是设计元素几十年如一日的传承，比如二战期间吉普车的造型，一直沿用至今。设计风格改来改去，反而有一种「暴发户」的范儿。它多了一番算计，却少了一份优雅。

这就是为什么蜗居里宋思明开的车绝对不能是雷克萨斯的原因。


---


# 迷信命

李老师，我是在《向上移动》认识您，包括微博每次看到您写的内容都有如沐春风的感觉，是不同褚老师的另一种广博和包容。

最近有件事让我翻来覆去睡不着，请您空闲时指导指导。按说我是不信“命”一说，谈恋爱后告诉家人，家人了解到女孩是“铁扫帚命”后对我很是担心。依据是我姑姑也是这种命，结果克夫改嫁，自己不能寿终正寝，一个表嫂同样出生于不吉利的月份，表哥十年前30出头死于白血病。

开始我觉得无所谓，但我爸已病故，我妈特别害怕再失去我，现在我也开始犹豫。让我犹豫的是姑娘对我很好，我不忍心仅仅因为可能会被克死或终生不幸一说分手，但被身边这些事例搞得不能坚定自己。我妈也陷入信命和不能要我这么辜负女孩的两难处境。

作为科学工作者的李老师是不会迷信命这一说，能不能说说您的看法。（问题来自微博私信）

—

看完你的故事，我真为那个一意孤行要嫁给你的女孩担心。如果我有机会见到她，听她讲了一个一模一样的故事，我一定会坚决地跟她说，千万别嫁给这个男生。

假设这个故事将来是这么发展的：你们俩冲破重重阻挠，历尽千辛万苦，不顾你母亲的坚决反对，终于走入了婚姻的殿堂。结婚之后，但凡出现任何波折 —— 孩子虽然聪明但是长得普通、工作虽然稳定但是升迁无望、买房虽然坚决但是只跌不涨、父母虽然行动如常但是小病缠身 —— 你第一时间会怎么想？

没错儿，无论真正的原因是什么，你百分之百会认为，这是女孩「克夫」的结果。

关键问题在于，出现让你产生这种想法的波折的概率，也是百分之百。因为这样的波折，是生活的一部分。

而你的想法其实也不能全怪你。你在婚前婚后收到了大量的心理暗示，致使「克夫」这个词儿和各种生活中不尽人意的故事一直在紧密关联着，在你的心里根深蒂固。大多数人都有这个倾向：一个错误的观点重复了很多遍，就不由自主地变成了事实。

那一个「科学工作者」是不是会迷信「命」这个东西？绝对不可能，因为这是一个逻辑错误。所有和「命」有关的逻辑命题，都认为如果事件 A 和事件 B 有关联（correlation），就可以推出它们之间有因果关系（causation），事件 A 导致了事件 B 的发生。

比如你观察到看电视看的多的孩子比较熊，于是得出了看电视容易让孩子更熊的结论。但是这个结论是不对的，正确的事实是熊孩子比正常孩子更爱看电视。

比如你发现风车转得越快，风就会越大，于是得出因为风车旋转而形成大风的结论。而正确的事实自然是因为有了风，风车才会旋转。

在中世纪的欧洲，人们发现虱子一旦离开人体，人就会很快生病，所以一度认为虱子是对健康有益的。但其实真正的原因是虱子怕热，所以人发烧的时候不会长虱子。

这些例子里的逻辑错误还算有情可原，因为至少依据的事实是基于统计数据的关联性。而说张三家的大门「路冲」所以儿子考不上大学，说李四家的寡妇是天蝎座的所以天蝎座的女人「克夫」，王五家全家都是属猪的所以没法儿不胖等等，则连基于统计数据的关联性都不存在，纯属令人啼笑皆非的无稽之谈。

所以说，如果那个一意孤行的女孩听完了我的建议，不顾我的坚决反对，还是一心一意地要和你结婚的话，用一句不科学的话来形容，你的「命」简直好得令人惊叹。将来你们婚后如果孩子聪明健康、工作轻松稳定、房子早早买入、父母行动如常，你一定不要忘了感谢她。

这叫什么来着？好像叫做「旺夫」的命，是吧。


---

# 自我介绍

李老师，您好！欣赏您看待问题又中肯又不落俗套，常常让人耳目一新。还过两个月就要离开学校去公司上班了，想请教您一个问题，进入一家新的公司，如何作一个好的自我介绍呢？（问题来自微博私信）

自我介绍与其追求标新立异，不如突出重点。而介绍自己时最关键的信息，是自己的名字。

我一向觉得，中文名字和英文单词一样，是最不好记的。绝大多数的父母给孩子起名字的时候，偏爱一些美好或者励志的寓意，完全不考虑别人是否容易记住。我去开会的时候见到很多陌生人，上来的自我介绍是「咱俩加个微信吧」，导致最后我甚至忘了微信里哪个陌生人对应的是他。

这一点英文就好很多，无论姓氏多么难记，至少名字千篇一律，非常好记。比如系里有一位教授叫Frank Kschischang，他幽默地把自己的难记的姓氏画成一幅编码示意图；我的导师叫Klara Nahrstedt，她干脆建议大家不要记她的姓算了。而无论是Frank还是Klara，都可以第一次见面就轻易记一辈子。

我自己的名字算是中文里相对容易发音的，但是对于外国人来说并不好记。在俱乐部打球时的对方队员，有时候上来就知道他自己记不住这个复杂的名字，于是问「Can I call you Bo?」简直就是当下要给我起个好记的外号。

对于中国人来说，我的名字则算是比较好记的。即使如此，我自我介绍时，多半还要补充一句这个名字的来历：「“葆”是草字头的“葆”。毛主席说了：永葆革命青春。意思是人虽然自然生命会衰老，但是政治生命可以永葆青春。」

我发现一提到毛主席，很多人都可以加深印象，更容易记住这个名字。

所以啊，如果你介绍自己的名字时可以介绍一下这个名字的由来和一条尽人皆知的典故，能让大多数人一次记住。也不要高兴得太早，以后见面时需要再把自己的名字重复几次，加深别人的印象，才算基本大功告成。


---

# 如何避免不成熟的行为

李老师，您好。相比较您和郭芳老师，微博里有些人的言论总是反复喜欢来奚落一些说过蠢话或者犯过错误的人。我是一个戾气很重的人，我想问您的问题是：如何避免残忍和不成熟的行为？（问题来自微博私信）

你听说过十九世纪初法国有一个叫伽罗华（Galois）的数学天才吗？

他十几岁时仅用了几年时间就提出了群和域的理论，用这套理论彻底解决了是否可以用根式求解高次方程的充分必要条件这个困扰了数学界三百多年的问题，奠定了抽象代数的根基，并普遍应用在现代编码理论中。

有一次因为一个偶然的机会。他遇到了一个向他倾诉衷肠的舞女。因为这个舞女，他接受了和一个枪法很准的对手决斗的邀约。

伽罗华在决斗前一天晚上彻夜未眠。他连夜写了一封长长的信，试图把自己所有未曾发表的数学发现悉数写到信里。天快亮了，他有点儿着急，写道：「不行，我没有时间了，没有时间了。」

他明明知道自己赢不了这场决斗，还是要去。

伽罗华终年仅仅二十岁，却是人类历史上最伟大的数学家之一。现代数学几乎半壁江山，都是基于他首创的抽象代数理论。

所以说，在社交网络上用一个匿名的账号和别人唇枪舌剑，就跟在公共汽车上几个陌生人为了一点儿小事儿就吵得不可开交一样，既没有什么必要，又没有什么意义。逞一时口舌之快，并不能带来什么「快意恩仇」的感觉，反倒是令看客对你刮目相看。而知书达理，温文尔雅的人，照样可以外柔内刚，笑傲江湖，指点江山。

我有一个缺点：胆儿小。我从小到大最怕各种动物，无论是趾高气扬的公鸡，还是街头流浪的小猫小狗，都能让我绕道而行。因为胆儿小，与其反唇相讥，我认为不如让步隐忍，全身而退。

我少年熟读的金庸笔下，姑苏慕容家「以其人之道，还治其人之身」的武功虽非绝世，至少会让对手想起「己所不欲，勿施于人」，自然而然地忌惮三分。

您要是确实血气方刚，咱要玩儿就向伽罗华或者普希金学习，玩儿点儿大的。自古英雄出少年，明知山有虎，偏向虎山行。

不过「决斗」之前，最好先提出一套代数理论，或者写几部传世的诗作。这样维基百科也能榜上有名，不枉此生。

---

# 逻辑思维

李老师您好。我有一个问题想请教您：您平时有没有刻意训练您的或者您学生的逻辑思维能力？如果有，可否分享一些有效可执行的方法？期待您的答复！（问题来自微博私信）

有个冷笑话是这么说的：博士生刚入学看不懂论文，抱怨「我怎么这么笨，连篇论文都看不懂？」等几年后再看不懂论文，开始抱怨「这个作者怎么这么笨，写篇论文都写不清楚？」这时他就可以毕业了。

正好前几天有个学生来找我讨论她论文的草稿，我把第一页看了好几遍，还是没看懂。

作为一个已经毕了业的博士，我说：「你的论文写得逻辑不清楚啊，我看了半天都没明白。」

她反问：「我觉得逻辑很清楚啊，哪儿不清楚了？」

这个问题很难，我一时竟然没有回答出来。

一篇文章是否容易懂，直接反映了作者的逻辑思维和写作能力。不同作者的文字，只需要读一小会儿，高下立判。但是我一直悲观地认为，逻辑思维能力如果靠老师教，不是一时半会儿就能教得出来的。问题就在于我觉得难懂的文章，作者却并不这么觉得。而说清楚为什么难懂，比重写一遍还要艰苦卓绝。

所以我认为，提高逻辑思维能力，基本上得依靠自学成才。

那这个「自学成才」该怎么学啊？—— 如果不是靠看《罗辑思维》的话。

首先，您工作里经常做的幻灯片，尽量不要用那种一行一个圆点儿的「bullets」。因为用「bullets」的潜台词是，您没有仔细想清楚它们之间的逻辑关系。无论是递进还是转折，全被「并列」这种最为枯燥单调的关系代替了。做幻灯片是为了讲一个引人入胜的「故事」，故事里有时「花开两朵，各表一枝」，有时「柳暗花明又一村」；起承转合之间，有时归纳，有时演绎，这样才能讲者眉飞色舞，听众茅塞顿开，意犹未尽。

其次，您应该尽量多写原创的文章。写作可以强迫您整理自己的思路，是提高逻辑思维能力最有效的方式。小时候我们写议论文，老师告诉我们要写清楚论点、论据和论证方法。但其实我认为科学论文写作的三个要素在日常写作中也非常重要：「需要解决的问题是什么？」（What’s the problem?）「这个问题为什么重要？」（Why it’s important?）「解法为什么有新意？」（What’s new?）

最后，您需要培养独立思考的能力，而非人云亦云。这种批判性思维的特点，是不轻易认同别人的论点，而是要仔细研究他的论据和思路，同时想想相反的观点有什么道理。刘瑜写过一篇小说叫《那么爱呢》，里面有一个人特别爱抬杠，爱说「这话也不能这么说」。这么说话虽然是聊天的大忌，但精神可嘉，因为适度地批判，才能更好地继承和发扬光大。

比如您快结婚了，在考虑什么时候贷款买房。无奈房价最近刚刚大涨，高不可攀，而且随时都有可能下跌。大家都说应该节衣缩食赶紧买，因为再等就再也买不起了。你这时不能盲目跟风儿，而是应该好好想想相反的结论是否逻辑上也说得通：说不定应该先租房子住，等到手头宽裕一点儿再买，因为理性的投资从来都是买跌不买涨。

仔细衡量正反双方的立论，正是独立思考的体现。任何人都会「先入为主」地去寻找对自己有利的论据来论证自己偏爱的预设立场和观点，英文叫「confirmation bias」。独立思考的好处，就是靠经常去质疑似乎是正确的观点，来尽量纠正这个归纳推理中的系统误差（systematic error）。

您看到这里，要是说：「这个博主怎么这么笨，写篇微博都写不清楚？」

那恭喜您，差不多可以毕业了。


---

# 变得细心

李老师，你好。想再麻烦你一次：请问在工作中，如何让自己变得细心，不出差错？是一遍又一遍得提醒自己“要小心，慢慢来”这样吗？[笑cry]前几天工作出了差错，很内疚，对自己很失望唉…[伤心] 谢谢。[可爱] （问题来自微博私信）

我们小学中学参加各种考试时，都可能遇到考试结束时间还没到，题已经做完了的情况。这时你是会提前起身交卷离开呢，还是反复检查答案，直到最后一分钟？

相信你的老师一定曾经强调过，做完了题一定要反复检查，不要提前交卷。

老师说得很有道理啊：题目大多有陷阱，自己也可能粗心大意，好好检查一下，可以提高成绩。提前交卷，你早几分钟离开教室还能干什么去？

可我倒是觉得，这也得看这个考试是否重要。如果是高考或者GRE，那当然要全力以赴；如果只是个普通的期中考试或数学竞赛，提前交卷有诸多好处：自己可以更加自信，心情愉快的同时，说不定还能给同学们带来一点儿心理压力。

所以说，做任何事情，不出差错的概率和你投入的时间是相关的。你要是投入了足够的时间，自然可以把不出差错的概率降到最低。可是这样做到底是否有必要，那就要看这件事儿的重要程度，是否值得你的时间。不要忘了，把一件事情迅速、高效、果断地完成，既能在领导面前体现你的能力，自己也能从中得到一种乐趣。

我在清华上学时就曾经参加过一次全校的英语竞赛。那场考试我不但第一个交卷，还得了第一名，并获得了一笔奖学金。如果仅仅是第一名而不是第一个交卷，我想也不会到现在还记忆犹新，到这个回答里来津津乐道。

不去斤斤计较地避免出错还有一个好处，可以减轻工作给自己带来的心理压力。我是一个细心的人，事必躬亲，力求完美，直到后来连做梦都梦到上课的时候把一道习题讲错了。凌晨从梦中惊醒的时候，我意识到其实一个人对心理压力的承受能力比自己想象的要差很多。

这样说来，不那么重要的事儿就不要花太多时间，尽量拖延到最后，然后高效粗线条地完成。即使出了错，说不定结果也没有你想象的那么糟糕。

当然，如果这件事情确实非常重要，甚至重要到可以决定今后的事业发展，那绝对要投入大量时间，认真做得尽善尽美。但是有很多事儿，比如分析财务报表或者开发程序，需要非常专心才能保证万无一失。对付这种重要而又容易出错的事儿，我认为「不能一口吃个胖子」，「仗要一个一个打」，要「论持久战」。一次不要工作太长时间，前一天的工作后一天检查，分而治之，每一段时间尽量高效地完成一个小目标。如果需要和别人合作，就更需要提前开始，预留足够的时间检查合作者的工作中是否有问题。

「胆大心细」，重要的事儿投入大量时间尽善尽美，不那么重要的事儿意识到「离了你地球照转不误」，是我对付工作的哲学。


---

# 内向

李老师好。我怀疑自己有社交恐惧。每次和别人面对面交流总会有脸麻的感觉，就像针扎一样。工作需要上台讲话，说话就结巴，恨不得低着头读完。老师我该如何练习，让自己生活更好一点？（问题来自微博私信）

我小时候，有一拨儿孩子有一个共同的特点，家里来了客人就特别兴奋，又跳又闹的来劲儿。那会儿管这拨儿孩子叫「人来疯」。

而我恰好和你一样，最怕的就是见到陌生人。我见到陌生人就紧张得不得了，绝对属于「人来疯」的反面儿。就像你说的，现在好像管这叫做「社交恐惧」，英文叫「anti-social」。

我想，如果用朋友圈儿里时不时冒出来的那种测试性格的小测验测一下，我的性格应该属于内向型（introvert）。我崇尚低调，从来不发朋友圈；不擅长参与集体活动；从来不踢足球，偏爱一个人长跑；与其去参加一个什么校友会活动，更喜欢在家看书写论文编程序。

这样的性格，大概是我害怕陌生人的原因。

其实像你我这样内向兼「社交恐惧」的人，还有很多。有的调查发现，这样的人，至少有三分之一。

然而现在的工作大多数都要和陌生人交流，开会要积极发言，随时要拿着「PPT」上台讲话，对外向性格的人极为有利。

我刚开始也和你一样，而且越是重要场合的讲话，我就越紧张。不但上台紧张，上台之前也紧张，甚至前一天晚上准备的时候就开始紧张。我紧张得需要把要说的话全都死记硬背给背下来。

日子就这么一天一天过去了，幸亏我只是上台说个话而不是表演钢琴独奏——那样我一定紧张得一个小节都弹不全——我发现也没有出太多洋相。

但是不知道你是否意识到，其实这样的性格没有什么不好。恰恰相反，内敛性格的人，更有可能
利用自己一个人孤单的时间（solitude），深入地去钻研一个问题，精益求精，最终「无招而胜有招」，达到「独孤求败」的境界。

苹果公司设计的第一台计算机，就是当年Stephen Wozniak 足不出户，拿着烙铁和各式集成电路芯片在自己家里设计调试出来的。Wozniak这个人是典型的内向兼社交恐惧的性格，他虽然不擅长上台讲话，但是没有他四十年前设计的苹果计算机，就没有今天的苹果公司。

在这个「直播」、「网红」、「大V」流行的时代，也许我们更需要的不是「人来疯」的那拨儿孩子，而是爱「宅在家里」的Wozniak。


---

# 失恋

哎，老师，我和前女友认识四年，在一起三年，因为读研了，异地了一年，在这一年中因为一点点小摩擦，在她的身边她觉得有个人更懂她，而我说话可能更加现实直白，一个星期前我们分手了。我觉得好痛苦，为什么四载不如几月珍，为什么直接宣判我死刑，而选择和别人在一起？

真的特别痛苦，如果我做错了，可以告诉我，给我一次机会去改，但是一直冷战逼着我说分手，上周我跑了1000多公里偷偷去找她，结果等来的却是，她和那个男生一直在微信上聊，并且两个人都有了好感。

我觉得有时候如果她能想想我们三年的感情，何必会成这样子？（问题来自微博私信）

如果你去知乎搜索「失恋」这个关键字，第一个跳出来的问题是「怎样快速走出失恋？」这里面有四千六百三十四个回答等着你去读，最高赞的回答有六千七百一十七个赞同。

可是我还是应该负责任地告诉你两个事实。

一、千万不要抱有幻想，无论你怎么做，一切已经无法挽回；

二、「快速」地走出失恋是不可能的。

毛主席一九六六年给江青写过一封信，信里说「天下大乱，达到天下大治。」失恋给人的感觉，就是一种「天下大乱」，一触即发，声泪俱下。

有人建议去旅行、去运动、去读书、去恋爱，但是你会发现，「天下大乱」的时候，其实这些都不管用。即使你真的试图去再爱上别人，每一次微信提示音响起，每一次手机在身边震动，你都会问自己「是不是她？」

我高中有一段时间，曾经一度发疯似的开始给她写信。信的内容我不记得了，但是不外乎在问她「为什么」这样的问题。说是写给她看的，但是其实只能算为了自己而写。因为我无法知道信寄出以后，她到底会不会打开信封，把信看完。

有一次妈妈发现了我在写信，说你还想不想好好准备高考提高学习成绩了？我非常不争气，一触即发，声泪俱下。

我自始至终没有收到过她的回信。也无从知道所有那些悬而未决的问题的答案。

三十年后，我没有加她的微信。因为我不能肯定，如果我发出请求成为她「新的朋友」，这个请求不会过期。

不过你放心，时间是一付万灵药。时间会在你痛苦时、反思时、声讨时、回忆时，一年年不经意地过去。直到有一天，你会发现自己的记忆越来越模糊，如果不去翻看以前的照片，你会连她美丽的模样都记不清了。

在这段痛苦的时间里，不知道哪里来的力量，你也许会通读萨特、叔本华、尼采的著述，迷上西方哲学，成为一名中青年学者，著作等身；你也许会沉迷于各路论坛知乎微博，横刀立马，舌战群儒，成为一名「十万加」「大V」作家；你也许会云游四方，看破荣辱成败，大彻大悟，成为一代高僧。

「天下大乱，达到天下大治。」

毛主席说得对。


---


# 思想习惯

李老师，您好。请问如何驾驭或改变自己的思想习惯？最近在弗兰克 · 哈多克《意志的力量》中看到一句话，说一个人的脆弱或不幸，虽然可以追溯到出身和环境，但归根结底要看这个人的思想习惯。而我感觉自己很容易陷入没有意义且重复的想法或对未来的幻想。 想听听您对这个问题的看法。感谢。（问题来自微博私信）

有一个英文短语叫「gut feeling」你听说过吗？

世界杯淘汰赛最近比利时绝地反转赢了日本那场看了吧？伤停补时最后一分钟，从比利时守门员手抛球开始，一下儿就传到日本队禁区。第二次传球时，比利时前锋卢卡库跳起来假动作一漏，成功吸引了一位防守队员，球直接到了队友脚下，近距离射门绝杀。

卢卡库跳起来漏球的假动作，当时是怎么思考的？

他看不到自己后面的队友，没有时间充分地衡量这一漏到底风险有多大。

他靠的就是「gut feeling」，是一种自信，一种直觉。直译为中文应该是「用肚子想问题」。

充分相信你的「肚子」（trust your gut），其实可以解决很多问题。比如你作为公司领导面试了一位员工，有优点有缺点，到底给不给「offer」？比如你研究过程中有两个想法，时间不多了，到底继续去琢磨哪一个？比如你大学毕业出国，可以选择美国，也可以选择加拿大，你准备去哪里读书？

这些问题都摆在岔路口上，决定了你到哪儿读书到哪儿工作，工作怎么做，跟什么人合作等等，按你的原话说，它们足以「驾驭和改变」你的生活。

可是我们做这些决定之前，真的没有时间去列出具体的表格或推出具体的公式去优化最终的目标函数。我们能做到的，只有相信自己的「肚子」。

我上大学时有一个室友，这位同学有两大业余爱好：申请入党和参加舞会。有一次开会时，他的发言一鸣惊人：班委是团委的左膀，团委是班委的右臂。他积极要求进步，头一次入党申请没有通过，一度伤心地哭了。去参加舞会时则像换了一个人，西服笔挺，头发锃亮。有一次从七食堂舞会回来，他非常纠结，因为他发现有两个女孩儿喜欢他，不知道该挑哪个了。

我们都说：「这还不简单，谁跟你说话多就挑谁呗。」

他思考了一下：「她们都没说话啊，都在默默地注视着我。」

你看，「trust your gut」其实也没那么容易，时机转瞬即逝，过了这村儿就没这店了。

下回再遇到这种可以改变自己生命意义的事儿，别去问弗兰克 · 哈多克，而是盲目地相信自己。



---

# 不要表白


李老师，您好！关注您的微博已经有些日子了，每次读您的文字正如大家评论的那样，散发着一种理性睿智的温暖感。

想要请教您的是一个偏个人情感方面的问题，描述为：在异性交往这方面，我发现我有着一个让其他人无法理解的观念，从心底里我会认为身边女生只会有女朋友、普通女生两类，当然同学、实验室伙伴那种特殊关系的除外。

这个问题挺困扰着我，这不昨天刚和心仪的女生大大方方的当面表白了，因为女生即将面临今后一年甚至几年的出国生活而被拒绝。回到寝室，半夜躺着醒来把所有相关信息和联系方式都删了，也想着今后应该不会再联系，完全没有一点那种“买卖不成仁义在”的情谊了。

对此，我自己分析的原因有以下两点：首先我认为可能是我自己太功利了，导致和女生分手、表白失败，从此两人就是天各一方那种，无需再有任何联系；其次，我确实在男女交往这块缺少必要的认识，甚至是男女间普通的朋友关系的认识上也有问题。

如能有幸看到李老师回复，不胜感激！谢谢您！（问题来自微博私信）

咱们来换位思考一下：如果你是这个女生，你应该如何选择？

一个男生冷不丁跟你说，他对你早已心仪已久，并且觉得你们两个人再合适不过了，愿意跟你发展更进一步的亲密关系。「合同」已经草拟好了，你是签还是不签？

这有点儿像一桌酒席：男生的这杯酒已经高高地举起来了，还振振有词地说：来，给个面子吧，干了？

你肯定会想，这男生以为他自己是谁啊？

无论这男生以前是不是个好朋友，你的最优策略一定是：果断地、坚决地、不留任何余地地拒绝他。但最好能找一个相对客观的理由，让他觉得是因为不可控的客观因素。

你瞧，你心仪的女生完全是按照这个策略处理这件事儿的。即使换成我是这个女生，也一样会这么做。

如果你的「表白」再高调一点儿，搞个什么公开场合九十九朵玫瑰啊拉个横幅啊什么的，相当于八抬大轿敲锣打鼓威逼人家签这份「合同」，那被拒绝的概率就更加接近百分之百了。

马克思主义哲学里说：「事物的发展是螺旋式上升的过程」，「从量变到质变」。其实恋爱也是一样。

「表白」有点像高手过招里亮出自己的底牌（play the trump card），风险极大，又完全没有任何好处。「质变」之前「表白」，注定会失败；「质变」之后「表白」，又显得画蛇添足，多此一举。

这时你一定会问：我就是想确定一下我们正式男女朋友的关系啊，为什么不行？而且我们俩以前是很熟的朋友加同学啊，又不是萍水相逢。

关键的问题是，为什么一定要强迫一个女生答应跟你确立正式男女朋友关系？确立与否，照样可以一起吃饭、喝酒、看电影、唱歌啊。

与其去「表白」，不如拉上她一起到酒吧看世界杯，一起到上海法租界吃零食，一起看「创造101」，或者一起到黄埔江边练习人像摄影。

当然如果你们能一起学习，一起准备英语考试，互相抽背单词，一起讨论一道悬而未决的疑难习题，那绝对是天下最浪漫最铭心刻骨的爱情。

与其大半夜的删这个删那个，给她打个电话聊聊天吧，说不定还有希望。

就是千万别再「表白」了。


---


# 边界感

李老师，您好。想请教您关于边界感的看法。最近发现在和朋友陈述自己的想法时，对方在我没有问她的意见时就已经直言不讳她的想法。比如：我说我想去打工旅游而不是现在就定下来。对方立马列举了各种原因告诉我打工旅游不好：耽误的时间成本难以弥补、打工旅游的工作都很基础工资也少、去外企会是更好的选择….听到这些我很不舒服，因为从始至终我没有问她的意见，只是告诉她我思考后的决定，我甚至会觉得对方这样是不尊重，虽然她是为我好。想问问李老师如何处理这种情况。谢谢！（问题来自微博私信）

有一个GRE英文词汇叫「gerrymander」你听说过吗？

中文大意是，把选举的选区人为划分得曲里拐弯儿的，为了自己党派选举时可以多得几张选票。

英文作为一种交流的语言，绝对像Intel处理器一样是一个复杂指令集（CISC）：一个单词儿竟然能代表一大块儿复杂艰深的含义，而这个「gerrymander」就是一个很好的例子。而中文则是ARM处理器里的简化指令集（RISC），每一个词汇的含义简单有效，字字珠玑，组合起来又能形神兼备，行云流水。

我们两个人之间的「边界感」，有点儿像「gerrymander」，似乎随便我怎么定义都可以。

你作为反对党，如果说这样定义边界有问题，我一定会疑惑不解地、满怀幽恨地、恨铁不成钢地跟你说：「我这还不是为了你好？」

为了你的前途，为了你的事业，为了你后一半儿人生的幸福，作为你的父母、你的好朋友、你的闺蜜，甚至你的战友、领导、老师、同学，我不告诉你残酷的事实真相，我不去关心你的个人问题，难道还会有别人像我这么好心吗？

我吃过的盐比你吃过的饭还多，走过的桥比你走过的路都长，我参加红军长征时你还不会走路呢，你这真是「好心当作驴肝肺」啊。

你现在不学习长大了哪儿来的饭吃？现在这也不行那也不行将来到哪找这么好的去？现在不结婚将来鸡飞蛋打了怎么办？越早生孩子孩子越聪明，这么简单的道理怎么就没明白？你看别人家都买房，你怎么还在犹豫？

于是组织上要找你了解情况，居委会要找你促膝谈心，班主任辅导员要找你做思想工作，让你一定要记住：集体荣誉高于个人利益，不要自私自利，要有崇高的理想，在奋斗中实现自己的个人价值。

对所有的这一切，你作为反对党，该怎么回应？

你可以直接上英文这个复杂指令集：「Why do you care? 」

你可以温文尔雅有礼貌：「我已经没救了，天要下雨，娘要嫁人，您已经尽力而为了，将来不会后悔的。」

你可以援引王朔《过把瘾就死》里的一句话：
「我觉得你在思想上太关心我了！都快把我关心疯了！」

你也可以用标准带北京口音的普通话反唇相讥：「有完没完？」

最好再用阴暗地的、叛逆的、让她觉得不打你一顿就不解恨的口气加上一句：「您管着吗？」

祝你旅途愉快，一路顺风。



---


# 英语学习班


看到微信里有一个「每天20分钟120天新概念英语」学习班的广告：「仅需399元」，如果能每天「打卡」不缺勤就可以全额退款。

这个英语速成班的理念是：全文背诵《新概念英语》一点儿用处也没有，需要用「拆解重构」的方法学习，学习一篇，相当于背诵一百篇。

「不用背的新概念，听说读写全面提升。」

你还别说，我小时候有一两个暑假，曾经认真自学过《新概念英语》。那是八十年代初，英语教材匮乏，我除了学过《新概念英语》，还学过陈琳英语和许国璋英语，仔细研究过十六种时态，从一般现在时到「过去将来完成进行时」（would/should have been doing）。

我无法想象，三十年以后，还有人去学习《新概念英语》。

无论是《新概念英语》还是陈琳许国璋英语，最关键的问题是学英语的理念是完全错误的。

学习英语不能靠精读的办法，靠学习语法、强背单词、全文背诵、「拆解重构」的训练来学。而《新概念英语》每篇文章极短，文章之间没有语境的联系，第二册和第三册之间难度跨度过大，作为英语教材，早就该过时了。

而是应该尽量脱离中文语境，靠大量快速地接触英文的办法来学。比如阅读，应该找大量报纸、杂志、小说，看完一遍坚决不看第二遍。单词不懂的可以根据上下文瞎猜，也可以查英英词典，阅读更简单的英文去理解更复杂的词义。

那如果《华尔街日报》、《经济学人》什么的我都看不懂怎么办？

学英语跟学数学学钢琴其实差不多，一口吃不成一个胖子，需要长期坚持，循序渐进。看不懂《经济学人》，可以看青少年小说（Teen fiction）；看不懂青少年小说，还可以看儿童读物。

所以「120天每天20分钟」是学不会英语的。

哈哈，写到这儿我都想开一个英语班儿了：「由学贯中西的北美知名大学教授领衔主演，让您在轻松愉快的氛围中享受英文的魅力。」

这不，宣传文案都写得差不多啦。


---


# 英语口语

李老师您好，看到您谈到学英语的问题，我作为一名英语专业的学生不免有点小激动，因为我就是那个还在抱着新概念四朗读的人哈哈。

谈到学英语，大多数中国人最津津乐道的恐怕是如何能短时间内掌握一口流利的英语口语，国内各种培训机构推崇的也是这种短时间、高强度（intensive）的学习方式，但学到的大多是一些类似于“how do you do?”之类的套话，长时间不练也就忘得差不多了。所以说白了还是得靠自学，国内学习口语缺乏语言环境，只能自己给自己创造环境，好在现在podcast之类的媒体软件很发达，想在国内练就一口伦敦腔也不是什么难事。但语言学习逃不掉面对面交流这一坎，自说自话时很顺，长时间不开口用英语和人交流等到再用时还是会语无伦次，尴尬百出。

语言学上有预制语块（prefabricated chunks）的概念，大意是我们交流中所使用的词汇、句子大多是我们之前就储存过的，交流时就是自动提取、匹配这些语块。按照这个概念，我们可能需要大量积累各种场景里所需要的表达，然后烂熟于心（proficiency），变成一种本能。

这样我们能解决输入的问题，然而流利的表达就不止于语言了，en, er, a 等语气词就好像中文交流中有人特喜欢说然后，然后，然后……一样烦人。

请问李老师，如何能做到交流中Clarity and Grace并重呢？谢谢！（问题来自微博私信）

——

语言学（linguistics）我一点儿不懂，所以我今天要说的「理论」全凭朴素的直觉，在你这个英语专业毕业的专家面前，无异于班门弄斧。

你提到的第一个问题是英文口语如何学习。我认为绝对应该从简单的对话开始。我自己的口语就是上小学时看电视跟着一个叫《跟我学》（Follow Me）的英国教学节目自学的。整个节目六十集，全部是情景对话，内容由浅入深，很多段落现在都能背出来。初中时又跟着一本叫《现代美国口语》的录音带学，还是情景对话，基本上奠定了我的英语口语基础。

我觉得口语是否能学好，这些教学节目或教材的质量非常重要。很多口语教材里的英语不够地道，自然也就学不到标准的口语。比如两个人见面最简单的寒暄，常见以下的对话：

Hi, Helen! How’s it going?

Fine, thanks — and you?

Just fine. Where are you off to?

To the library. I’ve got a history exam next week and need to start studying. Ugh.

Oh, no. Well, I’ll see you later then. Good luck! 

Thanks. See you later.

这段对话里有几句，大多数中国学生说不出来。比如「Where are you off to?」很多人会说「Where are you going？」但是后者稍嫌正式，前者则更轻描淡写。又比如「Oh, no.」有一点儿「同情你」的含义，并不是要否定或拒绝什么事儿。这些都是表面很简单但实际上相当地道的英文。

像这样的英文口语，难就难在用到的全都是极其简单的词，但是变化多端而飘忽不定，需要多听、多说，大量地重复练习，用起来才随心所欲。

这里推荐美国国务院为外国人学英语而编纂的《Everyday Conversations: Learning American English》，上面这段对话就是摘自这本小册子。（链接在评论里找）

你提的第二个问题是如何在说话时尽量避免夹杂en、er等语气词。我先给你讲俩故事吧。

看过最近Google I/O大会上的Google Duplex的演示吗？计算机可以打电话给餐厅预约时间订座位，对话清晰自然，甚至可以说是通过了图灵测试。

有趣的是，谷歌最近披露，早期的实验结果其实并不令人满意，预约电话经常失败，因为接听的人感觉像在和计算机说话。后来加入了en、er之类的语气词，让完美的句型里掺杂了一点儿停顿和犹豫，反而成功率大大提高，因为普通人都这么说话。

我多年前在微软研究院访问时，有幸和清华当年最著名的少年天才、邓小平爷爷当面表扬「计算机要从娃娃抓起」的李劲合作共事过一段时间。他说英文最喜欢加「basically」，一段英文甚至要加进好几个。不过，从来没有任何人在意这一点，也没人抱怨听不懂他说的话。

所以说，没必要过于追求完美。只要你能用英文清晰地表达自己的观点，多说几个en、er、basically，白玉微瑕，天才还是天才，没有人会在意的。


---

# 保持身体素质


李老师好！我是通过褚老知道的您，特别想问问，您是怎样保持身材和身体素质的（褚老说您的身体保持的极好）。据说男的三十以后身体开始走下坡路，我快29岁了，平时也有时间并且也在锻炼，很想和您请教下一个科学的健身和饮食计划，感谢！（问题来自微博私信）

一

运动和投资一样，其实我们最需要的是一个长期的策略。也就是说，和科学的健身饮食计划比起来，最关键的问题其实是：如何能在四十、五十、六十、七十岁时一直坚持运动。

很多人年轻时时间比较充裕，运动健身非常积极；而一旦到了四五十岁，体能直线下降的趋势一旦显现，就失去了运动的热情。

而绝大多数有关运动和健身的建议，都在强调「三个月见效」，如同投资建议强调短期收益一样。

别告诉我「运动产生多巴胺，会带来快乐的感觉」：相比躺在沙发上看电影，长跑或者举重绝对是一种痛苦的体验，毫无快乐可言。

长期坚持一种给自己带来痛苦的东西，太不容易了，依靠的动力不可能一成不变。所以最重要的是如何想尽办法，找到适合自己的动力（motivation）。

二

很多人喜欢在微信朋友圈晒自己的成绩，点赞数一多，动力也相应而来。

但是靠朋友圈提供动力有两个问题。一是每周三四次运动如果全都晒出来，很快朋友们就看得没劲儿了，长期来看点赞和评论只有可能单调递减。

比如这篇微博是我刚跑完步在星巴克一边喝咖啡一边写的，正打算晒一下刚才的成绩。你会发现，点赞数多半儿不如平时。

二是像力量训练这样必须长期坚持的运动无法截屏晒图片，不容易分享出来。

当然，孙俪可以让邓超给她录一小时的健身视频，再专业剪辑加速发到微博。她一定会收到无数赞美，「身材太好了」、「这什么器械我都不知道啊」。

而你要是这么费劲儿折腾视频来分享，一定回应寥寥。

所以，朋友圈微博晒成绩，不是一个长久之计。

三

那报名跑马拉松呢？有了目标是不是就可以经常运动了？

我同意有一个近期的目标确实非常重要。但是马拉松是极限运动，对体能要求很高，多半儿跑了几次就懒得跑了，能常年坚持的是极少数。而且，马拉松训练要求每月跑量至少两百公里以上，相当于每周需要五六个小时为跑马拉松「工作」。大多数人没有这么多时间，所以我认为跑马拉松是一种时间上的「奢侈品」。

太重视跑步还有一个问题：运动的项目过于单一。长期运动最重要的是以力量训练为「主食」，辅以花样繁多的有氧训练当「配菜」。如果每周只有五六个小时，正确的做法是拿出一半时间做力量训练，余下的时间尽量尝试各种运动项目的结合：跑步、动感单车、游泳、拳击、跳绳、瑜伽、普拉提、羽毛球，不一而足。

四

我在美国上学时有一个好朋友叫张戎，当年是清华十杰，绝对是一等一的「大牛」学霸。现在戎爷年龄摆在那儿，已跻身「大佬」行列。张戎是运动健将，当年跑铁人三项的，现在经常参加马拉松比赛，竟然跑过很多人梦寐以求的Big Sur International Marathon。

几年前张戎来大瀑布玩儿，我们早上一起沿着尼亚加拉河约跑十五公里，他一路闲庭信步，谈笑风生，我则不得不全力以赴。但我跑完了觉得心情好极了，平时多运动，竟然可以和当年可望而不可及的运动「大佬」比肩。

所以说，更靠谱的目标应该是自己生活中的朋友。无论什么年龄段，都可以找到三两好友，或遥相「PK」，或亲临其境，成为一种永恒的动力。

我前一阵儿在西安一个小馆子新认识了两个「酒肉」朋友。大家酒过三巡，相约有机会时一起轻装上路，以最快的速度挑战华山。

今天早上，我想着这个约定，顶着炙热的朝阳，以均速六分四十五跑完十一公里。水壶里弹尽粮绝时，我在一条几乎没有人的自行车道上。远处的高压线告诉我，这一切的痛苦没有什么意义。

想着的只有那个和以前素不相识的两个人的一个约定：一起以最快速度奔赴华山绝顶，和「华山论剑」那块大石头合影留念。

---


# 领导与 push


我来问李老师个问题。push学生push不动怎么办？

组里有几个学生，进度有快有慢。叫他们发周表报告进展，有的人一眼就能看出来周周都没干啥。一件事情布置下去，问一次没啥进展，再问还是没啥进展，我都懒得问了，显得老师反而急吼吼的沉不住气。你说批评吧，怕批评重了想不开。不批评吧，那就有点进展表扬一下，其实也很违心，因为实在是太差，找不到亮点，硬要表扬，他们也没法进步。灌鸡汤吧，也并没有效果。所以就处在一种：明明知道学生很差，却又怕告诉他们事实会导致工作更不好开展的局面。咋办呢？（问题来自微信）

——

「Push」这个词儿老是让我联想到马克思说的「资本家剥削工人的剩余价值」，似乎有点儿贬义，要不然咱换一种说法。

咱们就来聊聊「领导艺术」吧。

一

有一特好看的电影叫「When Harry Met Sally」你看过吗？电影中男主角 Harry 有一句名言：「There are two kinds of women: high maintenance and low maintenance.」

其实员工也有两种：「high maintenance」和 「low maintenance」。管理这两种员工的风格截然不同。

「High maintenance」的员工，需要一种细致入微、甚至有点儿封建家长式独断专行的管理风格。比如敏捷软件开发（agile development）的核心叫「Scrum」，一度非常流行，就是这种管理风格很好的一个例子。「Scrum Master」事无巨细事必躬亲地去跟踪员工的进度，每天都要站着开一个十五分钟的会。每个人都必须发言，并且要向所有成员当面汇报你昨天完成了什么，承诺你今天要完成什么。

作为领导，你自然就要多花很多时间和心血，严格控制和跟踪项目的进度，制作和更新 Gantt charts。所以说，这绝对是「high maintenance」。

你也许会问，科研往往需要的是一点一滴的积累和井喷的灵感，怎么能靠这种天天检查进度的办法来管理呢？这个问题其实2010年马里兰大学的两位教授就研究过，发现其实是行之有效的，还专门写了一篇论文来总结他们的成功案例 [1]。

但是另外还有一种员工，是典型的「low maintenance」。他们的求知欲和创新能力都很强，更乐于独立思考，独立管理自己的时间，直至独立完成一个引以为傲的项目。管理这种员工最好的方式是充分信任他们，「无为而治」，英文叫「laissez-faire」。唯一需要做的就是充分提供所需的资源，他们有问题时也可以随时向你咨询。

当然最可怕的一种员工是眼高手低，自己没有独当一面的能力，却好高骛远。就像「When Harry Met Sally」里 Harry 对 Sally 说的：「You are the worse kind: you are high maintenance, but you think you are low maintenance.」

二

一个微博上的问题，如果没有任何回报，大概不会有人去回答这个问题。

但是如果回答这个问题有一千块钱收入，一定会有不少人愿意去回答。

这符合博弈论里的一个基本假设：每个玩「游戏」的玩家都是理性的（rational），他们不仅有愿望而且有能力可以将自己的收益最大化。

诺贝尔经济学奖得主、著名经济学家Milton Friedman说过：「The world runs on individuals pursuing their self interests.」

如果干得好坏一个样儿，不会有人愿意努力工作。作为领导，你可以设计一种合理而有效的激励机制，在「比学赶帮超」的气氛中，让多快好省地完成项目的员工脱颖而出，得到他们应得的「分红」。这就是为什么公司里每年有绩效评估的原因：绩效评估的结果直接和奖惩机制挂钩。

当然，科研工作的「分红」不一定是奖金，也可能是去夏威夷开个国际会议的机会，是某个全校优秀论文的奖项，是提前一两年毕业，甚至仅仅是因为在截止日期之前写完了一篇重要论文所得到的通报表扬。

关键之处在于，你设计的激励机制里这些潜在的回报都绝不是你临时想出来的，而是早就白纸黑字有章可循，公平合理。绩效评估的设计绝对不能变相鼓动员工之间你死我活相互竞争，而是尽量鼓励合作双赢。在最好的激励机制下，当每一个员工都竭尽所能将自己的收益最大化时，实现你自己既定目标的可能性趋于最大。

三

古老的「鸡汤」，或者说好听点儿叫「情怀」，也不一定就一点儿用都没有。

比如有的公司 —— 我不说估计你都能想起来是哪家 —— 依靠的正是其领军人物的领袖魅力（charisma）。

而且往往最优秀的员工所看重的，正好就是这些散发着领袖魅力的「情怀」。

你一定会问，可这样的领袖魅力可遇而不可求啊，跟咱这种「衣带渐宽终不悔」的普通中青年小领导有关系嘛？

我倒是觉得，这样的领袖魅力其实就是一种自然而然的亲和力，就像夏天里家里的姥爷坐在胡同口的藤椅上，一边扇着扇子，一边讲着一个引人入胜的三国故事。

而你给大家的，不是什么「鸡汤」，也不是什么「情怀」，仅仅就是茶余饭后润物细无声地讲了几个故事而已。

[1] M. Hicks, J. S. Foster, “Adapting Scrum to Managing a Research Group,” http://t.cn/RgNTd8i


---

# 处理情感冲突


李老师，您好！关注您的微博有一段时间了，常看您回答一些年轻人的问题，今天我也有个小问题想请教您。

我即将与父亲同事的女儿去上海玩几天，还有另一个她自己的朋友同行，与我更是初相识。客观地说我们的关系属于几年未见的、非常普通的朋友，在旅行中做个伴。

由于上海某乐园正值旺季，票价比平时贵，算上一些附加消费大约会达到700元一天。我旅行是用的自己的存款，考虑到研究生开学还会花一大笔钱，我不太愿意花这个钱，所以与另两女生商量前一天晚仍住某乐园附近，但去的那天分头行动，她们俩去乐园玩，我回城内看艺术展，晚上再汇合。但她们不放心我一个人，就退掉了房间说不去了，但又说非常遗憾。我感觉自己很扫她们的兴，因为她们确实很想去，所以目前我花这笔钱跟她们一起去乐园仿佛成了维持她们旅行心情的唯一方式。

我感到不解的问题是，我应该如何处理自己需求和别人（情感）需求的冲突？

在我的价值观里，她们愿意去就去，我不太愿意去就不去，分头行动再汇合即可，大家都开心，不需要为彼此牺牲什么。但我没考虑到她们希望三个人总是在一起，甚至愿意因此不去乐园了。如此一来，她们将去与不去放在了利益的对立面，让我不知道该如何处理类似的事。

父母是普通工薪阶层，700一天肯定觉得贵的，但他们听说此事后，表示愿意他们出钱让我去。我感觉此举意在让我合群和学会迁就别人。多出700我自己是可以负担得起的，只是基于对存款的规划，我不愿意而已。

总结为一句话就是，我大概太贪心，既不太愿意打乱自己的规划，又不想伤害别人的感受。我想这种矛盾或许来自：我强烈的自我意识告诉我我应该遵从自己的内心，但周围环境（例如父母在此事中的举动）又时刻提醒我我应该考虑别人的感受，甚至牺牲自己去顺从别人，以维持一种“快乐的大氛围”，所以我感到很纠结。

如果是事实需求的话，我相信总能找到折衷的办法，但当我面对的是情感需求的时候，我就不知道怎么办了。有时候我觉得如果随意洒脱一点谁牺牲迁就一下都不是什么大事，但是有时候这种事情发生得多了容易改变一个人的风格。虽然此事只是小事，但我感觉它反映出了我在人生某种大原则上的摇摆不定。希望听听您对此类事的看法，谢谢您！（问题来自微博私信）

———

十几年前我还算是年轻教授那会儿，每年有一次机会可以和系主任聊一会儿天，系主任「面授机宜」，算是我当时的「mentor」。

有一次他看到我在十几个会议里担任了各种这组委会那委员会的成员，不但没有因为「没有功劳至少还有苦劳」而表扬我，还竟然建议我少接受几个这方面的邀请。

「You should learn to say “no” to people.」他说。

这是当年系主任给我的所有建议中，我印象最深刻的一句。

因为「say no」是一种「桃花潭水深千尺」的哲学，一种「牧童遥指杏花村」的境界。我即使在多年以后的今天，依然觉得这种境界犹如「南阳诸葛庐，西蜀子云亭」般遥不可及。

「Say no」之所以遥不可及，是因为我们从小到大耳濡目染的所有待人接物的道理，什么「在家靠父母，出门靠朋友」啊，什么「为朋友两肋插刀」啊，什么「毫不利己，专门利人」啊，什么「个人利益要服从集体利益」啊，什么「人生的意义在于贡献，而不是索取」啊，都与「say no」的哲学南辕北辙。

我之所以一直在用英文的「say no」来代替中文的「说不」，是因为前者我觉得很自然，而后者却因为这些从小到大的道理，觉得很唐突，很没有礼貌。

比如我平常跟小女儿建议她早点儿弹会儿琴什么的，她每次只需要一句「thanks but no thanks,」就一定可以把我凌厉的武功招数自然而然地化解于无形。我不但一点儿都没觉得生气，还觉得有点儿俏皮可爱。

而换了我呢，每一次没有狠下心来「say no」，到最后都差点儿沦落到「鞠躬尽瘁，死而后已」的境地。因为在我的「公理系统」里，一旦答应了别人，我绝对不会中途变卦，而且一定要把答应别人的工作做得尽善尽美。

一旦答应了别人，不仅仅可能像你的故事里一样多了一笔不菲的花费，而且还花了自己的时间。几百块钱省下来可以用在很多其他地方，但至少将来还可以再挣；时间则是一种更加无情的资源投入 —— 一旦过去就再也回不来了。

这就是「say no」哲学的最大好处：最初别答应别人，一切就都不会发生。

所以，理直气壮地、不计后果地、自私自利地、不顾集体利益地、「做一天和尚撞一天钟」地说「no」吧！洒脱地牺牲一下别人，迁就一下自己，这就是你「踏破铁鞋无觅处，得来全不费功夫」的人生哲学。

但是我不得不再次强调，这种境界实在太难以企及了。

比如今天有一个陌生人通过微博问我问题，我本来完全可以对她说「no」，可还是一念之差，想着「说不定将来可以成为一个朋友呢」，花了一个多小时时间，给她写了如上的文字。



---


# 人比人，气死人


李老师您好！从褚老师那认识您，一路看您的问答过来，感觉您就像身边的一位长者朋友，如沐春风、沁人心田。不知道您还记得1988年版本的《新华字典》上有这么一句话：“张华考上了北京大学；李萍进了中等技术学校；我在百货公司当售货员：我们都有光明的前途。”吗？

这句话之前又被翻出来被网友玩坏，改成了“张华考上了985大学；李萍进入了某垄断国企的干部培训班；我在世界五百强商超当供应链主管：我们都有光明的前途。” 来笑称现在的阶级分化和贫富差距。不料我之前翻最新版的《新华字典》也看到了这句话，但我的第一反应是——当时人们的感情真挚，不会因环境变化而自卑，情谊疏远。

我现在是一名在准备考研的学生。周围的同学也都想通过考研改变一些现状，对未来充满了期待。但我也知道和以前优秀的同学终究是有很大的差距了。如何面对这种差距，正确地放弃幻想，轻装前进呢？（问题来自微博私信）

一

俗话说得好：人比人，气死人。任何事儿都千万别跟别人比，别给自己树立标杆儿和榜样，否则一定跟小时候家长拿自己和「别人家的孩子」比如出一辙，最后是自个儿给自个儿找不痛快。

尤其不能比的，是好久以前的同学。时间这个东西，是一种奇妙的催化剂：时间长了，一切早已面目全非。当年和同学分道扬镳，你走你的阳关道，我过我的独木桥，这么多年来每一次微不足道的决定，都会影响后来的「前途」。

大多数同学聚会，除了特别要好的几个之外，与其说是去重温旧情，不如说是好奇心理使然，去看看其他同学都混得如何。同学聚会是一种典型的有偏采样：自己觉得混得不好都没去参加，参加了的都有点儿「来头儿」，有可以炫耀的资本。所以啊，这样的同学聚会，将来尽量少参加为妙。

二

那些「前途光明」的同学，当年是怎么出人头地，和大家拉开差距的？

这需要三样东西，缺一不可：资质、兴趣、运气。

资质就不用说了。即使是在微信公众号靠写文章赚钱的，没有一点儿天赋，也很难写出全国人民纷纷转发的「十万加」来。

以前有一种说法叫「干一行，爱一行」。「兴趣」就是把因果关系反过来，改成「爱一行，干一行」。你决定干的事儿一定是你不吃饭不睡觉地热爱着的事儿。「前途光明」的数学家不是为了毕业而学的数学，而是因为热爱得不可开交，天天浸淫其中，乐不思蜀。「混得好」的企业家也一样，完全是因为一种执着的、持之以恒的、发自内心的热爱。

资质和兴趣都具备了，还要有足够好的运气。这一点Gladwell在他那本著名的《Outliers》里已经说得很明确了：乔布斯和盖茨等人能成功的一大因素是他们赶上了好时候：他们都是1954至1956年出生的。

你看，想有个「光明的前途」真不是那么容易的一件事儿。

三

我小学时妈妈跟我说，她年轻时特别喜欢骑自行车，所以对未来一直有一个美好的理想。

我问：是当个自行车运动员？

她笑着跟我说，你猜错啦，是当个邮递员。

现在想来，那个年代当个邮递员和新华字典里说的在百货公司当售货员大概异曲同工：一辈子有稳定的收入，有劳保，有退休金，绝对是一份非常令人羡慕的工作。

这有点儿像在加拿大啊挪威啊这样的高福利国家当个空乘，当个小学老师，或者当个公共汽车司机，有工会制度保护，有稳定的收入，有劳保，有退休金。

这样的生活波澜不惊，既没有「过独木桥」的风险，又没有和风险相应的回报，是一种「一眼能看到火葬场」的「小日子」。你可以精打细算，量入为出，有时间尽心尽力地照顾家人和孩子，尽享天伦之乐。

那将来如果是这样红红火火的「小日子」，算是「光明的前途」吗？二十年后能有面子跟有点儿「来头儿」的同学们觥筹交错、共叙旧情吗？

如果你觉得可以，那么我有个好消息要告诉你：这样的「光明前途」既不需要太高的资质，又不需要「爱一行，干一行」的兴趣，连运气都不需要太好，兢兢业业地把每天的事儿做完做好就可以了。

妈妈后来清华毕业，但终究没有当上邮递员。


---


# 成功与小说


李老师你好！看了你微博猜测向你咨询问题的人一定很多，我都怀疑你是否会看我的，好吧就算不看，我也得写啊问啊。

李老师是个成功的人，而我却无所作为，每当想努力啊勤劳的学习，发现心怎么都静不下来。大道理小道理都懂，就是做不到耐着性子，一度怀疑是否记忆只有七秒，多次试验发现记忆不止七秒，自信重回，想看书，每次捧着书就是看不下去。甚是苦恼，想考什么证那是有决心没耐性，曾经谈不上多么热爱学习，但也不至于像现在成为不想看书，看不进去书的人。

拿着书很抗拒，不管是有兴趣还是交了钱要去考试的都不上心，可不学习不学点东西在这个城市真不知道能有什么工作。

已麻木的我以为别人的成功来得容易，真不知道别人是如何战胜困难，战胜自己。讨厌现在的自己。

李老师啊，你有什么好的办法让我好好看书，让我所下的决心付出行动吗？（问题来自微博私信）

一

我一边做晚饭一边跟刚到家的郭芳说：「今儿个微博私信又收到了一个问题。」

「什么问题啊？」

「她问，大道理小道理都明白，就是不爱看书学习，怎么办？」

「那她爱看小说吗？」

二

你想没想过，不爱看书的一大原因，很可能是你手里的书写得一点儿也不好看。

我们从小到大听过的都是似乎特别有道理的「励志」画外音：「读书破万卷，下笔如有神」啊，「人生能有几回搏」啊，「读万卷书，行万里路」啊，等等等等，不一而足。

但是说真的，大多数的书，真的写得不怎么吸引人。

比如说我家小女儿正在学的小学四年级语文课本，就有点儿令人捉摸不定。

先看题目：《夜莺的歌声》、《小英雄雨来》、《一个中国孩子的呼声》、《和我们一样享受春天》、《触摸春天》、《永生的眼睛》、《生命、生命》、《花的勇气》……

咱再随意打开一篇叫《触摸春天》的课文看看。

看文章像看体操一样，要注意它的开场和下法。

这篇文章开头写道：「邻居的小孩安静，是个盲童。」

结尾写道：「我没有惊动安静。谁都有生活的权利，谁都可以创造一个属于自己的缤纷世界。在这个清香袅袅的早晨，安静告诉我这样的道理。」

课后习题正好和这个结尾有关：「多美的课文……让我们结合课文和生活实际，说说对这句话的理解。」

读了这样有点儿令人提不起兴致的文章，我要是小学生，说实话多半儿也会放下课本，去打《王者荣耀》。

所以啊，不爱看书，很可能是书写得不好看；而你多半儿内心深处从小到大觉得不读书或者不学习是不对的，还要强迫自己看。就像背英语单词一样，越背越烦人，以前背的还都忘了个八九不离十。

明知「不进则退」还要逆水行舟，战斗还没打响，败局已定。

三

那你爱看小说吗？

比如钱钟书的《围城》、金庸的《天龙八部》、慕容雪村的《成都，今夜请将我遗忘》、艾米的《竹马青梅》、辛夷坞的《致我们终将逝去的青春》、王朔的《一半是火焰，一半是海水》，还有刘瑜的《那么，爱呢》？

你也许会说，我说的看书学习不是看小说不务正业，是学点儿对将来事业发展有用的东西。

你还别说，即使你将来的理想是当个数学家，你的当务之急还是放下微信，放下手机，放下所有的「大道理」和「小道理」，放下「学习」啊「成功」啊这些词儿，去亲身体验一把一种看一本书看得如痴如醉、如火如荼的感觉，一种唏嘘不已、物我两忘的境界。

因为那时你会发现，在一本写得引人入胜的书里，竟然藏着一个和微信群朋友圈完全不一样的世界。

我没有微信朋友圈，微信群里的红包总是抢不到，但却一直酷爱看小说，酷爱看一切令我陶醉于其中的书。所以说，我从来没有「成功」地「战胜」过自己。

「谁都有生活的权利，谁都可以创造一个属于自己的缤纷世界。在这个清香袅袅的早晨，安静告诉我这样的道理。

---

# 好好说话


李老师你好，关注您微博也有一段时间了，最近有个问题想请教您，还望解答。

怎么样才能好好说话呢，自己说话总是会无意的得罪对方，即使别人生气了还搞不清楚怎么回事，怎么样才能够提高那种语言上的分寸感？（问题来自微博私信）

你这个问题问我，绝对问错人了。因为我说话和你一样，也经常说错，跟你相比最多只能算是「五十步笑百步」而已。唯一比你略强一点儿的是，我一般说错了话刚说完就马上能意识到，可惜永远无法收回了。

因为我经常说错话，有时候也会有意识地想一个问题：怎么说才能少说错几句话？要是能把酒言欢，聊一晚上天儿，一句也不说错就好啦。

后来我发现，其实做到这一点并不是特别费劲儿。

你一定听过德云社的相声吧？聊天说话想少说错话，关键是别老去当那个逗哏的，说学逗唱样样精通；而是要多退居二线，去当那个捧哏的。

捧哏的常说的话很简单：「嗯」，「哟」，「那是」，「啊？」，「别逗了」，「等会儿等会儿」什么的，看过相声的都门儿清。

你说话的任务是，听明白逗哏的那位讲的故事，然后想办法激发他继续讲下去的积极性。

比如他故事讲到一半儿停下来，磕了一瓜子喝了一口啤酒，你这时正好可以接上话：「哟，那后来呢？」

千万别跟刘瑜小说《那么，爱呢》里的「蜘蛛侠」似的，来一句「那也不能这么说」，呛了逗哏的一句，这相声也就说不下去了。真是活该小说里的「蜘蛛侠」找不到对象，谁会喜欢和这种人聊天吃饭啊。

别较真儿，就能完美地演好一个捧哏的角色。

其实捧哏的烘托场上气氛并不那么容易，人那也是门儿说话的艺术。我想起了高晓松几年前在优酷搞的那个叫《晓说》的节目。本来好好的看的人其实挺多的，就差家喻户晓了，结果高老师大概嫌自己一个北京人侃单口相声不过瘾，有一集找了一个优酷的美女主持人坐在对面儿沙发上，一起聊林徽因。

结果这位美女有点儿辛苦地全程不停点着头，最多再加上几句「那然后呢」，捧哏捧得估计令高老师大失所望，过了几集就不再出现了。

所以说啊，也不能净说「那后来呢」，还要时不时锦上添花，来一句「这说的在理儿」、「您还挺明白」、「还真是这么回事儿」什么的，反正就是激励逗哏的继续变本加厉地猛说呗。

那你一定会问了，逗哏的说的一点儿不逗怎么办？或者没人爱说话，都在玩儿手机？

得，这时候就是您该「亮剑」出场的时候了。

「我给大家讲一笑话啊，估计你们肯定没听过。」

等你笑话讲完，一定会有人跳出来说「你这笑话一点儿都不逗，我都听过好几遍了。」然后继续口若悬河地开聊。

这时你立马「敌进我退」，继续当个捧哏的就行了。

捧哏到了最高境界，在座的各位竟然都有机会侃上一段儿，饭局在亲切友好的气氛中觥筹交错，酒过三巡，没人注意到你暗中「润物细无声」的起承转合。

如此说话的功力，要是你将来有机会和高晓松「对谈」，估计他能从抗美援朝侃到《如懿传》，喜玛拉雅上再开一专栏儿，也未可知呢。


---


# 人生不顺

李老师您好，我最近两年人生走得特别不顺利，这两天又在人生选择上焦虑的不行。您能帮我指点一下吗？先感谢您！

本科毕业于上海一所二本院校（我是山西省一本线），大四考研北京师范大学，初试过了，面试没过，难受了两个多月。因为自己心疼父母，不想让父母有太大压力，我就边工作边二战，还想考北师大，但没想到结果未遂人意，我便调剂到陕西省委党校，开学了几天，自己并不是特别开心，因为感觉自己不是特别适合党校氛围，还特别想念上海。所以又想再考了，这次想选个大城市比较好的学校，压力不是特别大的。跟中部城市比，还是想念上海。

您觉得我这样想奇怪吗？身边的学长学姐说时间耽误不起，可以把时间好好利用起来考博。我有点犹豫，不知道自己是不是执念。麻烦您帮我指点下吧，谢谢您！（问题来自微博私信）

一

前两天跟小女儿闲聊，不知道怎么就聊到了一个假想的场景。我问她：在荒无人烟的野外，一只灰熊发现了你，向你虎视眈眈地慢慢走来，你怎么办？

这运气确实没法儿再糟糕了。

但要按我从小到大受到的教育，正确的心态应该是去「挑战命运的安排」，向张海迪同志学习，学习她在残酷的命运挑战面前，没有沮丧，没有沉沦，以顽强的毅力与命运抗争，去做一个社会主义新人。

毛主席说的好，人定胜天嘛。

至少可以跟电影《Forrest Gump》里Jenny的名言说的：Run, Forrest, run!

女儿的回答却完全在我的意料之外：

「I will accept my fate and just die, right there.」

「那你为什么不跑啊？」

「No. I will just die.」

这让我想起了电影《Legends of the Fall》的结局：主角都年轻时去世了，只有Tristan活到了老年。他遇到了一只灰熊，拔出匕首和熊搏斗，画外是One Stab的声音：「It was a good death.」

二

按常理出牌的话，我想一般人遇到这种「命运」，都会跑的。无论如何，「跑」是以顽强的毅力去跟命运抗争，是不屈服于命运的安排。不跑必死无疑，跑还有一线希望，为什么不跑？

所以我对女儿的回答感到非常震惊。

「I will accept my fate.」

这是什么人生哲学？从来没听说过，跟我受到的教育格格不入，然而又令人耳目一新。

在你的故事里，当命运像贝多芬的交响乐一样来敲门的时候，你收到的那张纸上写着：陕西省委党校。

为了回答你这个问题，我还专门在网上找到了这个学校的地址，发现是在陕西省西安市市区。

确实，跟上海相比，我也更喜欢上海。

但是这可不是什么新疆维吾尔自治区吐鲁番市，西藏自治区林芝市，这座城市总人口一千二百万，机场可以直飞法国巴黎，有喜来登，有香格里拉，丽思卡尔顿就要开业。

如果考虑买房的性能价格比，西安甚至可以说还超过了上海。

If I were you, I will accept my fate.

And just die right there.

三

但是，如果不跑必死无疑，跑还有一线希望，为什么不跑？

好吧，那我们就来仔细分析一下因为「跑」而成功的概率。

咱们假设你复习准备了一年，成功考上了上海一所普通高校。研究生学成毕业后，工资是八千一个月。

而你如果继续在咱省委党校学习，因为不需要准备考研，可以提早一年毕业，工资低一点儿，是七千元一个月。

你复习准备一年的因为工资损失而带来的沉没成本，是八万四千元。你需要在上海工作七年，才能追上西安工作的收入，刚刚持平。

但如果西安房价每平米一万、上海每平米五万呢？那按照咱们假想的收入水平。在西安每年的收入可以买八平米住房，而在上海只能买两平米。也就是说，要是想和西安的住房水平持平，上海学校毕业需要找一个一年税后四十万，税前六十万的工作。

当然了，大城市生活质量不能简单地用买房面积来衡量。

那考研还指不定能不能考上呢。

阿斯顿马丁确实好，我也和大家一样喜欢啊。可惜喜欢归喜欢，上班儿还得继续开我那辆开了十七年的本田。

四

据说，野外碰到灰熊千万别跑。

跑了它一定会像追猎物一样追你，而灰熊的短距离冲刺速度远远超过奥运会百米冠军。

而以静制动，以不变应万变，倒也不一定就会束手就擒，必死无疑。

四面楚歌之时，背水一战，也许还有一线「置之死地而后生」的希望。


---


# 终身伴侣

李老师，看了您关于党校的问答，真的忍不住想跟您说下我的情况。我可能就是那种就地躺倒的人，也这么做了，每天乖乖巧巧按部就班，现在最大的困扰是找对象的问题。生活习惯爱好都比较独，接触不到新朋友，介绍的很难聊得来，想找志趣相投的，可我真的很像日本小说中独居的人，不喜欢吃不喜欢逛不喜欢凑热闹玩（可能也有经济原因）。如果您有兴趣的话，也开导开导我吧。（问题来自微博私信）

找终身伴侣这件事儿，我比较相信高科技。

一

斯皮尔伯格最近拍的一部叫《Ready Player One》的电影你看过吗？

电影里的男主角Wade和女主角Samantha就是在一个叫做「OASIS」的虚拟现实游戏里相识的。游戏里Wade的好朋友对他的网恋不以为然，警告他：「You’ve got to be more careful about who you meet out on the OASIS.」他斩钉截铁地反驳：「She just gets me. We even finish each other’s sentences.」

Finish each other’s sentences —— 两个人聊天儿不但不尴尬不紧张，还越聊越high，完全停不下来，只嫌时间过得太快。聊到酣畅淋漓之处，如同一个人左右互搏一样。这已经不仅仅是「心有灵犀」了，简直就是爱情的最高境界啊。

而如此境界，仅仅靠亲朋好友介绍相亲，估计多半儿体验不到。我一直觉得靠相亲来寻找终身伴侣效率相对比较低：本来天各一方的两个陌生人，突然坐在一张桌子上喝咖啡，这得多能说才能聊的起来啊。

但是如果依靠高科技，在虚拟现实的游戏里，为了一个共同目标的队友，还真有可能萌生出一种「两情相悦、心意相通」的浪漫情怀。你想啊，你和一个从未谋面的女生边语音聊天边一起打「吃鸡」，跳伞和射击时听到的是她略带娇滴滴的笑声和欢呼声，会不会跟斯皮尔伯格的电影里一样，整个人彻底地爱上了她？

没错儿，你其实爱上的不是一个人，而仅仅是一种声音。但是这种声音像Scarlett Johansson在电影《Her》里的声音一样，让人深陷其中，难以自拔。

二

不仅仅是虚拟现实游戏，其实靠谱一点儿的婚恋网站和交友app，依赖的也是高科技的算法。

普通的婚恋网站需要你去填写自己的兴趣爱好，然后用推荐算法来帮助你找和你最相似的陌生人。信息填得越详细，推荐给你的人就越准确越靠谱。

比如说如果你喜欢黄章晋或者高晓松，算法就可能推荐那些和你一样热爱黄章晋或者高晓松的粉丝。

如果你将来有办法把自己在知乎、微博或者朋友圈的所有内容和浏览记录都分享给这样的「人工智能」算法，我敢肯定，算法对你的了解会远远超过你的家人朋友——因为算法不会忘记任何历史信息，它甚至可能超过你自己。

你想象一下，这样的算法推荐给你的人，成功率是否比亲朋好友随便介绍的相亲对象高很多？

不喜欢下馆子不喜欢逛商店不喜欢凑热闹都没关系，但凡你有喜怒哀乐七情六欲，「人工智能算法」都能把你映射为一个高维空间中的向量，用一个向量之间的余弦相似度，就能在这个世界的某个角落里找到和你「心意相通」的那个人。

三

可是在这个柴米油盐的世界上。真的存在这样一个人吗？

即使真的存在，她真的还在等着你的出现吗？

也许你踏破铁鞋最终找到的，是一个和你志趣大相径庭，天天有事儿没事儿心情不好就跟你吵上一架，磕磕绊绊地也和你过了大半辈子的人。

不过这也没有关系，很多年以后孩子长大了，几个哥们儿叙完旧，英雄不减当年，再度开玩儿「绝地求生」的时候，你如果还能怔怔地记起当年一起打游戏时她的声音，就心满意足了。

就像斯皮尔伯格那部电影里的台词说的：「As terrifying and painful as reality can be, it's also the only place that you can get a decent meal. Because, reality is real.」


---

# 直博生


老师，您好。我是一名直博生，一直很焦虑迷茫，压力大，感觉在崩溃的边缘。找不到能解决我困惑的人，想跟您聊聊，或许会打开我的心结。

我的博士方向需要的知识，本科没有接触过。但导师总是说，这个还用学吗？那个还用学吗？直接用就会的呀！但从师哥师姐那里得知导师其实也不怎么会。就这样，导师让我做第一个工作，大概半年，仿真没有做出来，导师嫌弃没有成果，曾一度说我毫无能力之类的，外加各种毕业威胁。再后来就直接把我搁置一边，说了句你爱看什么看什么，不再管我，我遇见他打招呼都爱搭不理。偶尔又时不时地发发微信说我没产出等等。

在这种情况下，很难过，同届学生都做得风生水起，师哥们看了我，都说一句：心疼你。我压力好大，不想放弃，自己又迷茫，在这种境遇下，心里每天很乱，越乱越学不进去。我不知道，科研如果单纯靠自己，没人指导，是否真的可以做出成果。这种情况下，只靠努力，足够努力，一样会做的好嘛？我选择读博，就是希望将来能联培出国，但这样下去，感觉毫无希望。我真的不知道该怎么办，在周围同学的怜悯之中，自己更难过。

您能给点建议吗？我应该怎么面对当下的这一切，在科研上，我该怎么着手，让自己找到前进的方向。导师时不时对我的威胁，让我更压力大。所以，李老师，很期待您的回复，给一个不想放弃却倍感绝望但还想挣扎的我宝贵的建议。您觉得在这种情况下应不应该继续坚持读下去，我一直陷入其中，看不到希望。谢谢老师！（问题来自微博私信）

——

一

你想没想过，你一辈子认识的人里的大多数，都仅仅是昙花一现的过客。

小学时两小无猜的发小、中学时一见倾心的初恋情人、大学军训时凶狠无比的排长，时间长了，印象慢慢地淡忘，直到终于想不起来他们的名字，也记不起来他们的样子了。

据说，天底下所有的父亲最黯然神伤、欲哭无泪的时刻，是女儿大婚之时。我猜想，大概是终于意识到，骨肉至亲，二十多年的朝夕相处，终将远去，竟然也无法逃离生命之中「昙花一现」的命数。

学生跟导师读博的那几年时间，你以后会发现，更加是弹指一挥间的事儿。没办法，日子过得太快，青春稍纵即逝，「大江东去，浪淘尽、千古风流人物。」

正因为如此，每一天的日子，归根结底，还要依靠自己。

二

无论是学习还是科研，都应该静下心来，一点一滴慢慢地积累，这需要很长的时间。在这个漫长的过程中，同学也好，师哥也罢，可能会有人给你提建议，但是没有人可以真正全程陪着你。归根结底，还要依靠自己。

至于这位导师，我赞同毛主席的名言：「人不犯我，我不犯人；人若犯我，我必犯人。」毛主席还说过：「任何方面的横逆如果一定要来，如果欺人太甚，如果实行压迫，那么，共产党就必须用严正的态度对待之。」

当然，咱也可以跟老外学习，无论是Linux内核的创始人Linus Torvalds，还是当年的乔布斯，都是著名的坏脾气，一旦骂起人来，「谈笑间，樯橹灰飞烟灭。」

什么时候可以「中国人民站起来了」，对一个原本只是生命中的过客，有一点儿自己骨气和尊严，不再委屈求全？

归根结底，还是要依靠自己。

我建议：战略上要极端藐视，不要对「成果」太过苛求；战术上则要高度重视，充分利用每天的时间，经常参加各种运动，慢慢放宽自己的心情，每天做一点儿让自己觉得有收获的事儿。

不要忘了，你正值大好青春，不但有的是时间，而且早晚能毕业。

实在心情不好，给微博上的一个叫李老师的陌生人发私信，也未尝不是一剂良方。

三

据传说，昙花原来是一位花神，她一年四季，每天都会开花。她爱上了每天给她浇水的帅哥，被玉皇大帝知道了，大发雷霆要拆散她们。玉皇大帝把花神抓了起来，贬为每年只能开一瞬间的昙花，不让她再和情郎相见。

小朋友听到这里一定会问：那后来呢？

这个故事，还是由你继续给小朋友讲吧。


---

# 说话得罪人

李老师，想请教您一个问题：我一直以为自己是真正在为别人着想，但结果好像是处在我自己的环境里为别人着想。因此说的话好像会时不时地伤害到别人。

例如：别人送一个礼物，我首先表达了很高兴，然后说，太贵了，退了吧，等你赚钱了再送我。别人就会觉得我是在说他没有钱，在伤他自尊。说者无心，听者有意，这个现象好像会经常出现在我身上，并且我不知道自己说的话伤害到别人了，直到别人告诉我。

我试着站在别人的角度考虑，但是这好像并不是一件容易的事情，毕竟别人所处的环境可能难以模拟出来，我还是会被我所处的环境或多或少地影响着。

我该如何改变，另外如果出现这种情况我该如何弥补呢？（问题来自微博问答）

哈哈，这个问题问我绝对是问错人了。

世上有两种人。一种极具亲和力和领导才能，人见人爱，平时聊天随和、自然，让人感到如沐春风，心情愉快。

还有一种人性格内向，「情商」不高，容易说错话得罪别人，说完了呢一想又会后悔，但是早已覆水难收。

我母亲年轻时是前一种，而我则恰巧属于后一种。

不仅如此，而且多年来我发现，性格以先天的基因传承为主，就好像长得不好看很难改一样，性格也是很难后天改变的 —— 改的了一时，改不了一世。

有很多书里，会列举各种各样生活中的例子，教育像我这样的读者，在某一个场景中的每一句话，应该这样说，而不应该那样说。

可是问题在于，对于前一种人，这种书简直就是小儿科，他的话本来就是正确的说法啊。而对于我这样的人，就像你的故事里说的，无论初衷多好，总不可能每句话都想半天再说吧，那也太费劲儿了。而靠直觉说的话，性格使然，早晚还是要说错。

别说看书了，就算摆一个活生生的标兵模范在你面前，天天耳濡目染，也照样是要不然东施效颦，要不然画蛇添足。

那怎么办？

这个问题，一个相貌平平的女生看到别人漂亮，或者一个脑子不够聪明的男生看到同年级的学霸，一样都会问。

既然改已经没戏了，我建议：别想这么多，想怎么说话，就大大方方地敞开了说好了。

那些「有意」的「听者」，无论如何，都无法让他回心转意，让他喜欢上你。

说他「没钱」怎么了——我们大家不是也都没钱吗？

你将来命中注定的朋友，即使你长得不够漂亮、脑子不够聪明、说话不够完美，他们也早晚会喜欢你的。

就像二十多年前黑豹的那首《无地自容》里唱的：

人潮人海中有你有我
相遇相识相互琢磨
人潮人海中是你是我
装作正派面带笑容

不必过份多说自已清楚
你我到底想要作些什么
不必在乎许多更不必难过
总究有一天你会明白我


---


# 没有结果的吻


你好李老师。

我遇到了一个人。他身上有我喜欢的全部品质。而在此之前，我不知道那是我在伴侣身上需要的全部品质。

我们之间的交集只有短短五天，这之中的每一天，和他的每一个互动，都让我快乐。而在此之前，我不知道我可以这样快乐。

可是在我们第一次接吻第二天，他告诉我他不能和我在一起。他觉得doomed。

我当着他的面，念了我这五天的心路历程，念了我这五天写下的诗，哭了两声，自己下车走了。

我不知道我接下来该怎么办。我指的不是要不要删掉他的联络方式，也不是要不要再争取一下，我觉得都没必要了。只是我的喜欢突如其来，又被迫胎死腹中，我被自己的感情吓到了，也被它被迅速扼杀的事实吓到了。

我记得《欲望都市》里有一集，提出分开的作家忽然捧着花回来，和女主角一夜春宵后，留下纸条说自己做不到就走了。女主角愤怒地砸了桌上的花瓶。可我不愤怒，我现在无比孤独。我不知道原来，在我对一个人感觉这么好的时候，他却觉得没有结果。我想抱着我的妈妈哭一哭。

想听您说点什么。

（故事来自微博私信）

——

一

一九一二年四月十日，泰坦尼克号首次从英国南安普敦启航，前往美国纽约。

一九一二年四月十五日凌晨，在北大西洋与冰山相撞，一千五百多人遇难。

仅仅五天时间，竟然演绎了一场头等舱的阔小姐和四等舱的穷画家之间惊心动魄的爱情故事。

这五天时间里，和Jack的每一次互动，都让Rose觉得快乐。

而在此之前，Rose从来不知道她可以这样快乐。

没错儿，你的故事让我迅速想到了二十年前那部家喻户晓的电影——《泰坦尼克号》。

二

同样是二十年前，这部电影刚开始公映的时候，褚明宇曾经大笔一挥，写了一篇檄文发表在MIT BBS上，题目就叫《大骂Titanic》。这篇文章虽然短小，但极其精悍，全文毫不拖沓，行云流水，锋芒毕露。我先来摘抄一段：

——

《Titanic》给我的感觉只有一个字：俗。其实俗也不一定就是坏事儿，毛主席他老人家早就说过我们的文艺是要为工农兵服务的。就象当年流行过的《妈妈再爱我一次》还有《喜福会》之类的破烂儿，骗完了家庭妇女们的眼泪就可以老
老实实的收摊儿走人了。不过俗得无与伦比的东西要是被捧得太高吹得太悬主题歌咿咿呀呀悲悲切切满大街的放，就显得有些讨厌，让人忍不住想站起来骂两句了。

——

你瞧，从旁观者的角度来看，任何闪电式的爱情，都有「这就俗了」的嫌疑。《Titanic》还算好的，至少是两情相悦，直到灾难来临，还立志携手共度难关。你的故事里明显是你很爱他，但是他却不怎么爱你；你觉得可以以身相许，他却不想私定终身。如果说《Titanic》俗，那从一开始就注定要短命的爱情，就更加不值一提了。

但是我很羡慕你。

我们几乎每个人都曾经「暴怒」过——就是气得七窍生烟、呼吸都费劲儿的那种感觉。

但是我们不是每个人都「暴爱」过——就是爱一个人爱到昏天黑地，像一个刚打好了氢气的气球，越飞越高，飞得快的令人动容，忽然一声巨响，一切嘎然而止。

这种欲哭无泪、心如刀割的心情，不是每个人一辈子都能体验一次的。

你的运气简直好得让人难以置信，好就好在他五天就把你甩了。你的体验因为这过山车一般的几天时间太短，就像热水里刚出来去冰水里淋浴，从「I’m the king of the world」堕入万丈深渊，所有的痛苦体验加倍放大，很少有人能亲身经历。

而闪电式的爱情，早晚都是要以分道扬镳收场的。即使美丽得像张雨绮一样倾国倾城，几任男友，闪电恋爱闪电结婚，双胞胎都生了，不是一样要离婚？所以他提出「咱们没有将来」越早越好，「Jack」沉入大西洋以后，把你的微信删了，你早晚可以跟我们的阔小姐一样——「my heart will go on」。

如此完美的「暴爱」，能不让人心驰神往吗？

三

二十年前在美国的一个周末，我去看了一场叫《泰坦尼克号》的特价电影。可能是想再看一遍，刚好褚明宇也去了。

电影的结尾有一个细节。老太太Rose在船上安详地睡着了，房间里摆放着她年轻时在沙滩上骑马的照片，正是Jack说要带她去玩儿的。画面转到一个梦幻般的场面，破旧的沉船慢慢地变成了当年的泰坦尼克，Rose一袭白衣，美丽得令人窒息，从豪华的旋转楼梯拾级而上，Jack西装笔挺，微笑地在上面等着她。两人终于接吻时，泰坦尼克上的所有人全体起立，热烈鼓掌。

褚明宇后来说：这个电影真的挺好看的。


---


# 不会再遇见


李老师，您好，不知道您能不能看见我的私信，想请教您一个问题，就是一个平凡的人会遇见的情情爱爱的问题。

喜欢了一个很特别的男孩子，留着飘逸的长发，一双眼睛很忧郁，像个流浪诗人，身上也有一种说不出来的气质，非常特立独行的一个人，也是一个很自我的人。分手以后一直走不出来，一直沉溺在这种喜欢里，因为觉得在大街上再也找不到第二个这样的人了。现在的他，在我眼里实在是特别得无可取代了。可能因为年轻，喜欢这样的“怪人”，喜欢他的不合群，甚至想保护他的自我和他尖锐的性格。我不知道怎么办，真的很难走出这种喜欢。不是失恋的痛苦，真的是发自内心的太欣赏这个人了，很害怕自己再也遇不见这样的人。

我想知道您怎么看待年轻女孩欣赏怪人的美这件事。「那种欣赏常常掺杂着模糊不清的崇拜、向往甚至是保护欲。会在与之交往的过程中，自觉扮演起相对适应规则的一方，好去衬托他们对于社会关系的迟钝和漠然。也会因为怪人们每每释放出的“目中无人”，而高估他们的才华。在被他们抛出的谜面彻底击溃后，还要反思是否自己的理解能力过于低下。」您觉得这种崇拜是一时的，还是会随着成长改变呢？（问题来自微博私信）

——

一

哈哈哈，你大概忘了，我的专业是理工科，不是恋爱心理学。

不过即使是我这个外行，都可以斩钉截铁地告诉你，确实如你所说，以后你在「大街上」也好，小胡同里也罢，再也不会遇到他这样的人了。

这就好像我多年前第一次看《围城》，自从那个大雨的下午方先生从唐小姐家里离开之后，一直热烈地期盼着唐晓芙再次出现在小说中。

这让我看《围城》后一半儿时，有一种屏住呼吸，一直期待着小学生作文中的首尾呼应、交响乐里的华彩的感觉。

可惜直到那只祖传的老钟从容自在地打起来，唐小姐再也没有出现。

这种莫名的失落感，也许这正是《围城》这本小说的精华所在，正是钱老先生想讲给我们听的人生道理。

二

不过我看完你的问题，心里倒是隐隐有一种穿越到了金庸小说里的感觉。而此时此刻正跟我聊天的，是《神雕侠侣》里我最喜欢的女孩儿——郭襄。

郭襄在黄河北岸风陵渡口初遇神雕侠，自此无论是三枚金针，还是生日的三件大礼，直至绝情谷纵身一跳，十六岁的郭襄对她的「大哥哥」生死相依，情深至此，读来荡气回肠。

「在绝情谷底，郭襄从怀中取出最后一枚金针，说道：“大哥哥，当日你给了我三枚金针，曾说过凭着每一枚金针，我可相求一事，你无不允。今日我来求恳：不论杨大嫂是否能和你相会，你千万不可自寻短见。”」

我如果也有金针，一定会跟郭襄说：神雕侠确实独一无二，世上只有一个。

不过人生苦短，甜点有很多种，各有各的甜法儿，为什么一定要苦苦寻觅以后不会再出现的那一种呢？

不论以后是否还会再遇到这样的人，不论唐小姐是否还会在出现，千万要多尝试几种不同的甜点，才能不枉此生。

三

我最爱的英文电影之一 —— 其实是挺小众的一电影 —— 叫「Eyes Wide Shut」。

虽然这部电影没什么人看过，它的导演却是大大有名：他的名字叫Stanley Kubrick。

Kubrick一辈子导演过好多部超级牛的电影，每一部都足以让一位导演名垂青史：「The Shining」、「A Clockwork Orange」，还有最著名的「2001: A Space Odyssey」。

「Eyes Wide Shut」是他的最后一部作品。他对拍摄的细节极其较真儿，一部电影竟然拍了将近两年时间。电影的主题你说不定感兴趣：它是一个关于婚姻和出轨的故事。

这部电影后期剪辑刚刚结束没几天，Kubrick心脏病突发去世。

Tom Cruise和Nicole Kidman是两位我喜爱的明星，联袂主演了这部电影以后，很快就离婚了。

电影里我最喜爱的一句台词是这么说的：

Life goes on. It always does, until it doesn’t. But you know that, don’t you?


---

# 月光族


李老师你好，想跟您聊聊「消费观念」的事。

我的「消费观念」算是比较落后。我的家境并不贫穷，但我在买东西的时候却非常在意商品的价格，如果价格有点贵，即便我很喜欢也不买，因为我觉着省钱是种本事。而我的女朋友、父母和周围的很多朋友都很会享受生活，觉着喜欢就买喽。他们也常吐槽我的这种苦行僧式生活，说这也太屌丝了。李老师对此有什么看法？（问题来自微博私信）

——

哈哈，这明明是个优化问题 —— 你问一个学理工科的算是问对人了。

银行里一共就这么多钱，怎么花才能最快乐最幸福？

一

我前一阵子看到一篇文章，讲述在美国小镇里生活的一个大学教授，年薪五万，无论如何精打细算、精简开支，每月都所剩无几，基本只能当一个月光族，英文管这叫「live from paycheck to paycheck」。刘震云的成名小说《一地鸡毛》，说的也是这样一个故事。

这会让人陷入一种思维上的怪圈：越精打细算、量入为出，平时就越把精力用在如何花钱这件事儿上，越难以打破这种举步维艰的局面，去提高自己的收入。

所以说啊，长期来看其实有一个爱花钱的女朋友是好事儿：钱花得越多，越能激励你们俩去思考如何多挣钱。

「开源节流」——「开源」永远比「节流」更重要。

你看美国借的国债一年比一年多，经济不是照样红红火火、蓬勃发展嘛。

二

精打细算其实不难，但是如果像你说的那样只关注价格，长期来看，不一定是最省钱的。

原因很简单：贵的东西因为质量更高，说不定更耐用。比如你买一辆自行车，与其买辆最便宜的骑了几天坏了，不如买一辆贵一些的，说不定可以骑很多年。所以说，如果计算平均每年在自行车上的开销，买贵的比买便宜的更划算。

当然，我们到现在为止做了一个假设：你买自行车完全不在乎一辆好车给你带来的快乐。

这个假设几乎永远是错的。如果你的女朋友买一个Louis Vuitton的包比买一个Coach快乐二十倍 —— 虽然她不一定会拼Louis Vuitton这两个单词 —— 但价格仅仅贵了十倍，那她买LV的决定就绝对明智。

如果你买的东西可以用一辈子，一身西装、一件实木家具、一架三角钢琴，那也绝对不应该买最便宜的。因为一旦买了，穿着用着一点儿也不开心，早晚你收入增加了还会换更好的，长期来看，花的钱更多。

三

当然了，很多奢侈品其实卖给你的只是一个品牌的价值，比起普通商品，不一定能带来更多的快乐。

一块几万的机械表，每隔几年就要维修，走时还不如一块几百块的石英表。一架几万的单反相机，却很少带在身边，平时照相还是要用手机。

那很多人为什么还要买机械表买单反相机呢？

不是因为需要，只是因为得到一样梦寐以求的东西的那一瞬间，有一种快乐的感觉。

如果你不在乎这些，甚至越省钱越快乐，那少买奢侈品确实是「节流」的一个好办法。

四

那女朋友喜欢奢侈品怎么办？

你当然可以晓之以理、动之以情，提倡少买又贵又不合算的东西。

不过我更赞同另一种思路：你私下把她最想要又一直不舍得买的东西悄悄买下来，在一个街边的小馆子正吃饭的时候，不经意地拿出来送给她。

「Happy wife, happy life」—— 「你快乐所以我快乐」是花钱的最高境界。


---


# 处女情节


李老师您好，我想请教一下处女情结的事。

大学曾经谈过一个女朋友，差不多交往了一年的时候，我知道她不是处女了（我和她至今没有发生关系）。我的天塌下来了，我开始对她冷淡，发脾气，我开始心里恨她，恨上帝，心里想的将来要把那个男的阉割掉。我的心理产生了严重的矛盾，深爱她又接受不了她，整日处在抑郁当中，天天失眠被吓醒，天天在纠结到底爱不爱她。甚至一度有了轻生的念头，一下爆瘦20斤，真的走到了人生的尽头。

终于她也看出我的状态。为了不伤害她，我告诉她我抑郁了，她每天给我开导，逗我开心说会走出来的。我也看了很多这方面的书籍，我决定坚持我的爱，我要把精力放在学习上，我要考研，每天早出晚归。渐渐的我看到了希望，我突然不再想这件事，我好像更爱她了，每天学习到11点也要给她打电话聊天，不时会看看她的照片。

可是考研结果失败了，工作也没有着落，整个人垮了。所有的事接踵而来，朋友也伤害了我，这次彻底完蛋了，我又恢复到先前，不是冷淡，就是发脾气。最后她提出分手了，我也没有过多解释，我们就这样分开了。几次疼痛难忍，伤心绝望，我都没有联系她，我不确定我能有勇气坚持下去。

故事还没有完，现在我研究生也毕业了，工作还不错，终于几年之后我又碰到了一个我喜欢的人。我追了她很久，就在快要确定关系的时候她告诉我她谈了一个三年多的男朋友（之前她说没有谈过），我的天又一次塌了下来。开始追她之前我就想过她不是处女我能接受的，可是到了现在又活不成了。

我真的很讨厌这个情结，我也不知道为啥我这么强烈，两件事让我彻底对爱情绝望了，我想了很多很多，是不是我的占有欲，控制欲，还是我变态？如果我不爱她们，为什么会如此绝望？如果爱她们，为什么还接受不了？李老师，希望您能聊聊这个事，我不怕观点有多犀利，我想勇敢面对，谢谢。（问题来自微博私信）

一

好好认清形势吧，同学 —— 你现在只有两个选择。

要不然你单身一辈子。这就意味着将来你老了，很可能没有人陪你聊天，没有人陪你吃饭，没有人为你掉眼泪。你没有子女，没有亲人，独守空房，房子里只有冷冰冰的家具和电器。你玩儿着手机，潜意识里试图在一个叫Soul的app里找陌生人说话。

要不然你全心全意地爱她，将来说不定可以一起过日子，一起抚养你们的孩子。你老了退休了赋闲在家，可以和外孙子外孙女闲聊，万圣节可以带着孩子们出门要糖吃，一起大喊「Trick or treat!」，听她们弹琴、唱歌，给她们讲你当年热爱的金庸小说，还有你当年如何追到她们的姥姥的故事。

现在就决定吧，我这里在线等着你。

二

你的女朋友以前有过男朋友，不但不是坏事儿，还是一件值得庆贺的好事儿。不仅如此，她以前的男朋友越多，你就越值得开心。

你想啊，如果她以前交往过不少男生，什么人都见识过了，结果现在竟然会爱上了你，这是不是至少说明你长得还不算难看，见识还不算浅薄，能力还不算平庸，品格还不算低俗，至少比起她以前的男朋友，还有可圈可点之处？

人往高处走，水往低处流。恭喜你在竞争中脱颖而出，立于不败之地。

那如果反过来，她以前从来没有过男朋友，你是她的初恋又如何呢？

如果你们是青梅竹马、两小无猜时就相爱到现在，那可喜可贺，咱们可以拿这个素材写一篇感人的短篇小说。

如果不是，那隐含的风险就有点儿像买一支IPO的股票：你买的是谷歌的话自然大赚，但买的如果是Snapchat，很可能血本无归。

三

Kubrick的电影「Eyes Wide Shut」开场的圣诞酒会里，一个风度翩翩的陌生男士邀请Alice跳舞，边跳边聊：

「You know why women used to get married, don’t you?」

「Why don’t you tell me?」

「It was the only way they could lose their virginity and be free to do what they wanted with other men. The ones they really wanted.」

「Fascinating.」

四

我姥爷和我姥姥刚结婚的时候，每天工作时都要抽烟。姥姥也不跟他理论，只是每买一包烟，就另把一份烟钱单独存起来，很快就积攒了很大一笔钱。

姥爷看到了这笔钱，什么也没说，很快就戒了烟。按咱现在讲话，叫「秒懂」。

姥爷和姥姥后来培育了五个子女，晚年儿孙满堂，其乐融融。

作为一个男生，想要表达对你女朋友如火如荼的爱，最好的办法不是送给她九十九朵玫瑰表白，不是陪她到香港「血拼」，也不是带她去见你的爸爸妈妈，准备丰厚的彩礼。

而是慢慢地彻底地改变自己。


---

# 流水无意

李老师您好，我想请教一下关于我喜欢他但他不喜欢我的事。

平时和他聊天，是我主动开始的多，可能是我不够有自知之明，没有察觉到他有不想聊下去的意思，感觉良好。他跟我讲过他高中时他父母帮他申请晚上不去上晚自习，为了他能玩好休息好；大学时吃两份饭，担心别人很奇怪地看他，对面也放一个餐盘，假装对面还有一个人；还有研究生在美国去很多地方玩的趣事；还有他的婚姻观，培养孩子的观念，等等。有一次还叫我去他家坐了一会儿。

但是，在叫他出来玩了几次以后，跟他说了我爸爸去年生病去世的事情，那以后他就再也不愿意出来和我吃饭玩了，但还是会跟我在微信上聊很多。

直到最近，我问他是不是讨厌我，为什么不愿意和我一起玩了，他说为了我好，要保持距离，他替我保持距离。我问他原因，他说对我聊天的绝大部分内容没有兴趣，不想浪费时间；说要是和他聊篮球聊游戏，他就很感兴趣（他知道我不玩游戏）。我就说，那你可以带我玩，或者我看也行，他就说要和我保持距离。

平时聊天的感觉挺好，所以他说这些我挺惊讶的。我好不容易喜欢上一个人，对发生的这些事实在想不明白为什么，问他他也不是十分愿意说清楚。朋友说，其实就是他不喜欢我。我想可能也是这样，但我想他很明确地告诉我，他说话又总是很含糊很温柔。请问我应该怎么办？（问题来自微博私信）

——

一

我真的希望能告诉你点儿振奋人心的好消息，比如你还有一线成功的希望，比如如果你真心对他好，认真学习篮球技术认真打游戏，他一定会义无反顾地爱上你。

可惜我只能跟你说一个既成事实：你好不容易爱上的男生，他并不爱你，将来也不会爱上你的。

注意，我说的是他不爱你，并没有说他对你反感。

恰恰相反，多半儿他还挺喜欢你的某一方面的，比如喜欢你这个忠实的听众，喜欢跟你在微信上讲述他自己从前的故事。

可喜欢你这一方面并不代表喜欢整个的你。

你想啊，你对其他男生是不是也经常会喜欢他们身上某一两个细节——比如做什么事儿都靠得住，比如性格特别阳光——但是如果他们向你表白，你一定不会考虑？

没错儿，喜欢一个人身上的一个细节，不等于你就要嫁给他。

那你又要说了，他为什么不跟你明确说清楚啊？

等等，我怎么觉得他跟你说得简直没法儿再明确再清楚了呢？

他明明知道你不玩儿游戏，不懂篮球，还专门拿这两样儿举例；明明知道跟你出来玩儿才能进一步发展和你的感情，却坚决拒绝走出这一步；他都说了要「保持距离」了，你还要怎么更明确——「对不起，我不爱你，将来也永远不会爱你」？

他在不伤感情的基础上对你已经仁至义尽了——这阵子估计心里正想：这姑娘怎么一意孤行、没完没了啊？

二

要是说他「很含糊很温柔」，你大概没见过真正「很含糊很温柔」的男生。

我在美国上学的时候有个小师妹，到美国的时候本科刚从国内顶尖名牌大学毕业，既冰雪聪明又如花似玉，按常理说，在美国应该有大把的男生追她才对。

可惜的是，她刚到美国一下飞机，在机场就被一个其貌不扬又特别不爱说话的男生接走了，根本就没别人什么机会。

这个男生是真的不爱说话。我们大家跟他聊天，他一般就是听着，最多也就回一两句，从来没见他高谈阔论，讲过自己的什么故事。让人感觉有点儿像一个久经战阵的老兵，「欲说还休，却道天凉好个秋」，什么都经历过了，什么都不会再新奇。

那时中国学生会每年活动的重中之重，就是去机场接新生。当时他在机场第一次见到小师妹时是怎样的喜出望外，怎样「蓦然回首，那人却在灯火阑珊处」，就不得而知了。大概跟《致青春》里接新生接到郑微的老张心情差不多吧。

和郑微不尽相同的是，小师妹很快就和我们这位不爱说话的幸运儿恋爱了。几年以后他们在学校附近的一个风景秀丽的公园结婚，婚礼大宴宾客，还请了我去参加。

两人机场初次相识之后的第十个年头，在纽约离婚了。据说是男生婚外爱上了别人。

不过我们的小师妹也不是吃素的。离婚后立即开展一项庞大的工程，寻找下一位终生伴侣。连Facebook上的状态都写着：looking for a relationship.

功夫不负有心人，一年后她就找到了如意郎君。

三

「请问我该怎么办？」

你应该向小师妹学习她百折不挠、全力以赴「looking for a relationship」的精神，迅速组织力量，「放长线，钓大鱼」，把找男朋友作为一个重大研发项目来贯彻实行，争取在最短的时间内找到你最爱的人。

但是不要等到十年以后才明白一个道理：

你爱的人也许并不爱你。


---

# 冷暴力

李老师您好！我想跟你请教有关前男友的问题。

我和他分手是高考完第二天，他对我冷暴力，逼我说出“分手”二字（我觉得男生很擅长这样）。分手后一周后他有了新女朋友，那个女孩我也认识，我很伤心。大学我和前男友在一所学校。他和那个女孩在一起的时候私底下还和我保持联系，原因是因为不能彻底忘掉，还是会想起我。我当时还很爱他，他偶尔会来找我我从不拒绝。我们也一致对外保密保持着联系，但一直是他找我，因为他有对象所以我没主动找过他。

后来他分手了，分手后喝醉酒了来找我倾诉，说没珍惜我等等…就在我还以为我们会复合的时候，他在大学交了个新的女朋友。事情发生的很突然…后来我就劝自己放弃。他也消失很久了没有联系过我。我和他就这样拉拉扯扯到大三。

他最近又找我了，说梦到我了。他来找我我还是没拒绝。我清楚他有女朋友，从他说的话里感觉他对自己的现任女友不是很走心。他还叫我宝贝。原本以为我彻底放下了，但我又开始在意他了，期待他的早安和晚安，我也还是和以前一样，他不找我我绝对不找他。我该怎么办？我感觉他心里有我，这三年我一直没开始新的恋情，也是因为对他抱有一丝希望吧。他一找我，我就开始幻想各种关于他的未来。真的不知道该怎么办了。朋友劝我放手，也都不耐烦了。我表面上表现出对他不在意，但我心里明白自己的想法。

老师我就想问问你我有必要再为他在心里留位置吗？谢谢老师，麻烦您了！（问题来自微博私信）

——

一

你在写这个问题的时候，心里一定门儿清。

你清楚地认识到他和你的距离越来越远，认识到你们成功的机会越来越渺茫，认识到你早就应该放弃他。

但是微信里收到那句「早安」的瞬间，你还是身不由己，想着「反正他不找我，我绝对不会去主动找他的」，然后秒回。

这就好像一个痴迷炒股的股民，眼睁睁地看着手里的股票一年年地大跌，知道应该早点儿把股票清仓止损，可是却总抱有一线希望，想着「说不定已经跌到底了，很快就会大涨」，一直不卖，直至血本无归。

所以说如果真要短线炒股，不能手工去操作交易，而是应该设计一个算法——也就是一个计算机程序——由算法去交易，而需要手工设计调整的，仅仅是算法的参数而已。

人都有感情，有七情六欲，容易情不自禁、身不由己，所以炒股这种事儿，就应该采用没有感情的算法去做。将来自动驾驶算法成熟了，开车也可以尽量让算法来开，不至于把车开到桥下去。

可惜的是，人工智能算法还不成熟，至少现在还没法儿在微信替你和男友聊天。男友的「早安」来了，还是忍不住想回，怎么办？

二

想回就回呗。

不过如果你学过一点计算机科学，你会发现里面经常会提到一个「多线程」的概念。

有了「多线程」，一个计算机程序可以同时运行好几个算法，每个算法都以为自己拥有整个CPU。通俗一点儿说，就是一心二用甚至一心多用，好几件事儿同时进行。这就好像《射雕英雄传》里周伯通的双手互搏之术，心无杂念，分心二用，左手画方，右手画圆一样。

你想回他的微信，觉得希望虽然渺茫但终究还有一线希望，行，你随时可以和他开聊。不过回的同时你还得再多开几个「线程」，同时跟其他几个男生聊天，每一个都聊得火热，让他们以为是唯一在和你聊天的人。

在计算机科学里，这叫做「虚拟机」，你虽然只有一个「物理机」，但是可以分身出多个「虚拟机」，同时和好几个男生「谈恋爱」。

可这不是骗人吗？

准确地说，不是和好几个男生「谈恋爱」，而是同时「date」好几个男生。「date」这个英文词儿的好处是没有排他性，你可以中午date这个男生，晚上去date另一个男生，大大提高「谈恋爱」的效率。

而提高计算机程序执行的效率，正是当年发明「多线程」的初衷。

三

英文里分得很透彻：「boyfriend」你可以「date」很多，但是「fiancée」你只能有一个。

而什么时候一个男生就从「boyfriend」升级到「fiancée」了呢？

在他实在受不了你的「多线程」你的「虚拟机」，于是在一个灯光昏暗的西餐厅，酒过三巡，忽然对你单膝跪下，拿着三个月工资买来的钻戒，对你说「Will you marry me?」的那一刻。

「梦到你了」、「早安」、「晚安」？

这些统统不算。

---

# 告白

上上周六，我给喜欢的师兄发微信告白了，但师兄最近有女朋友了，拒绝了我。我后半夜发的消息，他早上回复的我，并且说要和我聊聊。但我当时被拒绝感觉很丢脸，和他见面也很尴尬，就没有去。我当时想着就是告白失败就放弃了。

上周还好，这周不知道怎么回事，每当下午四点多以后，看他就离开办公室，我猜是和女友约会去了，我就会难过。真的，很难过，从我表白之后，我们再也没有说过话。

我俩一个办公室，座位挨着，中间一块挡板，其实我难过的也有一点是觉得他根本一点都不关心我的感受。告白那天我还看他给另外一个小师妹朋友圈评论了，最近有时候他在办公室也会很开心的和别人聊天什么的。我因为觉得尴尬，现在在办公室他参与的聊天我都不会参加了，他是不是一点都不关心我的感受呢？

我其实一直想要表现的落落大方的样子，和他聊一次。我也不想在毕业前和他一直不再说话，毕竟是我喜欢的男生。我希望我们还能像从前那样聊天什么的，可每次一想约他聊天，就想人家会不会要去约会，没时间呢？那多尴尬，我就说不出口了。我也讨厌自己为什么别人不喜欢我我还总挂念着他，甚至会想万一他们将来分手了……李老师，我脑子挺乱的，该怎么办？（问题来自微博私信）

———

一

你有没有想过一个问题：如果你三十岁前命中注定会遇到三个男生，希望能和其中你最爱的最优秀的那个结婚，那你在遇到第一个男生时应该怎么做呢？

是直接表白，私定终身呢 —— 还是守株待兔，静等生命中你下一个爱上的男生出现，看看是不是比第一个更加出色？

正确的最优方案是：不要跟遇到的第一个男生表白，而是静等第二个男生出现。第二个男生如果比第一个男生优秀，就直接表白和他结婚；如果不如第一个，就等到第三个男生出现跟他表白结婚。

在全部六种的出现顺序里，用这个方法，可以有三种情况 —— 50%的概率 —— 能和最优秀的那个男生结婚。

如果有四个男生，最优方案还是略过第一个男生，从第二个男生开始，一旦发现比第一个更好，直接表白。这时你有46%的概率找到那个最优秀的男生。

如果有五个男生，最优解是略过前两个男生，从第三个开始，一旦发现比前两个更好，直接表白。这时你有43%的概率找到那个最好的男生。

你发现没有，这个算法按顺序分成两个步骤。第一步只去发现和收集有关男生的「数据」，而不去表白；第二步和第一步发现的最优秀的那个男生比较，一旦发现一个更好的，马上表白。

即使你遇到的男生很多，一样有最优的算法：第一步这个收集「数据」的阶段应该是所有男生总数的百分之三十七。

这么说吧，如果你从二十岁开始你的「数据收集」阶段，三十岁之前必须确定婚姻人选，那你在二十三岁（零八个月）之前，应该对男生持「收集数据」的观望态度；但一过二十三岁，就随时准备表白结婚。用这个算法，你找到最佳选择的概率，大约也是37%。

这就是著名的「最优停止」(optimal stopping) 理论。

你瞧，向你一辈子喜欢上的第一个男生表白，很有可能是一个错误的决策。要是以后遇到更好的呢？

所以说啊，他把你婉言拒绝了，避免了你因为一个错误的选择而和最优的结果失之交臂，你应该感谢他才对啊。

二

你一定要说，可是表白不等于就一定能成功啊！

你说得没错儿，咱们前面的理论做了一个不太现实的假设：表白不能保证结婚。说到底，不是人人都是刘雯刘亦菲。

那如果表白的成功率如果只有百分之五十怎么办呢？

答案很简单：提前结束对男生的数据收集工作，进入算法的「表白」阶段 —— 从37%提前到25%。用这个最优算法，你和最优秀的男生结婚的概率，也是25%。

那如果以前收集过「数据」的男生，你发现比后来的男生都优秀，希望吃「回头草」去跟他表白是否可以呢？

咱们假设你美得倾国倾城，他恰巧还没找到女朋友而且接受了你的表白的概率是50%，那么你的最优策略是推迟进入「表白」阶段：从37%推迟到61%。这时你找到最佳选择的概率恰好还是61%。

哈哈，下回如果父母再催你找男朋友，你就说现在正处于「最优停止理论」里的「观望」阶段。

三

好吧，咱们不聊算法了 —— 你太喜欢这个男生了，希望不惜一切代价追到他，「optimal stopping」be damned.

你虽然平时经常和他聊天，但是表白却以失败告终，主要是方法不得当：你给他发微信，还留给他大量思考如何回复的时间，这大大降低了成功的概率。

表白最好的方式，是语言上含糊，行动上明确。

比如聊得正high的时候，讲一个事先准备好的故事，引入入胜，风情万种。你们一起开怀大笑，然后你挽住他，慢慢而随意地靠在他的肩上。

也许——仅仅是也许啊——他说有女朋友只是一个拒绝你的借口。也许你如果有足够的勇气，还有希望。

人生如戏。就当是练兵场上，为命中注定的那下一个男生而「实战演习」吧。


---

# 鸡娃

李老师你好！有件事苦恼我很久，想听听你的建议！我家姑娘今年三年级，从小到大对学习不努力，成绩很好，现在三年级态度决定一切，依然是那个状态，每每见了我都要打她，因为学习态度特别不好。总被我哄着狠着去学，最近态度越来越差，上课不听讲，这样下去真的很担心她能不能考上好学校！另外我也并没有积极陪她学习，看她那态度，我非常没耐心。请李老师传点经验给我！谢谢。（问题来自微博私信）

一

我特别能理解你用了四个惊叹号表达的这种焦虑心情，因为带孩子这件事儿，实在是太不容易了。

任何一种似乎简单而且对别人家孩子挺有用的道理——快乐教育也好虎妈战歌也罢——对自己家的孩子都似乎没用。

我六七岁的时候，两岁的妹妹下午睡着的时候妈妈临时要上班去开个会，于是叮嘱我说，如果妹妹醒来哭了，就用开关电灯作为信号，妈妈在办公室看到，马上就会回家。

妹妹很快就醒来了，开始大哭。我使劲儿连续不停地开关电灯，一个多小时过去了妈妈也没回来，感觉像在盼望着一位救世主显灵。

到我三十多岁时，有一阵子白天自己在家带两个女儿，当时一个两岁一个不到五岁。经常会好不容易做好了午饭，孩子不好好吃；吃完了不睡觉，到下午困了就开始哭。后来我自己发明了一个有效的新办法，把孩子带上开车出门，车比较晃悠，可以很快睡着。

可惜的是，车一停下来，孩子就会很快醒过来开始哭。于是我就每天慢悠悠地开着车，在这个城市的大街小巷穿梭着。

我靠自己的努力，也可以一个人带两个孩子——那时有一种「中国人会造原子弹了」的自豪感，因为带孩子这件事儿实在太难了，是对一个人耐心的终极考验。

我要向世界上所有的母亲致以最真挚的敬意。

二

带孩子难，「高标准严要求」地把孩子带好就更难了。

说到底，谁不希望自己的孩子将来琴棋书画样样皆通，学习成绩优异，上一所理想的大学？

可关键问题在于，平常到底应该怎么做，才能教育出优秀的孩子？

你发现没有，中国孩子的父母在回答这个问题时，理念惊人的相似。我们强调学习态度端正，上课认真听讲，按时完成作业，还有考试成绩排名的重要性。

这些理念超级实用：无穷多的中国孩子既聪明又刻苦，各种竞赛和考试中脱颖而出，升入越来越好的学校学习。

可最让人头疼的问题是，别人家的孩子个个令人羡慕，自己家的孩子却总是不「争气」—— 成绩不理想，或者像你担心的「学习态度差」「上课不听讲」。怎么办？

三

按照一种既定的成功教育理念去带孩子，就像计算机算法中的一种叫「exploitation」的策略。别人家的孩子明明能成功运用，到了自己的孩子就会卡在某个中间状态，没法儿继续下去。

强迫孩子「端正学习态度」，甚至有适得其反的效果。

你可以试试准备一个计数器，每次提醒孩子「上课要认真听讲」的时候，就把计数器按一下，一个月以后看看你一共提醒过孩子多少次。

如果是你自己，有个人天天提醒你这个老生常谈的道理，你不烦死才怪了呢。你一定会说，我早就知道了啊。

孩子也一样，聪明着呢。你能想到的道理，人家早就听过不知道多少遍了。其实你完全不懂的东西，孩子也说不定懂不少。

你一定会说：「知道？知道上课还不听讲？」

哈哈，两个问题：你怎么知道孩子昨天上课没有去试图认真一点儿听讲？孩子以前为什么不爱听讲？

说实话我小学时上英语课，上课也不听讲。原因很简单：老师讲的我早就都会了啊。你说你孩子成绩很好，就是上课不听讲，那不是和我当年英雄所见略同嘛？

其实你迫切需要的是在「exploitation」上面再加上一点儿计算机算法中的「exploration」—— 让孩子「东一榔头西一棒子」地去探索未知的世界。她爱唱歌就让她去学唱歌，爱写小说就让她去写小说，爱打网球就让她去打网球。

你要做的事儿，只不过是多赚点钱，给她找最好的网球教练。

四

小女儿前一阵子去参加一个舞会，认识了一个外校的男生。她平常腼腆不爱说话，这天却和这个男生开心地聊了一个钟头。

舞会结束后她激动地跟我说：「You should be proud of me!」

没错儿，「优秀」的定义，不一定是成绩有多好，大学上没上「985」，而是有能力突破自己的极限，做成一件「中国人也可以造原子弹」的那种令人骄傲的事儿。

无论这件事儿是不是小到跟陌生人聊了一会儿天，或者独自一个人带着两个孩子，开着车在大街小巷里游荡。


---


# 冤枉好人

李老师，很抱歉再次打扰到您，我和她碰上了一个问题，这个问题让我们都不知道该怎么办了。（哭）

女友认为我出轨。我和她异地恋，我那天去看她和她待在一起的时候，一位我曾经的女性朋友发消息给我了，内容是上次聊天聊到的键盘的事情，她换了一个蓝牙键盘觉得很可爱，发消息和我说了一下。当时我的女友就在我边上，她看到有其他女生发消息给我，并且我因为会担心她误会，我会删除记录，然后那天我女友看见了就直接崩溃了。导致我们的关系变成现在这样了。

我和那位女性朋友是和女友在一起前认识的，有时候会联系，平常聊天我都是和她聊一些我和我女友的事情，因为我自己朋友很少，很多时候和女友闹矛盾我都不知道怎么办，又想解决问题就会去问问她，以她的的视角看看有没有办法，对于那些我做的事情我都是担心我女友会多想才删除的，没想到变成了现在这个样子。我可以拿我这辈子任何重要的事情发誓，我要是有什么出轨的想法，我都不得好死。我不知道怎么去处理这些问题，我明明很爱我的女友，为了见她，我各种省钱，为了回她消息，我会时不时看手机，都已经出现了幻听，现在我和我女友的关系变成这样，我真的不知道怎么去做。（问题来自微博私信）

哈哈，谈恋爱嘛，总是要吵架的 —— 我都可以想象你们之间的对话：

「我可以发誓，绝对从来都没有过出轨的想法。」

「那你没事儿干嘛要删微信聊天记录啊！」

一

大概是七八年前的圣诞节前几周吧，我运气不太好，收到了法院的一封信：「Jury duty call」。

什么是「Jury duty call」？哈哈你放心，不是传票，而是要求我去法院履行每一个加拿大公民都必须履行的义务：参加一个「Jury panel」。

「Jury panel」又是什么呢？就是一两百人在一个大房间里待命，时刻准备着，哪一个案子开庭了需要选择陪审团成员（juror）时，就进去几十个人备选。

我那天的运气真的是超级糟糕。一个强奸案件开庭审理，随机抽签竟然把我抽中了，双方律师发现我的职业是教授，欣然同意，不由分说，我立即成了十二个陪审团成员之一。

案子审理了五天。审理过程中，不允许带手机，不允许上网，必须专心认真地听讲，每个人只给了一支笔和几张纸用来做笔记。

但后来我发现，这五天时间是我印象里过得最充实的五天。

因为这段时间，法官给我们陪审团的每一个成员，详尽而又清晰地讲解了加拿大法律的要义。给人的感觉，就像张无忌在武当山顶跟张三丰学太极拳，新鲜热辣，现买现卖，学了马上就可以拿来用。

每一个陪审团成员，刚开始可以完全是法盲——需要的只是你公平、能独立思考、听得懂英文。

而双方律师总结发言结束之后，对案件的判决就由陪审团单独决定，法官无权过问。

二

在法官给我们讲过的法律要义中，我记得最清楚的两条，是「presumption of innocence」和「beyond a reasonable doubt」。

「Presumption of innocence」好懂：在控方（Crown prosecutor）证明有罪（guilty）之前，必须假设辩方（defendant）是无罪的。

而「beyond a reasonable doubt」法官则花了很长时间给我们解释。控方必须提供足够证据（burden of proof），证明辩方是「guilty beyond a reasonable doubt」。也就是说，不能是「可能有罪」（probably guilty），但也没必要完全不可能无罪（proof to an absolute certainty），而是这两点之间的一个状态。

而这里的怀疑（doubt）不能基于同情或偏见，而是要基于逻辑和常理（reason and common sense）。

正确理解「reasonable doubt」，可以援引著名的「Blackstone’s formulation」：宁可放走十个坏人，也不冤枉一个好人。

我记得我当时想的是，这都是谁发明出来的 —— 发明这玩意儿的人简直是个天才。

三

我想说的是，男女朋友或夫妻之间若是有所猜疑，我同样提倡「beyond a reasonable doubt」。

而你的这个案例，你的女友作为控方律师，完全无法提供足够强有力的证据，可以「beyond a reasonable doubt」。

和别的女生聊天不等于在和她谈恋爱，而删除微信聊天记录，则很可能是因为你害怕她会多想，会误解。

如果我给你这个案子一个十二人陪审团，他们一定会一致认定，没有足够证据证明你出轨。

「Beyond a reasonable doubt」这道理听着很高大上，但其实很朴素：咱不能捕风捉影，而是要有真凭实据。

其实我很能理解你女友作为控方的心情：万一辩方出轨了呢，心里过不去这个坎儿。

但是换个角度想，如果因为捕风捉影而和一个有志青年 —— 现在流行叫高富帅 —— 失之交臂，多不合算啊。所谓「过了这村儿就没这店儿」了。

四

那次审理的强奸案件，双方证人证词陈述花了五天时间。陪审团却只用了一小时就达成了共识：罪名不成立（not guilty）。

谁也不知道强奸案是否发生过，只是把「beyond a reasonable doubt」的原则用上了而已。

希望你的女朋友看了我的这篇文字，可以回心转意，和你和好如初。

就是别再删微信聊天记录啦。


---


# 罗马假日

我遇到了我喜欢的人，在喜欢他的过程中，我确实变成了更好地自己。因为之前他没有明确拒绝我，让我有一丝希望，但是现在他明确拒绝我了，同时也因为是某方面的合作伙伴，我们达成了做好朋友的关系。我很舍不得他这个好朋友，但是我不知道该如何与自己喜欢的人做好朋友？（问题来自微博私信）

一

你一定看过六十五年前拍的那部老电影《罗马假日》吧？

也许是奥黛丽 · 赫本和格里高利 · 派克在电影里合作得太出色了，当时的报纸上有传言，赫本和派克在拍电影的那一段时间曾经相恋过。

对于这一传言，赫本是这么说的：

「Actually, you have to be a little bit in love with your leading man and vice versa. If you're going to portray love, you have to feel it. You can't do it any other way. But you don't carry it beyond the set.」

中文大意是：「如果你想把爱情演好，你就得有一点儿爱的感觉。但是电影拍完了，你也没必要继续爱下去。」

派克则是这么说的：「Everyone in the set was in love with her.」（剧组里的每一个人都爱她。）

《罗马假日》是赫本拍的第一部好莱坞电影，第二年她就靠这部电影里的出色表现得了奥斯卡最佳女主角奖。派克后来也非常喜欢罗马，每次带孩子去罗马都要去电影里著名的「Mouth of Truth」去玩儿，重温他当年和赫本稍带临场发挥的那段儿表演。

赫本是在派克为了庆祝电影公映举行的一场鸡尾酒会上认识了她的第一任的丈夫Mel Ferrer的。后来赫本和Ferrer一起生了一个孩子，婚姻持续了十四年。

无独有偶，在这个电影拍摄过程中，派克也认识了一个去采访他的年轻女记者。电影上映两年之后，派克和他原来的妻子离婚，和这个女记者结婚了。

赫本和派克因为这部电影，成了一生的好朋友。

二

几年前网上有一个流传得很广的故事。故事里说拍电影时派克其实是很喜欢赫本的。赫本结婚时，派克送给她一枚蝴蝶胸针。这枚胸针赫本非常喜欢，一直珍藏着。

到赫本去世后，派克亲自参加了她的葬礼，在葬礼上老泪纵横，对着赫本的棺材说：「你才是我今生唯一的真爱。」十年后的一场拍卖会上，年迈的派克亲自前去买回了那枚胸针，去世时还把胸针放在身边。

这个故事听起来挺感人，我记得五六年前微博上还有不少人转发过。

但这段故事其实极有可能是后人杜撰的。谷歌搜索「Hepburn Peck Butterfly Brooch」，没有什么值得信赖的消息来源。

唯一值得信赖的一篇是《人物》杂志在赫本去世那年发表的文章。文章里没有提到胸针，仅仅提到了赫本葬礼中用到的鲜花是派克和其它朋友们一起送的。

更何况故事实在是有悖常理，赫本的葬礼上她前夫Ferrer等人都在场，派克不太可能突然跟大家宣布，其实赫本才是他一生的真爱。

三

无论这段感人的故事是否真实，《罗马假日》公映后赫本一直住在欧洲，派克则一直住在美国。

他们各自都很忙，很少联系。就像我们大家也很少跟远方的朋友联系一样。

我觉得，你越是喜欢这个男生，越想和他做好朋友，你和他就越做不成好朋友。

我建议你远走高飞，别动不动就和他微信联系，该忙什么就忙什么，联系越少越好。

只有这样，你们才有可能真正成为一生的好朋友。

就像赫本和派克那样的好朋友 —— 一个人去世了，葬礼上还有另一个人送的鲜花。


---

# 预测未来

李老师，您好，新年快乐。很抱歉新年第一天就用这样的方式打扰您。我有一个困惑，刚才看到有人转发2019年属相蛇犯太岁，我不太明白，就去查了一下。是描述属蛇的人各种运气不好，甚至会有血光之灾。我不知道该不该相信这些。李老师，您是怎么去理解以上？想听听您的看法。

一

先给你一个结论吧：任何试图预测未来的观点，都别盲目相信。

比如如果你看了一篇朋友圈转发的文章，说美国股市已经见底，2019年一定会稳中有升；或者看了一篇公众号里的 「十万加」，说新的一年国内二三线城市房价必然会大跌，你千万别盲目信以为真。

原因很简单。如果文章的作者确实有这种预测未来的能力，他完全可以靠这种「超人」的能力自己在股票或房地产市场里大赚一笔，没有必要把他的预测结果费尽千辛万苦写成文章免费提供给你阅读。实际上，即使作者的预测只是「有很大的把握」，他也一样可以依靠期货等各种金融衍生产品对冲风险，有多大的把握就可以赚多少。

金融和房地产市场的本质特征是，虽然几十年的长期可以升值或者保值，但一年甚至三五年的短期未来是无法准确预测的。

你也许要问，那像巴菲特这样的「股神」呢？

像巴菲特这样在股市中可以依靠准确的投资选择长期跑赢市场的人，其实也不是只有他一个。但是如果你希望他们替你投资，你得支付不菲的佣金费用。况且即使是巴菲特，从几年的短期来看，也不是每一次预测和投资选择都是正确的。

天下没有免费的午餐。If it sounds too good to be true, it probably is.

二

本质上来说，炒股有关的建议和看属相看星座运势差不多：它们都是利用你「想赢怕输」「不怕一万就怕万一」的心理，吸引你去关注。

预测你新的一年有「血光之灾」，后面多半儿会给你一些「化解之法」。要是预测你新年会「时来运转」「福星高照」呢，那后面多半儿会话锋一转，说几条「注意事项」，给你出几条高招。

这些运数预测文章的作者，多半儿希望能利用你愉悦或害怕的心理，吸引你去传播、打赏，去为这些「知识」花钱。说到底，咱们现在不是正身处「大数据」和「知识付费」的时代洪流中嘛。

可是我一直不太理解为什么很多读者会真的相信跟属相或者星座有关的分析。你想啊，同一年生的上千万人，或者同一星期生的几十万人，无论遗传基因、家庭背景、政治面貌、文化程度有多大差异，运数和性格都大致相同，这怎么可能呢？

有人可能会反驳，不对啊，我认识一个发小，用属相和星座的那一套去分析她的性格，特准！

别忘了，a broken clock is right twice a day. 

三

微博的粉丝分析中，甚至都能找到粉丝星座的分布图。在我的微博粉丝里，魔蝎座的人最多。

我对星座性格分析不熟，就上网搜索了一下。对待感情，魔蝎座的人「很难相处，有种高处不胜寒的感觉。碰到喜欢的人，不会主动的表白，只是做一些事情，引起对方的关注，当对方注意到的时候，摩羯座的人又会显得特别扭捏，尽管这就是自己想要的。」

哈哈，我前一段不是一直在说千万不要表白嘛 —— 看来我的文字最能和魔蝎座的人产生共鸣。

但是其实真正的原因多半儿是，很多粉丝在开通微博帐号时不想透露自己的生日，就随便填了一个一月一日。

而一月一日正好是魔蝎座。

本文此后还有百分之九十有关魔蝎座的精彩内容，晓之以理，动之以情，有理有节，不容错过。您可以猛戳以下二维码加入本文专属的收费微信群，每月酌情收取一元人民币费用。名额有限，先到先得，欲购从速。



---

# 如何攀比

李老师，人该如何正确看待比自己优秀的人呢？（问题来自微博私信）

一

咱们来假设一个场景：公司年会上有一个抽奖活动，几百个人可以有一个中奖的机会，如果中了奖，可以得到一部你一直梦寐以求的苹果（或者华为或者锤子或者小米）手机。

你的一位同事抽中了，非常高兴。你会是什么心情？

我想你大概跟我差不多。如果不认识这位同事，大概没觉得什么，甚至会为他高兴。如果恰好和这位同事比较熟，大概会有一点点羡慕，但是一小会儿以后也就忘记了。

一个人比自己「优秀」，就好像她抽奖时运气比自己好一点儿。也许会有点儿羡慕，但一小会儿之后最好就忘了。

二

但是其实我觉得，中奖的同事我会心生羡慕，但是「优秀」则连那一点儿羡慕都没太大必要。

主要是因为「优秀」这两个词儿很难精确定义。

离我住的地方不远，有一家有五十年历史的自行车店，叫「Mariposa Bicycles」，专门手工制造铝合金自行车。店主七八十岁了，造了一辈子自行车，还把自己的手艺传给了儿子。虽然自行车早就可以大规模生产，材料也早就演变成碳纤维或钛合金，但是只要还有顾客愿意买这个老店的自行车，他们父子俩就可以凭手艺继续把店开下去。

如果跟一个天天「空中飞人」全世界出差开会的企业高管比，我甚至觉得这父子俩更加「优秀」。几十年后，高管的「PPT」早就烟消云散了的时候，父子俩手工制造的自行车还可以骑着上路。

我一直有点儿羡慕像这父子俩这样的人。羡慕他们可以一辈子就专心做造自行车这么一件事，把这件事做得尽善尽美，而且还有买主认可他们的手艺。

我家附近还有一家汽车修理店也是如此。日出而作，日落而息，在同一地点开了三十多年了。我开的一辆十七年前买的车，又锈又旧，但每次坏了就放心地送到这家店去修理，「新三年，就三年，缝缝补补又三年」，竟然还能天天开着上班。做为一个连换个灯泡都要上网研究半天型号的我，对这家汽修店的老板也一样羡慕不已。

所以说啊，「优秀」这个词儿真的很难定义。有人大概觉得「富二代」啊明星啊网红啊大公司老板啊天天吃香的喝辣的更加「优秀」；而我呢，相比「治大国」，我更加偏爱「烹小鲜」；相比「待到理想化宏图，咱重摆美酒再相会」，我则更向往「小小竹排江中游，巍巍青山两岸走」。

所以啊，在你因为别人更「优秀」而「羡慕嫉妒恨」的时候，他说不定也在暗地里羡慕你呢。

三

我之所以不怎么羡慕富二代、网红和老板们的「优秀」，是因为这些跟在抽奖活动里中奖差不多，需要有很好的运气。

我更偏爱那种不怎么靠运气，而只需要有一点儿像样的手艺和特长，每天认真而专业地做好自己的事情的那种「优秀」。

外科医生每天做一台手术，钢琴老师每天教几个孩子，专车司机每天跑几趟机场，饭店厨师每天做几道拿手菜 —— 我觉得都特别优秀。

想起周围有这么多比自己优秀的人，我感到日子过得很踏实，人气十足，心情愉快。


---

# 人生的失败


亲爱的李教授你好，关注你的微博很久了，特别欣赏你的人生态度和思想。作为一个人生阅历还不足丰富的人，想请教您如何拥有一颗坚定的心去对待人生的挫折和失败呢？最近遭受了学习生涯中最大的失败，分数和排名下降很多。心态上的打击很大，也不停的在否定自己。虽然也明白“知耻而后勇”的道理，但在这一个努力的过程，心态很难坚定下来。想听听你的建议，谢谢！（问题来自微博私信）

一

我觉得咱们首先得琢磨一个基本问题：什么才算是人生中的失败？

「失败」这个词儿让人感觉挺严重的，所以我觉得「人生中的失败」一定和长年累月的错误生活方式有关系，有点儿「在错误的路上越走越远」的感觉。

比如，明知抽烟对自己和家人都不利，却没有下定决心迷途知返，可以算是一种「人生中的失败」。

或者明知成天玩儿游戏影响学习和工作，却深陷其中不能自拔，大概也可以算是一种「人生中的失败」。

那考试没考好呢？

我觉得这不能算，因为考试有很大程度上的偶然因素。比如考前正好身体不适，复习准备和考题相差甚远，或者一步推导出了差错，以致整道题功亏一篑，都可能是考试没考好的原因。

我就有幸认识一位很特别的同学，特别之处正好就和考试有关。

二

我认识这位同学那一年，和你一样也是刚上大学。

这位同学有一个与众不同的姓氏，他姓「移」。不知为什么，老是让我想起毛主席的文章《愚公移山》。大概也正是因为这个奇怪的姓氏，没有人给他起过外号，大家就尊称他为「老移」。

我刚上大学那年流行穿军装，至少也得斜背个军挎，那种一无所有的感觉，和校园里大喇叭放的崔健黑豹什么的很「搭」。

而老移两鬓略有些斑白，成天穿的是一件西服。西服穿得时间长了，显得有些破旧，风尘仆仆。

老移的爱好也和别的同学不一样。别人的业余爱好至少有好几种，有的人谈恋爱，有的人爱打牌，有的人爱踢球 —— 而老移只看武侠小说。别人白天学习时他在看小说；晚上十点四十五熄灯了，别人开始聊天，他则点起蜡烛，继续看他的小说。

据他自己介绍，五道口租小说的那家店里的所有武侠小说，他都看过好几遍了，有点儿「熟读唐诗三百首，不会吟诗也会吟」的境界。

直到很久之后，才听说了老移当年的轶事。

据说老移的高中时代是在江苏省读的书，88年就考上了清华大学计算机系。可惜的是，上了大学以后因为沉迷于看武侠小说，他好几门课不及格，被学校勒令退学了。

于是老移又回到了他江苏的老家，又准备了一年高考。1990年 —— 也就是我入学的那一年 —— 再次考入了清华大学计算机系。

三

后来的故事估计你都能猜到了。老移因为看小说，又是多门功课不及格。不过这回估计连系领导都被他「我想要回到老地方，我想要走在老路上」的精神所感动了，终于没有再次决定让他退学。

大学五年上完毕业的时候，我们同学里出国的出国，推研的推研，闪婚的闪婚，而「成功」、「失败」、再次「成功」了的老移，终于因为看了五年武侠小说，不及格的课目太多，没有拿到学位，只拿到了一纸结业证书。

说他看了五年小说，其实不是特别准确。准确地说，有一年物理课期中考试前，老移突然大彻大悟，开始学习。结果几天之后的期中考试，他一举拿下全班最高分98分。

考完期中考试之后，他又开始了他的武侠之旅。

四

老移从清华毕业后，去了建行系统工作了多年，又辗转移民了加拿大。

我十年前最后一次见到他时，他还是那副两鬓斑白风尘仆仆的样子，还是永远穿着一身略显破旧的西装。

他还是和多年以前一样，不怎么爱说话，笑得憨厚而从容。按这几年时髦的词儿来形容，老移一直是一「佛系」青年 —— 六十年代那会儿叫「逍遥派」，正是金庸武侠小说里的常用词。

我向老移的媳妇「表白」，说老移当年一直是我青春无悔的偶像。因为老移太擅长考试了，以至于考好考坏都是他一个人说了算。

有点儿像当年清华校园大喇叭里常放的那首崔健的《假行僧》：

我要从南走到北 我还要从白走到黑 
我要人们都看到我 但不知道我是谁

新年快乐。


---


# 夸自己

李老师，您好。我是从褚老师那认识的您。看了您不少微博，听了您不少分答，特别喜欢、敬佩您。您的善良、真诚以及没有架子，让我特感动。想听您夸夸自己。（问题来自分答「在行一点」）

我其实还真没啥优点，不过倒是有一特点。

我的特点就是运气一直很好。

就比如说高考吧——我的物理和生物一直是弱项，而语文是高考强项。结果我那年的全国统考试题，正好语文题极难，而物理非常简单，结果轻松过关，在人生第一大关口上展示了极其强悍的好运气。

上了清华一年过去了，忽然注意到一个同年级的女生绝对是小美女啊，怎么以前没发现？后来才知道她刚刚换了一副新眼镜——以前那副太难看了。我学习不如小美女，体育也不太灵，除了学校作文比赛得过名次，还真没什么突出的特长。小美女不但有人追，还有男朋友，结果后来竟然被弱不经风其貌不扬的我追到了，在人生终身大事上一锤定音，我再次展示了运气好的重要性。

后来出国了，运气更是越来越好。比如说褚老师吧，竟然在校园旁边的一个小馆子撞运气偶然碰上，后来一起吃香喝辣，无酒不成席，成了很好的朋友。我一直觉得，一个人的性格特色是很容易受他周围的朋友影响的。而我正好在上学的时候遇到了褚老师，吃喝玩乐之间，少花了多少2198啊 —— IPO时买了后来的蓝筹股，这不是运气好是什么？

虽然说运气不可能一直好下去，人生如赌局，有时也会有运气很糟糕的时候。可是金榜题名、洞房花烛、他乡故知几场大局都赢了，绝对算是难能可贵了吧？中学班主任大陈儿教导我们，「世上没有单纯的运气，机遇只偏爱有准备的头脑」，也许是我从小都在「时刻准备着」呢？

虽然没「创业」发过财，没走红当过领导，没戴过劳力士的手表，没玩儿过徕卡的相机，可从小第一批就戴上了红领巾，上中学第一批就玩儿上了苹果原装电脑，眼前有可爱的家人孩子，远方有难得一见的朋友，此般运数，夫复何求？

这不，今天一位从未见过的陌生人，到好久都没玩了的「在行一点」上 —— 这名字也太拗口了，还是叫分答吧 —— 把我小小地表扬了一下。这样的「机遇」，像是走在胡同里忽然飘来悠扬的琴声，令人心情大好，怎么「准备」的头脑都准备不来 —— 我们还是把他算在「运气好」的头上吧。

谢谢你。


---


# 没规矩

李老师，祝您青年节愉快。我也来私信求解惑了。是一个关于「原则」的问题。比如，最近和朋友玩游戏喝酒，喝一杯我就是喝一杯，倒满。朋友们喝着喝着就会倒少点儿，最后几乎成半杯了。褚老师引用过一句GQ的话，曾对我有所帮助，大意是「在一个俱乐部，两类人比较讨厌，一是没规矩的，二是太坚持规矩的」。所以想问下李老师怎么看。一，我是否应该坚持「满杯」。二，我是否应该坚持自己且不用在意别人的「鸡贼」做法。求指教。（问题来自微博私信）

一

你知道褚老师说的这个「GQ」杂志的名字是哪两个英文单词的缩写吗？

没错儿，是「Gentlemen’s Quarterly」——「男士季刊」。

可是「GQ」杂志其实不是季刊，也不是双月刊，而是一份月刊杂志。

这不是丢人吗？作为一份美国最有名的男性时尚杂志，连名字都在误导读者，还怎么取信于人？

你可能会说，这不是钻牛角尖儿吗？也许这个杂志创刊时是季刊，后来变成了月刊却没有改名，这似乎也没什么关系吧？

去研究GQ杂志的名字是否误导确实有点儿钻牛角尖儿。这就好像你第一次去和一个不认识的女生到一家正式的西餐厅约会，发现她竟然先拿那一把靠近盘子的叉子吃开胃沙拉，于是认真地给她介绍了一下西餐刀叉的摆放顺序一样。

大煞风景之余，还完全没有必要——用哪一把叉子吃沙拉，和GQ到底是不是季刊一样，是无足轻重的一个细节。

而你所谓的「原则」性问题，竟然是喝酒到底是半杯半杯还是满杯满杯喝的问题。

你所信任的GQ杂志还说过，力量训练之后不要喝酒，有氧训练之前也不要喝酒，前一天晚上喝酒还会影响后一天早上运动的成效。总的来说，喝酒无益于健康。

那你是否应该和朋友建议，咱俩要不然别喝酒了，改喝可乐？

等等，可乐也同样含有大量糖分和咖啡因，应该改成喝冰水。如果你朋友的健康不算原则性的问题，那什么是原则性的问题？

你的朋友这时一定会想：这人整个儿傻到家了啊，下次不能再和他喝酒了。

饭局不欢而散，这就是你在「原则」问题上钻牛角尖儿所希望得到的结果吗？

二

前一阵子我在法国开会，碰到了几位学术界的同行，聊到了我的新书《幸福》。我跟他们「宣传」这本书用到的一句名言是：如果搞科研是让你精神紧张的「毒药」，那我的这本书就是让你心情放松的「解药」。

而对于你这样完美主义到了钻牛角尖儿地步的人，我也有一份「解药」—— 美国青少年爱用的一个单词，叫「chill」。

「Chill」这个词儿还真不太容易翻译成中文。从发音来看，让我想起了小时候最爱的「清凉油」；从词义来看呢，又让我想起了一句北京话叫「哪儿凉快哪儿歇着去」。

与其试图翻译成中文，咱要不然还是继续假想那个跟一个未曾谋面的女生第一次约会的故事吧。

第一次约会去一家正式的西餐厅，这个选择本身就明摆着是「chill」的反义词儿——超级「un-chill」。

你想啊，吃完了这么贵的饭你如果说「我来我来」抢着买单，给她一种「欠了你」的心理暗示，她对你的印象能和「chill」沾上边儿嘛。

正确的约会地点是一家路边儿的小饭馆儿，一边儿喝着大扎的啤酒吃着新鲜出炉的烤串一边聊天，既可以半个钟头买单走人谁也不欠谁的，又可以「他乡遇故知」，海聊到馆子打烊。聊着聊着如果正好聊到了她特想去的一家网红甜品店，那不正好是下次一起「chill」的好去处嘛。

吃饭时既不能一句话不说各自玩儿手机，又不能吹上一晚上自己从前光荣的奋斗故事，因为这两者都一点儿也不「chill」。约会结束以后即使再喜欢她也要「chill」，别动不动就给她发微信，让人家觉得你平时无所事事，没有朋友，也无法自己独处。

没错儿，「chill」代表的是一种人生哲学。你越计较的事，越喜欢的人，就越有可能说出钻牛角尖然而却于事无补的昏话，做出南辕北辙的傻事儿来。「船到桥头自然直」，你越不在意，大家的心情就越愉快。

三

当然，如果不是第一次约会，聊天聊到了真正原则性的问题，你一定要就事论事，旗帜鲜明地表达自己的观点。

不过，在清晰地表达你的观点的同时，你还要说明「为什么」：你得出这个结论依据的是什么可靠的论据。

这就像中学时语文课写作文一样：议论文需要明确的论点和论据，逻辑清晰，「晓之以理」；而散文则「动之以情」，形散而神不散。

如果这位和你约会的女生还是固执己见，无法认同你的观点，那说不定你们将来也不太可能互为对方的「解药」，一起过日子也不一定能「幸福」。

最终分手的时候，你如果实在想要完美主义，还是可以找个机会善意地提醒她：西餐里的沙拉，应该是用左手最外面的那把叉子来吃。


---

# 短暂的快乐


李老师好！我本来是一个超级活泼开朗、无忧无虑的人。但是在经历了很多个突然长大的瞬间之后，我感觉现在的自己丧丧的，有种底色日渐悲凉的感觉，似乎快乐很难且很短暂。对于这种悲观，您有什么建议吗？（问题来自微博私信）

一

日子过得不开心，自然有很多可能的原因。甚至有的时候，亲人或者朋友无心说出的一句话，听了都会让人觉得生活索然无味，世界黯然失色。

但是既然你的问题这么笼统，有一种可能的原因，我打算单拎出来掰碎一点儿聊聊。

我觉得身边的很多人 —— 也包括我自己 —— 从小到大受到的教育，都有点儿过于「正能量」。比方说，我们要有崇高的理想，远大的抱负，从师要「青出于蓝而胜于蓝」，无论将来做什么工作，都要「干一行爱一行」，「三百六十行，行行出状元」。我们生怕自己变成了「伤仲永」中的那个「泯然众人矣」的天才少年，生怕「做一天和尚撞一天钟」。

等到我们为人父母的那一天，带孩子则更是如此：巴不得把自己未竟的理想和抱负，将来让孩子来替我们实现。我们「可怜天下父母心」，为孩子找最好的学校、上最好的特长班，同时永远在羡慕别人家的孩子：怎么教育的，这也太优秀了吧。

但是很多时候我们发现，从上学到上班，从谈个恋爱到结个婚，真实的世界其实极其残酷：工作不顺心，领导不待见，甚至谈个恋爱都谈不成。「待到理想化宏图」似乎永远没戏，只有时间，在一年一年没有悬念地慢慢流逝。

偏偏这时候，「头条」里充斥着各种「大牛」的成功经历，朋友圈里则永远是「哪壶不开提哪壶」—— 我这儿还没男朋友呢，闺蜜都结婚了；我这儿论文不断被拒，人家的论文永远榜上有名，搞不好还能得奖。就连机场的书店里，随处可见的都是马云、冯唐、李开复这样的「人生赢家」，令人相形见绌。

这大概就是你所说的「突然长大的瞬间」吧。

二

二十多年前我在清华上学的时候，同宿舍有一个室友，而且还恰巧睡在我的下铺，可以算是「睡在我下铺的兄弟」。

我发现我们班里的「神人」都有一个离奇的姓名 —— 我下铺的这位兄弟姓「银」，我们都管他叫「老银」。

老银虽然睡在我的下铺，但跟我完全不是一路人。我属于比较「追求上进」的同学 —— 每天晚上一定要去自习教室上自习，晚上十点准时下自习的那种。老银则是我的「镜面反射」：他从来不上自习，甚至不经常参加打牌或者踢球等一系列人民群众喜闻乐见的课外活动。

他的爱好时不时会变，但却永远别具一格。比如大二有一阵子，他喜欢修电视机。一位同学捡回来了一台没画儿了的黑白电视，他靠着一把老旧的电烙铁，愣是把这台电视给修好了。害的我十几年前买过的一台背投影的彩电后来颜色坏了，我第一反应竟然是自己打开后盖去修。

临近大学毕业时，班里的同学全体下馆子聚餐。像电影《致我们终将逝去的青春》或者《芳华》里的散伙饭场面一样，同学们频频举杯，依依惜别，男同学大多老泪纵横。据我观察，老银像没事儿人似的，冷眼旁观，不屑一顾。我的毕业纪念册上，「睡在我下铺的兄弟」没有留言。

我和老银明显不是「一条线上的蚂蚱」，毕业以后也就自然而然地失去了联系。每次老同学聚会时打探老银的消息，消息灵通人士寥寥。二十多年来，只是听说老银没怎么工作过，曾经迷过几年炒股，没有女朋友，后来辗转移民了加拿大。在加拿大也没怎么工作，据说这几年靠救济生活，白天喜欢在咖啡店闲着看看人来人往的风景，晚上则住在政府给无家可归者提供的住所（homeless shelter）。

据说有同学曾经问过老银，问他为什么不找个工作。他的回答是：为什么要工作？

一个清华的毕业生，在遥远的加拿大名副其实地「流落街头」，竟然过得还不错。有的人倡导「断舍离」，倡导「极简主义」，老银则把「极简主义」活到了极致，连个自己的家都给「断舍离」了。

心情「悲凉」的你一定会开心地发现，即使你将来「混」得再差，也比老银混得好些。

不过我一直觉得，老银像一位少林寺里扫地的和尚，武功卓绝，日子过得很牛逼。

三

前几天去香港，跟一位香港理工大学的教授朋友吃饭。酒过三巡聊起香港时局，朋友说这几天经常会觉得一个人就像大海中的一滴水，像沙漠里的一捧沙子，风暴来临之际，只有随波逐流的份儿。

其实不需要挂什么「十号风球」，即使是风平浪静，我们绝大多数人也不可能出人头地，在历史的长河中，充其量也只不过是一朵浪花罢了。

每天买个菜，做个饭，朋友圈里点几个赞，在咖啡店喝一杯咖啡，看着窗外行色匆匆的人们，「比上不足、比下有余」，不是也挺让人满足的么？

那年我竟然把家里那台背投影的彩电修好了，后来又看了好多年。


---


# 基层公务员

李老师好，有个非常纠结的选择需要咨询您。我刚毕业留京，到了很忙的基层当公务员，正在读在职博士。工作以后被离家远的漂泊感、北京的买房等生活压力压迫得忍无可忍，准备取消录用回家乡那边的省会新一线考公或者事业，或者等博士毕业进学校。可是父母反对，他们觉得省会生活压力也不小而且发展弱、考公竞争太大容易直接失业心态更不好。我自己是很不愿意继续在京基层公务员了，因为生活压力太大实在没有幸福感可言，可是父母的观点也很有道理的样子，所以导致我非常犹豫。您能帮忙指点一下么？

我是独生女也没有对象，自己离家太远这个漂泊感和生活压力太可怕了。而且放眼望去也觉得可改善性很小，本人不是喜欢打拼的性格，希望能过亲朋好友围绕的温馨生活，所以一度想冒险裸辞回去省会重新开始。但是又不确定自己考虑的对不对。

我最近几天也在反省自己。可能是刚出校园，独立应对生活的能力还不够，一个人没有援助力所以受不了压力了。而且因为我身处基层，单位平台低人员素质低，直接领导是个人品和作风很差的军转中年油腻男，天天被当成情绪垃圾桶和新兵蛋子挖坑欺负，工作特别忙还总受气，痛苦又没价值的工作，一个独生女远离家的孤独，还有未来的压力和恐惧。一来我就在各方面遇到加难题型，我真的都怕自己转正进入服务期走不掉就抑郁了。可是另一方面又觉得自己是不是在逃避压力，去了省会只是房价和家远的压力稍微缓解，还得面临可能短时间找不到满意工作的综合压力，找到了是不是又是另外一个坑。我真的挺纠结，又患得患失的。

这段时间思考去留的问题，让我精疲力竭十分痛苦，还请李老师指点一二。谢谢老师！（问题来自微博私信）

一

我们先来做一个假设：工作无论做什么，都会有其难处，世上不可能有十全十美的工作。

你不觉得吗——有的工作挣钱多但是太忙，有的虽然闲但是挣钱又太少；有的岗位受别人排挤，有的又责任重大，风险太高；有「痛苦又毫无价值」但是却四平八稳不容易丢的工作，就自然有挺有责任感但随时会失业的工作。

如果我们的假设成立，那你现在的工作虽然离完美有一段距离，可你将来回到省会城市重新找到的工作，很可能比现在也好不了多少。

如果不考虑工作好坏这个问题，那我们的这道选择题就简单多了：如果咱今后打算工作三十年，是住在北京呢，还是住在省会城市？

回答这个问题，我绝对不是一个合格的人选：我北京出生北京长大，肯定带有北京人的偏见。

我的答案是：我不但会选择住在北京，还会找机会到世界上其他的著名大城市都住上一阵子——比方说上海、香港、首尔、东京、纽约、还有伦敦。

也许正是因为我选择的是北京，将来才会有更多的机会去更多的地方。

二

我有一位教授同事，曾经成功创立过一家外汇交易的公司。因为这家公司创立至今发展得非常成功，他早已衣食无忧——按照现在时髦的词汇，叫「财务自由」了。特斯拉刚刚推出 Model S 的那一年，他就买了一辆来玩儿。他戴的智能手表是当年大名鼎鼎的 Pebble，论资历，苹果手表得管它叫「爷爷」。

一次闲聊时，这位同事说起他每个周末把自家的豪华特斯拉开出来，在Uber上接单。我觉得很神奇：他也不缺这点儿外快啊，为什么要临时开出租？

他说：就是为了好玩儿啊。

就跟他多年前买了点儿比特币，无论涨啊跌啊从来没卖过 —— 也是为了好玩儿。

工作二三十年，退休了还有二三十年，这么长的时间，我觉得「好玩儿」特别重要。

事业成功家庭和睦自然很重要，但「好玩儿」其实也是一种挺重要的体验，因为还有很多其他可以「玩儿」的。比如周末没事儿去开开出租，是一种「玩儿」法；在单位跟领导斗智斗勇，是一种「玩儿」法；认识一大帮子新朋友一起撸串喝酒侃大山，也是一种「玩儿」法。

而北京这样的大城市，玩儿法多半儿会比回到省会城市多一些。玩儿法一多，日子就变得更加有滋有味。

就像计算机科学里有一种叫「图灵测验」的概念一样，我一直笃信一种测验，我管它叫做「deathbed test」—— 这里的「deathbed」可以说是一个中性词，没有伤感的含义。虽然意思猜都猜出来了，还真没有对应的中文词。

这个测验是在问，临终前对自己玩儿过的这几十年，是像酒足饭饱的那种心满意足的感觉，还是后悔莫及？

我想，如果既跟领导缠斗过，又跟朋友快活过；既开过出租、又当过房奴；玩儿过文艺，弹过吉他，又飙过跑车，到「deathbed test」的那一刻，就不太容易后悔了吧？

否则，如果换了我，我总是会好奇：如果当年选择留在北京住下去，后来会是什么样？

三

当然了，「萝卜白菜，各有所爱」，很多人就跟我截然不同，更喜欢小一些的城镇。这就好像既有喜欢儿孙满堂、也有喜欢丁克的人一样。

我今天读到了一则在环球邮报网站上的留言，说一个加拿大人自己一个人住在阿尔伯塔省的一个小镇附近自己的农场里，离他最近的一户人家在一公里开外，每天只有一条狗陪伴着他。他只需每一两周到小镇上买一点儿水果，其他的吃的喝的农场里都有大量储备。他每天上网逛逛，在家做做木工，日子过得也挺充实。最近的世事纷争和他没什么关系，唯一的影响是小镇上给他安排的义工取消了。

也许是因为我当年是个城里长大的孩子 —— 就算把这个农场送给我，木工玩儿腻了的时候，我也注定会感到孤单。

如果真有世界末日的那一天，我想我会去上海徐家汇或者纽约曼哈顿找一家小酒吧，安静地等待它的到来。


---

# 酒店管理

葆春老师您好，我是一个不知名大学的本科的文科生。我父母文化不高，高考填志愿时不会帮我选专业，结果调剂到了我不喜欢的文科专业——酒店管理。

我挺羡慕理科生的。理科生可以自然而然地毕业后从事自己专业的工作。

我一直都是个没有目标的人。我好像从未对什么提起过很大兴趣，我也不是个勤奋努力的人。

今年就要毕业了。我想去上海，但我不知道自己到底可以做什么。我想过考研，但也没有明确的考研目标，我真的很迷茫。

我很后悔自己以前的选择，这两年来都沉浸在痛苦中，非常希望葆春老师能指点一二，谢谢葆春老师，盼复。（问题来自微博私信）

——

我以前在引用一个打算回答的问题时，问题中所用的语言和标点符号，一般都会粗略地修改一遍。比如有的人喜欢用很多逗号，经常一句话特别长。我会把问题中的一部分逗号改成句号，再多分几个自然段，让问题更加清晰易读。

看了你的问题，我发现无论是语言还是标点，通篇竟然没有一处需要修改。我喜欢你的问题中每个自然段里第一句话不用逗号，而是直接用句号结束。这样表达更加简洁明了，颇有古人「环滁皆山也。」的开门见山，我一看到就挺有好感的。可以说，我喜欢你这个「不知名大学本科的文科生」的文风。

那咱们就步入正题吧。

一

我小的时候有一种说法，叫「学好数理化，走边天下都不怕」。高中时，很多学习成绩不错的同学都对理工科趋之若鹜。大家高考考的都是「理工农医类」的考卷，班里学习最好的同学报的是北大生物系，而前几名的同学也清一色地都报了理工科。我上大学的时候，清华还是一所以工科为主的大学，我学的虽然是计算机，但学过金工实习，学过机械制图，感觉毕业了随时可以分配到大中型企业当一名工程师。

然而不知你发现没有，国外很多大学的惯例是将文科和理科归入同一个学院，工科则归入另外一个学院。与其分为「理工科」和「文科」，不如分为「文理科」和「工科」更为贴切。加州大学伯克利分校更加别出心裁，把文理学院叫做「College of Letters and Science」，一个学院涵盖了从文学到音乐到历史到经济到生物的方方面面，涉猎之广，令人目不暇接。

所以可以这么说，文科——也就是伯克利的「Letters」——至少和理科是可以相提并论、分庭抗礼的。那这个「Letters」到底毕业后有没有用、是不是白学了呢？

我很晚才领悟到，其实这个「Letters」说不定比金工实习机械制图比当年热门的金融和生物 —— 甚至比从二十多年前到现在一直热门的计算机 —— 都更加有用。

原因很简单：跟金工实习或者计算机都不同，文科学的很多东西，属于「看不见摸不着」的技能。正是这种飘忽不定的感觉，让很多人觉得时间白白浪费全都白学了，毕业了也不知道要干什么好。可如果从长远来看，也正是这种「看不见摸不着」的技能，才能真正左右一个人长期的职业发展。

我喜爱的电影「Jerry Maguire」和「Chicago」中的女主角Renée Zellweger，刚上大学时学的是英语文学（English Literature）。上了一阵子她开始选修戏剧表演方面的课程，后来毕业后参演了一些小成本制作的电影。共和党著名参议员Mitt Romney在去哈佛大学学法律之前，本科学的也是英语文学。

那他们的英语文学是不是白学了呢？从「看不见摸不着」的角度来看，我觉得非但没有白学，还造就了他们后来的事业。如果他们本科时学的是工科，那说不定现在也只不过是在一家大公司的研发部门供职，而不会成为好莱坞星光大道中的一员，不会成为政坛的一代枭雄了。

乔布斯零六年在斯坦福的演讲中说：「You can’t connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.」

英语文学也好，酒店管理也罢，或许越是没什么用的文科，就越没有白学。

二

所以说，学什么专业干什么工作是「有用」的，还真的不好说。

1873年，美国纽约有一个二十出头的小伙子，叫 Frank W. Woolsworth。一天，他衣衫褴褛地去应聘一家商店的营业员职位。老板跟他聊了一会儿，对他说：“行了，你下周一来上班吧。” 他非常开心，连忙问：“那我能拿多少工资？” 老板大叫道：“工资？你还想拿工资？我教你怎么做生意，你应该反过来给我发工资！”

那时候美国的劳动法还没有最低工资保护有关的条款，Frank 得以顺利得到了这个头三个月不拿工资的工作。头几年他确实很辛苦，每天只能打扫卫生，早上七点干到晚上九点，大家都瞧不起他。后来，他逐渐开始揣摩商品摆放位置和定价的门道，终于投资了几百美金，跟几个合伙人成立了一家以自己名字命名的「初创」公司，开了自己的第一家商店。他的生意越做越大，连锁店开始遍布全美，继而又遍布全世界。1913年，他的公司在纽约曼哈顿建成了当时全世界最高的摩天大厦。

试想，如果当年的 Frank 看不上这个既不发工资又要打扫卫生的工作，大概就悟不出来后来得以大获全胜但却转瞬即逝的商机了。公司成功之后，他果然很感激当年的老板给了他这个不拿工资的工作，还请这位老板到他自己的公司来当合伙人，「反过来」给他发了工资。

这样「励志鸡汤」的例子自然俯拾皆是。年逾九十的斯坦福大学著名经济学家 Thomas Sowell 在他的著作 《Applied Economics》中认为，无论是上学、看书还是工作，都是一个获取新的知识和掌握新的技能的过程。像在给自己「投资」一样，是一个积累「human capital」的过程。Sowell 提到：

「The growing importance of human capital tends to create greater incoming inequality between those people who have been assiduous in acquiring knowledge and mastering skills and those who have not. It tends to create greater inequality between those who work and those who do not.」

他的意思是，只要学点儿什么干点儿什么，永远比什么也不学什么也不干天天打「王者荣耀」强很多。

如果你还是觉得自己的学业和工作一时半会儿没有什么用处，那就想想Frank Woolsworth —— 他当年「初创」了公司，结果开的第一家商店很快就倒闭了。

放心吧，只要多运动增强免疫力，人一辈子有的是时间。

三

当然了，要想「学点儿什么干点儿什么」将来有用，你学的东西一定不能是别人强加给你的，得是自己感兴趣的。如果是别人强加的，换了谁都很难做到长期「勤奋努力」—— 你瞧，连李开复都明白要「追随你的心」。

如果你想来想去，除了打「王者荣耀」和看「乘风破浪的姐姐」，怎么也想不出还对其他什么东西感兴趣，那怎么办？

我建议，竭尽心力，自己设计制作一样需要一两个月时间才能做好的玩意儿。

一两个月时间不算太长，但也不太可能一蹴而就。

你提到正在考虑读研的可能性。读研的过程虽然千差万别，但是都有一个共同的特点：要毕业就得写几篇论文。

虽然写出来的论文本身多半儿没什么用处，然而一篇论文就像一座雕塑，每一笔每一划都是自己设计制作出来的，都是自己的呕心沥血之作。在这个过程之中得到的「看不见摸不着」的技能，意义远远超过论文本身。

如果你对写论文不感兴趣，那就拍一部微电影，上线一家淘宝店，写一本书，开一个线上直播，修好一辆没人要的旧车，或者实现一个网站。

注意，去云南大理旅行或者种一株玫瑰送给男朋友不能算 —— 花点儿钱或者浇点儿水就行，太简单了。

比如我这两个月，就竭尽心力，从头学起，花了所有的业余时间和所有周末，实现了一个全新的网站。

其实这跟跑马拉松差不多 —— 虽然没什么用，过程也很艰苦，但大功告成之后，我看着网站背后的每一行代码，感觉每一个字节都在我的指挥下跳动，觉得非常过瘾，感到了一种「更上一层楼」般的快乐。


---

# 电子诈骗


李葆春老师中午好。在电子诈骗中被骗的人，无论是出于贪还是侥幸的心理，您对这样的人、对被骗这种事怎么看？

撇开不讨论电子诈骗以及其他金钱骗局的低端、低技术含量和明显的诈骗性，也不谈普通人要有防诈骗的警惕心、不要明知故犯或贪心、要培养脚踏实地的性格或者政府应该积极打击诈骗犯，只谈那些不幸被骗的人，是不是被骗本身说明这类人确实人生的路会更难？

一辈子有可能不被骗吗？被骗过后会不再上当吗？人生又是否又会有重来的机会呢？为什么人性这么脆弱？（问题来自微博私信）

一

七年前有一个夏天，我正好在西安出差，准备在当当网上邮购一些书带回加拿大。我用我当时的手机号码注册了一个账号，选好了几本书，就下单了。虽然那时我没怎么在国内网站上买过东西 —— 即使到现在我都没有淘宝的账号 —— 但我一直听说国内的电商极其发达，只需要一两天时间，书就可以轻松地快递上门。

第二天，我接到当当网的客服打来的电话。客服首先跟我核对了一遍我的订单号、名字和快递收货的地址，然后客气地说：「李先生，不好意思，您的快递暂时缺货，需要先给您操作退款，等有货了再给您重新下单。」

我回答：「行，那你就先退款吧。」

「先生，您有没有QQ？」

「对不起，我没有QQ。你要QQ干嘛？」

「哦，是这样的先生，咱们这里查到您是用网银支付的，操作退款需要把钱原路退回给您的银行账号，需要您提供一些信息，所以必须用QQ联系您。」

「我确实没有QQ。你要什么信息？」

「那实在不行要不然这样：我这里有个网站，给您短信发过去了，您登录填写一下您的信息，填好了告诉我，我在线等您。」

网站我一下就打开了，里面提示我填写银行账号、收款人和密码。

后来我回想起来，真的是有点儿悬。直到打开这个网站之前，我还没有意识到这其实是个骗局。主要原因是对方刚开始就报出了我的订单号、收件人姓名和详细地址，骗取了我的信任。但是这个骗局的设计稍微有些粗线条，有两个明显的破绽：第一是对方带有南方口音的普通话，第二是让我填写账号密码。

对了，还有他后来愈发焦急的催促：「您填好了没有？填好了没有？」

电信诈骗之所以这么多年来一直没有杜绝，非常符合经济学的原理。由于作案风险相对比较低，获利又相对比较高，就会有更多的人投入其中，组织和分工也会越来越精准严密。再加上其套路层出不穷，年年都可以推陈出新，令人防不胜防。

所以我对在电信诈骗案中被骗的人非常同情 —— 我自己研究了半辈子计算机，也没有什么贪小便宜的心理，又历来小心谨慎，当年都照样差点儿上当。

二

那将来会不会再次上当受骗呢？

这得看你这个「受骗」如何定义了。

如果只是电信诈骗中的骗局，我想大多数人多半儿可以「吃一堑长一智」，不接陌生人的电话，基本可以对这种骗局「免疫」。

但如果你把什么「P2P理财」啊、「币圈儿」啊、「直销」啊、「万能保险」啊、「投行权威分析」啊什么的全都算上，那很可能你今后还会再「受骗」，而且还不止一次。

这是因为在如今的信息时代，每天主动读到和被动接受的信息和观点实在太多，哪些是正确的，哪些是错误的，哪些是事实真相，哪些则是以假乱真的宣传，不太可能有一种万灵的方法，可以保证自己的判断每次都准确无误。

不过你大可放心，这样的「受骗」就如同一家企业在市场中的亏损一样，并不一定是一件坏事儿。盈利是一种市场信号，亏损也是一种信号。和盈利比起来，亏损甚至可以让一家企业更有效地重新优化整合自己的资源配置和产品策略，积累更宝贵的经验。

一个人更是如此：赚钱的时候春风得意，而一旦因为判断失误听信了别人的「权威分析」上了当亏了钱，「痛定思痛」，总结出来的经验只会更加宝贵。

所以说啊，人生完全不用「重新开始」，以后的好日子还长着呢。

三

不过道理虽然这么说，要是换做是我，总还是会希望尽量多「盈利」少「亏损」，少总结宝贵的失败经验，心情会好很多。

我有三条「锦囊妙计」，说不定可以派上用场。

第一条是尽量不要人云亦云，盲目「跟风」。比如，如果大家都去买比特币或某种高回报的理财产品，你则要冷静下来持怀疑态度，问一个关键的问题：买房也好，比特币也好，P2P理财也好，这种投资为什么可以盈利？风险多大？风险从何而来？如果经过冷静的独立思考，觉得对这些问题的回答逻辑严密、符合常理，再去跟风不迟。

第二条是多考虑长期的影响，少考虑短期的效益。经济学家 Thomas Sowell 管只看短期效益的短视行为叫做「Stage One Thinking」。Sowell 指出，很多决策的制订都仅仅看到了短期的好处，没有考虑长远的负面影响。比如，如果有这么一种理财产品，头一年的回报百分之十，但长期来看没有保证，我们就一定要估算一下其长期的风险，连为其担保的公司倒闭的风险也要计算在内。

最后一条是尽量避免「冲动消费」。商场或网站大减价的或者「直播带货」的产品，都属于别人给你推销的产品。这些绝大多数都不是你需要的产品，很可能完全不适合你。但是你因为一时兴起，说不定就下单买下了。买了以后没怎么用，就造成了有限资源的浪费。而「好酒不怕巷子深」，质量上乘、做工精细的产品，你排队抢购都不一定抢得到，不会天天大减价推销给你。

比如说吧，如果我现在告诉你，我准备近期隆重推出一个名为「好酒不怕巷子深」的私人朋友圈，为期四周，每周两小时。届时将汇集我的三位老朋友作为嘉宾，有你早已耳熟能详的「大V」，有学识渊博的学者，还有神龙见首不见尾的高人，没有什么主题，大家根据共同关心的话题，全程语音互动，想聊哪儿就聊哪儿。由于平台资源限制，名额有限，优惠价格在评论里找，请大家尽快报名。

你可千万不要参加。


---


# 人生建议

Pavel Durov 最近三十六岁生日，在他自己创立的 Telegram 发表了一篇文章，聊了几条如何「永葆青春」的建议。

这种「人生指南」式的文章，大多数不值得看。但Pavel Durov则不同，虽然没什么人听说过他，我却是他的狂热粉丝。

粉到什么程度呢？我看过一点儿Telegram for iOS 的源代码，源代码竟然写得像一篇小说，精彩纷呈，令人拍案叫绝。

我还喜爱他的低调——这一点比马斯克强得多。越是没什么人听说过，越显得他非同寻常。

关于如何保持年轻，他的七条建议是：

一、不喝酒。这是唯一一条他强调了两遍的建议。

二、多睡觉。

三、不要吃得太多。Durov自己一天在六小时内吃两顿饭，或者只吃一顿饭。一天吃三顿饭他认为是一个坏习惯。

四、多运动。他喜欢在室外骑车游泳，或者做中度力量训练。

五、减少精神压力。什么事儿都往好的地方想。

六、不要吃肉。可以吃海鲜、吃鱼。

七、独自居住。

其实我觉得，这几条建议中，我们普通人只要能做到少吃、每天运动一小时、多睡觉，就已经非常不容易了。我现在做到了每天只吃早餐和午餐，傍晚跑步或者力量训练，周末去长途骑车，睡觉前不玩手机。要是能再多睡点儿就更好了。



---

# 王思聪


王思聪和孙一宁的故事，开始只不过就是一个有钱人爱上了一个美丽的女生追了半天最后满盘皆输的故事。故事虽然很平常，但还是可以复盘看看他到底输在了哪里。

我觉得，王思聪没学过计算机科学，一定不懂什么是「面向对象」的程序设计。「面向对象」虽然有点儿复杂，但大意是说每一个「对象」都有公有和私有两种变量，公有变量外界可以随意访问，而私有变量则「仅自己可见」。

比如说吧，如果你跟一个心仪的女生聊起密室逃脱或者肖战，多半儿她会很自然地跟你聊聊自己的看法；但你如果跟王思聪学习，去问人家「你现在在哪儿呢」「你约了谁啊」，那人家不但不一定有心情告诉你，反而会自然而然地产生反感的情绪，也许本来还有的一点儿好感也烟消云散了。

所以老话里「谈对象」这个词儿挺中肯的：无论你的「对象」跟你熟到什么程度，人家都有自己的「私有变量」。

当然了，王思聪可能确实有点儿陷入了单相思，竟然做出了一个极其错误的决定 —— 临时去杭州找我们的女主。去就去了呗，可以说去办别的事儿顺便看看她，可以在杭州先逍遥几天，慢慢再约不迟。可我们的男主急得像热锅上的蚂蚁，一定要当晚跟我们的女主见上一面，这就不是恋爱，而是要挟了。

人的本能都是要保护自己的，我们的女主自然是这方面的专家，决定立刻提出跟男主「做朋友」。所谓「做朋友」，就是把所有的公有变量全部转为私有，将来坚决不打算做朋友了。事已至此，便是华佗再世，也回天无力，后面死缠烂打的剧情，就毋需再看了。

四十年前，王朔在他的代表作《一半是火焰，一半是海水》里「海水」的那一半里，一个叫胡亦的女孩就跟书里的男主说过：

「你这人怎么这样无礼 —— 我们不过是萍水相逢，一块玩了几天，我又没花过你一分钱，从始至终就是旅伴关系。别说没有什么，就是真有过什么，我想走你也管不着！难道你碰到对你热情一点的女孩子，就都以为她们一门心思要嫁你？」

朔爷门儿清啊


---


#  元宇宙


李老师，最近「元宇宙」这个概念特别火，有人说人类即将进入一个新世界，《黑客帝国》将成为现实，有人说这只是一场雷声大雨点小的骗局。您怎么看「元宇宙」这个概念以及各大科技公司对它的重视？（问题来自微博私信）

一

「元宇宙」确实有点儿忽悠。

不过不是因为它太玄乎太科幻，而是因为它早就已经差不多实现了——只是为了宣传给戴了一顶冠冕堂皇的帽子而已。

你经常玩儿的各种在虚拟世界中游荡的游戏——比如原神——其实就是「元宇宙」。

前一阵子股票大涨的Roblox，当然也是「元宇宙」。

在微软的飞行模拟游戏中，你可以单独在晴空万里的清晨中起飞，也可以在电闪雷鸣的夜晚中降落；在经典游戏「The Sims」中，你可以和朋友火热开聊，尽情party——这些也都是「元宇宙」。

如同斯皮尔伯格的电影「Ready Player One」中一样，在这样的「元宇宙」里，你可以以任何自己最钟爱的装扮出现，可以变成一辆自己心仪的跑车或者二战时的飞机，甚至可以在孤岛上建一座古城堡，在塔尖眺望远处的灯塔。

在这样的「元宇宙」里，你可以尽情地爱上一个人，像「Ready Player One」那样爱上她的迷彩装扮，像电影「Her」里那样迷恋她略带磁性的声音，你们可以一起购物，一起游览世界。

注意，我说的「元宇宙」和Facebook或者Meta的那个南辕北辙，大相迳庭。我的「元宇宙」里没有工作，只有玩儿；不需要什么高级眼镜，只需要一台普通的电脑；没有漂浮在半空中的上半身假人，只有各式装扮的各色人等在争奇斗艳，觥筹交错，人声鼎沸。

我想我会爱上这样完美的「元宇宙」，无以自拔。

二

虽然说「元宇宙」已经差不多实现了，但其实从计算机技术上来说，离真正实现还有一段距离。

最难实现的其实跟虚拟现实没什么关系，而是一个既可以大家一起上线，又可以超低延迟的计算机网络。

其实计算机技术发展到了今天，保证大家一起上线并不太难，保证低延迟也不是很难，可难就难在两个要求需要同时满足。

比如直播技术可以几百万人一起上线，但是从现场大喊「新年快乐」到大家听到，大概需要十几秒到几十秒的延迟。

如果换成了Zoom这样的实时在线会议，延迟可以保证只有一两百毫秒，但是只能最多一两千人同时在线。

你一定会问，现在不是有了5G网络，可以支持超低延迟了吗？

其实这个问题远远没有你想象的这么简单。计算机网络就像一个错综复杂的公路系统，有省道、国道，还有纵横交错的高速公路。数据包每走一段就会遇到一个路由器，就像汽车路过高速上的收费站，如果路上没什么车还好，否则需要排队等候——车越多就越拥堵，数据包的延迟就越长。

而5G网络的低延迟，只不过让你早点儿开出小区上路而已。

可以说，如果将来「元宇宙」最终没火起来，多半儿是因为你的虚拟现实因为上线的人太多，堵在了高速上。

三

我有个学生叫王菲。

我一直认为，王菲同学的这个名字起得水平实在太高了，简直是神来之笔——不但中文名极其好记，而且英文「Fei」一样简单易读，毫无歧义，其背后的故事则是不熟的人初次见面自然而然的「ice breaker」。

王菲同学有一句特有哲理的口头禅：「想多了。」

是啊，与其天天琢磨「元宇宙」什么的，不如痛快地踢一场球，坐一回过山车，跳一次伞，喝一顿酒，吃一顿铜锅涮羊肉，再谈一场一辈子无以忘怀的恋爱。

就像Ernest Cline的小说「Ready Player One」最后写的：「我们坐在那里，手握着手，沉浸在那种奇妙的快乐中。」