---
title: Record number of nations to participate in Sea Breeze 2021
author: UKRINFORM
date: '2021-07-16'
slug: '248'
categories:
  - Translation Articles
tags:
  - Politics
---

[Source](https://www.ukrinform.net/rubric-defense/3268564-record-number-of-nations-to-participate-in-sea-breeze-2021-exercise.html)

>不出意外果然有波罗的海三国、乌克兰和格鲁吉亚。当然，我非常看好这5个国家的经济。

The U.S. Embassy in Ukraine posted this on Twitter.

"U.S. Sixth Fleet formally announces participation in the co-hosted Ukrainian-US annually held exercise Sea Breeze 2021 starting next week in the Black Sea region," the report reads.

The embassy noted that the Sea Breeze exercise was designed to enhance interoperability and strengthen maritime security and peace within the region.

This year’s iteration involves the largest number of participating nations in the exercise’s history, including 32 countries from six continents, 5,000 troops, 32 ships, 40 aircraft, and 18 special operation and dive teams.

The exercise is taking place from June 28 to July 10 in the Black Sea region and will focus on multiple warfare areas including amphibious warfare, land maneuver warfare, diving operations, maritime interdiction operations, air defense, special operations integration, anti-submarine warfare, and search and rescue operations. 

Ukraine and U.S. are cohosting the exercise in the Black Sea with participation and support coming from 32 countries in total: Albania, Australia, Brazil, Bulgaria, Canada, Denmark, Egypt, Estonia, France, Georgia, Greece, Israel, Italy, Japan, Latvia, Lithuania, Moldova, Morocco, Norway, Pakistan, Poland, Romania, Senegal, Spain, South Korea, Sweden, Tunisia, Turkey, Ukraine, United Arab Emirates, United Kingdom, and the United States.

Black Sea nations, in concert with NATO Allies and partners, improve their ability to conduct the full range of naval and land operations by participating in exercises like Sea Breeze 2021.

Sea Breeze 2021 is an annual multinational maritime exercise, involving sea, land, and air components, and is co-hosted by the United States and Ukraine to enhance interoperability and capability among participating forces in the Black Sea region.

