---
title: 微言（20）
author: Guanghua Mao
date: '2022-01-15'
slug: '368'
categories:
  - Original Articles
tags:
  - Insights
---

1. 劳动力跟任何单一资源一样，不跟其他市场要素结合，并不一定能创造什么价值。

比如1979年之前，按道理中国也有丰富的劳动力资源，也有“人口红利”，但为什么那时候的人那么穷，认为人口是最大的负担，需要通过计划生育来调节？这就是因为劳动力无法与其他市场要素结合。
1979年以后，中国逐步加入全球产业分工，与资金、各国对工业品的需求、以及成熟的技术与生产组织方式结合，就爆发出了惊人的增长，人口这才成了“红利”而不是负担。
真正的红利，是资源有效配置带来的分工细化与效率提升。
我不认为人均GDP10000美元的中国劳动生产率的提升到了尽头，“红利”还有很大的提升空间，只要坚持市场化配置资源。

2. “文化底蕴”是一个很玄虚的东西。你说它有，也很难证实它的存在；你说它没有，也很难否定它的存在。
我们换一年角度，宋元以来，江南四省科举就很盛，用现在的话说就是高考成绩很好。你可以说江南四省“文化底蕴”很厚，但实际可分析的是，在蒸汽机发明以前，船是人类的主要交通工具，江南四省有中国最好的内河航运条件，交通发达，带来的是效率提升，分工细化，所以江南人士有足够的资源供子女脱产读书，所以高考成绩肯定会好于没条件读书的省份。读书中举做官的人多了，也会有传帮带效果，这大概也可以解释为“文化底蕴”吧，但最重要的最确定的，还是前面说的：经济。
作为反例，江南四省中的安徽、江西，在铁路替代水路之后，被铁路干线甩开，经济文化地位就一落千丈。


3. 科技进步和社会分工共同推动了人类社会进步

4. 站在人类历史的眼光来看，语言的发明是人类实现从0到1的最重要的技术突破。
文字的发明，则是从1到10的技术突破。
现代科技，只是从10到100的技术突破。


5. 为什么社会分工细化就会强化契约精神？因为社会分工需要协作和交易，协作和交易需要信用，这是契约精神的基础。交易越发达，契约精神也就会越好。


6. 对于大部分人来说，可以看得见的意义是，参与社会分工，获得报酬（工资），换取生存资源。 但是它还有更隐性的功能，就是提供一个社会角色和生活秩序，让人免于无聊寂寞。 后面这个功能可能被人低估了。


7. 通货膨胀是怎么发生的呢？
如果生产端的供给满足不了消费端的需求，那么通货膨胀就有可能发生。
现在生产端和供应端都发生了很大的变化。对日本而言，简单概括就是“高效率，低增长”。
因为工业技术的进步，全球分工的形成，现在生活必需品的生产能力已经充足到严重过剩的程度，除非一些特殊的安排（比如日本对农产品的关税政策），不然任何生活物资短缺都会被全球供应链短时间抹平。所以由生产端产生的短缺很难长期存在。
在需求端方面，因为经济基本不增长，工资基本不涨，居民在生活必需品上的消费不容易有增量，所以消费品价格也涨不上去。
回到一个老问题上来，物价上涨可能会让人不适，但是，如果长期不涨，会让人更加不适，通缩会造成百业萧条，所以温和通胀一向是央行的工作目标，包括日本央行。但如果经济增长速度下来，央行再努力也不一定能实现这个目标。


8. 对于大多数国家来说，进出口是参与全球化社会分工的方式。
社会分工的好处是，取人之长，避已之短，发挥专业性优势，把事情做到极致，提高效率。这个跟人与人之间的分工是一样的。
现在大部分人不种粮食，不织布，不养鸡，他们只是从事复杂社会分工中的一个很细分环节，他们从事自己的分工获得收入可以理解为“出口”，他们用获得的收入购买别人的产品与服务可以理解为“进口”，进口与出口可能顺差，也可能逆差，但大体是均衡的，这样每个参与社会分工的人，都获得了比自己种粮、织布、养鸡高得多的生活水平。



9. 毕业有机会去公募基金公司做投研工作，那是非常不错的工作了。
当然，也仅仅是工作而已。
事实上基金公司的大部分工作，哪怕是投研岗，跟投资的关系也不是那么强，只是投资中的一个分工而已，对它不应该有那么高的期望，工资奖金可以，就是很好的工作了。
最后还是问你自己想要什么。


10. “工作可以把一个人从三大罪恶中拯救出来：厌倦、堕落、贫穷。” 送给所有想辞职炒股的人。我加句备注：最容易陷入这三大罪恶的，就是那些厌倦工作的人

11. 我再展开一下，为什么这些企业会常态化加班。 这些企业在市场上赖以生存的，是对用户需求反应的敏捷程度，而实现对一个需求的敏捷反应，通常需要工作有连续性，这并不是分工可以解决的

12. 人心很古指的是人性，主要由基因决定，和古时候没什么变化。世风日上指的是由科技进步，制度创新及分工合作深化扩大导致的经济社会发展，文明进步。没有矛盾。

13. 价值是减少交易成本，促进社会分工，提高生产力。


14. 分工可以极大提升生产效率。大家各自生产自己最擅长的东西，然后互换，比自己生产所有需要的东西效率高很多。
但是不一定所有我们需要的东西都能换到，所以市场越发达的地区，能换到的东西就越多，人们就可以把更高比例的时间用于生产自己擅长的东西，社会的平均生产力就越高。反之，市场不发达时，我们不得不去做很多我们不擅长的生产，效率低下。
只要进一步分工能进一步提升生产效率，人们就会不断追求把更高比例的时间投入更细分的领域，以提升生产效率。而为了使这种分工可行，就必须要更大规模的市场来满足人们的交易需求，所以全球化难以扭转的趋势。

15. 全球化的基础是：
1，市场经济是通过分工协作完成的。
2，交通、通讯条件的改善，使协作可以在全球范围内展开。
未来的全球化会进一步深化，使尽可能多的生产要素可以在全球范围内流动。比如中国经常提的人民币国际化，就是使资金可以在全球范围内流动。移民的常态化，使劳动力可以在全球范围内流动。


16. 1，人类历史上出现过多次“反科技”的行为，比如马车夫抵制火车，比如纤夫抵制轮船。
2，但这种反对是错的。科技进步提升效率，会细化社会分工，创造出无数新的产品和服务，改善人类的生活，也创造无数新的就业机会。
我举一个简单的例子来说，人类历史上大部分时间都吃不饱，大部分劳动力都投放在粮食种植业。现在美国只有不到1%的人从事粮食种植，美国人不但没有饿死还大量出口粮食，美国人也没有大规模失业。


17. 首先，我并不是“无政府主义者”，你把这样可怕的帽子扣在我头上，是很不厚道的。
人类能成为地球上的主宰，主要就是因为人类社会的分工系统比其他所有动物都要细致复杂。
分工协作需要善意、信任，凡是有利于协作的行为，会被多数人认为是“对”的，一直受到持续的激励；而破坏善意、信任的行为，会被多数人认为是“错”的，会受到惩罚，轻则舆论谴责，重则剥夺生命。你说的比如一个人为自己利益出卖部落的利益，他可以认为这是“对”的，也有人认为这是“错”的，这不重要，重要的是，他大概率会受到惩罚。人类社会法律的基本条款：杀人者偿命、偷盗者赔偿，就是基于这样的理念产生的。
分工协作，也意味着要把一部分权力，让渡给特定的组织，比如用暴力执行法律，这是政府的起源。


18. 你请一个咨询公司，付上几百万费用；或者花上几十万，上个EMBA，都很容易将这些引进来。不过不要迷信这些“经验”，经验的价值都是很有限的。管理无非是就是目标（虚实结合、远中近）、分工（适合每个业务阶段的队伍）、激励（精神加物质）。


19. 现代社会分工细化，通常人并不需要做所有的事情，比如科研工作者没有必要自己直接去“从商”。如果科研成果有商业价值，自然会有人来找你合作，把“商”那个环节补上。


20. 回复@即溶咖啡粉: 我的看法，无论是古圣还是今贤，都很有可能胡说八道，不要无保留地相信任何一个人。//@即溶咖啡粉:回复@不明真相的群众:这是理想状态 事实上信息费用太高 这也是社会分工的意义所在 比如我生病了 因为“主任医师”这个身份 我愿意相信他说的话 而不是自己去查一大堆资料 什么都自己判断 精力不够的 得有“捷径”


21. 这不是教科书的问题，是古人的认知能力问题。
我们设想一下，如果“罗绮”只能“养蚕人”穿，那么养蚕人的食物又从哪里来？是不是也是他自己种才公平合理？那样的话，社会分工根本不可能支持养蚕、织绸这种“没有实际作用”的奢侈产品和服务，所有人都光着屁股上树摘果子。
那是不是大家理想中的公平社会？//@看脚下:回复@不明真相的群众:你这是独立思考的结果吗？我小时候几天深信这些教科书的东西，导致青少年时期进入了自我矛盾和全面否定的阶段


22. 中国有句古诗“遍身罗绮者，不是养蚕人”。
富人消费丝绸，最后财富都转移给养蚕的、织绸的、卖绸的、缝衣的人那里去了，即便他们没有“遍身罗绮”，但比没有就业要好多了，或者，他们穿上绸缎的概率大大提升了。
如果富人把银子挖个坑埋起来，那就没有办法财富转移，会制造通货紧缩。
所以这句古诗创作者是它来控诉社会不公，在我看它，它却是社会分工财富转移的很好解释。//@天行健地乾坤:回复@不明真相的群众:富人买了奢侈品 财富怎么转给穷人了？ 方丈可以指教一下？


23. 新生孩子的时候，工作量超过人的承受能力，忙乱，很正常。比较好的办法是通过增加人力资源供应、细化分工来缓解困难。如果这个人力资源供应是付费购买的，更好。


24. 实际上，钱在周转运动中是产生了磨损的。
比如，你把10000块钱从工商银行转到招商银行，看起来你的钱没有产生磨损，但实际上，记账的过程，产生了系统的记账成本，但是这个成本微乎其微，银行帮你补贴了。
但是，在这之前很短的时间，跨行、跨地域转账也是要收费的，比如你在香港或者美国跨行转账，银行可能就要收你一笔钱，一般来说几十块钱。
在货币电子化之前，如果要把你的10000块钱转存到招商银行，需要柜员从金库里把钱拿出来，让武装押运车辆送到招商银行，那收费几十块钱就根本不够了。
在货币纸币化之前，你要把值10000块钱的黄金或者白银，从工商银行转存到招商银行，那么，需要用夹剪从工商银行的一大块金子里剪下一小块来，再派镖行押运到招商银行，你的10000块，扣除运转成本，剩8000块算不错了。
所以，钱的流转也是要损耗的，但是，因为技术进步（从贵金属到标准化硬币到纸币到电子记账），社会分工细化，这个周转成本持续下降到接近于零。

25. 这个问题，我也没有答案。
我记得早年欧洲殖民者刚到美洲的时候，需要劳动力。理论上来说，当地有现成的劳动力，就是土著居民印第安人，但是实验以后发现，当地土著不但接受劳动分工的意愿很弱，而且劳动还很容易把他们折磨致死。所以欧洲殖民者改成到非洲去引进黑人，黑人的耐劳性比印第安人要好，但是殖民者也还是承认，即便最耐劳的黑人，比白人的劳动效率还是低（指的不是象科学家、工程师这样的高科技劳动，而是耕地这样最简单的劳动）。美国修泛太平洋铁跌的时候，爱尔兰劳工效率不是很让人满意，有人提出引进华工，结果华工的表现很让人意外，劳动效率比爱尔兰劳工高多了。
所以我倾向于认为，不同的种族，在工作精神，劳动效率方面是有一些差别的，当然这种效率，跟这个种族的经济水平、教育水平、产业经验可能也有一些关系。
同时，社会的发展状态、社会制度，对于民众的劳动意愿和效率也会有影响。基本上，社会高速度发展段，社会上存在可逾越的贫富差距和阶层鸿沟的时候，民众的劳动意愿和工作效率会高。如果社会的贫富差距和阶层鸿沟无法逾越，比如资源世袭的专制社会；或者，不需要逾越，比如吃大锅饭的福利社会，那么民众的劳动意愿和工作效率可能会下降。

26. 现代社会的好处，是社会分工，可以通过跟他人的协作，各自发挥长处，把事情办好。


27. 1，现代工商业的兴起，做大了经济总量，支持更细的社会分工，也能养一个提供更丰富公共服务的政府。2，英国人发明了宪政制度，由纳税人和政府签订合同，有效约束了食利阶层的自利倾向。


28. 很多企业家都有跨界发展，“全产业链”的梦想。这种梦想大多是不能成功的，违背人性和社会分工的铁律。


29. 1，中国人没有分工精神，大企业云都要自己搞。2，中国人太喜欢山寨，容易模仿的行业，都是一堆同质化竞争者。

