---
title: 读书笔记：《公司会雇佣你的 44 个秘密》
author: Guanghua Mao
date: '2022-02-24'
slug: '411'
categories:
  - Original Articles
tags:
  - Book Review
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

# 前言

我们要学会把自己打扮成一个“最佳候选人”，因此我们要了解人事是如何淘汰和录用候选人的。可问题在于没有面试官会告诉你问题出在了哪里，在求职过程中遇到的大多数问题和困惑都会被公司当作“绝密”信息来保护。告知你这些秘密都是为了指导你更好地去应对招聘局面，并让你好好掌控面试过程，由此尽可能得到更高的薪水，获得最大的利益。另外还有一些秘密 --- 如何在入职后的九十天内让你看上去像最新的公司明星。


# 你正在被淘汰

面试难度越来越高，就业形势十分严峻，新的面试技巧五花八门。简历的通过率只有 1 %，99 % 的简历石沉大海。无所适从的人会成为就业市场的失败者，本章会帮助你看清人事经理们在招聘过程中的真实心理动机，让你学会规避风险，说他们想听的，展示给他们想看到的那方面，并努力成为他们最需要的样子，总之，努力成为他们心目中的最佳候选人，并在最大程度上保护自己的利益。人事经理们有他们不可告人的隐秘招聘规则。

## 你不是在应聘，而是在被拒绝

人事经理的活不轻松，他们没有足够的时间去阅读求职信和简历，没有精力核实简历里面的内容与公司岗位的契合度。他们不会因为你写出的密密麻麻的内容就把你列入考虑范围，也不会因为你自认为适合这份工作，就对你另眼想看。

当我们发出简历的一瞬间，人事就需要最有效率地找到该空缺职位的人选，淘汰掉所有不可能入选的人员。我们不是在应聘而是处于时刻被淘汰的边缘。负责为公司招聘的人可不是猎头，他们并不试图找到最佳人选，也不会为你量身定制一份适合你的工作。他们要做的是，从所有求职者中筛除 98% 的人。除非手中握着录取通知书，否则你依然处于被拒绝的体系中。

### 三步淘汰法

第一步：三秒钟关键字筛选简历

人事经理只会在你的简历上花费三秒钟，如果你的简历不突出，太长、太晦涩、太枯燥乏味，你就会被拒绝。在电脑软件面前，如果你的简历包含的关键词不够多，那么电脑便会淘汰你。

记住，别以为你的简历会被人事认真审阅，也别幻想自己精心设计的简历有什么与众不同，更别觉得自己绞尽脑汁、事无巨细的描述能给人留下什么印象。事实是，它和其他成堆的简历看上去没什么两样。所以，写好简历很重要。前提是，你必须意识到自己的简历是如何发挥作用的。

第二步：残酷的电话筛选

简历过关后，便是电话筛选，电话筛选的目的并非是要增进对你的了解，也不是想听到你所具备的更多技能，而是在这一过程中搜寻你本身的潜在“危险信号”。电话面试的陷阱非常多，很容易被淘汰出局。

就算通过了电话面试，第三阶段仍然是残酷的，为什么呢？公司每次招聘都会承担巨大的风险---时间、财务、法律等等。处于对一系列问题的担忧，公司的招聘才会变得如此可怕。而在整个面试过程中，面试本身又会具有最高的风险。

第三步：面试机会

你获得了面试机会，说明公司相信你具有从事这项工作的技巧与能力。但是，面试过程仍然会搜寻危险信号，比如外表、性格等。面试过程充满了需要机敏应对的问题、对性格的分析、网络筛选、背景调查，甚至还涵盖了心理学测试。


所以我们需要制作出引人注目的简历，怎样在最初的电话面试中保护自己，怎么在面试中发挥自己的优势，幸存下来，获得成功。






## 你与他们的“秘密标准”不符

其实，大多数应聘者都具备胜任该工作的必须技能，但是很多人都没有办法通过公司“秘密标准”的筛选。但是秘密标准，每个公司都秘而不宣、且各不相同。

### 歧视不公开但是存在的秘密

没有亮在明处的要求恰恰最容易击中求职者的软肋。比如有些公司不雇佣女性，不会雇佣曾被提前解职的人，不会雇佣在工作期间被评价为不合格的人，还有失业超过三个月，为公司的竞争对手之一工作过，外在形象与公司形象不符的人，你的种族、健康状况、外貌、婚姻状况都在考虑范围内。

在应聘过程中，求职者们经常坦诚告知对方自己的实际情况。他们天真地认为这些都是无关紧要的，全盘告知还从另一个方面表明了自己的可信度。可是，这却是给自己的求职道路“埋雷”的最愚蠢举动了。当你被悄然剔出比赛的时候，当你得到冠冕堂皇的拒绝时，请相信，这是你自己的“真诚”惹的祸。

理解这一点很重要：无论是在正式的面试还是非正式的交谈中，你选择告诉潜在雇主的一切讯息，都有可能被用来和你做对。不要犯言多必失的低级错误。许多公司想完全按照自己的意愿得到他们期望的最佳人选。谨言慎行，是我们在求职过程中必须具备的素养。

很多时候，求职者被淘汰出局的原因往往跟技巧或才干无关，却和公司私下的偏好密切相关。


### 公司绝不会让自己招惹麻烦

一旦确定某个候选人不符合公司的秘密雇人标准，机会的大门就永远关闭了，永远不会再打开。


## 你只有一次机会

为何招聘如此严苛，犯不得半点错误。公司深知一个对公司不感兴趣的人加入公司，或者伪装的理想雇员加入公司会给公司带来多大的风险。“请神容易送神难”，雇佣一个人要比解雇一个不称职的员工容易得多。


### 公司不想承担不必要的风险

有公司因招聘了不合适的雇员而深受其害，比如申请工伤赔偿、休产假、法律诉讼。有的公司曾雇佣过貌似前途远大，但刚一受聘就立刻朝相反方向发展，并在此过程中导致整个部门衰退的人。也许，一个原本积极向上、能动性强的团队一夜之间就开始转变，开始抱怨从管理方式到薪资补助在内的一切，而所有工作都没有人积极去做。

人事经理深知，求职者会在整个应聘过程中表现得像个最佳雇员。他们接受的训练使他们能非常仔细地审视一切，从每个求职者身上读出潜在“信息”。

只要有象征危险信号的红旗举起，即使是意外，哪怕是误解，你的求职之旅都会戛然而止。

整个过程你只有一次机会，容不下半点错误。

紧张的筛选过程中，他们不会暗示你犯了致命错误。事实上，他们会鼓励你一口气说更多，好让你误以为自己的表白不会对录用结果有何不利影响。


## 你犯错误时，没人会告诉你

社会规则严酷而冷漠，尤其是职场中，不要过多渴望他人的善意帮助。对于公司来说，利益的渴求远大于对他人的无私帮助，不要指望公司里面有人告诉你，是什么把你淘汰出局。


### 没人告诉你真实原因

一不小心说错话、做错事，或是触动了公司的某根敏感神经的求职者，会被无情拒绝。除非正式的书面录用通知已被签发，否则你仍然处于被筛选过程中。


### 你的话，令公司感到有潜在的麻烦

无论你不被聘用的原因究竟是什么，他们都没有义务向你透露任何信息。他们不会告诉你，你提到钱的次数太多了；他们不会表现出对你无意中说起的、即将进行的外科手术感到担忧；不会告诉你，你与他们心目中端庄的外表有差距；不会坦言某位面试官认为你的回答中，有一点点消极的成分。

大多数公司对求职者撒谎，是因为他们更害怕被人起诉，或是自己的秘密标准被公之于众。

一次不慎误入雷区，就不会再有人给你第二次机会。如果有什么教训需要我们铭记，那就是千万不要忽视人事经理们心底深处的警戒红线，和公司的秘密招聘标准。

大多数应聘者会不断重复错误的行为方式，一次次地浪费掉工作机会，失败之后根本不知道原因是什么，也不知道自己哪些方面需要改进。




## 隐秘模式会毁掉你的工作


### 表现消极，面试官比喜欢你这样

当被问到为什么会失业这么久，很多人会抱怨经济不景气，而不是自己做错了什么或是能力不足。当被问到为何离开原雇主时，他不希望被人以为是自己犯了错，所以他就说在那里呆着很不愉快，老板对他很不公平，工作环境很糟糕。

以消极的方式谈论过去的工作、公司和老板，会看上去是个不成功或者不吉利的求职者。

人事经理深知，无论经济或市场环境如何，公司对优秀求职者总会有极高需求。无论说什么都行，就是不要抱怨找一份工作有多艰难，或是评价以前的工作环境有多糟糕。

### 不要让人觉得你在意钱

一开始就说出自己对待遇的要求，这会让人认为他在乎的只有钱。应聘竞赛贯穿整个招聘过程，直到你胜利了，才有了与公司商谈薪资的基础。

即使公司在最初的面试中直接向你询问“期望的薪水”，或是要求你在求职信里写明“待遇需求”时，你也千万别上当。在这种情况下，你最好说明你目前的收入水平，告诉公司你在这方面的要求比较灵活，并且愿意考虑任何职位。这就为你奠定了坚实的基础，让你沿着赛道进行有效的商谈，而不至于一开始就被罚出局。

小小的错误模式每天都在令人们丧失工作。用错一个词，讲错一个故事，都足以让一次机会变成一个死胡同。


---


# 别再四处发送简历了

1. 要写自己的奋斗目标吗？

2. 用什么样的简历范本

3. 空窗期怎么办

4. 他们需要的证书我还没有，怎么办？

5. 需要把所有的优势都写在简历上吗？

6. 怎样通过计算机的在线筛选

7. 简历怎样才能出类拔萃

简历没得到电话回应，只有两个原因：求职者不知道怎样用正确的方式吸引人事经理的注意；在简历制作或提交过程中犯了常见的错误

简历制作要高于平均水准，简历并不只是在你求职时才用得上的东西，也不应该是到了找工作的时候才制作的东西。选择怎样制作和呈现自己的简历，可能比简历的实际内容更加重要。简历在缔造未来机遇中十分重要，是我们一生中最重要的一份资料，掌握着未来的赚钱能力、人生际遇和生活水准。

如果你送出的简历低于平均水平，或者你不知道怎样用正确的方式吸引别人的注意，那么，提交简历就毫无意义。公司如果之前见过你的简历，那么第二次投递毫无意义。

## 你的简历直接进了垃圾桶

求职简历如洪水泛滥，从一开始，你的简历就有可能被直接仍进垃圾桶，除非你能让自己的简历在三秒钟、或更短的时间内就牢牢吸引住他们的目光。

事实上，只有很少人懂得该怎样充分利用简历。它不应只是职位和职务的罗列，也不是你的个人编年史，而是一份自我推销广告。

你的广告是会让对方立刻给你打电话，还是扔进垃圾箱，都取决于你。你的简历就是你的一次机会，它使你能把自己推销到决策者面前，让他相信你具有特别之处，与大堆简历中的其他人不同。

你的求职简历必须展现你多年来努力不懈的过程，以及你对职业技能的拓展。这许多情况下，简历的制作方式比它实际涵盖的内容更为重要。

简历必须能设法使你在每次想要换工作时都获得最佳机会。有些事情应当在你的整个职业生涯都加以避免，还有些事连提都不能提。最有效的简历不是那些填满你所有经历和工作历史的文件，而是精心制作的推销广告，而且目标直指人事经理。

牢记你就是一件商品，你的目的就是要表现自己，得到招聘者的考虑。

以下十大秘密，会帮你创造出从人群中脱颖而出的顶级简历


### 别相信噱头的效果

你的简历要展示某些特别的、与众不同的东西，指的是风格、语气和形式，而不是搞怪。合格的求职者应该对自己的能力充满自信，无需借助各种把戏。最好的办法是交出一份整洁、自信的求职简历，让它自动通过招聘体系的考验


### 简历是广告，不是一本书

人事经理就像你的潜在客户。和所有广告商一样，你的目标是在竞争中胜出，强调你最大的卖点和特色。要尊重人事经理的时间，理解他们的工作性质。在他们的世界中，只有简短、自信的简历才会浮出水面。将所有关键信息归纳为最吸引人的片段，并以最快的速度、最有效的方式抓住人们的眼球。

使简历缩减为一页的窍门之一，就是让你已拥有的职位为你说话。你的大多数经历和才能都可以集中体现于你曾胜任的职位中。在每项工作中，说明三个成就的关键点。

你必须突出哪些关键信息：公司名称、职位；把你最让人难忘的成绩、得到的晋升、能表明你贡献大小的数字写进去。

记住简历是用来吊起读者胃口的。它应被设计成可以激发人事经理抓过听筒给你电话、向你了解更多情况的工具。


### 写目标已经过时了

求职目标会显得你的关注点过于狭窄，让人不安。求职总结应是关于你和你能为潜在雇主带来效果的有利推荐。这段总结应位于姓名和联系方式的下方，居中以获得最大的冲击力。

### 争取电话对谈的机会

简历的制作秘密是，千万不要弄成十分详细冗长的自传，而是尽一切可能争取到面试官的电话。

### 格式统一显得更自信

简历拥有始终如一的格式，易读性就会强很多。比如，要点式列表、相似的段落篇幅，以及传统字体。目前的职位需要三个关键要点，更远的职位只需要一个要点。不要用出格的字体，不要大量使用粗体和下划线，外表越整洁、条件越突出、简历更自信。描述你取得的每一项成就时，尽量使用表现主动性的词语。我个人喜欢的主动性词语包括“管理”、“创造”和“处理”。一个词不要多次重复。

### 记得更新简历

要养成每隔一段时间就更新简历的习惯，制作出完整的个人简历。你所列出的在以前工作中取得的成绩，要与你现在达到的新层级水准相关。

### 别在简历中用“我”

坚持用第三人称的口吻写简历。让自己尽可能远离个人经验，能帮你创作出最具说服力的第三人称简历。

### 经营你的市场

求职简历是你整个求职过程中最初的营销/广告工具。简历是你这个令人惊讶的商品的单页广告，也是你派往每个机会的密使。把它作为你最初的行销工具加以管理。

求职者最常落入的陷阱之一：简历是“水到渠成”的东西，当需要寻找工作机会时才投递简历。但事实会告诉你，一份杂乱无章的简历代表一次混乱的市场规划，必然得到糟糕的结局。简历需要认真的管理和创造，只有这样，它才能支撑你的职业目标向前发展。每一段经历结束时，那份工作如何在你的简历中呈现，将在很大程度上决定你未来能获得什么样的机会。如果你渴望有一天成为副总裁，你就应该去做那些能从简历上看出你坚定不移的决心的工作。简历应该是你的决策过程中发挥作用，协助构造你的职业规划。它不单是对既往职位的罗列，还应该能描绘出你的工作轨迹。

求职简历中，任何对于像是在倒退的职位的描述，都会给面试官摇起一面红旗。大多数人如果不是事到临头，是不会想起来写简历的，但如果你使它与你的发展能同步更新，你就会顺利得多，不再撞到意外的阻碍。

从职业总体目标和规划来考虑，职位上的连续变化比你从职位中获得的报酬重要得多。

通过仔细的计划，你可以在职业生涯的任何时候，构建起与你的未来目标吻合的、实实在在的职业轨迹。在简历上对你所有与行业相关的工作经历进行分组，这样做能有效突出你未来的目标。

在目前的简历中，需要将重点放在什么地方，该怎样选择事业道路的下一步，才能巩固那些目标。做出职业选择的时候，一定要记得带着你的简历一起进步。

### 小心空白时间段


尽可能在两份工作之间不要有空白时间段。如果你的工作史上存在时间间隔，要尽可能用积极的事情来弥补。但是有很多公司并不会雇佣有职场空窗期的人，因此要防患于未然，最好在依然受聘时，就小心地准备好寻找下一份工作的简历。有工作时找工作更容易，还在于它能帮你得到更高的待遇。假如出现了危机，你发现自己可能在不远的将来失去现有的工作，那就立刻开始寻找新东家，一遍可有做到无缝过渡，不留空白。


### 小心回应工作周期较短的问题

公司明白，枪手的人总会被“挖墙脚”到另外一家公司。工作只持续几个月会被认为是“解雇”。在某家公司待的年份过久，会被认为思想守旧、不能轻松适应新环境。

求职简历不仅仅是一张纸，它还是你达到职业目标的钥匙。如果你对它进行认真的创造和管理，想对待有力的行销工具一样对待它，你的简历自然会脱颖而出。






## 你可以在简历中撒谎

不能撒的慌：职位、日期、薪资、教育经历、曾经供职的公司

### 只表达对自己有利的部分

可以在简历中安全地编造，而且是对自己有用的谎言是：工作经历。这才是你可以掌控的内容，这就意味着，你可以把你认为对自己前进有害的事情忽略掉。就算一份工作经历不好，是你被冤枉了，你仍然会被拒之门外，理由只是为了“以防万一”。


### 自我推销，无须反思

诚实的信息属于你的隐私，简历的目的是为了营销。运用你的判断力，只写那些你相信能给别人留下最佳印象的事情就好。

## 电脑在决定你的工作前景

电脑程序会扫描简历，找到关键因素。这些关键因素会在招聘公告时出现，一定要弄清楚你的才能和条件最贴近的关键词是什么，把关键词分布开来，铺满整个简历。无论你具不具备相关的条件，都要写进简历。

### 设定切实诚恳的关键词

需要注意一点：公司也在提防着我们。如果你特别想欺骗某个系统，你还是不可能等到电话，无助于我们树立重要候选人的形象。事实上，所有包含主要关键词的简历都能被选中，所以，不必挖空心思搞得华而不实。把关键词写在靠前居中的位置。


## 让自己就像“被推荐”那样

首先，确保简历即使进入候选池。用高质量纯棉纸张或者布纹纸打印求职信，用传统方式邮寄给你能查询到的人。信封必须手写，并在底部标明“私人密函”。这样可以避免被前台或者助理拆开。

好处：1. 你的简历被摆在了关键决策者面前；2. 它可能会被从那个人的办公室转到人事经理的手里，看起来像是一次内部推荐；3. 用纯棉纸张打印、手写信封邮寄的简历与众不同。它有质感、有重量，甚至折叠方式都不一样；4. 拿着纸张阅读时，打印在高品质纸张上的文字更加清晰，让简历显得更重要。

通过这种方法，你可以摆脱很多公司要求填写的在线表格的约束。“即使你填好了，那些表格也只会让你看起来和所有人都一样”。在提交各种表格之后，你还要找到合适的名字，寄出你的简历。别在乎公司说他们“不接受某些方式的建立提交”，只管将它寄出去。如果运气好的话，你的简历会成为人事经理收件箱中，唯一一份亲手转交的高品质纸张打印的简历---这是最佳结果。

### 有时，打电话反而降低面试机会

电话查询自己的简历，实际上会妨害你得到机会，降低你作为候选人的地位。经验法则：不要打电话。把我们能尽力做好的事情全部做好以后，我们要尽自己所能的去找一个真正的内部推荐人。亲手递交简历真的十分宝贵，所以值得你去尝试。

## 优秀的求职信，成功的一半

有效的求职信和简历传递出的应该是你的自信心。所以即便是假装，也要让自己显得信心十足，这样别人也会对你有信心。不要说这样的话，“这个职位简直就是为我和我的经验量身打造的”，这只会激怒对方。自信地叙述自己的经历和特质，让别人得出结论。

说到不如做到。（show，not tell），突出自己的技能和经验，让简历阅读者自己慢慢得出结论。

如果你要去争取一个你完全不具备任职条件的职位，别道歉，也别去吸引面试官注意这一点。你只需简单而自信的把自己的条件说出来，不要把你想得到的职位的具体名称说出来。

### 用自信征服人事经理

不要用“亲爱的先生、女士”，你的简历是写给所有人的。任何情况下，都要体现自己的热情、简练和自信。你显得越自信，你成功的可能性越大。


## 互联网正在和你作对

你放到互联网上的任何东西---博客、照片、网页，都将被当成公共财产，很容易因此惹上麻烦。


### 私人网络信息影响求职印象

你在网络上公开某些事情，也许会导致你的简历被淘汰。互联网通常会鼓励你与别人分享公开和诚实的观点。假如你的观点触犯了你今后打算涉足的行业或公司的价值观或产品，你就是在威胁你的工作前途。

所以，无论你现在求职还是在职，为了自己的职业生涯考虑，一定要注意维护好自己的网络形象。

请避免使用任何将你描述成潜在的惹事鬼，或者带着性暗示的意味，或者非常自我的各种信息。

注意这些琐碎的细节，避免让他们给自己的求职道路增加不必要的障碍。我们也可以利用这一点，打造自己的形象，很多人事都会在网络社区注册账号，搜寻潜在的员工。

小心留意网络上发生的事情。一旦负面信息失控，而又不可能被删除，就会很麻烦。

## 前公司的评价帮不了你

除了你的职位、工作期限、工作职责、以及福利待遇，人事经理们无法从你的前老板那里得到任何信息。

### 找会加分的推荐人

你需要的是亲自告诉人事经理你的“职业推荐人”。对于人事经理来说，如果三个人中只有你能提供一份额外的职业推荐人名单，你自然就成了最妥当的人选。

这份推荐人名单至少要包含三个对你充满溢美之词的前老板、同事或客户的名字。不要在名单中列出你没有十足把握的人，确保你提到与你共事的人与你有过一段时间的接触。

制作高效推荐人名单的四个步骤：

1. 联系每个人，问问他是否愿意当你的推荐人


2. 给他们一些暗示，告诉他们你要申请的是什么职位，你希望他们强调什么，不要谈论什么


3. 坦诚地向他们保证，如果他们需要推荐人，你将义无反顾的充当


4. 将这些人称作“职业推荐人”

不要造假。

是否拥有这份名单，能决定你到底是求职候选人还是顶级候选人。自己找推荐人，还是一种有效的防御手段，让人事经理们的工作轻松些。

要想办法将个人广告、营销、互联网和推荐人名单精心组合起来，只有这样，才能为你的候选资格建立起坚实的平台，并让你看起来是最可靠的推荐对象。

借助每种可以利用的平台发挥你的最大优势，创造你所需要的内容，为简历赢得最大关注。游戏的目标是让自己看上去像最安全、最迷人的候选人。


---

# 你的面试完蛋了

## 人事经理不站在你这边

电话调查人、面试官和人事经理都受过那方面的训练。他们被训练成貌似热心、友善、乐观的公司代表。人事经理永远不会站着你这边。 不管你和这个人建立了何种联系，也不管你的见面多么令人愉快，与公司的利益和“秘密标准”相比，你的利益只能退居一边。

人事经理并不是在寻找最佳人选，而是在避免公司犯下聘用错误。他们的根本任务是，把所有那些可能给公司带来麻烦和不便的求职者淘汰出局。

### 未到岗前，都不可掉以轻心

公司希望严重的麻烦成为别人的问题，而不关自己的事。公司都在厉行节约，不愿意接纳有个人困难的员工了。公司只有让每个人都发挥 110% 的作用才能赢得竞争优势。



## 面试官会欺骗你


### 从你迈进公司，面试就已开始

一旦走进那道门，或是和任何公司代表对话，面试就已经开始。你说的一切都会被参考。从你嘴里说出的任何内容，甚至是玩笑和闲谈，都会被利用。

### 无论他们问什么都别上当

人事经理知道你想表现为最佳人选，所以他们会通过各种方式套话来了解真实的你，发现你的秘密。要牢记一点---不要与人分享你的隐私，不要上当。随时保持清醒，明白你在和谁说话，以及他的任务是什么。    

记住，面试不是告白。此时谈论你的个人事务、喜好、或者隐私信息，都是不妥的。在保护自己免受不当筛选和伪装圈套伤害的同时，你依然可以和面试官保持友好的联络。




## 你的肢体语言会出卖你

### 绝不忽视第一印象

衣着得体、面带微笑、目光接触、握手有力、起身迎接。

### 避免出现的情况

无精打采、盯着地板、双臂环抱、手插口袋、手摸鼻子、揉搓脖子、不停抖动、身体朝向、衣着随便

好的表现：

展现大方的仪表、适当的目光交流、调整姿势、身体前倾、运用手势、与理想形象吻合

## 应对陷阱问题的技巧

别被轻易诱导出消极想法，让自己说的每一句话都是积极的。人事经理希望求职者在面试过程中“原形毕露”，这样他们才能看出你在毫无保留的情况下是什么样子。他们想让消极人物“尽早暴露”，省得日后浪费时间和精力培养他们。

无论面试官问你什么问题，都要做出积极的回答。这不是在与他人分享你的实际看法，而是给他人留下最佳印象，让你的最佳素质闪光的时候。

不要允许自己上当，或者被面试官的问题弄得晕头转向。你要做的就是尽可能保持积极的形象、传递积极的信息。你选择对发生的事情怎么说，可能比真实发生的事情本身更重要。

找一些无伤大雅的弱点，以此作为你正在改进或已经改进的事情。

你个人的雄心、计划、愿望、发展，以及对晋升的期待是你自己的安排，不要在面试中表露出来。晋升不是你能左右的，而是由公司决定的。在他们了解你的真实面目之前，这种大话太容易被误解为“他很快就会对这个职位不满的，因为他已经在想要往上爬了。”

问题：你认为自己五年后会在什么位置？ 答案：不要说自己的未来个人规划，要说就像在这个岗位上为公司创造价值。

面试官会故意引诱你发表消极言论，比如他会抨击主管、说工作的艰难。面试者不能，要克制住发表消极言论的冲动，不然就会掉进陷阱。一定避免透露你职业生涯中的不幸或与消极经历有关的任何信息。

如果你知道面试官正在秘密寻找积极的故事，以及故事背后隐藏的闪光点，并且避免发表任何消极或者批评性的言论，你就能险中取胜，获得巨大成功，成为头号候选人。



## 讲故事是你最佳的防卫手段

当面试官提出一个问题时，他们需要的是迅速的、准备充分的回答，这才能给他们留下最好的印象。要是你结结巴巴，就会让人觉得你想隐瞒些什么。所以最好的办法就是准备 3~5 个小故事，每个故事不超过4分钟，他们都是你最棒的职业故事，要确保每个故事都是从完全积极的角度出发，避免任何消极成分存在。准备好成功故事还有助于你以更有说服力、更让人难以忘记的方式回答问题。

另外一种有效的准备面试的技巧：把你作为最佳雇员的十个特点写出来。你拥有什么别人不具备的特点？要把心态从一个求职者转变为任何公司都将聘用你视为荣幸的伟大员工。

## 某一种“类型”的人总能找到工作

有一个天大的秘密是面试官绝不希望求职者发现的：那就是和他们自己最相似的求职候选人会更受青睐

### 让面试官产生认同感

通过对面试官微笑，进行目光交流，让自己表现轻松，提一些与他办公桌上的照片相关的问题，或是对他进行由衷的称赞，都能很容易建立起这种关联。还要学会“对映作用”来达到目的。效仿面试官的语调和风格，这一作用对于任何人来讲都是有用的。另一种手段就是假装你的面试官是多年的好朋友，你们不过是进行所谓的面谈。但是要注意，不要放松警惕。


### 让对方觉得他是你的焦点

把注意力放在面试官身上，不要过于卖力地推销自己。面试官推荐与他自己相似的人的概率，比推荐其他人的概率高出十倍，因为他喜欢那种令人舒适的协调感。


## 如何应对面试伎俩

面试伎俩并不是用来了解你、发现你的才能，或是营造愉快的会面气氛的。它们都经过精心策划，用来观察你在困难或紧张的环境中会如何表现。不要对这种情绪刺激作出反应，你只需了解该提防什么，如何反应。

### 突然中止

面试官表现得很没有礼貌、毫无兴致。我们也要假装什么都没有发生，泰然自若地离开，微笑着感谢这场面试，不要有一丝慌乱。一定要记得稍后发送一封感谢信。

### 不断地被打岔

把精力集中到问题上，做出你最佳的回答，好像周围没有任何事情发生。不要露出任何不悦之色。

### 临场发问

突然让你给他卖一支笔，或者估算有多少个热气球。保持良好心态，尽量从专业角度处理和回答问题。


### 进餐面试

考察你的用餐礼仪和社交习惯。千万不要喝酒，不管其他人怎么做。

### 非传统的面试地点

为了考验你在压力面前如何应对

### “好”面试官/“坏”面试官

为了让你感到舒服，觉得有人在关照你，好让你不自觉地放松警惕。不管在面试过程中遇到什么，你都得保持冷静。

## 一种方法并不适合所有人

### 生手式

毫无准备、经验不足的面试官，要能够引导面试的方向向自己有利的方向发展，而不是任由面试官来主导。


### 质问式

始终面带微笑

### 流水式

多场面试，要确保自己精力充沛，各个击破。大多数人往往在与副总裁会面时才表现出精力旺盛的样子，对人力资源部助理则不太放在心上。千万不要那样。你根本无从预知谁更加重要，谁能起决定性作用。“超时”是一件好事，说明这个人很喜欢和你交流。


### 人资式

有时候，人事会带你参观办公室，给你介绍福利，公开讨论待遇问题，但公司的目的是为了让你卸下防备，降低你协商待遇的能力。所有商谈都要等拿到正式录用通知之后再说。在任何形式的面试中，你应该说“看上去不错”和“我很愿意考虑任何提议”。

### 主管式

某些情况下，可能成为你未来上司的那个人会是唯一一个面试官。因
此，你必须意识到，他可能没有接受过任何正式的面试技能培训，而且,
一个不得不亲自出马招聘员工的上司，很可能压力很大，过度劳累。大多
数上司连手头的工作都处理不完，更别提为每个空缺职位充当人事经理，你越能表现出对他有所帮助，越能表现出理解，对你就越有利。

应对主管式面试的关键在于，发现对这个人最重要的事物。他在寻找
最符合团队需要的高质量求职者，但还有些其他东西，比如真正的支持者、
拥有团队精神的伙伴。简言之，他要的是能靠得住的人。


### 


## 感谢信写得太迟了

## “补充说明”会毁掉工作机会


## “提问不当”让你像个危险人物

## 挑剔公司的人会被拒之门外
