---
title: 羊小倭微博言论合集
author: Guanghua Mao
date: '2021-07-17'
slug: '255'
categories:
  - Translation Articles
tags:
  - Insights
---

1. 店家说今儿这个天儿还来的都是死忠粉！其实是一富婆放了我和私募金的鸽子！说好的松茸大餐没了😔正好被私募金上了一堂巨牛逼的投资课灌顶秘传：一要分散二要长期持有🙃当然当然那得是美国佬的资产！后一句是我的巨大心得：但凡不是国际盘，都很难称得上算是资产！起码不能算是优质资产[攤手] ​

2. 说得太好了有点像我说的哦！这其实一点也不丢人不过太多人就是不肯承认，也可能是心知肚明却不好意思承认。当然也有狠多人是心里早明白却假装不明白并且生怕别人也明白。于是便大加鼓吹所谓“民族特色”，按时髦的说法是：中国佬自己的话语权。其实阿恪对中国佬最中肯的评价有另外几个字：上诈而下愚。


3. 一想到伟大中华民族的复兴大业还差着30%好几没有完成这事儿，我就心急如焚！我觉着吧：这事儿最终得落在当代艺术这帮丫的肩膀上！等鬼佬蜂拥来买齐白石张大千？难！指望太极拳奥运会夺金？遥远！靠针灸把鬼佬们麻醉了？也玄！放眼望去：咱中国佬唯一在形而上领域还有鬼佬埋单的也就是当代艺术了吧？ ​

4. 我发现：狠多人不愿意承认满清三百年其实是中华文明最停滞也是最屈辱的三百年。最简单问题：这三百年顶脑袋上的小辫子是你们丫老祖宗兴高采烈地顶上去的吗？不是吧？是被迫的吧？即使是这么多中国佬艺术家爱往自己身上贴所谓的民族符号，怎没见有贴辫子当符号的？似乎连溥儒老师也没画过大辫子人物吧？ ​

5. 都以为能骗得了自己也就骗得了别人！市场不是傻子，垃圾就是垃圾！路边苍蝇馆骗骗女文青也就算成功了，还真以为能上大台面？随着写实画派在中国渐渐失去市场，兄弟我相信《舌尖》类垃圾文化的受众群体也一定会萎缩！写实画派是什么？就是以一个虚假的起点开始捏造一个虚假的完美，赚取一片虚假的感动！

6. 昨大不靠谱@黄章晋ster 老师发图并问为毛这种丑陋至极的东东在中国特别多？晚间专门研讨惊诧发觉：会不会是这一届人民不行啊？可冷汗中细究：从新加坡到香港再台湾莫不如此诶！又问：尼玛走遍全世界哪一处唐人街不是当地最LOW逼审美大聚集之所在呢？于是又叹：尼玛不仅仅这届人民审美有问题啊？ ​

7. 晚间约酒@雕爷 去谈大买卖留下@和菜头 给我讲国际国内形式：科技不行教育不行XX不行其实连文学也不行！乜都不行！为毛当年海龟大都要全盘西化？因为他们丫国学底子太好！为毛现在很多海龟扯淡要打国学牌？实在因为自己国学底子太差！鲁迅为毛反对读中国书？就因为是看见差距太大所以对中国文化绝望了 ​

8. 白天和@和菜头 及@雕爷 谈及这咪兔要让中国艺术界完蛋啊（某猪不算艺术界或可算食评界）臭老雕说呸！咪兔就是美国文艺界发起的！大唏嘘：人家境界咋恁高呢？不怕自毁？晚间和童教授吃饭又有大担忧：你们教育界必重灾区！童教授撇嘴我们学习美范儿自重着呢！兄弟本来哈日现在发现真老大还就是美国佬 ​

9. 就知道狠多人骂我势利眼：鬼佬说好我也说好！其实也不完全这样的[摊手]我只是对确实先进的文明表达出应有的尊重！并且我还算善于思考并提问：世界顶尖的大画廊某间已经被郝量老师挤进去了另一间曾梵志张恩利俩萝卜也占了坑！就差卓纳名单里没中国佬的名字啦！由不得你丫不势力！猜猜会是谁[摊手] ​

10. 前好文提及大不靠谱@黄章晋ster 老师金句：汉奸要理直气壮！其实最经典的爱国名言出自陈大悲老师1922年话剧《爱国贼》：我们当贼的没有不爱国的！陈大悲：中国现代话剧之父伟大的戏剧先驱晚年曲线救国组远东剧团以“向新中国建设之理想迈进、创造新中国艺术，阐扬文化、纠正思想为宗旨”弘扬大东亚共荣 ​

11. 恩师饕餮烟花盛宴归来约酒大艺术家局聊及中国佬到底有冇哲学？从公孙龙到王阳明总感觉在似有似无间！朴素的早期思维最灿烂也就数先秦了[攤手]巨大心得：总应该算象形文字是罪魁！罢黜百家罪亦莫大焉[攤手]若一路思辨落来呢？格局也未可知！但首先要承认是低级文明，认了，才有变革的可能及重生的希望 ​

12. 昨夜大艺术家局聊及现代主义！我引用@史前人类学 老师金句：老毛子就算欧洲的地板，却也是中国的天花板！巨大心得：别自己吹啥叫牛逼！看看你对世界文明的贡献几何？而一个简单界定就是你影响了谁？多少接受了你影响的异域文明在转述你在延续你？而不能自己觉得好就算好！叨逼叨半天发现尼玛几乎冇 ​​​

13. 朋友圈楷模崔各庄之光[good]昨大艺术家局我招呼大不靠谱@黄章晋ster 丫正在五环外下厨闻讯竟丢下俩嗷嗷待哺的仔廿分钟现身！啃着羊腿肉大艺术家说想听批评于是聊及艺术评论：中国有艺术评论吗？台湾有吗？香港有吗？都冇！中国佬讲艺术就两类：假装B+吹牛B！若偏说有第三类那也就是low逼 ​​​

14. 我就知道有质疑：你说陈寅恪骂中国佬上诈而下愚！有啥凭据？于名人金句兄弟我从不敢瞎掰扯！此言见《吴宓日记》1937年7月14日：“晴。。。晚饭后与陈寅恪散步。寅恪谓中国之人，下愚而上诈。。。抵抗必亡国，屈服乃上策”可惜洞见伟大如陈先生亦只识国人之愚却忽略了美国佬的伟大：高级文明的力量 ​​​