---
title: 中国的建设狂热难解经济困局
author: 陈志武
date: '2021-06-26'
slug: '203'
categories:
  - Translation Articles
tags:
  - Economics
  - Prediction
---

> 中美之间的差距会越来越大，从2025年算起吧，国内的公务员、事业单位、国企、落后的法律体系等严重阻碍了经济的进一步发展，更不要说在逐渐缩减的自由。等待疫情结束，全球经济恢复，人们会逐渐认清美国仍然是生活和投资的最佳场所。中国和乌克兰的差距会逐渐缩小。

[Source](https://news.ifeng.com/opinion/200812/1205_23_909446.shtml)



在我们揣摩中国5860亿美元经济刺激计划的含义时，思考中国为什么每次在需要促进经济增长的时候，都选择基础设施建设、房屋以及大项目，是很有趣的。中国应该或者能够仅仅通过增加实体建筑来取得长期增长吗？如果当要暂停或改变经济增长的路径的时候，中国现存的政治－经济制度能够适应这样的变化吗？

在最近到巴西的一次旅行中，我的出租车司机抱怨圣保罗崎岖不平的街道和公路。我回应道，“我以为高油价和高铁矿石价格已经使巴西繁荣起来了…巴西为什么不在其基础设施建设上花更多的钱呢？”

出租车司机回答说，“巴西经济运行良好。但是，只要政府有额外的钱，卢拉总统总是喜欢减税并补贴人民，而不是将这些钱用在修建道路上。为什么？”

“哦，”我说，“想象你是卢拉并且有180亿美元可以支配。你是将这些钱花在修建公路上，还是宁愿给每个巴西人发100美元？”

“当然将它给人民，以赢得更多的选票。”

“如果赢得更多的选票不是政府考虑的一部分，那么将钱返还给人民从来就不是一个选择。中国不仅仅是花掉钱，而且似乎总是喜欢像摩天大楼，华丽的政府建筑物，公路以及大工业项目这样有形的东西。”

这不仅部分地解释了像印度和巴西这样的民主国家在基础设施上落后于中国的原因，也解释了中国将其新经济刺激计划集中于运输系统上的原因（仅仅铁路项目就会得到5860亿美元经济刺激计划一半以上的投资）。只对上级负责，而不对选民负责。对上级来说，有形的项目是最容易识别的东西。

事实上，虽然中国的新经济刺激计划极其强调基础设施建设，但是对诸如医疗和教育这样的社会保障项目却堪忧，即使这些社会保障项目可以降低家庭的储蓄压力并增加私人消费。

这种支出结构一点也不新鲜。在2007年，中国在医疗、社会保险和失业福利项目上的政府开支总计约880亿美元，即财政预算的15%，GDP的2.4%（既远远低于发达民主国家，也远远低于发展中民主国家的一般百分比）。巴西政府仅仅在医疗上的开支就占其GDP的4.7%。中国政府在教育上的开支大约是GDP的3%，而巴西的是GDP的 5.4%。

由于缺乏对政府预算的公众监督，中国特别偏向于赞成大型实体项目，并且，通过税收和全民所有制，政府几乎维持着对绝大多数国民收入和财富的完全控制，从而将这种偏向的影响最大化。北京令人惊叹的奥林匹克场馆不是一个意外，而是这种体系的结果。

征税权力如果不受人民代表大会和媒体的制约。那么，结果，从1995年到2007年，调整通胀后的政府财政收入增加了5.7倍。与此形成对比的是，在同期，城市人均可支配收入的累积增长是1.6倍，农村人均可支配收入的累积增长是1.2倍。这是越来越多的国民收入归国家所有的经济制度。

尽管进行过私有化，但是，现在中国仍然有大约119000家国有企业，这些企业的账面价值大约有4万亿美元。中国国有土地的价值超过了7万亿美元。加起来，这些国有资产合计几乎达到了中国国家生产财富的四分之三。

因为国家占有了这么多东西，所以在过去30年里，中国资产价值的收益都进入了政府的口袋。当大多数家庭不拥有生产资产的时候，它们不能分享资产升值和财产受益。对大多数中国公民来说，工资是唯一的收入来源。但是，工资的增长速度远远低于GDP的增长速度。难怪中国的国内消费不能以与GDP相适应的方式增长。

将中国从一个出口驱动型的经济体转变成为一个依靠国内消费的经济体需要进行两个根本性的改革。首先，剩下的国家资产的所有权应该公平地分配给13亿中国人。这可以通过将这些资产置于国家财富基金之下，并免费将基金的份额分配给中国公民的方式来实现。

其次，政府的预算过程必须通过国家立法机构的公开听证和经过媒体的公众参与进行公开。因为这样而增加的责任，可以使政府开支离开实体构造建设，向与人民需要相关的项目转移。

没有这样的结构改革和通过减税以及退税将财政盈余返还给家庭的行动，中国政府建立在投资上的经济刺激努力最多可以在短期内对经济起到促进作用。它们不能改变中国的出口和投资导向型的政治－经济体系。事实上，即使在新的经济刺激一揽子计划之后，中国仍然依靠投资和出口带动增长。

30年来。通过全民所有制和税收将资源集中到政府手中，对中国的发展起到了很大的作用。它为中国“集中资源办大事”的国家建设政策提供了基础。

但是，现在中国已经有了体面的基础设施，令人印象深刻的大楼以及过剩的工业基础。中国缺乏的是促进内生性增长的足够的私人消费。为了改变这一点，中国需要提高其人民对未来的金融安全感，并使私人收入的增长和GDP的增长相适应。建设一个国家需要的不仅仅是钢铁和混凝土。