---
title: 比吹牛更可怕的，是不知道自己几斤几两
author: 六陆
date: '2020-12-18'
categories:
  - Translation Articles
tags:
  - Psychology
  - Sociology
slug: '118'
---

[Source](https://translate.google.com/translate?hl=en&sl=zh-CN&tl=en&u=http%3A%2F%2Fblog.sina.com.cn%2Fs%2Fblog_4a01359b0102wgbh.html&anno=2&prev=search)

> 人最值钱的就是知道自己几斤几两，没个分量你往大秤上站站试试？那个秤砣动都不动。——倪萍《姥姥语录》

中国传统算命有一种说法叫做称骨。大体上同四柱算命差不多，能根据出生年月日推算出一个人一生的吉凶运势和旦夕祸福，在称骨算命中，一个人出生年、约、日都是有具体的重量规定的，只要把一个人的出生年、月、日的重量加起来，按照“称骨歌”查一查便可确定你的人生轨迹。对此我们大可一笑了之，但人都是有自己的重量的，做事之前总得掂量掂量，这事我是信的，不清楚自己几斤几两的人大多过不好自己的日子，我觉得这两者算是异曲同工。

前一段和朋友一起吃饭，期间有一位未见面的姑娘也在局儿上，期间闲聊，姑娘侃侃而谈，有哪个商场的贵宾会员卡，昨天又去买了件什么牌子的衣服，那天刚刚办完韩国自由往返的签证，这回没事就可以去逛街，眼睛里透着一股毫不掩饰的自得。后来又有人提起股票，姑娘又举手投足间开始指点江山，分析得头头是道，把去年股灾的原因，未来股市的发展方向都盘点的清清楚楚，另一位也是好信，问：“那妹子，你这去年看来是没亏啊，赚了多少呀？”姑娘抬起手指头一笔量：“都上双位数了呗。”

带她来的那位也讪讪的样子。这姑娘可能在桌上只有和我比起来，可以洋洋自得，因为其他人都要比她强过不止几倍，她所谓的商场，别说银卡了，很多人都是金卡，她所谓的品牌衣服是大家的日常穿着，她所谓的自由往返签证，在她还冒着尖奔着报个旅行团去香港那会儿，她们就已经开始总飞韩国购物了。而她所谓的股票经验，更是座上有专门从事这个行业的，有中国刚有股市那会儿，家里就有人炒股的，有一天涨跌停的钱数顶的上我一年赚的。

小李子演过一部电影叫做《华尔街之狼》，里面有这么一段话，小李子初入华尔街，遇到人生中的第一位导师马克：“做操盘手自己赚钱的同时还可以帮助对方赚钱，这不挺好的吗？”马克在豪华午餐上给小李子演的乔丹上了第一课：“不，华尔街的第一要则，没有人，除非你是沃伦巴菲特或者是吉米巴菲特，不然没有人知道股票是会涨，会跌，会持平，还是如此往复，至少咱们股票经纪人不知道，对吧？这都是唬人的，唬人的你知道什么意思吧？就是假的。“

所以，桌上在股灾中全身而退，甚至赚的满盆钵体的那些位大神，都不敢开口说自己预测的多准确，而这位姑娘竟然真的以为自己是股神的代名词。多可怕的一个事儿啊，就像班门弄斧一般，多丢脸的事啊，明明已经班门弄斧了还不自知。

饭局散了以后，我心里暗暗告诉自己，以后离她远点。不为其他，就算以后一起同行，被人误会我朋友都是这种以为自己很牛的角色也挺够呛的。

我平生最怕的几种人之一就有这样的，但也不奇怪，人往往皆是如此，不知道人家的底细，愿意大包大揽的吹点牛皮。人人都觉得自己总有一方面是特好的，都会习惯性地自我催眠，似乎这么做了，就成了真的。就像照镜子的时候，镜子里的自己总会好看那么两三分。这事太可怕了，因为你所以为的，并不是真实的，你成了自己心目中的女王却沦为桌上让大家大跌眼镜的对象。可这事也不怪她，根里带来的。从古至今都不可避免的，一直横在这儿的，我称之为人的劣根性之一。

我之前听过晓松老师的一次节目，他对于1860年的中国和日本做了详细的对比。非常有意思。

中华这个词竟然是日本发明的，而非中国。而中国对于国家这个词开始有了正确的认知是在1860年，那一年被称为咸丰十年，到底发生了什么事？初中的历史书和北京的一处景点儿都可以告诉你答案，英法联军进入了北京，火烧圆明园，逼得咱们的咸丰皇帝一路逃到了承德避暑山庄，犹如待宰的羔羊，在那等着改朝换代，叫英朝还是法朝还是英法朝，可英法联军抢烧过后，拍拍屁股回去了。

咸丰和慈禧这会儿才明白，原来远在大洋彼岸，人家有自己的底盘，人家和咱们一样，甚至比咱们强上多倍，人家不是来改朝换代的，只不过是来蓄意抢劫的。这才开心的回了老窝，并且承认英国可以自治。多荒唐，人家用你承认什么呀？

在这以前，中国一直称呼自己为天下，何谓天下，全宇宙！然后对于邻里乡亲的都怎么办啊？东边远点的就叫人家夷，南边远点的就称呼人家为蛮，西边的呢，统统叫做戎，北方的就说是狄，就我自己最牛，我是天下。

所以啊，老祖宗都犯这样的毛病，我们又怎么能避免。但往往见识越少的人，越是喜欢洋洋自得；眼界越窄的人，越是自以为是。因为懂得越多，越发现自己的无知，接触的人层次越高，越觉得自己的渺小。坐井观天，看见的不过见方尺寸，即便想要自醒一番，自己都跟不上境界。

就像我以前听说过，条件艰苦又信息闭塞的家庭中的孩子意外收获了参访记者给他的200元钱，开心的几乎要跳起来，拿着这200块钱恨不得横着走路，和全村的孩子说，我有钱了！可200算多么？对于我们来说，一顿饭可能还不够，他难道不知道这世界上有百万，千万，亿这样的数字作为计量单位？数学课本里一定学过，可为什么不说，因为那句大俗话，我连想都不敢想！他从来不会把这样的数字单位和金钱进行挂钩。

这不叫脚踏实地，这叫没有见识，没有眼界的悲哀，这叫不知道外面的世界有多大。

我小时候写过几篇作文，投了中学生愿意订阅的一本学生读物，录用后，拿着那本书在家炫耀了好多天，真心以为自己是文坛未来冉冉升起的一颗巨星。我妈说我的原话是：“这算是一本多大的杂志啊？就给你嘚瑟成这样，真是不知道自己几斤几两。”当初我认为是泼了好大一盆冷水，让我记到现在，后来越发觉得说的好有道理。

我曾经听说过一些人，看过几本书，便觉得自己洋洋洒洒可以泼墨；还有些年纪轻轻，刚上班的孩子，自认为工作不错，在大庭广众之下以月薪4000、5000作为骄傲的谈资；更见过多位三线小城生活的同龄人觉得自己有一辆不错牌子的车，买得起大众所熟知的几个一线品牌就成了上等人。

我想这些人的存在都是因为没见过真正的市面。有时候我们反感一些人是因为他们吹牛，但是什么叫吹牛？就是明明知道自己不是那么回事，但是选择夸大其词。这叫吹牛。而有时候我看见一些人会觉得深深的可怕，比胡乱吹牛要可怕得多，是因为他们讲的都是事实，但是他们没有认清这些让他们无比炫耀的事实在现实面前真实的价值是多少。

所以，最可怕的不是你无知，而是你无知还不肯自知。和那些明明已经很优秀依旧放低了姿态在拼命努力的人比，还处于我最牛我最棒的自我催眠里，快快醒醒吧，人啊！总要自己没事把自己拆卸的干干净净的上社会这杆子大秤去撑撑，才能知道自己是几斤几两。