---
title: 民企的未来
author: 辉格
date: '2021-07-06'
slug: '243'
categories:
  - Translation Articles
tags:
  - China
  - Economics
  - Business
---

[Source](http://headsalon.org/archives/3578.html)

2012年7月20日

> 根据我这些年的观察也只能看衰了，在党国2021年庆祝党生日的时候，我不禁想起了一句话：智者务其实，愚者争虚名。党、党国、党国人民都太爱虚名，尤其是在整体都国力大幅提升之后。但我们仍然需要注意的是，中国人均GDP为1.05万美元（2020），低于世界人均GDP的1.156万美元，另外，作为经济增长的主要引擎，2020年内地消费仍是负增长，全年社会消费品零售总额较上年下降3.9%。全国居民人均可支配收入扣除价格因素的实际增幅仅2.1%，低于经济增幅。我认为中国无法跨越“中等收入陷阱”。再重申一次之前提到过的观点，我认为中国的国力会在2025年左右达到近现代以来的相对巅峰。不禁让人想起了小镇做题家，一辈子受尽精神折磨，真可怜。

当地省市两级政府动用财政预算为私人企业江西赛维应付债务危机的举动，开了一个十分惹眼的先例；与此同时，同样陷入债务危机的众多浙江中小型民企却没有这样的好运气，个别企业破产大面积牵动了担保网络，导致银行争相抽贷，在当前这样的低迷萧条大背景下，恐怕会有一大批企业挺不过这一关。

近些年来，民营企业的生存环境日趋恶劣，今年更呈现出加速恶化的趋势，从新劳动法开始，民企面临的管制日益严苛，在资源能源类产业，他们被不断壮大的垄断国企全面排挤出市场，在煤炭业甚至遭遇大规模没收；金融危机后，又承受了干预政策的沉重打击：数十万亿投资很少落到他们手里，投资热潮所引发的要素价格暴涨却无从逃避，同样，信贷大放水时没他们的份，泡沫破灭后的紧缩却首先冲击到他们。

前景更加不妙，大规模财政干预导致的虚假繁荣过去之后，许多地方政府本已面临着一个财政烂摊子，加上制造业失速后，地方税收必将下滑，而土地财政又被上了锁，未来几年地方政府必将挖空心思寻找税源，民营企业恐怕会被首先拿来开刀；所以，一个摆在我们眼前的问题是：民企在未来还有没有生存空间？如果有，在哪里？

在企业与地方政府之间，曾有过一段为期十多年的蜜月期，各地政府争相招商引资，在土地、基础设施和税收等方面为企业提供极为优厚的条件，并且通过各种土政策，在总体制度变革滞后的情况下，在局部创造出良好的制度条件，张五常将此局面称为“县级制度竞争”，并坚信这是导致中国奇迹的秘诀所在。

然而仔细想想就会发现，张五常的县级竞争理论很难成立，首先，将地方政府视为拥有独立意志和行动能力的人格化主体，是站不住脚的，其次，即便地方政府具有这样的特性和能力，其所追求的，也不大可能是长期利益，更可疑的是，它能否对自己的许诺承担责任？在面临上级政府干预、调控、清理整顿和“规范化”时，能否顶住压力坚持自己的土政策？

事实也已表明张五常的乐观看法是错误的，在短暂蜜月期过去之后，硬伤逐渐开始暴露出来；被招商引资政策所吸引的企业家发现：早先的优惠宽松往往只是个养肥了再杀的圈套，根本不可能要求后任对前任的政策和许诺负责，当之前提供给你的资源有了更有利可图的用途后，他们会毫不犹豫的腾笼换鸟，把你升级换代、优化组合了。

更大的问题是，地方官员的激励机制与这种制度竞争并不匹配，特别是第一把手，他既非本地人，不受乡里评价的约束，而他的下一个任所通常也不在本地，因而既没有长期激励，也没有做长期承诺的能力。

这一点在官员普遍年轻化之后尤其突出，之前，地方政策还可以由通常本地任职的高层副职和中层官员获得一定的延续性，假如这些官员年龄较大、因而没有多大机会在更高层次上获得升迁机会的话，就会有激励维持政策与制度稳定，而且因为一把手调换频繁，实际政策制订更多掌握在这些副职和中层手里。

但近年来形势已经改变，随着官员年轻化以及地方势力全面削弱，官员的激励越来越多来自上面因而其作为也越来越迎合中央要求；其实，在中央集权制的大背景下，这种变化是早晚会发生的，中央不会坐视地方制度竞争的结果过度偏离其所设定的制度走向，而90年代以来的财税制度改革、银行与国企的垂直化改造、垄断央企所带来的巨额租金，都让中央政府拥有了扭转任何制度差异化和离心倾向的能力。

当一个长期衰退前景逐渐明朗时，上述隐患将会集中爆发，此前之所以能有一个蜜月期，是因为当时整个经济处于持续高速增长之中，在增长预期下，地方政府考虑的是：每年涌现的众多新企业（也是新税源）中，我能吸引来多少？而在衰退预期下，问题转变为：从这根正在融化的雪糕中，我能打捞到多少残值？

一旦这样的预期形成，局面就非常可怕，我们将看到一幅“泽之将竭，其捞也狂”的哄抢场面，因为此时竭泽而渔显然已是最理性的选择；考虑到人口逆转所带来的资本要素贬值浪潮才刚刚到来，还将持续二十多年，除非出现另一个异常强大的增长源，长期衰退前景是可以预见的，问题仅仅是触发哄抢的临界点何时到来，以何种方式到来。

面对如此前景，企业会做何反应？明显的出路是乘资产大幅贬值之前变现走人，这一过程实际上已经开始，留下来的不得不调整策略，将资本配置为容易转移变现的形式，其实因为财产权缺乏保障，国内企业原本就有这种倾向，比如许多知名制造业大厂商，其核心资源其实从来都不是制造，而是营销团队和规模化劳动组织，夸张点说，他们更像是营销或劳务公司，前者随时可以拉走队伍另起炉灶，后者只不过租个厂房转卖劳动。

赛维或许给我们演示了新时代的民企生存之道，那就是与官员利益绑在一起，同时借助相互牵制的利益网保护自己，赛维在光伏产业的迅猛成功便是利用了政府的干预政策，当前的债务危机也是该政策所导致的新能源泡沫破裂的结果，但因为他精心安排的债务结构，与地方政府形成了一种相互绑架的关系，得以避免成为投资狂热的替罪羊，相比之下，那些当初没有与政府一起吹泡泡的企业，反倒没有这样的好运气。

