---
title: 雪球方三文互联网投资分析笔记
author: 方三文
date: '2021-12-22'
slug: '356'
categories:
  - Translation Articles
tags:
  - Investment
  - Insights
---

[Source](https://zhuanlan.zhihu.com/p/111800271?utm_oi=1388405968477249536&utm_source=pocket_mylist)





雪球方三文互联网投资分析笔记


照例，上半部分笔记，下半部分原文摘录。

老方。北大---南周---网易---雪球。

1、互联网公司具有自我实现特征。越多人用越好用。社会关系沉淀＋数据积累＋用户生产内容。

2、三个角度理解互联网公司。 行业、产品形态、商业模式。

（1）行业。“好行业”特征：潜在的用户规模巨大，普适市场总体上》细分市场，市场处于增长期，终身/高频/高客单价需求。

交友的商业模式（终生）比结婚相关的行业要“好”（世纪佳缘）;商务游比休闲旅游的市场要“好”（频度高）;如果是非终生，低频的行业，那么需要客单价要高（搜房，汽车之家）。同时具备这三点要求是很难的，如果具备两点一般就是有潜力的行业。反例是网上卖书，这是典型的低频（比大家想像的要低很多）、低客单价（而且价格是相对透明的---印在书的后面，缺乏定价权）的行业。当然，图书作为第一代电子商务的交易标的，因为是高标准化产品，在电商发展的初期，图书是一个消费者容易信任和选择的切入点。

（2）产品形态。有交互和开放性的产品形态总体上更好;以用户而非流量来衡量的产品形态更好，以UGC取代竞价排名为特征的产品更好;以个性取代共性的产品形态更好，有长尾商业价值的产品形态更好。

（3）商业模式。离交易越近越容易挣钱，挣销售预算的钱优于挣市场预算的钱；用户直接付费优于客户转化（游戏直接向用户收费不需要客户转化，是“效率最高”的）；核心业务收费优于增值服务收费（提供什么类型的服务就在这方面收费是最优的例子：奇虎主要提供安全产品却不能从安全产品收费，而在增值服务上收费，这样转化链条就稍长）；交易佣金优于收广告费；效果广告优于品牌广告。

3、互联网公司是这个世界上最好的价值投资标地。

投资互联网公司的三个理由：行业规模超出人的想象，行业集中度非常高；注定是高利润行业；非常深和宽的护城河。

（1）关于高利润率。由三个因素决定：规模效应、自有用户比例、转化效率。

讲规模效应，互联网公司注定有大规模的特点，但它也有不同于其它行业的特点，互联网公司在扩张过程中，规模效应特别明显，当它的用户和营收以倍数增长时，互联网公司投入的增长速度远远低于它营收的增长（边际成本递减）；

第二，真正的互联网公司的营销和推广基本是靠用户口碑传播，成本是很低的；

第三，海量用户转化成为公司创造价值的商业用户。什么决定了转化效率？

首先决定转化率的就是网站内容和交易关系，对应关系越好，转化关系就越好；搜索引擎用关键词建立内容和广告之间的关系，所以转化率有了质的提升；时间上的对应。也许你知道用户需要某一类广告，但你很难知道他什么时候需要广告，这就是FaceBook和谷歌的区别；效果是否可以衡量。

（2）互联网的护城河。主要来自于用户反复访问这个网站带来的用户黏性、自我强化。反复访问、用户关系、UGC。

越多人用的网站越好用，最后会形成的格局是垄断。这个世界上垄断程度最高的就是互联网公司，垄断带来的行业集约化的程度都超过绝大多数传统行业的公司。垄断会带来什么？高利润，所以结论是什么？真正的互联网公司一定是垄断的，垄断带来的结果就是老二没有前途，非死不可。

在选择公司时大家可以一个个地问这些问题：*首先，这个行业/公司是否对应足够的用户需求；*这个公司的用户是买的还是自有的？*接下来要看这家公司是否拥有垄断地位？垄断地位如何形成，可以看这家公司？提供的功能和体验是否有独特性？还可以看这家公司提供的主要是互动体验还是单向浏览？还要看网站内容是用户原创还是来自第三方，有没有独占性？还可以看这个公司用户的转化方式是什么，是传统的付费广告、按点击付费还是根据成交的效果付费。

4、视频公司商业模式演进史

（1）短视频。为什么YOUTUBE能起来而国内的跟风者起不来？美国在录像机时代就有拍搞笑短视频的习惯，很多人喜欢搞这个，等于是有一批创作者，然后就搞起来了。而中国，一者上传视频需求和硬件条件不存在，二是贴片广告不成立（UGC，没有厂商愿意在一个品相不可控的视频上放广告）；

（2）长视频＋贴片广告的商业模式。供应方很有限，导致价格倒挂，采购成本很高。而且用户随着产品走，没有任何一家能够把所有的剧买下来。这就变成了一个简单的商业，我有钱的时候买一个东西，火了，卖了点广告，一算毛利是亏的，卖广告的钱还不够买版权的。

（3）短视频再次崛起的几个原因。

*手机取代了PC。这大概是2010年之后的事情，手机取代PC成为用户主要的（终端），无论是发、拍还是看；同时网速有了巨大提升，这时候发现用户拍短视频上传比过去用DV拍下来剪辑上传，便利性提升了一万倍，因为（终端）发生了变化。

*这个过程中发生了信息流广告，不是贴片广告，而是信息流广告，

*短视频和长视频有巨大的区别，短视频是依赖于所有用户的上传，而不是少数供应商，所有用户上传的目的就是要别的人看到，所以这个地方就存在一种规模效应，如果你能做到最大，其实本质上你是可以消灭竞争的。

*短视频是人类社会到目前为止门槛最低的媒介，这就是一个爆炸。相比较文字、电影、电视剧。

（4）关于直播。

*直播有规模效应，因为只有越多主播才有越多观众，越多观众就有越多主播，这时候有了规模效应，规模效应的意思是它能够通过规模消灭竞争。关于它们背后的商业模式，打赏是最好的方式。

*直播这个东西只有完全长尾化，有无数的主播来了，这个平台才有价值。同时，直播这个业务的本质其实是陪聊，而聊天这个东西一定只有长尾化的主播才可以。

*游戏直播的问题在于它是头部化的。如果是头部化的话，平台就比较难挣钱；映客的商业模式有个巨大的问题，你没有客户，要靠投放去买，如果要投放购买客户，你就必须得有卖点，通过广告获取，卖点只能是少数的明星主播，但直播这个模式一旦走入少数明星主播的模式，你的平台就完蛋了，因为头部主播要把大部分钱拿走。

*为什么打赏是比广告更好的商业模式？最好的商业模式就是你提供服务，对这个服务打赏，你看用户付费模式，一款10万人同时在线的游戏就可以支撑一个上市公司，但一个10万人浏览的媒体没啥价值，两个商业模式的价值完全不在一个层次上，需要转换场景的广告是最差的商业模式。

（5）短视频和直播这两个行业相比，短视频更大。因为聊是有门槛的，首先你不知道咋跟人家聊，看是没有任何门槛的。快手的DAU是1.2亿左右，抖音的DAU也接近1个亿，下面的直播平台，像陌陌、YY大概都是一千多两千万，差别还是比较大的。但直播是直接的商业模式，而短视频并不是直接的商业模式，需要在上面加信息流广告，所以可以认为短视频是一个更大的东西。

5、公司点评：

奇虎：商业模式的问题：收入的转化链条有些长，从浏览器到导航网站到搜索这个转化链条的衰减率会比较高。

微博：目前讨论的东西主要是国家大事，离商业价值有点远（核心业务收费优于增值服务收费）。

大众点评：大众点评从点评入手，美团直接从交易入手。在接入交易的环节，美团的执行能力很强。当交流和交易融合的时候，社区的价值就会爆发。

搜房：对搜房形成威胁的可能不是乐居这类模式，而是新出现的能够对交易接入更深的模式。

唯品会：服装库存问题是永远存在的，作为高毛利，低成本又有很强时令属性的服装，必然存在库存问题;同时，中国有非常大的贫富差距，地区差距，导致市场非常大。唯品会从一开始设计商业模式就决定了它的命运。大部分人对电商的理解是把线下的东西搬到线上来卖，但是线上卖货的门槛更低，导致竞争更激烈，大家挣不到钱。唯品会的思路和他们不一样，利用时尚差异，地区差异解决了三四线城市年轻女性的需求，同时解决了服装商的问题。唯品会对奥特莱斯的模式有深刻的理解。

腾讯满足最多人、最基础的需求，人未必要玩游戏，未必要电商上买东西，但人一定需要跟人沟通，所以在满足需求方面，它的土壤更加深厚，满足的用户数量也比其他两家大很多。第三，它在商业上或许跟阿里差不多，因为电商直接指向交易，创造的利润要多，所以总体上它们的利润体量差不多。但我觉得，腾讯满足的用户需求还有一些冗余，阿里的商业价值已经发掘得比较充分了。

我觉得T最大的价值是提高了沟通的效率。沟通应该说是人最重要的永恒的需求，而它这方面提供了一个比过去任何产品都更好的满足，极大的提高效率，改进了体验，然后在这个基础上做人与内容、与服务的链接，对提高整个社会的效率都起了很大作用。

它最大的问题就是它太强大，强大得让人觉得可怕。理论上来讲，它要能全部做成，简直就是中国。一个东西太强大，强大到总是让人害怕，就违背我们的常识。

B面临的问题核心是用户行为的变化，就是搜索占用户行为的权重大大的下降，新的行为是刷，在刷这个事情上它占的比较低。

6、其他。

——一个投资人要长期在市场上挣钱，必须基于三个认知，就是他的自我认知、市场认知和对公司的认知。我的自我认知和对市场的认知，可能超过大多数人，我在对具体的公司行业认知方面，优势比较有限。

——我对市场的认知是这样的，市场波动基本上非常难以掌握，但是可以事后利用。明天股票是涨是跌，是牛市还是熊市我们不知道，但是如果市场崩溃，通常是最好的投资时机。

——我一向强调我对大部分事情都一无所知，对大部分股票一无所知，对市场波动我就完全是搞不清楚。所以，我尽量少买股票，不要买那么多，尽量买自己熟悉的，不买自己不了解的。

——问：你觉得现在概率最大化的投资应该是怎么样？方三文：我觉得就是三个：一，做多互联网；二，做多中国；三，做多满足人的精神需求的东西。

——问：互联网企业投资，商业模式里最核心的东西看什么？方三文：看它满足了人的什么需求，它提供的东西能占有多大的市场份额，再看它能创造多少商业价值。

---------------------------------------------------

*以下为方三文关于互联网投资的几篇文章。

--------------------------



# 关于互联网公司投资的一些看法

2014年9月9日于长江商学院投资研究中心

简述：// @不明真相的群众2014年9月在长江商学院投资研究中心做了互联网投资的分享，他从优秀互联网公司的“自我实现”特征谈起，进而从行业，产品形态和盈利模式几个方面和大家探讨了优秀互联网公司的特征，最后还聊到了互联网公司的估值方法以及对一些具体公司的看法注：因记录和理解偏差，下文可能无法全面或准确反映方三文先生的观点，仅供参考。

## 一，互联网公司的“自我实现”特征

很多人认为投资互联网行业和价值投资的理念是相悖的，但实际上投资互联网行业的逻辑和价值投资的逻辑有深层的契合。

【例子】传统产业，即便以巴菲特的最爱可口可乐为例，可口可乐可以凭借其品牌，规模优势等建立竞争优势和护城河，但也无法对百事可乐形成压倒性的优势，因为作为一个消费者，我们不会因为其他人都喝可口可乐，我们喝百事可乐而在口感的获得上有任何的受损，但是在大部分自由市场，谷歌，脸谱对其竞争对手可以形成毁灭性的竞争优势，占据90％以上的市场份额，垄断程度远超很多传统产业的领先公司，为什么？

因为互联网的优势公司，一般除了具备传统领先企业的品牌，技术等优势，还有一个优势可以称作“自我实现”的属性，白话说就是：越多人用越好用，越好用越多人用，这使得竞争优势不断扩大。这一点是可口可乐都做不到的。进一步，为什么会产生“越多人用越好用”的特点？

1.一些互联网产品有社会关系沉淀的特点，比如QQ，微信，脸谱，在沉淀旧有的社会关系的同时，还会发展新的社会关系，使社会关系越来越稳固，这是非常强的锁定用户的功能。

2.一些互联网产品会形成大量的用户数据积累，比如搜索引擎，收录的网页越多，则搜索的效果越好，并形成循环式的正向激励。

3.一些互联网产品有大量的用户创造内容（UGC），这在本质上是用户在网站上抵押了“虚拟资产”，用户抵押的“虚拟资产”越多，就越离不开这个平台。

如果具备上述特征，则这种互联网产品就有“自我实现，自我强化”的特点，进而有潜力形成长久的竞争优势，最后体现在定价权上（高毛利率）。（腾讯，百度，谷歌，Facebook的）。如果能找到这样的产品，可能无法像传统产业一样去具体估值，但从根本上讲，是不是契合价值投资的理念呢？

## 二，三个角度理解互联网公司：行业，产品形态，商业（盈利）模式

以上述的思路，具体而言，什么样的互联网公司会有“自我实现”的特征从而获得竞争优势呢？可以从三个角度去考察和理解：这家公司是否拥有好的行业处境？是否是好的产品形态？是否是好的商业模式？

1.行业的选择可能是三个角度里面最重要的一个互联网产业里“好的行业”一般具有以下的特征：

潜在的用户规模巨大

普适市场总体比细分市场要好，当然，普适市场现在一般都有不可撼动的巨头。

市场处于增长期

终身/高频/高客单价需求

从这个角度，交友的商业模式（终生）比结婚相关的行业要“好”（世纪佳缘）;商务游比休闲旅游的市场要“好”（频度高）;如果是非终生，低频的行业，那么需要客单价要高（搜房，汽车之家）。同时具备这三点要求是很难的，如果具备两点一般就是有潜力的行业。

【例子】反例是网上卖书，这是典型的低频（比大家想像的要低很多），低客单价（而且价格是相对透明的---印在书的后面，缺乏定价权）的行业;当然，图书作为第一代电子商务的交易标的，因为是高标准化产品，在电商发展的初期，图书是一个消费者容易信任和选择的切入点，但上述低频，低客单价的问题一直存在。亚马逊后来的变化也和发现这个问题有关，所以首先切入了电子出版，甩掉了出版商环节，获得部分定价权，提高毛利率，但规模还是太小，所以进入百货，云计算等领域。但是当当因为本质上是个零售公司而不是互联网基因公司，所以很遗憾没能切入以互联网为核心的电子出版领域（相反，以起点中文网为代表的网上文学网站实质上成功进入了电子出版的市场），当当现在也开始做百货品类了，但时机有些迟了，竞争对手非常强大。

2.产品形态从产品形态的角度讲，有交互和开放性的产品形态总体上更好;以用户而非流量来衡量的产品形态更好，以UGC取代竞价排名为特征的产品更好;以个性取代共性的产品形态更好，有长尾商业价值的产品形态更好。

交互和开放性。交互和开发性更容易实现上述的“自我实现”功能。

用户而非流量。用户一般不但点击了内容，还生成了内容，甚至把“虚拟的家”安在了网站上，它带来了价值要远大于传统的流量。教资会取代竞价排名。UGC（用户生产信息）不光是在数量上，甚至在质量上，对信息质量带来了深刻的突破。

【例子】新华社（生产内容）每天制作的新闻约1000条，新浪网每天转载5至10万条新闻，而新浪微博（UGC用户生产），每天是千万量级的信息产生。数量上的优势比较容易理解，质量上的优势可能很多人未必认同，以新闻报道为例，用户多维度贡献的信息，特别是当事人都站出来贡献信息的时候，这种信息的质量，对事实还原的程度。往往超过优秀的记者。所以新浪微博的价值远高于新浪网，汽车之家的价值远高于一家在线汽车媒体。

个性取代共性。用户接收的信息是可定制的。可以更好满足用户的需求。

【例子】在进行广告活动中，定位的精准度可获得数量级的提升。根据雪球的经验，根据用户的个性化设置来推送广告，点击率提高10倍。

长尾商业价值。最典型的是百度，谷歌。

3.商业模式总结而言：离交易越近越容易挣钱，挣销售预算的钱优于挣市场预算的钱。

阿里巴巴从用户或者流量的角度衡量，在中国并不是最大的，但是阿里巴巴离交易是最近的，能挣到最多的钱;微博从产品形态上很好，但离交易太远。

挣销售预算远远优于市场预算，因为市场预算在公司里是最容易被砍掉的，但销售预算在越困难的时候是越不能砍掉的。形象地说，新浪网页展示广告的预算是可以被砍掉的，百度上广告是不能砍掉的，在天猫店的广告就更不能砍掉了。

那么同一种形态下何种盈利模式更优？

用户直接付费优于客户转化。典型例子：游戏直接向用户收费不需要客户转化，是“效率最高”的。一个一万人在线的游戏就可以支撑一个好的游戏团队;一个10万人在线的游戏可以支撑一个上市公司。

核心业务收费优于增值服务收费。提供什么类型的服务就在这方面收费是最优的例子：奇虎主要提供安全产品却不能从安全产品收费，而在增值服务上收费，这样转化链条就稍长。

交易佣金优于收广告费。搜房现在的尝试。

效果广告优于品牌广告。谷歌百度的广告和展示广告相比。

## 三，估值

1，对于互联网公司，用户的重要性高于营收，营收的重要性高于利润。

2，因为互联网行业的公司用传统方式估值是很难得，有个切入点可是以估总体市场的贵贱：比如在互联网行业的低潮期买入，在行业的狂欢期卖出。

3，对于某一个细分领域看好，比如电商，又看不清楚最终的竞争格局，可采取组合买入和再平衡的方法。

四，具体公司讨论

百度：在2012年时点上比较看好百度，基于上述的理由（如自我强化和长尾效应等）（注：讨论用的PPT是2012做的，所以回顾了当时对一些公司的看法）。

腾讯：在2012年的时候认为腾讯的商业模式有问题，一个是因为带来最大营收的游戏和QQ的绑定没那么强，这个问题现在依然存在;一个是移动互联网的冲击，但这个问题现在不存在了，因为腾讯通过微信逆天地抓住了移动互联网的机会。

潜在的平台公司

奇虎：商业模式的问题：收入的转化链条有些长，从浏览器到导航网站到搜索这个转化链条的衰减率会比较高。

微博：目前讨论的东西主要是国家大事，离商业价值有点远（核心业务收费优于增值服务收费），另外用户的增长有放缓的担忧。

垂直领域的平台公司

大众点评：。错过了好时机，本来最有条件做好团购业务，却被美团占了先机大众点评从点评入手，美团直接从交易入手。在接入交易的环节，美团的执行能力很强。（团购只是一种形式，本质是帮餐饮企业实现电商化）（当交流和交易融合的时候，社区的价值就会爆发）

搜房：核心问题是未来房地产成交量的问题，搜房在新房交易上的优势比在二手房交易上的优势要强;对搜房形成威胁的可能不是乐居这类模式，而是新出现的能够对交易接入更深的模式。

唯品会：服装库存问题是永远存在的，作为高毛利，低成本又有很强时令属性的服装，必然存在库存问题;同时，中国有非常大的贫富差距，地区差距，导致市场非常大。唯品会从一开始设计商业模式就决定了它的命运。大部分人对电商的理解是把线下的东西搬到线上来卖，但是线上卖货的门槛更低，导致竞争更激烈，大家挣不到钱。唯品会的思路和他们不一样，利用时尚差异，地区差异解决了三四线城市年轻女性的需求，同时解决了服装商的问题。唯品会对奥特莱斯的模式有深刻的理解。


---------------

# 不明真相的群众：老二非死不可

投资互联网的逻辑 2012

首先我是第一个演讲嘉宾，方三文，雪球创办人，今天我给大家演讲的主题是“老二非死不可——投资互联网的逻辑”。

什么叫老二“非死不可”？相信大部分人都认为自己是价值投资者，价值投资者有个鼻祖，昨晚刚刚给大家写了封信的巴菲特老先生，巴菲特老先生投资过很多公司，但他有个“洁癖”，不投资互联网公司，他也有自己的理由阐释：第一，他不懂互联网公司；第二，他不理解互联网公司的“护城河”是什么。

我也是一个巴菲特的信徒，但我认为在这个事情上我们的看法和老巴有所不同，我认为互联网公司是这个世界上最好的价值投资标地，我们应该投资互联网公司。为什么呢？投资互联网公司的理由主要就是三个：

第一，互联网公司的行业规模超出人的想象，是行业集中度非常高的行业；第二，互联网公司注定是高利润行业，利润高到什么程度呢？以前我们有个标语“抢劫不如去炒股”，2007年大牛市时大家说的，我们可以给这句话接一句，“贩毒不如投互联网公司”，别的行业的毛利润有个20、30，大家就觉得很好了，但如果互联网公司的毛利润低于50%，大概你都不好意思说自己是互联网公司；第三，互联网公司实际上有非常深和宽的“护城河”，接下来我会向大家反映。

$Facebook(FB)$，即将IPO的美国互联网公司，用户规模现在是8.5亿，下面是中国人熟悉的QQ，目前它的用户是7.11亿。可以说，有商业史以来，用户规模达到这个量级的公司和产品是非常少见的，大的规模当然意味着公司发展空间非常大。

首先是讲利润率的问题。我认为利润率由三个因素决定：规模效应、自有用户比例、转化效率。讲规模效应，互联网公司注定有大规模的特点，但它也有不同于其它行业的特点，互联网公司在扩张过程中，规模效应特别明显，当它的用户和营收以倍数增长时，互联网公司投入的增长速度远远低于它营收的增长；

第二，真正的互联网公司的营销和推广基本是靠用户口碑传播，成本是很低的。这个特点和另外一个行业比一下就会很明显，沃尔玛是传统商业的巨无霸，它每开一家商场都要投入相应的地产、物业，它的营收增长和投入增长是平行的，但互联网一定是交叉线，成本如果是这样的，它的营收和用户增长一定是远远超过，一旦互联网投资突破这个交叉点，它就进入到了暴利时代；传统商业基本每获得一个用户都需要付出成本，但真正的互联网公司因为拥有自己海量的自有用户，它的每个用户是可以重复使用的，也就是说，当互联网公司有了自己的海量自有用户之后，它的用户成本基本接近于0。

这些海量用户如何转化成为公司创造价值的商业用户？因为互联网技术的提升，其转化率正在不停提高，转化率每提高一次，就意味着公司利润的上升。我们来看是什么决定了转化率。

首先决定转化率的就是网站内容和交易关系，对应关系越好，转化关系就越好。来看三个网站：新浪、搜房、汽车之家。大家认为新浪的转化率高还是汽车之家的转化率高？（汽车之家），因为汽车之家的内容和销售这个行业的对应关系是好的，而新浪的内容和对应的交易关系差；

再看搜房，转化率也是很高的，去年搜房的广告收入大概22亿左右。新浪作为一个老牌互联网公司，用户量远超搜房的公司，去年的广告收入也是25亿，这就可以看出行业对应带来的转化率的提高。

比这种对应体效率更高的是单个链接的转化，类似于新浪、搜房、汽车之家，它的对应是泛整个的对应，但像百度、谷歌，它可以用关键词建立内容和广告之间的关系，所以转化率有了质的提升，像新浪这种千万用户量级的网站，它的广告收入是20多亿，去年百度有140亿（的收入）。

除了关键词对应，提高转化率之外，还有一个大家经常忽略的转化因素：时间上的对应，也许你知道用户需要某一类广告，但你很难知道他什么时候需要广告，这就是FaceBook和谷歌的区别。

2011年，谷歌的收入是350亿美元，FaceBook的收入是40亿美元，营收方面的差距是非常大的，它们的广告从本质上来说相似，都是关键词匹配的广告，不同处在于，谷歌广告出现在用户有搜索行为时，它知道用户什么时候需要广告，把广告送到它面前，所以转化率很高；FaceBook也许能猜到用户需要什么广告，但它不知道用户什么时候需要，所以目前为止它的转化率是低的。

除了对应关系，还有一个非常重要的提高转化率的东西：效果是否可以衡量。做广告销售的人都知道，说服客户的成本是很高的，如果你的效果不可衡量，你就要花大量成本，包括自己的时间、经济上的利益，付出这些来说服客户，但如果你的效果可以衡量，你说服客户的成本会一下下降，客户数量会增加得非常多，这也是传统门户网站和搜索引擎非常重要的区别。

除了效果之外还有一个规律，交易业绩转化率越高，最典型的就是淘宝，淘宝去年的广告收入大概是89亿人民币，已经非常接近百度了，它的用户其实是离百度很远的，这是因为离交易比较近带来的转化率的提升。

接下来我们讲互联网公司的“护城河”是怎么形成的：

互联网的护城河主要来自于用户反复访问这个网站带来的用户黏性，黏性是怎么形成的呢？我们可以分解一下，我认为大概分成三部分：

第一部分，因为网站拥有相对独特的功能和体验，使用户反复访问。如果用户反复访问，这个用户就变成了你的自有用户，这是形成用户黏性的第一个基石。

第二个基石，因为有互动，网站里形成了用户关系。大家知道，我们很难离开类似于QQ这样的即时通讯软件，最重要的原因是我们的朋友都在里面，我们因为交互形成了互动关系。再比如说，我们很难离开微博这个产品，其实是因为微博帮我们认识了很多新的朋友，我们很难离开这个关系，从此可以得出结论，对于互联网来说，2.0永远是优于1.0的。

第三个形成用户关系黏性非常重要的东西就是UGC，UGC是什么？用户创造内容。用户可以写一篇文章、发一条留言、上传一张照片。当用户创造的内容到了一定程度后，其本质上是把自己的虚拟资产放到了网站上，本质上是抵押了这个东西，重复访问网站的可能性**提升，这就是UGC形成的虚拟资产抵押效应，大家也容易得出，UGC网站的用户黏性高于传统网站。

这三个因素形成了用户黏性，同时我们可以看到，第二、第三个因素会决定，越多人用的网站越好用，最后会形成的格局是垄断，从商业角度来说“垄断”是最好的词，因为竞争是利润的敌人，巴菲特最喜欢垄断，这个世界上垄断程度最高的就是互联网公司，我们看看这些公司形成的垄断地位。

谷歌在美国的市场地位大概是多少？（80%），在欧洲的市场份额（90%多），这就是谷歌的垄断；FaceBook在社交领域的垄断大概到什么程度？淘宝在中国电子商务领域的垄断程度大概是多少？（80%）；百度在中国搜索领域的垄断程度是多少？（78%）；QQ在中国的IM领域垄断程度是多少？（90%）；新浪微博在微博领域的垄断比例是多少？对此大家有争议，但按用户生产内容的比和用户耗费的时间，现在大概是70%几。垄断带来的行业集约化的程度都超过绝大多数传统行业的公司，垄断会带来什么？高利润，所以结论是什么？真正的互联网公司一定是垄断的，垄断带来的结果就是老二没有前途，非死不可。这就是我今天演讲的主题。

作为投资来说我们要干什么？要投资老二非死不可的行业里的老大，所以互联网公司最适合价值投资。

我们怎样选择互联网公司？其实大家可以去拓展自己的思维，我觉得有一点要澄清，按我刚才这么说的，要投资什么好象已经说出来了，其实不是这样，刚才这只是一个最宽泛行业里的公司，还有很多隐型行业的隐型冠军，只要他在这个行业形成垄断，都会有非常好的利润率和“护城河”，在选择公司时大家可以一个个地问这些问题。

首先，这个行业/公司是否对应足够的用户需求；

这个公司的用户是买的还是自有的？

大家可以看互联网公司的报表，如果一家互联网公司的营销成本里有一项巨大付出是流量获取成本，那这个公司的用户是买来的。

接下来要看这家公司是否拥有垄断地位？垄断地位如何形成，可以看这家公司？提供的功能和体验是否有独特性还可以看这家公司提供的主要是互动体验还是单向浏览？刚才说了，互动体验是优于单向浏览的。还要看网站内容是用户原创还是来自第三方，有没有独占性？还可以看这个公司用户的转化方式是什么，是传统的付费广告、按点击付费还是根据成交的效果付费。

我们可以试着用这些标准看看这些公司。门户网站新浪、搜索百度、视频优酷、网络游戏盛大游戏、B2C1号店、电商平台淘宝、品牌电商凡客、社交新浪微博。我没办法一一展开，但可以简单看一下。

视频网站的内容是自由的吗？B2C电商的用户是自由的吗？网络游戏能否做到强者很强、一家垄断？大家可以顺着这个东西问下去，这就是今天我给大家带来的我对互联网公司投资逻辑的理解。

谢谢大家

---------------

# 地上没有天国—再谈雪球的社区秩序维护

来自不明真相的群众的雪球原创专栏

作为雪球的创始人，我相信我比大多数人更珍惜雪球的一切，它的用户，它的品牌，它独特的味道。。。

所以，每次看到用户投诉受到“不文明语言“或者“低素质用户“的困扰，要退出雪球，我都感到深深的遗憾。我是多么希望雪球用户个个都素质高雅，动机纯洁；我是多么希望每条发言都事实确凿，逻辑严密，语言文明。

可是当用户建议加强对“用户素质“的筛选，对“不文明语言“的监管时，我都没有作出积极的反应。

为什么？我之前写过一个短文回应，网页链接，因为行文不太文明，效果并不好。

现在我就更直白地说一下这个事情吧：

我从来不觉得雪球有能力去识别鉴定用户素质、用户动机，从而设置准入门槛。如果一个人或者机构宣称自己有这个能力和权力，还是，挺可怕的。

即便在单一个案中相对容易有结论的“语言文明“，个案一多，也不容易有清晰的可执行标准。我在释老毛的贴子后留言说“你确定自己在投资吗“？这语言文明吗？我是在骂人吗？释老毛也许不以为忤，换个人可能要投诉我对他冷嘲热讽人身攻击了。

那么雪球是不是对社区秩序就不做任何事情了？

非也：

1,无异议的无价值信息，比如垃圾广告，及时清理。

2,以个性化的产品设计，解决不同用户个人喜好的差异。比如，用户可以限制自己贴子的评论者资格，只允许特定的人（比如自己关注的人）评论；用户可以管理自己的关注名单，确保只获取自己认可的用户发布的信息；用户可以管理自己贴子的跟贴，删除自己不喜欢的回复；用户可以拉黑自己不喜欢的用户，以屏蔽他们发布的信息；用户可以组建和参加特定的群组，只和自己认可的人交流。

3,关于人身攻击和“不文明语言“，雪球提供举报功能，接到举报才处理，当然处理结果未必一定完全满足举报者的诉求。

除这些之外雪球不会更积极地介入社区秩序的管理。

我理解用户希望雪球通过积极监管能营造更好的秩序，但以互联网内外的实践来看，监管起的作用都是有限的，有时候甚至会走向反面。与此相比，我更相信用户个性化的选择和自由社区具备的自我净化能力。参差多态本是社会真实的一面，雪球会尽力做好能做的一切，但是地上没有天国，大家还是生活在真实而不完美的世界里吧

--------------------------

# 雪球CEO方三文：我对长视频、短视频、直播类公司的看法

2018.内容来源于界面采访

最近，中概股中最大的新闻毋庸置疑就是中国最大的互联网视频网站之一爱奇艺的美股上市了。今年，视频类公司越发强势，不断刷新我们投资者的眼球，雪球一直对视频行业给予高度关注，今天我分别从视频行业的发展过程、用户需求、行业优势、商业模式、市场体量等几个角度来谈谈我对视频行业的理解。

视频公司商业模式演进史

视频行业最早时候鼻祖是YouTube，最早是搞短视频的，短视频主要由用户拍摄上传，叫UGC。这个事情为什么YouTube能搞起来？美国在录像机时代就有拍搞笑短视频的习惯，很多人喜欢搞这个，等于是有一批创作者，然后就搞起来了。

传入中国以后，大家最开始时也想搞这个，之后发现碰上了问题：

1、并没有那么多拍摄者上传视频。你想，用摄像机、DV拍，拍了回去剪辑，这本身就是一个门槛很高的事情；

2、视频千奇百怪，当时互联网上成立的商业模式是在上面放贴片广告，这个不成立，因为没有厂商愿意在一个品相不可控的视频上放广告。

所以上传视频需求和硬件条件不存在，二是贴片广告不成立，这让整个行业陷入了困顿，陷入困顿后大家找出路，最后得出的结论，只有长视频的用户需求和商业模式才是成立的。所谓用户需求，用户最大的需求是看电视剧，在电视剧里放贴片广告，在电视台已经验证无数次了，只要搬过来就OK，所以大家纷纷搞长视频，贴片广告的商业模式。

搞了以后，用户需求没错了，但又碰上两个问题。因为长视频的供应方很有限，很长一段时间做长视频的公司比供应商还多，那样会导致价格倒挂，你去求着人家拍给你，采购成本很高。而且用户随着产品走，没有任何一家说我能够把所有的剧买下来，如果你不能把所有剧买下来，客户就乱跑，你买了这个剧的时候人家来这儿看，没有这个剧的时候人家不来这儿看，这就变成了一个简单的商业，我有钱的时候买一个东西，火了，卖了点广告，一算毛利是亏的，卖广告的钱还不够买版权的。

然后大家就陷入到了非常大的困境里，最主要的问题是没有任何一家能把所有视频全买光，这样的肯定最厉害，它有定价权，但没有任何一家能做到，最后就陷入了旷日持久的消耗。需求在那里，客户确实有需求，但你又消灭不了竞争，这样导致行业持续亏损，又因为有用户需求在，持续融资。

就在这个过程中又发生了两个事儿：

1、手机取代了PC。这大概是2010年之后的事情，手机取代PC成为用户主要的（终端），无论是发、拍还是看；同时网速有了巨大提升，这时候发现用户拍短视频上传比过去用DV拍下来剪辑上传，便利性提升了一万倍，因为（终端）发生了变化。

2、这个过程中发生了信息流广告，不是贴片广告，而是信息流广告，往里掺广告，你不要把它贴在短视频后面，以及直播这种商业模式。结果短视频这个东西又全部冒出来了，短视频和长视频有巨大的区别，短视频是依赖于所有用户的上传，而不是少数供应商，所有用户上传的目的就是要别的人看到，所以这个地方就存在一种规模效应，如果你能做到最大，其实本质上你是可以消灭竞争的，相比长视频有巨大的优势，或者短视频有一定程度上的规模效应或垄断效应了，这个过程中就崛起了快手和后来的抖音，我觉得只有快手和抖音上用户足够多，才会有更多人看，以及后面的商业模式——多人打赏，两个东西都形成了规模效应，结果短视频弯道超车，又杀回来了，而且最后它的商业模式比长视频好得多。现在长视频做得最优秀的爱奇艺也很痛苦，快手、抖音好得很。所以这个行业就是这样。

短视频为何能够崛起

回过头来说短视频为什么现在会崛起，主要原因在于短视频是人类社会到目前为止门槛最低的媒介。我们从媒介属性上来对比下文字、电影与短视频：

首先是文字这种媒介，中国还有很多人不识字呢，短视频看得懂吧？很多人看不懂文字，更多人是没耐心看，写一篇500字以上的文字有几个人有耐心看？没人看。

其次电影这种媒介，要下决心看一部2个小时以上的电影对大家都是一个非常大的挑战。首先你要下决心，第二你得老老实实在那儿坐两个小时，大部分人没这个耐心。

短视频的好处有：首先，视频这个媒介谁都看得懂，没有门槛；第二，随时随地可以看，退出机制非常灵活，所以它一下子就成了人类社会上目前为止门槛最低的媒介，这样就一下带来了用户需求的爆炸。全国电影一年500亿的票房，我们以25元一张票来算，全国人看了多少场电影？这样算下来几亿人一年大概看了两部电影。但我看短视频可一年不知道要看多少啊，所以这是一个爆炸。

点播是在这个基础上的业务模式，目前看不出任何迹象大家会不点播、不打赏了，看见好看的打赏一下，这是人类社会几千年以来从来没消失过的事情，大哥，小姐，唱一个，唱得好就打赏一个，这不是今天才有的，几千年来一直有。这是一个消费降级。

直播红利期并未结束

直播非常大地依赖于手机，手机取代电脑终端以及浏览终端，它有规模效应，因为只有越多主播才有越多观众，越多观众就有越多主播，这时候有了规模效应，规模效应的意思是它能够通过规模消灭竞争，所以做直播的公司，YY、陌陌，包括现在的快手也做直播，挣得盆满钵满。回头看已经上市的YY和陌陌一直在增长，快手和抖音也一直在增长。类似于UGC的快手、抖音这种平台，发展都是持续性的。直播本身是个工具，但直播上形成商业模式的就会是一个平台，关于它们背后的商业模式，打赏是最好的方式。

这里有一个特例映客，映客相关资料显示核心数据在下滑，但这个不是直播这个行业的问题，而是它用户获取方式的问题。映客没有自己获取客户的办法，它的客户都是靠投放去买的，这样的商业模式有个巨大的问题，你没有客户，要靠投放去买，如果要投放购买客户，你就必须得有卖点，通过广告获取，卖点只能是少数的明星主播，但直播这个模式一旦走入少数明星主播的模式，你的平台就完蛋了，因为头部主播要把大部分钱拿走。

另外直播这个东西只有完全长尾化，有无数的主播来了，这个平台才有价值，这是它自身商业模式的问题，企业的问题，和这个行业没有关系。反过来看同样是秀场直播的陌陌，它对头部主播的依赖非常小。大部分房间，你自己去陌陌上看，大部分房间平时同时在线人数只有百来号人，以前的快手，平均主播收入是多少？10块钱。极其长尾化，它通过长尾化达到了一个效果：用户需求也是千奇百怪的，你搞不清楚用户会喜欢什么，所以要通过无数人来生产，通过算法的匹配达到多样化，同时直播这个业务的本质其实是陪聊，并不是歌唱得多好听、舞跳得多好，本质上是Ta跟你聊天，但聊天这个东西一定只有长尾化的主播才可以，如果我的聊天里有10万人，我怎么聊？聊不了，只有我的房间里100个人，我就可以聊，然后可能有10个8个的聊得比较深，这样才是能够持续运行的生态。

跟斗鱼、虎牙这种偏游戏直播不同，游戏直播的问题在于它是头部化的。如果是头部化的话，平台就比较难挣钱。秀场直播有可能凭借用户后续实现垄断，至少是规模效应。

另外对于行业政策风险，我认为风险很小。姑娘唱个歌，小伙子打个赏，这是很健康的娱乐。除了一些个案，总体上来说这个事情不伤风败俗，没有社会危害性，很健康的。

打赏商业模式优于广告商业模式

广告这个商业模式跟打赏相比根本没法儿比，广告的意思是什么呢？

首先，违背客户的意图。我要看这个姑娘唱歌，你过来说奥迪汽车好，这本身跟我的意图冲突；

第二，转化率低。希望在转变场景下影响我的购买决策，今天你给我放汽车广告，也许我今年并不想买汽车，明年后年才买，你指望这个时候就改变我的投资决策，你说这个转化率有多低？

所以，最好的商业模式就是你提供服务，对这个服务打赏，你看用户付费模式，一款10万人同时在线的游戏就可以支撑一个上市公司，但一个10万人浏览的媒体没啥价值，两个商业模式的价值完全不在一个层次上，需要转换场景的广告是最差的商业模式。

反过来看上市公司的报表，YY从2012年上市到现在，年年增长，后劲很足。

短视频与直播平台不存在直接竞争

短视频平台和直播平台之间不太存在竞争，直播平台本质上是陪聊，而短视频主要是看，这个事情还是不一样的，但短视频平台它也可以做直播。整体上他们之间竞争不明显，总体上是一个新增的巨大的增量市场，大家各自做各自的。

另外这两个行业相比，短视频更大。因为聊是有门槛的，首先你不知道咋跟人家聊，第二人家不一定跟你聊，所以有门槛，看是没有任何门槛的。

快手的DAU是1.2亿左右，抖音的DAU也接近1个亿，下面的直播平台，像陌陌、YY大概都是一千多两千万，差别还是比较大的，但直播是直接的商业模式，而短视频并不是直接的商业模式，需要在上面加信息流广告，所以可以认为短视频是一个更大的东西。

2018


------------------
# 独家访谈雪球创始人方三文：三大维度对比国内互联网巨头投资价值

聪明投资者发布时间：18-04-2618:34

“腾讯最大的价值是满足最多人、最基础的需求，最大的问题就是它太强大”；

“阿里的商业价值已经发掘得比较充分了，它现在做得很多的新布局或者投资，说实话我不是非常理解”；

“网易商业价值提升的核心逻辑是什么？是游戏从电脑上到了手机上，你们的理解都是错的。”

四天前，“聪明投资者”独家访谈雪球创始人及CEO方三文，听他分析对比了腾讯、阿里、百度、网易这些互联网巨头的商业模式与投资价值。

43岁的方三文，人称“方丈”，自称“不明真相的群众”，主业陪聊，副业陪“赌”。

他曾经是南方周末记者、网易副总编，现在是投资社交平台雪球的创始人，并在雪球上募集了私募产品——雷石价值基金，也是一个私募管理人。

作为文人、投资人、企业经营者，他最喜欢雪球用户的身份。他把自己在雪球陪聊、陪“赌”中碰撞出的干货集结成书，《您厉害，您赚得多》销量超好。

作为互联网企业的创始人和经营者，方三文与“聪明投资者”畅谈近三个小时，说起雪球的现在和未来，概括了互联网投资最核心的三个要点。

他复盘自己最成功的投资——新浪、奇虎、微博，还有亏得最惨的富士康、聚美优品、盛大。

在盛大的投资失误中，他总结：“所有搞这种复杂的战略的公司通常都是不行的，千万不要投资”，以至后来一眼看穿 “表演得太用力了”的贾跃亭，乐视一股没买。

腾讯是“方丈”最早入手的港股之一，一路加仓，除了自己擅长的互联网领域，“方丈”的仓位里始终还有茅台、招商银行、好未来、特斯拉。

方三文说，自己不喜欢有规范、装饰过的文章，而是真实记录的干货，我们直接上对话：

回答“你是一个什么样的投资人”

1，聪明投资者：你是一个什么样的投资人？

方三文：一个投资人要长期在市场上挣钱，必须基于三个认知，就是他的自我认知、市场认知和对公司的认知。

我的自我认知和对市场的认知，可能超过大多数人，我在对具体的公司行业认知方面，优势比较有限。

2，聪明投资者：你对市场的认知是怎样的？

方三文：我对市场的认知是这样的，市场波动基本上非常难以掌握，但是可以事后利用。明天股票是涨是跌，是牛市还是熊市我们不知道，但是如果市场崩溃，通常是最好的投资时机。

10，聪明投资者：你从A股到投资美股用了多少时间？

方三文：2007年不是A股涨得非常高了嘛，我就看同样的股票，比如科龙电器，当时港股只有几毛钱，A股有几块钱，差不多十倍的差价。

我觉得按道理应该去买便宜的才对，当时我还特别想买腾讯，也是在港股，所以我想应该开个港股账户。

再后来2008年底市场崩溃了嘛，当时跌得特别厉害的是美股，我买了不少美股，我特别记得我在1块钱的时候买了好多花旗银行。

11，聪明投资者：你当时不是还在网易吗？

方三文：我在网易，但是我没买网易。

12，聪明投资者：为什么？

方三文：说不清楚。

13，聪明投资者：所以你最早到港股开户，买的是腾讯？

方三文：当时我买了三只股票，腾讯、中石油、比亚迪。

腾讯我认为公司产品很好，QQ非常厉害。腾讯买的时候应该是拆股前的二十几块钱，相当于现在4块钱左右。

然后买比亚迪呢，是当时我觉得汽车这个行业很好，但是A股上市的汽车行业全部是国企，我不太喜欢国企。我觉得如果有民营企业来搞，应该能搞的比较好，当时就找了比亚迪。

然后就是中石油，中石油不是说巴菲特挣了很多钱是吧？当时我看好像也还比较便宜，我买的时候应该是8块钱左右。

16，聪明投资者：在所有投资大师里，你最欣赏巴菲特？你认为巴菲特是一个什么样的人？

方三文：对。我认为巴菲特对投资有发自内心的兴趣，而且能够理解投资的本质。

17，聪明投资者：你觉得自己在这两点做得怎么样？

方三文：我觉得我做得还行。

回答“怎么评判投资能力？”

18，聪明投资者：你怎么选股？

方三文：商业模式是好的，产品是我能够了解的，治理结构是还行的，我会有个股票池，我会关注这个股票，平时会收到大量关于这个股票的评论，慢慢积累到我觉得这支股票是可以买的。目前价格不理想，我就等，市场经常会发生波动，有时候个股会发生激烈下挫。我会判断它激烈下挫的因素是不是根本性的？如果不是，我就喜欢用这种机会买入。

19，聪明投资者：你的股票池里大概关注了多少只股票？

方三文：100多只吧。

21，聪明投资者：你会做调研吗？

方三文：我基本上很少因为投资目的专门跑去调研。但是我投资的公司里面好多CEO甚至在我做基金之前很多年就是朋友，我平时也跟他们聊天或者什么，当然，没套内幕消息。

22，聪明投资者：一百只都是传统所理解的白马股吗，还是也有一些黑马股？

方三文：都有，比如说我最近有关注两支新股票，一只叫做大悦城，这个公司这几年在开发商业地产方面是取得非连续性的成功的，估值也不算贵。

我现在最关心的就是这种运营商业地产的能力到底是不是可持续的，我现在还没有答案。它现在市盈率14倍左右，将来比如跌到10倍，也许我会去买。

28，聪明投资者：有没有想过多做一些产品？

方三文：没有必要啊，一个策略一个产品你搞一辈子，规模可以扩大。

29，聪明投资者：你这个策略没有容量限制？

方三文：没有。很多人在小资金的时候，因为运气挣了一笔钱，然后因为业绩好规模扩大了，最后运气均值回归以后，他说自己是因为资金规模大了导致的亏损，其实根本不是，其实他本来就没有投资能力。

30，聪明投资者：怎么评判投资能力？

方三文：最后从结果上来讲是长期的超额收益。如果还要做得更细一点的话，就是他投资上获得的收益和他当初的动机比较匹配。

不卖腾讯和再买茅台的逻辑

31，聪明投资者：你在组合管理上有什么经验？

方三文：广种薄收，就是要在尽可能大的市场上选，比如说A股、港股、美股；然后选少的，你确定是优秀的，你有了解的；最后组合的构建上面，尽量考虑一些非相关性可能好一点。

32，聪明投资者：但你其实相关性是高的。

方三文：对，这东西你只能尽量去追求嘛，你也不可能为非相关性而非相关性。

33，聪明投资者：你买了很多互联网，是不是可以理解为它更偏行业主题基金？

方三文：我的组合里互联网占的比例是很大，但是也有其他的配置，比如说我的仓位里面始终都有茅台，有招商银行，有好未来，有特斯拉。

34，聪明投资者：现在大家都在买腾讯茅台这些股票，怎么看得出你的水平比我高？

方三文：我告诉你，首先你不一定会买，第二买了你拿不住。

35，聪明投资者：你是一直拿到现在？

方三文：对。

36，聪明投资者：有加仓吗？

方三文：有加仓，因为钱会越来越多。

37，聪明投资者：现在这个时间点给你一笔钱，你还是会去买？

方三文：会买。

38，聪明投资者：茅台也会买？

方三文：茅台也会买。

39，聪明投资者：不会觉得太高吗？

方三文：不会觉得太高，为什么太高呢？股票贵不贵和它过去涨了多少没有任何关系，只和它将来能挣多少钱有关系。茅台去年挣了270个亿，现在大概8000来亿市值，30倍的市盈率。但是去年年底茅台才宣布批发价上涨，2018年是它第一次享受全面上涨，所以今年利润有可能超过400个亿，你觉得贵吗？而且正常来说，茅台每年有10-15%的提价以及10-15%的扩产，你只吃这个就行了。要说它便宜说不上，但你要说它贵，也不对，可能比很多东西还便宜呢。

40，聪明投资者：如果只能买一家公司，你会买哪家？

方三文：我现在还真说不清楚。

41，聪明投资者：你做过的投资，有哪些从来不卖出的？

方三文：大部分都不卖出，我的基金运营才不到半年。

42，聪明投资者：个人投资呢？

方三文：那卖出的多了去了，我买过民生银行，买过中国国航，买过江淮汽车，不知道多少年前都卖掉了，再买过花旗银行、分众传媒，我在美国的时候就买过，然后退市卖掉。

43，聪明投资者：什么时候会卖出？

方三文：主要来说就是搞错了。理论上来讲，我都是追求不需要卖的。 但如果极度高估，有可能要卖出，但即便是高估，卖出也是非常非常困难。

“我从不care什么市场的玩法”

44，聪明投资者：你每天在雪球上花大量时间，获得各种信息，会不会觉得有的时候是噪音？

方三文：是安静还是噪音取决于你自己，别人信息的价值，最后也取决于你自己有没有使用的能力，如果你指望别人都给你提供好的信息，那信息就没有价值。

45，聪明投资者：你有没有想过筛选雪球上的信息？

方三文：谁能够筛选呢？谁有资格筛选？用什么标准筛选？

46，聪明投资者：所以你把它交给用户，自己去决定关注谁？

方三文：是，只有这样才能解决。我不认为除了我自己之外，有别人能帮我筛选信息，鉴定信息的好坏。我认为这个东西太可怕了，我对他一点都不信任。

47，聪明投资者：你在雪球上关注一个人，是出于投资的需要，还是做运维雪球的需要？

方三文：投资的需要。

48，聪明投资者：你觉得自己在互联网体系里处于什么位置？

方三文：我认为自己没什么过人之处，所以我从来不会去装高明或者装大神。

我一向强调我对大部分事情都一无所知，对大部分股票一无所知，对市场波动我就完全是搞不清楚。

所以，我尽量少买股票，不要买那么多，尽量买自己熟悉的，不买自己不了解的。

49，聪明投资者：在雪球上跟人交流的时候，有没有发觉自己对所买的7到10只股票是无知的？

方三文：你说的对，经常会发现自己是错的。一种是发现你的认识是不全面的，就是别人补了你。另外一种是发现你是错的，是推翻了是吧？那如果是推翻了，那你必须纠正错误。

50，聪明投资者：有没有什么时候被雪球告诉说，你错了？

方三文：有一次非常大的，但也不能说是我错了。2015年初酝酿过一个事情，叫做中概股回归。我是多年的中概投资者，我对这个事情是非常赞同，我说无论是政府的意志，还是投资者的需求，大家都觉得这个事情是最合理的。所以后来有一段时间证监会已经出了一个东西，我都还说这可能只是短时间的，最后应该是搞的，我说它应该符合各个层面的利益，但最后这个事情就没搞成，我不知道怎么回事。

51，聪明投资者：现在它们是真的要回来了，你会去买吗？

方三文：那也看价格，如果明明比美国价格贵很多，我为什么去买？

52，聪明投资者：但不同的市场玩法不一样？

方三文：我从来不care什么市场的玩法。

53，聪明投资者：比如当年港股和A股倒挂很多年，一直是倒挂。

方三文：那我也喜欢倒挂。只要有便宜的，我也愿意买便宜的。我从来不会去期待，我这个东西在一个独特的市场环境下，可以高价卖给别人，我认为那个东西是非常难以猜测。

54，聪明投资者：但你看它在A股暴涨，在港股就是不涨。

方三文：我不在乎。首先我赚得是公司增长的钱，股价不涨，净资产在涨，利润在涨，我急什么？公司增长的钱，是我愿意赚的。

第二，公司出现市场错误，被错误地低估了，这个钱也是我愿意去赚的，只有一种钱是我不愿去赚，或者说我认为赚不着的，就是说接下来会有什么行情，这个东西能够以很高的价格卖给一个不知道的人，这个钱我认为我是没有本事的，所以我不挣这个钱。

55，聪明投资者：现在的你，跟2006年入市的时候有些什么变化？

方三文：投资理念方面变化不大，但是对具体的公司和行业的认识会有比较大的变化，应该说，现在的我比过去更加保守和计较。

过去我买过很多股票，其实挣了很多钱，比如说我在2009年春天，我一块钱买了很多花旗银行，现在回头看，我可能就不会去买。

因为我对花旗银行的了解还远远不够。我当时总体上是以一个博反弹的态度去买花旗银行。但是我现在认为，在这种有可能会破产的企业上博反弹是不对的。当时真正应该做的事应该去买标普500指数。

56，聪明投资者：这些其实都是后视镜。

方三文：没错。但是大部分人的后视镜是希望回到一个自己利益最大化的地方去，我的后视镜还是回到一个概率最大化的方向去。

“方丈”最中意和肯定不会买的是？

57，聪明投资者：你觉得现在概率最大化的投资应该是怎么样？

方三文：我觉得就是三个：一，做多互联网；二，做多中国；三，做多满足人的精神需求的东西。

58，聪明投资者：互联网是比较大的概念，BAT（百度、阿里、腾讯）市值都已经大到有点让人觉得恐怖，你在里面倾向于哪一类型？

方三文：现在公司的市值确实是过去的公司所没有达到过的，但是你得看，现在这些公司产品覆盖的用户范围，覆盖我们生活的深度，以及它创造的利润规模，都是过去的公司所没有达到的。从这个角度来说，你就不会觉得它有多么可怕。

比如说，Facebook今年如果挣250亿美金，市值4000多亿美金。你说可怕吗？一点都不可怕，其实就是一个蓝筹股。

我觉得没有必要把公司分成大公司和小公司，还是讲商业增长的确定性，这个是我最看中。

59，聪明投资者：互联网企业投资，商业模式里最核心的东西看什么？

方三文：看它满足了人的什么需求，它提供的东西能占有多大的市场份额，再看它能创造多少商业价值。

60，聪明投资者：从这三个角度，比较阿里腾讯和网易，你怎么看它们的价值？

方三文：那显然啊，腾讯满足最多人、最基础的需求，人未必要玩游戏，未必要电商上买东西，但人一定需要跟人沟通，所以在满足需求方面，它的土壤更加深厚，满足的用户数量也比其他两家大很多。第三，它在商业上或许跟阿里差不多，因为电商直接指向交易，创造的利润要多，所以总体上它们的利润体量差不多。但我觉得，腾讯满足的用户需求还有一些冗余，阿里的商业价值已经发掘得比较充分了。

61，聪明投资者：BAT不同的商业模式，你更看好哪一家？

方三文：现在肯定是A和T比较有优势，B面临的问题核心是用户行为的变化，就是搜索占用户行为的权重大大的下降，新的行为是刷，在刷这个事情上它占的比较低。

62，聪明投资者：A（阿里）和T（腾讯）里面，你对T更看好？

方三文：也不能说是更看好，可能我更容易理解吧，因为T的基础是社交，我自己也是深度用户，包括我自己也运营一个垂直的社交的公司。

而A呢，它电子商务的核心逻辑总体上我也是能理解的，但是它现在做得很多的新布局或者投资，说实话我不是非常理解。

比如说它去搞什么阿里大文娱，也许我外行，我觉得不太理解，那我保持一个谦卑的心态，我不理解就不买。不过，从最后结果来看，它确实搞得一般嘛。

63，聪明投资者：你觉得腾讯最大的价值是什么？风险是什么？

方三文：我觉得它最大的价值是提高了沟通的效率。沟通应该说是人最重要的永恒的需求，而它这方面提供了一个比过去任何产品都更好的满足，极大的提高效率，改进了体验，然后在这个基础上做人与内容、与服务的链接，对提高整个社会的效率都起了很大作用。

它最大的问题就是它太强大，强大得让人觉得可怕。理论上来讲，它要能全部做成，简直就是中国。一个东西太强大，强大到总是让人害怕，就违背我们的常识。

64，聪明投资者：你觉得现在雪球让人害怕吗？

方三文：雪球现在完全没到让人害怕的地步，但是现在有些人觉得挺害怕的，但是我觉得离可怕还远呢。

65，聪明投资者：网易是你最熟的一家公司，分析师们对网易的客群价值都蛮看好的？

方三文：这样的看法完全是错的。网易这几年股价涨得很好，我可以告诉你，你们所接触的什么考拉、严选，对网易的股价或者是商业价值的增加值是非常微乎其微的，几乎可以忽略不计。

网易商业价值提升的核心逻辑是什么？贡献它营收和利润的主要是游戏，而游戏是网易从2001年就开始做，为什么这几年会有一个爆发，就是它成功的从电脑转移到手机上面。

66，聪明投资者：考拉、严选虽然比重小，但用户增长很快，中高端群体的用户价值，符合消费升级概念？

方三文：如果基于这个东西去投资网易，一定是错误的。

赚最多和亏最惨的股票，各来三只

67，聪明投资者：你觉得自己做得最成功的投资是什么？

方三文：嗯，做过几笔比较成功的投资。

一个是在2011年，就是在微博开始起来的时候买新浪，当时的买入价格大概30多块钱，好像最低的一笔是20多块钱买，后来微博果然做起来。

后来应该是2013年左右，大概在13块钱左右买了很多奇虎，后来也是达到一百块钱左右。

再后来是2014年还是2015年的，也是大概13块钱左右买过很多微博。这些交易我都已经卖出了。

68，聪明投资者：哪一个赚了最多？

方三文：可能还是奇虎。涨幅比较大，持仓也比较重。

69，聪明投资者：当时为什么买奇虎？

方三文：奇虎非常搞笑，当时市场崩溃，就捡便宜的买。

当时智能手机刚起来，大家猜智能手机上的主要商业模式可能是应用市场。360也做了一个手机助手。

我觉得如果能成为应用的分发平台，本身是APP store，这个生意是很好的，奇虎做得起来非常快，眼看很好，这个是当时我买奇虎最主要的一个理由。

现在回头看，当时判断完全是错的，但还是赚到钱了，人经常可以因为错误判断而挣了很多钱。

70，聪明投资者：如果包括浮盈和已经兑现的投资，你最赚钱的是哪一笔？

方三文：腾讯，我去年光给香港特区政府缴税都交了好多。

71，聪明投资者：你最失败的投资是什么。

方三文：有两笔，一笔就是当初买了个富士康，这是2008年的事情。

最早我不是买了比亚迪嘛，后来我就拼命研究，发现富士康做得好得多，我觉得应该去买富士康，20块钱左右买的，股价最后跌到1.5元！

72，聪明投资者：买富士康是因为什么？

方三文：我发现它的代工业务做得比比亚迪好很多。在管理方面，富士康或者整个鸿海集团吧，应该是创造了世界奇迹！非常大规模的情况下，还有很高的管理效率。当时很多文章说富士康最残酷，但实际上深圳的这些工人是以进富士康为荣的。但市场变了，它原来主要客户是功能机，是诺基亚和摩托罗拉，被iPhone这个智能机搞死了，问题出在这。

技术升级和产品变迁高于企业的管理水平，当火车来了的时候，你说你的马车公司管理水平很高是没有意义的。

73，聪明投资者：现在再来看富士康，你怎么看？

方三文：还是不行。现在富士康的业务，摩托罗拉和诺基亚已经完全不灵了。它现在接的业务，比如小米的加工之类。我觉得郭台铭也还是很狡猾的，iPhone的装配就没有放在那个富士康里面，现在放在内地上市的富士康里面，最好的业务不拿进来，说明这公司还是有问题。

74，聪明投资者：所以你是到1块5毛钱斩仓的？

方三文：5块钱的时候卖掉。（仓位）还挺重的，亏了好多钱。

75，聪明投资者：另一个失败的教训是什么？

方三文：后来买了一个聚美优品，这个甚至到现在为止，我都有点困惑。

聚美优品原来做的化妆品电商，它有一定市场份额，按道理也能挣点钱，但是现在公司连财报都不发了，高层管理人员几乎全部流失了，怎么会这样呢，我也搞不清楚什么问题。

76，聪明投资者：你什么时候把聚美优品卖了？

方三文：宣布私有化之后，7块钱左右。

77，聪明投资者：多少钱买的？

方三文：18到20块钱，我记不清楚，比腰斩还不止，脚斩，膝盖斩。

再跟你说一个我认为选股上非常大的失误，就是我曾经买过不少盛大，现在看来完全错误。

这两年贾跃亭风头比较盛，所谓生态化。但我告诉你，最早搞生态化就是陈天桥。陈天桥当时那个生态发展体系也把我吸引住的，太坑爹了，根本没搞成。

桥哥这家伙深藏不露是吧？他也不喜欢抛头露面，所以很有迷惑性。贾跃亭呢，用力过猛，所以我们现在道行不是很深，但也能看出来不行。

现在回头看，当时买盛大，就是他搞什么从文学影视旅游游戏什么，就是跟贾跃亭搞的那个想法是一模一样的！

所以我得出一个教训，所有搞这种复杂战略的公司一般都是不行，千万不要投资。

78，聪明投资者：现在市场上还有哪些企业有这种特质？

方三文：不说也罢了。我觉得无论企业家还是企业，能力是非常有限的，搞很多业务本身就是高估自己，还希望很多业务之间有协同效应，那更是扯淡。反正我对协同效应不怎么看好。

79，聪明投资者：你爱的腾讯，现在业务范围也很广？

方三文：不一样啊，它那个东西是有用户需求以后才搞的，不是说我买回一堆东西把它拼起来。事实上我们从来没有买过一股乐视，我判断它拼不起来。

80，聪明投资者：你只做二级市场投资，不做一级市场投资？

方三文：实话实说，我也投过一些天使项目，都是投我朋友做的，但说不上是投资。那哥们说我要创业，要不你帮一点？那行，我说要多少钱，我也搞不太清楚，就给他了，不是个严肃的投资。天使投资按道理就是这样的，投你认识的人嘛。

81，聪明投资者：你会投哪些什么样的人？

方三文：我比较熟，跟他比较要好的人。

82，聪明投资者：你要好的人一般都是什么人？

方三文：相对都是理性的。

原来你是这样的雪球

83，聪明投资者：报道说，你出来创业是因为焦虑，现在还焦虑吗？为什么？

方三文：唉，焦虑是始终伴随你的，人活着就会焦虑，只有死了才不焦虑！

84，聪明投资者：你现在焦虑什么？

方三文：公司面临的问题就是体量不够，这个不是最大的压力吗？

85，聪明投资者：雪球的体量目标是什么？

方三文：我觉得，做一个东西啊，最好在那个领域内占了50%以上的市场份额。

86，聪明投资者：现在雪球用户多少？

方三文：现在有2000万，日活是一百多万。

87，聪明投资者：你已经达到了，四千万股民，你已经有两千万了。

方三文：但是日活没达到。所以还有距离，所以还焦虑。

88，聪明投资者：雪球的护城河是什么？

方三文：可以说现在没什么护城河。如果说虚点的话，就是我们这个团队对这个领域的用户需求的理解能力，以及产品上满足需求的能力。但这个说起来有点虚，说了你也不信啊。

89，聪明投资者：给2000万雪球用户画像的话，会是什么样的？

方三文：比较活跃的这帮人就是重度炒股爱好者，通常男性为主，中年，30到35岁，对投资有比较强的兴趣，聚集在一线城市为主，北京、上海、深圳、杭州，有一定的比例是金融从业人员，但还是有很多是个人投资。

92，聪明投资者：这些私募如果出了问题，雪球扮演什么角色？

方三文：不承担任何责任，管理人不对亏损承担任何责任，而且承诺收益也是监管部门严厉禁止的。我们要做到的就是产品是合规的，业务流程是合规的，对合规承担责任。

93，聪明投资者：你的规模是最高的吗？

方三文：不是，前五都不一定排的上，最高的应该有7个多亿的人民币，那个人是做套利。

94，聪明投资者：你的客户跟一般私募的客户有什么不一样？

方三文：我的客户现在基本上都是我的雪球粉丝，我天天跟他们聊天，他们大概知道我是怎样的人，怎么投资，甚至我的持仓占比他们都知道。

95，聪明投资者：雪球整个团队架构是什么样的？

方三文：有社区业务团队，大概有四五十个人，还有交易业务团队，加起来应该五六十人。不同业务有几个分类，每个团队里面包括技术开发的，商业运营的。

96，聪明投资者：雪球暂时没有计划上市？

方三文：对。基本上商业体量得足够大才去上市，现在我们觉得还不够。

97，聪明投资者：雪球创业八年，有遇到过比较大的危机或者痛苦嘛？

方三文：肯定是有，经历的这个危机，现在不能披露。

98，聪明投资者：现在跟之前比，你觉得雪球有什么变化？

方三文：现在基本上结构已经比较完整，基本上不需要在业务方向上进行大的拓展。接下来就是数量和质量的问题，在每个架构里面，质量和数量还有非常大的提升空间。

99，聪明投资者：一句话来描述雪球的愿景，应该是什么？

方三文：把交流和交易整合在一起的一个投资平台，交流解决用户的决策问题，交易解决他的执行问题。

100，聪明投资者：雪球将来会成为一个怎么样的企业？

方三文：就是现在这个样子，金融投资的社交加电商，社交获客服务客户，电商实现交易闭环。

“现在说不上成功，但是应该会成功”

101，聪明投资者：在你投资企业里面，你认为谁最有企业家气质？

方三文：两个人是我现在认为的最优秀的企业家，一个是马化腾，还有一个就是扎克伯格。

他们有这几个特征，一个，就是能力还是很强的。第二，情绪非常稳定，在内敛和开放之间把握的比较好。战略眼光非常的毒，执行力也很强，但又不过分张扬。你看扎克伯格在美国国会上作证的视频，你会觉得这个人真是个非常人。我觉得随便拎一个中国的企业家去做这个事情，很少能做到。

104，聪明投资者：你自己是一个什么样的企业家？

方三文：我是一个能力比较平庸的企业家，现在说不上成功，但是应该会成功。

105，聪明投资者：你觉得什么是成功？

方三文：产品创造了足够大的确定性的用户价值，足够多的用户因为使用你的产品，获得了效率上的提升，体验上的提升，企业也获得商业价值。

106，聪明投资者：雪球算成功吗？

方三文：还谈不上成功，现在体量还不够大，创造的商业价值也还不够大。

107，聪明投资者：文人，投资人，企业家这三个角色让你选，你更喜欢哪个？

方三文：我最喜欢雪球用户的身份，可以发帖，可以在上面管理自己的基金。

108，聪明投资者：投资人和企业家这两个角色，哪个对你的挑战更大？

方三文：企业家的角色挑战更大。真正的企业家，不但应该有战略的眼光，而且也是一个很勤奋的人，有非常强的管理能力、执行力的人，我觉得我在这方面能力是比较差的。

“质疑人是一种非常罕见的能力”

109，聪明投资者：你会用什么词评价自己？

方三文：理性。

110，聪明投资者：投资风格呢？

方三文：现在还真说不好。

111，聪明投资者：有没有问过自己，方三文是谁？

方三文：没有，从来没有。

112，聪明投资者：你觉得最重要的事情是什么？

方三文：让自己有成就感。

113，聪明投资者：工作之外有什么爱好？

方三文：有点喜欢户外。

114，聪明投资者：你觉得自己管理情绪的能力怎么样？

方三文：我觉得比一般人强点，我大部分时候还是比较平静。

115，聪明投资者：什么事会戳到你的愤怒点？

方三文：我就恨别人不讲理，我就很生气的。

116，聪明投资者：用什么方式管理情绪？

方三文：过一会就好了，熬呗。

117，聪明投资者：推荐两本书吧。

方三文：有一本书我看了很多遍，不是著名的书，叫做《客厅里的绅士》，我很喜欢的，跟投资也没啥关系，但是经常夜深人静就会非常愿意去看。

118，聪明投资者：媒体的经历，对你现在做投资是否有帮助？

方三文：有帮助，我是逻辑爱好者，把这个应用到经济领域，其实跟我在南方周末的工作经历有关，那时候我比较喜欢跟经济部记者一起混，打下不少基础。

119，聪明投资者：记者通常喜欢质疑，不太容易相信别人，喜欢求证。

方三文：其实不一定，很多记者去采访哪个CEO，就崇拜哪个CEO。质疑人是一种非常罕见的能力，这很难的，尤其对方社会地位，财富、名望高于你的时候，大部分人是没法质疑的。

120，聪明投资者：你现在也有财富地位了，和做记者的时候看成功者，有什么不同？

方三文：我在这方面是跟人不一样，我一开始就很喜欢质疑。

讲一个笑话，我认识一个朋友在媒体圈，名气非常大，他去见哪个CEO，回来就买他家的股票，我经常是见了一个CEO，回来把股票卖了。但这个话我不敢再说了，因为以后有可能人家不愿意见我。

-------方三文毕业于北京大学中文系，1997年加入《南方周末》，后来待过些其他媒体，2005年至2010年担任网易副总编辑，2010年创办雪球，在2012年《财富》公布的“中国40位40岁以下的商界精英”榜单中排名30。

