---
title: Why can’t Europe create its own Facebook, Apple, Netflix, or Google? Here’s
  what Europeans think
author: James Pethokoukis
date: '2021-09-02'
slug: '296'
categories:
  - Translation Articles
tags:
  - Economics
---

[Source](https://www.aei.org/technology-and-innovation/why-cant-europe-create-its-own/)

April 25, 2016

Europe is big, wealthy, and well-educated. It’s where the Industrial Revolution and Great Enrichment began. So how come it’s having so much trouble generating fast-growing technology companies?


Here is Sequoia Capital’s Michael Moritz in the [Financial Times](https://www.ft.com/content/6425979e-07b0-11e6-9b51-0fb5e65703ce#comments):


>Over the past five years the eight most valuable technology companies developed in Europe have assembled a combined market value of around $32bn. That’s not a figure to be sneezed at any more than the admirable young European technology entrepreneurs who, despite all odds, are more inclined to take a risk than members of their parents’ generation. But EU legislators should be wondering why Europe’s eight most valuable companies are only worth about 10 per cent of Facebook or 6 per cent of Google.


Indeed, a [study](https://www.aei.org/economics/why-does-the-us-generate-more-fast-growing-tech-startups-than-europe/#.VaEPcGR9IQo.twitter) last year found that the cumulative value of all European billion-dollar tech startups, or unicorns, created since 2000 is around $120bn. (Facebook currently has a market capitalization of about $320 billion.)

Also in the FT, a new report finds that Britain has the largest number of non-US technology start-ups “but many are failing to grow far beyond that stage.” One reason cited was the low-level of venture capital funding:

>Between 2010 and 2014, about 40 per cent more early stage businesses in the US received venture capital funding than did so in the UK, when the number of companies was adjusted for differences in gross domestic product. Those US start-ups that did receive funding also received more than three times as much money on average as their British counterparts during the same period.


What do FT readers think about Europe’s unicorn shortage? (I wrote a similar piece about a year ago.) Some interesting (unedited) personal comments on the Moritz piece from European readers (note the number of mentions about culture):

“Stuffed to the gills with talented people with plenty of ability and ideas.  Let down by lack of enlightened investment, painful (near corrupt) board level management and government that hasn’t changed since the 60s.  Where are the exits for high tech in Europe? No exits = no investments.”


“Yes indeed Europe’s biggest enemy is its own unprecedented bureaucracy whose sole purpose it is to keep the status quo in the respective membership countries uniquely isolated from the other membership states and collectively the world. There exists a common platform with common laws, rules and regulations, but largely to keep others out, rather than focus to compete on the international front, both for individuals, companies and institutions! I am a Dutchman (proudly) but unfortunately living in a world where the politicians have branded everybody that earns more than them a ‘graaier’, greedy! A most unfortunate attitude, because these are the same people that draft the laws, rules and regulations! Respect for creativity, entrepreneurship, individualism, success  are alien concepts to the European bureaucratic machinery.”

”I would like to add another: the EU is [a] free trade area for manufactured goods but NOT for services, I think that’s a key reason why the likes of Google and Facebook have blossomed in the US, but similar companies have not formed in Europe. The markets in Europe are just too fragmented and restricted to support such innovation. The European consumers however are still very receptive of said innovations, as is clearly demonstrated by their take up of Google and Facebook products, products that can be shipped to us at near zero cost to the maker. We cannot be surprised by the market dominance of single suppliers under these circumstances. Yes the issue of that dominance needs to be addressed but the best way to do that is to encourage innovation in Europe NOT to stifle the innovator. Even China has its incumbent competitors to these behemoths, Baidu, Tencent Alibaba etc, again thats because these companies can operate freely across the whole of China.  Mr Moritz is asking a deep and troubling question for Europe, maybe Brexit will prompt the EU to get its head out of the sand and concentrate a little more on the service economy and a little less on Airbus’s and BMW’s.”

“One point I think may have been left out – the willing / eagerness of American consumers and businesses to try out and buy new technologies, compared to Europeans.  Even in this case, “tech hubs” can play a role. Soon after the iPhone was released and “apps” just becoming popular, I went to a tech conference hosted by our website provider, during which the head of the website designer / hoster declared in a speech that iPhone apps were a fad, and pointless.  I told my account rep that nevertheless, being only 150 miles from Silicon Valley, I thought apps were the future and I wanted  one for our site. Her response: “All my California accounts want one.” Small example, but just one example.”

“The answer to this is quite simple.  1.) Institutional: No ‘startup hub’/zone exists in Europe. There are pockets of them but it fails to amount to something significant like Silicon Valley (Tech City in London, Silicon Fen in Cambridge, …). Can’t really take advantage of the ecosystem and tap into network effects if the infrastructure/institution isn’t there. Furthermore, high rents driving out talent. 2.) Culture. Lack of a risk-taking culture on both the tech entrepreneur’s part, and also the financiers. VC’s lack of an appetite in making big bets and investment into big ideas. Failures are seen as a ‘very bad thing’, rather than a shared learning experience. 3.) Capital. See above. VC’s lack of an appetite in making big bets and investment into big ideas means that it’s difficult to do funding.”


“Working for a small Silicon Valley company for 10+ years but being British and always having lived in the UK, I tend to agree with the author. We can come up with excuses but across Europe we simply don’t have the can-do attitude that is common in many West Coast organisations. We laugh at the idea of the American dream but I’m not sure most Europeans even have a dream …. do we?”

“All the excuses and envy simply stop us even beginning to understand what is wrong with the climate of innovation on this side of the Atlantic. Something clearly is. Start for instance by looking at patents on business processes. Normal in the USA but impossible here. Our IP thinking is locked into the Industrial revolution – when the world and value propositions are all about services!”


” If you have met your basic needs of food, clothes, housing and healthcare, why work?  I think this describes most Europeans that want a 35 hour week and 6 weeks of vacation a year.  Why achieve something new? Why would someone like Steve Jobs, dying of cancer, still work and produce something like an iPhone when he was worth $Billions (i.e., he satisfied his basic Maslow needs)?  Why does Bezos of Amazon keep doing new things like develop a rocket that lands on its tail and better Kindles?  He’s worth $Billions.  The answer is that they want to achieve something new and useful.  This is why America is exceptional.  We have achievers.  Europe is filled with people just happy with the status quo.”