---
title: 'whigzhou 微博 美帝 '
author: whigzhou
date: '2022-03-13'
slug: '422'
categories:
  - Translation Articles
tags:
  - Politics
---

1. 持续的资本与人口流入其实是盎格鲁第二帝国与盎格鲁第一帝国的关键区别，英帝始终是资本人员持续净流出的，美帝则相反，前者是扩散型帝国，后者则是虹吸型帝国，

更一般而言，可以19-20世纪之交的人口转型为分界，之前的帝国都是扩散型的，之后变成了虹吸型，

很明显，后发国家受益于虹吸型帝国的程度，远远不如扩散型帝国，后者向你输送资本，派送精英，建立制度，前者吸走你的资本和精英，而且也不是真的非常关心你的制度（除非你惹到他）// 日本是惹了人家，台韩占了冷战前线的便宜，美帝不得不关心一下 //@叶子疏:也并非纯然如此....日台韩都是吃了全套制度输出和技术资本的..... // 美帝的虹吸性质有两小段时间是例外，一是美西战争到一战之间，二是二战后二十年，这两个阶段他是扩散的，资本和人员都在输出，但国内政界精英对这种扩散始终是不情愿的，很勉强，可见未来也不会有另一轮扩散，


2. 我也不觉得他说的就是主要原因，只是媒体的这个变化（若是真的）本身挺有意思，大学当然是很疯了 //@慕容飞宇gg:我觉得主要还是大学的原因。现在美帝几乎所有的大学都左疯掉了。不只是学生，当年的左疯学生现在占据了几乎全部的大学文科教职和大学行政职位。


3. 别的不好说，比较肯定的是罗马尼亚会大受其益 ​

>俄乌战争

4. 有个例子很能说明鹅国人的战斗力，一战中一批捷克人组织了捷克军团，在鹅国和鹅军并肩作战，布尔什维克割命之后，突然成了丧家之犬，想转到法国战场继续战斗，可是波罗的海的港口都被封了，为了能走铁路绕道海参崴回欧洲，占领了西伯利亚两年多，横行无阻，一度还控制了帝国的黄金储备，


5. 许多古代帝国在军事上其实都不够强大，挡不住成功组织起来的游牧入侵者，他们更多是靠削弱内部敌人来维持的 //@whigzhou: 不都是，很多是被崛起的强敌打败的，宋，明，清，奥斯曼，印加，阿兹特克…… //@施工弦:大国都是失败都是内部问题。汉唐明清的都是如此。



6. 最近听到一些特别悲观的声音，包括 Charles Murray 和  Razib Khan，他们说的都有道理，目前美国很多情况确实很糟糕，而且在可见未来还会更糟糕，不过，虽然我同意他们说的那些具体问题，但总体上却并不像他们那么悲观，我是这么想的：

1）美国当前的问题是内生的，简单说就是精英圈自作孽，而不是竞争对手找到了什么更高明的路子，

2）这些自作孽其实是它自身成功的产物，可以说是富贵安逸病，所以，如果局势果真恶化到不再富贵安逸了，风向就会逆转，

3）联邦制，自下而上的结构，分立的势力，将使这种风向逆转更容易发生，过程也更为平缓自然，

4）逆转可能是缓慢曲折的，但也可能是迅速干脆的，促成后一种情况最有效因素就是战争，正如珍珠港带来的大逆转，二战前后美国社会的面貌截然不同，

5）所以，真正致命的危险将是：那场有望触发大逆转的战争确实来了，可是美国却输掉了，

6）如果这场战争在几年内爆发，不可能输，

7）但确实有这样一种可能：在相当长一段时间内，比如二三十年，美国的情况在持续恶化衰败，而敌人在不断壮大，但与此同时，敌人表现的非常和平友善，非常有耐心，直到其实力足以压倒盎格鲁联盟之后，才伸出爪牙，这才是最危险的场景，

8）依我看，这不会发生




7. 扇出系数和控制强度之间的关系在很多场合都可以观察到，比如军队，平时的扇出系数约为9，1个师9个团，1个团9个连，一上战场，扇出系数就降到3，否则很难指挥，再比如，1949-54年间，某振泉的行政层级有六级：中央-大区-省-行署-县-乡镇，扇出系数小于10，稳定下来后去掉了大区和行署，扇出系数升至20-3 //  以县的数量为例，1）长波段看，从汉至清，人口规模增加7倍，县数略同，2）越是乱世，县越多，3）每个寿命较长的王朝，开国时县多，越成熟越少，大致从1500降至1200 //@whigzhou: 地方镇虎萎缩是集泉帝国趋于成熟稳定之后的惯常表现，这也是它集泉成功的表征之一



8. 最近这次干预丝毫看不出风格转变的迹象，而不久前把库尔德人卖给土耳其的举动，则堪称disposable empire at its worst  //@whigzhou: 学总大概误解了我的意思，美国向来不缺干预热情，缺的是长期承诺，总是打完就撤，『绝不多留一天』，用Niall Ferguson的话说，美帝国是『用完即弃的一次性帝国



9. 奥巴马从就任伊始便再三誓言要从阿富汗撤军，然而很少有人注意到这样一个事实：正是从撤军前景开始明朗之际，阿富汗的恐怖活动和美军伤亡也开始急剧增加，而在此前，美军对阿富汗的控制其实相当有效且伤亡极低，这一模式在美国的海外干预中屡屡重现


10. 威武 //@学经济家 :真.美国开始暴露了。以前解释日本为何误判时讲过，日本决策者们没意识到一个基础事实，就是美国90%的信号是由那10%的人制造的，政客、媒体、知识分子和好莱坞娱乐圈等。所有铁证都表明美国人分裂严重贪生怕死，结果一戳之后自己被打出屎来。


11. 所以美式干预看起来都很爽，特别适合拍电影，导弹一通打，空降师胡乱往下抛，海豹突击队四处乱窜，整个过程以小时分钟计，然后总统站到镜头前宣布行动结束，士兵马上可以回家过节，三年后那地方比以前还乱，不过没事，大家早就忘了，电影看得开心就行～ ​


12. 巴希尔这次倒台有点像90年代的非洲的一些模式：冷战结束了，独裁者没了卢布美金，不得不搞点紧缩政策，最后把中产阶级逼跳反了。
苏丹的故事很像这个模式。曾经靠着石油出口收入，苏丹养了一个庞大公务部门以及围绕着公务部门的服务业。要是看纯收入，会发现苏丹出现了中产阶级。但认真看这些中产阶级的就业，你就会发现这个中产阶级完全是石油财政的产物。
这些吸附性中产阶级（姑且这么叫吧）政治态度保守，毕竟吃财政饭。只要巴希尔把他们喂饱，他们就能在城市里为政权提供支持。
转折点是2011年南苏丹独立，巴希尔一下少了三分之二的石油收入，瞬间财政入不敷出。能借的债也借了，宏观经济恶化严重，不搞结构性改革和紧缩看起来是要凉。
紧缩薅谁的羊毛呢？虽然暴力机构花掉了财政支出的百分之60到70，但这笔钱是保命钱，刀子不能动到他们头上。
那砍谁呢？砍老师，砍医生，砍公务员吧。先是通胀把拿工资的中产阶级搞得优越全无（不拿工资的底层在通胀面前反而好受点），去年12月取消燃油食品补贴，物价进一步上涨，中产更是觉得没活路了。
最后他们也被逼上街了 // 南苏丹独立后，掌握了政权和石油收入的丁卡人正在高效率清洗境内其他部落，想当年丁卡人若不是英国人及时干预差点被努尔人杀光，这回风水倒了过来。


13. 当危机来临，很可能*怎么着都是死*时，就会乐意博一博新路子，如果能有机会同时博几条新路子，那当然就更好了，这大概就是有性繁殖的最初动因 //@whigzhou: 是的，这一点从商业角度也很好理解：假如一切顺利，收益丰厚，那就何不原样重复做法呢，俗话说穷则思变


