---
title: 童年幸福，长大后迷惘的“好孩子”们
author: 陈赛
date: '2021-08-31'
slug: '280'
categories:
  - Translation Articles
tags:
  - Insights
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

[Source](https://mp.weixin.qq.com/s/rhBW1zt9VZleeeJcLWNxiQ?xueqiu_status_id=193483524&xueqiu_status_from_source=utl&xueqiu_status_source=statusdetail&xueqiu_private_from_source=0105)

>一个稚弱的孩子，如何长成一个健康、独立、有担当的成年人，不是通过清除他／她的成长过程中的一切障碍、挫折与痛苦，而是帮助他／她学会如何自己应对这些问题。只有在面对这些问题的过程中，才能激发一个孩子自我应对的“抗逆力”。


# “好孩子”的危险


在我的童年时代，成年人世界对于“好孩子”的标准只有三个：第一，成绩好；第二，听话；第三，不谈恋爱。

“成绩好”，是因为在那个时代，对普通家庭来说，这是唯一改变命运的方式。

当然，成绩好的孩子如果谈了恋爱，那也不再是“好孩子”。在那个集体禁欲的时代，我们的父母和社会竭力营造一种“无性”“干净”的环境。尤其到了青春期，我们的身体已经开始发育，性意识已经伴随着身体的发育开始觉醒，但对那时的我们来说，爱美是一件羞于启齿的事情，对身体的各种莫名尴尬与自卑则是青春期的普遍记忆。对于“性”的任何好奇心都是被禁止的。

我们从不谈论性，与任何人都不谈，就好像这件事情不存在一样。电视上偶尔看到搂搂抱抱甚至接吻的镜头，父母就会在我们彼此之间的心照不宣中把电视关掉。

还有，好孩子从不忤逆他们的父母。在我们的文化里，忤逆父母是不孝，是最大的恶。但现代心理学认为，对父母的暴力情绪在一个人的成长过程中是很自然的。尤其是在进入青春期的时候，孩子开始学习认知自我，探索和建立自己和他人以及世界之间的边界。当他们觉得自己的边界受到侵犯的时候，就会奋起保护自己的边界。



英国心理学家唐纳德·温尼科特（Donald Woods Winnicott）认为，一个孩子要想长大并发现自身本性中最深刻的部分，他的人生中必须有一个人能够包纳他所有的攻击性而仍然爱他。“童年的意义就在于能表达很多坏的情绪而不至于有什么恶果和报应。”


所以，温尼科特很怕“好孩子”，因为他们做一切大人认为他们应该做的事情，而这恰恰是问题所在——他们的“好”是一种必要，而非选择。


是的，我们应该为孩子创造一个安全的环境。但是过于强调儿童的“脆弱性”是另一种危险的倾向——它为成年人的过度干涉提供了借口。很多时候，我们对孩子安全问题的偏执，表面上是保护，实际上却构成了一种剥夺，剥夺孩子成长所需的正常而真实的环境。

在这一切焦虑、不安的背后，是一种对儿童深深的误解——孩子如瓷器一样脆弱，无可救药的愚蠢，无法从错误中学习，所以成年人的责任是保护他们远离一切风险，代价却是儿童自我发展的内在自由。

温尼科特欣赏，甚至为那些会对父母尖叫、从他们钱包里偷钱的青春期少年辩护。他认为，这些“问题行为”其实是一个孩子被好好爱过的证据。正因为被好好爱过，所以才敢于如此挑战成人世界。

他认为，这样的破坏对一个孩子来说有着重要的意义。如果父母无法容忍这种破坏，过早、过于严格地要求孩子的顺从，会导致一个“虚假自我”的出现——对外顺从、表面上很好但却压抑了自己的重要本能、无法平衡社会性与破坏性，无法产生真正的慷慨或爱，因为它不曾被允许充分探索自私与恨。

在他看来，那些没有创造性、沉闷枯槁的成年人，基本上都是在童年时期未曾被容许表现得像个真正的孩子，有孩子的一切黑暗情绪，包括嫉妒、贪婪、自私，但仍然被接纳、被爱。



至少在我的记忆里，18岁以前的人生几乎完全是按照父母的意愿活着的。很少自由地选择什么，因此也不会对自己负责任。


我至今记得，第一次离开家乡来北京读大学，第一次独自面对世界时是多么的惶惑与不安。但正是在那种惶惑不安的自由中，我才开始慢慢学着按自己内心的声音去探索世界，学着以自己内心的感受作为行为的依据，知道自己想要什么，不想要什么，想要什么如何争取，不想要什么如何拒绝……

---


# 过度升级的“保护”



20年过去了，我们关于“好孩子”的模型有了多大的变化呢？


我们仍然对“成绩”有偏执，尽管越来越多的证据显示，就孩子的成长而言，个性的塑造远比认知更重要。


越来越多的父母意识到，顺从并不是一种好的品质。顺从的孩子无法自己为自己思考，更容易受到同侪压力的影响，也容易成为有歹意的成年人的虐待。


但从另一个角度来说，在“安全”的名义下，今天的父母对孩子日常生活的监控、规划与隔离比起过去有过之而无不及。


20年前，如果一个妈妈每天送孩子去上学，会被当成神经病。但现在如果一个妈妈每天让孩子独自去上学，就会被老师和家长骂不负责任。


20年前一个孩子成长过程中很多被认为是“正常”的性格或行为，比如发脾气、孤独、愤怒、害羞、内向，如今都被一一病理化为“心理问题”，如“多动症”“情绪障碍”等等。


心理咨询师徐卓在一篇我们的约稿中（《树欲静而风不止》）回忆自己的童年：“我生长于70年代的北京，小时候生长环境自由，也时不时的有些孩子气的冲突，‘基本上一三五收拾别人，二四六被别人收拾，周日休息’。这些打打闹闹里面催生的‘人际技巧’或者‘冲突管理’能力，其实也是一种‘实践智慧’，譬如如何见机行事、怎样寻求帮助，何时需要暂避锋芒、何时应该虚张声势，对于成年之后进入社会有很大帮助。”


其实，这一代的父母对于孩子安全的焦虑与恐惧并非毫无道理，但文明就是适应一个又一个不怎么完美的境况，人生就是一个接一个的难题。一个稚弱的孩子，如何长成一个健康、独立、有担当的成年人，不是通过清除他／她的成长过程中的一切障碍、挫折与痛苦，而是帮助他学会如何自己应对这些问题。


就像身体的免疫系统，你得暴露在病原体之中，否则你的身体不会知道如何应对病菌的攻击。从心理上来说也一样，孩子需要暴露在适当的不适、失败与挣扎中，才能学会如何应对这些挫折，才能激发他们自我应对的“抗逆力”。


几年前《大西洋月刊》上有一篇长文《如何让你的孩子长成一个心理病人》（How to Land Your Child in Therapy），作者是一位从业多年的心理咨询师，也是一位母亲。她在她的来访者中发现一个奇怪的群体，他们明明有着十分幸福的童年，但成年后却觉得迷惘失落，有深深的空虚感。


比如其中一位20多岁的女性，她的人生拥有一切令人羡慕的元素：父慈母爱，有亲密的兄弟姐妹，也有关系很好的朋友，受过良好教育，健康良好，有很好的工作和公寓。也没有任何抑郁或者焦虑的家族遗传基因，但是她的痛苦是真实的——夜夜失眠，害怕犯错，无法信任自己的直觉，总觉得自己做得不够好，有一种“漂泊无依”感。


最后，这位心理咨询师将病因指向父母的“过度保护”，对于子女“幸福”的偏执性追求，他们尽一切努力不让自己的孩子体验到哪怕一点点不适、焦虑或者失望。当这些孩子长大之后，哪怕遭遇到人生中再正常不过的挫折与失望，也会有天塌下来的挫败感。



---


# 木匠，还是园丁？



那么，我们到底应该怎样爱我们的孩子？多少的爱、什么样的爱才是恰当的？父母的爱与孩子的自由之间，父母的保护与孩子的自主性之间，应该是一种什么样的关系？



在《园丁与木匠》中，艾莉森·戈普尼克，美国加州大学伯克利分校的发展心理学教授给出了一个很好的答案。


她认为，过去半个多世纪以来，美国的主流媒体上呈现的亲子关系是一种典型的木匠思维。木匠是什么？木匠是一种工作，是根据我的想法、我的品位、我的技术、我的蓝图，制造一张桌子、一把椅子，或者一个书架出来。无论你的成品是桌子、椅子、书架，它的优劣可以用来判断木匠的好坏。


主流媒体鼓吹的“育儿”（parenting）也一样——你有一个原材料，就是你的孩子，只要你足够努力，技术和专业过硬，你的作品就会是一个聪明、成功、幸福的大人。所以，主流文化中亲子关系的图像其实就是木匠和桌子。当然，这个画面背后是亿万美元的市场。


但在她的实验室里，最前沿的科学研究所呈现的亲子关系却是另外一幅图像——是一个关于园丁照顾花园的画面。


如果你是一个园丁，你就会知道，你可能在花园里忙了一天，汗流浃背，累得跟狗一样，就像那些一天下来觉得自己累得跟行尸走肉一样的父母，但那些花花草草没有一个地方是按你原来的心意长出来的。用中国人的话说，就是“有心栽花花不开，无心插柳柳成荫”。


为什么会这样？



这里面其实有很深刻的原因。因为园丁在种东西的时候，不是想着要种出最大的西红柿，或者最美的兰花，他创造的是一个生态系统，各种植物可以在里面共同生长，只要你保证土壤丰饶、空间安全，花花草草就能以各种你预料不到的方式自行应对环境的变化。就应对变化而言，花园远比西红柿大棚或者兰花温室要灵活得多。


戈普尼克认为，从进化生物学的角度来说，这就是人类童年的全部意义所在——创造和保护这种生态系统，在这个生态系统里，各种新奇的、怪异的、有趣的、难以预测的变化可以发生，孩子可以自由探索应对的方法，等他们长大以后，每一代人能做上一代人预料不到的事情。


所以，为人父母，不是工作，不是木匠做桌子，重要的不是技巧。为人父母，是园丁种花，其本质是爱。这种爱没有目标，没有蓝图，但它确实有一个目的。这个目的不是去改变我们爱的孩子，而是给予他们成长所需要的，一个安全、温暖、自由的环境，或者说，一个“花园”。在这个花园里，一个生命层层绽放，最终他／她会找到属于自己的那条路（即使那条路不是我们会为自己选择，或者为他们选择的），他／她会塑造自己的命运，他／她会成为一个独一无二的自己。


