---
title: 拉不低的成本
author: 方三文
date: '2022-02-04'
slug: '392'
categories:
  - Translation Articles
tags:
  - Investment
---

我有一位朋友，在48块钱的时候，买进了中石油。

他的想法当然是好的，听说这是全世界最赚钱的公司，而油又是每天要烧的，未必这股票不会涨到100块去？

可是股不遂人愿，开盘以后这股就一路下跌。这朋友很是心焦。

到股价跌到30块钱的时候，这位朋友再度买进中石油股票，他说这叫补仓，可以拉低之前48块钱的成本。

可是，30块买完之后，股价跌到20块。于是朋友再度补仓，想把30块钱买的成本也拉下来一点。

之后呢？之后中石油的股价跌到10块钱左右，现在还在那挣扎。

我们假设吧，这位朋友三次买的中石油是等量的，那么通过第一次补仓，每股成本从48降到了39，通过第二次补仓，每股成本从39降到了32。

想到自己的成本是32而不是48，这位朋友心里的感受，要好了一点，因为无论如何，他敢判断中石油的股价涨回32的可能性要远大于涨回48。

但是事实的情况可能恰好相反，因为两次补仓，他的亏损额是原来的将近一倍。如果他每次都买了10000股，第一次买了以后亏损是38万，因为采取了两次补仓行为，现在的亏损大概是66万。

如果亏损的投资是泥牛入海的话，补仓就是这么一回事：分明有一头牛已经淹死了，非要把另两头牛也淹个半死，心理才觉得爽一点。

当然，有人会说，如果中石油后来涨回48块，你又会说另一番事后诸葛亮的风凉话了。

是的，所以问题不在我们补不补仓，也没有必要去赌中石油到底会不会涨回48块钱。惟一应该反思的是，我们在中石油48块钱的时候，作出购买决策的理由是否成立。如果我们确信48块钱的中石油是有投资价值的，那么以低于这个价格的任何价格购买或者补仓都是对的。

但是，估计在48块钱购买中石油的绝大部分人，都只是隐隐约约听说中石油是世界上最赚钱的公司，连巴菲特都买了；只是隐隐约约觉得中石油股价会涨。但他们不愿意花多一点时间去搞明白巴菲特的中石油是1.9港币买的，12港币差不多卖光了；更不愿意花再花一点时间搞明白中石油现在的盈利状况、增长前景和股本回报。

我们看看中石油的业绩和它给投资者的回报吧。从2006年至2009年，中石油的每股收益分别是0.76，0.75，0.62，0.56。对于这样一家收益没有增长，但是“大而不能倒”的公司，最简单的估值办法是看分红。从2006至2009，中石油给股东的分红分别是0.357，0.362，0.281，0.254.应该说，中石油的分配还是蛮大方的。按中石油现在股价10.28算，10.28购买的资产，分红0.254元，分红回报是2.47%.当然如果把未分配利润也算上，总体回报是5.44%.而现在一年期固定存款利率是2.25%。那么，按现在的价格购买中石油，至少是比固定存款合算。但也是刚刚比固定存款合算，股价再高一点，也许就覆盖不了股市投资比固定存款的风险了。这也可以让我们看到，48块钱购买中石油的决策，无论用什么估值方法，都是盲目的。

所以说，补仓不是问题，但千万不要仅仅为了“拉低成本”补仓，而是要反思，购买决策的理由是否足够充分




