---
title: Do the Rich Pay Their Fair Share?
author: Lee Ohanian
date: '2020-11-01'
slug: '78'
categories:
  - Translation Articles
tags:
  - English
  - Welfare
---

[Source](https://www.youtube.com/watch?v=DnEe4oaSC88&pbjreload=101)

Here's a question you're likely to hear whenever the subject of taxes comes up: Do the rich pay their fair share? There are two parts to this question: Who is rich? And, what is fair? Let's start with who is rich: Nearly everyone assumes that a person who is among the top ten percent of all income earners qualifies as rich. But according to 2011 data, a top ten percent household makes around $150,000 or above in gross annual income -- that's income before deductions and taxes. Now, $150,000 is a nice living, but it certainly doesn't make you rich. OK, then. What about the top 5%? You get into this percentile if your household makes around $190,000 or above. That's a nice bump. But it hardly puts you in the rich category. How about the top 1%? That's $500,000 or above. A great income, but remember, most people only get to that level after many years of hard work and, quite possibly, the accumulation of serious debt to fund their education or build their business.

Of course, there are people who make more than $500,000. And there are some who make many millions, even billions. But the number who do is very small. Now, let's talk about fair. Fair would seem be that the group of taxpayers who earn 10% of the country's income would pay 10% of the country's taxes; the group who earned 20% would pay 20% of the taxes and so on. But what If I told you that, according to IRS data, the top 10% of all earners -- the people making $150,000 and above -- pay 71% of all federal income tax while earning only 43% of all income. If anything, the top ten percent pay more than their fair share.

So, as it happens, do the much reviled top 1%. They earn 17 percent of all income, but pay 37% of all federal income taxes. And what about those at the other end of the income scale, the lower earners? Are we squeezing them? Hardly. Those who make $45,000 or less, 47% of all earners, pay little and often no income taxes. Ah, but what about payroll taxes -- the money we pay to fund Social Security and Medicare? That takes a bigger bite of the paycheck of lower earners than higher earners. Isn't that unfair?

Consider two points:

First, it's misleading to call the Payroll Tax a tax. It's really an insurance payment that guarantees we receive social security and Medicare after we turn 65.

Second, the benefits we receive from Social Security are capped, no matter how much we have paid in. This means that the payroll taxes of high earners actually help subsidize the social security and Medicare benefits that low earners receive at retirement.

How do all these numbers stack up against other countries? The US income tax system is substantially more progressive - meaning that income tax rates rise as income rises -- than other advanced countries, including Germany and Sweden. So, if you think that our tax system is unfair because it coddles high earners, then you must conclude that tax systems in these other countries are even more unfair. So how high are tax rates on Americans today? Well, throw in federal tax increases mandated in 2013 and state taxes, and top earners face a tax rate of more than 50 per cent in California and New York. Other states like Maryland and Connecticut are not far behind.
Do you think a tax rate of greater than 50% is fair? If so, is there any rate that wouldn't be? Nobody is calling for bake sales for anyone in the top ten percent of earners. And no one wants to minimize the struggles of those at the lower income strata. But to say the "rich," however you might define them, don't pay their fair share is simply wrong.

Finally, numerous academic studies, including ones that I have done, show that when tax rates are too high, investment, risk taking by entrepreneurs, and therefore job creation all decline. And when that happens it's the poor who suffer, not the rich. The rich do fine. It may feel good to take even more money from the top ten percent, but it doesn't do good. And it sure isn't fair.