---
title: 职业女性是花瓶吗？
author: 末世前的宁静
date: '2021-06-27'
slug: '215'
categories:
  - Translation Articles
tags:
  - Propaganda
  - Sociology
---

[Source](https://www.zhihu.com/question/31212844/answer/418468061)



女拳泡沫彻底破裂之后，众多“现代知识女性”将命如草芥

先给结论：建议那些连二本都考不上的女高中生尽量不要去读三本和大专，而是早点结婚。哪怕能够考上较好的大学，也应该尽早规划婚姻大事。

高等教育是一个巨大的泡沫，学历攀比是一场军备竞赛。之所以泡沫可以长期维持不破裂，是因为现代社会生产力足够高，有本钱来玩这种内耗的游戏。对于一个男人来说，他必须工作，而要找一份还过得去的工作往往必须拥有学历这块“敲门砖”。因此哪怕明知大学里学不到工作所需的技能，也不得不花费巨大的金钱、时间和精力去获取那张求职“入场券”。然而由于长期的高校扩招，大学生数量早就泛滥成灾。因此用人单位普遍都青睐 985, 211 大学的文凭，普通一本也还管用，但是二本、三本甚至大专的文凭在市场上的接受度就很低了，求职很容易碰壁。因此个人建议，如果连二本都考不上，就尽量另找出路。虽然许多工作需要文凭，然而也有一些看上去不怎么“高大上”、前景和“钱景”却不错的工作对文凭的要求并不苛刻。不过如果是女生，还有一条非常不错的人生道路：做一个贤妻良母。

由于长期以来女拳主义控制新闻传媒、社科理论和书籍出版，垄断话语权，全社会都弥漫着女拳礼教的气息。吃人的女拳礼教培养了一大批人云亦云的所谓“现代知识女性”。她们都会用教科书式的语言和复读机式的腔调念念有词：“女男平等是大势所趋，女性社会地位会越来越高。现代女性知性独立，根本不需要依赖男性。经济独立，思想也独立，不再需要给男人做生育工具。男人都靠不住，女人也要有自己的事业。相夫教子的妇女都很 Low, 现代女性都应该努力工作，唯有事业才能让自己拥有迷人的风采。除非遇到真爱，我们根本不需要结婚，剩女都是因为太优秀而剩下……”

上述女拳论调完全黑白颠倒，因为所谓的“独立女性”实际上是“独立婊”、女拳寄生虫。可以注意到，满口“独立、知性”的“现代知识女性”哪怕过了四十岁，依然特别乐意他人称呼自己为“姑娘，妹纸，女孩，女生”，甚至特别喜欢如此自称。因为这些称谓可以用来装纯装嫩，进而获取性别优待。而倍受女拳婊鄙视的劳动妇女，普遍从小就善于操持各种家务活，她们却从不自称“女孩”。很显然，传统妇女比现代妇女独立多了。可是传统妇女都承认自己只是男人的配角，极度依赖男人的现代妇女反而厚颜无耻地标榜自身“顶起了半边天”。实际上，无论是体力劳动还是脑力劳动，男人都是顶梁柱。大多数社会财富是男人创造的，男人才是社会和家庭的脊梁。然而由于女尊男卑的舆论和政策，最终在分配上却让妇女比男人的收入更高。比如一个售楼小姐扭几下屁股，就可以日收入过万，然后去嘲笑那些那些埋头苦干的男人是“穷屌 Loser”.


许多薪资不错的女性工作岗位是经济泡沫的结果，许多职业女性其实就是一个花瓶。然而生产力提高的速度远远赶不上人类欲望膨胀的速度，任何经济泡沫都最终会破裂。虽然现在女拳泡沫尚未整体破裂，却早就露出了破裂的迹象。许多中小型民营企业都不愿意招聘女员工，哪怕愿意招收，薪水也不高。因为经济环境越来越不景气，中小型民企的经营压力越来越大，怎么可能养得起众多“现代知识女性”这种花瓶？当然诸如公务员、事业单位、国有企业，以及官僚性质的民企和外企依然可以养活一些花瓶，可惜那些职位数量非常有限，无法吸纳所有女大学生。随着经济下行趋势越来越明显，女大学生的就业形势会越来越严峻。

有智慧的年轻女性应该意识到所谓“女人的事业”完全是一场经济泡沫，等到经济萧条以及社会动荡之后许多妇女要独立养活自己会非常艰难。哪怕在泡沫破裂前储备好了许多房产和钱财，到动荡不安之时都会贬值得一文不值。真正可以抵抗经济萧条和社会动荡的是婚姻家庭，有可靠丈夫以及子女的妇女容易渡过未来的逆境。只要选对了伴侣，婚姻家庭是非常超值的投资。因此如果一个女高中生连二本都难以考上，还是尽早去寻找婚姻伴侣为上策。哪怕能够考上 211 以上的大学，也应当在大学期间认真规划婚姻大事。

所谓“奋斗，发展，打拼，梦想”都是资本主义的洗脑营销，让人们沉溺于小资产阶级情调之中。利令智昏，被消费主义洗脑的现代人普遍缺乏谦卑之心，缺乏对风险和苦难的认识。本来这是一件很容易想通的事情，然而由于“商品拜物教”的长期洗脑，被仇男教育毒害的众多现代女性已经彻底丧失了自知之明。