---
title: 总会起作用
author: Whigzhou
date: '2021-09-03'
slug: '297'
categories:
  - Translation Articles
tags:
  - Sociology
  - Investment
  - Economics
---



@海德沙龙 《[噩梦般的底特律教育系统](http://headsalon.org/archives/7270.html)》 底特律自70年代以来就在持续衰败，居民不断逃离，工厂和住宅区一个个沦为废墟，犯罪率攀至榜首，随之一起沦落的还有它的公立教育系统，学生大量流失，出勤率、毕业率和学习成绩快速下降，然而这些学校的开支却并未减少，它正在从一个教育机构变成教师救济所…

@whigzhou: 选择机制总会起作用，问题是在哪个层次上起作用，假如你阻止自由市场在个体和企业层次上起选择作用，那么其他选择机制便会在产业、组织、城市、地区、国家等层次上起作用。


自由国家自由度最高的行业最具有全球竞争力，如美国的 IT和好莱坞，日本和韩国的汽车，中国的中低端制造业和手机产业等，被左派和非自由竞争祸害的行业：中国的 IT、媒体、医药、石油、汽车（或许现在好一点了）等等，美国的汽车产业，欧洲的 IT 业。在任何层面上都可以用这个规律分析。

>外部强加的制度当然可以造成很大差别，这个以前说过很多了，现在我想强调的是，对于某些文化，某些族群，外部再怎么强加制度，可能都不会达到很好的状态，当然，正面外部力量可以让它避免最坏的状态（比如变成朝鲜）

>简单说，在所有拉丁社会中，波多黎各当然已经非常好了，再怎么说，因为有美国，它不会变成阿根廷，或委内瑞拉，或古巴，而我的意思是，它也不大会变成夏威夷，变成韩国，变成香港，论制度条件，英属/美属加勒比的条件再理想不过了，但并未冒出任何加勒比小龙

>再看以色列，不考虑文化/遗传因素的话，当初的条件真是恶劣到无以复加，建国者满脑子共产主义，沉重战争负担，重税，重管制，恶性通胀，啥坏事都摊上过，最后愣是给拗过来了。

>随着技术/文化/制度的丰满成熟，地理因素对社会间差异变得越来越无关，地理大发现以来，英国人无论到哪里都能建立起自由社会，德国人和日本人无论到哪个自由社会都会成为模范公民，犹太人和华人无论到哪个自由社会都比其他民族会挣钱……，换句话说：更成熟的文化与制度更有能力控制和适应各种环境。