---
title: 微言（18）
author: Guanghua Mao
date: '2021-12-25'
slug: '359'
categories:
  - Original Articles
tags:
  - Insights
---

1. 重要的是能力的提升，工资不重要，学历不重要，对社会有价值，自己有优势，积累有价值.

2. 不要因为一件事情是大众所知的高回报而去做，而是要自己认同、擅长且享受过程而去做。

3. 看了一些快乐男生海选的视频，不得不说，爱好和擅长很多情况下并不是一回事。

4. 互联网对社会的改造，是逐步进行的。
最初期的阶段，人们把传统的信息、服务型态，简单照搬到线上，比如说，门户网站是把传统的报纸电视搬到线上，网上黄页是把分类广告搬到线上。这个可以说是模拟互联网的时代。
在第二阶段，互联网对传统的信息、服务型态进行了拆解重组，比如说，即时通讯工具，开启了文字、语音、视频、同步、异步兼容的通讯方式，使人的通讯效率有了巨大的提升，搜索引擎把结构化的内容（比如书籍、论文、小说）拆解成独立的网页，使人获取信息的效率有了巨大的提升。
链接效率提升以后，因为传导机制变了，需求端能够比较高效地把需求传导给供应端，会产生对生产的改造。我们可以举个例子，比如说，用户需要内容，那么我们第一步把传统的内容搬到线上，但到一定阶段以后，有很多非传统内容生产者的用户，直接在网上生产内容，他们生产的内容，不但在数量上远远超过了传统的内容，而且在型态和审美趣味上极大的颠覆了传统的内容，从而提供了完全不一样的内容消费体验。再比如说，用户需要出行服务，开始我们可以在网上叫出租车，但是很快，很多非传统出租车的司机和车辆进入了这个行业，提供了和传统出租车完全不同的出行体验。
我觉得，互联网对生产端的改造，才刚刚开始。
在这个改造中，有很多公司会因为开创某种新型的产品或者服务而横空出世，比如快手、抖音，这个很难预测。
同时，还有一类公司会获益，比如通过提供最基础的用户服务，从而掌握用户入口的，它们可以成为任何新型产品、服务的入口，比如腾讯、Facebook；给新的产品、服务型态提供基础设施，比如云服务的，比如亚马逊、微软。


5. 看了一下乔布斯的视频，我发现只有去欧洲做电商了。要能够将自己的构思落地，工程能力和思维能力同样重要。

6. 一般来说量化交易指的是吃买单卖单的差价，好像最早是某个获诺贝尔奖的教授发现的，到后来进来吃差价的人实在太多了，变成了比计算速度的游戏，对速度渴求到要在交易所机房隔壁拉光纤。
最近一波量化交易赚大钱的是做比特币量化交易的（佩服聪明人的脑子），2017年据传最差的收益率是400%。


7. 对，往这个方向解释，逻辑上比较容易讲得通（往支付结算工具上讲总是讲不通的），合规上也讲得通，监管部门要是来刁难的话，就说：我拿我的钱，买一个“资产”你有什么权利管。。。//@想要进步的青年:回复@不明真相的群众:比特币的需求很大部分是基于对政府的不信任，这个需求好像会一直存在[吐血]可能还是刚需



8. 绝大多数人的职业生涯规划太差了，见了很多名校毕业的，工作了 10 年也就 1.5 万一个月，为社会创造价值，自己喜欢且擅长，积累有价值。好好规划自己的职业生涯是非常重要的。

9. 腾讯现在的问题不在乱，而在治，太想系统化地管理。所以我很赞成红衣大炮的说法，乱点好。//@不明真相的群众:回复@阳淼: 打破山头是完美主义，不现实也没有必要，硬要搞就是灾难。

10. 不追求完美，接受不完美。

11. 天才是人类的财富，家人的灾难，他们想明白这点，就不祸害人了。


12. 1、钱不够，怎么决策空间都有限，所以最重要的想办法增加收入。2、我觉得，现阶段买房最好把它当作消费而不是投资来看，消费要量力而行，过度消费，远超过流金流入的消费有可能带来的不是幸福，而是灾难。


13. 自认为愚蠢比自作聪明要好，自认为能力有限比自认为无所不能要好，接收残缺比接收完美好。

14. 世界复杂性和人类能力的局限性导致很难做到绝对可知，但通过螺旋的上升逐渐逼近可知。完全的可知论容易导致绝对的真理和权威，进而盲目的自负，无论对自己还是社会都会是巨大灾难。同时我也发现，很多人（包括很多高学历的博士和成功的企业家）同时存在依靠想象力和科学观去认知世界。对待工作和科研，他们能够找资料，调研，做实验依靠数据和推理的方式去验证。但针对一些自己接触不多得问题，抽象的问题，比如管理问题、人性问题和中医问题，又回到依靠想象力认知，依靠盲目的权威崇拜和道听途说去认知世界

15. >方丈，为什么买股票，都建议远离杠杆，但买房子，基本全社会都在用杠杆？？也没见过有人警示不要贷款买房子，一定要付全款的

用杠杆买房子导致的灾难性后果，见2008年金融海啸。


16.  我从来不期望“史诗级的牛市”，每年赚个十个八个点我就满足了。
“史诗级的牛市”是灾难，会造成最广泛最惨烈的亏损。
工业化初期有牛市是对过往现象的总结，对指导未来沒有意义。


17. 做空是很可怕的，共识是很可怕的。

18.  人类追求放之四海而皆准的真理，追求冰清玉洁的世界，酿成的悲剧，那真是数不胜数。

19. 方丈，您说教育“内卷”的本质是什么，是价值观与目标高度统一导致的拥堵吗？

20.  理是这么个理。
如果有目标，有方法，有成就，那么哪个年龄都是好的。
如果没有目标，没有方法，没有成就，那么哪个年龄都是危机。//@牛市不牛熊市不熊:回复@不明真相的群众:有中年危机的人多半有童年危机、青年危机和将来的老年危机，危机无关乎年龄，而关乎内心，内心得不到平衡的人每一步都危机重重，恭喜，你的人生是部灾难片

21. 人性的虚妄。问题出在眼光或者说测量的颗粒度。 看到了一些局部的、阶段性可以模糊验证的规律（现象），就以为可以严格推演到到全世界，全人类。 人类这样的自负引起的灾难，也只能说是不胜枚举了


22. #苏州教师降薪#  刚签过字，自愿降薪。看来没考公务员是对的。

23. 高桥是清的经历： 1，英文很重要，走遍天下（富国） 2，规则很重要，个人、国家财富的基础 3，思想很重要，影响胜过武力（子弹） 4，运气很（最？）重要，机遇、贵人不能缺 时运变迁，个人、国家都是。



24. 你能看出之前看过的书“也是足够无语”，说明你的书没有白读啊，你的问题已经解决了。不要神化书，大部分书里都是废话和蠢话。但这个呢，又需要你读得足够多，或者你足够聪明，才能理解。我从来不刻意去挑好书，或者认为有什么方法可以挑好书，就随便翻翻，但看几页大体能知道这是不是好书。


25. 并不是“他们蠢”，而是我们每个人都蠢。认知能力不足以绝对解决问题，是每个人共同的困境，但不要否定每个人相对解决问题的努力，更不要用事后绝对正确的标准，去质疑人的动机。

26. 市场如果真送钱给你，一定得有人说你蠢。不存在一个万众欢呼的赚钱机会。


27. 这世界，最后往往是蠢人打败了聪明人//@不明真相的群众:回复@刘轶南老师:蛋卷和人最大的区别是，他很蠢，他不知道现在是牛市还是熊市，也不知道未来一年半债是不是坑


28. “货币的本质就是信用”，这没错。但“有信用的黄金是人们的不二选择”这个判断有问题--黄金本身没有信用，它的确有稀缺性，但稀缺性和信用是两回事。如果经济可以不断增长，信用就会不断扩张，因此约定一种有稀缺性的东西作为信用标志本身就很蠢。人类以前犯这个错误，就是因为没有认识到：“货币的本质就是信用”。所以将来应该不会再犯同样的错误 
