---
title: 勤奋、坚持与边际效应递减
author: Guanghua Mao
date: '2020-12-18'
slug: '119'
categories:
  - Original Articles
tags:
  - Business
  - Economics
  - Investment
  - Sociology
  - Psychology
output:
  blogdown::html_page:
    toc: true
    number_sections: true  
---

[Source](https://zhuanlan.zhihu.com/p/24504674)

[Source](https://translate.googleusercontent.com/translate_c?anno=2&depth=1&hl=en&prev=search&pto=aue&rurl=translate.google.com&sl=zh-CN&sp=nmt4&tl=en&u=http://blog.sina.com.cn/s/blog_4a01359b0102z8i6.html&usg=ALkJrhi6H41vjigRY5Br1216ZzlF-GmJXw)

> 无限追加投入，强调勤奋和坚持，是一种农业时代，马尔萨斯增长模式的价值观。在市场容量和增速都有限的情况下，边际收益一开始是会增长的，但最终是边际收益递减，投入并不会换来高额收益。斯密型增长才是符合现代市场经济的增长模型。蓝海战略，顺势而为，守正出奇才是能创造更多财富的价值观。

# 勤奋和努力是职场最大的谎言

请不要把努力和勤奋当成万能的大力丸！

这两天知乎上有个提问很热门，名字叫《外企，中年失业何去何从》，内容很写实很震撼人。尤其是一些答主身边的同事人到了中年，突然被告知公司在年底将不再跟个人续约，突然就得离开宽敞明亮舒适的办公室，离开免费的咖啡零食和高标准的食堂，离开出差就住四星五星宾馆的享受，离开高薪休假般的工作，工作和生活都被活生生的直接劈开，出现断崖式的下跌。

然后再准备去找工作，却发现机会很少，以前的经验能跟新工作完美匹配的很少，年龄被歧视，新机会普遍薪水大幅下降的失落感，常常让人想到晚上失眠。

这些人很勤奋，也很努力工作，到底错在那里了？

说这些人不聪明，能力不强？只要从学校毕业的人都知道，当初校招的时候，外企在招聘人的时候，都是选拔尖的，一个学校往往也只挑几个人出来。社会招聘那就更现实了，能力和经验匹配度都要非常高，本身素质很好，才能进去的。

说企业环境好温水煮青蛙，之后企业冷酷无情，为了提高竞争力翻脸不认的人，是站着说话不腰疼。企业不保持竞争力，最后在市场中落败了，损失算谁的？企业为自己打算就跟一个人工作是为了赚钱养家一样，本身并没有错。

------------------------------------------------------------------------------------------------------------------------------------

喜欢美剧的人，肯定都不会放过一部剧《绝命毒师》。50岁之前，化学老师沃特一直都过着平凡的生活，在一所高中教书，平时还打工补贴家用，每天的时间安排的井井有条，勤奋努力的工作着，家有怀孕的妻子和一个轻度脑瘫的儿子。

在自己50岁生日之际，检查出自己患有肺癌。得知这个消息后彻底改变了他的生活，为了给自己的家人留下更多的钱财，保证她们的顺利的生活下去，不得已中，沃特利用自己的化学知识，瞒着家人和朋友，干起了制毒的买卖。

跟毒贩们的合作与背叛，跟合伙人的矛盾、冲突与和解，在一次次的生死间逃了出来，最后成为了一代大毒枭。

这部片子具有现实意义，真实的社会问题展现，人物人性斗争的直现。如果不是被癌症所逼，沃特还是每天都在勤劳的工作，每笔薪水都有详细的归属，日子过的紧巴巴的！把化学知识用在教育上，薪水就这么点，但是把化学知识用在制毒上，价值暴涨。

如果不把精力都花在制毒是犯罪的道德和法律问题上，透过表现看本质，那么区别就是前后玩法思路上的不同，市场对于选择工作给出的价值高低的不同。

最终是两种不同的观念下的活法。一种是不懂自身工作内容价值的高低，在一种普通的价值观下的活泛；一种是在市场价值规则下，自主选择价值高的工作活法。

------------------------------------------------------------------------------------------------------------------------------------

反过来再看前面讲人到中年面临的事业危机，这里最大的问题就是职场的错误观念——对于成功的决定条件。

这些人只是努力的工作，为一家公司尽心尽力，以为这样就ok。

就像在学校的时候，老师会告诉我们勤奋的人可以笨鸟先飞，早点到达目标地，就是成功。

在职场的时候，大师们告诉我们要努力奋斗，面包会有的，牛奶也会有的，将来会成功。

在公司遇到困难或者迷茫的时候，领导告诉我们要坚持住，才能拨云见日。

但是勤奋、努力和坚持都只是一个正能量的过程，并不是解决问题的办法。

人再积极，再有更多的正能量，再勤奋，如果努力的方向不对，做的再多都没有什么用。

问题是显而易见的，一般人在二十多岁的时候，年轻但是经验少，工资从最低开始。35岁到40岁的时候，经验值已经达到了顶峰，工资和职位基本上也达到了顶峰。过了40岁，身体生理机能开始下降，精力再下降，适应变化的能力也在下降，有效经验也在减少，提供的价值减少，后面还有更多年轻的竞争者，除非提供高价值的供给，否则只能开始接受逐步减薪。这个是一个合理的、客观的过程。

------------------------------------------------------------------------------------------------------------------------------------

中年问题的本质就是没有看清自身价值在时间轴上会是一条抛物线，到达了高点后，就会下落，这条规律。一直以为只要自己努力做好事情，不存在年龄上的变量，就很稳，像成正比。结果就很明显了。

解决办法也很简单，向钱看，每年都要要求自己金钱上的有增长，换行业或者创业的话，允许有过渡性的下跌。

向钱看，其实是最正的方向。

如果有人说我能看清市场的方向，能预测清楚未来，直接可以打他嘴巴！要知道天使投资人的成功率最高也就10%左右，这帮人已经算精英中的精英了。

钱是市场价值的风向标，让市场来决定自己的价值，根据市场的需求而变化，提高自己，以后才有能力应对各种变化。没价值谁愿意去掏钱或者雇佣的，都不是傻子，尤其是老板，钱代表了这项工作的的实际价值，碰到只会说，但是工资却给的低的老板，直接无视掉。

每年都要有工资的增长，意思就是必须每年都有突破，在工作的价值上都要有提高，反过来逼迫自己成长。10年的时间，够成长到高职位，过了40岁公司也离不开你的职位，甚至自己当老板，那就更能应对各种变化了。

用钱来作为一个尺子，来规范自己的行为价值，根据市场来逐步提高自己的工作价值，到了一定的程度，自然就可以应对各种变化。

---

# 真正拉开人生差距的，不是能力，而是“指数型思维”

人与人的差距，到底是怎样形成的？是因为天赋还是努力？选择还是运气？基因还是能力？这些答案仿佛都对。
然而问题在于，当你面对的是一个原本能力相当，出身不比你优越，天赋也并不过人，机遇也少于你的人时，为什么如今他的成就却高于你10倍，甚至几十倍呢？

这个疑惑一直伴随我很久，直到前日，我终于从一个老朋友身上找到了答案。
他是我北大的同学，年长我几岁，却与我同级，因为是退役士兵考的研。
用他的话说，他出身湖南一农村，无论天赋还是成长背景，都与优越二字无缘，甚至放到人堆里都难以被发现。
但他有一个最大的优点，就是懂得“顺势而为”。

他从不安于现状，一直在寻求改变。这并非意味着他情商高，相反，他不苟言谈，即使在创业过程中，也从不有意识地进行任何主动社交。
坦白讲，在他刚创业那会儿，周围很多人都像我一样，压根儿并不认为他能做到多大，也不觉得他有什么超出常人的能力。
可直到前天，我和他进行了3个小时的谈话后，才发现我俩之间的差距，已不是10倍而已。

首先，这种差距体现在了事业的格局上。

他如今操盘了一个年入现金几亿的公司，利润率竟也高达50%以上（别乱想，这绝对是个阳光生意），关键五六百人的规模却没拿过一毛钱投资。更让人羡慕的是他还有大把时间，至少看上去很“闲”。

其次，如果说单纯是事业做的大，我认为没什么好探讨的，因为有钱的企业家多了去，屌丝逆袭的故事也到处是。

真正让我震撼，甚至产生一丝焦虑的，不是他的刻苦与能力，而是他甩我十条街的思维格局。

换句话说，我的成长路径是“线性的”，而他的成长路径是“指数级的”。

之前我还一直在想，同样是读一所学校，在一个教室，认识的都是同一批人，而且他未必有我“聪明”，为何他能积攒更多的势能？

如今我才顿悟，所谓“1万个小时”背后的专注理论，只能帮助你在原有的赛道里比周围人强，但不能帮助你在平行竞争中取得“裂变式成长”。

比如这位同学刚刚创业的时候，我毕业先去做了广告设计，我每天刻苦努力工作超过12个小时，2年多的时间就积累了1万个小时，但收入也只不过是从四位数变成五位数。

与此同时，我的同学当时情况并不比我好，他成了家还要带娃，压力负担也比我大。他做的同样是广告，只不过他是在那时刚兴起的微博上，通过运营账号给人做广告，收入比我好不了多少。

但你要知道，趋势的力量从来不会在当下呈现，它一般会在未来的3~5年现形。

如今，我们已毕业7年，途中我换了3个领域，最后才扎根到现在行业。但他一直在被“内容风口”推着跑，于是乎，我俩之间被“天时”拉开了巨大的差距。

所谓“天时不如地利，地利不如人和”，这句话放到今天已不是真理。

这个时代最厉害的就是“天时”，天时就是趋势，只有趋势才能带来最有爆发力、杀伤力以及指数级的增长。

真正拉开人生差距的，不是能力，而是“指数型思维”

## 真正能拉开人与人距离的，是“指数型成长”。

不妨再来回答一个问题：10年后，你的身价可能是多少？

显然，这个问题很难预测，因为这其中有太多的不确定性，我们无法判断接下来会发生什么事情，以及什么时候它会发生。

不过，如果你真的尝试了去思考这个问题，那么多半的回答，很可能是基于你现在的能力和资源而判断的。

就好比你现在年薪10万，也许你会猜自己未来每年多赚10万，十年后兴许你每年就可以赚到110万。

这，就是典型的「线性思维」，本身没有对错。

线性思维，本质上是一种从自我认知而出发的思维模式，比如在生活、工作中，倘若你想要做大10%，完全可以通过努力换得。

反之，如果你想要做大10倍、甚至100倍，那你就不得不摆脱这种线性成长，让自己重新思考，跳入一种叫做“指数型”的成长模式。

那究竟什么叫做「指数型成长」呢？

举个例子。假设你正走在一条马路上，你每一步都能迈出1米的距离，你走了6步，也就前进了6米，然后你再走24步，那么就离原点有30米的距离。你很容易知道这30步能把你带到多远，这就是简单地线性成长。

但是现在，请你再想象一下，如果你可以将自己的每一步都扩大一倍距离（无论这在科学上是否成立），当你走了6步时，实际上你已经走了32米（1、2、4、8、16、32）。而当你走完全部的30步时，你猜自己走了多远？

答案是10亿米，这个距离相当于你绕地球走了26圈！

真正拉开人生差距的，不是能力，而是“指数型思维”

因此，我们可以清晰的看到，线性成长是有局限的，因为单靠个人或一个组织的努力，迟早会遇到天花板。

而指数型成长是爆发性的，它会拉着你把你拖到自己都无法想象的距离。

这个道理很简单，可一个人若想获得指数型成长，首先要做到的是“顺势而为”。



## 所谓“顺势而为”，就是在确定的大方向里找概率。

记得若干年前，我做了一个针对特定人群的在线培训产品，试运营了一段时间后，感觉用户黏度和利润都不错，所以就想要复制。

于是，我兴奋地找到一个做投资的朋友，完整地阐述了我的这个创业想法。

没想到，还没等我说完，他就硬插了一句话：“这事情的市场潜力太小，没有想象空间。如果你真有兴趣，可以做成‘小而美’，但没有投资会感兴趣的。”

起初我认为这朋友真特么不够意思，可后来，当我冷静思考，才发觉了很多之前自己都未曾考虑到的问题。

其实，我们做任何事情都与投资一样，若想获得超预期的回报，重点并不在于我们能力有多少、把事情做的有多好，而在于你是否真的懂得“借势用力”。

这就好比有一次，雷军对傅盛说：“一个人要做成一件事情，其实本质上不在于你多强，而是你要顺势而为，于万仞之上推千钧之石。”

换句话说，一个人的能力再大，也无法穿越平台的优势；而平台的能量再大，也无法抵挡趋势的力量。

真正拉开人生差距的，不是能力，而是“指数型思维”

就如我的那位同学，当他回过头来总结自己的成功时，从来不会谈自己的能力，而是把成功的“运气”归功于势，说自己擅长的是利用并适应那些已形成的“势”。

比方说他早期创业做内容，微博火他就做微博，微信火了他就做微信，如今抖音、快手、小红书火了，他就去做短视频。

在他看来，自己团队能力再大，也比不过平台花几十亿上百亿去砸一件事情，他总结自己要做的事情只有一件，就是找到平台崛起的机会，然后跟着趋势一起爆发式增长。

换到个人角度，这让我想起之前很多读者给我的留言：究竟是选择一个自己擅长的事情做，还是先“混”进一个好的行业去适应环境呢？

如果你理解了以上文章的意思，就很容易给出答案。

相对个人前途的“不可预见性”而言，增加自己成功概率的方法其实很简单：就是我们先要跳到趋势中，然后利用大方向的确定性来抵抗自己小波动的不确定性。

这就像《孙子兵法》一书中所描述的一段话，“凡善战者，求之于势，不择于人；故能择人而任势。”



## 那些善于把握趋势的人，他们的思维往往是“有限多元”。

前阵子，一位朋友聊天时说了一句话：

“这个时代，如果还有人自称是‘专家’，那他一定是在假装什么；如果你听他说别人‘业余’，那一定是某些人在看不起另一些人。”

这句话，我觉得既好笑又中肯。

因为在我个人看来，有些“专家”，往往就是那些告诉你这件事情不可能实现的人。

可趋势，往往具有不可测量的未知性。当你听到有些人惯用“绝对”、“一定”、“必然”这些词汇的时候，就要开始提高警觉。

从另一个角度说，那些真正能把握趋势的人，有一个重要的原因，就是他们不会被单一的专业规则和思考方式所限。

我管它称之为“有限多元”，即不局限于某一特定规则，但又能保持一定程度上的专注。

比如腾讯这家公司，之前有篇文章《腾讯没有梦想》，指出腾讯早已不是一家科技公司，而成了一家投资公司。但我个人认为这只是表象，一叶障目而已。

目前的互联网巨头，没有一家是不做投资的。投资的意义不只是增加股价，更是一种填补自己生态短板的手段。

所以，腾讯本质上还是一家靠科技产品驱动的公司，虽然它也需要通过投资布局生态，但你从没见过腾讯投身过重工业、制造业或者房地产吧？

因此，“顺势而为”意味着不能被过去经验束缚、被已有资源裹挟，而是告诉我们要学会“有限多元”的思维方式，也就是先确定一条赛道，然后不断地切换分道线路。

只有这样，你才能实现“弯道超车”，真正与别人甩开差距。

真正拉开人生差距的，不是能力，而是“指数型思维”

再比如，我大学时学的是工业设计，很多和我同专业的人理想都是造汽车，所以经常会琢磨着未来能靠设计汽车实现抱负。

就在这群人里，我有个同学，他家境不太好，所以天天还想着怎么靠课外时间赚点小钱。

有一次，他在校门口看到一则驾校的招聘广告，于是欢天喜地跑回宿舍说自己萌生了个赚钱的好主意，结果没人搭理他。

后来，他自己联系上了一个驾校，说可以帮助他们在大学里招生，条件是每个人头返10%的回扣，并且由于学生没啥钱，所以通过他介绍的学员还要打85折。

如果事情放到今天，很难说有几个驾校愿意跟一个小屁孩合作。

可我上学那会儿，家庭购车刚开始普及，人们的消费水平提高了，汽车价格也下降了，导致了一大波的学车潮。

再者，由于大学生在校时间很闲，而且开车还属于个技能，对找工作是加分项，所以大学生考驾照便成了个新兴起的小风口。

基于以上两种原因，这个同学通过帮驾校招生，不到一年时间赚足了100万，依靠的方式仅仅是在宿舍门口贴小传单，于是很快成为了所有人眼中的“小土豪”。

后来，这个同学又干了两年，风口也过去了，他拿着自己挣的钱，跑到德国一所设计学院读了个研究生，回来摇身一变，成了大众汽车的设计总监。

而其它像我一样空有抱负的人呢？99%自打毕业就转了行。

所以，回过头来看，我这同学的成功并不是他有多大的能力，而是他刚好借助了东风，更重要的一点，是他从来不会被单一的规则和思考方式所限。

这在本质上，就是一种“有限多元”的思维。



## 机会从来不会自己消失，错过是因为缺少改变的勇气。

常常听到有人说，“为什么机会总是如此的不公平”，这句话完全是误解。

机会从来不会挑三拣四，也不会无缘无故到你跟前消失。

比如，有一个故事想必很多人听过：

一个有钱的商人来到一个小岛上度假，雇佣了岛上的一个渔夫当导游。

几天相处下来，商人发现这个渔夫很勤快，于是打赏给他一笔钱，并说：“你何不拿这笔钱买一艘渔船，这样你就可以捕更多的鱼，赚更多的钱？”

渔夫听罢，说：“然后呢？”

“这样你就可以把赚来的钱买第二艘、第三艘渔船......然后拥有自己的船队啊。”

“再然后呢？”渔夫不耐烦地问。

“那你就可以像我一样，每年可以有一个月悠闲的时间在小岛上度假，享受自己的人生了。”

渔夫抿了下嘴，回答商人说：“可我现在已经天天在这座小岛上享受人生了啊。”

说完，二人沉默不语。最后，商人临走前留下了一句话：“或许，你觉得自己早已在这座小岛上度假，但这样的生活，对我而言只是一年中很小的一部分。”

这个故事，在许多文章中都出现过，但很多人并没有谈到商人的最后一句话。

换言之，渔夫看似过着天天度假的“理想生活”，但实际上并没做出任何主动选择，他对于未来没有任何抵御风险的能力。

俗话说，不进则退。无论是小到个人，大到商业，趋势是这个世界上我们唯一无法人为改变的事情，并且它会重复上演。

比如工业革命，让一些效率低下的人员失业；互联网的演变，让众多传统企业濒临倒闭；而人工智能的出现，又让更多人感到岌岌可危，甚至焦虑......

因此，所谓的机会与趋势，并不在于你如何理解它，而在于你是否真的具备改变的勇气。

很多时候，即便机遇来了，但你如果一味地迷恋于现状，就极有可能会躲在原有的舒适区里裹足不前。

比如该选择升职后的日夜操劳，还是待在原本熟悉的岗位？

比如该面对创业的机遇和风险，还是朝九晚五等待年底加薪？

比如该接受棘手的业务拓展，还是守住自己门前的一亩三分地？

如果说，趋势对于每个人而言都是机会，那么机会从来不会偏袒任何一个人。然而，你若想要把握住它，就不得不时刻拿出迎接的勇气，因势而动。

所以，回过头来再看，两个能力相当的人之间如何拉开差距？

我个人的看法是：学会掌握一种“指数型思维”，即站在概率论的角度，从自己过去的5~10年中寻找未来5~10年的规律，认清人生的大方向，用趋势的不可逆性去抵抗个人风险的不确定性。

毕竟，无论是创业还是混职场，无论你面对的是一个市场还是一家公司，刻苦努力这些统统是基本条件，它不是决胜的关键，因为真正的机遇总是在趋势中上演。

因此，一个人若想在未来获得爆发式成长，就不得不掌握“指数型思维”
