---
title: 学会拒绝别人，才能过好自己的人生
author: 沐木李
date: '2021-10-25'
slug: '324'
categories:
  - Translation Articles
tags:
  - Insights
  - Personal
---

[Source](https://coo.people.cn/writer/detailslevel/detail/1340318065770332161/publish/article/8)

> 参加工作有感，要学会拒绝

太宰治在《人间失格》中说：“我的不幸，恰恰在于我缺乏拒绝的能力。我害怕一旦拒绝别人，便会在彼此心里留下永远无法愈合的裂痕。”
很多人明明很想拒绝别人，但是每次别人一求还是会心软答应，或者明明自认为拒绝得很好，结果还是落得被记恨、被埋怨的结局。

其实生活有很多事情是自己觉得碍于感情，碍于情面，就算自己心里不愿意，也不会去拒绝。不拒绝别人，只能委屈自己。

你要学会不喜欢就拒绝，没人会感激你的善良，他们只会得寸进尺。


太宰治在《人间失格》中说：“我的不幸，恰恰在于我缺乏拒绝的能力。我害怕一旦拒绝别人，便会在彼此心里留下永远无法愈合的裂痕。”
很多人明明很想拒绝别人，但是每次别人一求还是会心软答应，或者明明自认为拒绝得很好，结果还是落得被记恨、被埋怨的结局。

其实生活有很多事情是自己觉得碍于感情，碍于情面，就算自己心里不愿意，也不会去拒绝。不拒绝别人，只能委屈自己。

你要学会不喜欢就拒绝，没人会感激你的善良，他们只会得寸进尺。

学会拒绝别人，才能过好自己的人生

生活中，做人最大的问题，就是不会拒绝。和你关系再好的人，也要敢于拒绝对方的请求或邀请，该说不的时候，一定要说不，才能洒脱，懂得拒绝，活得才能不纠结。

当你放下面子，放下顾虑，对不想做的事说出拒绝时，你就会发现：

拒绝别人一时爽，一直拒绝一直爽。

# 你不必迎合所有人


毕淑敏说得好——“拒绝是一种权利，你那么好说话，但又有谁能体谅你？”

生活本就不容易，很多时候，你舍弃了自己宝贵的时间，却被那些利用你善良的人压榨，于他们而言，你所做的事都不值一提。

英国作家毛姆在小说《啼笑皆非》中讲过这么一段耐人寻味的故事：

一位早已疏远的老朋友找上门来，向自己道贺，怎么办呢？按照本意，自己实在无心见他，因为一来没有共同语言，二来也浪费时间。

可是好意难却，闭门不见似乎说不过去，于是只好见他了，对方却非得邀请自己到他家去吃饭。

在饭桌上，尽管自己没有叙旧之情，可是又怕冷场，于是又得强迫自己无话找话。

虽然自己不再愿意同这位朋友打交道，但还是不得不提出要回请朋友一顿，这样一来二去，因为不想拒绝别人，反而让自己更加为难。

生活中，在遇到不喜欢的事和人的时候，要勇敢地学会拒绝，如果你拒绝说“不”，那么现实的生活将对你说“不”。做自己的主人，就不要放弃你说“不”的权利。

答应别人的所有要求并不是“人好”的表现，那些不考虑自己感受和承受能力就应允下来的事情，只会让自己的情绪和生活变得糟糕。

你不必让所有人都喜欢你，每个人都有自己的生活方式。不要选择迎合别人，将就了自己。

该拒绝的时候就要学会拒绝别人的要求，当你习惯了被人拒绝，说明你已开始成熟。当你懂得拒绝别人，说明你已学会爱护自己。

作家陆琪说：“大家都以为，帮人才有力量，而实际上，拒绝是一件更有力量的事情。

学会拒绝，人们才知道你的底线，才明白，哪里是可以欺负你的，哪里不可以。”

拒绝是一门学问，那些能坦诚拒绝别人的人，在生活中都活出了真正的自己。

# 拒绝是对自己的尊重


网上流行这样一句话：“不要成全了别人，恶心了自己，学会拒绝别人，也尊重别人的拒绝。”

如果你想有尊严，就先不要去招惹人家，其次要学会拒绝，在别人没有拒绝你之前，先下手拒绝别人。

三国时期华歆在孙权手下时名声很大，曹操知道后，便以皇帝的名义下诏召华歆进京。

华歆启程的时候，亲朋好友千余人前来相送，赠送了他几百两黄金和礼物。

华歆不想接受这些礼物，但是如果当面谢绝肯定会使朋友们扫兴而归，伤害朋友间的感情。于是，他便暂时来者不拒，将礼物全部收下，并在所收的礼物上面悄悄记下送礼人的名字，以备“完璧归赵”。

华歆设宴款待众多朋友，酒宴即将结束之时，华歆站起来对朋友们说：“我本来不想拒绝各位的好意，却没想到收到这么多的礼物。

但是，匹夫无罪，怀璧其罪。你们想一想我单车远行，有这么多贵重之物在身，我是否有点太危险了呢？”

朋友们听出了华歆的言外之意，知道他不愿意接受礼物，又不好当面拒绝，以免大家都没面子，内心里对华歆油然而生出一种敬意，便各自将礼物取回。


太宰治在《人间失格》中说：“我的不幸，恰恰在于我缺乏拒绝的能力。我害怕一旦拒绝别人，便会在彼此心里留下永远无法愈合的裂痕。”
很多人明明很想拒绝别人，但是每次别人一求还是会心软答应，或者明明自认为拒绝得很好，结果还是落得被记恨、被埋怨的结局。

其实生活有很多事情是自己觉得碍于感情，碍于情面，就算自己心里不愿意，也不会去拒绝。不拒绝别人，只能委屈自己。

你要学会不喜欢就拒绝，没人会感激你的善良，他们只会得寸进尺。

学会拒绝别人，才能过好自己的人生

生活中，做人最大的问题，就是不会拒绝。和你关系再好的人，也要敢于拒绝对方的请求或邀请，该说不的时候，一定要说不，才能洒脱，懂得拒绝，活得才能不纠结。

当你放下面子，放下顾虑，对不想做的事说出拒绝时，你就会发现：

拒绝别人一时爽，一直拒绝一直爽。

1、你不必迎合所有人
毕淑敏说得好——“拒绝是一种权利，你那么好说话，但又有谁能体谅你？”

生活本就不容易，很多时候，你舍弃了自己宝贵的时间，却被那些利用你善良的人压榨，于他们而言，你所做的事都不值一提。

英国作家毛姆在小说《啼笑皆非》中讲过这么一段耐人寻味的故事：

一位早已疏远的老朋友找上门来，向自己道贺，怎么办呢？按照本意，自己实在无心见他，因为一来没有共同语言，二来也浪费时间。

可是好意难却，闭门不见似乎说不过去，于是只好见他了，对方却非得邀请自己到他家去吃饭。

在饭桌上，尽管自己没有叙旧之情，可是又怕冷场，于是又得强迫自己无话找话。

虽然自己不再愿意同这位朋友打交道，但还是不得不提出要回请朋友一顿，这样一来二去，因为不想拒绝别人，反而让自己更加为难。

学会拒绝别人，才能过好自己的人生

生活中，在遇到不喜欢的事和人的时候，要勇敢地学会拒绝，如果你拒绝说“不”，那么现实的生活将对你说“不”。做自己的主人，就不要放弃你说“不”的权利。

答应别人的所有要求并不是“人好”的表现，那些不考虑自己感受和承受能力就应允下来的事情，只会让自己的情绪和生活变得糟糕。

你不必让所有人都喜欢你，每个人都有自己的生活方式。不要选择迎合别人，将就了自己。

该拒绝的时候就要学会拒绝别人的要求，当你习惯了被人拒绝，说明你已开始成熟。当你懂得拒绝别人，说明你已学会爱护自己。

作家陆琪说：“大家都以为，帮人才有力量，而实际上，拒绝是一件更有力量的事情。

学会拒绝，人们才知道你的底线，才明白，哪里是可以欺负你的，哪里不可以。”

拒绝是一门学问，那些能坦诚拒绝别人的人，在生活中都活出了真正的自己。

学会拒绝别人，才能过好自己的人生

2、拒绝是对自己的尊重
网上流行这样一句话：“不要成全了别人，恶心了自己，学会拒绝别人，也尊重别人的拒绝。”

如果你想有尊严，就先不要去招惹人家，其次要学会拒绝，在别人没有拒绝你之前，先下手拒绝别人。

三国时期华歆在孙权手下时名声很大，曹操知道后，便以皇帝的名义下诏召华歆进京。

华歆启程的时候，亲朋好友千余人前来相送，赠送了他几百两黄金和礼物。

华歆不想接受这些礼物，但是如果当面谢绝肯定会使朋友们扫兴而归，伤害朋友间的感情。于是，他便暂时来者不拒，将礼物全部收下，并在所收的礼物上面悄悄记下送礼人的名字，以备“完璧归赵”。

华歆设宴款待众多朋友，酒宴即将结束之时，华歆站起来对朋友们说：“我本来不想拒绝各位的好意，却没想到收到这么多的礼物。

但是，匹夫无罪，怀璧其罪。你们想一想我单车远行，有这么多贵重之物在身，我是否有点太危险了呢？”

朋友们听出了华歆的言外之意，知道他不愿意接受礼物，又不好当面拒绝，以免大家都没面子，内心里对华歆油然而生出一种敬意，便各自将礼物取回。

学会拒绝别人，才能过好自己的人生

如果华歆声色俱厉地拒绝别人，甚至心怀疑虑，认真盘问对方，也许事态就会扩大化，甚至使双方的友情出现裂痕。

有时候，有礼有面的拒绝别人，既保护了别人的体面，也让人们看到你更加有尊严的生活方式，这是一种大智慧。

我们的一生都是在不断拒绝中度过的，无论说话还是做事，有选择就必然会有放弃和拒绝。在面对别人提出的不合理要求时，拒绝是对自己的尊重，也是自己的权利，不必为此感到愧疚和亏欠。

日本有位教授曾发出过这样的感慨：“央求人固然是一件难事，而当别人央求你，你又不得不拒绝的时候，亦是叫人头痛万分的。因为每一个人都有自尊心，希望得到别人的重视，同时我们也不希望别人不愉快，因而也就难说出拒绝的话了。”

做人要多包容多付出没有错，但凡事都要有一个限度。很多时候，你越过于好说话，就越没人对你好好说话。你懂得有所拒绝，才会赢得别人真正的尊重。

适当的拒绝，远比一味地付出和迁就更能让人明白该如何正确对待我们。

拒绝不喜欢、不合理的请求，是你的权利，也是你尊重自己的选择。

拒绝不是绝情，而是一种点到为止的理性，一种为人处世的智慧。很多时候，懂得如何拒绝，也是一种高情商的表现。


# 学会拒绝别人，才能过好自己的人生


卓别林说过一句话：“学会说‘不’吧，那样你的生活将会好得多。”

不是自己份内的事，就果断地拒绝；不干涉别人，也不让别人干涉自己，让生活和工作不轻易被打扰，专注于自己真正要做的、该做的事，乃是聪明理性的选择。

三毛说过，“不要害怕拒绝他人，如果自己的理由出于正当。当一个人开口提出要求的时候，他的心里已经预备好了两种答案。所以，给他任何一个其中的答案，都是意料中的。”

我有一个开书店的朋友，一次我晚上十点半打电话给她，请她帮忙找一本旧书的时候，她就坚决拒绝了，而且三番五次地告诉我，她的睡眠质量特别差，以后千万不要在晚上十点后打电话给她，否则很可能会失眠。

从那以后，我就谨记在心，不但晚上不给她打电话，甚至连她的朋友圈都不评论，生怕扰得她一夜都睡不着。

她拒绝我，是因为她想让自己的睡眠质量好一点，许多时候，拒绝就是为了让自己的生活变得更加美好。


拒绝，会减少其他人命令你和麻烦你的机会，你学会了“好意思”，别人在你面前才会变得“不好意思”。掌握了拒绝的能力，成为一个支配者，才不会被别人牵着鼻子走。

真正的自由，不是你拥有了多少，而是你敢于拒绝多少。

生活中，我们往往因为害怕失去别人，就不知道拒绝别人，殊不知，不懂拒绝，毫无底线的妥协，失去得更快。

作为一个完整的自我，从个人责任的角度出发，先把自己的正事处理好，在有余力的情况下去做其他的事，才不至于顾此失彼，让自己疲惫不堪。

拒绝，不仅仅是一种明确的态度，还掺杂着一种独立的精神。

敢于说“不”的人，往往都有自己坚定的立场、独立的思想，他们不会把别人的目光和看法放在第一位，只要有不同的意见和看法，就会大胆地表达出来，而不是趋炎附势、随波逐流，为了合群而刻意讨好。

敢于拒绝的人，都是内心强大的人，不怕自己跟别人不一样，也不畏惧异样的目光。

敢于拒绝的人，都会有一点独立精神，这种独立不是盲目地反对所有，而是听从内心的声音，坚守自己的原则，不轻易因外物而妥协。

当你可以心安理得地对不喜欢的人和事说“不”时，你便找到了有个性的自我人生。

很喜欢这样的一句话：人格健全需要人有说不的能力，能够拒绝自己不喜欢的人与事，当然，也包括你能够屏蔽垃圾资讯。拒绝就是建设，你家的大门保证只能让你喜欢的人进入。

越是有智慧的人，越懂得，保持应有的原则和底线，要比一味施予付出更重要。因为只有有原则的付出，才是有价值的。

记得，不要因为怕伤害别人，就把令自己为难的事情应承下来；自己囊中羞涩时，就别虎头虎脑地仗义；自己本分工作没完成时，就不要答应到处救火；触碰底线的时候，务必果断地表明态度。

敢于拒绝，才能成为真正的自己，才能有所成就，才能驾驭得了幸福和自由。

学会拒绝别人，才能过好自己的人生。

习惯性的付出和迁就，很容易让人觉得你很软弱，这样的形象也势必会被对方轻视。与人相处，不仅仅是自己的事，也不仅仅是对方的事，而是两个人相互之间的事。

想让他人以正确友善的方式对待自己，你就要先学会拒绝。拒绝是一种姿态，也是一种尊重，让人从内心里尊重你的选择。