---
title: 褚老师另类职场课（6）
author: Guanghua Mao
date: '2021-10-06'
slug: '318'
categories:
  - Original Articles
tags:
  - Job
  - Business
  - Politics
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---



# 职场权力的秘密

"power"：功率、动力、权力




# 职务权力 vs 个人权力：

公司前台和老板秘书职务不高，但权力很大，会认识很多公司的大人物、大客户和老板的待人处事。（自带人脉拓展性）

某市长司机被提拔成副科长，赵薇的老公以前也是市长司机。

技术大牛也可以拥有很大的个人权力。

要注重培养个人权力





# 员工不应该知道的公司秘密：

在任何公司里，当权力精英的秘书永远是一个快速升职的办法。


很多岗位都是自带人脉扩展性，有机会接触各个部门的人，和各个部门的高级领导。比如周凯旋





# 个人权力测试

1. 高层领导知道这人是谁吗？

2. 老板能不能不问别人就知道这个人工位在哪儿？

3. 这个人是讲过去比讲将来更多吗？

4. 肢体语言自不自信。

5. 这个人说话别人听不听？

6. 大家是不是愿意把各种消息透露给他，是不是信任他。

7. 参加会议的多少？

8. 除了领导，公司其他部门的人有多少人认识你？

9. 这个人平时都和谁吃午饭？

10. 这个人见什么人不需要先约？

11. 这人想要的东西能实现吗？




# 避免权力错误：

1. 白白有权力不用，让别人抢走。太面，总是屈服于看起来强势的人。

2. 领导害怕部下，怕对部下太严厉、太严格，记住被喜欢不重要，被敬重很重要。

3. 各种建立重要杠杆的机会被不断错过---大领导需要你汇报工作，不要害怕、不要担心，不要让自己的工作让别人去汇报，要跑步夺取。

4. 使用自己还没有拥有的权力---过早开始谈薪，要在对方十分想要你的时候去谈薪；当所有人都嚷嚷他应该需要这个权力，他肯定没有这个权力。

5. 后出价，只看价值是多少。

6. 误判自己权力的大小




准确的识别权力的分布是十分有用的。

职位从低到高，影响力从低到高。

职位高，影响力低：衣架。干得久，但没有大的贡献，老板的亲戚。帮不上忙

职位低，影响力低：面瓜。帮不上忙

职位低，影响力低：意见领袖

职位高，影响力高：权力玩家

职位超高，影响力超高：权力精英（老板，合伙人），部门最高领袖

权力精英决定职场文化：小米，苹果，锤子。做事风格，办事重点。




揭秘你的权力精英：

1. 别听他们说什么，看他们做什么。说的都很政治正确，很官方，很严格。

2. 权力精英的工作风格和兴趣话题以及工作方式。

3. 要注意什么人在权力精英面前被表扬、被提职。

4. 如果没有机会面对面和权力精英直接接触，可以问你的老板和人脉很广的人。

5. 看新来的权力精英改变了什么。




# 如何提升职场权力：

权力越大，能实现的目标就越多

1. 表现---performance，真正的职场权力源于有价值的贡献。有些人混得好是因为和某一个人的特殊关系，这非常危险。ROI，投资回报率，任何时候都要通过投资回报的视角来看待公司，要超出公司的预期，是非常重要的，这种回报是非常长期的。

2. 感知---perception，看不见的贡献没有任何政治价值，

2.1 重要性高，可见度高---造星类，要做好，还要包装好，花最大的精力。


2.2 重要性高，可见度低---透明类，要试图增加可见度。

2.3 重要性低，可见度高---维护类，经常需要重复做的事情，如财务收支的表，要模块化、仪式化。

2.4 重要性低，可见度低---费粮类，尽量不去做它。

2.5 要装成他们想要看到的那个人，fake it until you make it. 自信方面，语气姿势方面，能力方面等。

3. 伙伴---partnership，每一个积极的工作关系都会提升你的影响力。

3.1 多“请客”，多请大家来参与你的工作，邀请大领导来参加组会

3.2 多“组局”，把各个方面的力量结合在一起共同做一个项目。











































