---
title: 竞争意识削弱竞争力
author: 大漠孤鹰_Potter
date: '2021-03-18'
slug: '165'
categories:
  - Translation Articles
tags:
  - Business
  - Economics
  - Insights
---

 [Source](https://www.jianshu.com/p/863195057fda)

>深刻理解商业本质，根据 *The Power of Fifty Bits* 所说，竞争意识是人性的缺点，所以拼酒、拼成绩都没什么必要。


竞争意识削弱竞争力，相信很多朋友听到这句话的时候可能会感到迷惑不解，在我们的观念中，竞争意识是可以增强我们的竞争力的呀。人类科技之所以能够发展到今天这种高度发达的地步，与人与人之间、族群与族群之间、国家与国家之间激烈的竞争是分不开的。人与人之间激烈的竞争、生存的压力、获得更好生活的欲望迫使我们不断努力，不断学习，不断成长，不断突破、超越自我。可以说竞争无处不在，无时不在，竞争意识不可缺少，否则你将会被别人远远的甩在后面，面临被淘汰的命运。

最近听了罗胖60秒《商场上的“敌人”是谁》？豁然开朗，对这句话有了全新的认识。商场如战场，知己知彼，百战不殆，这个“彼”究竟是谁呢？有的公司将其理解为竞争对手，也对，其实这个“彼”主要应该是指客户、用户，了解用户，将主要精力、心思花在客户身上，用心为提供优质的产品和服务，我们才能真正的赢得客户，在市场竞争中立于不败之地。竞争对手的动态当然要关注，但是如果主要精力花在竞争对手身上而忽略了客户需求，是一种战略上的资源错配，将导致企业的失败，这就应了那句话，“竞争意识削弱竞争力”。其实这句话的真正意思是注意力、资源的配置决定竞争力，当我们将我们大部分的注意力、资源用在正确的方向、对象和目标上，自然就会产生竞争力，容易出成果，否则不仅不能增加竞争力，还会削弱竞争力，导致失败。做正确的事比正确的做事更重要。如果做的事本身是错的，方向不对，再努力、方法再正确也无济于事。

商场如此，情场也如此，比如一个小伙追一个漂亮的姑娘，同时还有8个情敌，那这个小伙子该怎么办呢？如果他将注意力、精力放在那8个情敌身上，即使他使出浑身解数，将他们一一打败，也不一定能抱得美人归。最好的办法就是不理会那8个竞争对手，将所有的注意力、资源、时间花在姑娘身上。

所以我们要正确的认识竞争和竞争意识，竞争意识固然重要，但更重要的是要搞清楚真正的对象、目标、方向，并将主要精力、资源花在他们身上。同时也要意识到合作比竞争更重要，共同做大蛋糕，皆大欢喜。