---
title: 买便宜股票可以使你贫困
author: 张化桥
date: '2021-03-27'
slug: '174'
categories:
  - Translation Articles
tags:
  - Business
  - Economics
  - Investment
  - Psychology
---

[Source](http://blog.sina.com.cn/s/blog_50c88c400100ileq.html)


不少人喜欢买便宜货：从旅行包到化妆品，从毛衣到皮鞋。只要有大减价，他们每场必到。他们买回一大堆东西，但不一定是真正有用的东西。看起来这些东西便宜，但因为没有实际价值，所以成了主人的负担。主人要找地方放置它们。主人本来想节约，结果每个月的开销超出预算，甚至负债累累。时间长了，那些便宜货没有用，主人又不忍心丢掉它们，于是搞一个大甩卖（即“garage sale”）。

买股票也是如此。有些人喜欢捡便宜货。突然，一阵大风扫过，一半的股价不见了。强忍了许久，主人才抚摸着伤口，斩仓。而斩仓又正好错过了下一轮投机的升浪。主人悔恨，却不断地重复同样的错误。这样的人掉到了“价值陷阱”（value trap）里面。

多数人认为，巴菲特是个价值投资者，可是有一本刚刚出版的新书却对这种看法提出了有力的挑战。美国Georgetown大学的教授Prem Jain在今年刚出版的大作Buffett Beyond Value中认为，巴菲特实际上既是 “增长性的投资者” （growth investor），又是价值投资者，而且更是前者。
　　
（1）要看过去多年的销售和利润

作者认为巴菲特成功的秘诀在于把重心放在公司的可持续的增长率，然后再看股票的价格是否足够便宜。作者找了很多的例子证明，对于低质量以及增长前景一般的的公司不管多么便宜，巴菲特都是不买的。

对巴菲特的两大投资原则，大家已经很熟悉了。（1）不能只看某一年的市盈率，要看过去多年的市盈率。这个原则很有意思，因为它可以帮你避开那个可笑的，关于究竟用那年的市盈率的问题。（2）所投资的公司必须足够大，在行业内必须有领导地位，而且负债率不高。他说大家要避开“价格低，但价值更低”的股票。当然，市盈率高的股票或者昂贵的股票不见得都是增长性的股票。

直到最近可口可乐是巴菲特最大的重仓股票，占他的所有的股票资产的16%。这些股票大多数是十几年前买入的。1988 年底，可口可乐的市净率高达5.32倍，而整个资本市场的市净率不到2倍。当时，可口可乐的市盈率为16.8倍，而S&P 500的平均市盈率只有12.4 倍。更重要的是，在巴菲特1988年买入可口可乐之前，可口可乐的股票已经从1978年上升了200%。所以，巴菲特不是一个捡便宜货的人。

这本书中讲，要看一个公司的历史业绩，最好看十年以上。我1994年入行时, 听老行尊们说过类似的话，但我没听进去。一是中国公司的历史短，二是情况变化快。如果你一定要坚持巴菲特的要求，你会错过很多好公司。当然，巴菲特也错过了太多好公司。但这没关系。

巴菲特愿意只投资已经被证明了的好公司（把前半场的钱让别人去赚）。这样的投资方法的成功的概率高，失败的概率低。在选到了好公司之后，巴菲特宁可在估值方面多一点让步。这与大家对价值投资者的看法不同。他说，“多付点钱买一个伟大的公司，远远好过贪便宜而买个普通的公司”。（It is far better to buy a wonderful company at a fair price than a fair company at a wonderful price）。价值投资的重点是看公司的过去，增长型投资的重点是看未来。而巴菲特投资的方法是两者都看，而且特别要看未来。

江山易改，本性难移。坏的管理层就是坏的管理层，也许永远不能变好。很多投资者太容易饶恕他们，原因首先是自己贪心和怀有侥幸心理。其次是一种无奈：天下乌鸦一般黑，不买这个股票买哪个呢？这是一种逼迫自己亏钱的方法。最后一点，就是懒汉习惯。大家愿意花大量的时间无所事事，也不愿意花一点时间，扎下去挖掘好的公司。巴菲特说，“如果你在厨房里发现了一个蟑螂，那你可以肯定绝不止一个”。

巴菲特建议大家看公司过去五年，十年的市盈率。很多中国投资者（我以前也是）会认为这个标准过于严格。但是你认真想想就明白，这个原则的意义很大。如果象某些中国地产公司那样，去年，今年和明年的利润分别为1亿元，8亿元，和25亿元，你认为它的市盈率应该是多少？它的市盈率应该以那一年为基础？它的利润增长能够持续吗？

（2）放弃前半场，只赚取后半场的暴利

人们把投资者分成截然不同的两大派别：价值派和增长派。这是很错误的。Jain教授认为，巴菲特既是增长派又是价值派，但首先是增长派。他还认为，当你发现一家公司很进取，正派，前景好，公司的利润会高速增长好些年的话，你千万不要用传统的估值方法去捆住你的手脚。今天看起来很贵的股票，过两年就显得很便宜，而且你似乎永远买不到它，因为它的股价不断创新高，似乎永远很贵。分析这种高增长的公司必须靠大智慧和高瞻远瞩，而判断大多数其它公司（以及做纯粹价值派的投资），不需要太多的智慧，谁都能够计算市盈率，市净率，等等。巴菲特说，利润高增长是价值投资的核心因子之一。没有增长，一个股票的价值会大打折扣。说到投资的安全性，他认为，利润高增长是最大的安全。进攻是最有效的防
御。

Jain教授问读者一个问题，在1980到1990年的十年，麦当劳的股票升值了6倍。你有没有胆识买入麦当劳的“昂贵的”股票，赚取后来的7倍？巴菲特有。他看中的是高增长和管理团队。可惜，他也不是神仙。他后来承认他在1998年卖出麦当劳的股票是一个巨大错误。

巴菲特劝大家区分一次性的因素所导致的高增长与可持续的高增长。比如，石油涨价会导致石油开采和钻井设备的制造商的利润出现高增长，政府对某项产品的退税可能刺激需求和有关公司的利润快速增长。但这并不能使它们成为高增长型的公司。在中国，“政府扶持”和集团（母）公司“注资”会给很多上市公司带来一次性的高增长。这种高增长具有欺骗性。很多通过后门上市的公司非常令人失望。原因是，他们的业务能力（执行力）并没有跟上。

(3) 销售额的增长是核心

利润虽然很重要，但一家公司的销售额的增长有时候更重要。靠退税，靠政府补贴，靠减少折旧，靠削减成本，靠屠杀供应商，靠逼疯下家客户，靠非经常性的收入，靠资产处置，靠关联交易(倚靠母公司注入資產)，靠财务技巧，靠一次性的并购，靠拣了个大便宜，总是有问题的，好处总是有极限的。

巴菲特和他的老师Graham都强调公司所处的行业的增长空间的重要性。我由此想到一些例子，比如，泡菜，钮扣，铅笔，报纸，系统集成，化学品的仓储，建筑安装，以及为某一个特殊的媒体和平台提供广告或者内容，这些都是增长空间不大的例子。增长空间的大小有时与企业所处的行业有关（夕阳还是朝阳行业），有时与商业模式有关（也就是如何赚钱的方法），有时与行业的最终大小有关。

一般人认为，高成长的公司都在科技，医药和媒体行业。这不见得。巴菲特自己就承认不懂科技和医药，所以只好再传统行业里寻宝。好在传统行业已经足够的大，机会足够的多。

（4）“价值陷阱”就是“贫困陷阱”

在香港，我发现最常见的两类“价值陷阱”是地产股和综合类企业。一年又一年，总有大量的投资者掉到里面不能自拔。在地产界，我常听人说，某地产公司的土地储备很多，位置很好，资金宽裕。但是，它们的开发能力低，资金周转速度慢。总之，别的开发商可以在同样的项目上赚5亿元，而他们只能赚1亿元，而且费时更长。也就是说，它们摧毁价值。这样的公司很多，它们的股价往往在净资产(NAV)之下一半或者更便宜。好些公司更在账面净资产之下，甚至低于每股净现金。

这种状况会改变吗？懒汉会变成勤快人吗？只要管理层不换人，或者不换思想，这种状况会持续很久。他们的土地储备或者大把现金与股民何干？

综合性的企业包括窗口公司。因为业务混杂，股民们看不到管理层的思维逻辑，更看不到他们的工作热情。如果管理层愿意把各项业务拆开来卖掉，净资产会高于他们的市值。可是股民们看不到曙光。

你试想，像这样的公司，如果四，五年以后他们的利润与现在相若，那么，他们四，五年以后的市盈率应该是多少？7倍，8倍，最多9倍而已。你算出它们四，五年以后的股价，然后用7%或者8%的贴现率折回到今天，你会大吃一惊！这个股票不值钱！它们让你贫困。

它们虽然账面价值大，业务规模不小，土地储备也好，但很快就会被小小的，但很进取的民营企业超过。这些民营企业的净资产虽然只有10亿元，但能够推动100亿元的年销售额，实现20亿元的利润。反过来，政府控制的有些企业，虽然账面净资产高达100多亿元，但只能推动40亿元的年销售额，实现5亿元的利润。你看那种公司优越？
