---
title: '方丈在雪球关于规模化的讨论'
author: 方三文
date: '2022-02-23'
slug: '408'
categories:
  - Translation Articles
tags:
  - Investment
---

1. 竞争是利润的杀手。
能持续经营的商业，总有一个东西是可以抵挡竞争的。
比如规模效应，你规模上去以后，成本会比别人低。大部分工业品生产有这个特征。
比如品牌效应，因缘际会+持续投入，会影响用户心智，能获得定价权，降低销售成本。
比如网络效应，越多人越好手。
影视作品的生产，没有上述特征。属于：
成功规律无法把握。
规模扩大效率无提升。
持续投入品牌无积累。//@_db_:回复@不明真相的群众:是哦 竞争又激烈 又无法高质量批量规模化生产 爆款产品具有偶然性 用户没有忠诚度 哪个好看去哪个看 这届观众不好带



2.  都不容易有很高的市场份额。//@行知非白:回复@不明真相的群众:是不是有点像您之前提的 理发店，规模化不足以提升效率？ 相比下，整形医院有更高的门槛，连锁扩张的可能性更大。


3. 造成市场集中度低下的原因
　　1、 由产品本质属性所决定
在著名的“波特产业竞争”理论中，所描述的零散型产业，多数是市场集中度低下行业，这些行业中的产品一般具有以下一项或数项产品属性和特征
1)、保质期短暂：比如糕点业、鲜奶业；
2)、储运成本过于昂贵：如桶装水和雪糕冷饮业；
3)、产品难以规模化生产：即产品无法快速低成本复制，比如众多的手工艺品，土特产品；
4)、受原材料供应制约：一些行业产品的生产基地必须建在原材料所在地周围，比如矿泉水业；
　2、由业内厂家的综合实力所决定
1)、业内厂家的综合实力普遍强大；
2)、业内厂家综合实力普遍较弱;
3、由消费需求多样化程度所决定
消费者需求日渐多样化已是事实；
4、 由新兴行业所处的发展阶段所决定
许多新产品（有专利垄断的除外）从中小企业中诞生、发展。但中小企业的实力又决定了在新行业发展初期难以迅速扩张占领市场。
5、受计划经济年代遗留的历史包袱和政策所影响

　　在一些行业，如果完全面对市场，可能早已是高市场集中度行业，但是由于存在地方保护，人为营造区域竞争壁垒，从而影响了一些行业的市场集中度。比如有众多地方品牌的啤酒、白酒、香烟行业
　　
　　
　　
4. 传统的教培行业，特别象餐馆：
1、服务依赖本地物理网点完成，每个网点招生（食客）的半径无法扩张。
2、服务由不同的老师（厨师）完成，产品流程、质量无法标准化，同时，单个老师（厨师）的服务能力是无法扩张的（他只有那些时间啊），优秀老师（厨师）最多只能提点价。所以整个市场份额的分布是极其碎片化的。
后来，企业化的教培机构，做了中央厨房，能做到教学体验基本标准化，所以能够相对规模化扩张。但这个扩张仍然受限于：物理网点需要有一定生源规模支持；教师的流动意愿很差，所以三线以下城市很难开网点，开了网点教学体验也很难保持一致性。
这个就相当于做了连锁餐厅，连锁企业的市场份额有了较大的提升。但是，要麦当劳开到非发达地区的县城依然是很困难的，甚到大城市的郊区都难。
但是，教培和饭馆有一个根本的不同，就是教学这种服务，有可能通过在线完成，如果这个事情办成，那么：招生半径可以无限扩大；教师的复用率大幅提升；物理网点成本大幅下降。




5. 东莞不是好的生意模式。赌和毒（兴奋剂）可以规模化生产，低成本复制；黄很难规模化低成本，因为服务的主体是人，公司只能起到一个“一对一掇合”的作用，价值有限，这就类似于教育培训行业“一对一掇合”模式不好一样。


6. 规模化、低成本地解决人的寂寞、无聊、焦虑问题。//@思奇求稳:回复@不明真相的群众:哪最好的生意呢？



7.  1、影视作品的成功规律很难把握，难以工业化规模化生产，现在看来，电视剧工业化比电影成功。2、在影视作品的生产过程中，公司这个组织的价值有限，导演、演员拥有议价权。3、投资影视有大量经济外收益（比如出风头，接近名人、美女），所以这个行业投资的定价，整体是溢价的。//@小明吹大象:回复@不明真相的群众:我有个很大疑问，其实就算去掉目前电影票房的注水部份，实际票房也是逐年大幅增长的，但是为啥不见影视板块赚钱呢？所以我从不买这些股票 $光线传媒(SZ300251)$ $华谊兄弟(SZ300027)$ $万达电影(SZ002739)$




8. 幼儿园不是好生意。1､家长的期待与园方能提供的服务，永远有巨大的差距。2､园方的管理意图与老师的实际操作，永远有巨大的差距。3､可以标准化、规模化的地方很少，企业的价值有限。4､房租、教师工资成本永远在上升，收费价格却受各种因素的影响，不容易提升。5､安全与责任方面的巨大风险，与极低的利润率，简直完全不匹配。//@心平气和撒:回复@不明真相的群众:财新：

       国内一家经营6岁以上课外辅导的公司负责人告诉财新记者，在国内做幼教成本高，风险大，考察之后选择了做6岁以上的教育连锁。

　　他指出，一线城市核心地段的幼儿园，租金成本占比或高于人力成本占比。孩子的人均活动空间大概需要5平方米，以一线城市的租金水平计算，每位孩子每月租金成本大约2000至3000元，一线城市的租金成本可能高于人力成本。

　　按照红黄蓝的收费标准看，在一线城市属于中低端幼儿园连锁，利润率大约在20%至30%左右，相比教育行业其他投资，利润率较低：“前期投资500万至1000万的幼儿园，收回成本需要2年以上，1000万以上的投资，需要3-4年收回成本，”他指出。

　　同样位于北京市朝阳区的思贝乐幼儿园近日在北京产权交易所挂牌转让，转让信息显示，幼儿园2016年营收为698.82万元，净亏损211.94万元，截至2017年9月30日，营收576.81万元，净亏损135.88万元。这家幼儿园每月学费超过5000元，和红黄蓝新天地幼儿园相当。

　　相比单体幼儿园，规模化经营的优势在于采购的边际成本会下降，并且会获得品牌优势，从而在招生上获得优势。但幼儿园行业和义务教育阶段不同，就近入学成为关键，因此幼儿园的位置以及地租成本成为关键。

　　前述课外辅导业内人士分析，加盟模式本身没有问题，但是快速扩张带来的风险在于，管理的标准化之外，是否有管理能力执行到底才是关键。

　　实际上，多位教育领域业内人士和投资人指出，纯粹线下的普通幼教园并不受风险投资类资本追捧：投资周期长，风险大，盈利不大已成业界共识。
　　
　　
　　
9. 财新记者了解，早期投资人退出时回报均不高。前述接触过红黄蓝的投资人指出，投资单体幼儿园和连锁幼儿园没有区别，因为幼儿园无法跨地形成协同，规模化效应不明显。幼儿园的品牌，与单体幼儿园的管理能力没有直接相关性，加盟店的品质控制难以量化，也难以产品化。从成本结构看，由于二三线城市缺少教师资源，成本可能比大城市高。


10.  "早就不上微博“是普遍的感受，如何看待这种感受？微博是在移动互联网的爆发阶段，最早提供的规模化服务，在某一阶段，微博消耗了中国移动互联网70%的流量。随着时间的推移，用户基数更为广泛的通讯社交游戏等类型服务都在往移动互联网服务这个池子里灌水，也在往每个用户相对恒定的使用时间这个池子里灌水，定位于媒体服务的微博市场份额必然被不停稀释。但在媒体服务这个市场，它的份额已经相当稳固。


11. 盈利的电商大部分在淘宝是肯定的，但同时淘宝店很大部分是不盈利的。淘宝店这个东西太有意思了，它根本上解决了一个群体的失业问题。一个人实在走投无路了，总可以开家淘宝店吧，还可以跟人说我在做“电子商务”。//@王治全:电商本质上还是商，就这点而言与小卖部没有区别。而且，是不是可以这样讲：90%的电商都是盈利的，只不过这些盈利的电商都集中在淘宝店上了。大的电商之所以目前还不盈利，与其规模化的运营模式，阶段性发展战略，行业的激烈竞争（如所谓“过度服务”和“恶性营销”），媒体成本所导致的营销投入过大等有关。再过1-2年回过头看，或许有些问题就更清晰了


12. 在一个正常竞争的商业环境里，超过三分之一的企业亏损是必然的，我不认为阿里能帮所有的淘宝店挣钱，上帝都做不到。

