---
title: 消失的百万代理人：卖保险不如跑长途？
author: 北京商报
date: '2022-01-30'
slug: '386'
categories:
  - Translation Articles
tags:
  - Economics
---

一直以来，“大进大出”是寿险业代理人的真实写照。近两年，局面似乎发生了改变，涌入代理人队伍的人在减少，而离开的人数却直线上升，李明（化名，以下人名均为化名）就是后者之一。

“孩子学费、房贷压身，我在一家运输公司做长途货运司机，一个月能赚1.5万元，收入比卖保险可观，主要还稳定。”李明坦言。

“拉人头”遇阻

一沓获奖证书、几支钢笔、一摞笔记本在李明的书桌上格外显眼，如今这个书桌成了他儿子的专属学习桌。

半年前，李明还是一家某国资背景寿险公司支公司的高级经理，拥有一个20人小团队。“我在2017年入行之初选择走增员路线，人口红利下招人并不难。”

单枪匹马不如团队作战。在加入保险业前，作为家庭顶梁柱的李明立下了30万年薪的军令状。思虑一番后，他了解到，仅凭一己之力单打独斗很难有高收入，金字塔式的保险代理人组织层级却可以让他轻轻松松实现自己的小目标。

一般而言，多数团队架构按“总监-经理-组长-组员”进行分层，上级收入来源除了自卖保单外，还有队员的保单提成和管理津贴。

随着人口老龄化加剧及居民健康意识的提升，保障需求不断被放大。民众的保险意识提升叠加人口红利，在李明的眼中，招新人似乎轻而易举、水到渠成。2019年，他的队伍从8人扩大至20人。

“快到碗里来”不再是一句广告语。行业数据便是最好的佐证，2019年保险代理人数量突破了900万大关，达到了912万。

但短短一年的风云突变，属于李明乃至行业的鼎盛之势便成沤浮泡影。人口红利散去，热闹归为冷寂，高流失率冲破李明的心门。即便是更新新人培训体系，抽调了最新的师资力量，但依旧不能挡住代理人离开的步伐。

看着身边伙伴不断流失，随之而来的是李明收入的断崖式下滑，从月薪2万元到月薪6000元。与其浑噩度日，守着已打下的成绩沾沾自喜，不如破釜沉舟，愧奋直前。追随着离开者的步伐，李明也彻底放弃了30万年薪的梦想，回归现实。在朋友推荐下，他开始跑起了货运司机。

一份《中国保险中介市场生态白皮书》明晰指出了代理人生存现状，七成代理人的月薪都未过万，每月收入在3000元以下的受访营销员约为10%，月收入在1万元下的人群约为69%。

“实在卖不动了”

和李明一起离开的，还有他的朋友王亮。

在加入保险代理人队伍前，王亮干过净水机销售、洗车等工作。为了肩负起养家的重任，三十而立时，他选择投身到金融业之一的保险领域。

刚加入保险业时，朝气蓬勃的团队、源源不断的保险知识、多劳多得的绩效体制无一不让王亮着迷。“每天早上开早会，将工作与学习融入一体。有时候还去外地旅游、团建、培训，这种工作氛围是我最喜欢的。”

“打鸡血”是王亮当时的工作状态。“all in”像战鼓一样，让他热血沸腾地去找客户促成签单。凭借着初生牛犊不怕虎的精神，他开始效仿师傅，列出潜在的客户清单，对自己的“五同人群”（同学、同事、同好、同乡、同宗）逐一筛查，无一漏网。“卖保险第一步是自己，第二步是缘故。”王亮说道。

随着连续几个月对亲戚朋友的不断挖掘，绩优、钻石等评选证书“接踵而至”，三星员工也收入囊中。“当时靠提成就能获得8000元收入。”王亮回忆道，这笔提成比身在公务员系统的同学工资都要高。

然而，美好的时光是短暂的，当身边的亲朋好友资源都被开发过了，王亮愁闷于“下一单在哪？”有保单开心到波峰、没保单失落至波谷的过山车式心情让他辗转反侧、夜不能寐。“亲戚朋友都走遍了，陌生拜访的客户，如果两次都没有买保险的意愿，我就不好硬着头皮再去找了。”

当离职后再次见到亲朋好友时，王亮用“舒坦”来形容：“因为周围认识的、不认识的客户资源挖尽了，实在卖不动了。”

如今38岁的王亮还没有太着急投入到下一份工作。“我想沉淀一下自己，多年来学习的保险金融知识并非一无是处。现在想多学习一下其他金融知识，拓展可选择的范围。”

在上海对外经贸大学金融保险系主任郭振华看来，随着市场挖净，导致代理人业务少，“活不下去”，他们就退出行业了。

王亮并非孤例，遗憾退场的不止一位、也不止一家保险公司的代理人。北京商报记者获得的一组行业交流数据显示，2020年底，保险代理人数量下滑至704万人，相较于2019年减少了208万人。

“时代抛弃他们”

“这个月我参加了3场送别宴，这次离开的是在公司做了十年寿险代理人的老同事，他因为连续3个月不开单，被迫离职了。”在保险行业“浸淫”20多年的某寿险支公司负责人黄超叹息道，“送走的人里，不仅有来了几个月就离职的新人，也有很多共事了数年的老搭档。”

黄超告诉北京商报记者，以前，很多小学没毕业的叔叔阿姨都可以从事保险销售工作。虽然这些人不懂得如何讲产品，甚至都分不清产品类型，但他们在工作过程中依靠人情、依靠情感，就能够完成签单。

实际上，“被迫离开”并不限于有形的裁员，市场环境的变迁也让一部分年龄较大的营销员无所适从，黄超有些无奈：“‘70后’早已把市场交到了‘80后’‘90后’手中，最早的‘80后’已经年过40岁。现在保险消费的‘主力军’是年轻人，这些叔叔阿姨们似乎和年轻人产生了代沟。他们中的很多人都不懂得互联网营销，甚至看不清字小如蚂蚁般的条款，更不用说进行双录等烦琐操作。以前那种靠感情、靠人情就能签单的时代已经一去不复返了，是这个时代把他们淘汰掉了。时代抛弃他们，甚至连个招呼都没有打。”

“现在我这个团队里，还有几位叔叔阿姨在坚持着，不过，离职是早晚的事情。”谈及此处，黄超的神色越发凝重。

虽然保险消费呈现出不断年轻化的发展趋势，但目前35-55岁的营销员仍占据了主体地位，《中国保险中介市场生态白皮书》显示，从保险营销员的年龄分布上看，35-45岁的营销员占比为40.52%，45-55岁的营销员占比为20.09%，也就是说，35-55岁的营销员占比超过了60%。

逆行者期待明天

在百万代理人离职潮中，仍有一些“逆行者”，这些新生力量或多或少是通过保险公司新颖的宣传方式招进来的，在北京生活的王莉便是其中之一。她在疫情中无意听到了一节免费的保险课程，便对保险代理人这一职业重新树立起了认识。

“保险公司获得新鲜血液的方式五花八门。”王莉说道，目前公司会举办免费美甲活动、户外野餐、徒步、免费送保险知识课程等活动，通过邀请三五好友参加的形式，让更多人了解保险，这也让一些人加入了代理人的大家庭。

此前，王莉曾在一家防骚扰科技企业工作，一个偶然的机会，让她重新认识了保险代理人这一职业，于是她毅然辞去工作。当然，鼓动她跳槽的原因是她大学期间学习的是保险专业。

对于“回归主业”的王莉来说，跳槽的代价是失去了共事多年的同事情谊，还有家人的冷眼相待以及前公司老板在她走后的例会上的笑侃。她无奈吐槽道：“都2021年了，竟然还有人以为保险是骗人的。”

入职以来，身边的代理人走得比日子过得都快。和她同期进来的，很多人选择了离开。王莉表示，“其中不乏奋斗多年的主管们，他们面临着北漂的生存压力，嫌赚钱少、收入低，还未离职就已经物色好了下家。也有一些应届毕业生觉得卖保险看不到前途，上几天班直接不来了”。

虽然身边代理人离开的很多，但王莉不认为自己是大潮中的逆行者，依然发朋友圈鼓励自己：“我们即便普通，但只要不下场，都会随着时代潮水不断向前。”