---
title: 设计自己的商业模式
author: 硅谷王川
date: '2021-01-03'
slug: '138'
categories:
  - Translation Articles
tags:
  - Business
  - Personal
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

> 这是四篇文章的合集

# [做一个大规模并联者](https://mp.weixin.qq.com/s?__biz=MzA3MzE5MjM2Mw==&mid=2672246965&idx=1&sn=803fb7180cdc05ee25f3faa9d9e30e45&chksm=85a12671b2d6af67ec5e9187ae1fe984083fb86b9db782878280b8879913c50be56904c7c750&scene=21#wechat_redirect)

最近看到斯坦福大学神经生物学专家，骆利群教授的文章 (中译文参见公众号“神经现实”）
为何人类大脑如此高效？
有感而发。(骆教授是科大少年班 81级校友，笔者的同系师兄，现为美国科学院院士. 英文原文来自于 "Think Tank: 40 neuroscientists explore the biological roots of human experience"一书,  原文标题 "The Brain Achieves Its Computational Power through a Massively Parallel Architecture - 大脑通过大规模并行架构实现其计算威力", 编辑者 David Linden)

1/ 大部分人的工作方式是类似串联系统。学一个专业，有一个雇主，走一条路，或者同一个时间只能服务一个客户。

2/ 有许多客户的公司类似并联系统，有几千/几万/几百万甚至更多客户的公司/明星就是大规模并联。

3/ 串联者的体验，和大规模并联者是两个截然不同的世界。虽然孤立地观察，他们好像在做同一件事。

4/ 串联者关心的是，其串联路径上的某个连接会不会断掉，因此想方设法去维护与其连接节点的关系。遇到困难瓶颈时会不断内省，而不是思考在外部建立新的连接绕过去。

5/ 大规模并联者关心的是，如何在耗费同样能量的情况下，建立更多有机连接。因此，他第一关心的是连接节点的群体特征，而不去迎合单个节点的特殊需求。第二关心的是，如何在单位时间内同等能耗下，提升连接的效率。第三关心的是，外界环境涌现出什么新的东西，可以建立新的大规模连接。可以参见笔者的老文章：


6/ 串联系统的最大问题是，任何一个连接点上的误差，会在连接步骤中叠加放大。不管你在任何单一连接上做得多好。

7/ 智能大脑来自于神经元大规模并联的连接。“哺乳动物神经元平均有数以千计的输入和输出. 与之相比，单个晶体管总共只有三个输入和输出节点...单个神经元表达的信息可能是嘈杂的（精确度为1/100）。通过从100个带有同样信息的输入神经元中取均值，下游的神经元伙伴可以提取精确度更高的信息（约千分之一） " -- 摘自骆利群教授的 "The brain achieves its computational power through a massively parallel architecture" 原文

8/ 大规模并行的连接，因为其高并行度，导致下游的信息更加精准。这是其相对于串行计算系统的能耗低很多的重要原因之一。

9/ 同理，拥有大规模并联的连接者，可以获得来自外部世界的精度更高的信息，因而更加真实地理解认识客观世界。而不是像串联者那样，被少数样本的不具代表性的信息变本加厉地误导。这也是为什么高手看似举重若轻，新手疲于奔命却总不得其法的根本原因之一。

10/ 串联者是脆弱的，少数连接被切断会导致其整个世界的塌陷，因此其内心是常常焦虑的.

11/ 大规模并联者是反脆弱的，部分连接被切断，只会自然推动他把精力转移到在别处建立新的大规模连接。因此其内心是平静的，对未来是不断好奇和憧憬的.

12/ 大脑神经元放电频率最多每秒 1000次，对应计算速度每秒一千次。现在普通 PC 的计算速度可以超越每秒一千亿次 （ 十万 MIPS）。大脑能耗 （约十瓦） 也只有普通  PC 的十分之一。但除了一些明确定义的计算任务之外，大规模并行处理的人脑之抽象学习思维能力，是以串行计算架构为主的能耗高得多的电脑目前无法比拟的.

13/ 大脑之所以是大规模并联的架构，不是来自某个主观设计，而是因为其它的架构都在自然选择中因为能耗过大，精度太低，过于脆弱而被淘汰掉了。

14/ 神经元的大规模并行连接，自发涌现出大脑这样复杂的系统。同理，可以高效率建立大规模并联关系的社会，可能涌现出和大脑一样复杂的东西。

15/ 大规模并联，可以彻底弥补个体能力的短板。与其把个体的某个专项能力做到极致，不如把与外界的大规模并行连接做到极致。在同等能耗的情况下，超大规模的并行连接，可以高效实现一些在个体缺乏与外界连接时，完全无法想象的事情。

16/ 高效建立大规模并联的一个方法，就是坚持把自己的深度思考付诸文字，通过各种社交媒体传播出去。

        
17/ 数量就是质量，巨大的连接数量带来的是新维度上的完全不同的东西。


18/ 财富，知识，力量，大脑的自我意识，本质上都是一个从外界高效吸取能量的，开放的，大规模并行网络。聚焦在培育开放网络的大规模有机增长，好的结果自然发生，没有上限。只关注局部几根线的连接或者某个静态的目标，而忽视网络的培育和建设，很容易被外界环境的波动所摧毁，或者被新涌现出来的发展方向所抛弃。

19/ 做一个大规模并联者，从今天开始。

---

# [如何做一个超级连接者](https://mp.weixin.qq.com/s?__biz=MzA3MzE5MjM2Mw==&mid=2672246940&idx=1&sn=e7103661d8428b9a13d4450ddda3e36a&chksm=85a12658b2d6af4e45821da51abcebfe4445299562ca0f35d2e67a56f574194b1ef2bc2a667b&scene=21#wechat_redirect)

最近读了 Scott Gerber 的 ”Super connector“, 和 Erica Dhawan 的 “Get big things done: the power of connectional intelligence", 有感而发。

1/ 和外界建立广泛和有价值的关系，是事业成功的超级助推器。但连接绝不是到处发名片，微信或LinkedIn 加好友。要建立有效的连接，人首先要有自知之明。

2/ 自知之明的最重要一点是不要以己度人。这包括多个方面，不能以小人之心度君子之腹，也不能以君子之心度小人之腹。不能以穷人的消费价值观来揣测富人，反之亦然。不能以男性的视角价值观和女性沟通，反之亦然。

3/ 人的本性是习惯性从自己的角度和价值观看问题，很少主动从他人的角度看问题，理解他人的需要。许多让你困惑觉得不可思议的问题，其实换个角度，从别人的视角看，非常简单明白不过。但如果不能够跨过这个坎，学会从对方视角理解问题，完全沉浸在自己大脑臆想的泡沫里，就会犯各种低级错误。

4/ 大部分做销售的人，一开始都没有自知之明，想问题完全不是从听众角度来思考。这表现在上来就不断介绍吹嘘自己，用自己的语境来表达，而完全不去聆听理解听众的要求，不去思考自己是否真正能够解决别人的问题。

5/ 另外一个例子是，很多人完全没有任何自我介绍，就去要求不熟悉的人引荐工作，介绍资源，寻求投资，完全是自说自话。别人凭什么要这么做啊？

6/ 这种做法可以叫做“阿Q跪拜吴妈式”：大约在公元一九一零年前后的某一天，阿Q唐突地跪在吴妈面前，自说自话地表白，“吴妈，我想要和你困觉！”。  我们都知道后来发生了什么。

7/ 这种低级的连接方式，如果不彻底改正，效果差，效率低，只是自欺欺人。

8/ 没有经验的年轻人犯这种低级错误可以理解。关键是有错就改。但如果工作十几年了，还是这样不长进，就很可笑了。

9/ 要改进，第一， 要谋求长期的互惠合作关系。如果你内心只是想做一锤子买卖，而对对方的利益诉求并不真正关心，大家都不是傻子，马上就可以感觉到，对你的要求也就只是随便敷衍。一锤子买卖的效率，长期看是非常低的。而长期合作积累出来的名声和信任，可以极大压低商业成本。

10/ 第二，平时要多积点善缘。有好的东西，要主动去分享。人性的 reciprocity (回馈的生物本能）是极为强大的。如果你主动释放善意，给别人以帮助，那么有心人都会本能地给你更大的回馈。当然，这个也要看对象。说话听声，如果别人没兴趣反应冷淡，就不必那么积极。


把自己的思考心得，通过写作公开发表出去，就是一种高效的分享方式


11/ 第三，花更多时间寻找和你可以互补合作的伙伴，这样你可以做真实的自己。大部分人的错误是浪费大量时间在没有资源互补关系的人身上，并且因此扭曲了自己的天性，去做一些自己不擅长不喜欢的事。


12/ 第四，在和外界的连接过程中，不断探索”邻近可能性“，拓深拓广自己的实力，这样自身才有更多机会和外界产生增益互补 (synergistic) 的关系，并形成良性循环.


13/ 第五，要设置边界，知道何时说”不“，不能让外人随意影响你的时间和行为计划。

14/ 第六，要多和那些自身有着高质量连接，并且乐于助人的人连接。把时间集中在最靠谱的 1%身上，可以更容易地把自己也变成这样的人。


15/ 普通人，无法理解有着大量的，多维度连接的超级连接者，为什么做事会如此容易。但这需要时间培养，没有捷径。只关心短期结果，不思考构建长期体系的人，他们永远努力奔跑在去解救下一个燃眉之急的道路上。

---

# [做一个独特而稀缺的人](https://www.chainnews.com/articles/799820179442.htm)

1/ 大部分人无法发财，最主要的原因，是自己做的事很容易被替代。

2/ 学的东西 （输入） 和 做的东西 （输出） 和别人一样，没有什么独到和与众不同的东西。 这就过滤掉 99.9 % 的人 了 .

3/ 即使有独到的东西，还需要大规模宣传，建立自己的品牌和一定规模的共识。这又过滤掉 99% 的人了。

4/ 有独特的东西和有品牌之后，还有关键一步：需要有意识去控制供给，制造稀缺性，实践稀缺性溢价的艺术，把利润最大化。

可参见笔者的老文章：

5/ 因为独特，所以无法替代 ； 因为有品牌和共识，就有需求 ； 当不可替代的供给无法满足强劲的需求时，就会产生稀缺，就会有巨大的溢价。

6/ 直播网红的打赏， 百度淘宝和币圈的竞价排名， 网络游戏道具的出售，都是这类模式的直观体现。

7/ 这个惊人的溢价是很多有成见的人不愿理解，无法理解，也永远不会理解的。

8/ 技术和效率可以产生独特，可以产生流量，但不一定必然产生稀缺和溢价。这是维技术论者必须小心而不可大意的。

9/
前面几点做到之后，要可持续地发展，必须把部分利润用来回到第一步，把东西做得更独特更好，生态更全面更深，品牌影响力更大，稀缺性和溢价更大，这样形成正反馈循环。

10/ 总结一下就是： 独特 - 品牌 - 稀缺 - 生态 -- 正反馈循环。没有人可以一步登天，但在正确的路上走的时间越长，和普通人的差距就会越拉越大。

11/ 即使自己做不到，看到那些极少数做到了的人或者公司，要能够看得懂，要知道如何参与其中分享其部分成长果实；
而不是愤世嫉俗地胡喷，眼睁睁看着好机会从面前流失。

12/ 乔布斯 1998 年开启 “Think different" 的宣传时，有多少人真正理解？至少笔者当时没有做到，有着亲身的惨痛教训。

13/ 今天还有多少自以为是的无聊看客，继续重复笔者当年的错误？

14/做一个独特而稀缺的人，本质就是自己掌握了自己的印钞权
。毕加索，香奈儿，张大千，卓别林，乔布斯，马斯克，特朗普，贝索斯，巴菲特，从这个角度看，是相似的人，只是程度规模有差别而已。

15/ 这样的知识体系，品牌体系，只会随着时间越积越厚；它不怕通货膨胀，可以跨越种族文化和国家的边界，跨越战争与和平的不同时代。

16/ 做一个独特而稀缺的人，从今天开始。

---

# [用摩尔定律武装自己](https://m.huxiu.com/article/337504.html)

1. 摩尔定律本质上是一个经济规律，在一个抽象的层面上，它并不单单绑定某一个具体技术。过去几十年，半导体公司把芯片产品分发到更大的市场，把产品的研发生产费用分摊到更大的基数上，以提高单品的利润率。然后，再把利润投入到技术升级，晶体管小型化，性能提高，再进一步降低单品价格，因为价格降低又发现了更多更大的应用市场，如此不断良性循环。

2. 如果从更长远的历史视角看，按照未来学家 Ray Kurzweil 的话说，摩尔定律只是几百年来，人类的计算技术——从算盘到手摇机械计算机再到继电器、真空管、晶体管，进而到大规模集成电路的演变——在过去五十年的自然体现。

3. 经济规律在计算技术的发展中，自然地选择了脱颖而出的大规模集成电路。但如果硅基的集成电路，在未来某个时间点，计算能力走到极限，同样的经济规律会自然地选择在那个时候涌现出来的最经济的技术方案.

4. 用摩尔定律的机制把自己武装起来，就必须要有原创的属于自己的作品产品，并且可以分发到很多客户手上。普通打工者相当于只有一个客户，没有属于自己的独立的产品，没有能力把自己的创造分发给多个客户，这个道理无法运用。

5. 对于个人而言，要把摩尔定律的机制用于自身的发展，就需要尽量做有这么几个特征的工作：制作成本低、边际成本低、分发成本低、通用性高、有长期价值。

6. 关于制作成本，比如说如果二十年前要做视频，买一个摄像机就要接近一千美元，还只能录到磁带上，转成数字化文件非常麻烦。宽带不普及，很难通过互联网分发。今天做视频，硬件成本摄像机和麦克风都在一百美元以下，非常专业的录像编辑软件一个月只要二十美元，成本是非常低的。边际成本和分发成本基本为零。如果是写软件，不用搭自己的服务器，直接租用亚马逊云服务，还有免费试用期。

7. 通用性高，就是你的产品服务能够潜在让很多人受益，而不是为了某个单独客户的非常小众的定制化需求。这里面最大的坑，就是很多定制化的工作来钱快，所以很多人为了赚这点小钱，就把自己宝贵的时间精力浪费消磨在上面了， 就永远迈不出利用摩尔定律发展自己事业的这条路。

8. 有长期价值，就是要避免那些时效性比较高的工作，比如做新闻工作的人，天天追逐一些当下热点，但过了几个月早就没有人追那些时事了。网红天天直播带货，虽然可以卖点钱，但是每天仍然要出台，他做的工作不能多年后仍然被反复引用。

9. 如果你做的产品作品满足这几个条件，那么下一步关键是，不断要找到更大的平台，更大的市场，把自己的边际成本低，分发成本低的产品推广出去。

10. 把自身的产品服务推广到最大的市场上，用来自市场的收入进一步提高产品质量，增加产品功能，降低产品单价，提高产品的通用性，这样可以进一步发展到更多更大的市场上。

11. 这种做法，最大的障碍在于发展的早期，因为自己可以接触到的客户比较少，无法产生利润，利润很小，甚至要很长一段时间忍受较大的损失。相当于你需要一个长长的跑道， 可以支持你滑呀滑，支持你达到正现金流，可以起飞。

12. 以前，很多产品制造成本高，边际成本高，分发成本高。现在，软件文字音像等等产品制作成本极低，边际成本分发成本也接近为零， 尤其是现在有了各种区域性、全球性的巨大的社交媒体平台。而社交媒体，就提供了这样一个快速起飞的跑道。今天个体拥有的几乎免费的信息资源的广度深度，都超过十年前一个亿万富翁花很多钱获得的信息基础设施。

13. 摩尔定律的特点，在于指数增长。指数增长在认知上的最大盲点，就是它的最大收获期在增长曲线的末端。

14. 荷塘上的荷叶，每天面积翻一倍，生长三十天就长满荷塘。但是一直到第二十七天， 他还只覆盖池塘的八分之一，还不是很显眼。你如果没有坚持到最后第三十天，你的收获差异会很大。这和我们干一天活拿一天的钱的直觉，差别很大。

15. 以 Netflix 为例，2009年十月之前十二个月的付费用户增长了两千八百万。而它从1997年到2011年花了十四年才获得两千三百万付费订户。Youtube 2006年成立，它2016年一年用户上传的视频时间长度的总量，超过之前十一年的总和。然后 2017年到2018年，又在这个基础上翻了一番，用户生态，广告生态很快就繁荣起来了。

16. 所以如果你的产品作品如果能够有这种指数增长的潜质的话，即使现在每个月只挣一块钱，价值也胜过现在每个月挣一百块但是不具有扩展性无法增长的业务。

17. 要对产品的功能、市场的推广不断做微调，以顺应增长的趋势。不能说一根筋只做一个方向的东西，比如说摩尔定律是晶体管密度每18个月～24个月翻一番，开始很长一段时间就是通过晶体管小型化，提高cpu的时钟速度实现。后来cpu速度到2002年底就到头了，再快就会出现过热问题。后来设计方向改为增加芯片内置的缓存cache的容量，增加系统并行度，走三维路线等等，来增加芯片的计算能力。未来芯片即使物理上的小型化路线走到尽头了，只要有办法让单位成本的计算能力每18个月翻一番，摩尔定律的路线仍然可以继续发展下去。

18. 以此为启发：如果你的产品在某个平台市场增长饱和了，就要争取朝别的更大的平台推广。或者朝别的维度，增加新的功能内容以适应新的市场增长方向。   

19. 对于个人而言，这种微调的能力是基于制作成本低和分发成本低的基础的。如果制作成本高，分发成本高，你是没有本钱做这种方向调整的。

20. 小结一下， 利用摩尔定律的机制把个人武装起来，主要就是这么几点：

做那些制作成本低、边际成本低、分发成本低、通用性高、有长期价值的东西。

不断拓展分发到新的市场，在利用获得的收入增加新的通用性高，有长期价值的更复杂功能和内容， 然后拓展到更大的应用市场。要灵活微调方向。最重要的是坚持到底， 要等到指数增长的曲线发展到一个巨大的体量。等你的客户受众达到巨大的规模，上千万甚至上亿的时候，你会发现这是一个全新的境界，后面越来越容易。

21. 那些听上去很厉害的大公司，和你的最大区别，无非就是他可以把产品卖给几百万人，你现在暂时只能卖给几个人而已。

22. 如果有几百万人以上的分发渠道，获得几百万人的信任，商业模式会自然涌现。即使你自己不知道套现，会有别人来请你帮你套现。

23. 但最后套现并不是最终目的，有最大数目的信任你的潜在客户和受众，就是最大的财富，不要为了短期利益而辜负他们的信任。
