---
title: 'The Once and Future Superpower: why China won''t overtake the United States'
author: Stephen G. Brooks; William C. Wohlforth
date: '179'
slug: the-once-and-future-superpower-why-china-won-t-overtake-the-united-states
categories:
  - Translation Articles
tags:
  - Politics
  - China
  - America
  - Insights
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---


 [Source](https://digitalcommons.dartmouth.edu/cgi/viewcontent.cgi?article=1133&context=facoa)

After two and a half decades, is the United States’ run as the world’s sole superpower coming to an end? Many say yes, seeing a rising China ready to catch up to or even surpass the United States in the near future. By many measures, after all, China’s economy is on track to become the world’s biggest, and even if its growth slows, it will still outpace that of the United States for many years. Its coffers overflowing, Beijing has used its new wealth to attract friends, deter enemies, modernize its military, and aggressively assert sovereignty claims in its periphery. For many, therefore, the question is not whether China will become a superpower but just how soon.

But this is wishful, or fearful, thinking. Economic growth no longer translates as directly into military power as it did in the past, which means that it is now harder than ever for rising powers to rise and established ones to fall. And China—the only country with the raw potential to become a true global peer of the United States—also faces a more daunting challenge than previous rising states because of how far it lags behind technologically. Even though the United States’ economic dominance has eroded from its peak, the country’s military superiority is not going anywhere, nor is the globe-spanning alliance structure that constitutes the core of the existing liberal international order (unless Washington unwisely decides to throw it away). Rather than expecting a power transition in international politics, everyone should start getting used to a world in which the United States remains the sole superpower for decades to come. Lasting preeminence will help the United States ward off the greatest traditional international danger, war between the world’s major powers. And it will give Washington options for dealing with non- state threats such as terrorism and transnational challenges such as climate change. But it will also impose burdens of leadership and force choices among competing priorities, particularly as finances grow more straitened. With great power comes great responsibility, as the saying goes, and playing its leading role successfully will require Washington to display a maturity thatU.S. foreign policy has all too often lacked.

# THE WEALTH OF NATIONS

In forecasts of China’s future power position, much has been made of the country’s pressing domestic challenges: its slowing economy, polluted environment, widespread corruption, perilous financial markets, non- existent social safety net, rapidly aging population, and restive middle class. But as harmful as these problems are, China’s true Achilles’ heel on the world stage is something else: its low level of technological expertise compared with the United States’. Relative to past rising powers, China has a much wider technological gap to close with the leading power. China may export container after container of high- tech goods, but in a world of globalized production, that doesn’t reveal much. Half of all Chinese exports consist of what economists call “processing trade,” meaning that parts are imported into China for assembly and then exported afterward. And the vast majority of these Chinese exports are directed not by Chinese firms but by corporations from more developed countries.

When looking at measures of technological prowess that better reflect the national origin of the expertise, China’s true position becomes clear. World Bank data on payments for the use of intellectual property, for example, indicate that the United States is far and away the leading source of innovative technologies, boasting $128 billion in receipts in 2013—more than four times as much as the country in second place, Japan. China, by contrast, imports technologies on a massive scale yet received less than $1 billion in receipts in 2013 for the use of its intellectual property. Another good indicator of the technological gap is the number of so-called triadic patents, those registered in the United States, Europe, and Japan. In 2012, nearly 14,000 such patents originated in the United States, compared with just under 2,000 in China. The distribution of highly influential articles in science and engineering—those in the top one percent of citations, as measured by the National Science Foundation—tells the same story, with the United States accounting for almost half of these articles, more than eight times China’s share. So does the breakdown of Nobel Prizes in Physics, Chemistry, and Physiology or Medicine. Since 1990, 114 have gone to U.S.-based researchers. China-based researchers have received two.

Precisely because the Chinese economy is so unlike the U.S. econ- omy, the measure fueling expectations of a power shift, gdp, greatly underestimates the true economic gap between the two countries. For one thing, the immense destruction that China is now wreaking on its environment counts favorably toward its gdp, even though it will reduce economic capacity over time by shortening life spans and raising cleanup and health-care costs. For another thing, gdp was originally designed to measure mid-twentieth-century manufacturing economies, and so the more knowledge-based and global-ized a country’s production is, the more its gdp underestimates its economy’s true size.

A new statistic developed by the un suggests the degree to which gdp inflates China’s rel- ative power. Called “inclusive wealth,” this measure represents economists’ most systematic effort to date to calculate a state’s wealth. As a un report explained, it counts a country’s stock of assets in three areas: “(i) manufactured capital (roads, buildings, machines, and equipment), (ii) human capital (skills, education, health), and (iii) natural capital (sub-soil resources, ecosystems, the atmosphere).” Added up, the United States’ inclusive wealth comes to almost $144 trillion—4.5 times China’s $32 trillion.

The true size of China’s economy relative to the United States’ may lie somewhere in between the numbers provided by gdp and inclusive wealth, and admittedly, the latter measure has yet to receive the same level of scrutiny as gdp. The problem with gdp, however, is that it measures a flow (typically, the value of goods and services produced in a year), whereas inclusive wealth measures a stock. As The Economist put it, “Gauging an economy by its gdp is like judging a company by its quarterly profits, without ever peeking at its balance-sheet.” Because inclusive wealth measures the pool of resources a government can conceivably draw on to achieve its strategic objectives, it is the more useful metric when thinking about geopolitical competition.

But no matter how one compares the size of the U.S. and Chinese economies, it is clear that the United States is far more capable of converting its resources into military might. In the past, rising states had levels of technological prowess similar to those of leading ones. During the late nineteenth and early twentieth centuries, for example, the United States didn’t lag far behind the United Kingdom in terms of technology, nor did Germany lag far behind the erstwhile Allies during the interwar years, nor was the Soviet Union backward techno- logically compared with the United States during the early Cold War. This meant that when these challengers rose economically, they could soon mount a serious military challenge to the dominant power. China’s relative technological backwardness today, however, means that even if its economy continues to gain ground, it will not be easy for it to catch up militarily and become a true global strategic peer, as opposed to a merely a major player in its own neighborhood.

---

# BARRIERS TO ENTRY

The technological and economic differences between China and the United States wouldn’t matter much if all it took to gain superpower status were the ability to use force locally. But what makes the United States a superpower is its ability to operate globally, and the bar for that capability is high. It means having what the political scientist Barry Posen has called “command of the commons”—that is, control over the air, space, and the open sea, along with the necessary infrastructure for managing these domains. When one measures the 14 categories of systems that create this capability (everything from nuclear attack submarines to satellites to transport aircraft), what emerges is an overwhelming U.S. advantage in each area, the result of decades of advances on multiple fronts. It would take a very long time for China to approach U.S. power on any of these fronts, let alone all of them.

For one thing, the United States has built up a massive scientific and industrial base. China is rapidly enhancing its technological inputs, increasing its R & D spending and its numbers of graduates with degrees in science and engineering. But there are limits to how fast any country can leap forward in such matters, and there are various obstacles in China’s way—such as a lack of effective intellectual property protections and inefficient methods of allocating capital—that will be extremely hard to change given its rigid political system. Adding to the difficulty, China is chasing a moving target. In 2012, the United States spent $79 billion on military R & D, more than 13 times as much as China’s estimated amount, so even rapid Chinese advances might be insufficient to close the gap.

Then there are the decades the United States has spent procuring advanced weapons systems, which have grown only more complex over time. In the 1960s, aircraft took about five years to develop, but by the 1990s, as the number of parts and lines of code ballooned, the figure reached ten years. Today, it takes 15 to 20 years to design and build the most advanced fighter aircraft, and military satellites can take even longer. So even if another country managed to build the scientific and industrial base to develop the many types of weapons that give the United States command of the commons, there would be a lengthy lag before it could actually possess them. Even Chinese defense planners recognize the scale of the challenge.


Command of the commons also requires the ability to supervise a wide range of giant defense projects. For all the hullabaloo over the evils of the military-industrial complex and the “waste, fraud, and abuse” in the Pentagon, in the United States, research labs, contractors, and bureaucrats have painstakingly acquired this expertise over many decades, and their Chinese counterparts do not yet have it. This kind of “learning by doing” experience resides in organizations, not in individuals. It can be transferred only through demonstration and instruction, so cybertheft or other forms of espionage are not an effective shortcut for acquiring it.

China’s defense industry is still in its infancy, and as the scholar Richard Bitzinger and his colleagues have concluded, “Aside from a few pockets of excellence such as ballistic missiles, the Chinese military- industrial complex has appeared to demonstrate few capacities for designing and producing relatively advanced conventional weapon sys- tems.” For example, China still cannot mass-produce high-performance aircraft engines, despite the immense resources it has thrown at the effort, and relies instead on second-rate Russian models. In other areas, Beijing has not even bothered competing. Take undersea warfare. China is poorly equipped for antisubmarine warfare and is doing very little to improve. And only now is the country capable of producing nuclear-powered attack submarines that are comparable in quietness to the kinds that the U.S. Navy commissioned in the 1950s. Since then, however, the U.S. government has invested hundreds of billions of dollars and six decades of effort in its current generation of Virginia-class submarines, which have achieved absolute levels of silencing.

Finally, it takes a very particular set of skills and infrastructure to actually use all these weapons. Employing them is difficult not just because the weapons themselves tend to be so complex but also be- cause they typically need to be used in a coordinated manner. It is an incredibly complicated endeavor, for example, to deploy a carrier bat- tle group; the many associated ships and aircraft must work together in real time. Even systems that may seem simple require a complex surrounding architecture in order to be truly effective. Drones, for example, work best when a military has the highly trained personnel to operate them and the technological and organizational capacity to rapidly gather, process, and act on information collected from them. Developing the necessary infrastructure to seek command of the commons would take any military a very long time. And since the task places a high premium on flexibility and delegation, China’s cen- tralized and hierarchical forces are particularly ill suited for it.

---

# THIS TIME IS DIFFERENT

In the 1930s alone, Japan escaped the depths of depression and morphed into a rampaging military machine, Germany transformed from the disarmed loser of World War I into a juggernaut capable of conquering Europe, and the Soviet Union recovered from war and revolution to become a formidable land power. The next decade saw the United States’ own sprint from military also-ran to global super- power, with a nuclear Soviet Union close on its heels. Today, few seriously anticipate another world war, or even another cold war, but many observers argue that these past experiences reveal just how quickly countries can become dangerous once they try to extract military capabilities from their economies.

But what is taking place now is not your grandfather’s power transi- tion. One can debate whether China will soon reach the first major milestone on the journey from great power to superpower: having the requisite economic resources. But a giant economy alone won’t make China the world’s second superpower, nor would overcoming the next big hurdle, attain- ing the requisite technological capacity. After that lies the challenge of transforming all this latent power into the full range of systems needed for global power projection and learning how to use them. Each of these steps is time consuming and fraught with difficulty. As a result, China will, for a long time, continue to hover somewhere between a great power and a superpower. You might call it “an emerging potential superpower”: thanks to its economic growth, China has broken free from the great-power pack, but it still has a long way to go before it might gain the economic and technological capacity to become a superpower.

China’s quest for superpower status is undermined by something else, too: weak incentives to make the sacrifices required. The United States owes its far-reaching military capabilities to the existential imperatives of the Cold War. The country would never have borne the burden it did had policymakers not faced the challenge of balancing the Soviet Union, a superpower with the potential to dominate Eurasia. (Indeed, it is no surprise that two and a half decades after the Soviet Union collapsed, it is Russia that possesses the second-greatest military capability in the world.) Today, China faces nothing like the Cold War pressures that led the United States to invest so much in its military. The United States is a far less threatening superpower than the Soviet Union was: however aggravating Chinese policymakers find U.S. foreign policy, it is unlikely to engender the level of fear that motivated Washington during the Cold War.

Stacking the odds against China even more, the United States has few incentives to give up power, thanks to the web of alliances it has long boasted. A list of U.S. allies reads as a who’s who of the world’s most advanced economies, and these partners have lowered the price of maintaining the United States’ superpower status. U.S. defense spending stood at around three percent of gdp at the end of the 1990s, rose to around five percent in the next decade on account of the wars in Afghanistan and Iraq, and has now fallen back to close to three percent. Washington has been able to sustain a global military capacity with relatively little effort thanks in part to the bases its allies host and the top-end weapons they help develop. China’s only steadfast ally is North Korea, which is often more trouble than it is worth.

Given the barriers thwarting China’s path to superpower status, as well as the low incentives for trying to overcome them, the future of the international system hinges most on whether the United States continues to bear the much lower burden of sustaining what we and others have called “deep engage- ment,” the globe-girdling grand strat- egy it has followed for some 70 years. And barring some odd change of heart that results in a true abnegation of its global role (as opposed to overwrought, politicized charges sometimes made about its already having done so),  Washington will be well positioned for decades to maintain the core military capabilities, alliances, and commitments that secure key regions, backstop the global economy, and foster cooperation on trans- national problems.

The benefits of this grand strategy can be difficult to discern, especially in light of the United States’ foreign misadventures in recent years. Fiascos such as the invasion of Iraq stand as stark reminders of the difficulty of using force to alter domestic politics abroad. But power is as much about preventing unfavorable outcomes as it is about causing favorable ones, and here Washington has done a much better job than most Americans appreciate.

For a largely satisfied power leading the international system, having enough strength to deter or block challengers is in fact more valuable than having the ability to improve one’s position further on the margins. A crucial objective of U.S. grand strategy over the decades has been to prevent a much more dangerous world from emerging, and its success in this endeavor can be measured largely by the absence of outcomes common to history: important regions destabilized by severe security dilemmas, tattered alliances unable to contain breakout challengers, rapid weapons proliferation, great-power arms races, and a descent into competitive economic or military blocs.

Were Washington to truly pull back from the world, more of these challenges would emerge, and transnational threats would likely loom even larger than they do today. Even if such threats did not grow, the task of addressing them would become immeasurably harder if the United States had to grapple with a much less stable global order at the same time. And as difficult as it sometimes is today for the United States to pull together coalitions to address transnational challenges, it would be even harder to do so if the country abdicated its leader- ship role and retreated to tend its garden, as a growing number of analysts and policymakers—and a large swath of the public—are now calling for.

---

# LEAD US NOT INTO TEMPTATION

Ever since the Soviet Union’s demise, the United States’ dramatic power advantage over other states has been accompanied by the risk of self-inflicted wounds, as occurred in Iraq. But the slippage in the United States’ economic position may have the beneficial effect of forcing U.S. leaders to focus more on the core mission of the coun- try’s grand strategy rather than being sucked into messy peripheral conflicts. Indeed, that has been the guiding logic behind President Barack Obama’s foreign policy. Nonetheless, a world of lasting U.S. military preeminence and declining U.S. economic dominance will continue to test the United States’ capacity for restraint, in four main ways.

First is the temptation to bully or exploit American allies in the pursuit of self-interested gain. U.S. allies are dependent on Washington in many ways, and leaning on them to provide favors in return— whether approving of controversial U.S. policies, refraining from activities the United States opposes, or agreeing to lopsided terms in mutually beneficial deals—seems like something only a chump would forgo. (Think of the Republican presidential candidate Donald Trump’s frequent claims that the United States always loses in its dealings with foreigners, including crucial allies, and that he would restore the country’s ability to win.) But the basic contract at the heart of the contemporary international order is that if its members put aside the quest for relative military advantage, join a dense web of institutional networks, and agree to play by common rules, then the United States will not take advantage of its dominance to extract undue returns from its allies. It would be asking too much to expect Washington to never use its leverage to seek better deals, and a wide range of presidents—including John F. Kennedy, Ronald Reagan, George W. Bush, and Obama—have done so at various times. But if Washington too often uses its power to achieve narrowly self- interested gains, rather than to protect and advance the system as a whole, it will run a real risk of eroding the legitimacy of both its leadership and the existing order.

Second, the United States will be increasingly tempted to overreact when other states—namely, China—use their growing economic clout on the world stage. Most of the recent rising powers of note, including Germany, Japan, and the Soviet Union, were stronger militarily than economically. China, by contrast, will for decades be stronger economically than militarily. This is a good thing, since military challenges to global order can turn ugly quickly. But it means that China will mount economic challenges instead, and these will need to be handled wisely. Most of China’s efforts along these lines will likely involve only minor or cosmetic alterations to the existing order, important for burnishing Beijing’s prestige but not threatening to the order’s basic arrangements or principles. Washington should respond to these gracefully and with forbear- ance, recognizing that paying a modest price for including Beijing within the order is preferable to risking provoking a more fundamental challenge to the structure in general.

The recent fracas over the Asian Infrastructure Investment Bank is a good example of how not to behave. China proposed the aiib in 2013 as a means to bolster its status and provide investment in infra- structure in Asia. Although its criteria for loans might turn out to be less constructive than desired, it is not likely to do major harm to the region or undermine the structure of the global economy. And yet the United States responded by launching a public diplomatic campaign to dissuade its allies from joining. They balked at U.S. opposition and signed up eagerly. By its reflexive opposition both to a relatively constructive Chinese initiative and to its allies’ participation in it, Washington created an unnecessary zero-sum battle that ended in a humiliating diplomatic defeat. (A failure by the U.S. Congress to pass the Trans-Pacific Partnership as negotiated, meanwhile, would be an even greater fiasco, leading to serious questions abroad about U.S. global leadership.)

Third, the United States will still face the temptation that always accompanies power, to intervene in places where its core national interests are not in play (or to expand the definition of its core national interests so much as to hollow out the concept). That temptation can exist in the midst of a superpower struggle—the United States got bogged down in Vietnam during the Cold War, as did the Soviet Union in Afghanistan—and it clearly exists today, at a time when the United States has no peer rivals. Obama has carefully guarded against this temptation. He attracted much criticism for elevating “Don’t do stupid stuff” to a grand-strategic maxim. But if doing stupid stuff threatens the United States’ ability to sustain its grand strategy and associated global presence, then he had a point. Missing, though, was a corollary: “Keep your eye on the ball.” And for nearly seven decades, that has meant continuing Washington’s core mission of fostering stability in key regions and keeping the global economy and wider order humming.

Finally, Washington will need to avoid adopting overly aggressive military postures even when core interests are at stake, such as with China’s increasingly assertive stance in its periphery. It is true that Beijing’s “anti-access/area-denial” capabilities have greatly raised the costs and risks of operating U.S. aircraft and surface ships (but not submarines) near China. How Washington should respond to Beijing’s newfound local military capability, however, depends on what Washington’s strategic goals are. To regain all the military free- dom of action the United States enjoyed during its extraordinary dominance throughout the 1990s would indeed be difficult, and the actions necessary would increase the risk of future confrontations. Yet if Washington’s goals are more limited—securing regional allies and sustaining a favorable institutional and economic order—then the challenge should be manageable.

By adopting its own area-denial strategy, for example, the United States could still deter Chinese aggression and protect U.S. allies despite China’s rising military power. Unlike the much-discussed Air-Sea Battle doctrine for a Pacific conflict, this approach would not envision hostilities rapidly escalating to strikes on the Chinese main- land. Rather, it would be designed to curtail China’s ability during a conflict to operate within what is commonly known as “the first island chain,” encompassing parts of Japan, the Philippines, and Taiwan. Under this strategy, the United States and its allies would employ the same mix of capabilities—such as mines and mobile antiship missiles—that China itself has used to push U.S. surface ships and aircraft away from its coast. And it could turn the tables and force China to compete in areas where it remains very weak, most notably, undersea warfare.

The premise of such a strategy is that even if China were able to
deny U.S. surface forces and aircraft access to the area near its coast, it would not be able to use that space as a launching pad for project- ing military power farther during a conflict. China’s coastal waters, in this scenario, would turn into a sort of no man’s sea, in which nei- ther state could make much use of surface ships or aircraft. This would be a far cry from the situation that prevailed during the 1990s, when China could not stop the world’s leading military power from enjoying unfettered access to its airspace and ocean right up to its territorial border. But the change needs to be put in perspective: it is only natural that after spending tens of billions of dollars over decades, China has begun to reverse this unusual vulnerability, one the United States would never accept for itself.

While this area-denial strategy would help solve a long-term prob- lem, it would do little to address the most immediate challenge from China: the military facilities it is steadily building on artificial islands in the South China Sea. There is no easy answer, but Washington should avoid too aggressive a reaction, which could spark a conflict. After all, these small, exposed islands arguably leave the overall military balance unchanged, since they would be all but impossible to defend in a conflict. China’s assertiveness may even be backfiring. Last year, the Philippines—real islands with extremely valuable basing facilities—welcomed U.S. forces back onto its shores after a 24-year absence. And the United States is now in talks to base long- range bombers in Australia.

To date, the Obama administration has chosen to conduct so-called freedom-of-navigation operations in order to contest China’s mar- itime claims. But as the leader of the order it largely shaped, the United States has many other arrows in its quiver. To place the burden of escalation on China, the United States—or, even better, its allies— could take a page from China’s playbook and ramp up quasi-official research voyages in the area. Another asset Washington has is inter- national law. Pressure is mounting on China to submit its territorial disputes to arbitration in international courts, and if Beijing continues to resist doing so, it will lose legitimacy and could find itself a target of sanctions and other diplomatic punishments. And if Beijing tried to extract economic gains from contested regions, Washington could facilitate a process along the lines of the proportional punishment strategy it helped make part of the World Trade Organization: let the Permanent Court of Arbitration, in The Hague, determine the gains of China’s illegal actions, place a temporary tariff on Chinese exports to collect exactly that much revenue while the sovereignty claims are being adjudicated, and then distribute them once the matter is settled before the International Court of Justice. Whatever approach is adopted, what matters for U.S. global interests is not the islands themselves or the nature of the claims per se but what these provocations do to the wider order.

Although China can “pose problems without catching up,” in the words of the political scientist Thomas Christensen, the bottom line is that the United States’ global position gives it room to maneuver. The key is to exploit the advantages of standing on the defensive: as a raft of strategic thinkers have pointed out, challenging a settled status quo is very hard to do.

---

# KNOW THYSELF

Despite China’s ascent, the United States’ superpower position is more secure than recent commentary would have one believe—so secure, in fact, that the chief threat to the world’s preeminent power arguably lies within. As U.S. dominance ebbs slightly from its peak two decades ago, Washington may be tempted to overreact to the set- backs inherent in an admittedly frustrating and hard-to-manage world by either lashing out or coming home—either way abandoning the patient and constructive approach that has been the core of its grand strategy for many decades. This would be a grave mistake. That grand strategy has been far more successful and beneficial than most people realize, since they take for granted its chief accomplishment— preventing the emergence of a much less congenial world.

One sure way to generate a wrong-headed push for retrench- ment would be to undertake another misadventure like the war in Iraq. That America has so far weathered that disaster with its global position intact is a testament to just how robust its superpower status is. But that does not mean that policymakers can make per- petual blunders with impunity. In a world in which the United States retains its overwhelming military preeminence as its eco- nomic dominance slips, the temptation to overreact to perceived threats will grow—even as the margin of error for absorbing the costs of the resulting mistakes will shrink. Despite what is being said on the campaign trail these days, the United States is hardly in an unusually perilous global situation. But nor is its standing so secure that irresponsible policies by the next president won’t take their toll.
