---
title: 美国会率先复苏 中国将二次探底
author: 方三文
date: '2022-02-04'
slug: '394'
categories:
  - Translation Articles
tags:
  - Investment
---

>神人，和之前 whigzhou 的预测一模一样

自2008年全球金融危机暴发之后，主流的观点都认为，美国的经济中心地位将动摇，中国为代表的新兴市场，将率先引导世界经济复苏。

做预言难免有大言欺市之嫌，我今天斗胆做一个相反的预言：美国经济会率先复苏，而中国经济可能二次探底。

为什么美国能率先复苏？几个原因：

首先是美国房价这个最大的资产泡沫，已经彻底引爆，美国房价即使不回升，也不会再大幅下跌了。这样房价下跌引起的家庭资产负债表恶化不会继续，消费者就不会因此再大幅削减家庭支出。

作为对这个论点的佐证，美国房屋销售和汽车销售正在稳步回升。美国三大汽车制造商福特、通用、克莱斯勒集团均宣布刚刚过去的5月汽车销售同比增长了10%。

就业的数据比销售数据更加意义，奥巴马刚刚在卡内基梅隆大学发表演讲时说， 5月非农就业报告将表明美国就业总量已开始强劲增长。

这些背后的一个情况是，美国政府的“救市”行动是有限的，除了救助金融机构之外，并没有过多直接干预经济，也没有巨额放贷催生新的资产泡沫。

所以，美国经济的增长动力更多来自企业创新和用户需求，是健康和可持续的。相比欧洲和中国而言，美国的情况最好，所以有可能率先复苏。

为什么中国要二次探底？

核心问题就是房价为代表的资产泡沫。2008年本来房价是可以软着陆的，结果却演绎了一出惊天大反弹，现在泡沫比2008年还厉害。这泡沫引起了严重的后果：

一是政府调控骑虎难下，房价涨也有问题降也有问题；二是资金和其他资源都往房地产投资里挤，导致实体经济的资源抽逃，这为经济增长埋下了很大隐患。江浙和珠三角很多早年做实业成功的人士，近年都已经完全没有兴趣再做实业，把工厂交给人打理，自己跑到全国各地去炒房。这样，怎么能指望他们改进产品质量，改良服务、增加就业机会呢？

当然，如果完全是市场化的话，炒房也未必一定是坏事，炒房的人多了，会吸引企业加大投资，改进房屋产品的质量，增加房屋产品的供应量，最后达成市场的平衡。

但是，现在的调控措施是限制房地产业上游的土地和资金的供应，这样，下游的房地产投资行为把价值往上游传输的链条完全断了，房地产就真的成了没有价值的零和游戏。如果一个游戏搞到这个程度，玩不下去是迟早的事。

所以现在这个泡沫，谁都不愿去搞破，甚至不敢去搞破，但最后可能还是会破。一旦破裂，它必将引发经济上的连锁反应，只好承担二次探底之痛。近期公布的中国制造业和汽车销售数据，都不理想，这说明对房价及房地产市场的担忧，已经传递到房产之外的行业去了，值得警惕。

如果这个推测成立，那么现在适当增持一些能从美国经济复苏中受益的股票，应该有一定获利机会。但同时要注意的是，股市和实体经济并不完全是同步的，并且波动幅度通常要大于实体经济的波动幅度，所以获利的机会也不是百分百的。