---
title: 好玩的事
author: VicodinXYZ
date: '2021-03-18'
slug: '169'
categories:
  - Translation Articles
tags:
  - Investment
---

[Source](https://m.weibo.cn/detail/4472185659954099)


又到了 13-F 文件季度性披露的时候。之前简单提过几句这个东西，这次就不细讲了。只说两个看到的有点好玩儿的小事情。

第一个是，李录的喜马拉雅资本久违地发布了 13-F，上面只有一家公司，美股的半导公司美光科技（MU）。这个公司我不太熟悉就不多说，不过作为帮芒格管钱的人，李录主要投资的是亚洲公司，这是他为数不多的美股持仓（13-F 只需要披露美股持仓），400m/16B 差不多是 2.5% 的仓位。

第二件好玩的事，是 Michael Burry 前两大持仓：Gamestop （GME）和 Tailored Brands（TLRD）。而且合起来占比超过基金规模的 1/3 了，可谓是重仓投入。这俩公司是什么情况呢？

第一个公司，打游戏的同学可能有点概念，就是美国那种街边连锁的电玩商店，卖点 PS、Xbox、Switch 游戏机、游戏卡带、电影 DVD 和周边手办之类的。这生意不用我说你也知道，过去十年早被亚马逊阿里这种线上电商，加上主机和 PC 游戏的数字化浪潮冲击地七零八落了。从股价上也能看出来——GME 2007 年底曾经达到的历史最高价是 42 美元，现在多少钱呢？4 块钱左右。市值只有 2.6 亿美元。看起来已经无可救药了。

第二个公司——可能是我不太熟悉这个小众行业——就更不知道是干啥的了。看官网描述，TLRD 是卖男装的，还有租赁燕尾服的业务，还是个四十多年的老牌公司。不过具体怎么卖我也不确定，但公司运营状况绝对很差——目前处于亏损状态，而股价 2015 年还有 60 美元之多，现在居然也是 4 块钱。总市值是悲惨的 1.9 亿美元。

就这么两个公司，被 Michael Burry 看上了并且重仓持有，我觉得还挺有意思的。需要提到的一个背景是，Burry 在 2007-2008 年做空次贷危机一战成名之前，其实是个如假包换的价值投资者，而是是格雷厄姆那种「捡烟蒂」风格的价投，天天算公司 book value 的那种。早年间他在自己的博客上写公司研究心得，写的都是那种根本没人关注的、经营看起来非常凄惨的小破股票，现在有些内容还能找到。结果就是靠研究投资这种冷门地板价公司，Burry 不仅吸引了 Vanguard 和 Joel Greenblatt 这样的成名机构和个人投资者，还在 2000-2005 年获得了巨大的超额回报，把自己基金的管理规模翻了上百倍。尤其是 2002 年这种整个市场下跌超过 20% 的年头，Burry 的回报居然是 16%。后来他的兴趣从小破股转移到了房地产次级贷市场，and the rest is history。

换句话说，「捡垃圾」可谓 Michael Burry 的看家本领和成名之作。时过境迁，2020 年这个时点他又回到了老本行，下注了两家看起来有点悲惨的公司。而且据我粗（hu）略（luan）估算，这两家公司目前股价都在他买入成本价的 20% 以下。Burry 还能再次顶住压力，化腐朽为神奇么。他还会打起他心爱的架子鼓么？（大雾）时间一定会给我们答案。