---
title: “葡萄界爱马仕”跌落神坛?
author: 红星新闻
date: '2021-08-30'
slug: '271'
categories:
  - Translation Articles
tags:
  - Business
  - Economics
  - Firm Behavior
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

[Source](https://www.msn.cn/zh-cn/news/national/%e2%80%9c%e8%91%a1%e8%90%84%e7%95%8c%e7%88%b1%e9%a9%ac%e4%bb%95%e2%80%9d%e8%b7%8c%e8%90%bd%e7%a5%9e%e5%9d%9b%ef%bc%9f6%e5%b9%b4%ef%bc%8c%e4%bb%8e%e6%af%8f%e6%96%a4300%e5%85%83%e8%b7%8c%e8%87%b3%e6%af%8f%e6%96%a410%e5%85%83-%e2%80%9c%e9%98%b3%e5%85%89%e7%8e%ab%e7%91%b0%e2%80%9d%e6%80%8e%e4%b9%88%e4%ba%86%e2%80%a6/ar-AANBArR?ocid=mmx)

>其实是经济学的常识，[蛛网模型](http://headsalon.org/archives/651.html)说的也是这件事，另外，在[塑造观念世界](https://guanghuamao.netlify.app/2020/12/01/96/)一文中，我也表达了相应的意思。可见“闷声发大财”还是很有道理的，但是不可能一直瞒得下去，所以还是要靠“市场失灵”。

一度进超市卖到每斤300元的天价、有着“葡萄中的爱马仕”之称的阳光玫瑰葡萄，近几年在网络和市场上很是火了一把。

这个2010年从日本引进的葡萄品种，2015年开始走进国内大众的视野，并逐渐流行。起初由于其价格昂贵，很长一段时间维持在每斤百元以上，引发众多谈资，成为一款“网红明星水果”。



如今，又一个6年过去。近日，红星新闻走访调查四川、云南等多个阳光玫瑰葡萄产地发现，这个顶着网红光环的“奢侈品水果”，价格神话未能延续，正逐年呈大幅下降趋势，今年上市以来批发价大多在每斤10至20多元。特别是8月以来，国内多地阳光玫瑰葡萄陆续上市，部分地方售价甚至已跌至每斤10元以下。与6年前相比，阳光玫瑰葡萄的价格跌幅惊人，已然走进了普通人的果盘。

从每斤300元跌到几元、十几元，6年时间，阳光玫瑰葡萄身上到底发生了什么？这是否意味着它已开始走下“神坛”，种植前景还会“阳光”吗？红星新闻记者走访多位种植户、收购商以及业内专家，希望能找到背后的答案……

# 【跌落】



曾风光卖到300元一斤

去年开始大跌，今年更低至每斤10元

阳光玫瑰葡萄系从日本引进的品种，当年进超市售价一度高达300元一斤，但从2020年开始在国内市场每斤售价已降至几十元。今年，西昌的市价已跌至每斤几元、十几元不等。

当下，正是阳光玫瑰葡萄上市季。四川西昌市作为“中国晚熟葡萄之乡”，葡萄种植面积超过10万亩，是四川省种植阳光玫瑰最多的地区。

8月18日，西昌永辉超市里的阳光玫瑰葡萄售价每斤8.98元

8月18日上午，在西昌市长安农贸批发市场内，成都游客杨女士买了20斤阳光玫瑰葡萄，准备带回家分享给亲戚朋友。购买价格仅每斤10元，这让她很惊讶：“这是不是我认识的阳光玫瑰葡萄啊？”她最早接触到此品种是在2016年，参加团购的价格高达每斤100元。“去年这个时候，我在西昌购买过阳光玫瑰葡萄，价格在18元一斤，没想到今年价格便宜这么多”。

红星新闻记者了解到，阳光玫瑰葡萄是从日本引进的品种，原产地是日本冈山县，因口感细腻果实饱满，而价格昂贵，素有“葡萄中的爱马仕”“葡萄中的茅台”之称。

据公开报道，问世之初，这种葡萄在日本一串售价曾高达500元人民币，平均一颗10元。2010年，我国开始引进阳光玫瑰，但直到2015年前后才逐渐走进大众视野。刚开始，阳光玫瑰葡萄进入超市时售价一度在每斤300元；后来，随着产量增加价格略有下降，不过徘徊在每斤百元左右。但从2020年开始，该品种在国内市场每斤售价已降至几十元，甚至部分地区每斤价格一度下跌至三四元。

今年，阳光玫瑰葡萄的价格继续呈现大幅下降趋势，水果销售商也深有感触。“去年，像这个品质比较好的阳光玫瑰葡萄价格卖到了40多元一斤，而今年最高都没有超过20元。”西昌的水果批发商杨女士告诉红星新闻，相比去年，今年阳光玫瑰葡萄价格近乎“腰斩”，“尽管价格降了，但到处都是卖阳光玫瑰葡萄的，竞争很大，市场并不理想”。

连日来，红星新闻记者在西昌走访发现，目前，阳光玫瑰葡萄的市场价格每斤几元、十几元不等，甚至有商贩吆喝“十元三斤”的贱价大甩卖。不过，多名水果销售商表示，目前，这种几元一斤的阳光玫瑰品质比较差，“像西昌本地产的大多价格在十几元一斤”。

阳光玫瑰的市场价格波动，也直接影响到种植户的收益。走进西昌市太和镇太安村，放眼望去全是葡萄大棚，这里是西昌种植阳光玫瑰最集中的区域之一，村民陈光红是远近闻名的种植户。

2019年，陈光红的7亩多阳光玫瑰开始挂果，投产第一年就卖了40多万元；2020年，这7亩多阳光玫瑰开始丰产，产值达到了107万元，除去人工、肥料等成本，利润有90多万元，创造了一个暴富神话。然而，他的7亩多阳光玫瑰今年未能继续创造奇迹。陈光红告诉红星新闻，今年7月初，他家的阳光玫瑰再次丰收，是西昌最早上市的一批，但价格比去年低了不少，“去年，最高的时候批发每斤卖28元，最低也卖近20元，但今年最高也就卖到每斤19元，后面每斤十四五元，在西昌都算很不错的价格了”。

陈光红表示，他家的葡萄品质和去年都差不多，但受市场及价格下跌因素影响，今年7亩多阳光玫瑰只卖了60余万元。“虽然价格降了，但一亩还是有8万元产值，与以前种粮食相比，收益还是高了不少”。

# 【“过山车”】


从“白富美”到“平民化”

收购商：阳光玫瑰葡萄走进普通人果盘

陈岩是河南郑州人，从事葡萄收购十多年，每年在全国各地收购阳光玫瑰葡萄，货源主要供应大型超市，年销售额数千万元。这些年，他见证了阳光玫瑰价格“过山车”式的变化。

陈岩告诉红星新闻，云南是全国阳光玫瑰葡萄最早上市的地区，每年五六月份，云南建水、宾川为代表的第一批阳光玫瑰葡萄上市，“我们今年最高的收购价在50元一斤，但那个时候量非常小，主要是吃个‘鲜’，当地阳光玫瑰大量上市之后，收购价也就在15元一斤左右”。

工人正在包装阳光玫瑰葡萄

云南阳光玫瑰葡萄在全国产区中一直备受关注，价格也一直位居高位。对此，陈岩分析原因有三：其一， 云南的阳光玫瑰是全国产区最早的，上市时间早价格自然高；其二，云南产区的种植技术和品质上要比其它产区好；其三，云南本身气候就独特。不过，陈岩也表示，相比早期“物以稀为贵”的时候，这两年云南阳光玫瑰价格是降下来了，“2018年，我们在云南建水收购过近百元一斤的阳光玫瑰葡萄”。

陈岩介绍，进入七月之后，云南的阳光玫瑰接近尾声，四川西昌等地的阳光玫瑰开始上市。今年7月中旬，陈岩从云南转战西昌收购阳光玫瑰葡萄，以368万元的价格收购了西昌市建兴村的丰源农业基地60亩阳光玫瑰葡萄，“这是今年我们在西昌收购的第一批阳光玫瑰，每斤价格大约16元左右，而去年首批收购价在每斤20多元”。

“虽然目前阳光玫瑰葡萄已在全国普及，但整体看来，云南建水、宾川和四川西昌的品质最好。从今年的收购价行情来看， 每斤价格比去年同期跌了至少5至10元。”7月20日，陈岩在接受红星新闻采访时表示，量少价格高是所有商品的普遍现象，但随着阳光玫瑰大量上市，价格下降是必然趋势。

陈岩表示，最近几年，阳光玫瑰种植在全国各地疯狂扩张，到了去年基本在全国普及，“现在南到云南、广东、广西，到东北的辽宁，都有大量的种植。”进入八月下旬之后，全国各地的阳光玫瑰陆续上市，由于上市期集中，价格跌幅也更明显，部分地区价格降至冰点，预计今年的收购价会跌至每斤5至10元。“从去年的情况来看，有的地方最低收购价仅4元一斤”。

说起阳光玫瑰葡萄，浙江温岭的种植户谢永斌则用“一落千丈”来形容。谢永斌表示，他五六年前开始小规模试种阳光玫瑰，今年发展扩大到110亩。种植面积增长的同时，价格却在不断下跌。“前几年批发每斤30多元，现在只有七八元，当然这跟我今年葡萄上市时间推迟，又遇上部分地方疫情反弹也有关系”。

红星新闻记者调查发现，各产区“阳光玫瑰”的价格行情差异较大，两极分化严重，每斤从几元至几十元价格不等，市场价格悬殊主要与品质直接挂钩。而在一些大型的电商平台上，阳光玫瑰的价格大多为每斤十多元，甚至七八元的也有，主打低价。

8月18日下午，陈岩告诉红星新闻，截至目前，国内的阳光玫瑰葡萄价格已经下跌至每斤8元至13元，与7月相比每斤又下降了5元。 “目前，市场上几元一斤的阳光玫瑰也比较多了，价格从‘白富美‘到‘平民化’，阳光玫瑰逐渐成为人们果盘中的常客，成为老百姓都能吃得起的水果”。

# 【疯狂】



高昂利润吸引农户入圈

种植面积暴增，今年将破100万亩

“几乎每年的种植面积都在翻番。”湖南澧县种植户陈伟觉得有点“疯狂”，当时他看到每个村基本都在发展葡萄，“不管你走在那条路，绕到哪里，你看见的都是阳光玫瑰”。

红星新闻记者调查发现，近年来，阳光玫瑰价格走下“神坛”，与国内种植面积爆发式增长也有很大的关系。自2015年以来，在高昂利润的驱使之下，越来越多农户开始投身阳光玫瑰的怀抱，种植面积也在不断激增。

据中国科学院果树研究所不完全统计，2020年，全国阳光玫瑰葡萄种植面积已达80万亩，而且还在扩增，今年将突破100万亩。值得一提的是，2016年时，全国种植面积仅有几万亩，增长速度可谓惊人。

疯狂扩种的背后，是超高的经济收益。甘先生是云南建水县的一名农场主。2017年，他听说附近的农场主依靠40亩“阳光玫瑰”卖出700多万元，就将自家的几百亩夏黑葡萄全部换成了阳光玫瑰。目前，他经营着360亩阳光玫瑰，年总产量约500吨，年销量4000万元。红星新闻记者了解到，近5年来，阳光玫瑰葡萄在建水县迅速“成长”，种植规模达到3万亩，占云南省三分之一。2020年，建水县阳光玫瑰葡萄产量突破万吨，产值达4.8亿元。

湖南澧县的种植户陈伟说，他从2016年开始种植，那时整个县不超过几百亩，2018年就一下子涨到了3000亩，2019年挂果面积达到1万亩以上，2020年则达到2.4万亩。

四年前开始，陈伟在云南、陕西、河南等地收购阳光玫瑰，他亲眼看到，最疯狂的时候，云南有的种植户一车货能赚30万元，有的人一年轻松赚到1000~2000万。“2017~2019年，阳光玫瑰可以说是一门‘暴利’生意。”在澧县，大户一亩阳光玫瑰轻轻松松就能赚到5至7万元，对更精耕细作的小户来说，一亩地甚至可以赚到7至10万元。

四川西昌的种植户陈光红也深有感触，三四年前，当地种植阳光玫瑰的农户很少，在每亩可赚几万、十万元的暴利驱使下，部分农户把原本种植的夏黑葡萄、红提都换种为阳光玫瑰。“农产品跟风，一旦发现好的品种，大家就一拥而上，扩大规模，就怕错过了赚钱的机会。最疯狂的2018年，只看到村里的大棚拔地而起，以前全是一望无际的土地，现在望去全是葡萄大棚”。

红星新闻记者从西昌市相关部门获悉，截至2020年，该市阳光玫瑰种植面积达到1万余亩。

然而，在种植面积暴增之下，阳光玫瑰葡萄产量剧增，但也导致品质参差不齐。有业内人士表示，有的种植户为了赶上高价期，还没完全成熟便采摘上市，“优质的阳光玫瑰，糖度要达到18~19度，但有人可能为了赶一波行情，在糖度14~15度时就采摘销售了。这样不仅价格上不去，还无形之中伤害了整个行业”。还有的种植户会过量使用膨大剂和植物生长剂人为缩短葡萄生长周期，影响了阳光玫瑰的营养成分和风味，损害了阳光玫瑰的品质。

有网友称，今年吃到的味道似乎不如去年，“在不同的生鲜平台买了几次阳光玫瑰，味道感觉像是退化了一样”，这引发了众多网友的共鸣。

# 【危机】


“天价”并非常态

产量增加价格下降是必然，应控产增质

一面是高涨的种植热情，另一面却是逐年走低的行情，种植户们也逐渐嗅到了危机，“现在种植面积越来越大，价格年年在下降，至于以后能不能赚钱，很难说”。

“前景依然看好，国内的发展还处于初级阶段，但应考虑市场饱和度安排种植，切忌盲目跟风。无论任何品种，一旦产量增加，价格下降是必然的。光注重产量是不行的，品质才是核心。”对于阳光玫瑰葡萄的迅速扩张，多位业内人士表达了相同的观点。

“自2017年以来，全国各地都在跟风种植。但葡萄主要消费市场，还是10至20元每公斤。”国家葡萄产业技术体系首席科学家、中国农业大学教授段长青曾在接受采访时认为，“阳光玫瑰”的生产成本较高、用工量大，不宜盲目扩种。

“现在全国各地都在种，但种出一流品质的不多。”四川省农科院园艺所研究员刘晓表示，各地的气候、地理环境和栽培技术不同，因而果粒大小、糖度和香味不同，不是所有阳光玫瑰都能卖出高价。

面对阳光玫瑰葡萄持续走低的市场行情，云南、西昌等地的多位企业负责人表示，虽然其总体产量上去了，但整个市场果品精品率依旧很低，应该坚持精品化种植，持续提升果品市场竞争力。“如果能种出好品质的果子，相信依然能够卖出好价钱”。

西昌市大兴乡丰源农业基地场长罗华俊在接受红星新闻采访时表示，基地于2014年建园，期间由于管理、技术等问题，在种植阳光玫瑰葡萄过程中经历过曲折。近几年，基地总结种植经验、教训，并寻求到院校技术支持，还成立了技术团队，所以果品产量和品质有了保障。“河南的老板一口气包下60亩地的果子，今年行情较去年有所下滑，但我们的售价每斤却比去年高了四五元，这就是品质提升价格的最好证明”。

谈及今年阳光玫瑰葡萄行情，罗华俊认为，由于该品种葡萄供应量激增，导致行情下跌，但精品果仍受市场青睐。

中科院果树研究所专家王海波表示，阳光玫瑰葡萄大量上市后，品质定会参差不齐，虽然价格波动是由市场决定，但品质却能自己决定，“好价格还需自身硬”，优质品种依然能卖出好价格，因此不用过分悲观。不过，他同时提醒农户，应考虑市场饱和度安排种植，切忌盲目跟风，无论任何品种，一旦产量增加，价格下降是必然的，当前与其扩大产量，不如控产增质，鉴于阳光玫瑰属丰产品种，增质才是盈利的出路。

6年，从每斤300元的天价到如今的几元、十几元，阳光玫瑰葡萄走进普通人的果盘，成了“贵族水果平民价”的典型之一。对此，有业内人士表示，“天价”并非常态，“阳光玫瑰”的价格终究要回归市场，任何品种只有走入寻常百姓家，才有生命力。