---
title: 身心健康故事 2 则：葛伟与王银达
author: 谷雨实验室
date: '2020-10-26'
categories:
  - Translation Articles
tags:
  - Business
  - Chinese
slug: '68'
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---


[第二个故事](https://zhuanlan.zhihu.com/p/77742566)

> 那些原先爱他的人现在憎恨他（没错，就是憎恨）、鄙夷他，亲近的朋友反目，连家里的保姆也发短信指责他。财富投下的阴影曾遮蔽过很多东西，现在全部展现在他眼前。

> 破产的地产商人葛伟决定把自己的故事讲出来。2020年4月，他录下一段视频迅速走红。负债几个亿是什么感受？罗永浩或许可以回答这个问题，他转发了关于葛伟的新闻。

> 从更长的时间轴看，生于60年代的葛伟是中国最典型的地产商人，他出身普通，靠做广告赚到第一桶金，之后成为中国第一代炒房者。至少在人生的前五十年中，葛伟都是当仁不让的赢家，而赢家总是正确的。他的情怀、偏执和一点点傲慢可以被容忍，但当规则变化，故事又是另外一种讲法了。


# 破产之后

空旷的房间中，一匹铜马的存在显得有些突兀。它有半个人那么高，前蹄微抬，昂然挺立。这是葛伟18年前从泰国买来的，光运费就花了七八千。它用料厚实，指节敲击会发出低沉的闷响。从原先的家里搬出来时，葛伟放弃了价值百万的实木家具和家电，唯一留下了这匹马，他觉得它会一直陪伴自己。“现在有点委屈它了。”葛伟坐在沙发里，注视着铜马，“它不应该在这么小的房子里。”

仅仅五年前，这匹马坐镇的地方还是重庆一间七百多平米的独栋别墅，独立泳池、桑拿房、家庭影院一应俱全，13间房里装置了286盏灯，开起来像个闪闪发光的城堡。别墅前种着三棵双生银杏树，这是葛伟专门从济南运到重庆的，每棵十几万。

一到秋天，金黄的落叶洒满庭院，银杏果啪嗒啪嗒掉在地上，家里的五位保姆就拾起它们，剥开洗净，煮汤的时候放进去几颗。

如果不是那次破产，无论从任何角度评价，地产商人葛伟都是人们眼中的成功人士。他踏准了时代的步点，身段轻盈，而回报是巨大的财富。但当可以立足的阶梯垮塌，他开始怀疑自己——和所有失败的人一样怀疑自己。

从2014年开始，房地产行业转冷，虽然之后还有波动，但大趋势已不可逆转。葛伟身边，有做生意的朋友自杀了，还有的心力衰竭而死。2020年4月，葛伟录下一段视频迅速走红：“今天是我54岁生日，我还没死……”

命运的逆转发生在6年前的7月24日，那天重庆的气温高达38.5度，燥热难耐。在办公室里不断踱步的葛伟接到银行打来的电话，他此时的负债已达3.7亿，债务涉及5家银行、3家贷款公司和38位个人债主。在这之前的两年时间里，他每天要支付15万元利息。他扛不住了。挂掉电话之后，他做出停息的决定，这意味着他将背上“老赖”的名号，连同巨额债务一起将他拖入深渊。

他点上十六年来的第一支烟，从办公室的弧形落地窗里，他看到拥堵的车辆和人群，不知他们在过着怎样的生活，是否也和自己一样绝望呢？也是从那时起，他不再敢去阳台，连通往阳台的玻璃门也不打开。他没想过自杀，而是执拗地暗示自己“我不能死”——后来精神科医生告诉他，这其实是一个意思。正常人不会去想“我不能死”。

现在这间月租金两千元的房子紧靠重庆滨江路，在阳台上就能看到不远处的嘉陵江。房间陈设简单，客厅里除了沙发和电视几乎不再有任何东西。尽管已经在这里住了3年，但房间的住客似乎随时准备离开。当然，鉴于租客的身份，你依然能看到一些财富的痕迹。卫生间里的浴巾一条两千多，CK的；小厕纸篓1100元，他已经忘了牌子，只记得它来自意大利。

搬进这栋三十年来住过最小的房子后，葛伟选了最小的房间当卧室，不到十平米，几乎没什么下脚的地方。逼仄的空间让他觉得安全，也更温暖一些。书桌上方原先贴着世界地图，上面的五十多个色块都曾留下过他的脚印。这是很久以前的事了，现在世界地图换成了重庆地图。

破产后，他意识到自己必须重新学会做一个“普通人”，甚至为此颇受鼓舞。但当他第一次站上轻轨站的时候，这一切又显得太陌生和艰难了。他懵懂又拘谨，在人群中躲闪，像个从乡下来的穷亲戚，连交通卡也不知道去哪儿办。他不愿意接触轻轨上的扶手，就像能一眼看见上面布满的细菌一样——干净是生活的第一准则——手机支付出现之前，他甚至只用刚从银行里取出的新钱。

他有洁癖。有一次，他在轻轨上看见身前的乘客起身离开，为了让座位上的余温和气味散去，他在心中默念十几秒再坐下，而身后的大姐没有给他这个机会。那么现在呢？“老子先抢到（座位）再说！”他摆出一副跷二郎腿的样子。

两种生活的转换并不那么顺利。过往的生活在他身上留下了确凿的痕迹，他追求精致、高雅，如果无法分辨哪些更好，就买最贵的那一个。房间里的一切都是纯色的，衣橱里纯黑的衣服，纯灰的床单。

纯白碗碟是最近才有的，在这之前，他吃了几年的外卖，偶尔自己动手下厨，要提前去超市买一次性餐盒，用完了直接丢掉。二十多岁的时候，葛伟就住上别墅了，最少的时候也有两个保姆照顾他——一个做清洁，一个做饭。“你说我会做什么？”他摊了摊手。

放在几年前，他无论如何也想象不到，一个人每月花一万块钱居然也能生活。之前有员工想涨500块钱工资，葛伟大手一挥，“500块能干什么？”现在他终于意识到，500块可不只能买一份牛排，还能交一家人一个月的水电费。

---

# 负债上亿的人

葛伟身材消瘦，戴一副黑框眼镜，一排小胡子密密匝匝立在上唇，像个倔老头。他习惯穿一件没有logo的黑色Polo衫，原先是杰尼亚，现在换成了二百块的优衣库，两者都是纯色，“但感觉不一样了”。

他自认和那些房地产商不是一路人，床边几摞哲学经济学书籍就是证据之一。他喜欢聊情怀（事实证明这可能是商人的负资产），或者德意志第三帝国的兴亡。在生意人的饭局里，他是滔滔不绝的那一个。这是他获得尊重的方式。但后来他发现一个残酷的事实，事情不需要那么复杂，他所拥有的财富是“1”，除此之外的东西都是后面跟着的“0”。

至少在商人的圈子里，一个人能得到的尊重是以财富的数量为标尺的。在刚刚过去的、以房子为核心的兴旺年代里，房地产商是各种场合的座上宾——按葛伟的话说，是“商业的顶端”。当饭局中有人被介绍为房地产开发商，人们不免把酒杯压得低一点，“这都是不用讲的”。

但现在呢？他输光所有筹码，变成“老赖”，一个“过街老鼠”，守信人成了失信人——他反抗过这个称呼，“你知道的，我们（认识）二十几年，我是非常讲信用的”。他跟很多人讲这句话，即便不能抚平债权人的愤恨，还是一遍一遍地讲。

有一次，在重庆江北嘴一间高级写字楼，朋友鲁磊反驳他：“说这些有什么用？现在不还钱还讲啥子？”之后他就没再说过。每一通电话都在催他还钱，给他送法院传票的快递小哥都露出鄙夷的神色。他不断撕挠心口那块皮肤，脱掉衣服就是一道道血印子，就好像孤独和痛苦幻化成了实体，淤塞在他胸口，随时就要爆炸。

对葛伟来说，失去财富这件事本身或许并不那么重要，至少不是最重要的。可怕的是，尊严和信心伴随金钱一起消失了。尊严不是面子，跟豪车、豪宅，或者上百万的实木家具无关——那是生意人充场面的玩意儿。

那种令人恐惧的感觉十分真切，他感到自己内在的价值被摧毁。前来讨债的人一波接一波。有人来硬的，拿刀威胁他，他并不害怕，当年因为拆迁问题被二百号人围着，他也没怕；有人来软的，二话不说跪下来求他，说借给他的二十万是老母亲捡矿泉水瓶攒下的。他听得落泪，可还是没办法。债主们用指节重重地砸他面前的大理石桌面，“咚咚咚”，直到现在这绝望的声响还会在他头脑中回荡。

在财富的巨大落差中，隐匿的人性被赤裸裸地撕开。几年前，名下一家公司破产清算时，他派人去公司清理保险柜，而掌管钥匙的人是葛伟手下的公司老总之一。

在葛伟的讲述中，这个四十多岁的女人出身贫寒，是他一手带出来的，往常对他鞍前马后，“吃火锅我都不用自己夹菜”。葛伟欠了她一些钱，但自认这些年让她赚得更多，结果这位老总并不打算原谅他，她把钥匙扔在满是油污的垃圾桶里，让葛伟的人去捡。

他原先生活在一个温暖的世界。他和他的朋友们去世界各地旅游，每天下午四点就联系去哪里吃饭（友谊地久天长）。直到2014年，还有个身家数亿的朋友向他保证，“再穷不能穷孩子”，意思是，孩子的问题，他来承担。后来葛伟二次创业失败，真正成了孤家寡人，孩子的几万块学费没着落了，葛伟求那位朋友兑现承诺，哪怕是借呢，但对方反倒让他在生活上多节约。

还有一些变化是悄然发生的。朋友们给他孩子包的过年红包，从前些年的七万，逐年递减，今年只剩一万二。他曾怀疑自己是不是变得敏感了，或许有这方面的原因，但现实让他否定了这个想法。有时他想约朋友出来吃饭，电话总是打不通，再打过去，一问就是忙。

“放屁！”他轻蔑地笑了一下，“原来葛伟的电话你敢不接吗？”

事后复盘，如今的惨状大概率可以避免，哪怕手段不那么光彩呢？债务危机爆发时，就有朋友暗示他，提早转移切割一部分财产，或者索性丢下这个烂摊子，到柬埔寨躲避风头。葛伟没答应，他虽然从商多年，但自认有些读书人的清高，无法容忍自己是个不道德的人。

我见到几位葛伟的债主朋友，虽然他们对欠钱这件事颇有不满，但也都不得不承认，他是个讲信用的模范“老赖”。李齐是葛伟的债权人之一，两人是认识二十年的好朋友。作为一个多年从事小额贷款的商人，李齐对债务人的状态非常敏感，他手上至今还有十多起追债官司。常见的情况是，欠钱的人前一天还信心满满地应承会按时还钱，但第二天就再也联系不上了。

2014年后，葛伟破产期间，两人见过几次，看到葛伟头发花白，满脸杂乱的胡须，他心情复杂。那段时间，李齐会时不时地、挑各种时间给葛伟打电话，除了沟通破产进度，还有个隐秘的小心思，为了确认他的朋友没有跑路。

有时候葛伟坐在家里翻手机通讯录，几百个人名滑过去，每一个都是能被称为“朋友”的人，他们原先生活在一个世界里。翻到最后一行，也找不到几个能打电话的。

其实他没想借钱，更不想抱怨（懦夫才这么做）。如果可以的话，他只是想随便聊些什么，哪怕没什么可聊的，到江边走走，或者只是喝杯茶也行。他并不怪罪他们，做了这么多年的生意，利益交换的道理再明白不过，至于自己，“罪人是没有避风港的”。

对于负债上亿的人来说，睡眠也成了一件奢侈的事，他每天吃两粒安眠药，有时更多。更多时候他毫无睡意，就开着车通宵在滨江路上跑。凌晨12点后，万家灯火和霓虹灯都熄灭了，路上几乎没人，他随便找个地方停车，坐在江边一支接一支抽烟。有时候突然想起什么，比如某一桩官司涉及的利息，就慌忙打开手机上的计算器，像神经质一样一遍遍地算。

他试过很多办法打发时间，准确地说是为了把大脑从痛苦的思绪中揪出来一会儿。他有时花几个小时拨弄一片含羞草，看叶子展开又收起。或者整天在重庆街头快走，上上下下，漫无目的，他相信身体的疲劳能抵消精神的痛苦，因为“重庆的棒棒是从来不会失眠的”。

在嘉陵江边，有好几次，他遇上一对捡废品为生的残疾夫妻，他在一边看着，觉得自己和他们同病相怜，便拿出一百块钱给他们。逐渐地，他身上坚硬的倔强盖过了痛苦，“我身上还是有股劲的。”葛伟说，他决心把最后的筹码压上赌桌，“老子不得死！老子要翻起来！”

---

# “做过房地产，你再也不会做其它行业了”


对于葛伟这一批商人来说，成也房地产，败也房地产。

将近三十年前，海南房地产泡沫还没有破灭。在海口的一家酒店里，葛伟以12.5万一亩的价格买到一块土地，拿到建筑图纸和批文之后，连钱也没交，出门转手卖给下家，每亩加三万。在当时，这种玩法叫“炒图纸”——在物理世界没发生任何改变的情况下，一张楼房设计图加一纸批文就能卖出天价，之后再按更高的天价卖出去。人们坚信“总有人会接盘的”，就如同相信明天天上还会掉钱一样。

1988年，海南建省，成立经济特区，一时间出现“十万人才下海南”，楼市成为人们竞相追逐的对象。1991年，海南商品房价格为1400元/平米，两年后就涨到了7500元/平米。巅峰时期，海南一省就有两万多家房地产公司，这里诞生了无数的财富神话，包括后来影响中国房地产市场的万通六君子。

但事实上，这只是一个击鼓传花的游戏，每个人都心知肚明。至于能不能赚钱，一靠胆量二看命。1993年6月，海南的游戏结束了，葛伟是成功上岸的人。

也是在那段时间，他斥资170万买下位于海口的独栋别墅，作为这套房子的中介，他后来的朋友陈松赚走了其中的20万。葛伟感叹，当年赚钱实在太容易了，这也让他更加放胆，“虽然我不赌博，但我赌的都是（更大的），我是一个梭哈的性格”。

每个出生于60年代的人都会面对数不清的机遇，在市场经济的大潮下，世界就像倍速播放的电影一样日新月异。从很年轻的时候起，葛伟就自信这辈子不可能为钱烦恼。他头脑灵活，胆子又大，八十年代在渝州大学（现重庆工商大学）读书的时候，就倒卖过摩托车票，一张卖50块，当时饭店里一盘红烧肉是三毛五分钱。

大学毕业后，他在一份跟城建有关的行业报纸当了一年记者。报社的广告部和编辑部挨着，他一个月拿七十多块钱的时候，广告部的大哥们已经月入上万了。葛伟总能看见他们提着皇冠密码箱，啪嗒一声打开，十元大钞，一千块一扎，塞得满当当。

烟，一条条的阿诗玛——当时是一种高档香烟。“小伙子，抽吧！”大哥们对他说。他原本还有个当作家的梦想，但看见那些作家诗人们的穷酸样，“还是赚钱要紧”。

八十年代是广告行业的拓荒期，而报纸是不多的广告渠道。陈松告诉我，当时他给一位老板写了篇专访，刊登在他供职的小报上，酬金是18万元。加入广告部之后，葛伟赚到了第一桶金。那时他每天四点起床，坐七个小时长途车去各个县市推销广告版面，丰厚的收入给他带来巨大的动力。1988年一年，他就赚了30万，而当年全国职工平均工资为1746元。后来在海南炒房，这笔钱又被成倍地放大。

从行业媒体跳入房地产，这不是偶然。在当时，一个是渠道和流量，一个是刚需。葛伟的报社同事里有位叫吴亚军的年轻人，后来她参与创建了龙湖地产，一度成为中国女首富。2020年，吴亚军以990亿元财富位列《2020胡润全球房地产富豪榜》第12位。

葛伟喜欢读历史，明白一个地区进入发展轨道时，房地产是必不可少的，而彼时内地缺少资本，市场广阔，这往往意味着暴利。很难说这个认识是开拓了他的视野，还是限制了他的视野。在此后二十多年的地产生意中，这个看法逐步僵化，成了他人生经验的一部分——葛伟反复听到并深以为然的一句话是，“做过房地产，你再也不会做其它行业了”。

1997年，重庆设立为直辖市，葛伟和几位合伙人提着现金回乡，成为一个真正的房地产商——他用100万定金购得150亩地，几年的时间，地价飞涨，一进一出之后，他获得上千万利润。

1998年，国家实施以“取消福利分房，实现居民住宅货币化、私有化”为核心的住房制度改革，房地产时代正式拉开大幕。

---

# 财富是一个危险的东西

时代的浪潮制造了多少财富故事，就制造了多少同等的幻觉。葛伟喜欢冒险，这样的人的命运，得到金钱和失去金钱一样，都不完全是理性的结果。多少年以后，葛伟的朋友张怀坐在他位于“西郊庄园”的别墅里，试图总结葛伟的失败。“财富是一个危险的东西。”他说，“这个时代变化太快了，他以为自己在成长，实际上只是膨胀。”

“西郊庄园”是葛伟房地产生涯里最得意的作品。正因为它，葛伟陷入破产的泥潭。庄园里环境清雅，一幢幢淡黄色别墅分布其间，茂密的草木间散落八匹一人高的铜马，马身已经有些斑驳，这是葛伟的审美。

十年前的巅峰时期，葛伟的身价曾高达5个亿。金钱源源不断涌来之后，葛伟的洁癖和自律成了朋友圈中一件稀罕事。做生意几十年来，他几乎不烟不酒，连KTV也极少去，李齐多次邀请他去澳门赌博放松一下，无一不被他拒绝。多年来，他坚持锻炼身体，每天跑步一小时，手机丢在车里，天大的事也找不到他。

葛伟对完美有一种偏执。1999年，葛伟看中了位于重庆九龙坡含谷镇的230亩土地，准备在这里建造别墅区。原因很简单，他认为别墅是人类的终极居住形态，精致、优雅、亲近自然。早在海口那栋别墅居住时，他喜欢在台风来临时赤裸上身，到别墅花园中拥抱风雨。

从理性上讲，当时选择建别墅是一种吃力不讨好的行为。和葛伟一起从海南回乡创业的朋友都选了另一条路：他们买下市中心的地皮建快消商品房，数千套房子三个月一扫而空。内心深处，葛伟看不上这样的生意，他去参观这些朋友的楼盘，朋友兴奋地告诉他，自己买的瓷砖有多便宜，用起来跟那些贵的没什么区别。葛伟没说什么，心中暗想，“怎么会没区别呢？这是给人住的房子，要建就要建最好的。”

那时候的葛伟看起来非常骄傲，听不进别人的意见。尽管很多朋友劝他，应该建一部分小型联排别墅，面积小、总价低，资金回笼快。但葛伟不理会这些建议，他认为别墅是奢侈品，“豪宅，豪的就是空间”。

他对自己的能力很自信。为了完美，2003年，葛伟在建设“西郊庄园”别墅区的时候，请来了加拿大设计师保罗，样板房的装修交给了香港设计师团队。他还专门从四川广汉定制了纯铜马雕塑，每匹27万，就连别墅区里的树木也要严格筛选，每一棵都要高于12.5米的别墅层高。

还是在很多年前，他性格中矛盾的一面就体现出来了。他喜欢交“社会上的朋友”，觉得他们真实、接地气，但又表现得特立独行：一帮人赚到钱就去吃饭打牌，葛伟不打，在麻将桌旁边看书。他喜欢读书。他还开过一家火锅店，叫“鲁尼火锅”——鲁迅加尼采的意思。

在朋友眼中，他不是那种一见面就满脸堆笑的商人，饭桌上遇见品行低俗的人，不管对方是再大的领导或再成功的商人，葛伟只会默默把账结了回家，再不相见。“其实他（赚钱）的机会比我们多很多，但是他都放弃了。”葛伟海南时期的合伙人吴琦说。当时很多人对他的印象是傲慢。我第二次见到葛伟那天，陈松也去他家中做客。说起那时的葛伟，这位江湖气十足的商人坦诚地说：“当年我非常讨厌他。”

上世纪90年代，陈松从海南回来，承接了重庆市政府的城建项目，正为资金发愁。因为当年有过帮他买房的交情，便找到葛伟，希望他给些帮助。但那时的葛伟意气风发，以一种近乎无视的态度拒绝了他。这让陈松深受打击。那次不愉快的接触之后，陈松接下一门公路收费站的生意，巅峰时每天营收二十多万。

对于葛伟来说，别墅似乎成了一种执念。极高的品质要求意味着更大的投入，从2003年起，他开始借入外债，最初是银行，后来是贷款公司，再到个人。这为后来的崩盘埋下伏笔。

在鲁磊看来，葛伟把西郊庄园当成了自己的作品，这是商人的大忌。朋友们认为他是有“情怀”的人。为了“情怀”，葛伟甚至做出一些今天看来颇为荒诞的事。他把普通别墅的售价定在三四百万一栋，湖边别墅卖七八百万，而每栋别墅的成本不到二百万。

李齐对西郊庄园的别墅颇为欣赏，作为朋友，他希望葛伟能给他打个折，购入一套，但葛伟二话没说，拒绝了。当时楼盘做活动，五一期间购入能优惠几万块钱，一位颇有身家的老板带着三位邻居来看房，想每家买一套，只因签合同的时间晚了三天，葛伟拒绝优惠，原价408万的房子抹个零头也不行，最后交易泡汤。

那时候，葛伟的负债已经上亿，而且正像滚雪球一样越滚越多，但在他看来并不是什么问题——资金已经变成资产，是无论如何也跑不掉的。葛伟买地之后，国家就停止批准独栋别墅建设用地，一位银行行长告诉他，再过两三年，西郊庄园的价格还要翻倍。

葛伟下定决心要在这场赌局里死扛到底，宁愿每年缴纳上千万利息，也不愿早点回笼资金，甚至在西郊庄园现金流紧张的时候，他又拿出几千万投资三期楼盘，指望快速卖出三期缓解西郊庄园的窘境。

几年后，市场上联排别墅增加（葛伟不认为那是真正的别墅），通往西郊庄园的路因取消收费站而时常造成大规模拥堵，西郊庄园突然无人问津了。

现在回忆起来，葛伟觉得2010年左右是他最辉煌的时候。那时，负债并不是什么问题，从银行拿钱是再容易不过的事。2008年全球金融危机爆发后，中央投资四万亿用于基础设施建设，之后，这些资金又被地方政府和民间投资成倍放大。

“就像涨大水一样，”现在葛伟的合伙人之一、做建筑机械的刘远告诉我，“只要你在河边，到处都是鱼，找钱的机会多得很，银行追在屁股后面放贷”。葛伟没有察觉到危险即将来临，他指望这场豪赌能有个圆满的结局。

直到2014年，持续的住房供应过剩及去库存政策的推进，导致房地产市场转入低迷。葛伟记忆中，那一年重庆有好几位房地产商破产，当然也包括他自己。

---

# 失败以一种惨败的方式表现出来

2019年10月，葛伟将自己破产的经历写成1.6万字长文，发在新注册的公众号上。之后，无数同病相怜的人找到他，诉说自己的苦痛。

陈松联系到葛伟，自从那次借钱之后，两人已经二十多年没见过了。他们相约在一间咖啡馆，四目相对，感慨万千。早在十年前，陈松就因为资金链断裂破产，在一个充满霉味的地下室里住了两年。现在，他每次出门都会在包里放一副塑料框眼镜，因为看守所里是不让带金属框眼镜的。

48岁的刘远看到文章之后，立马联系葛伟见面。二十多年前，他几乎与葛伟同一时间进入房地产行业，之后创立自己的建筑机械公司，员工最多时达到872人。房地产建筑市场骤然转冷的时候，银行抽贷九千万，公司年产值狂跌90%。

他赌红了眼，拿出家中所有的钱，包括妻子存下的最后几十万块钱，但局面没有丝毫回旋。他躲在朋友家里，一些债主找到他老家，扬言要掘他祖坟。那时妻子怀上他们的第三个孩子，瞒着他打掉了。

终于有一天，他站上32层天台，思考自己要不要跳下去。他想了整整一夜，抽完了两包烟。天刚亮，一位老婆婆上去晾衣服，就跟他打招呼：“你在做啥子啊小伙子？”他突然觉得自己有点好笑，索性不跳了。即便现在财务状况已经缓解很多，但刘远说到之前的事还是会眼圈发红。

越来越多的人找到葛伟，他们把他看成一个符号，一个失败过但努力再起的英雄，就像他们自己一样。他在短视频平台上的粉丝已经超过30万，罗永浩转发了有关他的新闻。这一切给了葛伟信心，他觉得总要做点什么，为自己也为别人。

2020年4月，葛伟约了包括陈松和刘远在内的几位朋友喝茶，他们都是经历过失败的生意人，聊着聊着，这七位中年男女，曾经被人仰视的亿万富豪一个接一个哭起来。

没人会否认葛伟几乎是个真正的好人，类似的形容词还包括，有情怀、有文化、有爱心……有很多事实可以提供证明：他曾持续资助一家福利院近十年；汶川地震第二天给灾区捐了十万；今年新冠疫情，他捐了1000元。钱打出去，银行卡里只剩三百四十块，那是他的全部身家。

但现在，当人们谈起这个“好人”的时候，总要带些惋惜的语气。这场以葛伟为中心的地震波及甚广，无数人被卷入余震。之前为葛伟贷款担保的中间人，现在在市场上卖手链为生；张怀为了接管西郊庄园的物业摊子，资金一时周转不开，卖掉了一辆雷克萨斯；李齐的小贷公司最近几年本就举步维艰，加上葛伟的欠款无法归还，一度濒临崩溃边缘——值得一提的是，当年他没买到的西郊庄园的房子，被葛伟以房抵贷，给了他五套，他一套也没留，全部打对折卖出去了。

接管物业后，张怀的日子也不好过。庄园里的住户都是有钱人，但让张怀苦恼的是，没几个人愿意交每月一千出头的物业费。后来他总结出一个道理：“你知道有钱人为什么有钱吗？”张怀说：“因为有钱人在乎钱。”

张怀身材宽大，蓄一脸络腮胡。他和葛伟有一些共同的特点，本质是生意人，但对艺术很向往。葛伟的家中有一个昂贵的铜马，张怀的家却像一个艺术画廊，客厅里摆着一架来自西班牙的铣床，或者说装置艺术。他原本是葛伟的装修承包商，两人因脾性相投成为朋友。

在张怀的理解中，他和葛伟这代生意人大多是草莽英雄，随着时代变化，“该死就死嘛”。他觉得这没什么大不了的，所谓赚钱亏钱不过是社会财富的重新分配。在更具体的场景里，失败以一种惨烈的方式表现出来。

当一个人曾经是富豪，他所拥有的东西，金钱、名誉、尊严总会在决定性的时刻让他投下更大的筹码。2014年，葛伟决定停止付息之前的几个月，他在渝高广场附近的办公室里试图说服张怀给他投资。

张怀觉得，葛伟彼时的激动溢于言表，他分不清这是他的真实想法还是为了借钱不得已的伪装。他觉得面前这个人像一个吸毒者，而吸毒的人听不进去任何劝告。张怀看着葛伟双眼浸泪，最终什么也没说，回去之后，把二百万打到了葛伟账上。

事实上，在资金链濒临断裂的时候，葛伟不止找做生意的朋友借钱。他也向承包商、公司员工和他们的家人借了钱。每个人都对他的人品有信心，即便抛开这一点，西郊庄园里一百多栋别墅可是实实在在的。他对自己也有信心，一个踏准所有浪头的房地产开发商不可能是普通人。

公司办理破产后，葛伟全家还剩下1400万现金和两套房子。在旁人看来，这笔钱是他最后的保底资金，即便做些保守的理财，也不至于让全家人潦倒生活。但葛伟觉得，这笔钱也是他的筹码，是赢回尊严的最后机会。

他又一次选择冒险，然后又一次失败。

---

# 世界以完全陌生的逻辑运转

葛伟想了很多种办法翻盘。他二次创业，投资互联网，但隔行如隔山，之前的逻辑行不通了。2015年，他看中了中产社交和短视频两个项目，跟一位来自西安的互联网从业者吃过一顿饭之后，就觉得项目大有可为，激动地在家里走来走去，盘算着一旦成功，可能就是“下一个马云”。

他努力地消除对新领域的陌生感，至少让自己不会显得那么不合时宜。他在手机里下了有道词典，什么叫banner，什么叫KPI，什么叫日活，就像重新学一遍英文一样，听见不懂的词就转头查，查完了继续听。他到上海，到杭州去找投资，年轻的投资经理坐在他面前，谈论看起来简陋的商业模式和无法形成的闭环，听得他一愣一愣的，末了还不忘说一句，“你这（模型）跑不通啊”。

他还找到鲁磊给他投资——葛伟还欠他800万没还，但这次他又投了400万。鲁磊是重庆一家律所的老板，长着一张国字脸，有棱有角，身上有种不怒而威的气质——这作为经商中的一项缺点，被他专门总结改正过，现在他即便早已身家过亿，但无论见到谁都会率先露出笑脸。

从生出做互联网的念头仅仅三天之后，项目就上马了。葛伟任命了一位据说很有经验的互联网从业者，按照当时主流的玩法，先砸钱，后赚钱，推广活动一波接一波。

对于员工来说，葛伟绝对是个好老板。就像原先做房地产公司一样，他每天带到办公室两条烟，大家一起抽。偶尔看见有员工在工作时打游戏，他睁一只眼闭一只眼。至于周末，每天的加班费是一千元，按时发放。后来有朋友听说这件事，非常震惊，“你傻X啊？互联网哪有什么加班工资？”

起初的兴奋并没有维持多长时间，到2016年，互联网融资环境急转直下。看着账面余额，葛伟心里逐渐开始发虚。这跟做房地产的时候不一样，那时心里踏实，花再多钱盖房，归根结底，资产只是以另一种形式表现出来。但互联网是个看不见摸不着的无底洞，成百上千万的资金砸下去就化为无形，“连灰都没有”，APP的日活始终维持在个位数，他再次失败了。

他发现这个世界正以他完全陌生的逻辑运转。几年后，当他成了一个自媒体红人，有很多家MCN机构找到他，给出的许诺包括但不限于帮他一年把粉丝涨到500万，和罗永浩一样的直播带货渠道，或者根据他的故事改编电影和网剧。

他起初又很兴奋，感到自己再次踏入到洪流之中。有家MCN机构借他的名字收粉丝会员费，99元一个人，现在已经有上千粉丝“入群”，他们边收钱，葛伟边退，用自己的钱退。“有时候我真的不懂他们，我缺的是这点钱吗？”葛伟自言自语说。他和陈松站在家里的阳台上，望向不远处的嘉陵江，陈松语气哽咽，“我真替他觉得不值”。

荒诞的故事总是发生在现实中。市场像个脾气琢磨不定的小孩子，谁也说不准它下一秒给你的是什么。破产带给葛伟的教训之一是，即便看见财富的大门打开，但不是每个人都能走进去。

新的故事正在发生，只是没人知道结局如何。与葛伟初次见面的第二天，他去到杭州考察供应链，为之后可能的直播带货做准备。因为失信人的身份，他无法搭乘飞机和高铁，只能坐12个小时的动车，每天和各种商家聊到凌晨两点，第二天一大早又去参观工厂。他不断给自己信心——他必须给自己信心。

那一拨失意的商人正在重新寻找自己的位置。刘远从天台上走下去之后，大睡了几天，随即重新振作起来。2016年一年时间，他把员工团队缩减至二百多人，原先砸进去两三千万但连个响儿也没听到的研发中心被全员裁撤，另聘新人。“原来光靠喝酒，靠胆子大，（现在）不行了”。刘远说。现在，他的公司研发了用于高层建筑的升降梯，每台利润是原先的五倍。

至于陈松，他只是想争口气，证明他们这些人一旦有机会，依然可以腾云驾雾，重新成为社会的精英。

但每个人心里都清楚，有些东西已经永远地失去了。葛伟还有很多不愿意讲的故事，关于他的婚姻，关于他的家人，或许以后能听他亲口讲出来，谁说得准呢。很多年前，在墨西哥坎昆海滩上，他一边吃早餐，一边看着一只只小海龟伸着头，路过遮阳伞，路过摆在沙滩上的木质桌椅，向大海走去。

那时他坚信，自己拥有的一切都是靠努力和勇敢挣来的。海浪拍岸，一波一波的，这是他记忆中最幸福的时刻。
