---
title: Putin’s new Ukraine essay reveals imperial ambitions
author: Peter Dickinson
date: '2021-08-11'
slug: '264'
categories:
  - Translation Articles
tags:
  - Insights
  - Investment
  - Politics
---

[Source](https://www.atlanticcouncil.org/blogs/ukrainealert/putins-new-ukraine-essay-reflects-imperial-ambitions/)

Russian President Vladimir Putin has outlined the historical basis for his claims against Ukraine in a controversial new essay that has been likened in some quarters to a declaration of war. The 5,000-word article, entitled “On the Historical Unity of Russians and Ukrainians,” was published on July 12 and features many of talking points favored by Putin throughout the past seven years of undeclared war between Russia and Ukraine.

The Russian leader uses the essay to reiterate his frequently voiced conviction that Russians and Ukrainians are “one people,” while blaming the current collapse in bilateral ties on foreign plots and anti-Russian conspiracies.

In one particularly ominous passage, he openly questions the legitimacy of Ukraine’s borders and argues that much of modern-day Ukraine occupies historically Russian lands, before stating matter of factly, “Russia was robbed.” Elsewhere, he hints at a fresh annexation of Ukrainian territory, claiming, “I am becoming more and more convinced of this: Kyiv simply does not need Donbas.”

Putin ends his lengthy treatise by appearing to suggest that Ukrainian statehood itself ultimately depends on Moscow’s consent, declaring, “I am confident that true sovereignty of Ukraine is possible only in partnership with Russia.”

Unsurprisingly, Putin’s article has sparked a lively discussion in Ukraine and beyond. Ukrainian President Volodymyr Zelenskyy initially responded by trolling his Russian counterpart and stating that Putin obviously has a lot of free time on his hands.

Others identified numerous imperial echoes and thinly veiled threats in Putin’s attempt to play amateur historian. Stockholm Free World Forum senior fellow Anders Åslund branded the article “a masterclass in disinformation” and “one step short of a declaration of war.” Meanwhile, Russian newspaper Moskovsky Komsomolets claimed the essay was Putin’s “final ultimatum to Ukraine.”

Nobody in Ukraine needs reminding of the grim context behind Putin’s treatise. Since spring 2014, Russia and Ukraine have been engaged in an armed conflict that has cost over 14,000 Ukrainian lives and left millions displaced. The Kremlin continues to occupy Ukraine’s Crimean peninsula and much of the industrial Donbas region in eastern Ukraine. Earlier this year, Moscow massed over 100,000 troops close to the border with Ukraine in what some military observers described as a dress rehearsal for a full-scale Russian offensive.

This week’s publication of Putin’s grievances in such a formal and high-profile manner has inevitably fueled speculation that the Kremlin could be preparing the ground for a major escalation in hostilities. As the debate continues, the Atlantic Council invited a selection of Ukrainian and international commentators to share their thoughts on what Putin’s article may mean for Russia’s future policy towards Ukraine.

**Melinda Haring, Deputy Director, Eurasia Center, Atlantic Council**: Putin’s delusional and dangerous article reveals what we already knew: Moscow cannot countenance letting Ukraine go. The Russian president’s masterpiece alone should inspire the West to redouble its efforts to bolster’s Kyiv ability to choose its own future, and Zelenskyy should respond immediately and give Putin a history lesson.

**Danylo Lubkivsky, Director, Kyiv Security Forum**: Putin understands that Ukrainian statehood and the Ukrainian national idea pose a threat to Russian imperialism. He does not know how to solve this problem. Many in his inner circle are known to advocate the use of force, but for now, the Russian leader has no solutions. Instead, he has written an amateurish propaganda piece designed to provide followers of his “Russian World” ideology with talking points. However, his arguments are weak and simply repeat what anti-Ukrainian Russian chauvinists have been saying for decades. Putin’s essay is an expression of imperial agony.