---
title: 一道经典的咨询业面试题
author: 褚明宇
date: '2021-12-25'
slug: '360'
categories:
  - Translation Articles
tags:
  - Labor
---

想起一道经典的麦肯锡面试题。

大意是这样的：你有没有注意过，在公共场所的卫生间里洗手，一开水龙头，很快就有热水;而在自己家的卫生间洗手，往往得等一会儿，水才会变热？

咨询公司想考查的并不是你知不知道“正确答案”。事实是，很多问题本身就是多解或者无解的，没有唯一的所谓“正确答案”，他们想考查的是你的思维方式。

其中，很重要的一点就是看你能不能“结构性”地思考。听到一个问题之后，不是急于给出答案，而是给出一个结构和思路。这个结构必须满足两点要求：一、它可以帮你把问题清楚地分解成几个部分;二、这个结构必须全面（能够用到所有的已知信息），而且不能事先排除任何一种可能的合理解决方案。

比如这道面试题，如果你一上来就说，是不是因为公厕的热水器功率大？完了，这份工作你肯定得不到。

一个可行的“结构性”思路是这样的，你可以说：

决定水龙头出口水温的有3个环节——

第一，热水的生产环节;

第二，热水的传输环节;

第三，热水的使用环节。

你瞧，一旦有了这个结构，你就可以尽情地展开了。比如在“生产”环节，你可以跟面试官讨论家用热水器和专业热水器的差别;在“传输”环节，你可以讨论管道的长度和隔热效果，算一算热消耗什么的;在“使用”环节，你可以估算公共场所水龙头的使用率，进而跟家庭的使用模式对比……

说着说着，答案是不是就清晰起来了？

注意，还有一个关键是，你不能自说自话，你不仅需要结构化的思路，还要跟面试官互动，把整个回答的过程变成一场讨论。在这个讨论过程中，对方會给你提供新的数据，而你要根据新的已知条件，不断修正自己的思路，直到最后双方对正确的解决方案达成共识。

这个过程其实很接近真正的工作场景——结构化思考、分解问题、与同事协作、提出假设、获得新的数据、修正假设、不断迭代，直到得出合理且被大家认可的解决方案。

其实，这道面试题还真有一个“标准答案”，我就不公布了，您就当是道练习题吧。

有人问，如何有效阻止父母盲目投资，上当受骗？咱们就从头开始，“结构化”地思考一下吧。

决定你父母陷入投资骗局的有3个环节：资金来源、投资的信息渠道、投资的决策研究。

作为你的咨询师，一旦有了这个结构，我就可以尽情地展开了。比如在“资金来源”环节，我可以建议你让你父亲管理家里所有的存折和账户密码;比如在“投资的信息渠道”环节，我可以建议你找出你母亲接触受骗项目的节点——一个嘘寒问暖的推销帅哥，还是她的微信好友，从而阻断她和这个节点的联系;比如在“决策研究”环节，我可以建议你给父母找一些能分散精力、特别费时费力、特别上瘾但无害的活动，比如打打小麻将、跳跳广场舞什么的，从而减少他们琢磨“投资”的兴趣、时间和精力……

不幸的是，现在我只能自说自话，无法跟你讨论，无法从你那里获得新的数据点，从而修正我的思路，然后迭代，与你达成共识，进而得到最终的解决方案。

希望至少我能给你提供一个思路吧。