---
title: What is wrong with the Ukrainian economy?
author: Anders Åslund
date: '2021-09-02'
slug: '294'
categories:
  - Translation Articles
tags:
  - Ukraine
  - Economics
---

[Source](https://www.atlanticcouncil.org/blogs/ukrainealert/what-is-wrong-with-the-ukrainian-economy/)

>一切都在迅速好转

APR 26, 2019

Construction is booming in Kyiv, Ukraine, but not the rest of the economy. A major reason is that Ukrainians with some extra savings do not put their money into banks but buy additional apartments instead. Others keep their savings in cash. On average, Ukrainian MPs keep $700,000 at home. Those who have a lot of wealth transfer it to offshore havens, where the money is safe.


Ukraine is now the poorest country in Europe. According to the International Monetary Fund, Ukraine overtook Moldova as the poorest country in Europe as measured in GDP per capita in 2018 at $2,963, 8 percent less than in Moldova. These numbers can be boosted in many ways. Probably half of the Ukrainian economy goes unreported in official statistics, and prices in Ukraine are so low that one gets much more for a dollar there then elsewhere. Still, the growth rate has been around 3 percent a year for the last three years, and the IMF predicts a similar rate even for the long term. A poor country with macroeconomic stability and open access to the large European market should be growing steadily by 7 percent annually.

What is wrong? Usually the discussion focuses on what the state does, but there’s a better way to understand how the economy really functions: follow the money.


Ukraine has a steady net capital outflow of about 4 percent of GDP each year. Foreigners see what is going on, and real foreign direct investment has been as little as 1 percent of GDP for the last five years. Naturally, the war has scared many away, but that is hardly the main reason why FDI remains flat. Instead, Ukraine should have FDI of 4-5 percent of GDP. Then the investment ratio would not be 20 percent of GDP but 28-30 percent of GDP, which is the difference between 3 and 7 percent growth.

There is little or no financing available for business. By and large, business investment is based on retained earnings. Since 2014, the National Bank of Ukraine (NBU) has closed 100 of the then 180 commercial banks. In many cases, the owners of the bank had taken most of the loans, and large deposit holders lost their money. In other cases, the banks specialized in money laundering, and some functioned just like holding companies.

But the banking system has not been cured. Because of the many bank failures, state banks now account for 58 percent of all banking assets. Interest rates are prohibitively high. The NBU just cut its interest rate to 17.5 percent a year, while inflation is just over 8 percent. The lowest commercial borrowing rates in hryvnia are 22 percent, which means that the real interest rate is at least 14 percent a year. That is far too high for investment, so bank loans are not financing investment. In spite of very high deposit rates, banks do not attract many deposits either.


The banks’ primary problem is that their biggest clients do not pay. In total, non-performing loans in the Ukrainian banking system are more than 50 percent. The reason is that Ukraine has a few hundred people who consider themselves too superior to pay, and unfortunately the Ukrainian judiciary agrees. In particular, 427 members of parliament enjoy legal immunity and probably two-thirds of them are businessmen. Others have simply very good relations with the relevant parts of the law enforcement apparatus. European elites behaved like that in the 18th century. It was only in the 19th century when the playing field was leveled that Europe started growing.



Herein lies the critical shortcoming of the Ukrainian economy. First, parliamentary immunity has to be abolished. People should join the parliament to become politicians, not businessmen.



Second, Ukraine needs to redo the failed judicial reform so that all Supreme Court judges can be verified as honest people. The same is true of the general prosecutor’s office. The Security Service of Ukraine (SBU) must no longer deal with economic crimes. Its 8,000 or so officers that work in that department should be laid off. Most of them have earned more than they will need for their retirement.


Third, the best collateral for a bank loan is land or real estate. However, today agricultural land cannot be used as collateral, because of the moratorium on private land sales. If that is finally lifted, the banks could give far more credit to agriculture, which could double its output.

Then, banks could start to function normally and attract both capital and deposits. The market would bring down interest rates. The state banks could attract investors and be privatized. If property in Ukraine would be deemed safe, capital outflows would dwindle and instead be invested in the Ukrainian economy. Foreigners would see the transformation and want to join the Ukrainian growth party.

