---
title: 人口压力与人类文明
author: Guanghua Mao
date: '2021-03-06'
categories:
  - Original Articles
  - Translation Articles
tags:
  - Culture
  - Demography
  - Labor
  - Prediction
slug: '145'
---

 [Source](http://headsalon.org/archives/6798.html)

 [Source](http://headsalon.org/archives/662.html)

[Source](http://headsalon.org/archives/658.html)

在[气候变迁的历史启迪](https://guanghuamao.netlify.app/2020/12/23/1/)一文中，我提到过气候变化对人口数量的影响，以上三篇文章通过扩展马尔萨斯模型，让人口模型变得更加精致，也有助于我们进一步了解人类社会。

---

根据马尔萨斯理论模型，如果自然条件、制度和技术没有受到抑制、人口将呈几何级数增长、且人口总量总是被抑制在生活资料所允许的水平之下。理由是：人类作为生物、生存和繁衍乃人之本性、人们会将生活资料不断投入到生存和生育更多子女上。一开始，随着人口增长，由于规模效应而边际效应增加，但是不断膨胀的人口最终会耗尽规模效应、边际产出开始下降；最后在均衡态，人口受到抑制而到达极限。

更具这个理论模型，我们能够更好地理解我们所处的这个时代——大航海发现了新大陆、两次世界大战和共产主义消灭了大量人口、战争催生了大量的技术创新、美国推行的宪政和市场制度极大解放和发展了生产力。人类迎来了大繁荣时代。气候从暖和变为寒冷也有同样的效果，高纬度地区人口对气温变化更加敏感，人口承载能力下降，大量人口不得已向更加暖和的地方迁移，大量的战争和冲突频频发生。同样的，当一个地方制度开始退化，或者有部分地区有着更好的制度条件，人们将会不断地从制度条件差的地区移民到制度条件好的地区，这就是我们所看到的亚非拉地区的人们不断移民到欧美澳，农村人口涌向城市，东北人口涌向海南。

但是从马尔萨斯的视角来看待我们当前的某些国家，确实显得有些奇怪，很多发达国家的人口出生率不断下跌，但是如果我们将整个人类视为一个系统，我们仍然能够看到人口在不断地增长，发达国家的人口下跌更像是财产权的确立和中产阶级生活标准在全球传播的结果。财产权的确立类似于赋税，社会的确有富余的资源，但这些富余的资源被少数人或者国家拥有，这些资源被用来支持庞大的官僚机构或者高水准的个人生活。而中产阶级生活标准的全球传播让很多父母宁愿少生小孩也要精养少数小孩。但是，只要社会中有部分人仍然坚持多生粗养（不练钢琴、不背唐诗、不追求学历），人口依然会不断增长，而且那些信奉多子多福的人会在社会中占据主导地位。

如果说社会的剩余资源率对一个社会的繁荣程度（城市化、工艺品和宏大工程）有着直接影响，那么是什么影响了社会剩余率呢？根据马尔萨斯模型，我们可以看到在给定人口数量的情况下，一块新的领土、技术条件和制度变革都有利于提高社会剩余率，但是领土和技术的红利最终都会被吃干抹净，转变为更多的人口；另一方面，如果其他条件不变，在人口处于极限状态的情况下，通过消灭部分人口将有利于提高社会剩余率。战争、瘟疫和制度都能够完成这一个任务。国家为了更多的税赋，不得不消灭部分人口，通过臭名昭著的计划生育、发动战争、强行堕胎等形式，提高社会剩余率，另一个就是私人财产制度，它也有助于提高社会剩余率，那些对私人财产保护得更好的地区，文明也确实更加繁荣。

社会剩余率的提高使得大量人口不需要再日日夜夜耕作就能够养活自己，这些人开始创造文化，跳舞、写诗、打篮球、影视剧等文艺作品不断涌现在社会剩余率高的地方，而社会剩余率最高的美国、在文明繁荣方面有着无可比拟的优势。

对于这一主题，人性：策略的遗骸说的很好，但是我认为，社会整体富裕之后，人们过剩的精力、财富和过多的时间需要找到发泄口，而源于人类认知的局限性，能够让人们以极其廉价和简单的方式去消耗掉时间、精力和财富的产品，终将更受欢迎。



