---
title: '七十多年前，到底是谁打跑了日本人？ '
author: 照理说事
date: '2021-12-06'
slug: '341'
categories:
  - Translation Articles
tags:
  - China
  - History
  - America
---

[Source](https://www.sohu.com/a/161971048_665541)

欢迎捧场照理说事。咱们这期聊聊日本人对二战态度这个话题。每当咱们中国人把二战后的德国跟日本对待那场战争的态度做个比较，就会发现这两者简直是天壤之别，一边是总理向犹太人纪念碑下跪，举国上下深刻反省历史，把纳粹做为人们言行的禁区，一边是政府变着法儿的否认侵略罪行，首相去参拜甲级战犯，人们不禁会问，两国都是战败国，为什么差距这么大呢？原因其实归根到底就是一句话，二战日本是败了，但它从来没认为输给了中国！

咱们回顾一下二战远东战场的进程，1944年到1945，日本在太平洋上曾经占领的那些岛屿已经悉数被美军攻占，曾经不可一世的日本海军几乎都被美国人送到了太平洋海底。这还不算，美军一次就出动五百架B29轰炸机对日本东京等主要城市轮番轰炸，倾如雨下的凝固汽油弹把木质建筑为主的东京几乎烧了个片甲不留，甚至有人开玩笑说，除了几个城市留着日后便于测试原子弹的爆炸效果，整个日本已经被炸成了一片废墟，当然了，就这样了日本鬼子还在叫嚣玉碎，跟美国人本土决战。直到美国投下原子弹，苏军出兵东北才迫不得已，仓皇投降。

可是，咱们回过头来看看中国战场的形势，你会大吃一惊，就在太平洋战场上日军被美国人打得没有还手之力的同时，中国战场的日军甚至还在高歌猛进攻城掠地。以至于天皇宣布投降的时候，中国战区的日军处于无人受降的尴尬局面。1944年，因为处于绝对优势的美国海空军已经完全切断了从东南亚到日本本土的海上交通线，不仅军事力量无法调动，更致命的是对于日本来说最珍贵的东南亚的石油橡胶这些自然资源没法运回日本本土，所以日军决定打通经过中国腹地连接东南亚的所谓大陆交通线，在1944年春天发动了豫湘桂战役。

在八个月中，攻陷城市146座，打通了纵贯中国南北的交通线，包括平汉线、粤汉线、湘桂线和中越交通线，侵占了河南、湖南、广西、广东四省20多万平方公里的土地。这是中国抗战以来，在正面战场上的一次大溃败，所以在历史教课书上被称为豫湘桂大溃败。通过这次战役，日军已经逼近贵阳，陪都重庆都陷如了混乱。这样的形势如果出现在抗战初期也许还说得过去，当时的日本法西斯正处于最嚣张的时候，但问题是时间已经到了距离日本投降还不足一年，面对已经处于崩溃边缘的日军，还出现这样的大溃败，难怪当听到大本营要求投降的命令后，侵华日军诧异不已，不敢相信，因为他们感情上实在没法接受向刚刚还在逃跑的败军投降。

刚才咱们讲的是日本陆军。日本作为岛国，以海洋立国，海军对日本来说更为重要。只要海军主力还在，就进可攻，退可守。我们退一万步说，就算中国军队抗日战争中全歼了中国国土上的日本侵略军，又如何消灭日本海军，登陆日本迫使日本投降呢？中国八年抗战，却没能击沉日本一艘驱逐舰。尽管战史大肆宣传“八一三”凇沪抗战中空军英雄沈崇诲驾机撞沉了日本侵华舰队旗舰出云号巡洋舰，但实际上出云号是在1945年7月战争结束前，在本土濑户内海的吴军港被美机炸沉的。据检验，出云号只挨了一枚炸弹就沉没了，这艘日俄战争时期的老朽军舰尽管不堪一击，但作为侵华海军旗舰却绰绰有余。

太平洋战争中日本海军先后投入航空母舰25艘，被击沉21艘。二战中美国建造、改装航空母舰150艘，大部分都投入了太平洋战场，完全是以雄厚的国力把日本压垮了。太平洋战争中日本海军战死40万人，而在中国八年只战死2万人的海军陆战队，相差20倍。可以说，在二战中，日本海军完全没有把中国视为对手。

二战期间，日军两面作战，跟中国开战的同时，还发动了太平洋战争跟美军作战，而且还在中国东北陈兵百万关东军防守苏联。如果你留心一下太平洋战争的那段历史，无论是硫磺岛冲绳战役，还是中途岛，莱特湾，珊瑚海海战，都创造了人类历史上海战规模之最，几十艘航母几百艘战舰规模的厮杀，海空立体作战的夺岛战役，这跟中国战场的战争模式和规模都有天壤之别，完全不在一个量级上。其实，这也从一个侧面说明，中国的抗战是多么的艰苦卓绝，以中国那点实力，国民政府没有亡国投降，共产党领导的敌后抗日力量一直坚持壮大，已经实属不易，但是，事实让我们不能否认，没有美国人的太平洋主战场，没有苏军出兵东北，短时间内我们根本不可能打败日本。

也正因为如此，在日本人内心深处，自己是败给了美国人，甚至可以说是败给了苏联人，但很少有人认为自己败给了中国人。日本人自古至今都是一个崇尚实力的民族，看看日本人所尊重的国家，无论是大唐，蒙古帝国还是今天的美国，无一不是所在时代的王者。现在，很多西方媒体说我们的国防现代化发展是在穷兵黩武，国内有些人也跟着起哄，质疑我们军队大规模现代化的必要性，对此，我想说的是，要想让日本人意识到自己是中国的战败国，最好的方式就是在实力上压倒它，我们的军备不是太多了，而是还不够多，还不够先进，多花一些钱去建设一支能够震慑敌人的军队，总比真的上前线去打仗要好得多吧？