---
title: 煮老师微博言论合集
author: 煮肘
date: '2021-07-16'
slug: '251'
categories:
  - Translation Articles
tags:
  - Business
  - Economics
  - Insights
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

# 负债70万

煮老师，关注您几年了，经历越多越佩服您的观点和智慧，真正的朴素的大智慧，大道至简，我一直崇尚这些，但智慧相差太远，我80年的，已近40，农村穷孩子出身，毕业后一直很顺利，在手机行业，从在外企做一个省级办事处的负责人，到苹果代理商的分公司负责人，曾有几年在沈阳拿着70万左右的年薪，没缺过钱，转折就在辞职创业，自己投了一百多万开了三家餐厅，做了三年，最后经营不善交不起房租都撤了，随之交往多年的女朋友也跑了，仅剩的一套房也因当时开店她投了20万而过户给她，目前真是三无人员负债30万，目前在一家创业公司拿着一万多的工资不死不活，我这种情况这个年龄靠打工是没什么机会了，只能找机会再博，目前在看精品生鲜水果店生意，已经着手选址，和一多年伙伴(之前合作过生意，无纷争)合作，又得是举债创业，明年还有一餐饮项目，也是研究观察了一年准备年后下手，这是赚钱方面的计划，关于结婚生娃，十分认同您说的找年龄小的，可目前这经济状况，我想还是先做事吧，大体情况如上，望百忙之中给些建议，不对的地方就骂，感谢了

答
你这是向往提问里的最穷的了，负30万[哼]

你这感觉先找个普通人，结了算了

你也不可能大发财的，别做梦了

别年轻了，能娶老婆就不错了

我最鄙视的就是没多少水平，还整天惦记创业的男，想发财想疯了？

创业失败会陷入绝境的，我都鄙视

别人失败了，也是优秀男，你这失败了，负资产

打工工资就说明市场对你能力判断了，还胡闹？

沈阳70万年薪？你就是被这些运气害的，以为自己牛

还农村创业？现在是80年代，90年代吗？你啥根基都没，还借钱传统行业创业？？

老老实实发挥最擅长的，找个合适的企业打工吧

真要自己做，也是小生意，叫毛的创业啊？

生存先吧你

你女朋友找潜力股就是傻的，还好不太傻，跑了[哼]

#煮老师谈婚恋#

---

# 不需要读大学

为什么好女生根本不需要读大学？

因为大学学的知识，对好女生无用，反而圈子分为大多有害，被左派洗脑

郭晶晶这类的体育生，是基本不学文化课（可以学，但基本不看成绩，不理成绩），郭晶晶是拿了金牌后，才进入大学的（也基本是混个文凭），显然读不读大学没什么区别，照样属于顶级女生，照样嫁豪门还幸福

郭晶晶可不是富家女

那些叫喊着读大学的女生，谁不知道你们大学时在疯闹混吗？说的好像在认真读书似的，说的好像所学的那些真的有多大用似的

学做家务都比大学学的那些有用10倍，学点家务至少你不至于家里发臭啊

---

# 女子无才便是德

说几句

1、我从小就看三言二拍，就知道里面的名句“黑蛇口中牙，黄蜂尾上针，两般犹未毒，最毒妇人心”

2、唯小人与女子难养也，近则不逊、远则怨。

3、女子无才便是德。

小人与无见识无良好思想教育的女子，是根本不懂共赢，太低贱，不是重视共赢，好不重视信誉，缺乏靠信誉获得长久幸福价值的。

他们会抓紧各种机会，目光短浅，愚昧的牟利，会长期如此心态，习惯如此心态。

找女人和小人（下人，与大人、君子反之），需要留意其心态习惯，需要是安分的。
不要给财富及财富机会机密，给不重视孩子的女人，不安分的下人手里。

这些人会利用一切手段资源，牟求暴富，却根本没有能力驾驭财富，最后多抱着搞来的财富不得善终。

优秀的人，是贵族心态，是注重长久和谐共赢的，绝不会靠坑人牟利，具有良好的信誉。
他们具有道、德的智慧（见老子的《道德经》、亚当斯密的《道德情操论》），明白事物因果规律，圣人不仁，利己利他。
这样的人，追随者多，自然就会富。

财富在优秀者里，是造福家族、造福社会的工具。
财富是实现幸福稳定手段，而不是目的，他们不会为了钱财坑害家人、公司伙伴

女人和小人的思想层次是极低的
女人所关注的，所擅长的，是生活，而不是工作上合作共赢，女人是很难具有事业上的信誉的，难以获得好的合作伙伴或者帮忙的人，所以难以做大（自己当老板的做大）。
女老板，大多是背后有男人，用男人的关系在做，女人在台前张罗而已。
少部分运气好的寡妇女老板，可以因为海量寡妇拼搏生存，而小概率冒出来几个。女人难以工作做大做好，是概率，不是绝对无，因为大千世界，总会有各种原因，让人条件具备，可以成功的，只是多少而已。而这些“成功的女老板”，实际只是财产看起来还行，而幸福远远不如类似的男老板，数量也比不过类似的男老板。

人没有优秀孩子是必然不幸的
女人因为生于青春短，必须30岁前生孩子，多生几个，才可能培养优秀孩子而幸福。基础素质优秀，只是成才概率高，但不会太高，还是需要更多的数量才能比较筛选出。皇帝那么优秀，生好几个孩子，才勉强找一个还行的。你一个只是“学历还行”的家伙，生一个，怎么可能高概率优秀？'

如玩一个新游戏，任你再聪明再优秀，你刚玩时，必然是“萌新”，必须需要长时间丰富经验后，才可能懂，才能玩好。
养孩子也如此，等你明白玩法后，你已经错过了孩子对应的时机了，必须是下一个孩子吸取教训改善（其实还可能是错，需要多次试错后，才能明白真理）
生第一个，养时，任你再牛，也难以一次养好的
孩子也需要近距离观察年龄接近的人，真正思想交流，对比较量，才能真正成长好的。
老师只能教育知识
而其他方面，不要以为只有父母教育孩子，其实很多时候是孩子教育父母（让父母反思明白应该如何做才对），很多时候是孩子兄弟姐妹间相互教育。

当代中国女人多是独生子女，大多左派父母，女生非常悲惨，缺乏右派父母的教导，缺乏姐妹交流，被迫学校看着屌丝同学互相学习，被迫网上听车10%的垃圾女权及50%的垃圾般女权们中那5%的总群体呱噪，被洗脑成左派蠢女，弄得废物无用（企业不乐意要）且惹男人讨厌嫁不出去。
男人对这些看起来光鲜的年轻蠢左女，当然是睡着玩，但不愿意终身相伴。

女子无才便是德

女人必须不学赚钱之才（大部分大学不应该女人去读，女人可以学幼教等适合女人的专业，不以赚钱为目的），重视子女教育，重视家庭合作共赢和睦，选择合作共赢爱孩子共同培养优秀孩子，共同长久幸福生活的男人，才可能幸福。
否则即使年薪百万也只是败犬，为了几百万贱卖了自己的青春人生
女人有钱是得不到幸福的，是不能考此找优秀男的，反而更不利找优秀男，更吸引渣男。
男人靠自己才华赚钱，是可以35岁再找一个21岁，19岁的优秀乖美女的，是容易因此幸福的。
所以男人可以去追求才华，去努力赚钱，而女人不应该如此。（主要是因为女人生育才能幸福，不生育是绝不会幸福，生了不育不教，更不会幸福，女人生育时机是18～30岁，需要多生，多教孩子，这和赚钱严重冲突。所以女权分子实际都是反婚反育的，她们希望女人都不要生小孩，来减少她们不生孩子对比的挫败。但人类不可能都不生孩子，每个女人人均生育不足2，就是人类走向灭亡。本文化不足2，就是本文化民族走向灭亡。

男人找女人，只找年轻、安分女子，以相夫教子为己任，终是如此的。
优秀女人找男人，只找有才能，品行好（有信誉，真诚，互利，而不是爱心标榜口上道德的），爱家人爱孩子的。

若一个人连自己的孩子都不爱，会爱别人？不要蠢了。

每个人都应当以自己家人孩子为第一重视，这样的人才值得信任，值得选择。无论是生活，还是事业合作。
无恒产者无恒心
不爱后代的人，必无耻害人

---

# 左与右

完全右的女，是极少的，是基本不在网络上晃荡的
她们早早就嫁出去了，根本不可能等到25

左是平等，要结果平等，搞规则平等（认死理，生搬硬套），幻想不实际，惦记好事，不愿意吃亏，对陌生人与对亲友态度接近

右是物竞天择，竞争奋斗，生存至上，效率至上，一切看实际情况，有大原则，有特殊例外，务实，考虑事情往坏的方面考虑，不惦记好运，也不惧怕风险，是做措施防范坏风险坏事发生或设法降低损失，追求平均高效率。愿意吃小亏，对陌生人与对亲友态度大不同。

右就是做正确抉择，而不是认死理不充分思考的做大决定
要右，是非常困难的，是要求很高水平的

因为右几乎是选择出正确答案，所以只要水平足够高，同类情况基本都是一样的结果

而左是各有各的错误习惯和观点，例如“我一定要找个身高180以上的男”，就是左；而“我要找个170以上的男”就是右。
为什么？
因为左比较爱走极端，也不看特殊情况。你可以把180以上视为优点，给加分，但认为是必须，或者把一个不是特别重要的因素放在特别重要的位置，都是左。（幻想，规则平等，条件平等不懂优劣）

所以左是程度问题，1%左，还是5%左，还是10%左，能10%左已经很失败了。
也是水平问题，所以左基本是蠢不自知（在自己不熟悉的领域）

越蠢的人越容易左
越聪明的人，在自己越熟悉的领域，越容易右。但在不熟悉的领域，若被人忽悠，如果还对左没有清晰深刻认识，也容易左。白左里圣母那一类，主要是不熟悉，被忽悠，一旦他们感受到实际情况，会立即对该方面变右（变正确）

这世界是竞争的，年轻缺乏经验的人，很容易被经验丰富的人欺骗打败

小女生，不知道天高地厚，要去和一群老男人竞争，认为自己牛逼，必然傻逼了，毫无悬念

女人就算自己优秀，竞争赢了，也是需要二三十年时间，证明自己优秀，也没有生育价值了，没人愿意娶了培育共同后代了，这是非常悲剧的，女人最后变成花钱找男人上床，还要防着别人坑钱跑了和别人去生，不悲剧吗？
男人可不需要怕这一点，少给钱，生娃，熬到35，40岁，女人基本可以被信任了，跑了也和别人生不了娃了。

实际女人和男人竞争，是损失非常大，得不偿失，不值得，所以女人根本不努力，女人从古都是被保护照顾的，所以在工作上更难有成绩。强行扭曲只是破坏全体效率

假设男女基本能力完全一样

女人花30分的努力，就能通过嫁人，和60分的男过一样的生活
她为什么要努力？当然不会努力，当然生孩子陪孩子幸福去了

女权最害女人，实际上过去二三十年，因为强制独生子女，女人在家确实比较闲，确实需要创造更多价值，但过去的那观念导致很多女人被压迫赶去上班，回来照样还需要带孩子做家务
难道不生孩子？不生孩子少生孩子，就被换人，小三上位[微笑]

不生孩子，男人比女人富的就更不会娶女人了

一个女人如果愿意陪上床，可以满足几十个男人，通过性勒索是难以整体胁迫男人的，因为绝大部分男人并不需要每天都发生性关系。如果不重视孩子，男人会普遍不养女人

女权无数幻想，无数毁女人

现在的女人情感和生活比古代痛苦多了
现在生产力高这么多倍，如果在古代，女人会远远比现在幸福。

自由？呵呵，挑拨离间哄骗人的借口

你上班有自由吗？更没自由



---

# 就业难

大学生就业难，企业招工难，是因为大学培养的多是眼高手低的废物，既不能吃苦耐劳，又叛逆矫情，还不辨是非，都是废品，不合格，所以学生难就业，企业难招聘。婚恋市场也是如此，废物女太多了（男也受一定影响，但远不如女的观念错误严重），农村出来读个3本，就认为自己该嫁月薪2万以上或家里500万的