---
title: 褚老师另类职场课（5）
author: Guanghua Mao
date: '2021-10-06'
slug: '317'
categories:
  - Original Articles
tags:
  - Job
  - Business
  - Politics
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---



问题：裸辞是世界末日吗？

回答：1. 裸辞不是世界末日；

2. 裸辞后空窗期会让下家企业对雇员的评价减分；

3. 有找工作的能力，应该能做到没辞职就先找到下家；

4. 裸辞是对自己的职业生涯严重有害的事情；

5. 企业找人的时候是会看你过去的工作是成功还是失败（985、211为什么吃香）；

6. 最好是成功，而不是失败了在解释；

7. 非常难说服潜在的雇主你是没有问题的；

8. 就算碰到很差的雇主，也不要裸辞，要先找到下家，这是正确的职场政商；

9. 裸辞的第三个问题，潜在雇主的眼里他的选择是很多的，一个裸辞过，一个没有裸辞过，雇主会简单选择没有裸辞过的（相对优势）；

10.无论如何永远不要裸辞。

11. 雇主是很贱的，大家都愿意抢，你的offer越多，就越有人愿意给你offer。




别成为“那个问题”

一旦这个人决定解决你的时候，他只会注意到你的缺点，而看不到你的优点。

新 offer 能够帮你涨工资。

在公司混的目标不是生存而是发达



# 如何政治“自杀”

## 缺乏情绪控制

1. 有人会故意激怒你，让你情绪失控

2. 愤怒类：抱怨（公司、领导不好）、叛逆（敢于站出来说话，做点不一样的）、冲突

3. 焦虑类：面（不敢发言、不敢表达自己的观点）、作（嫌弃这不好、事儿多、爱麻烦别人）、躲（看见领导不敢打招呼）

##  受害者人设（自我实现的预言）
1. 别跟自己“对话”，大家要忍住这种倾向（锚点效应），不要觉得有同事或领导在针对自己，自己很容易把自己想象成为一个受害者。

2. 别跟“受害者”对话，对传播负面消息和闲话的人少接触，永远积极向上。（跳到甲方的一个客户混饭吃是一个非常差的职业选择）

3. 如果你真是受害者。不要告状。


## 自我中心（过度自私）

1. 变态和烈士都是自我中心
2. 要学会当赢家

## 以愚蠢的方式对待变化

1. 要适应新的角色和新的环境





# 政治风险信号：

## 有点不对劲

1. 经常想到“公平”问题

2. 在公司经常是自己待着，没什么朋友

3. 老板忽略你

4. 公司派人来“帮助”你 


## 未来不明朗

1. 本来应该归你的任务，交给别人干了

2. 有超过一次错过了提职（5年不提职，就再也不会提职了）

3.  换了新经理，自己的杠杆明显下降

4. 人事部门的人突然找你谈一谈

## 突变要发生

1. 重组之后，你的团队规模、职责、职务、汇报层级下降

2. 你上级的上级入场，找你“说话”.

3. 有裁员的谣传，同事避免跟你接触





attribution error: 成功都是自己的功劳，失败都是别人的错误。凡是从自己身上想一想有什么提升的可能。





#员工不应该知道的公司秘密：

公司的记忆只有“七秒”：好事和坏事

累积：时间上，可转换：去别的职位，别的公司是否还有用

可累积的，可转换的：口碑（如H-index），职位、学历，敌人

可累积的，不可转换的：钱、经验、知识

不可累积的，可转换的：业绩（一年内有效），要及时转换，通过当年的业绩努力提职。

不可累积的，不可转换的：加班，那个问题（可以通过重组、跳槽、改变自己来跳出这个坑）






quote：

1. 脑残就是一遍又一遍重复做同一件事情却期待不同的结果。
2. 朋友来来去去，但敌人是累加的。（千万不要轻易得罪人）




































