---
title: 煤老板遇上红酒
author: ' 种昂'
date: '2020-10-19'
categories:
  - Translation Articles
tags:
  - Business
  - China
  - Chinese
slug: '67'
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

[Source](https://ishare.ifeng.com/c/s/v004xSCSrM3--fl4iaVpSP4TfrQa-_IoXsz6UO3-_-_wVZP9gig__?from=ucms_web&v_p=86&WBAPIAnalysisOriUICodes=10000001_10000002&launchid=10000365--x&wm=3333_2001&aid=01A6sOQkOJFCuFsMULBzFwKKoIxhfJVTBRDiixw2Td_8x10Jg.&from=10AA293010)

> 以为比煤、油、房还暴利！煤老板豪掷千金宁夏做红酒 没想到却是无底洞

 今年以来，红粉佳荣葡萄酒庄庄主马九虎心生退意，正计划出售这个宁夏红寺堡产区最大的葡萄酒庄。

“酒卖不出去，钱回不来，库存不断增加，每年酒庄亏损都在上千万元，如今是靠借钱在维持运营。”在9月25日和10月8日的两次采访中，苦心经营多年葡萄酒庄的马九虎，现在有些心灰意冷。

红粉佳荣葡萄酒庄面临的也是宁夏葡萄酒产业的共性难题——品质虽高，品牌却小；定价虽高，有价无市；产品滞销让酒庄运营举步维艰。今年突如其来的疫情，更是让他们雪上加霜。

---


# 这里的红酒确实好

目前，宁夏葡萄种植面积达57万亩，占全国的四分之一，也是全国最大的酿酒葡萄集中连片产区，综合产值达260亿元。根据葡萄酒行业市场调研和咨询机构WineIntel－ligence对中国中上层消费者的葡萄酒产区知名度调查，法国波尔多产区位列榜首，中国宁夏位居第二。

近年来，宁夏吸引了美的集团、正大集团、董明珠、郭广昌等知名投资商频频到访，考察投资。这让当地政府意识到，“一瓶酒的价值远超一吨煤”，且发展潜力巨大。但宁夏这个中国最大葡萄酒产区，也亟待葡萄酒产业的整体升级。

2020年9月25日，宁夏自治区政府召集葡萄酒相关政府部门与主要酒企召开产业推进会，对“十四五”葡萄酒业发展规划进行最后的修订。参会人士透露，“十四五”期间，宁夏计划在现有规模上实现倍增——2025年葡萄种植面积将达100万亩，葡萄酒产值达到千亿元。

在诸多政商两界人士看来，葡萄酒产业发展已关乎整个宁夏的经济转型和产业结构升级，若要达到这一目标，突破市场滞销瓶颈、实现产业良性循环发展，是关键所在。

---


# 煤老板跨界做酒庄

马九虎是陕西榆林人，原是当地有名的“煤老板”，不仅在榆林拥有煤矿，而且在天津、烟台等港口设有多家货站，煤炭贸易一度做得风生水起。2006年，马九虎被宁夏吴忠市红寺堡产区招商而来，与亲朋一起在这里投资葡萄酒庄。“当时投资了7500亩葡萄园，直到现在，红粉佳荣在宁夏红寺堡产区都是最大的酒庄。”庄主马九虎回忆，酒庄于2008年开始建园，按照400元/亩的价格一次性买断，使用期30年。因葡萄种植规模大，附近5个村、五六百名村民都成了这片葡萄园的产业工人。

按照马九虎最初的设想，每年土地总成本300万元、工人工资每月700元，再加上政府给予补贴，葡萄园乍看投入不大。然而后来每到丰收季节，他一家人总为葡萄销路发愁。

为了消化产能，2014年马九虎又投资5000万元购入酿酒设备和一个个橡木桶，聘请国外酿酒师，建起了红寺堡产区最大的酒庄，年产1000吨葡萄酒。

一位当地官员坦言，最初宁夏葡萄酒产业招商吸引了各类投资者，其中不少是挣了钱的“煤老板”“油老板”“房老板”——当地人称之为“新三板”。他们完成了财富的原始积累，迫切寻找新的投资渠道。

2008年后，全国各地投资商蜂拥而入宁夏，贺兰山东麓大大小小的酒庄拔地而起。许多老板的投资逻辑与马九虎相差无几，他们不远千里而来，一头扎进了葡萄地，盘算着——3斤葡萄酿一瓶酒，每瓶葡萄酒不算橡木桶陈酿只有十多元的成本；在终端市场，一瓶葡萄酒售价却动辄数百上千元，这简直比煤、油、房还暴利！平时自己的企业每年酒水招待也在上千万元，用这个钱几乎就能自建一个酒庄……不久，一个个跨界而来的老板在宁夏葡萄园里一掷千金。

可当跨界投资者真的种上葡萄、盖起酒庄，成为令人羡慕的“庄主”后却发现，与当初设想的完全不同。

马九虎的女儿回忆，此前种植葡萄，只是涉足农业，盖起酒庄后，却要横跨种植、酿造、销售，涉足一二三全产业链，投入更大、周期更长；此前葡萄卖不掉，但毕竟价值较低，如今酿成了酒，仍旧积压在手、难以销售，沉淀的资金却越来越多。

红粉佳荣葡萄酒庄于2014年开始出酒，产品定位以中高档为主，最低价格也近两百元一瓶。初期产量较小，主要依靠朋友关系销售，到了2017年，酒庄产量增至800吨，销售成了令马九虎一家头疼的难题。“从煤炭跨界经营葡萄酒，没有销售渠道，又找不到得力的销售团队。而在东部沿海城市开设一场推介会，场地费、中介费、运费、劳务费等处处需要花钱，还要给予经销商高额的提成。有时一百万的收入，就要数十万的开销。”

红粉佳荣酒庄也曾尝试设立了16家直销店，在福建、广东、东北等地销售。“价格低了，经销商利润低、不接受；价格高了，消费者不买账，销量又上不去”；“外地经销商来宁夏采购，包吃包住，最后问到何时进货，却又转向别家”；“市场竞争激烈，进店销售，就要首先铺货赊销。可当首批货卖完，该出资进货时，许多门店为了不占压资金，又会选择其它红酒免费赊销”……尽管酒庄酒在国内外获奖不断，可销量远远无法消化产量。

---


# 酒庄“吃钱”，投资长达10年

产出无法变现，但酒庄的资金投入却不能间断。

根据测算，红粉佳荣每年仅人工成本支出就高达1500万元，以维系酒庄必须的葡萄冬季埋土、春天出土，剪枝、采摘等；每年用于浇水灌溉的水电费上百万元；此外还要高价聘请酿酒师……葡萄酒卖不出去，库存高达两千多吨，超过原有容量一倍以上，还得另行投资扩建储罐。“没想到酒庄如此‘吃钱’，是一个无底洞。”马九虎粗略算来，这些年资金投入源源不断，整个酒庄的投入已有五六亿元。

2017年后，煤炭产业政策调整，马九虎在榆林的煤矿采矿权被收回，多家煤炭货站也被迫卖出。没有外来资金的输血，红粉佳荣酒庄日常经营开始举步维艰。

今年春天，红粉佳荣酒庄竟连葡萄出土上架的人工费也无力支付，马九虎只好紧急借钱，才得以维持酒庄正常运营。今年疫情使酒庄的经营雪上加霜，1—9月酒庄销售尚不足100万元。“现在酒庄只好以低于成本的价格卖掉部分葡萄、葡萄酒，来勉强支撑现金流，”马九虎的弟弟马忠理负责酒庄的田间管理，几年下来皮肤已晒得黝黑、一身风尘。他坦言，当初只看到末端暴利，没有看到整个产业链涉及农业、工业、服务业，如此复杂。

红粉佳荣酒庄的困境，是宁夏相当数量酒庄的缩影。

宁夏贺兰山东麓日照充足、昼夜温差大、砂石土壤透气性好，适合优质葡萄的生长。宁夏现有酒庄210多家，年产葡萄酒1.3亿瓶，综合产值达260亿元。吴忠是宁夏最大的产区，葡萄种植面积和葡萄酒产值约占整个宁夏的一半。

一位长期负责该产业的官员介绍，宁夏葡萄酒产业最初兴起于1998年；从1998年到2008年，宁夏葡萄酒产业起步，只有个别酒企在投资；从2008年至今，全国各地的投资商纷纷前来，葡萄种植面积、葡萄酒产值大幅提升。这其中既有张裕、轩尼诗等国内外顶级酒商，也有诸多煤老板、油老板、房老板等跨界投资者。

投资葡萄酒庄是一个重资本、长周期的产业。葡萄从种植到挂果须3年，期间没有任何产出；5年后，葡萄才能达到一定品质；在橡木桶陈酿也要两三年；再用两三年的时间打市场、创品牌……一个葡萄酒庄从投建到正常运转，至少要在十年以上。葡萄种植属于农业，投资周期长；中间酿造属于轻工业，有着一系列工业标准、食品标准的约束规范，资金、设备、人员投入是固定的，一个酒庄必然会沉淀大笔资金。“这对急于赚快钱、追求暴利的跨界投资商，无疑是一个漫长的过程，投资风险极大。”上述官员指出，葡萄酒庄是一个典型的三产融合发展的产业，而跨界投资者对产业有感情、懂技术、会运营的很少，尤其是末端的销售，已成了宁夏许多酒庄发展的主要瓶颈。

---

# 销售困境，一箱酒卖一瓶酒的价

不仅仅是跨界而来的“煤老板”“油老板”“房老板”，宁夏部分专业化较高的酒庄，也同样面临着葡萄酒滞销的困境。

从2011年起，宁夏自治区政府提出以“小酒庄、大产区”的模式发展葡萄酒产业。葡萄酒产地在宁夏，市场却在数千里外的沿海地区，“小酒庄”往往无实力全国营销。结果宁夏葡萄酒品质虽高，品牌知名度却低，定价虽高，却往往有价无市。

维佳妮酒庄就是宁夏“大产区”中“小酒庄”的典型代表。该酒庄规模不大，葡萄种植面积仅有500亩，每年产量10万瓶，一直以做精品酒庄而小有名气。

维佳妮酒庄副总经理段成春介绍，维佳妮从2006年开始种植葡萄，是整个宁夏产区葡萄品质最高的酒庄之一。去年，宁夏葡萄市场价格4元多/千克，而维佳妮的葡萄却能卖到16元/千克，是市场价的3倍以上，且供不应求。每年8月，葡萄尚未采摘就会预售一空。

葡萄酒素有“七分种植，三分酿造”之说。维佳妮采用传统工艺酿造，葡萄酒的品质在宁夏也被认为高出一般酒庄。其最低的一款酒售价598元/瓶，超出了当地多数葡萄酒。

可段成春坦言，维佳妮也一样饱受滞销的困扰：有着高端酒的价格，却无高端酒的品牌知名度，在北京、上海、广东、福建一带依靠少数经销商以品鉴会形式推广，约占总体销量的45%，其余均是前来旅游、考察的散客销售。今年受疫情影响，酒庄出货量不足往年三分之一。

按照500亩的种植面积，如果将葡萄尽数酿酒，维佳妮酒庄不但无力销售，还得追加投入、扩建储罐，资金链就有断裂之虞。所以，酒庄只得每年出售一半葡萄，尽快回笼资金，维持运营；一面主打高端产品，专做精品酒庄。

一位吴忠市相关官员坦言，以吴忠为例，40家建成酒庄，只有十多家真正盈利，不到20%。这位官员认为，盘活现有酒庄资产，是当下宁夏发展葡萄酒产业的关键。

2020年疫情突发，使本就经营困难的酒庄雪上加霜。一位当地业内人士解释，春节是消费旺季，节前各酒庄都将产品发到了各地经销商手中，可疫情突发后，经销商既无法销售，也无处储存，纷纷要求退货。吴忠一家酒庄原本一瓶葡萄酒120元，一箱6瓶，最后被迫以199元/箱赔本处理，一箱酒几乎只卖了一瓶酒的价格。

吴忠一位官员介绍，今年春天，吴忠不少酒庄的酒发不出来，也卖不出去，部分连葡萄出土、上架的人员工资都难以支付。直到5月份以后，因国外葡萄酒难以进口，各酒庄经营才普遍开始好转。

根据吴忠市对辖区酒庄销售的统计，去年1-8月，吴忠葡萄酒销量277万瓶酒，今年同期只有69万瓶。

一位葡萄酒市场销售人士坦言，宁夏产区的葡萄酒价格普遍高于进口酒，后来政府变“小酒庄、大产区”为“大酒庄、大产区”的发展思路，就是试图引导企业扩大规模，使酒庄变成酒厂，降低售价，与外界接轨、与市场同步。

---

# 煤老板做酒的时代过去了

过去，煤炭曾是宁夏传统支柱产业，煤炭产值占全部工业比重两成以上。如今，当地政府已普遍认识到，“一瓶优质葡萄酒的价值大于一吨煤的价值”：葡萄酒产业链长、横跨一二三产，提供就业岗位多，煤炭多是卖资源，容易坐吃山空；煤炭是不可再生资源，产业对环境污染大，葡萄越是老藤、品质越高，有利于改善环境，可持续发展；并且葡萄酒是国际通行商品，能够像法国波尔多一样提升宁夏在国际上的地位与形象。

目前，宁夏葡萄产业年综合产值由5年前的20亿元增加到260亿元。在许多政、商界人士看来，葡萄酒产业发展已关乎整个宁夏经济的转型和产业结构的升级，突破现有市场瓶颈则是实现良性发展的关键。

近年来，宁夏自治区政府对于葡萄酒产业扶持力度远超国内其他地区：对新建酒庄基地一次性补贴1500元/亩；低产园改造1000多元/亩；对在宁夏以外举行推介会，根据范围和效果给予补贴、奖励……

与此同时，各级政府开始帮助葡萄酒企业进行推广——在东部各大城市设立40个农产品营销中心，拿出几千万元进行补贴销售；不定期组织宁夏各酒庄在福建、江苏、北京、广东等地联合推广；同时，政府主导创立了“贺兰红”葡萄酒共享品牌，并授权西鸽酒庄等当地龙头企业使用。

西鸽酒庄庄主张言志，原是澳大利亚富邑集团旗下奔富品牌经销商。2017年开始，张言志投资3亿元、收购2万亩葡萄园，建成了宁夏贺兰山东麓产区精品葡萄酒生产规模最大的西鸽酒庄，用进口渠道销售自产的葡萄酒。

张言志介绍，十年做进口酒的经历，手头上积攒了500个区域大销售商，以往的销售渠道让西鸽酒庄在2019年开庄第一年就卖出3000万元，2020年截至5月份酒庄获得了2.99亿元的订单。

同样是销售出身的类人首酒庄董事长冯清，则把酒庄做出了另一番景象。十年前，冯清开拓线上线下双渠道，目前线上销售已占总收入的一半；线下设在全国的门店共有6000多家，一半在宁夏，一半在全国各地。

类人首的产品涵盖从三四十元到上千元的葡萄酒，甚至能够根据市场需求，在短时间调制新品。有一次，电商经理汇报，年轻女性客户反映喜欢甜度较高、果香芬芳的葡萄酒，冯清在半个月内调制出一款桃红葡萄酒，获得了大量的复购；南方经销商反馈，当地吃海鲜更适宜口感轻柔的葡萄酒，类人首快速反应、推出新品；有时客户需要定制个性化酒标，只要达到一定购买量，就能满足客户需求……

每天，冯清时刻关注网店的数据流量——进店人数多少，进店时间多长，转化率高不高，回头客多不多。一旦业绩下滑，立刻考虑推出哪一款产品降价引流。“并不是给一款优质的产品取个名字就叫品牌，定个高价就能让市场认可。”在冯清看来，十多年前，国内优质产品尚供不应求；可如今洋酒不断涌入，中国市场进入全球化竞争时代，仅凭产品优质已无法立足。一个酒庄的健康运行，是要产品走向市场，让资金来源于市场，形成良性的生态闭环，关键是真正让产品符合市场需求，而宁夏多数酒庄产品线较少，有的仅有两三款。

对于很多酒庄国内外获奖不断却连年滞销，冯清指出，“葡萄酒七分种植、三分酿造”，宁夏产区有着公认的品质，但相当一部分产品定价太高，严重脱离市场。

他给记者算了一笔账：一瓶葡萄酒的成本大致包括种植成本和冬埋费用，每亩葡萄种植约需10.3-10.6个工人，按照每个工人120元至150元计算，人工成本共计1650元，加上水电、肥料等成本，约在2500元左右，按一亩地产400瓶酒计算，经过橡木桶陈酿，加上酒瓶、酒塞与包装，每瓶酒的成本不过二三十元，加上部分渠道费用，性价比完全可与国外葡萄酒抗衡。“可是，许多酒庄投入了大笔资金，总想尽快收回投资，往往定价数百、上千元/瓶，追求十多倍甚至几十倍的利润。”冯清指出，高端化引领，不是说一个产区所有产品都要高端化。进口酒和国产酒本质上都是商品——经销商关注的是品质好不好，能否获利；消费者关心的是性价比如何。过高的定价，在经销商看来，是拿着高额的终端零售价在给酒庄打工，不会用心做市场，消费者更不会买账。

中国食品工业协会葡萄酒果酒专家委员会秘书长杨强指出，目前部分企业跑偏，过分强调高端化、专业化、场景化，使大众望而却步，自身市场也越来越萎缩。“葡萄酒就应该让人先喝起来，促进大众消费，才能推动产业与经济的双循环。”

事实上，中国超市中，进口葡萄酒零售价最低只有40元/瓶左右。中国本土产品在进口酒面前，反而难有价格优势。

像冯清、张言志这样拥有渠道资源的投资者，开始受到宁夏各级政府的青睐与扶持。一位吴忠市官员表示，以前，地方政府招商，来者不拒。如今，面对一无持续投资实力，二无行业背景资源，只有一腔热情、赚快钱的投资客，开始婉拒。在这位官员看来，最好能招到大财团的投资，或是本就有葡萄酒销售渠道资源的客商。

近年来，宁夏产区吸引了美的集团、正大集团、董明珠、郭广昌等投资商频频到访。这位官员表示，过去那种“煤老板”“油老板”“房老板”买一块地、靠自身关系往外销的时代过去了，葡萄酒产业全面升级即将到来。