---
title: The Myth of the Gender Wage Gap
author: Christina Hoff Sommers
date: '2020-11-01'
slug: '82'
categories:
  - Translation Articles
tags:
  - Propaganda
  - Politics
  - Economics
---

[Source](https://www.youtube.com/watch?v=1oqyrflOQFc)

Women in the United States and in Western Europe are the freest and most liberated in human history. In many ways they are not merely doing as well as men, they are doing better. Women's emancipation is one of the glories of Western civilization and one of the great chapters in the history of freedom. So, why then are those in the women's movement, such as the leaders and members of activist groups like the National Organization for Women, the professors in Women's Studies departments at our colleges, and many women in the media, why are they still so dissatisfied?

These feminists hardly acknowledge women's progress. Yes, they concede, that some advances have been made, but the fact that most women reject their activist brand of feminism and think of themselves as free is, for this crowd, proof of just how entrenched patriarchy and inequality truly are: women are so oppressed, they don't even know it.

Year after year these activists make claims about women and violence, women and depression, women and eating disorders, women and workplace injustice -- to support their views. Over the years, I have looked carefully at many of these claims. What I have found is that much of the supporting evidence, mostly victim statistics, is misleading and often flat out wrong. Consider the issue of the so-called gender wage gap. How many times have you heard that,
for the same work, women receive 77 cents for every dollar a man earns? This charge is constantly repeated by feminist activists and their supporters, yet it is so deeply misleading as to border on outright falsehood. The 23-cent gender pay gap is simply the difference between the average earnings of all men and women working full-time. It does not take account for differences in occupations, positions, education, job tenure, or hours worked per week.

Now, wage-gap activists in groups like the American Association of University Women or the National Women's Law Center they say, no, no -- even when you control for these factors, women still earn less. Well it always turns out that they have omitted one or two crucial data points.

Take the case of doctors. On the surface, it looks like female physicians are clearly victims of wage discrimination -- they appear to earn less for the same work. But dig a little deeper beneath the surface and you find that women are far more likely than men to enter lower paying specialties like pediatrics or family medicine than higher-paying cardiology or anesthesiology. They are also more likely to work part time. And even women who work full time put in about 7 percent fewer hours than men. Women physicians are also far more likely to take long leaves of absence -- usually to start a family. Now, there are exceptions, but most workplace pay gaps narrow to the point of vanishing when one accounts for all of these relevant factors.

Now, how do the women's advocacy groups react to this? They insist that women's choices are not truly free. Women who decide, say, to stay home with children, or to work fewer hours, or to become pediatricians rather than heart surgeons, are held back by "invisible barriers" or internalized oppression.

According to the National Organization for Women, powerful sexist stereotypes "steer" women and men "toward different education, training, and career paths" and family roles." But is it really social conditioning that explains women's vocational preferences and their special attachment to children? Perhaps in the pursuit of happiness, men and women take somewhat different paths. And, isn't it more than a little patronizing to suggest that most American women are not free? They're not self-determining human beings? And here is a common sense proof that the male-female wage gap is untrue. If it were really true that an employer could get away with paying Jill less than Jack for the exact same work, wouldn't most employers fire as many of their male employees as possible,
and replace them with females, and enjoy a huge market advantage?

As a regular campus lecturer, I routinely encounter students who have fully accepted the feminist propaganda. American college women are arguably the most fortunate, liberated beings on the planet -- yet in their feminist theory classes they are likely to learn that they are put upon and tyrannized by men. And the more elite the school, the more advanced the degree, the more likely they are to take such feminist propaganda seriously. But this doesn't have to continue. The time has come for young woman to take back feminism. Reform it. Correct its excesses. Repudiate the victim propaganda. Get rid of the "women are from Venus, men are from hell" storylines. Begin the arduous task of correcting almost three decades of feminist misinformation. Women who are plagued by workplace injustice or sexual violence will be best helped by truth and solid research -- not by hysteria and hype. And a final piece of personal advice for young women: appreciate, and make good use of, the unprecedented freedom that you have.