---
title: 我们信了很多年的这些事 居然都是谣言！
author: 中国日报网
date: '2021-08-11'
slug: '266'
categories:
  - Translation Articles
tags:
  - Propaganda
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

[Source](http://ex.chinadaily.com.cn/exchange/partners/82/rss/channel/language/columns/v0m20b/stories/WS60f681c6a310efa1bd663209.html)

# 迪士尼创造了米老鼠？

Walt Disney did not create Mickey Mouse. His close friend and collaborator Ub Iwerks did, though he was "denied credit" for creating this major piece of pop culture history. Iwerks came up with the character in 1928.

华特·迪士尼没有创造米老鼠。这一在流行文化史上举足轻重的动画形象是迪士尼的好友兼合伙人乌布·伊沃克斯创造的，但是伊沃克斯却被剥夺了著作权。伊沃克斯于1928年创作出了米老鼠。

# 爱因斯坦小学数学不及格？

Albert Einstein never flunked a math class as a child. When the adult Einstein was shown a newspaper article claiming he had, he replied, "Before I was 15, I had mastered differential and integral calculus." While Einstein achieved high grades throughout his childhood education, he "hated the strict protocols followed by teachers and rote learning demanded of students" at the schools he attended.

阿尔伯特·爱因斯坦小时候数学从未不及格。当有人让成年的爱因斯坦看这条假新闻时，爱因斯坦答道：“我在15岁前就已经掌握微积分了。”尽管爱因斯坦小时候学习成绩一直很优异，但是他讨厌那些学校里“老师遵循的条条框框和让学生死记硬背的要求”。

# 鲨鱼不会得癌症？

Sharks can get cancer too. The myth that they cannot is perpetuated partly by people trying to sell shark cartilage as a cancer treatment, even though it's been proven to be ineffective.

鲨鱼也会得癌症。鲨鱼不会得癌症的谣传挥之不去，一部分原因是有人试图将鲨鱼软骨作为抗癌药物来售卖，尽管事实已证明，鲨鱼软骨对于治疗癌症是无效的。

# 拿破仑是个矮子？

Despite the fact that his name has become synonymous with "angry short man," Napoleon Bonaparte was actually of average height for the time period in which he lived. His contemporaries described him as being 5'2", but the French measured height differently back in the day, so he was actually around 5'5". That made him just "an inch or so below the period’s average adult male height."

尽管拿破仑的名字已经等同于“愤怒的矮子”，但其实拿破仑·波拿巴在他所生活的那个年代身高算是中等水平。他的同辈人描述他的身高为5英尺2英寸（157厘米），但是法国人那时候测量身高的尺度和现在不同，所以拿破仑的实际身高应为5英尺5英寸（165厘米），也就“比同时期成年男性的平均身高矮了一英寸左右”。

# 人类只利用了10%的大脑？

According to a survey from 2013, around 65 percent of Americans believe that we only use 10 percent of our brain. But this is just a myth, according to an interview with neurologist Barry Gordon in Scientific American. He explained that the majority of the brain is almost always active.

2013年的一项调查显示，约有65%的美国人相信人类只用了10%的大脑。但这其实是误解。神经学家巴里·戈顿在接受《科学美国人》的采访时解释道，人类大脑的大部分基本一直都处于活跃状态。

# 牛顿是被苹果砸中了头才发现万有引力的？

Isaac Newton didn't discover gravity because an apple bonked him on the head. Rather, he witnessed an apple falling and wondered why objects always fall down instead of up or sideways, a thought that inspired his Law of Universal Gravitation.

艾萨克·牛顿发现地心引力并不是因为被苹果砸中了脑袋。事实上，他是在目睹苹果落地时忽然好奇为什么物体永远向下落而不是向上或向两边，这个想法启发他发现了万有引力定律。

# 右脑发达的人创造力更强？

People think that personalities whose right side of the brain is more developed tend to have good creative skills. And those who have their left side of the brain dominating tend to have better analytical and logical skills. However, recent research has completely destroyed this myth. Scientists analyzed the work of 1,011 brains. The participants were between 7 and 29 years old. They didn't find any signs of left or right hemisphere domination.

人们以为右脑更发达的人通常创造力更强，而左脑更发达的人通常分析能力和逻辑推理能力更强。然而，最近的一项研究彻底粉碎了这一误解。科学家分析了年龄在7岁至29岁之间的1011个人的大脑运作，结果没有任何迹象表明有人的左脑或右脑更发达。

# 梦游的人不能叫醒？

The presumption that sleepwalkers will exhibit wildly disturbing behavior when awakened is largely unfounded. Although some people may become aggressive, researchers have found that most of the time sleepwalkers are simply confused, disoriented, scared, or embarrassed. Waking a sleepwalker should be done as gently as possible to avoid such responses.

人们认为，梦游者被叫醒后会产生非常令人不安的行为，其实这是没有根据的。尽管有些梦游者被叫醒后会有攻击性，但是研究人员发现，多数时候梦游者被叫醒时只会感到困惑、迷失方向、惊恐或尴尬。为了避免这样的反应，叫醒梦游者时应该尽可能温柔。

# 蝙蝠是瞎子？

No, bats are not blind. Bats have small eyes with very sensitive vision, which helps them see in conditions we might consider pitch black. They don't have the sharp and colorful vision humans have, but they don't need that.

不，蝙蝠不是瞎子。蝙蝠有视觉非常敏锐的小眼睛，帮助它们在漆黑中看见东西。蝙蝠没有人类那样清晰而多彩的视觉，不过它们并不需要。

# 黑洞是个洞？

Black holes. Not really “holes,” but rather hugely dense objects with massive gravitational pull.

黑洞其实不是“洞”，而是能产生巨大引力的密度极高的物体。

 