---
title: 褚老师劝你别追热点
author: 褚明宇
date: '2022-02-27'
slug: '412'
categories:
  - Translation Articles
tags:
  - Insights
---

>战略定力特别重要，在读研究生的时候我都还没有领悟这一点。

问题：

褚老师，对于小米加入造车浪潮，想听听您的看法？


回答：

首先声明一下，这不会是一篇现在司空见惯的「公号体」文章——

又是语气宏大得不行假装专业的行业分析又是东拼西凑不懂装懂有关自动驾驶的所谓「技术流」又是头头是道的商务「战略」啊「布局」啊，而实际上呢就是两个月薪三千的半无业的「小编」为蹭热点被老板逼着连夜熬出来的「十万加」雄文。

如果你想看的是那些东西，那么抱歉，下面的内容不是你想要的，请到此止步。

今天，褚老师只讲个人偏见。

一些无系统、无理论、无战略、毫无「科技含量」的，随意的、纯个人的感想和偏见。

一、关于小米为什么会选择造车？

英特尔的创办人以及长期的领军者安迪格罗夫说过（原文懒得查了，凭印象复述哈）：

牛逼企业家的一个重要能力不是知道企业能做什么，而是知道不能做什么。

这句话说得极好，也是区分我们大多数「普通人」和格罗夫、盖茨们的一个关键而巨大的思维以及能力鸿沟。

普通人最爱采取的也是最坚信不疑的「战略」是——追热点。

就比如炒股吧，哪个股票前一段涨了上了新闻，你瞧着吧，大家都会一窝蜂地去买这个股票。一件事情「热门」本身就是自己一定要参与其中生怕落后的理由。

商务上也是这样，美甲店一热，大家都一窝蜂地去开美甲店，奶茶店看上去火了，于是又头脑一热一窝蜂地去开奶茶店。

当然，这种行为时髦的说法绝不是「追热点」，他们会搬出雷军老师的那句名言：「在风口上，猪也能飞起来」作为安慰自己的理论。

但可悲的是，大多数都把雷军这句话理解反了，雷军这么说并不是鼓励你去追热点，而是让你别去瞎凑热闹。

风口下面都是摔死的猪。

那么雷军这次「加入造车浪潮」，到底是不是「追热点」呢？

答案一会儿再公布啊，咱们还是先回到安迪格罗夫那句名言。给你举个例子吧——还是用炒股来帮助讲解。

这个故事有关我一个前同事 Dan Povey，这人是人工智能、语音识别领域世界级的天才，可以说一人改变了整个语音识别领域。不仅如此，这老兄还很神怪，如果你对他的经历感兴趣，下面是我的一篇旧文，欢迎偷窥。

链接：《Dan Povey 秘史》

今天不重复他跟的乌兹别克斯坦美女的爱情故事以及后来钻研「藏尸」的事迹，我想说的是有关炒股的一件小事。

某一年夏天（当时我们还都在纽约），当时「文艺复兴科技」这么一个本来圈外知道的人不多的公司刚上了新闻，原因大概是文艺复兴公司的 Bob Mercer  因为一年挣了十亿美元创了某种华尔街记录，上了《华尔街日报》。

记者问他成功的秘诀是什么？他说是当年带走了我司语音识别团队（也就是我和  Dan  所在的团队啊！）的骨干，把语音识别算法应用于炒股——好听的说法是量化对冲。

当然，Bob Mercer、Peter Brown 以及 Mukund Padmanabhan 这几位「前同事」离开我们研究小组的时候我和 Dan 还没有加入，哈哈生生错过了这么个发财的绝好机会。

不过，他在《华尔街日报》上这么一发言，那一段我们的电话就被各种猎头打爆了，还有就是，大家都跃跃欲试在午饭时表示，干脆我们自己也试试用我们的看家本事——语音识别各种算法——炒炒股吧。

你知道我这人，拖延症极其严重，这件事一直停留在午饭的闲聊里。

但是  Dan  这个人则完全不同，他极聪明同时又动手能力极强，凡事只要你能让他发生兴趣，他会立即动手尝试，并且很快做出让你吃惊的结果！

就在我们第一次午饭闲聊感慨垂涎了前同事的发迹之后没几天，Dan 已经自费购买了某种相当全面细致的金融历史交易数据，尝试并实现了一系列算法，在数据集上训练、测试、调试，把那天我们有一搭无一搭聊到的可能炒股想法全弄通了。

哈哈当然是利用上班时间以及们组用来做科研的一个几百台服务器组成的集群。

结论是：一个好消息，一个坏消息。

好消息是，只是经过这么短暂、迅速的实验，我们已经找到了可行的能挣钱的算法，而且，我们找到的最挣钱的几个算法（以及相应的金融产品）还是文艺复兴科技玩儿不了的！

是  Dan  比文艺复兴里几十个数学、物理奥赛金奖获得者更牛逼吗？

对这一点其实我不怀疑，但是这不是我们的算法文艺复兴玩儿不了的原因，问题的关键在于：

体量！

Dan 几天里发现的最挣钱的那几个算法（以及金融产品），或者说是「模式」吧，都只适用于小资金量的交易，一旦你大量资金入场，原有的可被利用的模式就不复存在，算法也就失效了。

对于小打小闹挣点儿钱这些算法可以，但是如果你是像文艺复兴那样上千亿美元规模的基金，这种所谓的「机会」根本就没有什么意义。

你说这是好消息啊，我们能玩儿，而大量化对冲基金玩儿不了，那岂不更好？

这就涉及到那个坏消息了，当时互联网炒股还没现在这么便宜，在美国的个人炒股平台  Ameritrade  每一笔交易好像是要交几美元的佣金。

如果你每笔交易很大，这个佣金按比例看就没那么糟糕，但是如果你每次就几百几千的交易额，再加上我们的算法依赖反复地、高频次的交易，佣金很快就变得相当可观，本来理论上的利润很快就被佣金吃没了。

所以，折腾了一通之后，Dan 还是决定放弃幻想，好好做研究——这么好的脑子没浪费在炒股上也是人类的福音啊。

好吧，言归正传，我想说的是，像小米这么一个六千六百亿美元市值，二〇二〇年销售额超两千四百亿人民币体量的公司，能对增长数字真地有意义的新「机会」比你想象的要有限得多。

你能挣钱——甚至是发财——的机会，对于小米来说，根本就不能对营收产生任何影响，尤其是高科技公司追逐的每年动辄百分之好几十的业务增长。

就算你开奶茶店能挣一亿，但这一亿的「新业务」对于小米的两千四百亿又有个屁用呢？

不排除有蠢货会说：开十家店挣一亿，那开一万家店不久能挣一千亿了？你瞧，这就是我费了半天的口舌讲上面那个炒股故事的原因。

抛开体量说「机会」是一种很业余的错误。

规模小的时候很挣钱的买卖，你不能傻逼呵呵地 extrapolate——认为扩大规模还是一样能挣钱。

怎么样，听着熟悉吧？很多餐饮企业老板都有这种错觉，比如当年的俏江南，比如现在的那谁还有那谁……​我就不点名了哈。

雷军显然不是那种人。

除了体量的限制而不能做的事情，还有很多所谓的「风口」是由于技术、企业「基因」等等原因而主动选择不去做的，这是安迪格罗夫那句名言的另一个、也是更考验企业管理者的一个维度。

接着拿餐饮企业当反例啊。不知道你有没有听说过「湘鄂情」这家企业，「湘鄂情」原来呢是一家挺成功的连锁餐饮企业，体量也不小，但是二〇一四年，老板决定转型，搞——云计算！

哈哈你听着像个笑话吧？这还真不是我编的！

那几年云计算是某种「风口」，很多不自量力的「猪」都以为自己能飞，连跟云计算八杆子打不着的开湘菜管的都跃跃欲试了，像万达这样的还能跟科技扯上一点的企业当然也不能落后啊，万达也大手笔地进军了云计算，还和我司高调搞了合作。

结局呢？

用一句美国人的套话吧：The rest is history.

安迪格罗夫说：

牛逼企业家的一个重要能力不是知道企业能做什么，而是知道不能做什么。

抱歉，王健林老师以及「湘鄂情」的二位老板，他们缺乏的能力以及栽跟头的地方恰恰就是不知道自己不能做什么。

安迪格罗夫牛逼！

但是，雷军不是这样的人。

过去几年里，风口换了一个又一个，你看雷老板都追过那个了？好吧，他也许半心半意地凑过云计算、区块链的热度，但是从我这么一个旁观者来看，他根本没有认真过！至少，绝不是湘鄂情万达那样傻乎乎地动了真感情的认真。

从这一点来看，雷军是个优秀、清醒得多的企业家。

这一次，我觉得小米是认真了。

但绝不是头脑发热的认真，而是一种深思熟虑之后的，甚至是不得不的选择和认真。

毕竟，新能源汽车这五年里会以每年超过  36%  的速度增长（IDC 预测），到二〇二五年会达到数万亿人民币级别的市场规模，这样的「机会」不管是从体量还是「基因」，都是小米必须不能错过的机会啊！

乔布斯刚去世的时候，美国畅销作家马尔科姆格拉德维尔在《纽约客》上写过一篇「悼词」，很多乔粉颇为不满，因为他说：

乔布斯不是个 innovator 而是一个 tweaker  ——不是一个「创新者」而是一个「改良者」。

我一直觉得这句话说得极好。

不知道你记不记得，在小米初期，雷军一度被称为雷布斯，那时候中国人知道马斯克的还不多，企业家都爱以中国乔布斯自居，哈哈搁现在，我想雷军说不定就会被叫成雷斯克了。

但是我还是觉得把雷军叫成雷布斯更为贴切，因为从根本上，雷军也是一个改良者而不是一个创新者。

果粉米粉乔粉们别弄错了，我这么说绝不带任何贬义，正相反，这是对雷军老师能力、风格的一种真诚的致敬。

也许米粉们不会承认，但是小米的产品，包括小米生态链产品，很多从设计上都「致敬」了当年苹果的设计，也许可以这么说，苹果的产品设计是一种 tweak，而小米是对这种 tweak 的 tweak.

说句心里话，虽然小米的起步是从「致敬」苹果开始，但是到了现在，小米的手机在很多方面已经比苹果优秀得太多，至少我本人吧，如果有朝一日要换手机品牌，我会考虑小米，但已经不会再考虑苹果。

言归正传，我想说的是，连一阶 tweaker 都要做车了，二阶 tweaker 怎么能不跟进呢？

说到一阶  tweaker，乔布斯的接班人 Tim Cook 是一个典型的知道不能做什么的优秀企业家，他掌舵这些年，苹果的营收、股价都创造了奇迹，但是他都推出了什么「新产品」呢？

苹果这些年的巨大成功恰恰就在于他没去追什么乱七八糟的风口，除了手机本业，他几乎只谨慎地推出了一个「周边」品类——  AirPods，一炮而红，成为苹果营收增长的新支柱。

而现在，苹果「谨慎地」开始做车了。

当一个谨慎的、知道不能做什么的优秀企业家决定要做一件事的时候，那么这件事成功的可能就要比风口的猪门要大得多。

雷军是这样一个企业家。

二、关于小米做车会不会成功？三、小米跟造车「新势力」们比，我更看好谁？……

本来想写个五、六点的，没想到写完第一点已经快四千字了，今天就写到这儿吧，好在新能源汽车这个话题一时半会儿不会消失，以后有机会再接着跟大家聊啊。

One more thing ...

二〇一九年，Dan Povey——就是那个世界级的天才技术大牛，毅然谢绝美国某企业的高薪聘请不远万里来到了中国工作。

当时从北大到阿里等等一系列顶级机构都给了他 offer，但是最后他选择了——

小米。

最后，小米跟造车「新势力」们比，我更看好——老罗。