---
title: 王健林的飞凡梦
author: Guanghua Mao
date: '2021-03-18'
slug: '161'
categories:
  - Translation Articles
tags:
  - Economics
  - Business
  - Investment
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

> 拼多多比飞凡网成立晚一年，飞凡网含着金汤勺出生，拼多多还是小米加步枪。王健林要是早一点读到 [Good News is Unplanned](https://guanghuamao.netlify.app/2019/12/23/good-news-is-unplanned/) 这篇文章就不用花这么多钱了。

# 飞凡网注销-腾百万散伙

2020.06.30

刚过去的618年中大促，我国几大电商巨头争相斗艳、使出浑身解数力争冲击新业绩，但与之同时，却又有一个电商平台宣告注销，低调的落幕，它就是曾经名噪一时的飞凡电商。


近日，万达旗下电商平台上海新飞凡电子商务有限公司正在计划注销，正在做最后的债务清算。依稀的记得王健林曾野心勃勃地表示 “万达将打造全球最大的商业 O2O 平台，万达未来最大价值的板块是飞凡，而且还将在 2020 年利润过百亿并上市”，而今却非常露骨地表现着，万达的电商梦已经彻底破碎，更别提上市了！

相信还有不少人还不知道飞凡电商究竟是干什么的，更别提在上面买过东西。据了解，8年前，网上购物算得上是“新鲜事物”，当时双11、618并非家喻户晓，但嗅觉敏锐的商界大佬们却意识到了互联网的神奇魔力，于是这一年万达电商平台雏形“腾百万”横空出世，而到了2014年万达正式官宣联合百度、腾讯共同出资50亿，飞凡网也就此诞生。

不过好景不长，到了2016年，百度、腾讯和王健林三个主体退股，马云口中的“凑拢班子”正式对外宣布散伙，随之变更为新飞凡，成为万达网科旗下全资子公司，虽说队伍散了，但王健林对“新飞凡”依然不死心且报以厚望，并还宣称将在2018年实现盈利，并于2020年上市，然而，如今2020年已经过去了大半年，也没能等来新飞凡上市敲钟的一天。


这么多年过去了，王健林始终没有让飞凡电商做出一点点的成绩，除了飞凡电商频繁换帅还可以引起媒体关注，几乎是被市场给遗忘了。据了解，在很长一段时间里面，飞凡电商更是连一个CEO都没有，相关人士爆料称，这是因为没有人可以达到王健林的标准，以老王的标准这个CEO可能只有马云或刘强东才能胜任。因此在飞凡仅存活了五年的时间里，光CEO就换了四个，在刘允担任新掌门之前，经历过龚义涛、董策、李进岭三任负责人。

三任CEO惨淡离职带来负面影响，飞凡网人事分歧限制团队建设

飞凡网在李进岭离职之后的情况不容乐观，甚至可以说其成立5年以来仍未真正走上企业发展的正轨。尽管，现在的非凡网由万达网络集团副总裁徐辉来主持大局，但这也凸显了万达在互联网方面无人可用的窘境。尤其是5年来三任CEO快速离职的现状更是标志着飞凡网进入到平台发展的阵痛期。

从200万到450万再到800万元，万达给飞凡网CEO开出的薪资越来越高，但这个位置却越来越难做。有着深厚技术经验的龚义涛和董策努力数年，只留下了一个进展迟缓的飞凡网。于是，曾深耕艺龙旅行网、芒果网、中旅总社等平台的李进岭便走马上任。但对于李进岭，万达内部却存在严重的分歧，有一种说法是高层认为其不懂零售，相信这种分歧和抵触也是逼走李进岭的原因之一。

而从更深层来看，万达内部的高层对飞凡网的人事问题远未达成一致，说明公司内部分歧严重，这势必将延缓飞凡网的整合和发展，更将错过追赶互联网潮流的最佳机遇。此外，800万年薪留不住CEO的消息将会为其带来负面影响，人心惶惶、人才流失将严重影响内部团队的战斗力。

飞凡网华丽数据真实性不足，飞凡APP缺乏电商基因体验滞后

从外部看，飞凡网在李进岭的治理下给出了一份华丽的答卷。据万达年报，2016年飞凡网活跃用户达到1.5亿，飞凡通会员8284万，新签合作大型商业中心1799家，中小商家10万家。但有报道指出，飞凡网的会员大多数通过连接万达线下的免费WiFi获取，活跃度并不高，很多业绩也是在万达的支持下认为做出来的，并不能掩盖飞凡网虚弱无力的事实。

其实飞凡网做的好与坏在飞凡APP上一目了然，互联网平台最重用户体验，而飞凡APP的制作还十分粗糙，不能对广大消费者产生足够的吸引力。虎嗅网就指出，“它是一个低配版的大众点评、美团、百度糯米”，并存在附近商家少、优惠券折扣低、品牌产品凌乱、热荐文章匮乏等等的不足。

可见，飞凡网不仅持续经历内部人事上的剧烈变动，而且仅有一个用户体验不足的飞凡App在支撑门面。线下对线上的无缝对接、线上操作的人性体验、O2O服务的便捷供应都是飞凡网目前尚未解决的问题，这充分说明飞凡网仍不具备核心的电商基因，较之与其对标的淘宝、京东还相去甚远。

“腾百万”解体带来相爱相杀，战略转型中仍未找到盈利模式

值得注意的是，飞凡网脱胎于万达在在2014年与百度、腾讯联合成立的万达电商，一期计划就投资50亿元，百度、腾讯各持15% 的股份，意图打造世界最大的O2O电商平台。对此，马云当时就指出这个“腾百万”不过是三方出资来对抗阿里巴巴的“凑拢班子”。果然仅仅两年后，腾讯、百度便推出了飞凡网的平台，士气汹汹的“腾百万”从此解体。

从互联网竞争的格局来看，腾讯、百度并非真正要帮助飞凡网做大做强，只是因为阿里巴巴势大不得不抱团取暖。事实上，“腾百万”三方之间也是竞争对手，如百度再次推出自己的电商平台“百度MALL”，腾讯与京东深度合作、团队作战，这种合作势必不能长久。而离开了百度、腾讯，几乎没有互联网经验的飞凡网不得不从零做起、自我探索，既消耗了资源又耽误了发展的时间，走了诸多的弯路。

最为关键的是，飞凡网对自身发展并无明晰的战略。最初，万达意图打造2C的“O2O电商平台”，但折腾几年后发现电商市场已经被淘宝、京东牢牢锁定，要想从中分羹难度异常之大。而现在，飞凡网提出走2B模式的“实业+互联网大型开放型平台公司”路线，打造面向中小商业地产的服务平台。这种战略转型虽有必要，但能否成功仍是个未知数。

总而言之，飞凡网的倒下也正式宣告王健林的电商之路失败。而现今的电商行业市场格局基本已定，不过仍在加速洗牌当中，一些曾经知名的电商平台相继倒下，同时又有许多新玩家入局。那么，下一个倒下的又是谁呢？

---

[Source](https://www.sohu.com/a/218327473_115280)

# 万达电商做砸了

2018.01.23


五年来执着于自己不擅长的，终究是错了。

话语间充满遗憾与惋惜，王健林还是从某种程度上承认了飞凡的失败。

在1月20日万达集团2017年年会上，王健林特别提到了飞凡的问题。他说，飞凡原本的方向有偏差。“过去总想着做规模，如果从一开始就只为万达广场、旅游度假区研发，可能早就整出名堂了”。

一项创立五年，仅负责人就换了4个的集团业务，到今天还在纠正方向的偏差。王健林的言外之意，不仅承认了飞凡过去定位的混乱，也将板子打在了网科所有人身上。

一个月之前，在“年底冲一波”失败后，这个曾被他寄予厚望、希望能跟马云扳手腕的业务，以一轮大裁员宣告自己五年探索的终结。

5年来，万达电商一直未见盈利，他称自己犯了一个错误，给曲德君太多钱。“如果当初少给点钱，定个投资上限就好了”。

在今年的年会上，王健林给网科制定了新的方向，要求他们把精力收回来，扎实做应用软件的开发。倔强的王健林依然强调，飞凡已经摸索出赢利模式，今年可以收支平衡。他还强调以前有前景的，还要继续做下去，绝不能把希望寄托在别人身上。

飞凡内部在过去5年里究竟经历了什么？为何会屡战屡败，直到今天还在调整方向问题？脱离王健林的发言稿和看似光鲜的数字，真实的飞凡，究竟是什么样？

## 转型困局

王健林做好了交学费的准备，只是没想到会一交就是5年。

万达做电商，最早要从2012年说起，那时候，凭借万达广场的早年成熟的商业地产模式，从2005年到2012年，万达在全国20个城市的商业数量急速扩充到上百个。这也帮助王健林在那一年成功登顶中国首富。

但也是自那一年起，线下零售业态遭受了来自互联网的巨大冲击，万达广场也不能幸免。如何对遍布全国的万达广场进行互联网化改造，成为了王健林新的思考重点。

万达集团大转型的序幕随即展开。王健林做了两个方向的尝试，一是主动调整业态，升级改造。影院、体育、儿童业态等由此而来，此后，万达收购了美国第二大院线，并以此为基础成立了文化集团。另一方面，万达广场开始吸收互联网的便利性等特点，希望提升线下业态的体验，飞凡的雏形由此而来。

但在实际进行的过程中，飞凡却遭遇了多次大的根本性调整。起初，王健林希望能够通过飞凡链接商户，甚至充当商户的POS机，后来，飞凡又开始与互联网金融挂勾，并与万达的传统金融业务相融合，去年底，他们又说自己要做像美团那样的“逛街指南”。

但这些几乎完全对立的方向却给飞凡带来巨大的定位问题，事实上直到今天，即便在今天的飞凡内部，也有很多人不清楚这个问题的答案。王健林对飞凡寄予厚望，但理想和现状存在巨大差距，这导致内部长期存在的数据造假现象。

根据万达2016年年报，飞凡将于2018年实现盈利，并于2020年上市。王健林2017年初曾表示：“集团已经批准飞凡的五年发展计划。2017是关键一年，今年任务完成，明年才有可能整体盈利。”

王健林对于飞凡的信心，事实上是来自于下属们汇报的“注水报告”。那一年，万达的工作报告里说飞凡的活跃用户达到1.5亿，飞凡通会员8284万。

但是实际上，飞凡的数据存在不小的夸大成分。一名飞凡场景项目的员工告诉界面新闻，他们对外推广时，会宣称有2亿活跃用户，日活千万级。他坦言“2亿用户其实就是2亿个手机号”。

而据易观千帆统计数据显示，2017年7月，飞凡APP的日活用户数据在7.4万-16.2万之间；2017年3月、4月、5月的月活用户数量分别为197.2万、113.3万、114万。这个数字甚至也高估了飞凡的活跃度，一位知情人士透露，飞凡接近真实的数据是：日活PV（Page View，即页面浏览量）30万，远远不是万达宣称的千万级。

彭博曾报道过飞凡用户数的问题。他们引用Questmobile的数据显示，截至2015年12月，飞凡的用户量达到513万，而2016年2月飞凡用户量下降了84%，至82.4万的低点。彭博当时说，飞凡的用户量与大众点评的4330万用户量相比存在极大差距，更不用说，据Questmobile数据显示，其竞争对手百度糯米的用户量为1.920亿。

类似的数据掺水，并非仅是过去一年的情况。对于数据注水，王健林其实早已察觉。知情人士透露，他曾经在内部表示，“我每次见到曲德君都叮嘱这个事，你谁都可以忽悠，你别忽悠我。”

连翻换帅，多次改版，王健林始终没有得到一个像样的东西。这磨灭了他最后的耐心，也成了导致此前那场大裁员的导火索。

## 失败的最后一搏

王健林曾期盼经过2017年之后，飞凡能实现盈利。在经历了5年的颠簸之后，王健林给了飞凡最后一个机会。

事实上，飞凡的这场溃败并非没有征兆。一名飞凡员工告诉界面新闻记者，2017年4月时，公司内部流传一个消息：6月公司会有一次非常重大的人事变动。

到了6月底，飞凡公司重新拆分了组织架构。万达网科成立了智慧生活事业群、数字商业事业群等，吸纳了原先飞凡公司的职能和项目。从那时起，智慧生活事业群接到一个重要任务——重新做飞凡APP。

这个重大调整与飞凡在2017年三、四月份的融资失败有关。2017年初，整个飞凡公司在努力筹备融资，界面新闻记者获悉，很多投资人及投资机构对飞凡以及整个万达网科进行评估，有投资机构在评估后表示“完全不知道飞凡在做什么”。

融资失败刺激了王健林，他下了一个决定：飞凡要进行重大调整，要明确方向。6月底的结构与人事调整结束后，飞凡APP研发团队于7月开始研发新版飞凡。

这是王健林给飞凡的最后一次机会。一名副总当时曾向员工表示，这次调整的目标就是在年底冲一波，这一波成了，接下来就能过得很好。如果不成，飞凡就会完蛋。

随后，新版飞凡APP在2017年9月上线，10月26日正式对外发布。当时万达网科副总裁、COO刘允在谈到飞凡APP的改版时，还向界面新闻表示，“我很兴奋，有一种使命感。”

然而一个月后，飞凡的员工几乎被裁光了。曾被万达寄予厚望的飞凡就这样“完蛋”了。界面新闻记者多方了解到，当时与IBM的谈判失利，可能是压垮飞凡的最后一根稻草。

刘允曾是前谷歌全球副总裁、大中华区负责人。2016年9月加入万达网科，担任副总裁以及COO。在刘允加入万达后，万达就开启了和IBM的合作。这一合作项目“万达公有云”本来是万达集团层面的合作，由万达集团信息管理中心副总经理冯中茜负责，她相当于朱战备的副手。王健林为了支持网科，把这个项目给了网科来操作。

但在刘允接手该项目后，双方的合作始终没有真正落地。

一名万达网科员工称，前段时间，刘允再赴美国和IBM谈公有云合作，最终谈崩了，引发公有云项目全线解散。同时随着刘允的失利，他负责的智慧生活事业群也受到了极大影响。

刘允是飞凡的第四任掌舵者。此前，万达电商经历过龚义涛、董策、李进岭三任CEO，在龚义涛和董策之间，万达集团CIO朱战备也曾临时接手电商项目几个月时间。

而与IBM的合作搁浅，新版飞凡上线后，用户数量也未见增长。新版飞凡没能完成“年底冲一波”的使命。

飞凡失利的同时，万达集团整体也正经历有史以来第二次大风波。海外投资的收缩，回A股的失败，让万达集团整体陷入被动，资金链也面临极大考验。在这种大背景下，王健林首先砍掉了失血最多的业务——万达城和万达酒店，虽然承载着文化板块转型的重任，也曾经喊出要打败迪斯尼这种豪言壮语，但这些项目后期的运转需要大量银行贷款支持，也是风险敞口最大的业务。

“飞凡是万达的出血点之一，多年来一直没能扭亏。本来到了年底没完成任务，就会有一波裁员，这是规定动作。这次只是下决心彻底甩掉了。”一位知情人士表示。

## “面向曲德君编程”

除了定位不清晰，飞凡管理上的弊病，基因上的不适，也是导致其失败的原因。

“编程一般是面向对象编程，而我们是‘面向总裁曲德君编程’，曲总怎么说，我们就怎么做，这证明了万达的执行力，但做不出什么互联网产品。”网科一位软件工程师向界面新闻记者表示。

一些员工认为万达网科跟他们待过的所有的互联网公司都不一样。互联网公司基本都以“快”为主，而在万达网科，最强调的是“向上汇报”，要先把计划做好了、向上汇报了、上面批准了才能行动。

上述工程师表示，在万达网科，基层员工不需要进行讨论，任务都是上面领导层指定好的。如果基层员工认为决策有问题，不想听话，那领导就会另拉一个部门来做。

他举了一个例子：此前飞凡要做一个内容发布系统，一段时间后，领导发现小组产品负责人不太听话，便另外成立了一个部门，再做一个内容发布系统，导致两个内容发布系统长期并存使用，直到后来这位领导发话，废掉其中一个系统，逐步迁移到另一个。在这样的氛围下，大多数人都学会了“闭嘴”。

在此之前，经历了连续多年的方向错误，王健林曾将希望寄托于“自己人”。

2016年底，万达开启一次全集团范围内的结构调整，互联网和金融被首次分开，新成立的网科集团，由曲德君挂帅。

曲德君是在王健林麾下效力十三年的老臣。过去在培育万达电商这件事上，王健林一直坚持高薪培育豪华高管阵容。龚义涛曾经担任谷歌总部电子商务部经理、阿里巴巴国际交易技术资深总监；李进岭则是原芒果网CEO，据传以800万年薪加盟万达电商。

选择了自己人掌舵之后，王健林还是不忘给曲搭配一个懂互联网的副总裁，也就是前谷歌全球副总裁、大中华区负责人刘允。曲德君习惯万达的高执行力风格，而刘允的思维则更互联网。万达繁琐的汇报机制以及自身重执行的工作模式，最终也拖垮了这家公司。

军人出身的王健林创办的万达具有集团军的特点，指哪打哪，模块化节点式管理，这在万达广场的快速扩张中起到了关键作用。但在互联网项目和创业公司中，个体的创造性极为重要，这是万达基因里没有的东西。

万达电商首任CEO龚义涛在离职一年多后也曾表示：“在万达，通常先是用PPT的模式向领导请示汇报，所有的事情都需要领导批准才能做，我们互联网企业出身的人没有这个习惯，我们的思维是发散型——想到哪里就说到哪里。”

界面新闻记者了解到，万达网科大裁员后，网科集团现任总裁曲德君或将离开网科，回到万达商管。曲德君的继任者有可能是万达集团副总裁兼信息中心总经理朱战备。

王健林希望万达网科能拓展新业务，在互联网领域占据一席之地，但“一切唯上”并不符合互联网行业的规律。万达成功依靠的执行力，反过来成为现在失败的直接原因。

一场大裁员接踵而至。目前，几百名被裁员工与万达网科的谈判陷入僵局，矛盾的焦点在于，万达网科强迫员工签下“主动离职协议”，协议中称，员工是因个人原因辞职，终止与公司的劳动关系，终止全部的劳动待遇，不发表对公司不利的言论。

对于万达来说，这是万达集团整体转型过程中一次竭尽全力的尝试。在世界范围内，都没有一家地产公司向互联网行业转型的成功案例，有很大的难度。但最终为失败买单的，不应该只是普通员工。

在1月20日的年会上，王健林否认了网传裁员6000人的说法，他称整个网科只有3000人，强调“他们还是开发了一些有用的东西，只是这些东西有培育期，还不能马上被资本市场接受”。

他甚至为飞凡制定了新的方向——万达网科今后要朝着线上线下融合的道路走，花精力搞自主研发的应用软件，并对所有科创企业、院校、研究机构、个人开放万达场景平台，要继续启动第二届创新加速器。

悬念留在了最后。王健林称，网科集团上半年内与世界级网络巨头的战略合作将落地。这次，又是谁会入局陪他打上一把？
